### ISSUE TITLE
Transmission Mac hung process accessing disk

### ISSUE THREAD

**Issue by prohtex** [transmission/transmission#272] opened 2017-05-10 06:34 UTC
I've been using Transmission Mac GUI for many years. I've always had issues with the GUI locking up (general unresponsiveness, beachballs) but this has improved in recent releases, so I moved to an external thunderbolt RAID and added more torrents (800 or so, each in the 20gb-50gb range). At any given time 95% of these are completed and seeding.

I've encountered 2 problems which I have not been able to resolve. First, when new torrents are added, the GUI goes through a very predictable series of hangs. I generally add 1-3 torrents at a time, using the "Display a window when adding" option. These populate in the main window, and sometimes begin to download. Then, there is a series of "hiccups" of intense disk activity on the external drive. These last 10-30 seconds, and cause all network activity to hang (all torrents stop seeding/downloading). Adding a few new torrents ALWAYS causes 5 or so of these "hiccups." I have the "keep incomplete files.." option set to a directory on the boot drive (internal SSD), so I don't understand why Transmission is seeking so aggressively on the external disk. There is always a hiccup when the download completes, but this I understand (the file is being moved to the external disk). But why when adding as well? Adding new torrents is a painful stop and go process and usually only resolves after 10 minutes or so.

More crucially, after about a week or so, Transmission takes down the whole system. First, all network activity in the application stops. No seeding, no downloading. The external drive shows light activity. Transmission indicates all torrents are seeding fine, yet nothing is happening. The application is responsive, and the external disk can be accessed fine with the Finder and command line tools. Nothing seems amiss, yet some Transmission process is hung accessing the disk. Attempting to quit Transmission causes it to hang. Attempting to spindump Transmission in Activity Monitor causes Activity Monitor to beachball. Transmission can be force quit. From here, things get ugly. Attempting to unmount the volume in the Finder or with "sudo umount -f" causes the system to hang. First, the disk icon goes grey in the Finder. Then, the Finder beachballs. The dock beachballs. The terminal will work for some time, and top shows kernel_task using resources. "sudo umount -f" hangs indefinitely. Attempting to reboot the system from the GUI or with "sudo reboot" initiates and then hangs on a black screen. This hang does not resolve and the only recourse is to hard power down the machine, while the hung process is still accessing the external disk.

I have reproduced this issue on 3 different machines (two Sierra, one, El Capitan), with 4 different enclosures and drives from 2 different manufacturers. I am very confident this is not an OS or hardware related issue. I'm happy to provide logs or to take other troubleshooting steps. Any help is much appreciated.

I have not yet tried to run Transmission as a daemon as I am pretty keen on the GUI, but would give that a go if necessary.

**Comment by mikedld** [comment] 2017-05-14 09:30
Would you be able to use a [nightly build](https://build.transmissionbt.com/job/trunk-mac/)? It would then help to get a number of `sample Transmission` (from command line) reports at the time of "hiccups" and "hung accessing the disk". There could also be reports created automatically by the system itself which could be found in Console (or /Library/Logs/DiagnosticReports and ~/Library/Logs/DiagnosticReports), but again they would [probably] only make sense if created during the use of the nighly build.

**Comment by prohtex** [comment] 2017-05-16 06:10
Hi Mike, thanks very much for your reply. I have some diagnostic reports in /Library/Logs/...cpu_resource, wakeups_resource and so forth. Where should I send them? I will switch to a nightly build and on the next hang try to gather a sample. I did try this once, and it hung with no ouput (same as trying to Sample Process in Activity Monitor).

**Comment by prohtex** [comment] 2017-05-18 12:53
I just collected a number of samples before, during, and after one of these "hiccups." I'd be happy to share them.

**Comment by mikedld** [comment] 2017-05-18 13:35
They shouldn't contain any personally identifiable information, so just upload them here.

**Comment by prohtex** [comment] 2017-05-24 15:45
Ok, here they are. I took these before, during, and after the hangs.

[Transmission_2017-05-17_023003_Nkx5.sample.txt](https://github.com/transmission/transmission/files/1026145/Transmission_2017-05-17_023003_Nkx5.sample.txt)
[Transmission_2017-05-17_023044_LzMc.sample.txt](https://github.com/transmission/transmission/files/1026147/Transmission_2017-05-17_023044_LzMc.sample.txt)
[Transmission_2017-05-17_023315_uqcJ.sample.txt](https://github.com/transmission/transmission/files/1026148/Transmission_2017-05-17_023315_uqcJ.sample.txt)
[Transmission_2017-05-17_023330_jsau.sample.txt](https://github.com/transmission/transmission/files/1026146/Transmission_2017-05-17_023330_jsau.sample.txt)

**Comment by mikedld** [comment] 2017-05-24 17:40
Those aren't taken from a nightly build :(

**Comment by prohtex** [comment] 2017-05-24 21:39
Sorry, I did have this same issue with the nightly, but wasn't able to grab the spindump. I've since moved the majority of my torrents to Deluge temporarily to mitigate this issue and also #273. I could reload everything and repeat it with the nightly but that's a big process. There's nothing useable in these logs?

**Comment by mikedld** [comment] 2017-05-30 06:12
Not entirely, but decoding "???" (instead of function names) you could see there requires debug symbols for a specific version and I don't have those which complicates things...

**Comment by prohtex** [comment] 2017-05-30 06:18
These were taken with 2.92 (14714). I have 924 active torrents totaling around 20tb. When I can, I'll migrate everything over to the nightly and take some more samples. I've seen this "hiccup" in every version of Transmission Mac I've used for about as long as I can remember. It's never been an issue for me before, because I've never had so many active torrents. It seems that as the volume of seeded torrents grows, the length and severity of the disk hangs increases.

**Comment by prohtex** [comment] 2017-06-16 00:25
Also wanted to mention that my internet connection is pretty fast - I regularly get 50mb/sec down

**Comment by tclementdev** [comment] 2018-09-07 19:33
@mikedld I'm having the exact same issue as described here. I have samples too but no symbols. What is the process to resolve those symbols? Can we download the dsyms for released builds somewhere?

**Comment by mikedld** [comment] 2018-09-07 19:44
@tclementdev, starting with 2.93 DSYMs are at https://github.com/transmission/transmission-releases/ along with the binary packages, e.g. [Transmission-2.93-dsym.zip](https://github.com/transmission/transmission-releases/raw/master/Transmission-2.93-dsym.zip), [Transmission-2.94-dsym.zip](https://github.com/transmission/transmission-releases/raw/master/Transmission-2.94-dsym.zip).

**Comment by tclementdev** [comment] 2018-09-07 22:02
@mikedld Thank you. So here it is, there are two seemingly stuck threads:

    -[Controller openMagnet:] (in Transmission) (Controller.m:1138)
    -[Torrent initWithMagnetAddress:location:lib:] (in Transmission) (Torrent.m:174)
    -[Torrent(Private)     initWithPath:hash:torrentStruct:magnetAddress:lib:groupValue:removeWhenFinishSeeding:downloadFolder:legacyIncompleteFolder:] (in Transmission) (Torrent.m:1701)
    tr_torrentNew (in Transmission) + 167
    tr_lockLock (in Transmission) + 18
    _pthread_mutex_lock_slow
    _pthread_mutex_lock_wait
    __psynch_mutexwait

and

    ThreadFunc (in Transmission) + 15
    libeventThreadFunc (in Transmission) + 141
    event_base_loop (in Transmission) + 786
    bandwidthPulse (in Transmission) + 167
    tr_bandwidthAllocate (in Transmission) + 251
    phaseOne (in Transmission) + 140
    tr_peerIoFlush (in Transmission) + 399
    canReadWrapper (in Transmission) + 182
    canRead (in Transmission) + 1087
    peerCallbackFunc (in Transmission) + 367
    tr_torrentGotBlock (in Transmission) + 288
    tr_torrentCheckPiece (in Transmission) + 22
    tr_ioTestPiece (in Transmission) + 129
    readOrWritePiece (in Transmission) + 891
    tr_fdFileCheckout (in Transmission) + 254
    tr_sys_file_close (in Transmission) + 18
    close

It's very hard to make sense of it (at least for me) while reading the sources, maybe there's a lot of inlining. So the first one is the main thread, it's the one hanging the GUI. The second one, I don't know why we're stuck on this close (or why it would be called so often), also I don't know if the same lock is held between these two stacks. One interesting thing to note is that when waiting long enough (a couple of minutes), the app ends up unstucking itself, I do not need to force quit, so this is only a temporary deadlock that we're looking at.

**Comment by ckerr** [comment] 2022-01-19 23:03
Closing as a dupe of https://github.com/transmission/transmission/issues/2462. I realize this ticket was filed before 2462, but there are so many overlapping tickets at this point that it makes sense to start with a new "big picture" ticket.

**Closed by ckerr** 2022-01-19 23:03 UTC
