### ISSUE TITLE
Torrent added via watch directory doesn't auto-verify files properly

### ISSUE THREAD

**Issue by plotski** [transmission/transmission#5754] opened 2023-07-08 11:28 UTC
### What is the issue?

Steps to reproduce this issue:

1. Run transmission-daemon with --watch-dir.
2. Create a torrent.
3. Move the torrent content file(s) to Transmission's download directory.
4. Copy the torrent to the --watch-dir.
5. Observe how Transmission verifies the first few files (or the single file if there is only one) to 0% while the rest of the files are verified to 100%.
6. Manually tell transmission-daemon to verify the file(s) again (e.g. with transmission-remote).
7. Observe how all files are now at 100% as expected.

If I add the torrent with transmission-remote, everything works fine and all files are immediately verified to 100%.

I've only tested this with the daemon.

Below is a Bash script that should demonstrate the issue.

```bash
demodir='/tmp/demo'
contentpath="$demodir/content"
torrentpath="$demodir/test.content"

transmissiondir="$demodir/transmission"
downloaddir="$demodir/downloads/"
watchdir="$demodir/watch"

pidfile="$demodir/pid"
configdir="$transmissiondir/config"

rpcport=5000
peerport=54321

mkdir -p "$transmissiondir"
mkdir -p "$downloaddir"
mkdir -p "$watchdir"

cleanup() {
    [ -f "$pidfile" ] && kill "$(cat "$pidfile")"
    rm -r "$demodir"
}

trap cleanup EXIT

run_transmission_daemon() {
    transmission-daemon \
        --pid-file "$pidfile" \
        --config-dir "$configdir/" \
        --download-dir "$downloaddir" \
        --watch-dir "$watchdir" \
        --rpc-bind-address 127.0.0.1 --port "$rpcport" \
        --peerport "$peerport" --no-portmap --no-dht \
        --paused
}

create_torrent() {
    local contentpath="$1"
    local torrentfile="$2"
    local downloaddir="$3"

    # Increasing the piece size (-s 32, -s 64, etc) increases the number of
    # files that are verified to 0% intially.
    transmission-create -s 32 -p -t 'http://localhost:1234/announce' "$contentpath" -o "$torrentfile" >/dev/null
    ln -s "$contentpath" "$downloaddir"
}

create_content_file() {
    local contentpath="$1"
    local contentsize="$2"

    dd if=/dev/random of="$contentpath" bs=1 count="$contentsize"
}

get_singlefile_content() {
    local contentpath="$demodir/singlefile_content"
    local contentsize="$(( 1024 * 1024 ))"

    create_content_file "$contentpath" "$contentsize" \
        && echo "$contentpath"
}

get_multifile_content() {
    local contentpath="$demodir/multifile_content"

    mkdir -p "$contentpath"
    create_content_file "$contentpath/a" "$(( 26 * 1024 ))"
    create_content_file "$contentpath/b" "$(( 755 ))"
    create_content_file "$contentpath/c" "$(( 35 * 1024 ))"
    create_content_file "$contentpath/d" "$(( 3 * 1024 ))"
    create_content_file "$contentpath/f" "$(( 9 * 1024 ))"
    create_content_file "$contentpath/g" "$(( 31 * 1024 ))"
    create_content_file "$contentpath/h" "$(( 11 * 1024 ))"
    create_content_file "$contentpath/i" "$(( 33 * 1024 ))"
    echo "$contentpath"
}

run_transmission_daemon &
sleep 1

# Add torrents via watch directory.
create_torrent "$(get_singlefile_content)" "$watchdir/singlefile.torrent" "$downloaddir"
create_torrent "$(get_multifile_content)" "$watchdir/multifile.torrent" "$downloaddir"

# # Adding the torrents via the RPC interface works as expected. All files are
# # at 100% after the initial automatic verification.
# create_torrent "$(get_singlefile_content)" "$demodir/singlefile.torrent" "$downloaddir"
# transmission-remote localhost:5000 --add "$demodir/singlefile.torrent"
# create_torrent "$(get_multifile_content)" "$demodir/multifile.torrent" "$downloaddir"
# transmission-remote localhost:5000 --add "$demodir/multifile.torrent"

# Wait for automatic verification to finish.
sleep 3  # Increasing this doesn't help

# Observe how some file(s) in the torrent are at 0%.
echo '### TORRENT FILES AFTER ADDING:'
transmission-remote localhost:5000 --torrent 1 --files
transmission-remote localhost:5000 --torrent 2 --files
sleep 1

# Verify again manually.
echo '### VERIFYING:'
transmission-remote localhost:5000 --torrent 1 --verify
transmission-remote localhost:5000 --torrent 2 --verify
sleep 3

# Observe how all files are now at 100%.
echo '### TORRENT FILES AFTER VERIFYING:'
transmission-remote localhost:5000 --torrent 1 --files
transmission-remote localhost:5000 --torrent 2 --files
```

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.3 (6b0e49bbb2)

**Comment by tearfur** [comment] 2023-07-11 03:06
Reproduced in `4.0.3` and `main` (8169d524eab8aeb5cf16be12182e83dde109ffd4).

Same behaviour even if the torrent is created with mktorrent instead of transmission-create.

**Comment by tearfur** [comment] 2023-07-12 08:54
@plotski It's simply because you linked the download directory *after* you created the torrent.

```bash
create_torrent() {
    local contentpath="$1"
    local torrentfile="$2"
    local downloaddir="$3"

    # Increasing the piece size (-s 32, -s 64, etc) increases the number of
    # files that are verified to 0% intially.
    transmission-create -s 32 -p -t 'http://localhost:1234/announce' "$contentpath" -o "$torrentfile" >/dev/null

    # Move this line before transmission-create
    ln -s "$contentpath" "$downloaddir"
}
```

Please close this issue if this solves your problem.

**Comment by plotski** [comment] 2023-07-12 09:51
I can confirm the fix. Thank you!

But I don't understand why this matters. If I translate this to a real world
scenario, it should work.

1. A and B have the same file.
2. A creates a torrent of that file.
3. B creates a symlink to that file in the download directory AFTER the symlink
   was created.
4. B gets the torrent from A and can verify and seed the file.

My guess would be that my script is doing something slightly different, but I
don't see it.

Also, why does it work if I add the torrent via the RPC interface instead of the
watch directory?

Can you elaborate or did you just figure this out by trial and error?

**Closed** 2023-07-12 09:51 UTC

**Comment by tearfur** [comment] 2023-07-12 10:58
I don't understand your "real world scenario", but at least for your script...

...it didn't work because Transmission can start to verify files before the symlink was created.
