### ISSUE TITLE
Qt6 Sorting doesn't work

### ISSUE THREAD

**Issue by meerfrau** [transmission/transmission#5436] opened 2023-04-22 20:01 UTC
### What is the issue?

Both transmission-qt 4.0.2 and git master fail to show any effect when I click on any sorting option. This also happens in compact view.

New torrents are added on the top of the list, but after a program restart they are at a random place.

I'm on Qt 6.5.0
```
	libQt6Widgets.so.6 => /usr/lib/libQt6Widgets.so.6 (0x00007f8b63000000)
	libQt6Network.so.6 => /usr/lib/libQt6Network.so.6 (0x00007f8b62e6b000)
	libQt6Gui.so.6 => /usr/lib/libQt6Gui.so.6 (0x00007f8b62400000)
	libQt6DBus.so.6 => /usr/lib/libQt6DBus.so.6 (0x00007f8b63cf8000)
	libQt6Core.so.6 => /usr/lib/libQt6Core.so.6 (0x00007f8b61e00000)
```

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.2+

**Comment by ckerr** [comment] 2023-04-22 21:25
Hi @meerfrau, thanks for reporting this.

> New torrents are added on the top of the list, but after a program restart they are at a random place.

This is a duplicate of https://github.com/transmission/transmission/issues/155, so I'm going to close this ticket as a dupe. Thanks for reporting it though! I'd rather a bug get two tickets than zero tickets :smile_cat:

**Comment by meerfrau** [comment] 2023-04-22 22:04
Is #155 really covering my first complaint? I'm really not annoyed by the jumbling between sessions, but much more that _no sorting is possible_.

**Comment by ckerr** [comment] 2023-04-22 23:31
@meerfrau sure, a video would be great, thanks :bow:

**Comment by frozenpandaman** [comment] 2023-04-24 06:52
> @meerfrau sure, a video would be great, thanks 🙇

@ckerr Seems related to #5321 where I provided a video.

**Comment by frozenpandaman** [comment] 2023-05-09 04:04
@ckerr It's not *only* ordering between sessions, or I wouldn't necessarily describe it as such, but this re-ordering bug (shown in the GIF below) may be a result or effect of that one.

![](https://user-images.githubusercontent.com/7245874/228434021-d7c91de3-cbc0-448d-b45a-9041fb3bcae4.gif)

**Comment by meerfrau** [comment] 2023-05-09 10:10
@ckerr With git main the issue is gone. Thanks!

**Closed** 2023-05-09 17:11 UTC
Labels: bug, needs clarification, scope:qt, needs confirmation, type:ui
