### ISSUE TITLE
4.0.0-beta.1 [macOS] Transmission won't resume torrents from prior versions

### ISSUE THREAD

**Issue by CyberSkull** [transmission/transmission#3907] opened 2022-10-08 11:10 UTC
4.0.0-beta.1 on macOS 10.15.7 won't resume the torrents created by older versions of Transmission (I've been using the nightly builds). It will resume torrents it created, but the rest won't resume. Resuming torrents created in version 4 can take a minute or two for the progress bar to turn green and the resume button to disappear.

**Comment by Coeur** [comment] 2022-10-08 15:00
Possibly a duplicate of what got fixed with #3889. Can you try a newer nightly?

**Comment by CyberSkull** [comment] 2022-10-09 08:28
Seems to be fine in bfe6953822.

**Closed** 2022-10-09 15:22 UTC
