### ISSUE TITLE
Private info misplaced

### ISSUE THREAD

**Issue by jpmelko** [transmission/transmission#1337] opened 2020-06-24 21:29 UTC
see attachement (French Version)
This exists for a long time
![Capture d’écran 2020-06-24 à 23 28 06](https://user-images.githubusercontent.com/29252675/85629601-742f3800-b672-11ea-8048-b3868d7ea307.png)

**Comment by ckerr** [comment] 2020-07-27 23:58
Closing as a duplicate of https://github.com/transmission/transmission/issues/1362

**Closed by ckerr** 2020-07-27 23:58 UTC
