### ISSUE TITLE
Compile windows version running crashed

### ISSUE THREAD

**Issue by Judgegao** [transmission/transmission#7183] opened 2024-10-18 07:57 UTC
### What is the issue?

Install transmission for windows through source code compilation

Refer to the official documentation: 
`https://github.com/transmission/transmission/blob/main/docs/Building-Transmission.md#on-windows`

The transmission version I compiled is 4.0.3

After successful compilation, the binary is generated in the `build` folder 

![微信截图_20241018155517](https://github.com/user-attachments/assets/ae2f0e26-e995-42e7-8a17-bd85691d3787)

Double click run

exe file location:`D:\code\transmission\build\qt\Debug\transmission-qt.exe`

**The program crashes frequently**

![微信截图_20241018154556](https://github.com/user-attachments/assets/d24e497b-68b7-4a8b-9041-d2f07f514240)

I had this problem on both windows10 and windows11

Hope to get help and answers!!!
Thank you！

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.3

**Comment by nevack** [comment] 2024-10-18 08:11
Please remove copyright content

**Comment by Coeur** [comment] 2024-11-05 13:50
Duplicate of #7182.

**Closed by Coeur** 2024-11-05 13:50 UTC
