### ISSUE TITLE
Unable to save resume file: Too many open files

### ISSUE THREAD

**Issue by Bubblemusic** [transmission/transmission#4670] opened 2023-01-26 12:51 UTC
### What is the issue?

Synology DS218J -(DSM 7.1.1-42962 Update 3) -the error appears every 3-4 hours after starting any task (regardless of 1 or 100 active torrents)

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

3.00-20

**Comment by ckerr** [comment] 2023-01-26 15:01
Duplicate of #3677

**Closed by ckerr** 2023-01-26 15:01 UTC
