### ISSUE TITLE
non-magnet torrents disappeared when upgrading from 3.00 to 4.0.0

### ISSUE THREAD

**Issue by michaelkaufman** [transmission/transmission#4754] opened 2023-02-08 18:59 UTC
### What is the issue?

I keep torrents i may want to download paused and undownloaded. Some of them are magnets that have not even connected to start the download. 

When I upgraded to Transmission 4 I opened my client and there are many missing torrents. More than half that I had queued up. 

Why is this and where are they?

I used groups.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4

**Comment by ckerr** [comment] 2023-02-08 19:28
Missing magnet links is a duplicate of https://github.com/transmission/transmission/issues/4295.

**Comment by michaelkaufman** [comment] 2023-02-08 19:32
Not sure why you closed this. I downgraded and they did not come back. Also they were not all magnets @ckerr

**Comment by ckerr** [comment] 2023-02-08 19:46
@Coeur can you PTAL? I don't have access to a  mac to help @michaelkaufman out with this

**Comment by Coeur** [comment] 2023-02-08 20:13
I'm afraid I don't have anymore a spare setup to conduct research on Transmission 3 -> Transmission 4.

And if the issue is "most of" them but not all of them, then there may be unknown conditions to reproduce the issue (magnets without metadata? BitComet torrents? Filenames with unicode? Complete or incomplete downloads? etc.)

**Comment by michaelkaufman** [comment] 2023-02-09 00:47
I was able to find the missing torrents in  ~/Library/Application Support/Transmission but I have to go through and organize them in groups again.

**Comment by am0** [comment] 2023-02-10 01:06
Acknowledging that this happened to me as well. Thankfully had a Time Machine backup, so keeping with 3.00 until I can copy them all to a list and reimport.

May I be so bold to suggest putting a warning on the upgrade notice to back up all Magnet links before doing so? Handbrake does this with its queue so it's not uncommon practice.

**Comment by pinta-vodki** [comment] 2023-02-10 13:43
This is a real problem. I had lots of magnet links saved for later download (so that Transmission doesn't reserve the space it needs by starting a download). All of them were gone after upgrading. The ~/Library/Application Support/Transmission/Torrents folder gives an error when opening older torrents.

Downgrading to 3.0 is not easy for me, because I don't know how to build an older version. The one surely safe download I could find was 2.94 on MacUpdate. I did not restore old magnet links, and the torrents that were completed/in progress all reset to 0%. Fortunately, that version was able to open the files in the Application Support folder, but adding them all back was a real hassle. 

Will try Time Machine restore later today when I get home, but this surely needs to be fixed. I imagine many users will not bother themselves with registering on forums/github to comment, but will be quite frustrated.

**Comment by JustinTArthur** [comment] 2023-02-10 15:55
@wankxxx @am0 and @pinta-vodki, transmission/transmission#4295 is the ticket for magnet-driven downloads disappearing.

**Comment by ckerr** [comment] 2023-02-10 20:34
As @JustinTArthur said, 4295 is the previously-existing ticket for magnets disappearing.

I'm leaving this open since @michaelkaufman said that non-magnets also disappeared. I haven't seen that happen and (I think?) the rest of the comments in this ticket are about magnet links so I'm not  sure what to think about the non-magnet bug report.

**Comment by ckerr** [comment] 2023-02-10 20:35
I'm going to add labels and change the issue title to distinguish this from 4295.

**Comment by programatix** [comment] 2023-02-10 23:30
I encountered this issue as well. After upgraded to version 4 from 3, torrents went missing. I have to manually re-add all missing torrents.

**Comment by Coeur** [comment] 2023-02-14 04:26
The easiest way to move forward with this issue would be that someone encountering the issue visits `~/Library/Application Support/Transmission`, then finds there the torrent that has disappeared in 4.0.0 and shares it here for reproduction.

Alternatively, in Transmission 4.0, open the logs window (cmd+3), and save them all and shares the logs, and hope that someone will browse them for errors and figure out what caused them.

**Comment by ckerr** [comment] 2023-02-23 00:27
Is this still an issue in 4.0.1?

**Comment by ckerr** [comment] 2023-03-18 03:06
Closing due to lack of response and lack of actionable info.

**Closed by ckerr** 2023-03-18 03:06 UTC
Labels: bug, scope:mac, needs confirmation
