### ISSUE TITLE
Use units based on powers of 2

### ISSUE THREAD

**Issue by svkirillov** [transmission/transmission#5133] opened 2023-03-03 16:24 UTC
### What is the issue?

Use units based on powers of 2 instead powers of 10 for describing speed and disk usage.

1 KB (1000 bytes) -> 1 KiB (1024 bytes)
1 MB (1000 KB) -> 1 MiB (1024 KiB)
1 GB (1000 MB) -> 1 GiB (1024 MiB)
1 TB (1000 GB) -> 1 TiB (1024 TiB)

It is common for other torrent clients, e.g. qBittorrent, Deluge.

### Which application of Transmission?

All clients.

### Which version of Transmission?

4.0.1 (e1c6e1be43)

**Comment by ckerr** [comment] 2023-03-03 16:32
Hi @svkirillov, thanks for reporting this!

I think this is a duplicate of https://github.com/transmission/transmission/issues/198 so I'm closing this as a dupe.

**Closed by ckerr** 2023-03-03 16:32 UTC
