### ISSUE TITLE
Can not rename file/folder when adding torrent. Only when it was added

### ISSUE THREAD

**Issue by slrslr** [transmission/transmission#1099] opened 2020-01-10 10:09 UTC
On Windows 10, transmission 2.94
When i select to add torrent file, it shows dialog where i should be able to rename the files and folders that will be downloaded via torrent.

Single click, doubleclick, F2 and even the right click "Rename" menu entry does nothing.
But after torrent is added, i doubleclick torrent, and on FIles tab i am able to rename.
But this is not handy. Renaming on torrent adding should be fixed.

Related: https://trac.transmissionbt.com/ticket/5384

Issue also in v. 3.00+

**Comment by danfiscus** [comment] 2020-01-31 22:23
This is doubly problematic when the preset file/folder name is incompatible with your drive/file system/OS's naming conventions.

**Comment by slrslr** [comment] 2020-02-05 18:43
This is Windows 10 and the filesystem is NTFS and it happens to all torrents i tried so far, so i doubt it is some incompatibility on my side. If you think it is and know some more steps i need to do to provide more details, let me know.

**Comment by uap4** [comment] 2021-07-04 09:35
Linux. transmission-qt 3.00
In the terminal displays "edit: editing failed" when I press the right button and rename.

**Comment by ckerr** [comment] 2022-02-24 19:54
Duplicate of https://github.com/transmission/transmission/issues/638

**Closed by ckerr** 2022-02-24 19:54 UTC
