### ISSUE TITLE
IO freezes during file allocation for big files

### ISSUE THREAD

**Issue by const586** [transmission/transmission#568] opened 2018-03-31 17:00 UTC
Optimize disk allocation for very large files.

What is the problem?

If I download a file of about 100 GB. And if the early rare piece is at the end of the sequence. It will take a very long time for the OS to write this piece.

To get around this problem, I propose the following algorithm.

If the requested piece is too far (optional) from the right of the last requested - request a new piece that satisfies the distance condition.

**Comment by cfpp2p** [comment] 2018-04-02 16:35
> preallocation: Number (0 = Off, 1 = Fast, 2 = Full (slower but reduces disk fragmentation), default = 1)

**_#files-and-locations_**
https://github.com/transmission/transmission/wiki/Editing-Configuration-Files#files-and-locations

> To get around this problem, I propose the following algorithm.
> 
> If the requested piece is too far (optional) from the right of the last requested - request a new piece that satisfies the distance condition.

yes, something like that works:
**_george gray - 2015-05-27_**
https://sourceforge.net/p/transmissiondaemon/discussion/general/thread/2d0fd14b/#453a

**Comment by const586** [comment] 2018-04-03 17:03
it's not work.
I use transmission-2.93-r96926a8337. Win version

**Comment by ckerr** [comment] 2022-01-19 23:04
Closing as a dupe of https://github.com/transmission/transmission/issues/2462. I realize this ticket was filed before 2462, but there are so many overlapping tickets at this point that it makes sense to start with a new "big picture" ticket.

**Closed by ckerr** 2022-01-19 23:04 UTC
