### ISSUE TITLE
Downloading progress keeps rolling back

### ISSUE THREAD

**Issue by senhuiguo** [transmission/transmission#4815] opened 2023-02-11 02:48 UTC
### What is the issue?

I was trying to download several files but found out that the progress keeps rolling backward, due to which I'm unable to finish the download. I also tried another tool (BitTorrent Web) and had no issue with those magnet links, so I think the issue is with Transmission. Here's a [screen recording](https://www.dropbox.com/s/4swyle0fd64adm4/Screen%20Recording%202023-02-11%20at%201.36.18%20pm.mov?dl=0) of the rolling back, where the progress keeps coming back and forth.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0

**Comment by ckerr** [comment] 2023-02-11 03:07
Duplicate of https://github.com/transmission/transmission/issues/4583

**Closed by ckerr** 2023-02-11 03:07 UTC
