### ISSUE TITLE
download speed limit ignored in 4.0.0-beta.3 through 4.0.1

### ISSUE THREAD

**Issue by Krisztian89** [transmission/transmission#4701] opened 2023-02-01 10:26 UTC
### What is the issue?

Transmission ignores download rate on M2 Mac mini both global and turtle (slower) limits.
Ventura 13.2

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0-beta.3 (634b1e8fc1)

**Comment by Krisztian89** [comment] 2023-02-01 18:24
I set the download rate to 5120 KB/s and I could see in the top right corner of the app and also on the dock icon around 10-12 MB/s download speed.

**Comment by ckerr** [comment] 2023-02-01 19:00
OK, thanks for the info. 

I'm going to be a little more specific because it could help me to understand the problem.

- Are we talking about a single torrent, or multiple torrents?
- For each torrent -- in the Torrent Inspector dialog, under "Transfer Bandwidth", which items are checked? And if either of the speeds are checked, what are their values?
- In Settings > Bandwidth, are either of the "Global bandwidth limits" checked, and if so, what are the speed values of the checked rows?
- What color Is the turtle in the lower-left corner of the main window -- blue, or grey?
- Does the speed in the top right corner of the app match the speed of the individual torrent row in the main window?

**Comment by Krisztian89** [comment] 2023-02-01 19:32
[https://imgur.com/a/K1nwfan](url)

**Comment by ckerr** [comment] 2023-02-01 20:33
That's really informative; thanks!

And none of the checkboxes are checked under Inspector > Options > Transfer Bandwidth?

**Comment by Krisztian89** [comment] 2023-02-01 21:08
Only the "Stay within the global bandwidth limits" checked.

**Comment by ckerr** [comment] 2023-02-01 21:09
![LxhB8yh](https://user-images.githubusercontent.com/70381/216163736-a9487d02-9f3d-40dd-8dd1-d69632e3d9bd.png)

**Comment by ckerr** [comment] 2023-02-01 21:09
> Only the "Stay within the global bandwidth limits" checked.

Ah, drat! I was hoping that was it :smile_cat:

**Comment by ckerr** [comment] 2023-02-01 21:11
OK next blind guess is it's some issue with Turtle Mode that I haven't encountered.

@Krisztian89 if you unclick the turtle s.t. it's grey, does the problem persist?

**Comment by Krisztian89** [comment] 2023-02-01 21:13
Yes, the global bandwidth limit also ignored :/

**Comment by Krisztian89** [comment] 2023-02-03 19:56
Can not use my internet because transmission stole the whole bandwidth during download.

**Comment by Finesse** [comment] 2023-02-08 11:42
@ckerr I've just updated to 4.0.0 and have faced this issue too. My troubleshooting:

- Quit Transmission and start again
- Turn the turtle on and off
- Check that there are no limit overrides for the transfer

<img src="https://user-images.githubusercontent.com/9006227/217519793-1bdf8fbc-1e5f-49f0-838e-f39161cdbe88.jpg" width="1101" />

**Comment by NekoFever** [comment] 2023-02-11 14:32
Same here on an M1 Pro MacBook Pro running latest macOS. I didn't notice the problem in the early betas but it's definitely happening now in 4.0.0.

![Screenshot 2023-02-11 at 2 27 07 pm](https://user-images.githubusercontent.com/5204912/218263510-338fa673-175f-4b63-8cfb-8eada2cf99da.png)

**Comment by ckerr** [comment] 2023-02-12 01:35
I haven't been able to reproduce this but clearly other people are seeing it, so removing the "unconfirmed" label

**Comment by ckerr** [comment] 2023-02-12 01:56
For people experiencing this:

- are both download and upload limits ignored, or just download?
- is it all torrents, or just some?
- can you take a picture of the peers tab while this is happening? (ok to block out IP addresses)

**Comment by Finesse** [comment] 2023-02-12 12:51
@ckerr 

> are both download and upload limits ignored, or just download?

Only the download speed limit is ignored. The upload speed limiter works both in the turtle mode and for individual transfers.

I also tried to change the «Global bandwidth limits» settings, it gave no effect. I tried different speed limit settings for individual transfers.

> is it all torrents, or just some?

All

> can you take a picture of the peers tab while this is happening? (ok to block out IP addresses)

<img width="428" alt="image" src="https://user-images.githubusercontent.com/9006227/218311955-380f5d4e-007c-4491-af11-35826e7b31b9.png">

**Comment by ckerr** [comment] 2023-02-12 20:15
I still see the issue but this info is very helpful in narrowing down the suspects. Thanks :heart:

**Comment by ckerr** [comment] 2023-02-12 20:17
I still am not seeing the cause of this issue, but all this info is very helpful in narrowing down the suspects, e.g. even individual peers are exceeding the download limit. So it's not related to webseeds and it's not some aggregate-across-all-peers limit issue.

Thanks for the info!

**Comment by nitz** [comment] 2023-02-13 13:31
I'm seeing the issue, sort of.

I'm on Win 10 Pro 22H2 19045.2546, `v4.0.0 280ace12f8` (Qt only install). Not using turtle mode, just individual per-torrent settings. I typically use upload limits because unchecked uploading chokes out my connection, but what I've found is enabling the "Limit Upload Speed" seems to actually limit the **download rate**. Enabling "Limit Download Speed" doesn't seem to affect download speed at all, and I'm guessing will limit the upload, given the reversal of the prior.

I'm betting the UI is just reversed in where it's applying the values.

![image](https://user-images.githubusercontent.com/602691/218470828-3fc3445f-1c7e-402c-bb48-f24a9f4bdd8d.png)
![image](https://user-images.githubusercontent.com/602691/218470961-604208e3-67cd-47a8-90bb-2918c613d8f4.png)

**Comment by Bamgie1** [comment] 2023-02-14 12:11
I also had this issue yesterday. No turtle, no global - nothing works. But I could swear that it wasn't like that at first. So I restarted my Mac and everything works like a charm now.

**Comment by LordDeimos666** [comment] 2023-02-15 18:38
Same issue, download speed ignored on a docker version of it.
Rolling back to 3.0 for the moment.

**Comment by Helyos96** [comment] 2023-02-16 16:52
Same issue after upgrading from transmission-qt 3.0.0 to 4.0.0 on Ubuntu 22.10. Using this PPA: https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/transmission

Download limits are ignored. Tried changing it, restarting the app, toggling the turtle on/off, setting per-torrent limits (and unchecking "Honor global limits"). Nothing seems to work.

**Comment by erekle13** [comment] 2023-02-17 07:41
Same here with 4.0.0 (280ace12f8) on M1.

**Comment by ckerr** [comment] 2023-02-18 17:22
I had a small amount of time this morning to look into this.

Bug tracking nodes:

- It's not a bug in the client code. It's been reported in tr-qt and tr-mac and I'm able to reproduce it in both.

- In libtransmission it doesn't appear to be a bug in settings, session, or bandwidth classes. So I can toggle "limit download" in the global settings dialog and see that the session bandwidth _is_ clamping down how many bytes can be read from any given peer. So somehow that's being disregarded further down the pipeline.

- Possibly in the UTP code that's new for 4.0.0. Or possibly in the code that says "hm we've been clamped down to 0 Bps, let's turn off polling on this socket until we're allowed some Bps".

--- 

This definitely needs to get fixed in the `4.0.x` series and would be nice-to-have for `4.0.1`.

Purely from a timing standpoint I may not be available to work on this before Wednesday's `4.0.1` deadline. This is an important bug, but IMO not a blocker compared to all the other fixes queued up for `4.0.1`.

***If*** `4.0.1` ships with this bug, it'll be at the top of the list for `4.0.2`.

**Closed** 2023-02-27 21:03 UTC
Labels: pr welcome, confirmed, bug:regression

**Comment by RobFog** [comment] 2023-03-15 21:54
Should this issue be moved to the 4.0.2 milestone for clarity?
