### ISSUE TITLE
Transmission GTK+ doesn't respect GNOME dark theme settings

### ISSUE THREAD

**Issue by rail01** [transmission/transmission#5275] opened 2023-03-22 13:40 UTC
### What is the issue?

Transmission GTK on GNOME systems fails to respect system-wide dark theme option and instead always defaults to light theme.

Discussion about the problem: https://github.com/transmission/transmission/discussions/5140

![Screenshot from 2023-03-22 14-39-09](https://user-images.githubusercontent.com/29921838/226922073-2a2ff5a3-72a4-4b6e-be16-14803ff3dad4.png)

System info:
- Arch (`transmission-gtk` installed from official repos)
- Linux 6.2.7
- GNOME 43.2-1

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.1 (e1c6e1be43)

**Comment by ckerr** [comment] 2023-03-22 14:43
Duplicate of https://github.com/transmission/transmission/discussions/5140

**Closed by ckerr** 2023-03-22 14:43 UTC
