### ISSUE TITLE
TransmissionBT Forum Signup Broken

### ISSUE THREAD

**Issue by slimandslam** [transmission/transmission#4869] opened 2023-02-13 19:09 UTC
### What is the issue?

The new user signup at https://forum.transmissionbt.com does not work. I'm not sure if the reCaptcha is broken or something else. On Firefox (latest MacOS version), it seems to work, but submitting your new user signup just brings you back to the form (now empty) and no email is ever received. On Safari, ugly error messages are displayed outside the form after submission:

```
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php on line 80: file_get_contents(): SSL context creation failure
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php on line 80: file_get_contents(): Failed to enable crypto
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php on line 80: file_get_contents(https://www.google.com/recaptcha/api/siteverify): failed to open stream: operation failed
```

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0

**Comment by ckerr** [comment] 2023-02-13 21:13
@slimandslam thanks for reporting this!

I think this is a duplicate of https://github.com/transmission/transmission/issues/4853 so I'm going to close this ticket.

**Closed by ckerr** 2023-02-13 21:13 UTC
