### ISSUE TITLE
Adding Groups as Functionality to Web Client

### ISSUE THREAD

**Issue by shatteredsite** [transmission/transmission#5014] opened 2023-02-23 22:11 UTC
### What is the issue?

Due to the fact groups can be used to set download paths of torrents, the ability to designate groups when adding torrents with the web client would allow users to maintain file organization on remote machines. This can be very helpful on NAS with media server software.

### Which application of Transmission?

Web client

### Which version of Transmission?

4.01

**Comment by ckerr** [comment] 2023-02-24 00:45
Hi @shatteredsite, thanks for the suggestion!

I think this is a duplicate of https://github.com/transmission/transmission/issues/3813 so I'm going to close this ticket as a dupe. Please check out 3813 and subscribe to it if you want to follow its progress!

**Closed by ckerr** 2023-02-24 00:45 UTC
