### ISSUE TITLE
when verifying,show "File name too long"

### ISSUE THREAD

**Issue by avatasia** [transmission/transmission#6711] opened 2024-03-17 09:56 UTC
### What is the issue?

file name: 
[EAC] [110427] TVアニメ あの日見た花の名前を僕達はまだ知らない。 ED 「secret base ～君がくれたもの～」[DVD付初回生産限定盤]／本間芽衣子、安城鳴子、鶴見知利子（CV：茅野愛衣&戸松遥&早見沙織） (ape+cue+ISO).rar

This can work in windows. 
I know the limit  255 NAME_MAX in linux.
But I find it works on qbittorrent.
It reduces the file name to the limit,and use the name anywhere.
But transmission just report file name too long.
So I wish transmission can consider whether it's supported.
Qbittorrent trim the file name to 244 bytes.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.5

**Comment by tearfur** [comment] 2024-03-18 05:52
Duplicate of #2311.

**Closed by tearfur** 2024-03-18 05:52 UTC
