### ISSUE TITLE
The Transmission application does not open for me

### ISSUE THREAD

**Issue by Cristo095** [transmission/transmission#6033] opened 2023-09-24 20:36 UTC
### What is the issue?

The Transmission application does not open for me, the executed program appears even in task management but I cannot open and use it as I want.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.4 Stable

**Comment by Daniel6372** [comment] 2023-09-25 03:03
duplicate of https://github.com/transmission/transmission/issues/5982

**Comment by tearfur** [comment] 2023-10-03 12:50
@Cristo095 If your issue is not yet solved then please re-open.

**Closed by tearfur** 2023-10-03 12:50 UTC
Labels: scope:qt
