### ISSUE TITLE
Have Transmission run in menu bar icon instead of dock

### ISSUE THREAD

**Issue by tsegreto** [transmission/transmission#6850] opened 2024-05-22 22:03 UTC
### What is the issue?

Huge fan of Transmission, however, it would make so much more sense to have it running in the menu bar instead of the dock. This seems like it should be a fairly simple implementation.

### Which application of Transmission?

macOS app

**Comment by killemov** [comment] 2024-05-23 06:51
Duplicate of #6841.

**Closed** 2024-05-23 11:48 UTC
