### ISSUE TITLE
Skipped Files Still Downloaded On Linux

### ISSUE THREAD

**Issue by EvilSupahFly** [transmission/transmission#3650] opened 2022-08-16 06:05 UTC
When I pull up the "Properties" page on an active Torrent, and select the "Files" tab, I have the option to skip downloading any or all of the files and/or folders listed. Generally speaking, I don't want things like extra subtitle files, or footprint text files from torrent hosting sites ("`Torrent Downloaded From Blah Blah Blah.com.txt`"), or non-essential files for additional languages, and things like that.

However, even when I uncheck the Download box, Transmission still downloads those files, and I have to go into the torrent folder after and remove them myself.

It's not a functionally crippling issue, but it is a bit of an irritation. Is this a bug? Because that seems like a pretty big design flaw, otherwise.

If it helps, I'm running Transmission-GTK v3.00 (bb6b5a062e) from the Linux Mint 21 (Cinnamon) official repositories. Full system specs [here](https://termbin.com/y6ye) for the morbidly curious.

**Comment by ile6695** [comment] 2022-08-16 09:59
Duplicate of https://github.com/transmission/transmission/issues/290

Simplified explanation is that some files need to also be downloaded because they contain data that another (selected) file requires.

**Comment by EvilSupahFly** [comment] 2022-08-17 14:26
> 
> The simple answer is that both the selected and skipped files share a "piece". Pieces have to be downloaded completely, (skipped) files do not. For example, if you have a 1 MB torrent with only 1 MB piece but with 200 5KB files and you select only 1 of those files then all of them have to be downloaded anyway because they are contained in that one same 1MB piece.

This makes more sense. Thanks!

**Comment by ile6695** [comment] 2022-08-17 15:00
> No! Bad explanation. They especially DO NOT contain data another file requires, which is impossible. Maybe you got lost in translation?

Emphasis on the simplified. Your answer is more detailed, but now reader needs to know what torrent pieces are.

If someone asks why those skipped files are not deleted after downloading them, they are still needed in order to verify the files you did want to download.

**Closed** 2022-08-17 15:12 UTC
