### ISSUE TITLE
Is Transmission 4.0 supported on Windows 7 SP1?

### ISSUE THREAD

**Issue by dftf-stu** [transmission/transmission#4761] opened 2023-02-08 22:52 UTC
### What is the issue?

Is the new _Transmission_ 4.0 release supposed to work on _Windows 7_?

I have an install of 64-bit _Windows 7 with Service Pack 1_ and all updates installed, and have downloaded the new 4.0 stable-release (with a Digital Signature date of 8 Feb 2023) from GitHub.

The app installed without any errors, but upon trying to launch it after, I just get:
**transmission-qt.exe - Application Error**
**The application was unable to start correctly (0xc0000005). Click OK to close the application.** 

On the main download page for Transmission (https://transmissionbt.com/download) it says "Requires Windows 7 or later", so I am assuming it should work?

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.0 (280ace12f8), Digital Signature date: 8 Feb 2023

**Comment by ckerr** [comment] 2023-02-08 23:01
I don't think any of the maintainers are running Windows 7 so it probably depends on how lenient you are with your definition of "supported." :neutral_face: 

We'll answer questions and try to help, but it'll probably be up to you to do the testing and help track down any issue.

> 0xc0000005 

this sounds like a possible duplicate of #4734

**Comment by dftf-stu** [comment] 2023-02-08 23:02
Hmm, so looking at the app's files I find "qwindows.dll" which is version 6.4.0.0.

A quick Google seems to suggest that Qt 6 series dropped-support for Windows 7 and 8.

So I'm guessing someone needs to correct the text on the Download page to:
**Requires Windows 10 or later**

And perhaps on the "Previous Releases" page you could add:
**Still using Windows 7?  Download Transmission 3.0**
**Still using Windows XP or Vista?  Download Transmission 2.84.9**
So as to make it clear what the final versions are?

Thanks

**Comment by dftf-stu** [comment] 2023-02-08 23:08
@ckerr : see comment above, thanks

**Comment by ckerr** [comment] 2023-02-08 23:30
Closing as a dupe of 4734.

**Closed by ckerr** 2023-02-08 23:30 UTC

**Comment by GaryElshaw** [comment] 2023-02-09 00:12
Just a note to let you know Transmission 4.0 can be built with Qt5.
