### ISSUE TITLE
Wrong ratio & completion computations

### ISSUE THREAD

**Issue by Berbe** [transmission/transmission#7243] opened 2024-11-13 11:24 UTC
# What is the issue?

The recent change making ratio appears as percentage made me realise some displayed values seem wrong.

## Ratio
Ratio shall be defined as uploaded/downloaded, but it rather seems to be computed as uploaded/have:
![Ratio](https://github.com/user-attachments/assets/26622d24-ba75-4dc4-9e59-8e92314d06e6)
Here, the ratio should be 4.43 GB / 18.61 GB ~= 0.24, not ~= 18.61 GB / 524 kB

## Completion
On top of that, another problem: the displayed percentage should be completion, which is different than ratio.
This is defined by have/available.
Availability is defined by the files the user selected in the torrent (ie not necessarily the whole torrent).

## Units
On top of all that, units being used are decimal, base 10 (for instances kB, GB) rather then [binary](https://iec.ch/prefixes-binary-multiples), base 2 (for instance kiB, GiB).

# Which application of Transmission?

transmission-daemon

# Which version of Transmission?

f10ed942e3b73b92cf0d24850a167fb9b7fa0d07 (#7051 on top of 7e4b4f10a1f90885c0bebb168eedffe153f1cf53)

**Comment by killemov** [comment] 2024-11-13 12:03
Duplicate of #6087

**Closed** 2024-11-14 06:47 UTC

**Comment by Rukario** [comment] 2024-11-14 15:41
After seeing your screenshot I guess I'll have to give #5937 a refinement 😅
