### ISSUE TITLE
Transmission gives up if disk is not mounted (Error: No data found!)

### ISSUE THREAD

**Issue by AlexanderJonsson** [transmission/transmission#1308] opened 2020-06-09 12:01 UTC
When adding or resuming a torrent with the target disk unmounted causes Transmission to give up on downloading the file and prompting the user to re-add the torrent. Inconvenient if Transmission is auto adding and deleteing torrent files.

Using "Move data file to..." as suggested also does not work, the torrent needs to be removed and re-added.

The behaviour should be to simply resume or re-check the data after the disk has been mounted.  

![Screen Shot 2020-06-09 at 13 52 38](https://user-images.githubusercontent.com/39478379/84144412-7d0bf100-aa58-11ea-9f44-8bd65fee768a.png)

**Comment by ckerr** [comment] 2022-01-27 04:36
This is a duplicate of #834

**Closed by ckerr** 2022-01-27 04:36 UTC
