### ISSUE TITLE
transmission-gtk.desktop.in is not using translated strings

### ISSUE THREAD

**Issue by scootergrisen** [transmission/transmission#1590] opened 2021-01-14 14:52 UTC
Seems like https://github.com/transmission/transmission/blob/master/gtk/transmission-gtk.desktop.in does not contain translations for the following strings:

    [Desktop Entry]
    Name=Transmission
    GenericName=BitTorrent Client
    Comment=Download and share files over BitTorrent
    Keywords=torrents;downloading;uploading;share;sharing;
    
    [Desktop Action Pause]
    Name=Start Transmission with All Torrents Paused
    
    [Desktop Action Minimize]
    Name=Start Transmission Minimized

They are in the po files but seems they are not put to use in the transmission-gtk.desktop.in file.

Using:
transmission-gtk 3.00
Fedora 33 Workstation
GNOME 3.38.2

**Comment by avivmu** [comment] 2021-02-04 11:21
What language?
There was a [sync translation commit](https://github.com/transmission/transmission/commit/a6798adf2c110dd92961a9e52c2eb6f1b33dbd89) not long ago - try using latest master and see if it solves your problem

**Comment by ckerr** [comment] 2022-01-18 05:44
is this still an issue in `main`?

**Comment by scootergrisen** [comment] 2022-01-18 10:46
In 2.9 i see underscore:

    _Comment=Download and share files over BitTorrent

But no underscore in main:

    Comment=Download and share files over BitTorrent

Looking at that it seems the translated string would be added in 2.9 but not in main.

**Comment by ckerr** [comment] 2022-01-18 16:44
Dunno if that makes a difference or not. That change occurred [here](https://github.com/transmission/transmission/commit/8c160aad2d3adb7417c26605fd08e79494e07ee5#diff-d94907f26ea48b7eeb778b9dd9f0bed995834e86c21cce594b704c2895841f82)

**Comment by scootergrisen** [comment] 2022-01-18 17:34
Ok it says "replace intltool with gettext".
So perhaps underscore is not needed with gettext i don't know.

**Comment by mikedld** [comment] 2022-10-22 12:33
I'm not sure I understand what this is about. transmission-gtk.desktop.in file doesn't have translations because it's a template, translations are added during build, when transmission-gtk.desktop file is generated, and then the installed file has them. Leaning toward closing this as invalid.

**Comment by scootergrisen** [comment] 2022-10-22 18:45
The problem is/was that a string like:

    Download and share files over BitTorrent

Exists and is translated in the po file like:
https://github.com/transmission/transmission/blob/main/po/da.po#L1238-L1240

But the translated string is/was not in transmission-gtk.desktop on the users computer when Transmission is installed.

transmission-gtk.desktop should contain both lines:

    Comment=Download and share files over BitTorrent
    Comment[da]=Download og del filer via BitTorrent

But only contained this line:

    Comment=Download and share files over BitTorrent

So far as i think i was. Have not tested recently.

So maybe someone else can check to see if those strings are all ending up in transmission-gtk.desktop on the users computer when Transmission is installed so the user can see all translated string.

**Comment by mikedld** [comment] 2022-10-22 19:08
Just checked:
* Debian ([transmission-gtk_3.00-1_amd64.deb](http://ftp.debian.org/debian/pool/main/t/transmission/transmission-gtk_3.00-1_amd64.deb)) — translations missing :x:
* Ubuntu ([transmission-gtk_3.00-2ubuntu2_amd64.deb](http://mirrors.kernel.org/ubuntu/pool/main/t/transmission/transmission-gtk_3.00-2ubuntu2_amd64.deb)) —translations missing :x:
* Fedora ([transmission-gtk-3.00-13.fc38.x86_64.rpm](https://kojipkgs.fedoraproject.org/packages/transmission/3.00/13.fc38/x86_64/transmission-gtk-3.00-13.fc38.x86_64.rpm)) — translations missing :x:
* Arch ([transmission-gtk-3.00-4-x86_64.pkg.tar.zst](https://geo.mirror.pkgbuild.com/extra/os/x86_64/transmission-gtk-3.00-4-x86_64.pkg.tar.zst)) — translations missing :x:
* Gentoo ([transmission-3.00-r4.ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-p2p/transmission/transmission-3.00-r4.ebuild)) — translations present :heavy_check_mark:

P.S. I'm on Gentoo ;)

**Comment by mikedld** [comment] 2023-01-29 20:22
I believe this is caused by incorrect build configuration. Tried building current `main` on Fedora and Ubuntu, both result in translations being there in the installed desktop file if `ENABLE_NLS` is set to `ON` (which is the default). Unless there's proof that setting `ENABLE_NLS` to `ON` results in missing translations, it might be better to report this to your distro bugtracker / package maintainer.

**Closed by mikedld** 2023-01-29 20:22 UTC
Labels: help wanted, needs clarification, scope:gtk, pr welcome
