### ISSUE TITLE
[Feature Request] Parallel verification of local data

### ISSUE THREAD

**Issue by yxwangcs** [transmission/transmission#912] opened 2019-05-18 19:09 UTC
Hi transmission developers,

It seems that for transmission 2.94 it can only verify local data one torrent at a time, but verification doesn't take up much cpu usage even on a very old laptop of mine. Is it possible to allow parallel verification of local data?

**Comment by xavery** [comment] 2019-05-19 22:32
The verification process is IO bound anyway, so this wouldn't guarantee vast speedups unless your data is scattered across different physical drives, and the potential algorithm used in Transmission would be able to figure out only to run parallel verification for files/folders actually residing on physical drives.

**Comment by lps-rocks** [comment] 2019-06-15 03:08
> The verification process is IO bound anyway, so this wouldn't guarantee vast speedups unless your data is scattered across different physical drives, and the potential algorithm used in Transmission would be able to figure out only to run parallel verification for files/folders actually residing on different physical drives.

Large disk arrays / modern SSDs/NVMe can easily keep up with the I/O  - I think it's time to make this operate like an additional download/seed queue - but instead for checking...

**Comment by fisherwei** [comment] 2020-03-30 08:50
TR can only verify torrent one by one, whatever high speed all flash disk arrays or a old HDD.

parallel verification controlled by user is a good idea.

**Comment by A-l-exa-n-d-r** [comment] 2021-03-03 09:58
Аlso relevant for the situation: 1 large/long torrent blocks the scan of smalls/fast. Since there is not even an option to pause the scan / lower the priority of the long torrent.

**Comment by lordkitsuna** [comment] 2021-03-09 17:19
I will toss my vote of support into this, i just had to verify over 1000 and its painful watching it do it one at a time when my raid array is capable of far more than its doing. on a single io stream it hits saturation but my array is capable of handling many streams at once without falling apart would have been nice to have it doing like 10 at a time instead. would love an option i could set for this

**Comment by delroth** [comment] 2021-05-02 04:26
+1 to this feature request. I run Transmission on a server with a large disk array and a slow ARMv8 CPU (but with 8 cores). The current verification doesn't nearly saturate my disk bandwidth before saturating the one CPU thread it's doing verification one.

The good news is that I was annoyed enough at this that I've implemented what I think is a working version of this FR. Please see #1685 and give feedback and testing reports. Thank you!

**Comment by ckerr** [comment] 2022-01-19 23:03
Closing as a dupe of https://github.com/transmission/transmission/issues/2462. I realize this ticket was filed before 2462, but there are so many overlapping tickets at this point that it makes sense to start with a new "big picture" ticket.

**Closed by ckerr** 2022-01-19 23:03 UTC
