### ISSUE TITLE
transmission-daemon 4.1.0-dev crash after the first connection to the webservice

### ISSUE THREAD

**Issue by mate1213** [transmission/transmission#6020] opened 2023-09-18 21:14 UTC
### What is the issue?

The daemon is running until the firs connection is not opened to the web controller after the following crash happens..
```
/usr/local/bin/transmission-daemon --log-level=warn -e /var/log/transmission.log -g /srv/transmission-daemon -f
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```
This instance installed and updated according the documentation, without error in the compilation steps.
https://github.com/transmission/transmission/blob/main/docs/Building-Transmission.md#building-transmission-from-git-first-time

Further info can be provided, if needed.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.1.0-dev

**Comment by tearfur** [comment] 2023-09-19 01:08
The symptoms are different, but judging from the way to trigger this, it's probably a duplicate of #6003.

**Comment by mate1213** [comment] 2023-09-19 20:14
Even with ` --log-level=trace` I cannot get the same debug output to verify (probably because the build flag, I used what is in the doc). But it seems like these are the same.

Can I revert to the latest stable release, some how? (Using source code, to build it locally.) THX for help.

**Comment by tearfur** [comment] 2023-09-20 00:46
Can I revert to the latest stable release, some how?

Just checkout the release tag and then update your submodules by `git submodule update --init --recursive`.

**Closed** 2023-09-20 00:46 UTC
