### ISSUE TITLE
Transmission daemon on Ubuntu timesout on startup; fails

### ISSUE THREAD

**Issue by tonydiep** [transmission/transmission#7185] opened 2024-10-19 14:10 UTC
### What is the issue?

After installing transmission daemon on Ubuntu 24.04 and starting it, the daemon serves a web page for a couple of minutes, can download a torrent, then times out and fails.

During installation the followign error message is printed:

```
Setting up transmission-daemon (4.0.5-1build5) ...
Created symlink /etc/systemd/system/multi-user.target.wants/transmission-daemon.service → /usr/lib/systemd/system/transmission-daemon.service.
Could not execute systemctl:  at /usr/bin/deb-systemd-invoke line 148.
```

Oct 19 09:59:06 hottie systemd[1]: Starting transmission-daemon.service - Transmission BitTorrent Daemon...
Oct 19 10:00:36 hottie systemd[1]: transmission-daemon.service: start operation timed out. Terminating.
Oct 19 10:00:36 hottie transmission-daemon[2968]: Closing transmission session... done.
Oct 19 10:00:36 hottie systemd[1]: transmission-daemon.service: Failed with result 'timeout'.
Oct 19 10:00:36 hottie systemd[1]: Failed to start transmission-daemon.service - Transmission BitTorrent Daemon.

Package info is

```
Package: transmission-daemon
Version: 4.0.5-1build5
Source: transmission
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Sandro Tosi <morph@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1,673 kB
Pre-Depends: init-system-helpers (>= 1.54~), adduser
Depends: transmission-common (= 4.0.5-1build5), libc6 (>= 2.38), libcurl4t64 (>= 7.28.0), libdeflate0 (>= 1.0), libevent-2.1-7t64 (>= 2.1.8-stable), libgcc-s1 (>= 3.4), libminiupnpc17 (>= 1.9.20140610), libnatpmp1t64 (>= 20150609), libssl3t64 (>= 3.0.0), libstdc++6 (>= 13.1), libsystemd0
```

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

deamon won't start. can't get info.

**Comment by killemov** [comment] 2024-10-20 08:36
Hmmm. I've had timeouts happen in the past, but that was with a lot of torrents on very low-power hardware. I had to change the service file:

<pre>
[Unit]
Description=Transmission BitTorrent Daemon
After=network.target

[Service]
User=debian-transmission
<b>TimeoutStartSec=infinity</b>
Type=notify
ExecStart=/usr/bin/transmission-daemon -f --log-error
ExecStop=/bin/kill -s STOP $MAINPID
ExecReload=/bin/kill -s HUP $MAINPID
Restart=always
Environment=TRANSMISSION_WEB_HOME=/home/killemov/shift
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
</pre>

**Comment by tearfur** [comment] 2024-10-20 10:33
Duplicate of #6991

**Closed** 2024-10-21 03:26 UTC
