### ISSUE TITLE
Transmission 3.00 pauses downloading when moving downloaded files to target folder, sometimes it breaks system Wifi in macOS Ventura 13.1

### ISSUE THREAD

**Issue by owenzhao** [transmission/transmission#4556] opened 2023-01-08 11:29 UTC
### What is the issue?

When a torrent file is downloaded successfully, Transmission will move it to the target folder I set. However, when the moving starts, other torrents will stop downloading until the moving ends. That is something odd, as I never notice this before.

Also, sometimes when this kind of thing happens, the network connection will not work. I can not even connect to my local router. It takes over 3 minutes until the network is back. Also, when this issue happens, AdGuard jumps and says its network extension is not working and disables itself. However, even with AdGuard disabled, the issue still happens. So it must be something with Transmission. I will test some other BitTorrent clients and see if they also cause this issue.

The second issue is simpler with [Transmission 4.0.0-beta.1 (afdae24995) Freezing regularly on M1 MBA](https://github.com/transmission/transmission/issues/4269). But mine was 3.00 (f4489c982e) Intel.

### Which application of Transmission?

macOS app

### Which version of Transmission?

3.00 (f4489c982e)

**Comment by owenzhao** [comment] 2023-01-08 11:47
I found something more. As I said when I downloads a torrent, Transmission will put part file in an incoming folder, and when the download finishes, Transmission will move all downloaded items to my target folder. 

However, I find that Transmission some how delayed the remove operation of the downloaded folder. For example, I have a folder, say "foo" folder with a file "bar.mp4" in it. After copying foo folder to the target folder. Transmission doesn't remove the foo folder in the incoming folder, it first removes the bar.mp4. Then after about 3 minutes, it removes the foo folder. During that delay time the CPU usage and disk usage are both low, so I have no idea why it delays.

**Comment by owenzhao** [comment] 2023-01-08 11:47
The incoming folder and target folder are in different drives.

**Comment by ckerr** [comment] 2023-01-08 16:23
Duplicate of https://github.com/transmission/transmission/issues/2462

**Closed by ckerr** 2023-01-08 16:23 UTC

**Comment by owenzhao** [comment] 2023-01-09 00:01
> Duplicate of #2462

I don't think this issue is the same as #2462. As in its threads, it was said the reason of the issue is because slow I/O. For my case, it was not true.

My incoming folder's drive was a M.2 SSD, whose speed was over 900MB/s on both write and read. The target folder's drive was a normal disk, whose speed was about 100MB/s. So when moving from incoming to target, the read speed was only 100MB/s. My internet download speed is 400 Mbps. So the max download speed is 50MB/s. 150MB/s is much more less than 900MB/s. Therefore, the other torrents should not be paused during the moving. 

Also my issue was not just about the blocking. Transmission also cause the Wifi down for the system. For me, the second issue was much more important than the first. The second issue was never mentioned in #2462 .

**Comment by ckerr** [comment] 2023-01-09 18:21
> Therefore, the other torrents should not be paused during the moving.

Yes, unless I'm misunderstanding what you're saying, that behavior that you're describing is a direct symptom of 2462?  When all of the torrent work is being done in a single thread and its disk IO is blocking, all the other torrent work comes to a stop while files are moving.

**Comment by owenzhao** [comment] 2023-01-09 23:35
> > Therefore, the other torrents should not be paused during the moving.
> 
> Yes, unless I'm misunderstanding what you're saying, that behavior that you're describing is a direct symptom of 2462? When all of the torrent work is being done in a single thread and its disk IO is blocking, all the other torrent work comes to a stop while files are moving.

What about the WiFi blocking on the whole system? Is that a part of disk blocking?
