### ISSUE TITLE
transmission-qt: duplicate process

### ISSUE THREAD

**Issue by zlice** [transmission/transmission#6993] opened 2024-07-13 12:57 UTC
### What is the issue?

When launching `transmission-qt` it seems to spawn for each run. Didn't see another issue for multiple processes but I wouldn't think this is expected behavior.

**2 qt windows**

![2xtqt](https://github.com/user-attachments/assets/3bfce24a-7495-49d1-b27c-fece5f1f6710)

**2 titlebar items**

![tbar-2xtqt](https://github.com/user-attachments/assets/b9a57aa1-8f53-48f0-94d9-b80ff2fb9e77)

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.6

**Comment by Pentaphon** [comment] 2024-07-13 15:02
Dupe of https://github.com/transmission/transmission/issues/255 I believe

**Closed** 2024-07-14 20:33 UTC
Labels: duplicate
