### ISSUE TITLE
transmission 3.0 client with GUI in macOS Big Sur - almost always block itself and freezes the Mac at regular intervals (daily or so).

### ISSUE THREAD

**Issue by abetancort** [transmission/transmission#1750] opened 2021-08-03 15:39 UTC
Hi,

Using transmission 3.00 with macOS Big Sur, if transmission is allowed to seed and/or download a few files (15-20 counting both) it’ll eventually freeze and with it most of macOS apps running (beach bolls a galore). Shortly afterwards the whole OS becomes extremely unstable and will eventually come to a halt. Forcing the user to manually power-down the Mac where transmission is running.

While the macOS is unstable, unusable, you can do a safe restart or shutdown of the Mac, the transmission app is still running (frozen), thus not responding to the signals send by the OS. Disabling the ability of the OS to proceed with the proper shutdown

Trying a somewhat controlled but not perfect shutdown, I have tried to force quit transmission and after a few tries it’ll disappear from the dock. If I had any hopes, they were in vain, the OS will inform it’s not able to shutdown because transmission is still running. 

Now, getting lucky some times, I have got to these before the system totally freezes. Looking in the system monitor for any processes with the transmission name or something similar. I have found nil. But if I try to open transmission again, it’ll, transmission, complain that it can’t be done because there’s another instance already running. 

Looking the console and trying to find any entries about transmission (activity.logs, application crashes.logs or anything in the system log), there are be none. Either transmission for macOS doesn’t use macOS standard logging facility or doesn’t log anything at all.  I doubt the second, because transmission is a well developed multiplaform torrent client whose development cycle is very mature. But I have yet to figure out where those logs are filed in the Mac. 

It’s a pity because it has been the go to torrent client (GUI or not) for the Mac platform since ever. 

Whatever, I’ll try to find the root causes next week or so, if to no avail, I’ll try the transmission daemon for a week to see if it behaves differently or if at least I’m able find an analyze those dammed logs. 

If everything turn out to be futile and with despair move to another torrent client, waiting to return as soon as someone more versed finds the root cause and it is either fixed or patched somehow. 

Thanks mate.

**Comment by vga-256** [comment] 2022-08-26 19:45
Can confirm exactly the same behaviour in Mojave (10.14.6) with 3.0. Kills downloads, then hardlocks the app after a short amount of time. Force-quit to exit, and then the app can't be restarted due to another process blocking it.

**Comment by ckerr** [comment] 2022-08-26 20:31
Duplicate of https://github.com/transmission/transmission/issues/2462

**Closed by ckerr** 2022-08-26 20:31 UTC
