### ISSUE TITLE
Add option to remove/block selected peer

### ISSUE THREAD

**Issue by muthu32** [transmission/transmission#293] opened 2017-05-27 01:46 UTC
When I download movies, some peers are just uploading and not downloading the file. This cause me to loss big amount of data. To avoid max. loss, I am used to set upload limit to 100kb.
But problem of upload while download is still exist and this is caused by some peers.
Utorrent have some tricks to block unwanted Peers.
http://www.tricksuniversity.in/how-to-remove-peers-from-utorrent.html 
I want an option to delete/block Peers for torrents.

**Comment by Astara** [comment] 2017-07-12 10:45
If a peer has the whole file, why would it need to download?  Wouldn't it only 'upload'?  Also don't be confused by what peers seem to be doing with you -- if they don't have the whole torrent, they might downloading from other peers.  In fact in a super-seeder setup, each peer sends what it gets to another peer -- not to the same peer.  If you block them from downloading from you, you may break the chain.

**Comment by muthu32** [comment] 2017-07-13 06:17
transmission already has a block list. => Can you tell me how to do it in transmission.

**Comment by Astara** [comment] 2017-07-13 06:46
I don't use the windows version, but if you run the transmission-remote with the help option you can see a reference to the block list.  I've never used it, but perhaps searching for "how to use transmission blocklist" in google will lead you to info on how to do it.
Like I said, though, you may end up hurting your own performance.  You shouldn't have any problems with
data loss such that you need to block clients.  It's perfectly normal for clients to only engage in 1-way communication with a peer while they are getting 'fed' by other peers.  

I can download much faster than upload, so if a client is transferring data to me, they might not want to wait around for my slow return speed, and may be getting their data from a faster client.  If you block them, you'll *likely*, only find it slows down your overall transfer speed.

If you want to manage your upload v. downloaded amount, set your allowed rates for your downloaded amount to something real low, like 10KB (or other way around if that's your issue).

**Closed** 2017-07-13 10:16 UTC

**Comment by gkaklas** [comment] 2017-08-21 09:55
Hello

I'm not a developer of transmission, just a user, but I would like to add a few notes:

* Blocklists are for a very specific purpose, I think for blocking peers that are malicious (attacking) to the swarm, copyright companies etc. The peers you are describing are not considered harmful, they are just acting based on a protocol.
* Trust the Bittorrent protocol and your client that they automatically and by design do the best possible in order for everyone to download the torrent as fast as possible, you don't need to do anything at all. Many people have sat down for years and thought very carefully how is the best way to do this, and they know what they are doing. Even if you think that a peer is bad, it may not be (read below)
* The Bittorrent protocol [has predicted](https://en.wikipedia.org/wiki/Tit_for_tat#Peer-to-peer_file_sharing) that there may be users who download but not upload, and the clients block such users automatically -- everyone gets as long as they give.

BTW from what I understand because of the last point and some other rules, if you limit your upload speed as you did, your download speed will never reach its full capacity. Also, seeders might refuse to connect to you, since they prefer to seed to the users with the fastest upload first, so they can seed to others and increase the overall speed of the swarm. Not my field though, I may be wrong.

It is very possible that someone is not giving the file to you because you already have downloaded what they have to give you. You still want to connect to this peer, because in the future they will download a new part from someone else, then they will give it to you etc. The whole bittorrent swarm is based on the fact that each peer will get a different part of the file, then they will share it with each other until everyone gets all the files. Blocking users by yourself because you don't like them is bad for everyone, including yourself, and so is limiting your upload speed.

Hope I helped!
