### ISSUE TITLE
Transmission GTK becomes unresponsive randomally when using the GUI

### ISSUE THREAD

**Issue by duduedri96** [transmission/transmission#730] opened 2018-10-04 17:35 UTC
From time to time, when using the GTK GUI of Transmission, it suddenly becomes unresponsive for keyboard/mouse presses. The downloads continue to progress and the window is updated with information - speed, ETA, etc., but it is not possible to control the GUI (e.g. start a new torrent).

Journalctl shows the following assertion error continuously when trying to interact with the GUI when it is unresponsive:
transmission-gt[27249]: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

Thanks.

**Comment by Riotous** [comment] 2018-10-05 06:16
I think the GTK version is being phased out in favor of the Qt version for Linux and Windows so this may not matter any longer.

**Comment by 6wl** [comment] 2019-01-02 14:04
> I think the GTK version is being phased out in favor of the Qt version for Linux and Windows so this may not matter any longer.

Really hope that's not the case.

**Comment by ckerr** [comment] 2020-05-17 02:03
It's true that the Qt client has seen more activity lately, but the GTK client isn't going anywhere.

**Comment by ckerr** [comment] 2022-01-24 05:50
Closing as a dupe of #2462. I realize this ticket was filed before 2462, but there are so many overlapping tickets at this point that it makes sense to start with a new "big picture" ticket.

**Closed by ckerr** 2022-01-24 05:50 UTC
Labels: bug, scope:gtk
