### ISSUE TITLE
Info Request: interface binding

### ISSUE THREAD

**Issue by geraldsnm** [transmission/transmission#1689] opened 2021-05-10 17:08 UTC
Can you folks comment if this was ever properly implemented on Linux? 
https://trac.transmissionbt.com/ticket/2313

I found the config parameters bind-interface-* and I tried to set as follows with no apparent luck:

    "bind-interface-device": "tun0",
    "bind-interface-enabled": true,

I need the ability to permanently configure the interface name so that as IP address changes on my VPN connection it continues to work without needing to update the configuration. 

Any help you can provide is greatly appreciated. Thx

**Comment by nepthar** [comment] 2021-10-29 21:04
This has been a requested feature for TWELVE years. Hey developers - I'll donate $100 to this project if this feature is implemented (properly).

Also, if I've missed something and it's already developed, I'll donate that same $100 once someone shows me how to get it to work.

**Comment by ckerr** [comment] 2022-01-18 22:25
@nepthar a PR would be more welcome than $100. I'm not your monkey.

**Comment by ckerr** [comment] 2022-02-25 22:15
This is a duplicate of This is a duplicate of https://github.com/transmission/transmission/issues/338

**Closed by ckerr** 2022-02-25 22:15 UTC
Labels: enhancement, scope:core, pr welcome
