### ISSUE TITLE
download queue limit ignored

### ISSUE THREAD

**Issue by minusf** [transmission/transmission#906] opened 2019-05-11 10:45 UTC
If a monitored folder is set with many torrent files in it, after startup Transmission starts processing all of them ignoring the "Download with maximum of" setting. Pausing and unpausing applies the correct limit.

**Comment by ckerr** [comment] 2022-02-25 04:35
Duplicate of https://github.com/transmission/transmission/issues/379 (though it is reporting for the seed limit, but it's the same issue)

**Closed by ckerr** 2022-02-25 04:35 UTC
