### ISSUE TITLE
"Test Port" incorrectly says "Port is closed" on system with both IPv4 and IPv6, caused by portcheck.transmissionbt.com

### ISSUE THREAD

**Issue by sanderjo** [transmission/transmission#1190] opened 2020-04-26 12:12 UTC
transmission-2.94

"Test Port" incorrectly says "Port is closed" on my system which has both IPv4 and IPv6.

![image](https://user-images.githubusercontent.com/1273502/80307024-ea283780-87c6-11ea-815f-aeddfa40754a.png)

Cause http://portcheck.transmissionbt.com/ is incorrectly configured for IPv6, resulting in http://portcheck.transmissionbt.com/51413 giving in Chrome

> This page isn’t working
> If the problem continues, contact the site owner.
> HTTP ERROR 400

If I force IPv4, it goes OK:

```
$ curl -4 http://portcheck.transmissionbt.com/51413
1
```

**Workaround so that all transmission clients work again without software change: transmissionbt.com's DNS admin removes the IPv6 resolution**

```
$ host portcheck.transmissionbt.com
portcheck.transmissionbt.com is an alias for vm4.transmissionbt.com.
vm4.transmissionbt.com has address 87.98.162.88
vm4.transmissionbt.com has IPv6 address 2001:41d0:c:5ac:5::1
```

Trigger is a default request, which uses IPv6, also from within transmission, on a web server that gives `400 Bad Request` if you approach it via IPv6:

```
$ curl -v http://portcheck.transmissionbt.com/51413
*   Trying 2001:41d0:c:5ac:5::1:80...
* TCP_NODELAY set
* Connected to portcheck.transmissionbt.com (2001:41d0:c:5ac:5::1) port 80 (#0)
> GET /51413 HTTP/1.1
> Host: portcheck.transmissionbt.com
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Server: nginx/1.10.3 (Ubuntu)
< Date: Sun, 26 Apr 2020 12:05:24 GMT
< Content-Type: text/html; charset=ISO-8859-1
< Transfer-Encoding: chunked
< Connection: keep-alive
< 
* Connection #0 to host portcheck.transmissionbt.com left intact
```
So: request via IPv6 results in `HTTP/1.1 400 Bad Request`

Correcting the website for IPv6 is probably not a good idea, because that would check the IPv6 connectivity, whereas the user probably wants to check IPv4 connectivity through NAT.

Best solution: check both!

**Comment by slokhorst** [comment] 2020-05-23 12:51
Duplicate of #381

**Comment by JPUnD** [comment] 2020-08-11 19:21
So transmission claiming that the port is closed is "cosmetic"?

The firewall on my server looks like:
```
$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
8181                       ALLOW       Anywhere                   # peer port
8181 (v6)                  ALLOW       Anywhere (v6)              # peer port
```

And my router looks like:
![image](https://user-images.githubusercontent.com/41581666/89939505-f5855e80-dc0f-11ea-9c2a-10e5eb4600b2.png)

I have the same scheme for Wireguard and it works, so I'm assuming that transmission isn't running into issues because the `transgui` on my computer says that the port is closed, right?

The strange thing is if i run a service like canyouseeme.org if I check the wireguard port the connection timeouts, while transmission says connection refused, I'm assuming this is the way transmission answers to incoming packets? Or am I doing something wrong? I know that Wireguard works that's for sure.

**Comment by diegorodriguezv** [comment] 2020-10-27 01:18
This was driving me crazy. I disabled IPv6 in my router and the port is now shown as open. Please fix it! 
<3

**Comment by undgang** [comment] 2020-12-29 14:06
> This was driving me crazy. I disabled IPv6 in my router and the port is now shown as open. Please fix it!
> <3

Same issue here.enable ipv6: webgui no response ; transgui baad request.
After disable ipv6 on my router : All fine!
By the way, I'm using synology nas.
Hope developers fix them asap.

**Comment by ckerr** [comment] 2022-01-26 07:22
This is a duplicate of #381

**Closed by ckerr** 2022-01-26 07:22 UTC
