### ISSUE TITLE
Does not download anything at all

### ISSUE THREAD

**Issue by ProdigyESP** [transmission/transmission#6795] opened 2024-04-15 20:53 UTC
### What is the issue?

Do not download magnet links.
Does not download torrent files.
I add the link or torrent file, copy the address of the destination folder because there is no button to select the location where you want to save the torrent and when I hit open..... nothing happens! xD I literally read that it was the most powerful torrent manager that exists and it does absolutely NOTHING.
A total disappointment

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.5

**Comment by Pentaphon** [comment] 2024-04-16 06:05
There is a issue where the "save to" location doesn't show up until you restart the client after the first run https://github.com/transmission/transmission/issues/3708 on Windows. 

However, does your torrent even have peers? Have you tried again with a popular torrent like a Linux distro?

**Comment by killemov** [comment] 2024-04-16 07:11
Duplicate of #6772? Test with a popular Linux distro torrent please.

**Closed** 2024-04-22 12:36 UTC
Labels: duplicate
