### ISSUE TITLE
Transmission freeze when moving files to shared folder

### ISSUE THREAD

**Issue by neofleo** [transmission/transmission#5767] opened 2023-07-11 20:11 UTC
### What is the issue?

My Transmission is freeezing and not acessible when moving files from temp folder on local machine and local drive to a mounted folder from a distant machine using NFS ("sudo mount -t cifs -o vers=3.0,file_mode=0777,dir_mode=0777,credentials=/root/.examplecredentials //IP/DISTANTFOLDER /LOCALFOLDER")
Everything is fine on that mounted folder I check permisisons and when moving is done (but moving is done since minuts but Transmission still not up), Transmission come back like a flower.

Deluge and other downloaders can handle this with any problems but Transmission don't want.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

latest linuxserver/transmission

**Comment by ckerr** [comment] 2023-07-12 03:17
This is a duplicate of https://github.com/transmission/transmission/issues/2462

**Closed by ckerr** 2023-07-12 03:17 UTC
