### ISSUE TITLE
macOS nightly 3.00+ (c50da43ae0) cannot connect to external volume

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3510] opened 2022-07-22 05:30 UTC
More of a headsup, because i found a solution, but....

The client can't connect with an external volume with previously downloaded torrents and tries to re-download all of them. Looking in the prefs, Transmission thinks the external drive is inaccessible. Testing on 3.0 release, there is no issue and everything behaves normally. Reopening 3.00+ (c50da43ae0), the drive is now seemingly accessible, but the client still wants to download the torrents.

I've checked the external drive permissions and it's about as open as it can possibly be. 

Verifying local data on all of the previously downloaded torrents seems to fix the issue.

**Comment by ckerr** [comment] 2022-07-22 06:22
I think this what #3508 was trying to say, so I'm going to close this as a duplicate. I believe this is resolved by 0da1cbb6ecaa405ec36a3736924cd20f4822ed2a but please do lmk if that' s incorrect

Duplicate of #3508.

**Closed by ckerr** 2022-07-22 06:22 UTC
