### ISSUE TITLE
transmission-gtk needs "GDK_BACKEND=x11" on Ubuntu 21.10

### ISSUE THREAD

**Issue by Zorono** [transmission/transmission#2522] opened 2022-01-26 19:57 UTC
Hello every Creature,
**transmission-gtk** requires setting GDK_BACKEND to x11 in order to work...

My **$HOME/.config/transmission/settings.json**: 
```
{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-updates-enabled": true,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 150,
    "compact-view": false,
    "details-window-height": 527,
    "details-window-width": 700,
    "dht-enabled": true,
    "download-dir": "/sda9/Downloads/Torrenting",
    "download-queue-enabled": true,
    "download-queue-size": 25,
    "encryption": 2,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/sda9/Downloads/Torrenting/InProgress",
    "incomplete-dir-enabled": true,
    "inhibit-desktop-hibernation": false,
    "lpd-enabled": true,
    "main-window-height": 615,
    "main-window-is-maximized": 0,
    "main-window-width": 856,
    "main-window-x": 56,
    "main-window-y": 50,
    "message-level": 2,
    "open-dialog-dir": "/sda9/Downloads/",
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 56357,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": true,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": true,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 0.2500,
    "ratio-limit-enabled": false,
    "recent-download-dir-1": "/sda9/Downloads/Torrenting",
    "rename-partial-files": true,
    "rpc-authentication-required": true,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": true,
    "rpc-password": "___{HIDDEN}___",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "filthy",
    "rpc-whitelist": "127.0.0.1,::1",
    "rpc-whitelist-enabled": true,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "/home/zorono",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "show-backup-trackers": false,
    "show-extra-peer-details": true,
    "show-filterbar": true,
    "show-notification-area-icon": true,
    "show-options-window": true,
    "show-statusbar": true,
    "show-toolbar": true,
    "show-tracker-scrapes": true,
    "sort-mode": "sort-by-progress",
    "sort-reversed": false,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "statusbar-stats": "total-transfer",
    "torrent-added-notification-enabled": true,
    "torrent-complete-notification-enabled": true,
    "torrent-complete-sound-command": "canberra-gtk-play -i complete-download -d 'transmission torrent downloaded'",
    "torrent-complete-sound-enabled": true,
    "trash-can-enabled": true,
    "trash-original-torrent-files": false,
    "umask": 18,
    "upload-slots-per-torrent": 14,
    "user-has-given-informed-consent": true,
    "utp-enabled": true,
    "watch-dir": "/sda9/Downloads",
    "watch-dir-enabled": false
}
```

Operating System: Debian
Distributor: Ubuntu
Distributor Release: 21.10
Distributor Codename: Impish Indri
Operating System Architecture: amd64
Distributor Life Cycle: Non-LTS
Kernel Version: 5.13.0-27-generic
Windowing System: Wayland
Environment: Gnome
Environment Version: 40.4.0

**Comment by ckerr** [comment] 2022-01-26 20:05
I'm not able to reproduce this issue and suspect it is going to be a configuration issue on  your machine -- I run transmission-gtk at least once a day on an amd64 21.10 box running wayland and am not seeing this problem. Before writing this comment I confirmed that it does wfm in that environment, both with stock transmission-gtk and with a build from `main`.

**Comment by ckerr** [comment] 2022-03-05 15:57
Closing as a duplicate of https://github.com/transmission/transmission/issues/2572

**Closed by ckerr** 2022-03-05 15:57 UTC
Labels: needs clarification, scope:gtk, de:gnome3
