### ISSUE TITLE
WebUI Stops Working While Setting New Location

### ISSUE THREAD

**Issue by Jorsher** [transmission/transmission#6384] opened 2023-12-15 23:35 UTC
### What is the issue?

It appears that while moving a torrent (setting a new location), Transmission stops doing anything else. I'm moving some very large torrents (100s of GBs) and have noticed WebUI is inaccessible (never stops trying to load)

The processes still show as running with activity. Free space is decreasing on the volume the files are being moved to. I guess moving torrents causes webui to stop until the move is complete?

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.4

**Comment by killemov** [comment] 2023-12-17 18:14
Hey there. This is a well known phenomenon. It's currently best not to move large files across filesystem barriers. Copy the the entire content to it's destination manually (cp -rupa) and then set the new location without moving content in transmission and then remove the content at the old location.

**Comment by tearfur** [comment] 2023-12-18 01:28
Closing as a duplicate of #2462.

**Closed by tearfur** 2023-12-18 01:28 UTC
