### ISSUE TITLE
XXX.torrent is not a valid torrent file.

### ISSUE THREAD

**Issue by oceanzhang01** [transmission/transmission#2632] opened 2022-02-16 11:37 UTC
![image](https://user-images.githubusercontent.com/17286950/154256865-e9cde632-1df8-4dbd-bf7e-0acf77d62c0e.png)
[D92EA5798DE081B821278EAB8F6E380C9CFD2AE1.torrent.zip](https://github.com/transmission/transmission/files/8079519/D92EA5798DE081B821278EAB8F6E380C9CFD2AE1.torrent.zip)
other bt downloader like 'libtorrent' ,'qtorrent' is ok.

**Comment by ckerr** [comment] 2022-02-16 16:42
This is a duplicate of #1964. Fixed in the [nightly builds](https://transmissionbt.com/download)

**Closed by ckerr** 2022-02-16 16:42 UTC
Labels: duplicate
