### ISSUE TITLE
Paused torrents show as 0% downloaded when migrating Transmission 3.00 to 4.0.1

### ISSUE THREAD

**Issue by radupotop** [transmission/transmission#5070] opened 2023-02-26 22:26 UTC
### What is the issue?

I use the transmission-daemon with the webui.  Migration is from Transmission 3.00 to 4.0.1. OS is ArchLinux.

After migrating to 4.0.1, some torrents which were previously paused (but 100% downloaded) now show as 0% downloaded and paused. This is not true since the data is there. I tried to run the "verify data" option on them but it doesn't work.

A separate issue I've been seeing during this migrations is that some torrents which I have renamed from their original names (to ones which i found more descriptive), were now downloaded again under their old names set by the torrent creators.

I have since migrated back to 3.00 and these issues went away.
(I made a copy of the `/srv/transmission/.config/transmission-daemon/` folder before upgrading, just in case issues arise.)

Let me know if I can provide more details to help you sort out these issues with version 4.

Thanks

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.1

**Comment by ckerr** [comment] 2023-02-26 23:33
Hey @radupotop thanks for reporting this.

I think this is a duplicate of https://github.com/transmission/transmission/issues/5007 so I'm going to close this as a dupe.

5007 is fixed by https://github.com/transmission/transmission/pull/5025 which has been merged into `main` and will be imcluded in 4.0.2.

**Closed by ckerr** 2023-02-26 23:33 UTC
