### ISSUE TITLE
error: required file 'third-party/dht/Makefile.in' not found

### ISSUE THREAD

**Issue by mfe-** [transmission/transmission#4403] opened 2022-12-18 18:35 UTC
### What is the issue?

when trying to build transmission 3.0 with `./autogen.sh` it fails with

```bash
configure.ac:651: error: required file 'third-party/dht/Makefile.in' not found
configure.ac:651: error: required file 'third-party/libb64/Makefile.in' not found
configure.ac:651: error: required file 'third-party/libutp/Makefile.in' not found
configure.ac:651: error: required file 'third-party/libnatpmp/Makefile.in' not found
configure.ac:651: error: required file 'third-party/miniupnpc/Makefile.in' not found
```

Complete command output
```bash
transmission-3.00# ./autogen.sh 
creating libtransmission/version.h
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:109: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:109: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:109: the top level
configure.ac:110: warning: The macro `AC_HEADER_TIME' is obsolete.
configure.ac:110: You should run autoupdate.
./lib/autoconf/headers.m4:743: AC_HEADER_TIME is expanded from...
configure.ac:110: the top level
configure.ac:116: warning: The macro `AC_LANG_C' is obsolete.
configure.ac:116: You should run autoupdate.
./lib/autoconf/c.m4:72: AC_LANG_C is expanded from...
m4/acx-pthread.m4:13: ACX_PTHREAD is expanded from...
configure.ac:116: the top level
configure.ac:116: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:116: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
m4/acx-pthread.m4:13: ACX_PTHREAD is expanded from...
configure.ac:116: the top level
configure.ac:565: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:565: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
m4/glib-gettext.m4:48: GLIB_LC_MESSAGES is expanded from...
m4/glib-gettext.m4:298: GLIB_GNU_GETTEXT is expanded from...
m4/glib-gettext.m4:395: AM_GLIB_GNU_GETTEXT is expanded from...
configure.ac:565: the top level
configure.ac:565: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:565: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/headers.m4:89: _AC_CHECK_HEADER_COMPILE is expanded from...
./lib/autoconf/headers.m4:56: AC_CHECK_HEADER is expanded from...
m4/glib-gettext.m4:102: GLIB_WITH_NLS is expanded from...
m4/glib-gettext.m4:298: GLIB_GNU_GETTEXT is expanded from...
m4/glib-gettext.m4:395: AM_GLIB_GNU_GETTEXT is expanded from...
configure.ac:565: the top level
configure.ac:565: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:565: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/headers.m4:89: _AC_CHECK_HEADER_COMPILE is expanded from...
./lib/autoconf/headers.m4:56: AC_CHECK_HEADER is expanded from...
m4/glib-gettext.m4:102: GLIB_WITH_NLS is expanded from...
m4/glib-gettext.m4:298: GLIB_GNU_GETTEXT is expanded from...
m4/glib-gettext.m4:395: AM_GLIB_GNU_GETTEXT is expanded from...
configure.ac:565: the top level
configure.ac:565: warning: The macro `AC_OUTPUT_COMMANDS' is obsolete.
configure.ac:565: You should run autoupdate.
./lib/autoconf/status.m4:1025: AC_OUTPUT_COMMANDS is expanded from...
m4/glib-gettext.m4:102: GLIB_WITH_NLS is expanded from...
m4/glib-gettext.m4:298: GLIB_GNU_GETTEXT is expanded from...
m4/glib-gettext.m4:395: AM_GLIB_GNU_GETTEXT is expanded from...
configure.ac:565: the top level
configure.ac:20: installing './compile'
configure.ac:20: installing './config.guess'
configure.ac:20: installing './config.sub'
configure.ac:19: installing './install-sh'
configure.ac:19: installing './missing'
configure.ac:651: error: required file 'third-party/dht/Makefile.in' not found
configure.ac:651: error: required file 'third-party/libb64/Makefile.in' not found
configure.ac:651: error: required file 'third-party/libutp/Makefile.in' not found
configure.ac:651: error: required file 'third-party/libnatpmp/Makefile.in' not found
configure.ac:651: error: required file 'third-party/miniupnpc/Makefile.in' not found
cli/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
autoreconf: error: automake failed with exit status: 1
```
Any help apprechiated.

### Which application of Transmission?

None

### Which version of Transmission?

3.0.0

**Comment by GaryElshaw** [comment] 2022-12-18 19:49
i think you might be missing the full complement of third party stuff. First time building is as follows.

`$ git clone https://github.com/transmission/transmission Transmission
$ cd Transmission
$ git submodule update --init --recursive
$ mkdir build
$ cd build
$ # Use -DCMAKE_BUILD_TYPE=RelWithDebInfo to build optimized binary.
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
$ make
$ sudo make install`

**Comment by mfe-** [comment] 2022-12-19 17:50
Hi,
I used the attached source code from https://github.com/transmission/transmission/releases/tag/3.00
Since my system doesnt have cmake I need to use configure and make

**Comment by ckerr** [comment] 2022-12-19 18:28
Most of the development effort at the moment is being spent on getting a stable 4.0.0 release out the door, so the only 3.00 issues that will get attention are if there's some critical bug in 3 (e.g. data corruption) or if the issue is still present in 4. Since the autotools build scripts were remove over two years ago in https://github.com/transmission/transmission/pull/1465, this doesn't meet either criteria so I'm going to close this issue.

Possible workarounds: you could try building on another system and/or installing cmake on your target system

**Closed by ckerr** 2022-12-19 18:28 UTC
