### ISSUE TITLE
Nightly crashed get_peer_stats

### ISSUE THREAD

**Issue by dantearmok** [transmission/transmission#6212] opened 2023-11-05 16:10 UTC
### What is the issue?

Mac mini (late 2012, 2.5-GHz 4-Core i5), 16GB RAM, plus an assortment of USB & FW HDs.
macOS Ventura 13.6.1 (w/OCLP 1.1.0), PeakHour 4.1.16, PIA 3.5.1, and Xcode 15.0.1.
Pipe is 450 Mbps wifi to Comcast coax 100/25 Mbps, with PIA beaming me thru to Bahamas.
Transmission uses a FW Drobo (long-term seeding) and three USB hard drives.

Running Transmission-9cadcbdb86 Build #9404 (Nov 4, 2023, 7:18:40 PM)

Transmission was seeding lots for almost 12 hours, then it crashed.

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Transmission [2492]
Path:                  /Users/USER/*/Transmission.app/Contents/MacOS/Transmission
Identifier:            org.m0k.transmission
Version:               4.1.0-dev (14714.4.1.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2023-11-05 05:16:21.4665 -0500
OS Version:            macOS 13.6.2 (22G417)
Report Version:        12
Anonymous UUID:        9D83084F-22F2-20FB-B0D2-056E94905F2F

Time Awake Since Boot: 40000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   Transmission [2492]

Application Specific Information:
abort() called

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff81b3a91e2 __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff81b3e0ee6 pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff81b307b45 abort + 123
3   libc++abi.dylib               	    0x7ff81b39b282 abort_message + 241
4   libc++abi.dylib               	    0x7ff81b39acb2 __cxa_pure_virtual + 18
5   Transmission                  	       0x108bc86fc (anonymous namespace)::peer_stat_helpers::get_peer_stats(tr_peerMsgs const*, long, unsigned long long) + 698 (peer-mgr.cc:1645) [inlined]
6   Transmission                  	       0x108bc86fc auto tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_5::operator()<tr_peerMsgs>(tr_peerMsgs const*) const + 698 (peer-mgr.cc:1732) [inlined]
7   Transmission                  	       0x108bc86fc tr_peer_stat* std::__1::transform<std::__1::__wrap_iter<tr_peerMsgs* const*>, tr_peer_stat*, tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_5>(std::__1::__wrap_iter<tr_peerMsgs* const*>, std::__1::__wrap_iter<tr_peerMsgs* const*>, tr_peer_stat*, tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_5) + 732 (transform.h:29) [inlined]
8   Transmission                  	       0x108bc86fc tr_peerMgrPeerStats(tr_torrent const*, unsigned long*) + 917 (peer-mgr.cc:1728)
9   Transmission                  	       0x108af2b3f -[Torrent peers] + 59 (Torrent.mm:938)
10  Transmission                  	       0x108b44e9d -[InfoPeersViewController updateInfo] + 1060 (InfoPeersViewController.mm:154)
11  Transmission                  	       0x108b09434 -[InfoWindowController updateInfoStats] + 48 (InfoWindowController.mm:468)
12  Transmission                  	       0x108ac0d9f -[Controller updateUI] + 904 (Controller.mm:2322)
13  Foundation                    	    0x7ff81c2e5716 __NSFireTimer + 67
14  CoreFoundation                	    0x7ff81b4d5b42 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
15  CoreFoundation                	    0x7ff81b4d56bf __CFRunLoopDoTimer + 807
16  CoreFoundation                	    0x7ff81b4d52da __CFRunLoopDoTimers + 285
17  CoreFoundation                	    0x7ff81b4bb7b8 __CFRunLoopRun + 2210
18  CoreFoundation                	    0x7ff81b4ba8bc CFRunLoopRunSpecific + 560
19  HIToolbox                     	    0x7ff825406f3d RunCurrentEventLoopInMode + 292
20  HIToolbox                     	    0x7ff825406d4e ReceiveNextEventCommon + 657
21  HIToolbox                     	    0x7ff825406aa8 _BlockUntilNextEventMatchingListInModeWithFilter + 64
22  AppKit                        	    0x7ff81e4b625c _DPSNextEvent + 858
23  AppKit                        	    0x7ff81e4b5106 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1214
24  AppKit                        	    0x7ff81e4a7788 -[NSApplication run] + 586
25  AppKit                        	    0x7ff81e47b9a1 NSApplicationMain + 817
26  Transmission                  	       0x108ab011f main + 73 (main.mm:17)
27  dyld                          	    0x7ff81b08741f start + 1903

Thread 1:
0   Transmission                  	       0x108bb4234 math::wide_integer::uintwide_t<1536u, unsigned int, void, false>::eval_divide_knuth(math::wide_integer::uintwide_t<1536u, unsigned int, void, false> const&, math::wide_integer::uintwide_t<1536u, unsigned int, void, false>*) + 58 (uintwide_t.h:3620)
1   Transmission                  	       0x108bb2b3a math::wide_integer::uintwide_t<1536u, unsigned int, void, false>::operator%=(math::wide_integer::uintwide_t<1536u, unsigned int, void, false> const&) + 87 (uintwide_t.h:1789) [inlined]
2   Transmission                  	       0x108bb2b3a math::wide_integer::uintwide_t<768u, unsigned int, void, false> math::wide_integer::powm<math::wide_integer::uintwide_t<160u, unsigned int, void, false>, math::wide_integer::uintwide_t<768u, unsigned int, void, false>, 768u, unsigned int, void, false>(math::wide_integer::uintwide_t<768u, unsigned int, void, false> const&, math::wide_integer::uintwide_t<160u, unsigned int, void, false> const&, math::wide_integer::uintwide_t<768u, unsigned int, void, false> const&) + 973 (uintwide_t.h:5164)
3   Transmission                  	       0x108bb2594 tr_message_stream_encryption::generatePublicKey(std::__1::array<std::byte, 20ul> const&) + 89 (peer-mse.cc:81)
4   Transmission                  	       0x108bb2f02 tr_message_stream_encryption::DH::publicKey() + 114 (peer-mse.cc:89)
5   Transmission                  	       0x108bb4d0f void tr_handshake::send_public_key_and_pad<512ul>(tr_peerIo*) + 57 (handshake.h:171)
6   Transmission                  	       0x108bb4bc2 tr_handshake::send_ya(tr_peerIo*) + 514 (handshake.cc:40)
7   Transmission                  	       0x108bbd84c tr_handshake::tr_handshake(tr_handshake::Mediator*, std::__1::shared_ptr<tr_peerIo>, tr_encryption_mode, std::__1::function<bool (tr_handshake::Result const&)>) + 416 (handshake.cc:828)
8   Transmission                  	       0x108bcac6b std::__1::__unique_if<tr_handshake>::__unique_single std::__1::make_unique<tr_handshake, (anonymous namespace)::HandshakeMediator*, std::__1::shared_ptr<tr_peerIo>&, tr_encryption_mode, (anonymous namespace)::connect_helpers::initiate_connection(tr_peerMgr*, tr_swarm*, tr_peer_info&)::$_16>((anonymous namespace)::HandshakeMediator*&&, std::__1::shared_ptr<tr_peerIo>&, tr_encryption_mode&&, (anonymous namespace)::connect_helpers::initiate_connection(tr_peerMgr*, tr_swarm*, tr_peer_info&)::$_16&&) + 101 (unique_ptr.h:728) [inlined]
9   Transmission                  	       0x108bcac6b void tr_peer_info::start_handshake<(anonymous namespace)::HandshakeMediator*, std::__1::shared_ptr<tr_peerIo>&, tr_encryption_mode, (anonymous namespace)::connect_helpers::initiate_connection(tr_peerMgr*, tr_swarm*, tr_peer_info&)::$_16>((anonymous namespace)::HandshakeMediator*&&, std::__1::shared_ptr<tr_peerIo>&, tr_encryption_mode&&, (anonymous namespace)::connect_helpers::initiate_connection(tr_peerMgr*, tr_swarm*, tr_peer_info&)::$_16&&) + 114 (peer-mgr.h:231) [inlined]
10  Transmission                  	       0x108bcac6b (anonymous namespace)::connect_helpers::initiate_connection(tr_peerMgr*, tr_swarm*, tr_peer_info&) + 851 (peer-mgr.cc:2496) [inlined]
11  Transmission                  	       0x108bcac6b tr_peerMgr::make_new_peer_connections() + 2615 (peer-mgr.cc:2532)
12  Transmission                  	       0x108bca037 tr_peerMgr::reconnect_pulse() + 3173 (peer-mgr.cc:2211)
13  Transmission                  	       0x108bcb3ce tr_peerMgr::bandwidth_pulse() + 162 (peer-mgr.cc:2252)
14  Transmission                  	       0x108c63a63 event_persist_closure + 210 (event.c:1623) [inlined]
15  Transmission                  	       0x108c63a63 event_process_active_single_queue + 1121 (event.c:1682)
16  Transmission                  	       0x108c60903 event_process_active + 220 [inlined]
17  Transmission                  	       0x108c60903 event_base_loop + 1134 (event.c:2006)
18  Transmission                  	       0x108bb1735 tr_session_thread_impl::sessionThreadFunc(event_base*) + 87 (session-thread.cc:239)
19  Transmission                  	       0x108bb1b07 decltype(*static_cast<tr_session_thread_impl*>(fp0).*fp(static_cast<event_base*>(fp1))) std::__1::__invoke<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, void>(void (tr_session_thread_impl::*&&)(event_base*), tr_session_thread_impl*&&, event_base*&&) + 30 (type_traits:3859) [inlined]
20  Transmission                  	       0x108bb1b07 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, 2ul, 3ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>&, std::__1::__tuple_indices<2ul, 3ul>) + 30 (thread:287) [inlined]
21  Transmission                  	       0x108bb1b07 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>>(void*) + 63 (thread:298)
22  libsystem_pthread.dylib       	    0x7ff81b3e11d3 _pthread_start + 125
23  libsystem_pthread.dylib       	    0x7ff81b3dcbd3 thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	    0x7ff81b3a4fae __semwait_signal + 10
1   libsystem_c.dylib             	    0x7ff81b297585 nanosleep + 196
2   libc++.1.dylib                	    0x7ff81b32a5b4 std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>> const&) + 73
3   Transmission                  	       0x108bf95dc void std::__1::this_thread::sleep_for<long long, std::__1::ratio<1l, 1000l>>(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l>> const&) + 17 (thread:386) [inlined]
4   Transmission                  	       0x108bf95dc tr_web::Impl::curlThreadFunc() + 448 (web.cc:713)
5   Transmission                  	       0x108bf9851 decltype(*static_cast<tr_web::Impl*>(fp0).*fp()) std::__1::__invoke<void (tr_web::Impl::*)(), tr_web::Impl*, void>(void (tr_web::Impl::*&&)(), tr_web::Impl*&&) + 26 (type_traits:3859) [inlined]
6   Transmission                  	       0x108bf9851 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*>&, std::__1::__tuple_indices<2ul>) + 26 (thread:287) [inlined]
7   Transmission                  	       0x108bf9851 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*>>(void*) + 59 (thread:298)
8   libsystem_pthread.dylib       	    0x7ff81b3e11d3 _pthread_start + 125
9   libsystem_pthread.dylib       	    0x7ff81b3dcbd3 thread_start + 15

Thread 3:
0   libsystem_kernel.dylib        	    0x7ff81b3a71de kevent + 10
1   Transmission                  	       0x108b57eec -[VDKQueue watcherThread:] + 203 (VDKQueue.mm:189)
2   Foundation                    	    0x7ff81c29f5d3 __NSThread__start__ + 1009
3   libsystem_pthread.dylib       	    0x7ff81b3e11d3 _pthread_start + 125
4   libsystem_pthread.dylib       	    0x7ff81b3dcbd3 thread_start + 15

Thread 4:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff81b3a25a2 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff81b3b071d mach_msg2_internal + 78
2   libsystem_kernel.dylib        	    0x7ff81b3a95d4 mach_msg_overwrite + 692
3   libsystem_kernel.dylib        	    0x7ff81b3a288a mach_msg + 19
4   CoreFoundation                	    0x7ff81b4bc9e0 __CFRunLoopServiceMachPort + 145
5   CoreFoundation                	    0x7ff81b4bb46b __CFRunLoopRun + 1365
6   CoreFoundation                	    0x7ff81b4ba8bc CFRunLoopRunSpecific + 560
7   AppKit                        	    0x7ff81e6163f5 _NSEventThread + 132
8   libsystem_pthread.dylib       	    0x7ff81b3e11d3 _pthread_start + 125
9   libsystem_pthread.dylib       	    0x7ff81b3dcbd3 thread_start + 15

Thread 5:: com.apple.coreaudio.AQClient
0   libsystem_kernel.dylib        	    0x7ff81b3a25a2 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff81b3b071d mach_msg2_internal + 78
2   libsystem_kernel.dylib        	    0x7ff81b3a95d4 mach_msg_overwrite + 692
3   libsystem_kernel.dylib        	    0x7ff81b3a288a mach_msg + 19
4   CoreFoundation                	    0x7ff81b4bc9e0 __CFRunLoopServiceMachPort + 145
5   CoreFoundation                	    0x7ff81b4bb46b __CFRunLoopRun + 1365
6   CoreFoundation                	    0x7ff81b4ba8bc CFRunLoopRunSpecific + 560
7   AudioToolbox                  	    0x7ff82b7a3b0b CADeprecated::GenericRunLoopThread::Entry(void*) + 157
8   libAudioToolboxUtility.dylib  	    0x7ff82a5a03ab CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*) + 77
9   libsystem_pthread.dylib       	    0x7ff81b3e11d3 _pthread_start + 125
10  libsystem_pthread.dylib       	    0x7ff81b3dcbd3 thread_start + 15

Thread 6:: caulk.messenger.shared:17
0   libsystem_kernel.dylib        	    0x7ff81b3a251e semaphore_wait_trap + 10
1   caulk                         	    0x7ff82513d07e caulk::semaphore::timed_wait(double) + 150
2   caulk                         	    0x7ff82513cf9c caulk::concurrent::details::worker_thread::run() + 30
3   caulk                         	    0x7ff82513ccb0 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 41
4   libsystem_pthread.dylib       	    0x7ff81b3e11d3 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff81b3dcbd3 thread_start + 15

Thread 7:: caulk.messenger.shared:high
0   libsystem_kernel.dylib        	    0x7ff81b3a251e semaphore_wait_trap + 10
1   caulk                         	    0x7ff82513d07e caulk::semaphore::timed_wait(double) + 150
2   caulk                         	    0x7ff82513cf9c caulk::concurrent::details::worker_thread::run() + 30
3   caulk                         	    0x7ff82513ccb0 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 41
4   libsystem_pthread.dylib       	    0x7ff81b3e11d3 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff81b3dcbd3 thread_start + 15

Thread 8:
0   libsystem_pthread.dylib       	    0x7ff81b3dcbb0 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	    0x7ff81b3dcbb0 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	    0x7ff81b3dcbb0 start_wqthread + 0

Thread 11:
0   libsystem_pthread.dylib       	    0x7ff81b3dcbb0 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007ff85eabb9c0  rcx: 0x00007ff7b7452af8  rdx: 0x0000000000000000
  rdi: 0x0000000000000103  rsi: 0x0000000000000006  rbp: 0x00007ff7b7452b20  rsp: 0x00007ff7b7452af8
   r8: 0x00007ff7b74529c0   r9: 0x00007ff81b39f191  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x0000000000000103  r13: 0x0000003000000008  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007ff81b3a91e2  rfl: 0x0000000000000246  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x02000148 
Trap Number:     133

### Which application of Transmission?

macOS app

### Which version of Transmission?

Transmission-9cadcbdb86 Build #9404 (Nov 4, 2023, 7:18:40 PM)

**Comment by ckerr** [comment] 2023-11-05 18:34
Duplicate of https://github.com/transmission/transmission/issues/5853, fix @ #5992

**Closed by ckerr** 2023-11-05 18:34 UTC
