### ISSUE TITLE
torrents added from watchdir incorrectly warn: "contains invalid data."

### ISSUE THREAD

**Issue by jtrosper** [transmission/transmission#980] opened 2019-08-20 20:48 UTC
When using the watch folder feature of Transmission, any torrent which Transmission discovers this way says that the torrent file contains invalid data.  This occurs regardless of the torrent file in question - it even said it for the official Ubuntu torrent.

However, the torrent does function correctly once you dismiss the warning.

Additionally, if the torrent file is added to Transmission via normal means, it also functions correctly and does not produce the warning.  It appears to only manifest via the watch folder.

This is with the Linux client, version 2.92 via Ubuntu repos.

**Comment by AD-Wright** [comment] 2020-01-22 20:14
I have also been having this issue - could it be related to: https://github.com/transmission/transmission/blob/c62cb35fd44f76e389d47f9371a6d935cd36fa07/qt/WatchDir.cc#L43-L56 It appears the watchDir function uses a different error handling than other instances of tr_torrentParse - it expects an integer, but torrentParse now returns strings.  I could be wrong, I'm not super familiar with this project.

**Comment by ckerr** [comment] 2022-01-25 22:47
Is this still an issue in the [nightly builds](https://transmissionbt.com/download)? tr_torrentParse() was refactored out and no longer exists

**Comment by ckerr** [comment] 2023-01-27 20:43
It's been a year since the request for info; closing issue.

**Closed by ckerr** 2023-01-27 20:43 UTC
Labels: bug, needs clarification

**Comment by itenev** [comment] 2023-07-03 17:11
Just reproduced with transmission-gtk 3.00 (bb6b5a062e) via the Ubuntu 22.04.2 LTS repos

**Comment by ckerr** [comment] 2023-07-03 19:31
> Just reproduced with transmission-gtk 3.00 (https://github.com/transmission/transmission/commit/bb6b5a062ee594dfd4b7a12a6b6e860c43849bfd) via the Ubuntu 22.04.2 LTS repos

@itenev please see if you can reproduce in 4.0.3 or higher

**Comment by itenev** [comment] 2023-07-04 16:31
4.0.3 works fine. I tested the transmission-daemon built from the transmission-4.0.3.tar.xz sources, by configuring a watch-dir in the demon settings.json

**Comment by ckerr** [comment] 2023-07-04 21:54
@itenev thank you for checking! :bow:
