### ISSUE TITLE
Usability issues with the web ui in v4

### ISSUE THREAD

**Issue by tiagoboldt** [transmission/transmission#5507] opened 2023-05-08 22:49 UTC
### What is the issue?

TransmissionV4 Web UI provides a modal-style torrent info window. This window has some usability issues:
* It hides the download/upload speed information about the selected torrent shown on the top bar;
<img width="364" alt="Screenshot 2023-05-08 at 23 46 58" src="https://user-images.githubusercontent.com/147858/236953793-681b655b-0dac-4343-85e0-86b9ccee28e4.png">
<img width="364" alt="Screenshot 2023-05-08 at 23 47 05" src="https://user-images.githubusercontent.com/147858/236953798-435192ac-057e-4895-87bb-2ddba10698ab.png">

* It overlays text when showing IPv6 addresses;
<img width="559" alt="Screenshot 2023-05-08 at 23 46 08" src="https://user-images.githubusercontent.com/147858/236953660-0fc7d743-5499-4d49-9d99-0853ed7bcc41.png">

* It does not provide a close button, with the user having to try and error until finding how to close it.

These were a regression from v3 web UI, which did not manifest any of the issues above.

### Which application of Transmission?

Web client

### Which version of Transmission?

v4.0.3

**Comment by ckerr** [comment] 2023-05-09 17:08
Duplicate of https://github.com/transmission/transmission/issues/4209

**Closed by ckerr** 2023-05-09 17:08 UTC
