### ISSUE TITLE
downloads don't start automatically

### ISSUE THREAD

**Issue by MagOO33** [transmission/transmission#2656] opened 2022-02-19 11:28 UTC
Hello,
When I use a magnet link on MacOS 12, Arm version, download never starts even if I check the "automatic start after metadata received" bouton.
It starts downloading when I restart it manually.

**Comment by ckerr** [comment] 2022-02-19 13:48
Hi, thanks for reporting this.

I think this is a duplicate of https://github.com/transmission/transmission/issues/2239, so I'm going to closing this issue as a dupe.

**Closed by ckerr** 2022-02-19 13:48 UTC
