### ISSUE TITLE
Transmission nightly build forgets group assignments

### ISSUE THREAD

**Issue by CyberSkull** [transmission/transmission#2772] opened 2022-03-15 01:17 UTC
Transmission 3.00+ (a942c67199) (and prior versions, not sure how far back) keeps forgetting the group assignments of torrents. The only torrents not to loose their groups are the conditionally assigned ones, as it will default back to those on restart of Transmission.

Transmission 3.00+ (a942c67199), macOS 10.15.7.

**Comment by ckerr** [comment] 2022-03-15 22:34
:confused: AFAIK the macOS client's grouping code hasn't changed at all. Maybe a009a7f930f4f6b94ae75f1984ba8f0a40fb7545 ? @sweetppro is that possible?

**Comment by ckerr** [comment] 2022-03-15 22:35
@CyberSkull a009a7f landed on Mar 2. Could you try a build from before and after that date to compare?

**Comment by chaseholden** [comment] 2022-03-16 01:50
macOS 12.3 Monterey - iMac Pro 2017 32GB 1TB SSD
Lost Group bug applicable for at least last two Transmission 3 versions:
- f4489c982e
- 72a67054ea
- Upon launch, All Groups are Completely Lost On Launch except first group & No Group.
- I had perhaps 16 groups for thousands of torrents and they're all completely lost. Extremely frustrating.
- Each group had as many as a thousand torrents. Now all except the first group are just lost to "No Group"
- This happened with each of the past two versions. Using f4489c982e, I manually regrouped each of perhaps a thousand torrents which was completely wasted time since installing 72a67054ea wiped even those out. This is enough to make me quit the beta program. Please tell me there's a way to recover the lost groups!?

**Comment by CyberSkull** [comment] 2022-03-16 07:29
I tried the March 1st build, but it can't load my torrent list at all!

**Comment by CyberSkull** [comment] 2022-03-16 07:38
Same problem shows up in the March 4th 0cd3eb26ff build.

**Comment by morbus** [comment] 2022-03-16 12:29
I've seen this too. I wonder if it's related to the change to the Mac's load torrents code, in https://github.com/transmission/transmission/commit/a009a7f930f4f6b94ae75f1984ba8f0a40fb7545?

If I *manually* assign torrents to a group, then the group is retained as long as the application is open. If I close the app and reopen, all the groups are lost. If, however, I enable "Assign group to new transfers based on criteria", and make a rule based on tracker, then quit and reload the app, the torrents are grouped upon startup, which seems to suggest these "old" torrents are being considered "new transfers" (which would also nicely explain why their group is lost on startup).

**Comment by morbus** [comment] 2022-03-16 12:33
If I use a March 1st build (Transmission-60ef1abadf) then, like CyberSkull, no torrents are loaded at all.

**Comment by morbus** [comment] 2022-03-16 12:50
Ok, so I can confirm there's a "before and after" with https://github.com/transmission/transmission/commit/a009a7f930f4f6b94ae75f1984ba8f0a40fb7545.

Here's what I did (and might be a fix for you to @CyberSkull):

1. Quit whatever nightly I was using.
2. Grab March 1st Transmission-60ef1abadf (#7709).
3. Start Transmission-60ef1abadf. Confirm that no torrents are loaded.
4. Head to ~/Library/Application Support/Transmission/Torrents and double-clicked a torrent.
5. Torrent is loaded in Transmission-60ef1abadf with data intact (location, file naming, etc.)
6. Manually assign that torrent a group.
7. Quit Transmission-60ef1abadf.
8. Start Transmission-60ef1abadf.
9. Group is retained.
10. Double-clicked a hundred or so torrents at a time from ~/Library/Application Support/Transmission/Torrents. (I don't think I'd do a thousand at once, @CyberSkull, as I beach balled when I attempted it and waited for about five minutes with no luck).
11. All torrents imported with data intact (location, file naming, etc.).
12. Manually assigned all the torrents into groups.
13. Quit Transmission-60ef1abadf.
14. Start Transmission-60ef1abadf.
15. Groups are retained.

**Comment by sweetppro** [comment] 2022-03-16 17:51
I see this too,
I can take a look over the weekend and see if there's anything obvious

**Comment by sweetppro** [comment] 2022-03-16 18:09
Ive uploaded a fix in this [PR](https://github.com/transmission/transmission/pull/2777)

**Closed** 2022-03-16 20:16 UTC
Labels: needs clarification

**Comment by morbus** [comment] 2022-03-16 23:35
Can confirm this is fixed in today's nightly, Transmission-4f2472cd93.app.

**Comment by CyberSkull** [comment] 2022-03-16 23:50
Looks fixed now in 4f2472cd93.
