### ISSUE TITLE
transmission web UI says port is not open - even if it's accessible from the outside

### ISSUE THREAD

**Issue by akosmaroy** [transmission/transmission#738] opened 2018-10-13 07:45 UTC
Hi,

I'm trying to get the peer listening port work with transmssion-daemon. I've set up port forwarding in my router appropriately. the forwarding works, e.g. from an external system, I can do the following:

```
$ telnet x.x.x.x 51413
Trying x.x.x.x...
Connected to x.x.x.x.
Escape character is '^]'.
^]
telnet> q
Connection closed.

$ sudo nmap -sU -p 51413 x.x.x.x

Starting Nmap 7.60 ( https://nmap.org ) at 2018-10-13 09:44 CEST
Nmap scan report for x.x.x.x (x.x.x.x)
Host is up (0.060s latency).

PORT      STATE         SERVICE
51413/udp open|filtered unknown

Nmap done: 1 IP address (1 host up) scanned in 1.03 seconds
```

still, the transmission web UI says that the port is closed

what am I doing wrong?

Akos

**Comment by alexiri** [comment] 2018-11-03 18:17
Do you have an IPv6 address? Apparently portcheck.transmissionbt.com doesn't work over IPv6: https://gist.github.com/alexiri/4cb552a699eae3895cafbc4e3d4df8f0

The portcheck service needs to be fixed to support IPv6.

**Comment by akosmaroy** [comment] 2018-11-03 18:33
yes, I have an IPv6 address

does this mean that the check is wrong, but otherwise all is fine? or that because the check is wrong, transmission doesn't see that the appropriate port is exposed and is not working accordingly?

**Comment by alexiri** [comment] 2018-11-03 19:00
You'll have to use some other tool to check if the IPv4 and IPv6 ports are open, like [this one](https://websistent.com/tools/open-port-check-tool/). Either way, I think transmission works just fine, the only issue would be that peers can't initiate connections with you, you have to initiate all of them.

**Comment by akosmaroy** [comment] 2018-11-04 07:58
> You'll have to use some other tool to check if the IPv4 and IPv6 ports are open, like [this one](https://websistent.com/tools/open-port-check-tool/).

I've checked / I know the ports are fine

> Either way, I think transmission works just fine, the only issue would be that peers can't initiate connections with you, you have to initiate all of them.

so than it doesn't work properly

**Comment by andrasfuchs** [comment] 2019-08-07 06:55
I can confirm that something is not working right in the nighty build regarding the port check. It always reports that the port is closed, although it's reported to be open by external websites. 
I reverted to the 2.94 stable (d8e60ee44f) version and it works fine.

As a UI feature request I think it would be very useful to have a small warning icon (maybe on the bottom status bar?) to indicate if the port is closed or open at the moment, so the users could fix it. Since it's not shown now anywhere except the preferences / network tab after clicking on the test port button, it's rarely noticed.

**Comment by treysis** [comment] 2020-01-18 15:22
Problem is difference between IPv4 and IPv6. E.g. IPv4 port is closed for me, but IPv6 is open. The check only supports IPv4. So it will report a closed IPv4 port, while IPv6 port is open and IPv6 peers can also initiate connections with my host. The UI should make a distinction between IPv4 and IPv6. Anything else doesn't make sense at the moment. Too many IPv4-only hosts out there.

**Comment by txVLN** [comment] 2021-12-19 04:07
Looks like there's several copies of this issue. Here's the one with the most activity: https://github.com/transmission/transmission/issues/407

**Comment by ckerr** [comment] 2022-01-26 07:18
I think this is a dupe of https://github.com/transmission/transmission/issues/381 ?

**Closed by ckerr** 2022-01-26 07:18 UTC
