### ISSUE TITLE
Crash on Quit macOS 13.1 arm64 T4b nightly build 26a8c17187 #8566

### ISSUE THREAD

**Issue by chaseholden** [transmission/transmission#4340] opened 2022-12-09 02:12 UTC
### What is the issue?

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Transmission [28523]
Path:                  /Applications/Transmission.app/Contents/MacOS/Transmission
Identifier:            org.m0k.transmission
Version:               4.0.0-beta.2.dev (14714.4.0.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-12-08 18:10:06.7501 -0800
OS Version:            macOS 13.1 (22C65)
Report Version:        12
Anonymous UUID:        C9574617-5AC7-0CB7-EE92-A1FB4E8060A3

Time Awake Since Boot: 100000 seconds

System Integrity Protection: enabled

Crashed Thread:        1

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000000bf2f
Exception Codes:       0x0000000000000001, 0x000000000000bf2f

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [28523]

VM Region Info: 0xbf2f is not in any region.  Bytes before following region: 4331536593
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      1022ec000-1024f8000    [ 2096K] r-x/r-x SM=COW  .../Transmission

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x18887d564 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1888b9638 _pthread_cond_wait + 1232
2   libc++.1.dylib                	       0x188806ac4 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   libc++.1.dylib                	       0x18880769c std::__1::__assoc_sub_state::__sub_wait(std::__1::unique_lock<std::__1::mutex>&) + 56
4   libc++.1.dylib                	       0x188807740 std::__1::__assoc_sub_state::wait() + 56
5   Transmission                  	       0x102397588 tr_sessionClose(tr_session*, unsigned long) + 520
6   Transmission                  	       0x1022f2ca0 -[Controller applicationWillTerminate:] + 1032
7   CoreFoundation                	       0x18898d570 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
8   CoreFoundation                	       0x188a2b054 ___CFXRegistrationPost_block_invoke + 88
9   CoreFoundation                	       0x188a2af9c _CFXRegistrationPost + 440
10  CoreFoundation                	       0x18895eb74 _CFXNotificationPost + 708
11  Foundation                    	       0x18984c72c -[NSNotificationCenter postNotificationName:object:userInfo:] + 88
12  AppKit                        	       0x18be2ce9c -[NSApplication terminate:] + 1092
13  AppKit                        	       0x18bdc0fa0 -[NSApplication(NSResponder) sendAction:to:from:] + 440
14  AppKit                        	       0x18be8d618 -[NSMenuItem _corePerformAction] + 336
15  AppKit                        	       0x18be8d394 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 104
16  AppKit                        	       0x18c17fcc4 -[NSMenu _performActionForItem:atIndex:fromEvent:] + 212
17  AppKit                        	       0x18be8c8a4 -[NSMenu performKeyEquivalent:] + 356
18  AppKit                        	       0x18c2bd404 routeKeyEquivalent + 428
19  AppKit                        	       0x18bd43d68 -[NSApplication(NSEvent) sendEvent:] + 652
20  AppKit                        	       0x18bf96360 -[NSApplication _handleEvent:] + 60
21  AppKit                        	       0x18bc0ba08 -[NSApplication run] + 500
22  AppKit                        	       0x18bbe2e28 NSApplicationMain + 880
23  dyld                          	       0x18858fe50 start + 2544

Thread 1 Crashed:
0   Transmission                  	       0x1023cc5c0 tr_peerIo::setCallbacks(ReadState (*)(tr_peerIo*, void*, unsigned long*), void (*)(tr_peerIo*, unsigned long, bool, void*), void (*)(tr_peerIo*, short, void*), void*) + 0
1   Transmission                  	       0x1023c5854 tr_handshakeDone(tr_handshake*, bool) + 204
2   Transmission                  	       0x1023d676c Handshakes::abortAll() + 56
3   Transmission                  	       0x1023d1754 tr_swarm::stop() + 56
4   Transmission                  	       0x1023a4274 stopTorrent(tr_torrent*) + 176
5   Transmission                  	       0x1023a4430 tr_torrentFreeInSessionThread(tr_torrent*) + 144
6   Transmission                  	       0x102396f00 tr_session::closeImplPart1(std::__1::promise<void>*, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 312
7   Transmission                  	       0x1023c2b84 tr_session_thread_impl::onWorkAvailable() + 116
8   Transmission                  	       0x102455bb8 event_process_active_single_queue + 1092
9   Transmission                  	       0x102452560 event_base_loop + 1068
10  Transmission                  	       0x1023c2900 tr_session_thread_impl::sessionThreadFunc(event_base*) + 96
11  Transmission                  	       0x1023c2d48 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> >(void*) + 68
12  libsystem_pthread.dylib       	       0x1888b906c _pthread_start + 148
13  libsystem_pthread.dylib       	       0x1888b3e2c thread_start + 8

Thread 2:
0   libsystem_kernel.dylib        	       0x188884a00 __select + 8
1   libcurl.4.dylib               	       0x19d8afaa8 Curl_poll + 516
2   libcurl.4.dylib               	       0x19d8a9c6c multi_wait + 764
3   Transmission                  	       0x1023f7d44 tr_web::Impl::curlThreadFunc() + 356
4   Transmission                  	       0x1023f8050 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_web::Impl::*)(), tr_web::Impl*> >(void*) + 64
5   libsystem_pthread.dylib       	       0x1888b906c _pthread_start + 148
6   libsystem_pthread.dylib       	       0x1888b3e2c thread_start + 8

Thread 3:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x188879d70 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x18888b8a4 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1888825c4 mach_msg_overwrite + 540
3   libsystem_kernel.dylib        	       0x18887a0ec mach_msg + 24
4   CoreFoundation                	       0x188998bc0 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1889974ac __CFRunLoopRun + 1232
6   CoreFoundation                	       0x188996888 CFRunLoopRunSpecific + 612
7   AppKit                        	       0x18bd42410 _NSEventThread + 172
8   libsystem_pthread.dylib       	       0x1888b906c _pthread_start + 148
9   libsystem_pthread.dylib       	       0x1888b3e2c thread_start + 8

Thread 4:
0   libsystem_pthread.dylib       	       0x1888b3e18 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x1888b3e18 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x1888b3e18 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x1888b3e18 start_wqthread + 0

Thread 1 crashed with ARM Thread State (64-bit):
    x0: 0x000000000000beef   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000020   x6: 0x0000000000000003   x7: 0x0000000000200000
    x8: 0x0000000000000005   x9: 0x0000000000007507  x10: 0x000000000004c100  x11: 0x0000000000044100
   x12: 0x0000000000044100  x13: 0x000000000004c100  x14: 0x00000000ffffffff  x15: 0x00000001302c30b0
   x16: 0x00000001888e6ed0  x17: 0x00000001e8a5cba0  x18: 0x0000000000000000  x19: 0x0000000118e8f880
   x20: 0x0000000000000000  x21: 0x0000000118e8f890  x22: 0x00000001580b0008  x23: 0x00000001580b9e68
   x24: 0x00000001023c2898  x25: 0x0000000000000080  x26: 0x000000010252f730  x27: 0x000000013050fed0
   x28: 0x000000013050fed0   fp: 0x000000016ddcac50   lr: 0x00000001023c5854
    sp: 0x000000016ddcabd0   pc: 0x00000001023cc5c0 cpsr: 0x80001000
   far: 0x000000000000bf2f  esr: 0x92000046 (Data Abort) byte write Translation fault

Binary Images:
       0x188879000 -        0x1888b1ff3 libsystem_kernel.dylib (*) <aebf397e-e2ef-3a49-be58-23d4558511f6> /usr/lib/system/libsystem_kernel.dylib
       0x1888b2000 -        0x1888beffb libsystem_pthread.dylib (*) <132084c6-c347-3489-9ac2-fcaad21cdb73> /usr/lib/system/libsystem_pthread.dylib
       0x1887fa000 -        0x188860ff3 libc++.1.dylib (*) <a4bed887-64ce-3f2e-80df-87d583b262d9> /usr/lib/libc++.1.dylib
       0x1022ec000 -        0x1024f7fff org.m0k.transmission (4.0.0-beta.2.dev) <f4315316-be17-3891-8cd3-65faa5c3e1fb> /Applications/Transmission.app/Contents/MacOS/Transmission
       0x188917000 -        0x188deefff com.apple.CoreFoundation (6.9) <fd16d6d9-10c0-323b-b43b-9781c4a4d268> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x189843000 -        0x18a27bfff com.apple.Foundation (6.9) <f1f5f857-8c3c-36d5-bc27-7702d6795468> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x18bbdf000 -        0x18cae9fff com.apple.AppKit (6.9) <dbbd4dea-6c68-3200-a81b-79b6a62f4669> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x18858a000 -        0x188614b63 dyld (*) <487cfdeb-9b07-39bf-bfb9-970b61aea2d1> /usr/lib/dyld
       0x19d87d000 -        0x19d8e9ff3 libcurl.4.dylib (*) <86328110-e0b6-3469-9a6a-307aec0e715b> /usr/lib/libcurl.4.dylib
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.3G resident=0K(0%) swapped_out_or_unallocated=1.3G(100%)
Writable regions: Total=1.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.3G(100%)

                                   VIRTUAL   REGION 
REGION TYPE                           SIZE    COUNT (non-coalesced) 
===========                        =======  ======= 
Accelerate framework                  256K        2 
Activity Tracing                      256K        1 
CG backing stores                    4544K        4 
CG image                              832K       39 
ColorSync                             560K       28 
CoreAnimation                        7168K       59 
CoreGraphics                           32K        2 
CoreUI image data                    2928K       23 
Dispatch continuations              416.0M        4 
Dispatch continuations (reserved)    64.0M        2         reserved VM address space (unallocated)
Foundation                             48K        2 
Kernel Alloc Once                      32K        1 
MALLOC                              806.6M      203 
MALLOC guard page                     192K        8 
MALLOC_MEDIUM (reserved)             40.0M        1         reserved VM address space (unallocated)
STACK GUARD                          56.1M        8 
Stack                                11.7M        8 
VM_ALLOCATE                           496K       14 
VM_ALLOCATE (reserved)                256K        1         reserved VM address space (unallocated)
__AUTH                               1857K      347 
__AUTH_CONST                         24.1M      568 
__CTF                                  756        1 
__DATA                               11.8M      557 
__DATA_CONST                         27.5M      573 
__DATA_DIRTY                         1945K      221 
__FONT_DATA                           2352        1 
__LINKEDIT                          769.1M        4 
__OBJC_CONST                         4567K      313 
__OBJC_RO                            65.4M        1 
__OBJC_RW                            1986K        1 
__TEXT                              567.1M      594 
dyld private memory                   256K        1 
mapped file                         236.2M       65 
shared memory                         896K       16 
===========                        =======  ======= 
TOTAL                                 3.1G     3673 
TOTAL, minus reserved VM space        2.9G     3673 

-----------
Full Report
-----------

{"app_name":"Transmission","timestamp":"2022-12-08 18:10:07.00 -0800","app_version":"4.0.0-beta.2.dev","slice_uuid":"f4315316-be17-3891-8cd3-65faa5c3e1fb","build_version":"14714.4.0.0","platform":1,"bundleID":"org.m0k.transmission","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.1 (22C65)","roots_installed":0,"name":"Transmission","incident_id":"7EAE02A7-BFCE-4129-BC6B-88D434E8ED61"}
{
  "uptime" : 100000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac13,2",
  "coalitionID" : 13561,
  "osVersion" : {
    "train" : "macOS 13.1",
    "build" : "22C65",
    "releaseType" : "User"
  },
  "captureTime" : "2022-12-08 18:10:06.7501 -0800",
  "incident" : "7EAE02A7-BFCE-4129-BC6B-88D434E8ED61",
  "pid" : 28523,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2022-12-08 18:05:16.7660 -0800",
  "procStartAbsTime" : 2465592508137,
  "procExitAbsTime" : 2472546340148,
  "procName" : "Transmission",
  "procPath" : "\/Applications\/Transmission.app\/Contents\/MacOS\/Transmission",
  "bundleInfo" : {"CFBundleShortVersionString":"4.0.0-beta.2.dev","CFBundleVersion":"14714.4.0.0","CFBundleIdentifier":"org.m0k.transmission"},
  "storeInfo" : {"deviceIdentifierForVendor":"2A43E20A-3B04-5D49-AE65-45A7E4CD70F5","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.m0k.transmission",
  "crashReporterKey" : "C9574617-5AC7-0CB7-EE92-A1FB4E8060A3",
  "throttleTimeout" : 2147483647,
  "sip" : "enabled",
  "vmRegionInfo" : "0xbf2f is not in any region.  Bytes before following region: 4331536593\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      1022ec000-1024f8000    [ 2096K] r-x\/r-x SM=COW  ...\/Transmission",
  "exception" : {"codes":"0x0000000000000001, 0x000000000000bf2f","rawCodes":[1,48943],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x000000000000bf2f"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":28523},
  "vmregioninfo" : "0xbf2f is not in any region.  Bytes before following region: 4331536593\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      1022ec000-1024f8000    [ 2096K] r-x\/r-x SM=COW  ...\/Transmission",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 1,
  "threads" : [{"id":1221670,"queue":"com.apple.main-thread","frames":[{"imageOffset":17764,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":30264,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":1},{"imageOffset":51908,"symbol":"std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)","symbolLocation":28,"imageIndex":2},{"imageOffset":54940,"symbol":"std::__1::__assoc_sub_state::__sub_wait(std::__1::unique_lock<std::__1::mutex>&)","symbolLocation":56,"imageIndex":2},{"imageOffset":55104,"symbol":"std::__1::__assoc_sub_state::wait()","symbolLocation":56,"imageIndex":2},{"imageOffset":701832,"symbol":"tr_sessionClose(tr_session*, unsigned long)","symbolLocation":520,"imageIndex":3},{"imageOffset":27808,"symbol":"-[Controller applicationWillTerminate:]","symbolLocation":1032,"imageIndex":3},{"imageOffset":484720,"symbol":"__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__","symbolLocation":148,"imageIndex":4},{"imageOffset":1130580,"symbol":"___CFXRegistrationPost_block_invoke","symbolLocation":88,"imageIndex":4},{"imageOffset":1130396,"symbol":"_CFXRegistrationPost","symbolLocation":440,"imageIndex":4},{"imageOffset":293748,"symbol":"_CFXNotificationPost","symbolLocation":708,"imageIndex":4},{"imageOffset":38700,"symbol":"-[NSNotificationCenter postNotificationName:object:userInfo:]","symbolLocation":88,"imageIndex":5},{"imageOffset":2416284,"symbol":"-[NSApplication terminate:]","symbolLocation":1092,"imageIndex":6},{"imageOffset":1974176,"symbol":"-[NSApplication(NSResponder) sendAction:to:from:]","symbolLocation":440,"imageIndex":6},{"imageOffset":2811416,"symbol":"-[NSMenuItem _corePerformAction]","symbolLocation":336,"imageIndex":6},{"imageOffset":2810772,"symbol":"-[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:]","symbolLocation":104,"imageIndex":6},{"imageOffset":5901508,"symbol":"-[NSMenu _performActionForItem:atIndex:fromEvent:]","symbolLocation":212,"imageIndex":6},{"imageOffset":2807972,"symbol":"-[NSMenu performKeyEquivalent:]","symbolLocation":356,"imageIndex":6},{"imageOffset":7201796,"symbol":"routeKeyEquivalent","symbolLocation":428,"imageIndex":6},{"imageOffset":1461608,"symbol":"-[NSApplication(NSEvent) sendEvent:]","symbolLocation":652,"imageIndex":6},{"imageOffset":3896160,"symbol":"-[NSApplication _handleEvent:]","symbolLocation":60,"imageIndex":6},{"imageOffset":182792,"symbol":"-[NSApplication run]","symbolLocation":500,"imageIndex":6},{"imageOffset":15912,"symbol":"NSApplicationMain","symbolLocation":880,"imageIndex":6},{"imageOffset":24144,"symbol":"start","symbolLocation":2544,"imageIndex":7}]},{"triggered":true,"id":1221756,"threadState":{"x":[{"value":48879},{"value":0},{"value":0},{"value":0},{"value":0},{"value":32},{"value":3},{"value":2097152},{"value":5},{"value":29959},{"value":311552},{"value":278784},{"value":278784},{"value":311552},{"value":4294967295},{"value":5103169712},{"value":6586003152,"symbolLocation":0,"symbol":"_platform_memmove"},{"value":8198146976},{"value":0},{"value":4712888448},{"value":0},{"value":4712888464},{"value":5772083208},{"value":5772123752},{"value":4332464280,"symbolLocation":0,"symbol":"tr_session_thread_impl::onWorkAvailableStatic(int, short, void*)"},{"value":128},{"value":4333958960,"symbolLocation":0,"symbol":"evthread_lock_fns_"},{"value":5105581776},{"value":5105581776}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4332476500},"cpsr":{"value":2147487744},"fp":{"value":6138145872},"sp":{"value":6138145744},"esr":{"value":2449473606,"description":"(Data Abort) byte write Translation fault"},"pc":{"value":4332504512,"matchesCrashFrame":1},"far":{"value":48943}},"frames":[{"imageOffset":918976,"symbol":"tr_peerIo::setCallbacks(ReadState (*)(tr_peerIo*, void*, unsigned long*), void (*)(tr_peerIo*, unsigned long, bool, void*), void (*)(tr_peerIo*, short, void*), void*)","symbolLocation":0,"imageIndex":3},{"imageOffset":890964,"symbol":"tr_handshakeDone(tr_handshake*, bool)","symbolLocation":204,"imageIndex":3},{"imageOffset":960364,"symbol":"Handshakes::abortAll()","symbolLocation":56,"imageIndex":3},{"imageOffset":939860,"symbol":"tr_swarm::stop()","symbolLocation":56,"imageIndex":3},{"imageOffset":754292,"symbol":"stopTorrent(tr_torrent*)","symbolLocation":176,"imageIndex":3},{"imageOffset":754736,"symbol":"tr_torrentFreeInSessionThread(tr_torrent*)","symbolLocation":144,"imageIndex":3},{"imageOffset":700160,"symbol":"tr_session::closeImplPart1(std::__1::promise<void>*, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >)","symbolLocation":312,"imageIndex":3},{"imageOffset":879492,"symbol":"tr_session_thread_impl::onWorkAvailable()","symbolLocation":116,"imageIndex":3},{"imageOffset":1481656,"symbol":"event_process_active_single_queue","symbolLocation":1092,"imageIndex":3},{"imageOffset":1467744,"symbol":"event_base_loop","symbolLocation":1068,"imageIndex":3},{"imageOffset":878848,"symbol":"tr_session_thread_impl::sessionThreadFunc(event_base*)","symbolLocation":96,"imageIndex":3},{"imageOffset":879944,"symbol":"void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> >(void*)","symbolLocation":68,"imageIndex":3},{"imageOffset":28780,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":7724,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1221757,"frames":[{"imageOffset":47616,"symbol":"__select","symbolLocation":8,"imageIndex":0},{"imageOffset":207528,"symbol":"Curl_poll","symbolLocation":516,"imageIndex":8},{"imageOffset":183404,"symbol":"multi_wait","symbolLocation":764,"imageIndex":8},{"imageOffset":1097028,"symbol":"tr_web::Impl::curlThreadFunc()","symbolLocation":356,"imageIndex":3},{"imageOffset":1097808,"symbol":"void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_web::Impl::*)(), tr_web::Impl*> >(void*)","symbolLocation":64,"imageIndex":3},{"imageOffset":28780,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":7724,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1222028,"name":"com.apple.NSEventThread","frames":[{"imageOffset":3440,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":75940,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":38340,"symbol":"mach_msg_overwrite","symbolLocation":540,"imageIndex":0},{"imageOffset":4332,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":531392,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":4},{"imageOffset":525484,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":4},{"imageOffset":522376,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":4},{"imageOffset":1455120,"symbol":"_NSEventThread","symbolLocation":172,"imageIndex":6},{"imageOffset":28780,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":7724,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1224571,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":1225589,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":1225590,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":1225591,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6585552896,
    "size" : 233460,
    "uuid" : "aebf397e-e2ef-3a49-be58-23d4558511f6",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6585786368,
    "size" : 53244,
    "uuid" : "132084c6-c347-3489-9ac2-fcaad21cdb73",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6585032704,
    "size" : 421876,
    "uuid" : "a4bed887-64ce-3f2e-80df-87d583b262d9",
    "path" : "\/usr\/lib\/libc++.1.dylib",
    "name" : "libc++.1.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4331585536,
    "CFBundleShortVersionString" : "4.0.0-beta.2.dev",
    "CFBundleIdentifier" : "org.m0k.transmission",
    "size" : 2146304,
    "uuid" : "f4315316-be17-3891-8cd3-65faa5c3e1fb",
    "path" : "\/Applications\/Transmission.app\/Contents\/MacOS\/Transmission",
    "name" : "Transmission",
    "CFBundleVersion" : "14714.4.0.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6586200064,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5079040,
    "uuid" : "fd16d6d9-10c0-323b-b43b-9781c4a4d268",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1953.300"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6602108928,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 10719232,
    "uuid" : "f1f5f857-8c3c-36d5-bc27-7702d6795468",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1953.300"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6639448064,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15773696,
    "uuid" : "dbbd4dea-6c68-3200-a81b-79b6a62f4669",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2299.30.116"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6582476800,
    "size" : 568164,
    "uuid" : "487cfdeb-9b07-39bf-bfb9-970b61aea2d1",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6937890816,
    "size" : 446452,
    "uuid" : "86328110-e0b6-3469-9a6a-307aec0e715b",
    "path" : "\/usr\/lib\/libcurl.4.dylib",
    "name" : "libcurl.4.dylib"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6581829632,
  "size" : 3434283008,
  "uuid" : "00a1fbb6-43e1-3c11-8483-faf0db659249"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.3G resident=0K(0%) swapped_out_or_unallocated=1.3G(100%)\nWritable regions: Total=1.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.3G(100%)\n\n                                   VIRTUAL   REGION \nREGION TYPE                           SIZE    COUNT (non-coalesced) \n===========                        =======  ======= \nAccelerate framework                  256K        2 \nActivity Tracing                      256K        1 \nCG backing stores                    4544K        4 \nCG image                              832K       39 \nColorSync                             560K       28 \nCoreAnimation                        7168K       59 \nCoreGraphics                           32K        2 \nCoreUI image data                    2928K       23 \nDispatch continuations              416.0M        4 \nDispatch continuations (reserved)    64.0M        2         reserved VM address space (unallocated)\nFoundation                             48K        2 \nKernel Alloc Once                      32K        1 \nMALLOC                              806.6M      203 \nMALLOC guard page                     192K        8 \nMALLOC_MEDIUM (reserved)             40.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                          56.1M        8 \nStack                                11.7M        8 \nVM_ALLOCATE                           496K       14 \nVM_ALLOCATE (reserved)                256K        1         reserved VM address space (unallocated)\n__AUTH                               1857K      347 \n__AUTH_CONST                         24.1M      568 \n__CTF                                  756        1 \n__DATA                               11.8M      557 \n__DATA_CONST                         27.5M      573 \n__DATA_DIRTY                         1945K      221 \n__FONT_DATA                           2352        1 \n__LINKEDIT                          769.1M        4 \n__OBJC_CONST                         4567K      313 \n__OBJC_RO                            65.4M        1 \n__OBJC_RW                            1986K        1 \n__TEXT                              567.1M      594 \ndyld private memory                   256K        1 \nmapped file                         236.2M       65 \nshared memory                         896K       16 \n===========                        =======  ======= \nTOTAL                                 3.1G     3673 \nTOTAL, minus reserved VM space        2.9G     3673 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 250000011
    },
    {
      "rolloutId" : "6347054113acce15305b7b82",
      "factorPackIds" : {
        "SIRI_MEMORY_SYNC_CONFIG" : "634705e78e8be655c1316a6e"
      },
      "deploymentId" : 250000004
    }
  ],
  "experiments" : [

  ]
}
}

### Which application of Transmission?

macOS app

### Which version of Transmission?

T4b nightly build 26a8c17187 #8566 macOS 13.1 arm64

**Comment by ckerr** [comment] 2022-12-09 06:34
Duplicate of https://github.com/transmission/transmission/issues/4317

**Closed by ckerr** 2022-12-09 06:34 UTC
