### ISSUE TITLE
Compact View unresponsive, no effect up to build fd9c454c45 #8464

### ISSUE THREAD

**Issue by chaseholden** [transmission/transmission#4163] opened 2022-11-13 23:11 UTC
### What is the issue?

M1 Ultra ARM64 macOS 13.1 Ventura 

Compact View is unresponsive rendering no change or effect
Past view recent dev builds up to build fd9c454c45 #8464

### Which application of Transmission?

macOS app

### Which version of Transmission?

dev build 4. fd9c454c45 #8464

**Comment by ckerr** [comment] 2022-11-13 23:18
Dupe of #4164

**Closed by ckerr** 2022-11-13 23:18 UTC

**Comment by chaseholden** [comment] 2022-11-14 00:21
@ckerr apologies! I have no idea how this got duplicated.

**Comment by ckerr** [comment] 2022-11-14 04:05
No worries!
