### ISSUE TITLE
[macOS] 3.00+: crash related to network connectivity issues

### ISSUE THREAD

**Issue by mag01** [transmission/transmission#1630] opened 2021-02-26 02:38 UTC
I'm encountering occassional crashes that are related to network connectivity issues as they occur only in cases like the connection going briefly down.
It's been occurring for quite a long time, even at versions prior to 3.00.

Now I tried the latest build (https://build.transmissionbt.com/job/trunk-mac/6784/)
3.00+ (090a4b5ff8)
and the crash still happens. Crash report for this build attached.

[Transmission_2021-02-25-001538_MacBook-Air.zip](https://github.com/transmission/transmission/files/6047052/Transmission_2021-02-25-001538_MacBook-Air.zip)

macOS 10.14.6 (18G8022)

**Comment by thesamesam** [comment] 2021-03-11 14:55
Related to #1437?

**Comment by ckerr** [comment] 2021-05-21 16:25
Possibly related to #1437 but it has a different trace, so I'm not positive.

Trace from @mag01's zipfile:

```
Thread 1 Crashed:
0   libsystem_kernel.dylib        	0x00007fff719862c2 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff71a41bf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff718f06a6 abort + 127
3   org.m0k.transmission          	0x00000001066709cd tr_assert_report + 202
4   org.m0k.transmission          	0x0000000106652d27 tr_peerIoTryWrite + 483
5   org.m0k.transmission          	0x00000001066528f2 tr_peerIoFlush + 203
6   org.m0k.transmission          	0x00000001066674ff phaseOne + 128
7   org.m0k.transmission          	0x0000000106667271 tr_bandwidthAllocate + 235
8   org.m0k.transmission          	0x0000000106658dfc bandwidthPulse + 161
9   org.m0k.transmission          	0x000000010668727d event_base_loop + 1541
10  org.m0k.transmission          	0x000000010664daad libeventThreadFunc + 144
11  org.m0k.transmission          	0x0000000106643801 ThreadFunc + 28
12  libsystem_pthread.dylib       	0x00007fff71a3f2eb _pthread_body + 126
13  libsystem_pthread.dylib       	0x00007fff71a42249 _pthread_start + 66
14  libsystem_pthread.dylib       	0x00007fff71a3e40d thread_start + 13
```

**Comment by ckerr** [comment] 2022-01-23 18:22
Is this still happening in newer nightly builds?

**Comment by ckerr** [comment] 2022-02-22 21:05
Duplicate of #833

**Closed by ckerr** 2022-02-22 21:05 UTC
Labels: bug, needs clarification, scope:core
