### ISSUE TITLE
Bug: App Icon not displayed in desktop

### ISSUE THREAD

**Issue by SaucySauce** [transmission/transmission#6530] opened 2024-01-15 15:14 UTC
Windows 10 IoT Enterprise LTSC 21H2 (Family computer)

Installed Transmission 4+(several updated files tested).
Shows this on the desktop but displays the correct icon on the taskbar and indicators.

![Captura de ecrã 2024-01-15 140652](https://github.com/transmission/transmission/assets/38703177/f2f4696f-8b5d-4e18-a276-9b52c712c531)

Not the primary user of this system so it's possible my brother has done something but I doubt it. I enabled the old Windows Image Viewer from pre W10 systems and that's pretty much the extent of what I have done to this Windows install.

**Comment by mikedld** [comment] 2024-01-15 15:33
Closing as duplicate of #4572.

**Closed by mikedld** 2024-01-15 15:33 UTC
