### ISSUE TITLE
MacOS: Magnet transfers don't auto start once added

### ISSUE THREAD

**Issue by Coding4Coffee** [transmission/transmission#2617] opened 2022-02-13 14:58 UTC
Magnet transfers always pause once the metadata is downloaded and don't auto start although "Start transfers when added" is ticked. 

Nightly: 83db648b3c

**Comment by ckerr** [comment] 2022-02-14 02:36
Duplicate of https://github.com/transmission/transmission/issues/2239

**Closed by ckerr** 2022-02-14 02:36 UTC
