### ISSUE TITLE
Locale symbols issue after update from 3.0.0 to 4.0.0

### ISSUE THREAD

**Issue by abubaca4** [transmission/transmission#4871] opened 2023-02-13 20:03 UTC
### What is the issue?

System debian 11, ntfs file system with ntfs3 driver(kernel driver)
In 4.0.0 transmission starting replace russian locale symbols with _
![изображение](https://user-images.githubusercontent.com/55701175/218561558-f90ea6e2-1f53-4384-89ba-ddc4c3d53a46.png)
![изображение](https://user-images.githubusercontent.com/55701175/218561696-d847a1d7-5b0f-4fdf-a02e-aabdad73ba73.png)
![изображение](https://user-images.githubusercontent.com/55701175/218562255-c62bccf5-aad2-4398-b6e9-5b595b3106ac.png)
Also transmission display Error:
Invalid argument (/mnt/MG04ACA400N/Anime/Hai To Gensou No Grimgar/Rus Sound/Onibaku/[04] Hai To Gensou No Grimgar TV 03 ?????.mka)
So all files downloaded but transmission try to do it one more time. Work well in 3.0.0

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.0

**Comment by ckerr** [comment] 2023-02-13 21:24
Hi @abubaca4 thanks for reporting this!

I think this is a duplicate of #3442 so I'm going to close this ticket as a dupe.

**Closed by ckerr** 2023-02-13 21:24 UTC
