### ISSUE TITLE
Long search for DHT peers

### ISSUE THREAD

**Issue by Tockman** [transmission/transmission#4345] opened 2022-12-10 08:11 UTC
### What is the issue?

It needs a very long time to find peer(s) for a torrent, if specified tracker is out of reach and the single available protocol is DHT. It really takes more than an hour (while qBittorrent, for an instance, does that for a minute).

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0-beta.2 (bceb368f1b)

**Comment by ckerr** [comment] 2022-12-16 21:25
This looks like a duplicate of #4003, so I'm going to close this one.

**Closed by ckerr** 2022-12-16 21:25 UTC
Labels: duplicate, type:perf
