### ISSUE TITLE
Problem with UNIT3D tracker

### ISSUE THREAD

**Issue by Juniorsnet** [transmission/transmission#7193] opened 2024-10-22 18:52 UTC
### What is the issue?

From TR I had a problem with some trackers, the error is "please respect the min interval" in TR 4.0.6.
Search in internet I saw that only happens in the tracker UNIT3D. But hey says that there are a problem in TR 4.0.6.
I downgraded the version to 4.0.5 and the error is gone.

https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/4146#issuecomment-2333608586

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.6

**Comment by Yohmi** [comment] 2024-10-23 08:59
4.0.6 is banned from many private trackers since more than 2 months now. 
From what I understand, the main problem comes from an external library which was fixed already since quite some time. But the admins of the transmission project seem too busy (or reluctant) to release a hotfix, despite an active development community. 
See : https://github.com/transmission/transmission/issues/7035 https://github.com/transmission/transmission/issues/7094 https://github.com/transmission/transmission/issues/7058

**Comment by tearfur** [comment] 2024-12-30 06:59
Duplicate of #7078

**Closed by tearfur** 2024-12-30 06:59 UTC
Labels: duplicate
