### ISSUE TITLE
Transmission port "closed" despite tcpdump showing the packets reach it and netstat shows transmission-daemon listening in the right port

### ISSUE THREAD

**Issue by subiol** [transmission/transmission#1669] opened 2021-04-17 11:47 UTC
I am editing the inital description of the issue because at first I though it was just a mistake of the checker, but the port actually seems closed:

Since two days ago, transmission is telling me my port is closed and I do not see any incoming connection from a peer when I download something, even when a torrent has more than 30 peers. After spending a morning trying to find out what is going on, I have no idea what is wrong, because tcpdump indicates the packets arrive to the right port and netstat shows that transmission-daemon is listening in the right port.

With more detail:

I am running transmission-daemon in a container in my home server, with a firewall before the internet. I am running transmission-remote in my Ubuntu laptop to connect to the daemon and ask it to check the port. I have not updated transmission-daemon or transmission-remote recently, not changed the configuration prior to the port saying it was closed.

The firewall has the port forwarded towards the container running transmission-daemon, and logs correctly that is passing the incoming packets.

After not understanding which part was wrong in my network setup, I decided to check the network of the container and backtrack devices until I find out where the problem was.

Iptables indicates the transmission-daemon container accepts all incoming transmissions. I run netstat in the transmission-daemon container and it indicates transmission-daemon is listening in the correct port, both for incoming transmissions port and for the RPC port.

Then I run tcpdump in the container running transmission-daemon. I have seen that everytime I ask transmission-remote to check the port, the container receives traffic in the listening port from vm4.transmissionbt.com (87.98.162.88). I have let tcpdump run for 10 minutes without asking transmission-remote to check the port and I have received zero traffic from that host. When I click check port, tcpdump running in the transmission-remote container registers a lot of traffic from that host, and then a few more 30-40 seconds later, then nothing.

So tcpdump indicates that the incoming transmission reaches the right container in the right port. Iptables is not blocking incoming traffic. Netstat shows that transmission-daemon is listening in that same port of the container. And yet, transmission-daemon seems to be not receiving the traffic or ignoring it. What could be the issue here?

**Comment by txVLN** [comment] 2021-12-19 04:06
Looks like there's several copies of this issue. Here's the one with the most activity: https://github.com/transmission/transmission/issues/407

**Comment by ckerr** [comment] 2022-11-28 19:12
Closing as duplicate of #407

**Closed by ckerr** 2022-11-28 19:12 UTC
