### ISSUE TITLE
Crashing on OS X after submitting a torrent via API

### ISSUE THREAD

**Issue by viega** [transmission/transmission#1400] opened 2020-08-16 06:09 UTC
On transmission 3.0.0, as well as the most recent nightly build, if I, via the RPC API, submit a torrent to my Mac OS X box running transmission, it accepts the torrent, then crashes immediately.  When I restart, the torrent starts, and the log has, "Unable to create session lock file (78): Function not implemented".  

The exact same thing works fine when submitting to my Linux box.  In both cases, transmission and the download directory all live on a locally mounted disk running the default native file system.

This started w/ my upgrade to 3.0.0.  I'll attempt downgrading in the morning, but I'm pretty confident that it will start working again.

I'm using the clutch library for Python, and am simply just doing:
client.torrent.add({'metainfo' : contents})

I test the value and success is returned before the crash.  If I'm batch submitting, the connection closes before I can submit a second torrent

**Comment by viega** [comment] 2020-08-16 06:10
I should have said, I'm running on 10.13.6, and cannot upgrade beyond 10.13 b/c it's a mid-2011 mac mini.  Have not tried anything more recent.

**Comment by ckerr** [comment] 2021-10-13 19:14
> "Unable to create session lock file (78): Function not implemented".

This seems to be a duplicate of https://github.com/transmission/transmission/issues/1391

**Closed by ckerr** 2021-10-13 19:14 UTC
