### ISSUE TITLE
transmission-daemon 4.0.1 not recognizing already download files by 3.x, re-downloads, refusing to verify...

### ISSUE THREAD

**Issue by rokezu** [transmission/transmission#5098] opened 2023-03-01 00:15 UTC
### What is the issue?

I have a few hundred torrents that after upgrading to transmission-daemon 4.0.1 (Arch Linux pacman pkg), are unrecognized by the client and then started to download again, overwriting already valid data.  Only a small percent of the downloaded torrents were recognized at the first run. 

After trying to reverify some files, some are able to do so, but many are left out... Sometimes after I start them up, it will then verify the files, but other times it will start to download over the already downloaded files. 

I'm at a loss at what triggers when 1) the files are recognized as valid (something in the .resume file?) 2) why some files get to be verified on demand and other just don't. 

There was a massive corruption event after I left it for a few minutes at the the first run and it started to download over files that were already completed.  I'm worried that if restart the downloads to trigger a verify, it will instead redownload the files. 

Any ideas? What did I do wrong?  I'll try to get some logs, but --logfile seems to be ignored as well.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.1

**Comment by ilikepeaches** [comment] 2023-03-01 00:27
Perhaps related to https://github.com/transmission/transmission/issues/4987 which is fixed in the latest nightly?

**Comment by rokezu** [comment] 2023-03-01 00:30
> Perhaps related to #4987 which is fixed in the latest nightly?

I'll review that, but definitely will revert to 3.00 for a while, I'm doing that right now, luckily had a snapshot with the .resume/.torrent files for that version of just a couple of days ago.  Thanks!

**Comment by ckerr** [comment] 2023-03-01 00:31
Hi @rokezu thanks for reporting this.

I think this is a duplicate of #5025 which is fixed by #5025, which will be included in 4.0.2.

**Closed by ckerr** 2023-03-01 00:31 UTC
Labels: duplicate

**Comment by rokezu** [comment] 2023-03-01 00:45
Thanks @ckerr! Yes it looks like the same, my apologies for not searching properly around before filing the issue. Just did a quick search and didn't found about #5025 and didn't know the proper wording of the symptoms of my issue.
