### ISSUE TITLE
[feature-request] Stop seeding after X minutes

### ISSUE THREAD

**Issue by refriedfood** [transmission/transmission#575] opened 2018-04-05 05:10 UTC
Great job with the windows builds so far, very light weight. The only reason I have not replaced my main client is for two reasons, 1) no RSS, and 2) no option to pause or stop seeding after an allotted time period. I suppose if implimented, a "force resume" option would be needed even for those past the time period.

This feature would be great, and since you already have an Ratio timeout and idle timeout, I wouldn't think stopping after a specified number of minutes would be too difficult or unwelcome.

**Comment by lampra1** [comment] 2018-04-13 23:15
+1

**Comment by donileo** [comment] 2018-10-14 20:01
Definitely need this as well.

**Comment by xelra** [comment] 2018-12-18 00:11
This is a duplicate of https://github.com/transmission/transmission/issues/111

**Closed** 2018-12-18 00:14 UTC
