### ISSUE TITLE
Crashes all the time

### ISSUE THREAD

**Issue by RaZ31337** [transmission/transmission#1394] opened 2020-08-10 05:36 UTC
Sometimes if I add a few torrents "too fast" or sometimes just if a torrent has a particularly long file name, or some other parameter that escapes me. How do I find out what is causing it to crash? Transmission runs as a docker on my unraid and is remotely controller on Windows10 with transmission 3.0

**Comment by ckerr** [comment] 2022-01-19 18:55
Since you're running a Docker container for the daemon it sounds like you have tech skills, so the most useful thing would be to build transmission-qt locally and run it in a debugger.

On the other end of the spectrum, probably the easiest thing to try would be a nightly build from transmissionbt.org and see if the problem is still there. Transmission has undergone a _lot_ of development since Aug 2020 :smile:

**Comment by Coeur** [comment] 2022-10-09 16:02
I'll close this issue, as it's not possible to take actions without a crash log.
Feel free to re-open an issue once you have collected a crash log or a way to systematically reproduce the issue on Transmission 4.

**Closed** 2022-10-09 18:35 UTC
Labels: needs clarification
