### ISSUE TITLE
can't rename (input/output error)

### ISSUE THREAD

**Issue by rd1** [transmission/transmission#308] opened 2017-06-05 05:49 UTC
this error occurs on downloads with magnet. 

Running v2.92 on win 10 x64 v1703

1st time i've had trouble renaming a torrent.

file attribs and permissions all check out.

restarted the service multiple times, still no luck.

is this normal to be unable to rename magnet downloads?

**Comment by jpl42** [comment] 2017-07-23 23:42
Same problem here. I can rename when torrent is paused though.

**Comment by ckerr** [comment] 2022-01-24 15:28
I'm not able to reproduce this. If this behavior is still happening in the post-3.00 nightly builds, please update the issue with instructions on how I can try to trigger it in my own testing.

File / disk IO is no different between magnet and non-magnet torrents. I don't think that should make any difference

**Comment by Arthesian** [comment] 2022-08-25 12:54
not sure if it's the same issue as the original post.

But I'm unable to rename a Torrent in the WEB UI, that has a name with a colon ( : ) in it. It got downloaded with a underscore ( _ ) instead of the colon on the filesystem, since a colon is not a valid path character... but now I'm not able to change the name

running 3.00-20 on a Synology NAS (using WEB UI to access the 'client')

**Comment by Arthesian** [comment] 2022-08-25 13:06
> not sure if it's the same issue as the original post.
> 
> But I'm unable to rename a Torrent in the WEB UI, that has a name with a colon ( : ) in it. It got downloaded with a underscore ( _ ) instead of the colon on the filesystem, since a colon is not a valid path character... but now I'm not able to change the name
> 
> running 3.00-20 on a Synology NAS (using WEB UI to access the 'client')

I made it work by removing the torrent from WEB UI, opening the Torrent file in a text editor, and chaning the file name inside the torrent file - then re-adding it to WEB UI

I was able to rename the torrent to the 'new' folder name and relocating the torrent to the existing files (with performing a verify on local files).

**Comment by ckerr** [comment] 2023-01-27 15:34
Duplicate of #1700.

**Closed by ckerr** 2023-01-27 15:34 UTC
Labels: bug, needs clarification
