### ISSUE TITLE
[WEB UI] Login page instead of Sign in popup

### ISSUE THREAD

**Issue by ZimGil** [transmission/transmission#1232] opened 2020-05-15 01:15 UTC
How about switching to a proper Login page instead of the sign in popup?
Couple of reasons IMO:
1. Better look and feel
2. Will be easy to use with services like [LastPass](https://www.lastpass.com/)
3. Can add a `Remember Me` option, maybe

**Comment by madcowGit** [comment] 2021-08-08 18:37
same as #823

**Comment by normanr** [comment] 2021-11-09 22:29
same as https://github.com/transmission/transmission/issues/716

**Comment by ckerr** [comment] 2022-02-24 20:47
Duplicate of #466 716

**Closed by ckerr** 2022-02-24 20:47 UTC
Labels: duplicate, enhancement, scope:web
