### ISSUE TITLE
#8356 build c75c6bf5c8 Unexpected Crash on Quit, 2 magnets won't verify, multiple access prompts 

### ISSUE THREAD

**Issue by chaseholden** [transmission/transmission#3920] opened 2022-10-09 05:01 UTC
#8356 build c75c6bf5c8 on macOS 12.6 ARM64 M1 Ultra

1. After running previous build b49129dfa6 and updating to c75c6bf5c8 #8356, I had 48 totally completed magnets downloaded and successfully verified 100% (green). 

2. However, opening in #8356 c75c6bf5c8, mysteriously 2 of those 48 not only display as never downloaded w/o metadata (red), but attempting to verify the files causes the selection to jump selection to another completed magnet torrent. 
- The other magnet torrent, though selected, does not verify or do anything. It's as if the 2 of 48 seemingly random magnets don't exist or are lacking the connection to their constituent files, which I can verify as valid in Finder. 
- I verified local data on a few other magnets and those verified normally (100%).
- When I quit and open Transmission 3, those two (2) red magnet torrents show as 0% but when I verify local data, successfully validate as 100% complete. Strange. 

3. Continue to incur 7 dialogue prompts to approve access to 3 removable volumes which I thought was fixed.

4. Quitting App results in Unexpected Crash dialogues with sample report as follows:

<details><summary>Translated Report</summary>

```
Process:               Transmission [52382]
Path:                  /Applications/Transmission.app/Contents/MacOS/Transmission
Identifier:            org.m0k.transmission
Version:               4.0.0-beta.1.dev (14714.4.0.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-10-08 22:01:19.0236 -0700
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        C9574617-5AC7-0CB7-EE92-A1FB4E8060A3


Time Awake Since Boot: 600000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x18fa1ad98 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x18fa4fee0 pthread_kill + 288
2   libsystem_c.dylib             	       0x18f98a340 abort + 168
3   libc++abi.dylib               	       0x18fa0ab08 abort_message + 132
4   libc++abi.dylib               	       0x18f9fa938 demangling_terminate_handler() + 312
5   libobjc.A.dylib               	       0x18f8f0330 _objc_terminate() + 160
6   libc++abi.dylib               	       0x18fa09ea4 std::__terminate(void (*)()) + 20
7   libc++abi.dylib               	       0x18fa09e40 std::terminate() + 64
8   Transmission                  	       0x102378958 std::__1::unique_ptr<tr_session::tr_udp_core, std::__1::default_delete<tr_session::tr_udp_core> >::reset(tr_session::tr_udp_core*) + 28
9   Transmission                  	       0x10237c0a4 tr_session::~tr_session() + 608
10  Transmission                  	       0x102379008 tr_sessionClose(tr_session*) + 1696
11  Transmission                  	       0x1022bb308 -[Controller applicationWillTerminate:] + 1392
12  CoreFoundation                	       0x18fb11468 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
13  CoreFoundation                	       0x18fbb5bb8 ___CFXRegistrationPost_block_invoke + 52
14  CoreFoundation                	       0x18fbb5b24 _CFXRegistrationPost + 456
15  CoreFoundation                	       0x18fae00f8 _CFXNotificationPost + 732
16  Foundation                    	       0x1909a5c28 -[NSNotificationCenter postNotificationName:object:userInfo:] + 96
17  AppKit                        	       0x192907edc -[NSApplication terminate:] + 1352
18  AppKit                        	       0x1928865c8 -[NSApplication(NSResponder) sendAction:to:from:] + 460
19  AppKit                        	       0x19297c2ec -[NSMenuItem _corePerformAction] + 444
20  AppKit                        	       0x19297bfe0 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 100
21  AppKit                        	       0x192cb70cc -[NSMenu _performActionForItem:atIndex:fromEvent:] + 228
22  AppKit                        	       0x19297b304 -[NSMenu performKeyEquivalent:] + 452
23  AppKit                        	       0x192df21fc routeKeyEquivalent + 568
24  AppKit                        	       0x1927f0e6c -[NSApplication(NSEvent) sendEvent:] + 1172
25  AppKit                        	       0x192aab0f4 -[NSApplication _handleEvent:] + 76
26  AppKit                        	       0x192673008 -[NSApplication run] + 636
27  AppKit                        	       0x1926446fc NSApplicationMain + 1132
28  dyld                          	       0x10278d08c start + 520

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x18fa128b0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x18fa12d20 mach_msg + 76
2   CoreFoundation                	       0x18fb1d210 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x18fb1b6c0 __CFRunLoopRun + 1180
4   CoreFoundation                	       0x18fb1aa84 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x1927ef100 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x18fa5026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18fa4b08c thread_start + 8

Thread 2:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x000000018fa0e0c8   x5: 0x000000016db4dd50   x6: 0x0000000000000074   x7: 0x000000016db4e0c8
    x8: 0xb0f6bd8c78321ae2   x9: 0xb0f6bd8d7ab21f62  x10: 0x0000000000000200  x11: 0x000000000000002d
   x12: 0x000000000000002d  x13: 0x000060000ba36228  x14: 0x000000018fa0e0f2  x15: 0x0000000000000000
   x16: 0x0000000000000148  x17: 0x00000001e9b73680  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000102800580  x21: 0x0000000000000103  x22: 0x0000000102800660  x23: 0x00006000057f35d0
   x24: 0x0000000000000030  x25: 0x00000001024b7000  x26: 0x00000001024d0d98  x27: 0x00000000634255a2
   x28: 0x000000006342559f   fp: 0x000000016db4dcc0   lr: 0x000000018fa4fee0
    sp: 0x000000016db4dca0   pc: 0x000000018fa1ad98 cpsr: 0x40001000
   far: 0x00000001024c94a4  esr: 0x56000080  Address size fault

Binary Images:
       0x18fa11000 -        0x18fa48fff libsystem_kernel.dylib (*) <a9d87740-9c1d-3468-bf60-720a8d713cba> /usr/lib/system/libsystem_kernel.dylib
       0x18fa49000 -        0x18fa55fff libsystem_pthread.dylib (*) <63c4eef9-69a5-38b1-996e-8d31b66a051d> /usr/lib/system/libsystem_pthread.dylib
       0x18f910000 -        0x18f991fff libsystem_c.dylib (*) <b25d2080-bb9e-38d6-8236-9cef4b2f11a3> /usr/lib/system/libsystem_c.dylib
       0x18f9f9000 -        0x18fa10fff libc++abi.dylib (*) <4e8d8a11-4217-3d56-9d41-5426f7cf307c> /usr/lib/libc++abi.dylib
       0x18f8cf000 -        0x18f90cfff libobjc.A.dylib (*) <ec96f0fa-6341-3e1d-be54-49b544e17f7d> /usr/lib/libobjc.A.dylib
       0x1022b0000 -        0x1024cffff org.m0k.transmission (4.0.0-beta.1.dev) <65396af0-9ed9-3f75-ae0b-92f7b35e656e> /Applications/Transmission.app/Contents/MacOS/Transmission
       0x18fa98000 -        0x18ffdefff com.apple.CoreFoundation (6.9) <fc3c193d-0cdb-3569-9f0e-bd2507ca1dbb> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x19099c000 -        0x190d8dfff com.apple.Foundation (6.9) <8bbf8f9b-0034-34f0-a2c5-13c31941632d> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x192641000 -        0x1934f9fff com.apple.AppKit (6.9) <5e432f87-5b58-391a-a542-fa2d909dd210> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x102788000 -        0x1027e7fff dyld (*) <38ee9fe9-b66d-3066-8c5c-6ddf0d6944c6> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=3.0G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=3.0G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               768K        6 
Activity Tracing                   256K        1 
CG backing stores                 4544K        4 
CG image                           880K       29 
ColorSync                          624K       27 
CoreAnimation                     17.1M       38 
CoreGraphics                        32K        2 
CoreUI image data                 2240K       20 
Foundation                          48K        2 
Kernel Alloc Once                   32K        1 
MALLOC                             1.1G      168 
MALLOC guard page                  192K        8 
MALLOC_MEDIUM (reserved)           1.6G       15         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           256.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        3 
Stack                             9264K        3 
VM_ALLOCATE                        352K       15 
VM_ALLOCATE (reserved)             256K        1         reserved VM address space (unallocated)
__AUTH                            2514K      287 
__AUTH_CONST                      19.6M      476 
__CTF                               756        1 
__DATA                            14.9M      466 
__DATA_CONST                      17.4M      483 
__DATA_DIRTY                      1702K      197 
__FONT_DATA                          4K        1 
__LINKEDIT                       579.6M        5 
__OBJC_CONST                      3345K      257 
__OBJC_RO                         83.0M        1 
__OBJC_RW                         3168K        1 
__TEXT                           475.6M      500 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
mapped file                      188.0M       30 
shared memory                     1376K       14 
===========                     =======  ======= 
TOTAL                              4.4G     3065 
TOTAL, minus reserved VM space     2.5G     3065 
```
</details>

<details><summary>Full Report</summary>

```json
{"app_name":"Transmission","timestamp":"2022-10-08 22:01:19.00 -0700","app_version":"4.0.0-beta.1.dev","slice_uuid":"65396af0-9ed9-3f75-ae0b-92f7b35e656e","build_version":"14714.4.0.0","platform":1,"bundleID":"org.m0k.transmission","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6 (21G115)","incident_id":"C09DD23E-61E5-4EEB-A46A-3AB2BF16B3AC","name":"Transmission"}
{
  "uptime" : 600000,
  "procLaunch" : "2022-10-08 21:49:49.9042 -0700",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac13,2",
  "procStartAbsTime" : 14494683539956,
  "coalitionID" : 105443,
  "osVersion" : {
    "train" : "macOS 12.6",
    "build" : "21G115",
    "releaseType" : "User"
  },
  "captureTime" : "2022-10-08 22:01:19.0236 -0700",
  "incident" : "C09DD23E-61E5-4EEB-A46A-3AB2BF16B3AC",
  "bug_type" : "309",
  "pid" : 52382,
  "procExitAbsTime" : 14511222433530,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Transmission",
  "procPath" : "\/Applications\/Transmission.app\/Contents\/MacOS\/Transmission",
  "bundleInfo" : {"CFBundleShortVersionString":"4.0.0-beta.1.dev","CFBundleVersion":"14714.4.0.0","CFBundleIdentifier":"org.m0k.transmission"},
  "storeInfo" : {"deviceIdentifierForVendor":"2A43E20A-3B04-5D49-AE65-45A7E4CD70F5","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.m0k.transmission",
  "crashReporterKey" : "C9574617-5AC7-0CB7-EE92-A1FB4E8060A3",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":5360507,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":6704652488},{"value":6135536976},{"value":116},{"value":6135537864},{"value":12751587805955758818},{"value":12751587810292670306},{"value":512},{"value":45},{"value":45},{"value":105553311523368},{"value":6704652530},{"value":0},{"value":328},{"value":8216065664},{"value":0},{"value":6},{"value":4336911744,"symbolLocation":0,"symbol":"_main_thread"},{"value":259},{"value":4336911968,"symbolLocation":224,"symbol":"_main_thread"},{"value":105553208489424},{"value":48},{"value":4333465600},{"value":4333571480,"symbolLocation":16,"symbol":"vtable for fmt::v9::basic_memory_buffer<char, 500ul, std::__1::allocator<char> >"},{"value":1665291682},{"value":1665291679}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6704922336},"cpsr":{"value":1073745920},"fp":{"value":6135536832},"sp":{"value":6135536800},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6704704920,"matchesCrashFrame":1},"far":{"value":4333540516}},"queue":"com.apple.main-thread","frames":[{"imageOffset":40344,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":0},{"imageOffset":28384,"symbol":"pthread_kill","symbolLocation":288,"imageIndex":1},{"imageOffset":500544,"symbol":"abort","symbolLocation":168,"imageIndex":2},{"imageOffset":72456,"symbol":"abort_message","symbolLocation":132,"imageIndex":3},{"imageOffset":6456,"symbol":"demangling_terminate_handler()","symbolLocation":312,"imageIndex":3},{"imageOffset":135984,"symbol":"_objc_terminate()","symbolLocation":160,"imageIndex":4},{"imageOffset":69284,"symbol":"std::__terminate(void (*)())","symbolLocation":20,"imageIndex":3},{"imageOffset":69184,"symbol":"std::terminate()","symbolLocation":64,"imageIndex":3},{"imageOffset":821592,"symbol":"std::__1::unique_ptr<tr_session::tr_udp_core, std::__1::default_delete<tr_session::tr_udp_core> >::reset(tr_session::tr_udp_core*)","symbolLocation":28,"imageIndex":5},{"imageOffset":835748,"symbol":"tr_session::~tr_session()","symbolLocation":608,"imageIndex":5},{"imageOffset":823304,"symbol":"tr_sessionClose(tr_session*)","symbolLocation":1696,"imageIndex":5},{"imageOffset":45832,"symbol":"-[Controller applicationWillTerminate:]","symbolLocation":1392,"imageIndex":5},{"imageOffset":496744,"symbol":"__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__","symbolLocation":28,"imageIndex":6},{"imageOffset":1170360,"symbol":"___CFXRegistrationPost_block_invoke","symbolLocation":52,"imageIndex":6},{"imageOffset":1170212,"symbol":"_CFXRegistrationPost","symbolLocation":456,"imageIndex":6},{"imageOffset":295160,"symbol":"_CFXNotificationPost","symbolLocation":732,"imageIndex":6},{"imageOffset":39976,"symbol":"-[NSNotificationCenter postNotificationName:object:userInfo:]","symbolLocation":96,"imageIndex":7},{"imageOffset":2911964,"symbol":"-[NSApplication terminate:]","symbolLocation":1352,"imageIndex":8},{"imageOffset":2381256,"symbol":"-[NSApplication(NSResponder) sendAction:to:from:]","symbolLocation":460,"imageIndex":8},{"imageOffset":3388140,"symbol":"-[NSMenuItem _corePerformAction]","symbolLocation":444,"imageIndex":8},{"imageOffset":3387360,"symbol":"-[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:]","symbolLocation":100,"imageIndex":8},{"imageOffset":6774988,"symbol":"-[NSMenu _performActionForItem:atIndex:fromEvent:]","symbolLocation":228,"imageIndex":8},{"imageOffset":3384068,"symbol":"-[NSMenu performKeyEquivalent:]","symbolLocation":452,"imageIndex":8},{"imageOffset":8065532,"symbol":"routeKeyEquivalent","symbolLocation":568,"imageIndex":8},{"imageOffset":1769068,"symbol":"-[NSApplication(NSEvent) sendEvent:]","symbolLocation":1172,"imageIndex":8},{"imageOffset":4628724,"symbol":"-[NSApplication _handleEvent:]","symbolLocation":76,"imageIndex":8},{"imageOffset":204808,"symbol":"-[NSApplication run]","symbolLocation":636,"imageIndex":8},{"imageOffset":14076,"symbol":"NSApplicationMain","symbolLocation":1132,"imageIndex":8},{"imageOffset":20620,"symbol":"start","symbolLocation":520,"imageIndex":9}]},{"id":5360749,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":0},{"imageOffset":545296,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":6},{"imageOffset":538304,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":6},{"imageOffset":535172,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":6},{"imageOffset":1761536,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":8},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":5365413,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6704664576,
    "size" : 229376,
    "uuid" : "a9d87740-9c1d-3468-bf60-720a8d713cba",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6704893952,
    "size" : 53248,
    "uuid" : "63c4eef9-69a5-38b1-996e-8d31b66a051d",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6703611904,
    "size" : 532480,
    "uuid" : "b25d2080-bb9e-38d6-8236-9cef4b2f11a3",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6704566272,
    "size" : 98304,
    "uuid" : "4e8d8a11-4217-3d56-9d41-5426f7cf307c",
    "path" : "\/usr\/lib\/libc++abi.dylib",
    "name" : "libc++abi.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6703345664,
    "size" : 253952,
    "uuid" : "ec96f0fa-6341-3e1d-be54-49b544e17f7d",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4331339776,
    "CFBundleShortVersionString" : "4.0.0-beta.1.dev",
    "CFBundleIdentifier" : "org.m0k.transmission",
    "size" : 2228224,
    "uuid" : "65396af0-9ed9-3f75-ae0b-92f7b35e656e",
    "path" : "\/Applications\/Transmission.app\/Contents\/MacOS\/Transmission",
    "name" : "Transmission",
    "CFBundleVersion" : "14714.4.0.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6705217536,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5533696,
    "uuid" : "fc3c193d-0cdb-3569-9f0e-bd2507ca1dbb",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6720962560,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 4136960,
    "uuid" : "8bbf8f9b-0034-34f0-a2c5-13c31941632d",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6750998528,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15437824,
    "uuid" : "5e432f87-5b58-391a-a542-fa2d909dd210",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.60.148"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4336418816,
    "size" : 393216,
    "uuid" : "38ee9fe9-b66d-3066-8c5c-6ddf0d6944c6",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 6701596672,
  "size" : 3144744960,
  "uuid" : "049b583e-d4dc-3b2b-88da-e52d6e18313d"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=3.0G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=3.0G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               768K        6 \nActivity Tracing                   256K        1 \nCG backing stores                 4544K        4 \nCG image                           880K       29 \nColorSync                          624K       27 \nCoreAnimation                     17.1M       38 \nCoreGraphics                        32K        2 \nCoreUI image data                 2240K       20 \nFoundation                          48K        2 \nKernel Alloc Once                   32K        1 \nMALLOC                             1.1G      168 \nMALLOC guard page                  192K        8 \nMALLOC_MEDIUM (reserved)           1.6G       15         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           256.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.0M        3 \nStack                             9264K        3 \nVM_ALLOCATE                        352K       15 \nVM_ALLOCATE (reserved)             256K        1         reserved VM address space (unallocated)\n__AUTH                            2514K      287 \n__AUTH_CONST                      19.6M      476 \n__CTF                               756        1 \n__DATA                            14.9M      466 \n__DATA_CONST                      17.4M      483 \n__DATA_DIRTY                      1702K      197 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       579.6M        5 \n__OBJC_CONST                      3345K      257 \n__OBJC_RO                         83.0M        1 \n__OBJC_RW                         3168K        1 \n__TEXT                           475.6M      500 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                      188.0M       30 \nshared memory                     1376K       14 \n===========                     =======  ======= \nTOTAL                              4.4G     3065 \nTOTAL, minus reserved VM space     2.5G     3065 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000020
    },
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 240000027
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "5b729754-3882-4560-826f-9c0bc27d77c6",
      "experimentId" : "6192fb082171a2330e561df0",
      "deploymentId" : 400000034
    }
  ]
}
}
```
</details>

**Comment by Coeur** [comment] 2022-10-10 03:40
For the crash on Quit, it's a duplicate of #3776

**Comment by ckerr** [comment] 2022-10-10 15:19
> When I quit and open Transmission 3, those two (2) red magnet torrents show as 0% but when I verify local data, successfully validate as 100% complete. Strange.

Transmission 4's resume files use a different, more efficient method for remembering progress between sessions. Transmission 3 doesn't know that format so some of that progress is going to get dropped on the floor when you downgrade like that.

**Comment by ckerr** [comment] 2022-10-10 15:22
> Continue to incur 7 dialogue prompts to approve access to 3 removable volumes which I thought was fixed.

Duplicate of #2171 

I'm going to close this ticket; just from an issue management standpoint: there are four different points being discussed here, two are duplicates (the crash, the permissions prompt), one is invalid (the 3.00 downgrade behavior), one is needinfo. But because they've all been reported in a single bundle, if taken at face value the ticket can't be closed until all four are resolved. And it makes it harder for other people experiencing the same problem to find information.

**Closed by ckerr** 2022-10-10 15:22 UTC
Labels: scope:mac

**Comment by chaseholden** [comment] 2022-10-10 22:31
> I'm going to close this ticket; just from an issue management standpoint: there are four different points being discussed here, two are duplicates (the crash, the permissions prompt), one is invalid (the 3.00 downgrade behavior), one is needinfo. But because they've all been reported in a single bundle, if taken at face value the ticket can't be closed until all four are resolved. And it makes it harder for other people experiencing the same problem to find information.

@ckerr Understood, CK and I'll remember to separate issues in the future.

**Comment by chaseholden** [comment] 2022-10-10 22:39
> > When I quit and open Transmission 3, those two (2) red magnet torrents show as 0% but when I verify local data, successfully validate as 100% complete. Strange.
> 
> Transmission 4's resume files use a different, more efficient method for remembering progress between sessions. Transmission 3 doesn't know that format so some of that progress is going to get dropped on the floor when you downgrade like that.

@ckerr However, that does not seem to answer why the unexpected failure when I copy the magnet URL of 2 completely downloaded files (100% progress), remove those magnets from T3, re-add those magnets to T3 by pasting the magnet link, and then attempting to verify local data. 

This user expects that once a file is completely downloaded to 100% progress, the file is changed to be a singular file that would be recognized by any version of Transmission or at least recognizable. Adding the magnet URL as a "new" magnet in T3 I would expect to at least be able to read the file and recognize it as whole, complete.

If not, perhaps the "copy magnet URL" operation is not actually copying the magnet URL as unchanged from the original magnet URL first added, which this User would understandably expect.

**Comment by ckerr** [comment] 2022-10-10 23:13
@chaseholden there aren't any plans to do another release on the 3 series so I'm not sure it's productive to do triage on 3.00 issues.

**Comment by GaryElshaw** [comment] 2022-10-11 02:08
> @chaseholden there aren't any plans to do another release on the 3 series so I'm not sure it's productive to do triage on 3.00 issues.

I think that should be noted on the website that there will be no further work on any previous version of Transmission.
