### ISSUE TITLE
transmission-daemon just quits without any messages or signal.

### ISSUE THREAD

**Issue by TByte007** [transmission/transmission#7055] opened 2024-08-11 17:26 UTC
### What is the issue?

transmission-daemon just quits after random amount of time. No core, no signal, no messages in the log nor in the console when started with -f

[2024-08-11 17:04:48.874] web.cc:175: Will verify tracker certs using envvar CURL_CA_BUNDLE: none
[2024-08-11 17:04:48.874] web.cc:176: NB: this only works if you built against libcurl with openssl or gnutls, NOT nss
[2024-08-11 17:04:48.874] web.cc:177: NB: Invalid certs will appear as 'Could not connect to tracker' like many other errors
[2024-08-11 17:04:48.874] rpc-server.cc:836: setting password-enabled to 'false'
[2024-08-11 17:04:48.874] rpc-server.cc:763: Added '127.0.0.1' to host whitelist
[2024-08-11 17:04:48.874] rpc-server.cc:763: Added '::1' to host whitelist
[2024-08-11 17:04:48.874] rpc-server.cc:822: setting our username to ''
[2024-08-11 17:04:48.874] rpc-server.cc:830: setting our salted password to '{fbcdaaa4340d5437732e74b5ef1ebcf2282a8270lZW/iga0'
[2024-08-11 17:04:48.874] rpc-server.cc:923: Serving RPC and Web requests from '/usr/local/share/transmission/public_html'
tbyte@TiTaN:~ on 4
$:> tail /var/log/transmission.log
...
[2024-08-11 17:09:35.069] dbg [Random torrent every time] setting [x.x.x.x]:43286 do_purge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error (peer-mgr.cc:622)
[2024-08-11 17:09:38.040] dbg [Random torrent every time] setting [x.x.x.x]:21225 do_purge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error (peer-mgr.cc:622)

All the messages are just "do_purge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error (peer-mgr.cc:622)"
Is there something that I can enable to see what is going on?
Regards.

PS: I ran it through lldb and got this:
Process 73783 exited with status = 13 (0x0000000d)

PS1: If this helps (broken pipe?): 
echo $?
141

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

transmission-daemon 4.0.6 (38c164933e)

**Comment by tearfur** [comment] 2024-08-12 01:12
Probably a duplicate of #7035. Is 13 the number for `SIGPIPE` on your system?

**Comment by imaami** [comment] 2024-08-12 11:14
To see what the signal numbers are you can use `kill -l`:

```
$ kill -l
 1) SIGHUP       2) SIGINT       3) SIGQUIT      4) SIGILL       5) SIGTRAP
 6) SIGABRT      7) SIGBUS       8) SIGFPE       9) SIGKILL     10) SIGUSR1
11) SIGSEGV     12) SIGUSR2     13) SIGPIPE     14) SIGALRM     15) SIGTERM
16) SIGSTKFLT   17) SIGCHLD     18) SIGCONT     19) SIGSTOP     20) SIGTSTP
21) SIGTTIN     22) SIGTTOU     23) SIGURG      24) SIGXCPU     25) SIGXFSZ
26) SIGVTALRM   27) SIGPROF     28) SIGWINCH    29) SIGIO       30) SIGPWR
31) SIGSYS      34) SIGRTMIN    35) SIGRTMIN+1  36) SIGRTMIN+2  37) SIGRTMIN+3
38) SIGRTMIN+4  39) SIGRTMIN+5  40) SIGRTMIN+6  41) SIGRTMIN+7  42) SIGRTMIN+8
43) SIGRTMIN+9  44) SIGRTMIN+10 45) SIGRTMIN+11 46) SIGRTMIN+12 47) SIGRTMIN+13
48) SIGRTMIN+14 49) SIGRTMIN+15 50) SIGRTMAX-14 51) SIGRTMAX-13 52) SIGRTMAX-12
53) SIGRTMAX-11 54) SIGRTMAX-10 55) SIGRTMAX-9  56) SIGRTMAX-8  57) SIGRTMAX-7
58) SIGRTMAX-6  59) SIGRTMAX-5  60) SIGRTMAX-4  61) SIGRTMAX-3  62) SIGRTMAX-2
63) SIGRTMAX-1  64) SIGRTMAX
```

**Comment by TByte007** [comment] 2024-08-12 22:28
> Probably a duplicate of #7035. Is 13 the number for `SIGPIPE` on your system?

13) SIGPIPE (FreeBSD 14.0)

**Closed** 2024-08-13 07:27 UTC
