### ISSUE TITLE
Feature Request: Display external address on WebUI status bar

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#7139] opened 2024-09-24 12:21 UTC
### What is the issue?

Inspired by https://github.com/qbittorrent/qBittorrent/pull/20118 , This adds an external address display label on the WebUI status bar.

### Which application of Transmission?

Web client

### Which version of Transmission?

N/A

**Comment by tearfur** [comment] 2024-09-25 12:21
Duplicate of #5785

**Closed by tearfur** 2024-09-25 12:21 UTC
