### ISSUE TITLE
Choice of Accent color may not be ideal on macOS

### ISSUE THREAD

**Issue by fxcoudert** [transmission/transmission#2205] opened 2021-11-22 19:33 UTC
Using `Transmission-1459220b5b.dmg` (build #7379). Bug observed with both M1 and Intel modes.

My system tint (highlight color) is blue, so in macOS UI, all highlights are blue (items selected, in particular). But in Transmission this tint is not obeyed: UI uses red to highlight selected torrent, open tab, etc.

<img width="703" alt="Capture d’écran 2021-11-22 à 20 31 54" src="https://user-images.githubusercontent.com/1980544/142923582-e5f8fc37-8f6a-4035-8a71-e5d03edf65d8.png">

and (torrent title obscured):

<img width="634" alt="Capture d’écran 2021-11-22 à 20 32 26" src="https://user-images.githubusercontent.com/1980544/142923740-07663595-b885-4b1f-a3e0-ad14df8e7a3e.png">

**Comment by Oleg-Chashko** [comment] 2021-11-22 19:53
_But is it a deliberate choice of Transmission to go for “bright red” as a preferred tint?_
I agree that “bright red” is not the best choice.

**Comment by GScottElshaw** [comment] 2021-11-23 00:08
I've been editing the plist file for months, to the extent that I don't even close the document window because another build will be around the corner, the cursor even appears at the correct position in line 92 - Adjust, save, quit, reopen....

![Screenshot 2021-11-23 at 1 08 05 PM](https://user-images.githubusercontent.com/69029666/142953257-6401dce4-aceb-4c72-9fa5-405f1d8a6295.png)
.

**Comment by fxcoudert** [comment] 2021-11-23 08:27
It is a deliberate choice, apparently: https://github.com/transmission/transmission/commit/55e883318d8582cbaea0cbfffb4e502dbac5e949
https://github.com/transmission/transmission/pull/1535

**Comment by mikedld** [comment] 2021-11-23 10:38
I believe crimson red is Transmission's signature color, if you look at the [website](https://transmissionbt.com/) and t-handle on the icon. Whether it's a good choice for the UI I'll let @livings124 weigh in.

**Comment by GScottElshaw** [comment] 2021-11-23 14:22
Um, as someone with a lot of experience with accessibility, it's not.

**Comment by fxcoudert** [comment] 2021-11-26 21:24
<img width="40" alt="Capture d’écran 2021-11-26 à 22 23 34" src="https://user-images.githubusercontent.com/1980544/143655960-18ecda48-99de-49f4-be74-97e5a5fa04e7.png">

For some UI elements, like the "magnet", red on red becomes almost invisible…

**Comment by livings124** [comment] 2021-11-26 21:27
I thought this red would be a nice tint color, but sounds like I might be in the minority here. Thoughts on what would be a better tint color (would need one for light mode and one for dark mode).

**Comment by fxcoudert** [comment] 2021-11-26 21:29
I checked and most apps I have on my laptop specify no specific tint color, which is allowed and defaults to “blue” (i.e., same as pre-macOS 11).

**Comment by GScottElshaw** [comment] 2021-11-27 00:11
In a former life I was part of my country's web standards setting and implementation across government. Simply, white on black text is still the best and the default should be monochromatic. If that's too rough? An even darker blue for increased contrast with the white text. I'd love a monochrome version where the highlight colour on the mac is black, and then in night mode it is white. While we're on the subject, can someone, perhaps @ckerr or @nevack  politely ask for this man's code for increasing and decreasing font sizes? [He's done a lovely job with complex text and an inspector panel like Transmission's](https://github.com/losnoco/Cog). I'm often squinting on my Macbook Air. @livings124 One of the many reasons not to use red https://en.wikipedia.org/wiki/Color_blindness

**Comment by fxcoudert** [comment] 2021-11-27 08:41
Black tint for highlights is not one of the “standard” choices of macOS, and might be weird to users. It also would need to redo some icons, which have black element and would become almost invisible on a black background:

<img width="116" alt="Capture d’écran 2021-11-27 à 09 37 46" src="https://user-images.githubusercontent.com/1980544/143674529-db26fe4e-573c-4a2a-9ee0-d6b879eb2e6e.png">

**Comment by GScottElshaw** [comment] 2021-11-28 01:20
To be fair, the main menu does this already (black and white) without a highlight colour, and each of those windows in the inspector is completely unique. For example, I am never confused between the views of each of those options when clicking on them, they are all unique data views. Another thought, something i just noticed and could be helpful with what we are discussing, there is no text popup when the mouse hovers over each of those options in the inspector menu as there is with the main menu.
![Screenshot 2021-11-28 at 2 18 28 PM](https://user-images.githubusercontent.com/69029666/143725222-263695fa-6972-421c-9a3b-6ffbb7d60b23.png)

**Comment by GScottElshaw** [comment] 2021-11-29 03:00
Speaking of hover-data, is this useful any longer? Bytes?

![Screenshot 2021-11-29 at 3 57 54 PM](https://user-images.githubusercontent.com/69029666/143801943-a9412a30-3c4f-4211-a646-82d7fd097550.png)

**Comment by nevack** [comment] 2021-11-29 11:28
> Speaking of hover-data, is this useful any longer? Bytes?
> 
> ![Screenshot 2021-11-29 at 3 57 54 PM](https://user-images.githubusercontent.com/69029666/143801943-a9412a30-3c4f-4211-a646-82d7fd097550.png)
> 
> Could someone please put me in touch with whomever designs or designed the icons for the main window and inspector for MacOS?

Icons can be updated with SFSymbols, like it was done for other placed when updated to Big Sur

**Comment by fxcoudert** [comment] 2021-11-29 13:04
First tab could be `info.circle`:

![Capture d’écran 2021-11-29 à 13 56 50](https://user-images.githubusercontent.com/1980544/143872052-8b83a81b-f5af-4103-95bd-0799450de3c6.png)

Second one is harder to find. Maybe a puzzle piece? 

![Capture d’écran 2021-11-29 à 14 04 21](https://user-images.githubusercontent.com/1980544/143873094-bd9b3e7d-fcbe-4660-b302-19db41a9833a.png)


Third one could be `antenna.radiowaves.left.and.right`:

![Capture d’écran 2021-11-29 à 13 58 15](https://user-images.githubusercontent.com/1980544/143872232-d0e88a3f-ca07-4ceb-b4d7-8cbfc33c7016.png)

Fourth could be `person.3.fill`:

![Capture d’écran 2021-11-29 à 14 01 23](https://user-images.githubusercontent.com/1980544/143872706-598ee1d3-06be-48c5-97f9-9d276ffae146.png)

Fifth could be `doc.on.doc`:

![Capture d’écran 2021-11-29 à 14 00 49](https://user-images.githubusercontent.com/1980544/143872610-3fe85d87-34fe-41b7-951b-0739bc029d0e.png)


And sixth `gearshape`:

![Capture d’écran 2021-11-29 à 13 59 52](https://user-images.githubusercontent.com/1980544/143872574-fde0ce13-45a5-4f90-9d4a-4093af3ffdf5.png)

**Comment by livings124** [comment] 2021-11-29 13:17
I recommend opening a new ticket if you don't want this icon discussion list.

Re: ascent color, I'm open for other colors, but using black and white seems less like an accent color that matches the branding of Transmission (the designed intent of ascent colors) and more like a hack around theming the system towards personal ascetics.

**Comment by nevack** [comment] 2021-11-29 14:51
> I recommend opening a new ticket if you don't want this icon discussion list.
> 
> Re: ascent color, I'm open for other colors, but using black and white seems less like an accent color that matches the branding of Transmission (the designed intent of ascent colors) and more like a hack around theming the system towards personal ascetics.

I think it's possible to use different shades of accent color for different situations.

I agree that branding is important, but we can change color for situations when this color attracts too much attention.
Red is looking perfect for default controls, but I agree with @fxcoudert that it's too bright for large row selection.

Maybe it's better to use another marker for selected rows? Like some border, dot, checkmark, etc.

**Comment by livings124** [comment] 2021-11-29 15:03
> I think it's possible to use different shades of accent color for different situations.
> 

You can select one color for light mode and one for dark (and they should be roughly the same, just adjusted slightly to match light/dark elements).

> 
> 
> I agree that branding is important, but we can change color for situations when this color attracts too much attention.
> 

Nope, not how ascent color works. A single color (per light/dark mode) can be set and cannot be changed at runtime.

> Red is looking perfect for default controls, but I agree with @fxcoudert that it's too bright for large row selection.
> 
> 
> 
> Maybe it's better to use another marker for selected rows? Like some border, dot, checkmark, etc.
> 
> 

We won't be diverging from the standard system behavior.

**Comment by nevack** [comment] 2021-11-29 15:07
> You can select one color for light mode and one for dark (and they should be roughly the same, just adjusted slightly to match light/dark elements).

But it's possible to adjust NSColor value afterward, isn't it? I mean, on a per control basis.

**Comment by livings124** [comment] 2021-11-29 16:04
> > You can select one color for light mode and one for dark (and they should be roughly the same, just adjusted slightly to match light/dark elements).
> 
> 
> 
> But it's possible to adjust NSColor value afterward, isn't it? I mean, on a per control basis.

This value is hard coded in the plist and is not designed to be per-control.

**Comment by GScottElshaw** [comment] 2021-11-30 00:23
> more like a hack around theming the system towards personal ascetics.

Ouch.

The context of my original point was with regard to accessibility, red is just not a good colour to use when text is involved. A monochromatic option would be great for users who have various sight issues. It is also why i pointed out that having the option to increase font sizes would also help dramatically (it's my 51st birthday today, and the font size on this macbook air, for the 'Seeding to' information has my eyes constantly moving focus as i glance at other information, and that is partially to do with the font size and accent colour options).

In my professional work? I work in branding, web comms, accessibility, UX/UI design across platforms and hardware. Which of these windows is no longer on brand?

Ascetically yours,
Gary

![Screenshot 2021-11-30 at 1 01 33 PM](https://user-images.githubusercontent.com/69029666/143963199-e8d50ed2-1288-439c-83f7-0413dd272c35.png)

**Comment by livings124** [comment] 2021-11-30 02:52
A monochromatic option seems like something that should be at the system level with the other accessibility options. With specific regard to accent color, the color should of course not cause accessibility issues, but should highlight the app's brand/theme. Perhaps a softer red? [Here's a blog post](https://512pixels.net/2020/11/big-sur-accent-highlight-colors/) about accent color, since I think there might be some disconnect on what we're talking about.

**Comment by GScottElshaw** [comment] 2021-11-30 03:42
Thank you. 

I agree, but no platform has ever integrated a full accessibility matrix at the system level, and the majority rely on developers to provide the basis for doing it, there is no magic bullet. If I could increase font size at a system level on a per application basis i'd do it, but i cannot which is why I suggested looking at the increase/decrease code for [Cog](https://github.com/losnoco/Cog). It has a similar look and feel to Transmission and deals with font increases/decreases, I think, elegantly, across both the main window and an inspector window. 

I should make clear, I'm not proposing two changes necessarily, but if you must keep red, allow for the increase in font sizes - or change the default colour. For purely accessibility (colour-blindness) reasons and legibility purposes, red is not a good colour.

As I pointed out, I think, if your concern is branding, I think you need to have a full discussion with the other contributors about the current state of what the brand is, because post-3.0 it is not consistent anymore. And certainly not across platforms. I think that's okay to a certain extent. For example, an accent colour is not a branding issue if the accent colour can be chosen. The branding issue/hill I would hold on to is the look and feel of the main window and the inspector window. That is unique to Transmission. That image I posted? There is only one inconsistent window and it is not the preferences or main windows. 

I read the blog post, but it's not particularly relevant to what I have been talking about in that users have for a long time wanted to control system-level colour changes. It is apples and oranges, Transmission does not allow this, and as I have mentioned elsewhere, I keep the plist open in my txt-editor of choice and regularly change line 92 to 'Blue'. Night or day modes it offers the best contrast for reading the text.

**Comment by fxcoudert** [comment] 2021-11-30 09:02
I fear that some of that discussion is going away in tangents, and actually not relevant to the existing macOS UI (or existing possibilities). macOS has many options for accessibility, and the goal of achieving greater accessibility of Transmission should be achieved by leveraging those, rather than reinvent the wheel.

- Bigger text? There is a system-wide default for enabling this, and you can use a hotkey to increase the size of any text element in the UI. I checked, and it works on Transmission.

- There are also options for high contrast mode, choosing your own Accent color, and even setting color filters (including gray).

Some of the discussion on Accent color seems to misunderstand what it is. Every app has one accent color (with two “variants”, for light and dark UI). That Accent color is used only *if the user has not specific their own system-wide accent color*. So whatever is given in Transmission is not override users choice, and in particular if a user has specific concerns about Accent color, they will surely have set it in a way suitable to them.

**Comment by livings124** [comment] 2021-11-30 11:57
100% @fxcoudert

We should keep this a ticket about improving accent color, which does include improving readability but not re-inventing accessibility on Mac platforms.

If someone could propose an accent color that is easier to read when used as a highlight color that also fits with Transmission's branding (primarily red, but open to other possibilities) I think we can move forward with this issue.

**Comment by GScottElshaw** [comment] 2021-12-01 00:48
> * Bigger text? There is a system-wide default for enabling this, and you can use a hotkey to increase the size of any text element in the UI. I checked, and it works on Transmission.

Please tell me how this can be enabled.

> * There are also options for high contrast mode, choosing your own Accent color, and even setting color filters (including gray).

Yes, but this is a system-wide option, yes? It applies to all applications and can't be used on a per-application basis.

**Comment by mangosplat** [comment] 2021-12-01 17:46
Hello. I'm going to put aside the text, contrast, accessibility issues, etc. aside since I believe they are off topic, I think transmission handles them pretty well, and I don't think its this project's concern to manually handle them anyways.

I quite liked the theme-ing transmission used previously (default/blue). It was unified across platforms (e.g. mac and the web client looked similar). Since no one has suggested it yet, would it be possible to just revert the accent color added since (55e8833) ? I find myself missing the old aesthetic. I don't feel like many apps use their brand's accent color for menu selection and in just my subjective opinion it looks tacky with the color everywhere. Just an idea.

![image](https://user-images.githubusercontent.com/95374372/144285348-8aa4eb31-2fa4-4234-9afa-c2bc67533ddf.png)

![image](https://user-images.githubusercontent.com/95374372/144285379-d80b90f2-20e5-48d1-a7b6-31dda8fb269c.png)

**Comment by livings124** [comment] 2021-12-07 02:35
@mangosplat You can have the previous blue by setting that as the ascent in the general section of System Preferences. I am hoping to find an exact color that makes the most sense as the ascent color for Transmission, which I don't believe is an explicit blue unfortunately.

**Comment by mangosplat** [comment] 2021-12-07 02:42
@livings124 Sure I can understand that. If you are set on adding an accent colour and would like red, here are some other apps I know that use various shades of red as an accent colour for reference: apple music, apple calendar, openemu

I think a similarity to note is that they don't overuse it

**Comment by GScottElshaw** [comment] 2021-12-07 02:42
The accent colour can't be changed in the preferences, only in the .plist (on OSX) at line 92. The 'Groups' colour can be changed in the preferences, but that's something else.

**Comment by livings124** [comment] 2021-12-07 02:44
> The accent colour can't be changed in the preferences, only in the .plist (on OSX) at line 92. The 'Groups' colour can be changed in the preferences, but that's something else.

You can disable per-app customizations in General preferences.

**Comment by GScottElshaw** [comment] 2021-12-07 02:47
As in?
![Screenshot 2021-12-07 at 3 46 46 PM](https://user-images.githubusercontent.com/69029666/144956926-8c9283c3-bc6f-4257-992b-4a92b7a0644c.png)
?

**Comment by livings124** [comment] 2021-12-07 02:48
@GScottElshaw Yup, change accent from multicolor to a constant color

**Comment by GScottElshaw** [comment] 2021-12-07 02:51
That seems a bit overkill to do that at a system level, no?

**Comment by livings124** [comment] 2021-12-07 02:53
As opposed to having the app developer change it to your preference? I'm very openly asking for explicit suggestions (or even better, PRs) for an appropriate accent color for this app, but prefer not to use generic blue unless we're completely stuck here.

**Comment by GScottElshaw** [comment] 2021-12-07 02:59
Why not have a default accent colour and have the ability for _users_ to change it in preferences as they can for groups?

**Comment by livings124** [comment] 2021-12-07 03:03
> Why not have a default accent colour and have the ability for _users_ to change it in preferences as they can for groups?
1. You cannot change accent color at run time when using standard APIs.
2. Even if you could, Transmission is by design meant to be lightweight, and an "in-app accent color customization setting" would be antithetical to that.

**Comment by GScottElshaw** [comment] 2021-12-07 03:08
A run time ability to ad hoc individually colour files by group, but an inability to change an accent colour without a text editor or adjusting OS preferences. Got it. Thanks.

**Comment by fxcoudert** [comment] 2021-12-07 08:25
There is no accounting for taste, and we have to respect the overall macOS UI, so there is limited choice. Options are:

- Remove accent color altogether, revert to system default, the blue
  - Pros: reverts to known behaviour, familiar to users, probably easier on the eye
  - Cons: 
- Try to use red to match Transmission's icon
  - Pros: branding/visual identity
  - Cons: it's a lot of red when you select transfers, might be less accessible to visually-impaired users

In all cases, if the user has set a system-wide accent color, this will take precedence.

My personal preference would be to keep the old behaviour, which will upset nobody ;) But since @livings124 doesn't favour that, if we use red, I suggest using macOS's own tint of red:

<img width="441" alt="Capture d’écran 2021-12-07 à 09 25 04" src="https://user-images.githubusercontent.com/1980544/144993133-5438707f-386b-4594-bcbe-b731ca7b3be0.png">

which would probably be the most consistent choice, UI-wise. I've opened a PR to do that: https://github.com/transmission/transmission/pull/2278

**Comment by livings124** [comment] 2021-12-12 22:45
I've merged in the PR to match the system's red color. It seems less intense and should be more accessible.

**Comment by GScottElshaw** [comment] 2021-12-12 22:51
I'm afraid the shade of this colour makes no difference with regards to accessibility. It is red. http://web-accessibility.carnegiemuseums.org/design/color/

**Comment by livings124** [comment] 2021-12-12 23:41
> I'm afraid the shade of this colour makes no difference with regards to accessibility. It is red. http://web-accessibility.carnegiemuseums.org/design/color/

That site doesn't say to not use red as a highlight color; in fact it gives examples of different reds to use as background colors. The point made is to not use green-on-red or red-on-green.

Also, this is the red Apple uses in Calendar and as the explicit red accent color in Settings.

**Comment by DevilDimon** [comment] 2021-12-21 14:16
> The point made is to not use green-on-red or red-on-green.
That's exactly what happens with seeding torrents, though
<img width="129" alt="Screenshot 2021-12-21 at 14 15 26" src="https://user-images.githubusercontent.com/10220441/146944381-473e043d-28b2-4ae5-9a69-516a6b881a8f.png">

**Comment by shatteredsite** [comment] 2022-02-11 19:58
Just to preface, I have worked in political marketing and web design (think PACs and nonprofits) for years. I focused on creating/rebuilding, highly legible, accessible (to ADA standards) sites to appeal to a wide range of demographics. I also work as an artist part-time in multiple media.

Aside from the red being terrible for those with deuteranopia (red-green colorblindness), which affects about 4.5% of the total population, the change in accent color is a prime example of 'if it ain't broke, don't fix it.' When it comes to the the accent color, it is important to keep in mind basic color theory. Bright red takes the eye away from the important information as red is an intense/hot color that draws the user's eyes towards the background, making what is in the foreground less immediately legible. The order in which we focus ends up reversed. It also denotes something is wrong, an error, or an emergency, which will be confusing to some. It is a terrible irritant that I avoid in design with substantial text at all costs, even though red is my favorite color personally.

The red accent color will do nothing for in-app branding regardless. A simple, well designed icon in the toolbar next to the app name would be far more effective, if old school. There are other options to explore, but that would be the most simple. However, the branding you really need to be concerned with is getting users to download the app in the first place. In-app branding is icing on the cake at best. What will keep people using this app and spreading the word is functionality and ease of use. The red detracts from that.

The website is a far better focus in terms of branding. Right now it needs a complete redesign and would do **far** more good with far fewer headaches or conflict. The site visually screams 'not maintained' and it has also been a while since a major release, compounding the issue further. I would be willing to design/build/contribute to it, however this is not the thread for that.

I beg you, eliminate this red monstrosity.

**Comment by ckerr** [comment] 2022-02-12 00:58
@shatteredsite I'm not going to get between you and the main mac dev for the project about the macOS client's look and feel, but I do appreciate the _other_ topic that you raised here about the website. If you want to start a discussion thread on that or file a separate issue to discuss that away from this topic, please do, because I agree with you there that it needs a refresh.

FWIW the website's repo is at https://github.com/transmission/transmission.github.io if you'd like to start making pull requests too :smiley:

**Comment by GScottElshaw** [comment] 2022-02-12 01:10
@shatteredsite I'm in if you are.

**Comment by livings124** [comment] 2022-02-12 02:22
Seems like the large majority consensus is to kill the tint, so it'll be removed before the next release.

**Comment by livings124** [comment] 2022-02-21 14:41
The accent color has now been removed in https://github.com/transmission/transmission/pull/2671

**Closed by livings124** 2022-02-21 14:41 UTC
Labels: scope:mac, pr welcome
