### ISSUE TITLE
Transmission 20220531 hanging and how to safely export all settings and torrents

### ISSUE THREAD

**Issue by karimsah** [transmission/transmission#3171] opened 2022-06-01 09:31 UTC
Hi !
20220531 transmission Nightly hangs with no crash on Windows 10.
The same behaviour happens with latest stable 3.0.0 .
I suspect some file corruptions in my config/torrent files.

1. Is it possible to export settings safely on Windows ?
2. Which folder/files to copy ?
3. Any advice to give me to get logs from hanging executable ?

Thank you !

**Comment by ckerr** [comment] 2022-06-01 17:31
Hanging without a crash sounds like a duplicate of https://github.com/transmission/transmission/issues/2462 -- the most common case is it hangs while writing data to a slower disk or networked disk.

Fixing this is on the longer-term TODO in 2462.

**Closed by ckerr** 2022-06-01 17:31 UTC
Labels: duplicate
