### ISSUE TITLE
Community Forum [yes I know this doesn't belong here]

### ISSUE THREAD

**Issue by sararielle** [transmission/transmission#4964] opened 2023-02-20 16:26 UTC
### What is the issue?

I'm sorry to post this over here. I know it doesn't belong here (but I can't figure out how else to ask). I am trying to access the community support boards but I don't appear to already have an account and registration appears to be broken.  Everything says "contact an administrator" but I can't find contact information that doesn't require a functioning account.  Is there someone I can reach out to for help?

### Which application of Transmission?

None

**Comment by robd003** [comment] 2023-02-20 17:48
Are you also stuck on the "I agree to these terms" step and it just reloads the page without continuing?

**Comment by ckerr** [comment] 2023-02-20 18:04
Hi @sararielle, thanks for reporting this.

I think this is a duplicate of https://github.com/transmission/transmission/issues/4853 so I'm closing this one as a dupe. Please subscribe to 4853 to get updates on that ticket. Thanks!

**Closed by ckerr** 2023-02-20 18:04 UTC

**Comment by sararielle** [comment] 2023-02-20 18:17
thank you! I apologize for not having realized it was a dupe.
