### ISSUE TITLE
New version v 4.0.1. doesn't allow to limit download speed anymore

### ISSUE THREAD

**Issue by Nickoparis** [transmission/transmission#5125] opened 2023-03-02 10:10 UTC
### What is the issue?

Limiting transfer speed always worked but since new release it doesn't.
Whatever settings you do, it goes up to max speed download.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1 (e1c6e1be43)

**Comment by ckerr** [comment] 2023-03-02 13:26
Hi @Nickoparis, thanks for reporting this!

I think this is a duplicate of https://github.com/transmission/transmission/issues/4701 so I'm closing this one as a dupe. This is fixed by https://github.com/transmission/transmission/pull/5086.

**Closed by ckerr** 2023-03-02 13:26 UTC
