### ISSUE TITLE
Port forwarding stops working after awhile

### ISSUE THREAD

**Issue by catadropa** [transmission/transmission#2920] opened 2022-04-15 20:43 UTC
In my message log:

```
Mon Apr 11 04:00:15 2022        Information     upnp.cc:359     If your router supports UPnP, please make sure UPnP is enabled!
Mon Apr 11 04:00:15 2022        Information     upnp.cc:303     Port 51413 is not forwarded
Sun Apr 10 09:49:56 2022        Information     port-forwarding.cc:110  State changed from 'Starting' to 'Forwarded'
Sun Apr 10 09:49:56 2022        Information     upnp.cc:353     Port 51413 is forwarded
Sun Apr 10 09:49:56 2022        Information     upnp.cc:280     Local Address is '192.168.0.100'
Sun Apr 10 09:49:56 2022        Information     upnp.cc:279     Found Internet Gateway Device 'http://192.168.0.1:49152/soap.cgi?service=WANIPConn1'
Sun Apr 10 09:49:55 2022        Information     port-forwarding.cc:110  State changed from 'Not forwarded' to 'Starting'
Sun Apr 10 09:49:54 2022        Information     session.cc:753  Transmission version 3.00+ (205abbbcce) starting
```
(Log entries from newest to oldest)
Startup here was 9am, 10 Apr. So port forwarding got established on startup. Then at 4am that night, perhaps with my Gateway Device rebooting, port forwarding stops and stays stopped forever more.

Shouldn't there be logic to retry port-forwarding, knowing that it was working fine since startup?

**Comment by vodzl** [comment] 2023-01-13 06:05
Hello,
I think i run into the same issue.
Win10, x64, beta3

First launch during Windows session has UPnP working but when i exit transmission and start it several hours later then 
UPnP doesn't work at all until Windows is restarted. I have tried it with same port and randomize ports option enabled.

**Comment by Vexariboerl** [comment] 2023-01-19 21:49
I posted a similar issue with Transmission here:
[Port closed after a few days on M1 mac](https://github.com/transmission/transmission/issues/4618)

**Comment by ckerr** [comment] 2023-01-19 23:23
Closing as a duplicate of #2223.

**Closed by ckerr** 2023-01-19 23:23 UTC
Labels: bug, scope:core, pr welcome
