### ISSUE TITLE
I can't download any Torrent/ No puedo descargar ningún Torrent.

### ISSUE THREAD

**Issue by CamiloPSEVEN** [transmission/transmission#6778] opened 2024-04-10 05:58 UTC
### What is the issue?

I try to download the Torrents but the download never proceeds/ Trato de poner a descargar los Torrents pero las descargas nunca proceden.
![ERR](https://github.com/transmission/transmission/assets/166586931/568b06e6-55ba-4a1b-b154-f06a7c341fa7)

### Which application of Transmission?

None

### Which version of Transmission?

transmission-4.0.5-qt5-x64.msi

**Comment by killemov** [comment] 2024-04-10 10:55
Please remove references to any copyrighted material.

Also duplicate of #6772.

**Comment by CamiloPSEVEN** [comment] 2024-04-11 04:51
> Elimine las referencias a cualquier material protegido por derechos de autor.
> 
> También duplicado del [n.° 6772](https://github.com/transmission/transmission/issues/6772) .

It's done, now how do I fix the problem?

**Comment by isaiasluc** [comment] 2024-04-11 15:04
Did you checked if the torrent has peers?

**Comment by killemov** [comment] 2024-04-11 15:26
> Did you checked if the torrent has peers?

Judging from the screenshot: There are no peers.

**Comment by isaiasluc** [comment] 2024-04-11 15:43
> > Did you checked if the torrent has peers?
> 
> Judging from the screenshot: There are no peers.

So the client is unable to find any other users who are sharing or downloading the same file(s) you are interested in, basically...

**Comment by isaiasluc** [comment] 2024-04-11 15:44
I suggest you to test with a torrent file who has many peers available

**Closed** 2024-05-13 08:41 UTC
