### ISSUE TITLE
New WebUI / API initiated transfers stuck on "verifying" for a long time before beginning

### ISSUE THREAD

**Issue by aniqueta** [transmission/transmission#1467] opened 2020-10-10 23:00 UTC
This issue arises on macOS Catalina using the desktop version (not daemon) of Transmission 3.0.0. This issue existed prior to 3.0.0 and on macOS Mojave, and has persisted across a reformat and fresh install.

When the Mac is in "lock screen" mode, new transfers that are created remotely using the WebUI or automatically via API access remain stuck on "verifying" for ~30 min. The progress on verifying moves slowly forward to ~25% and then eventually completes quickly. Eventually, the transfer moves to download or upload and works as normal.

A resolution to this "verifying" delay is to unlock the screen either physically or over VNC/Screen Sharing. 

I'm not sure what is the reason for this, but I believe recent versions of macOS have security measures that change how apps work without user interaction and when the screen is locked. I don't think this is the reason though, since eventually the transfer works as normal. 

I have not tried the headless daemon version, since I do want to keep desktop UI, and I would prefer not to install Homebrew. 

Happy to help debug and troubleshoot.

Thank you!

**Comment by ckerr** [comment] 2022-01-18 06:01
Closing duplicate of #1118

**Closed by ckerr** 2022-01-18 06:01 UTC
