### ISSUE TITLE
Client hangs while moving data files

### ISSUE THREAD

**Issue by pawel-jurczyk** [transmission/transmission#694] opened 2018-08-21 09:24 UTC
The app is most likely using the main thread when moving the data files, thus in seems that it's hung for the duration of the transfer. This is especially visible for large files or slow drives.

**Comment by pyrovski** [comment] 2018-09-17 05:50
Moves are executed in the event thread via a synchronous function: https://github.com/transmission/transmission/blob/a53bae2849f5709ffafec8ab6505ca4002ca5309/libtransmission/torrent.c#L3328. This problem is emblematic of all filesystem IO in Transmission; if the disk is slow or the filesystem is mounted over the network, the IO will block the event loop.

**Comment by bukazoid** [comment] 2018-12-01 08:16
I have same issue. I have preload drectory on local drive but the target directory is a mounted to another computer through the internet. The connection speed is quite unstable and it is between 1-10Megabytes per seconds, so, for big files(i am talking about gigabytes) it is an issue. So, when downloads are finished and preloaded files copying to the target directory, gui interface become inaccesible. It would be nice to have copying operations in separate thread.

**Comment by bjzy** [comment] 2018-12-29 20:57
Same problem. Would love it if this could be fixed. I run a script nightly to move recently downloaded torrents from my fast drive to long term seeding/storage which is on a slower disk. My GUI is unresponsive during a lot of the moves, especially very large files.

**Comment by Yonn-Trimoreau** [comment] 2019-01-20 14:41
Same issue here... Does anyone have a fix? This behavior triggers systemd's Restart=on-failure event and restarts transmission unexpectedly..

**Comment by RobCrowston** [comment] 2019-07-11 23:35
I notice this problem when a torrent of say ~100 GB completes. Even moving files within the same RAID (but across file systems), it takes many minutes to finish, during which the client sits unresponsive. The transfer should be made asynchronous.

**Comment by andreygursky** [comment] 2019-07-20 11:25
At least two disk intensive functions are executed in threads (using ```tr_threadNew()```):
* ```tr_verifyAdd()```
https://github.com/transmission/transmission/blob/eef47993887a486890fe3116c828a1e939bf1b69/libtransmission/verify.c#L269
* ```tr_makeMetaInfo()```
https://github.com/transmission/transmission/blob/eef47993887a486890fe3116c828a1e939bf1b69/libtransmission/makemeta.c#L567

**Comment by ckerr** [comment] 2020-04-30 22:16
This looks like it's a duplicate of #108; closing.

**Closed by ckerr** 2020-04-30 22:16 UTC
