### ISSUE TITLE
Web client text unreadable in dark mode

### ISSUE THREAD

**Issue by 1100101** [transmission/transmission#3834] opened 2022-09-21 21:08 UTC
I'm using the latest Transmission from `develop`, but for a while now I noticed that text in the web client's torrent details, or tracker page is unreadable. It's very light grey text on a white(ish?) background.
I see this on a Windows 11 machine in dark mode (using Firefox or Edge), as well as on an iPad mini, also in dark mode.
Once I switch either device to light mode, the text becomes readable again.

I found #2609 which supposedly should've fixed this?

**Comment by GaryElshaw** [comment] 2022-09-22 13:49
@ckerr Any tips on where i should start looking to help fix this?

**Comment by ckerr** [comment] 2022-09-22 13:53
It's likely something in the scss file in `web/assets/css`. There are a few dark / light mode customizations there @ https://github.com/transmission/transmission/blob/main/web/assets/css/transmission-app.scss#L111

**Comment by GaryElshaw** [comment] 2022-09-22 14:44
@1100101 Because it can be weird, if you navigate to line 111 and change these values to transmission-app.scss, does it resolve your issue?

`  @media (prefers-color-scheme: dark) {
    --color-fg-primary: #{$grey-400};
    --color-fg-secondary: #{$grey-300};
    --color-fg-tertiary: #{$grey-200};`

**Comment by ckerr** [comment] 2022-09-22 15:13
(Also to be clear,  you have to rebuild the web app before the change will take effect. Sass converts the scss into css, which then gets webpacked up with the rest of the app)

**Comment by 1100101** [comment] 2022-09-22 18:36
@GaryElshaw Yes, that worked. The text in those screens is now readable again.

Since actually there isn't much difference in the overall appearance of the web interface between dark and light mode (the main window stays white, the menu bar does not change color etc), I decided to use the same values for primary/secondary/tertiary color as for `color-schema: light`.
Now there really is no difference between light and dark.

**Comment by GaryElshaw** [comment] 2022-09-22 21:55
@1100101 Frank can you please show me a screen shot of the change? At some point i want to pull apart the entire theme.

Charles, is the change i've suggested something that should permanently change?

**Comment by ckerr** [comment] 2022-09-22 22:07
> Charles, is the change i've suggested something that should permanently change?

IDK, let's see the screenshot :smile_cat:

**Comment by 1100101** [comment] 2022-09-23 09:48
Here are the requested screenshots:

### Light mode
![01 light mode](https://user-images.githubusercontent.com/1006337/191934756-2b6822af-44b9-4af1-83e5-e54872adeaa1.jpg)
### Dark mode (before the change)
![02 dark_mode old](https://user-images.githubusercontent.com/1006337/191934801-8b053f57-624f-4196-a3b9-fb76a2ac6704.jpg)
### Dark mode (after the change)
![03 dark_mode new](https://user-images.githubusercontent.com/1006337/191934809-d0ba8f94-c4a5-48d3-a5d3-2839baa96229.jpg)

While the text on the details page is now quite readable, some of the other text values (# of torrents, up/down speed) are now less readable.

**Comment by GaryElshaw** [comment] 2022-09-23 16:31
Thanks for sharing those Frank. Essentially, dark mode is busted right now, and needs reworking for white text to appear on a black background. Thanks for bringing it to the project's attention, i'm not sure when it will be fixed, but it's on the list!

**Comment by ckerr** [comment] 2022-09-23 18:45
Yeah, looks to me like the problem isn't the text color, but background color in dark mode should actually be dark

**Comment by ckerr** [comment] 2022-10-21 17:24
Fixed by https://github.com/transmission/transmission/pull/3985

**Closed by ckerr** 2022-10-21 17:24 UTC
Labels: scope:web, pr welcome, good first issue, type:ui
