### ISSUE TITLE
Downloading two torrents with conflicting filenames causes bug

### ISSUE THREAD

**Issue by Harvie** [transmission/transmission#1200] opened 2020-05-02 09:28 UTC
Hello,
i've been using transmission for some time without any problems, but recently it happend to me that i've started downloading two torrents. unfortunately i didn't noticed that both contained only one file and the name was exactly the same. This caused transmission to overwrite the file, so one of the torrents reported "please verify local data".

There should be some check for this, possibly adding suffix to filename. like web browser does, when you download same file twice...

**Comment by andrew-phi** [comment] 2020-05-26 10:39
I think an internal check like this would suffice to prevent this problem:
OnAdd(newtorrent)
{
for (name = newtorrent.filenames...)
  if (existing = FindInAllOtherTorrents(name))
   if (existing.CRC != new.CRC)// allow same files in different torrents
     return fail;
}
So transmission may refuse to add torrent until user specifies different locaiton.

**Comment by andrew-phi** [comment] 2020-05-26 10:47
Of course it would be better to check if a file about to be downloaded belongs to any other torrent and has different checksum. (sorry, somehow github refuses to edit comments)

**Comment by sserdda-liamE** [comment] 2020-05-27 03:23
The issue with torrent clients is that they need to point to the same file to facilitate cross seeding.  If I point it to Totally.Legal.Download.BD.1080p.AC3.YIFY which already exists and the client decides to make Totally.Legal.Download.BD.1080p.AC3.YIFY (2) and redownload the whole thing, that just doesn't work.  You can't really treat having files with the same name as worthy of any sort of special warning because cross-seeding is far, far, far, far, far more common than trying to download two different files into the same directory with the same name.

The typical behavior of a torrent client will be to hash check to the existing file, and if it doesn't check, to overwrite.  (if you didn't want it to overwrite you should've loaded the torrent it in a stopped state, forced recheck, and then decided what to do based on the result of the check)
Adding the torrent in the started state says you want it to download the contents of the torrent.
You can have a partial download from another tracker or even a completely empty file so the failure to hash check to the entirety of the file doesn't mean you don't want it to continue.

The only check that I can think of that says. "Something isn't right here," would be a *file size* mismatch.  If the file sizes don't match they can't check to each other and it would be nice to get a warning on this condition.
So for example if I have Totally.Legal.Download.BD.1080p.AC3.YIFY.mkv and I'm trying to cross seed to a mkv with the same name but which someone has muxed Finnish subtitles into, I probably do not want to overwrite my original download with the new one when they fail to hash check to each other.
So a popup with something like, "Warning, files already exist in on disk with different file sizes from torrent contents.  Overwrite?" might be helpful.

**Comment by NSQY** [comment] 2021-11-16 10:39
A simple warning would be sufficient in my case.

**Comment by ckerr** [comment] 2022-02-11 06:43
This is a duplicate of #251

**Closed by ckerr** 2022-02-11 06:43 UTC
Labels: enhancement
