### ISSUE TITLE
Why re-add to re-download?

### ISSUE THREAD

**Issue by JustMyGithub** [transmission/transmission#1358] opened 2020-07-11 09:49 UTC
"No data found! Ensure your drives are connected or use "Set Location". To re-download, remove the torrent and re-add it"

Why is it handled this way? Why does the user have to re-download the torrent (er extract it from transmission folders manually)?

If a recheck in the wrong location would reset the current location by accident this would be easily repared by changing the directory to the correct one or movin the files into the chosen directory and recheck then.

So I do not understand why this decision was made.

**Comment by euclip** [comment] 2020-07-11 23:28
What actually causes this error to happen? I've seen it a couple times now after upgrading to 3.0. The drive is connected (it's internal) and the location is correct.

**Comment by JustMyGithub** [comment] 2020-07-12 02:33
I think this happens when you recheck data and there is no data anymore in the destination folder. If your observation is correct (and the drive was not disconnected somehow) I don't know why/how this occurs for you. 
I am still using 2.94.

**Comment by strpkg** [comment] 2020-07-13 01:48
@euclip 

> What actually causes this error to happen? I've seen it a couple times now after upgrading to 3.0. The drive is connected (it's internal) and the location is correct.

This is caused by the new file and dir name sanitization in the newest version v3.00.
After the upgrade, it expect sanitized file and dir names on disk, but unfortunately it doesn't update the existing file and dir names with on disk, which breaks the link between the files and the torrent.

See [https://github.com/transmission/transmission/issues/1325](https://github.com/transmission/transmission/issues/1325)

**Comment by pradorocchi** [comment] 2020-11-18 16:54
On MacOS this also happened on previous (2.94) version and on current v3 version, 
it is easy to replicate on MacOS:

Close Transmission, manually delete some files, open Transmission again. 
It does never re-checks, and return that same message, even if I put back the deleted file(s) again there. 

Transmission can be closed again, and relaunched again.. N times, and it will never continue that torrent [which I manually deleted some files, or all files, etc..)

The only way I can make it goes and recheck is: by deleting the torrent from the its queue via Transmission interface (but not the torrent data) and re-add the torrent. After re-adding, it will notice that there are incomplete files on the disk (which already were there) and will re-check them and continue to download.

Happens on 2.94 and also on current version.

I am currently investigating the code to check if I can find the cause and adjust it.

_This is only a complementary comment to this thread, to clarify the situation, since I know about what the OP is telling._
PS: I am specifically refering to the MacOS version

**Comment by JustMyGithub** [comment] 2020-11-29 09:21
I noticed at least two of my downloads are broken. This maybe caused by a kernel panic, but now I have to recheck all downloads just to be sure nothing else was lost. Due to this bug in transmission I have to readd all downloads anyway, so I will now try other clients to easy this in the future. Goodbye transmission, I mostly liked you.

**Comment by belialboy** [comment] 2021-06-28 12:19
I'm experiencing this same behaviour in Transmission 3.00 (bb6b5a062e) in docker. Drive is mounted, but torrents loose 'link' is the container is rebooted. Need to delete the torrent and re-add for it to get picked up.

**Comment by nikolai5slo** [comment] 2022-01-06 06:50
I had same problems. Once happened that my drive didn’t mount and transmission put all my torrents (100+) into this state. I tried "verify local data" and "set location" and nothing helped. I had to re-add them all by hand.

**Comment by ckerr** [comment] 2022-01-27 04:37
Duplicate of #83

**Closed by ckerr** 2022-01-27 04:37 UTC
