### ISSUE TITLE
[Windows] File allocation problem when doing selective download

### ISSUE THREAD

**Issue by kissglay** [transmission/transmission#595] opened 2018-04-28 08:11 UTC
Assume the torrent contains file: 1, 2, 3, 4.
If only download file 3, and pieces cross the boundary of file 3 to file 2 and 4, then the file 2 will be fully allocated rather then a sparse file, but the file 4 as a single piece. Maybe this's because the block getting allocated is at the end of file 2 but header of file 4. But if the file 2 is large enough, like above 20G, The whole Transmission would freeze for a very long time (depending on the file size) and you can't do nothing until the file is fully allocated. 

This issue was reported 2 years ago on the transmission forum and has long been fixed by the discontinued unofficial Transmission-QT. 
For further detail, plz refer to https://forum.transmissionbt.com/viewtopic.php?f=17&t=17934

**Comment by m0n** [comment] 2018-12-04 12:49
This is so BIG issue and can't be fixed for years? I just downloaded a smaller-than 4GB file and it used up 16GB because a few non-sparse-allocated & unwanted files (3-5GB each).

**Comment by kevvood** [comment] 2019-08-18 16:08
Please, do something about this issue. How many HD were killed around the world because of this behavior. I don't kown if this is a Windows only problem. I read elsewhere something about a mecanism using a torrent pieces cache for unselected files, seems a good idea. How about sparse files; might not be portable, not sure? I love Transmission but it is painful to let those unselected files to be created, they use space (sometimes A LOT) and stress the HD(s).

**Comment by kissglay** [comment] 2019-08-18 17:10
I've ditched transmission for good and switched to qBittorrent. Maybe it'll never be fixed.

**Comment by ckerr** [comment] 2022-02-22 21:02
Duplicate of #290

**Closed** 2022-02-22 22:55 UTC
Labels: duplicate
