### ISSUE TITLE
Ctrl-V Copy-Paste Keyboard Shortcut is Broken

### ISSUE THREAD

**Issue by AJMansfield** [transmission/transmission#5317] opened 2023-03-28 20:22 UTC
### What is the issue?

When adding a torrent, I am unable to use the ctrl-v keyboard shortcut to paste a magnet link or other information into the "Or Enter a URL:" field in the "Add Torrents" dialogue; instead, attempting to paste this way triggers the "verify data" function on all selected torrents in the main list interface behind this dialogue.

Pasting via other means does work: both shift-insert and right-click-paste are able to paste the clipboard into this field. Copying selected text from this dialogue with ctrl-c also still works.

Using the "Absolute Enable Right Click & Copy" browser extension in "absolute" mode also succeeds at re-enabling the ctrl-v paste shortcut.

Browser Version: Firefox 111.0.1 (64-bit) on Windows

### Which application of Transmission?

Web client

### Which version of Transmission?

Transmission 4.0.2 2a57b17031

**Comment by ckerr** [comment] 2023-03-28 22:08
Duplicate of https://github.com/transmission/transmission/issues/5298

**Closed by ckerr** 2023-03-28 22:08 UTC
