### ISSUE TITLE
Feature Request for Proxy Support

### ISSUE THREAD

**Issue by joaosarmentoptc** [transmission/transmission#5502] opened 2023-05-07 21:54 UTC
### What is the issue?

As the title indicates - it's very shameful that transmission doesn't support proxy connections.

I'm forced to use another client, that does it, whenever I'm connected to a network that operates over a proxy.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.3

**Comment by ckerr** [comment] 2023-05-08 00:59
Duplicate of #5502

**Closed by ckerr** 2023-05-08 00:59 UTC
