### ISSUE TITLE
DEF CON 32 torrent fails to be added with "unrecognized info" error

### ISSUE THREAD

**Issue by LackThereof** [transmission/transmission#7162] opened 2024-10-10 03:42 UTC
### What is the issue?

When attempting to add [DEF CON 32 v2.torrent](https://media.defcon.org/DEF%20CON%20Torrents/DEF%20CON%2032%20v2.torrent) via either web interface or Transmission Remote GUI v5.18.0, I recieve an error message similar to the following
> Error adding "DEF CON 32 v2.torrent": unrecognized info

I assume the torrent is correctly created because I generally trust the defcon media team to know what they're doing.  Error message is nonspecific, though, so I'm not confident.

Transmission daemon 4.0.6 (38c164933e) running on Windows 10 Home v22H2 (19045.5011)

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.6

**Comment by nevack** [comment] 2024-10-10 05:34
I do think this is because `v2` indicates torrent v2 format.

Transmission does not support v2-only torrents, only v1 and v2 hybrid ones.
https://github.com/transmission/transmission/issues/5560

I think you can use v1 counterpart and go with it.

**Comment by tearfur** [comment] 2024-10-15 01:58
Duplicate of #458.

**Closed by tearfur** 2024-10-15 01:58 UTC
