### ISSUE TITLE
Transmission 2.94 - other folder than default

### ISSUE THREAD

**Issue by Jarda-H** [transmission/transmission#1321] opened 2020-06-16 17:50 UTC
Hi, have instalated Transmission  2.94-16 to my NAS (DS218j - DSM 6.2.3-25426)
I want to use other folder than default folder.
Eg. I want to seed **only one** torrent form volume2/test, but my default folder is volume2/Transmission.
If I try to verify that torrent it starts verifying, but after verify it drops again to 0% and stoppend state.
![image](https://user-images.githubusercontent.com/62809719/84809375-4743ab00-b00a-11ea-9537-e00f08110720.png)
![image](https://user-images.githubusercontent.com/62809719/84809443-5b87a800-b00a-11ea-9a7c-b61dcbe428ed.png)
![image](https://user-images.githubusercontent.com/62809719/84809586-7e19c100-b00a-11ea-8cd9-24e910c5da00.png)

**Comment by ckerr** [comment] 2023-03-13 21:38
Closing as duplicate of https://github.com/transmission/transmission/issues/4987

**Closed by ckerr** 2023-03-13 21:38 UTC
