### ISSUE TITLE
MacOS: Crash after opening webui

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#6182] opened 2023-10-30 09:22 UTC
### What is the issue?

Crash after trying to open the webui.

[crash.txt](https://github.com/transmission/transmission/files/13203264/crash.txt)

### Which application of Transmission?

macOS app

### Which version of Transmission?

e27b05b and b7c5aca (maybe further back?)

**Comment by tearfur** [comment] 2023-10-30 13:06
Duplicate of #6172.

**Closed by tearfur** 2023-10-30 13:06 UTC
