### ISSUE TITLE
'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: components.count > 0'

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3468] opened 2022-07-18 13:44 UTC
Build appears to be fine, but fails to launch, a single bounce in the dock and no crash report.

**Comment by sweetppro** [comment] 2022-07-18 14:09
which version of macOS?

**Comment by GaryElshaw** [comment] 2022-07-18 14:12
12.4

**Comment by GaryElshaw** [comment] 2022-07-19 08:22
Sorry, i should have made clear the build process i'm using is cmake.

**Comment by GaryElshaw** [comment] 2022-07-19 09:39
Just me? That's an odd place to look.

`Couldn't read '/Users/user/.config/user-dirs.dirs'`

**Comment by nevack** [comment] 2022-07-19 10:07
> Same here:

Let's file a separate issue for this.

**Comment by GaryElshaw** [comment] 2022-07-19 10:12
I know. But generic is not the exact. 

Why should this be a separate issue? Let me reiterate. There is a failure to launch with one bounce in the dock and no crash report after building with cmake. Is there anything you would like to add Roman? @rgaufman

**Comment by ckerr** [comment] 2022-07-19 15:10
The "Couldn't read `bandwidth-groups.json` message shows up in the unit tests too.  `tr_loadFile()` logs an error when the file doesn't exist, but it's OK for some files to not exist. Since it's not causing the crash and not contributing to the crash, I agree it should be handled in a separate ticket.

@rgaufman's trace looks actionable and looks like a macOS client issue

> 	2   Foundation                          0x00000001a25b7ea8 -[NSCalendarDate initWithCoder:] + 0
>	3   Transmission                        0x0000000100080c24 -[Torrent insertPathForComponents:withComponentIndex:forParent:fileSize:index:flatList:] + 928
>	4   Transmission                        0x000000010008053c -[Torrent createFileList] + 456

**Comment by GaryElshaw** [comment] 2022-07-21 07:25
Just a note. The jenkins nightly builds launch fine.

**Comment by ckerr** [comment] 2022-07-21 17:14
user-dirs.dirs topic is covered in https://github.com/transmission/transmission/issues/3500

**Comment by GaryElshaw** [comment] 2022-07-23 02:24
Okay, so if i go into the app contents and start the binary, we have, wait for it....

```
/usr/local/Applications/Transmission.app/Contents/MacOS/Transmission ; exit;
gary@Garys-MacBook-Air ~ % /usr/local/Applications/Transmission.app/Contents/MacOS/Transmission ; exit;
2022-07-23 14:16:57.199 Transmission[51026:485979] Unable to load nib file: MainMenu, exiting

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]
```

Somewhere we got our cmake wiring a bit wrong during the auto-layout process?

**Comment by Coeur** [comment] 2022-10-08 22:38
This thread seems to be mixing in new issues with the additional comments.
I'll focus on the original issue.
It's a duplicate of #3434.

**Closed by Coeur** 2022-10-08 22:38 UTC
Labels: help wanted, scope:mac, bug:regression
