### ISSUE TITLE
File list filters should return matching folder names too, not just files

### ISSUE THREAD

**Issue by elmimmo** [transmission/transmission#1817] opened 2021-09-18 18:48 UTC
On macOS at least, when using a filter in the file list in order to search for content inside a torrent, no folder with mtaching name is returned, only files.

Please, make it so that searching inside a torrent also returns matching folder names.

**Comment by Coeur** [comment] 2022-10-09 06:17
It's a nice request. But I'm removing "good first issue" as it's more tricky than we can think at first.
There would be two possible approaches:

A. We generate new FileListNode each time we filter, to represent the folders with less children than without filter.

B. Or we also filter in each delegate method like `outlineView:numberOfChildrenOfItem:` and `outlineView:child:ofItem:`

And there may be the question of selecting/unselecting a folder which is in filtered mode: does that select/unselect only the filtered items, or all the real children of the folder?

**Comment by ckerr** [comment] 2023-01-27 15:31
Duplicate of #858.

**Closed by ckerr** 2023-01-27 15:31 UTC
Labels: scope:mac, feature disparity, pr welcome
