### ISSUE TITLE
Degraded performance on high speed download - single thread ?

### ISSUE THREAD

**Issue by apexlir** [transmission/transmission#1238] opened 2020-05-18 13:34 UTC
I'm trying to find why transmission (2.94) performs poorly on a high speed download compared to qbittorrent and deluge and by looking at the CPU usage per core I noticed that the load is not distributed equally on the 4 cores of my system as you can see here : 

![image](https://user-images.githubusercontent.com/5002968/82218482-3d9c2a00-991c-11ea-958c-d7342cb6b4e5.png)
![image](https://user-images.githubusercontent.com/5002968/82218601-6c1a0500-991c-11ea-9c6b-a74b7e20ce4a.png)

Any idea why ?

**Comment by mjyhj** [comment] 2020-06-08 05:32
Because tranmission only supports single threads.
Single thread CPU100% ，and the Webui‘s response is slow.

**Comment by ckerr** [comment] 2022-01-19 23:03
Closing as a dupe of https://github.com/transmission/transmission/issues/2462. I realize this ticket was filed before 2462, but there are so many overlapping tickets at this point that it makes sense to start with a new "big picture" ticket.

**Closed by ckerr** 2022-01-19 23:03 UTC
