### ISSUE TITLE
Crash in gtk client: "what: argument not found"

### ISSUE THREAD

**Issue by catadropa** [transmission/transmission#2817] opened 2022-03-25 12:28 UTC
Updated today, restarted. Now it crashes shortly after startup just while using the client. It's not immediate but it happens pretty quick, like while scrolling the list of active torrents?

(transmission-gtk:3694): glibmm-ERROR **: 08:25:03.171: 
unhandled exception (type std::exception) in signal handler:
what: argument not found

**Comment by ckerr** [comment] 2022-03-25 16:12
@catadropa the crash is coming from changes made last week to the GTK client's GUI strings that are marked up for internationalization. `what: argument not found` is the new string builder tool's way of saying there's a bug in one of those strings.

Since you said the crash happens when scrolling through active torrents, I inspected the strings in that part of the code and found a couple of errors. They are _probably_ the cause and will be fixed by #2189, but since the error message is so terse it's hard to be certain. Please lmk after 2819 is merged.

Thanks!

**Comment by catadropa** [comment] 2022-03-26 09:58
No crashes now, yay!

But overall up/down speed on the status bar is now 0 / 499.99899291513... and neither shows "kBps"

**Comment by ckerr** [comment] 2022-03-27 18:37
LOL wonderful. Well at least it doesn't crash, right? :dizzy_face: 

I appreciate the update; I'll take a look at that speed formatting

**Closed** 2022-04-01 16:29 UTC
Labels: bug, scope:gtk

**Comment by catadropa** [comment] 2022-04-02 14:00
Looks good again now, thanks. Plus I had just seen a crash (related to text formatting?) that I couldn't reproduce after updating to today's latest.
