### ISSUE TITLE
Magnet links deleted after updating

### ISSUE THREAD

**Issue by AtomicPip** [transmission/transmission#4733] opened 2023-02-08 08:11 UTC
### What is the issue?

I lost several hundred magnet links when I updated to v4.0 on macOS. Has this been reported before? They were either in a paused or stalled state.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0

**Comment by killemov** [comment] 2023-02-08 08:34
Please search before you post. Duplicate of #4295.

**Comment by ckerr** [comment] 2023-02-08 08:49
Closing as duplicate of 4295

**Closed by ckerr** 2023-02-08 08:49 UTC
Labels: duplicate
