### ISSUE TITLE
Bandwidth limit does not work

### ISSUE THREAD

**Issue by RoninFromMoscow** [transmission/transmission#5076] opened 2023-02-27 08:11 UTC
### What is the issue?

Transmission 4.0.1 (e1c6e1be43) MacOs version.

Transmission ignores bandwidth limit settings for both upload and download.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1

**Comment by jbarlov** [comment] 2023-02-27 10:22
For me it's just the download limit – both global and also when specifying on each download. Upload limit works.

**Comment by ckerr** [comment] 2023-02-27 16:36
Hey @RoninFromMoscow, thanks for reporting this.

I think this is a duplicate of #4701 so I'm going to close this one as a dupe.

**Closed by ckerr** 2023-02-27 16:36 UTC
