### ISSUE TITLE
Queue order not preserved on restart.

### ISSUE THREAD

**Issue by lswank** [transmission/transmission#4892] opened 2023-02-14 19:10 UTC
### What is the issue?

On macOS Ventura 13.2.1, Transmission 4.0.0 (280ace12f8) does NOT preserve the order of files to be downloaded in the queue. I order mine manually from smallest to largest. If I close the application and reopen, the order is not preserved.

### Which application of Transmission?

macOS app

### Which version of Transmission?

Transmission 4.0.0 (280ace12f8)

**Comment by ckerr** [comment] 2023-02-14 20:13
Hi @lswank, thanks for reporting this!

This seems to be a duplicate of #155 so I'm going to close this as a dupe.

**Closed by ckerr** 2023-02-14 20:13 UTC

**Comment by albabe** [comment] 2023-04-27 19:27
The "dupe" is from Jan 25, 2017.  if you close it, then will anyone see this at all?

**Comment by nevack** [comment] 2023-04-27 20:34
> The "dupe" is from Jan 25, 2017. if you close it, then will anyone see this at all?

Having 2 issues about the same problem doesn't help to "fix" something magically faster.

**Comment by ckerr** [comment] 2023-04-28 16:43
> The "dupe" is from Jan 25, 2017. if you close it, then will anyone see this at all?

There is a draft in progress but I haven't pushed it up to GitHub yet. There are some differences between the macOS client and the other clients that make this a little more complicated than it ought to be.

Also this is like the third time that @albabe has been pointed to 155 and still makes comments like the above and "I just tried 4.0.3 and it's still broke. Anyone?" and "So... any progress?" in *other* issues. (1) stop pinging on this issue, all it does is piss off the dude who's working to fix the issue and that's not productive. (2) if you do have anything productive to add to the discussion, do it in 155. Next time it'll be a ban.

**Comment by albabe** [comment] 2023-04-28 23:59
@ckerr 
I don't know how to use this Forum... I had never used it before.  I didn't realize I was posting in 2 places.  When I figured-out what was going on with my version of Transmissiion, I did post what I thought might be helpful information to the Programmers on 155... at least I think it was over at 155.
So maybe a little patience on your part would be warranted... but I assume you're much to much of an Authoritarian in you're little tiny world to understand that.
Don't bother banning me, I'm gone, jerk.

**Comment by albabe** [comment] 2023-04-29 22:16
> > The "dupe" is from Jan 25, 2017. if you close it, then will anyone see this at all?
> 
> Having 2 issues about the same problem doesn't help to "fix" something magically faster.

Thats not what I meant.  I was talking about it being from 2017.  Meaning that it's so old do any of the tech Volunteers even see it.

**Comment by albabe** [comment] 2023-07-27 22:56
So... I can't find any information as to whether this issue has been fixed yet?  How do I find out?
