### ISSUE TITLE
Output the completion percentage from the transmission-remote -l command using floor rounding instead of rounding to the nearest whole number.

### ISSUE THREAD

**Issue by hrimfaxi** [transmission/transmission#6550] opened 2024-01-25 08:12 UTC
### What is the issue?

For instance, I have a torrent that is perpetually stuck at 99.95%, which is incorrectly displayed as 100% by transmission-remote -l, leading to erroneous script actions or misjudgments. In transmission-remote -t xxxx -i, the correct completion percentage for this torrent is displayed accurately. I recommended that any completion percentage that isn't 100% in transmission-remote should be uniformly shown as 99%:

Incorrect `transmission-remote -l` output:
```
transmission-remote -t 1605 -l
    ID   Done       Have  ETA           Up    Down  Ratio  Status       Name
  1605   100%   79.35 GB  Unknown      0.0     0.0   37.1  Idle      
```

Its detail output:
```
transmission-remote -t 1605 -i
......

TRANSFER
  State: Idle
  Location: /home/hrimfaxi/finished/
  Percent Done: 99.5%
```

I expected this output:
```
transmission-remote -t 1605 -l
    ID   Done       Have  ETA           Up    Down  Ratio  Status       Name
  1605   99%   79.35 GB  Unknown      0.0     0.0   37.1  Idle      
```

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

transmission-remote 4.0.5 (a6fe2a64aa)

**Comment by hrimfaxi** [comment] 2024-01-25 08:20
I used this script to select all seeding torrents:

```python3
#!/usr/bin/env python3
# coding: utf-8

import subprocess, io, sys, re
from pprint import pprint

def transmission_list(host='localhost'):
    lines = []
    output = subprocess.check_output(['transmission-remote', host, '-l'])
    ret = dict()
    for line in io.StringIO(output.decode(sys.getdefaultencoding())):
        line = line.rstrip()
        rows = [ r.strip() for r in line.split('  ')]
        rows = list(filter(None, rows))
        if rows[0] == 'ID' or rows[0] == 'Sum:':
            continue
        tid = int(rows[0].replace('*', ''))
        ret[tid] = [rows[1], rows[-1]]
    return ret

if __name__ == "__main__":
    torrents = transmission_list()
    for tid in torrents:
        percent, name = torrents[tid]
        if percent == "100%":
            print (tid, torrents[tid])
            # continue my stuff to all seeding torrrents
```

Because of completion percent rounding up, there is no way to make sure these torrents which shows "100%" complete are REALLY completed, unless I start to double check each torrent with `transmission-remote -t xxx -i`, which is nontrivial and stupid.

**Comment by killemov** [comment] 2024-01-25 11:20
Why use round instead of floor for this?!?! Wait a minute ...

List view (wrong?):
https://github.com/transmission/transmission/blob/9f77ef9c7ae32c1dcb7be79fca338f3ea1fb62fe/utils/remote.cc#L1293

Detail view (correct?): 
https://github.com/transmission/transmission/blob/9f77ef9c7ae32c1dcb7be79fca338f3ea1fb62fe/utils/remote.cc#L981

So floor IS being used, but the calculations do appear to be different.

**Comment by tearfur** [comment] 2024-01-25 13:01
Duplicate of #6423, and it is already fixed.

**Closed by tearfur** 2024-01-25 13:01 UTC
