### ISSUE TITLE
Dependency conflict: libayatana-appindicator3 vs. libappindicator3

### ISSUE THREAD

**Issue by fredo-47** [transmission/transmission#3693] opened 2022-08-22 15:52 UTC
I am on Linux Mint 21 Cinnamon, and usually only build transmission-daemon from nightlies for my NAS.
Today I tried to build also the transmission-gtk, from latest revision (258faf36233983c39c423e7ab7f4225009cf1b3e)

During make process, I found out that there was a conflict due to missing "libappindicator/app-indicator.h" (coming from dependency libappindicator3).
My existing system already has the transmission-gtk version 3.00, which depends on "libayatana-appindicator3".
But the build process apparently does not accept this "libayatana-appindicator3", but insists on "libappindicator3".

Now when I command to install libappindicator3, I am told that then libayatana-appindicator3 as well existing transmission-gtk(3.00) would have to be removed first, because libappindicator3 and libayatana-appindicator3 are mutually exclusive.

Is this intended behaviour?
As I understand, original libappindicator3 is not maintained anymore and libayatana-appindicator3 is kind of successor.

Can the current code be modified so that libayatana-appindicator3 would be alternatively accepted?
A quick search indicates that this may be related to [issue #594](https://github.com/transmission/transmission/issues/594).

**Comment by LaserEyess** [comment] 2022-08-22 23:11
>  As I understand, original libappindicator3 is not maintained anymore and libayatana-appindicator3 is kind of successor.

The problem with this is that it's not true. libayatana-appindicator3 is not a successor and only Debian based distros support it. It is not API/ABI compatible so developers have to support both of them. It's a bit of a mess.

A gtk client I work on does that, see https://github.com/transmission-remote-gtk/transmission-remote-gtk/pull/184. A *real* solution is being [proposed upstream](https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/84), but no ETA or even formal commitment from the ecosystem so who knows if it will actually happen.

**Comment by fredo-47** [comment] 2022-08-22 23:26
Thanks for the answer. Sorry, I was not aware of the details.

So, what I am wondering is: 
How is it that transmission-gtk v3.00 (from Linux Mint repository) only accepts "libayatana-appindicator" but not "libappindicator3",
and building transmission-gtk from nightly only accepts vice-versa, i.e. accepts only "libappindicator3" but not "libayatana-appindicator"?

Something seems to be wrong here, doesn't it?

**Comment by LaserEyess** [comment] 2022-08-22 23:54
Likely because debian (and therefore ubuntu and therefore mint) patches transmission to use libayatana.

**Comment by ckerr** [comment] 2022-08-23 03:10
Duplicate of https://github.com/transmission/transmission/issues/594, but thank you for filing this because I'd forgotten about the patch in that issue. :smile_cat:

**Closed by ckerr** 2022-08-23 03:10 UTC
