### ISSUE TITLE
App freezes when moving from location of incomplete files to default location

### ISSUE THREAD

**Issue by gingerbeardman** [transmission/transmission#6961] opened 2024-06-29 21:19 UTC
### What is the issue?

1. default location: external USB
2. keep incomplete files in: folder on internal SSD

This setup means torrent contents are downloaded to SSD, then upon completion moved to external USB.

During the move to external USB
- the app is essentially frozen
- no data is transferred for the other torrents
- this can take multiple minutes

It would be good if the move could be done in a non-blocking way.

### Which application of Transmission?

- macOS app

### Which version of Transmission?

- 4.0.6 (38c164933e)

**Comment by killemov** [comment] 2024-06-29 22:07
Non-blocking IO is in the works. In the meantime you could script copying the data to its target and then relocate the data without moving in Transmission.

**Comment by tearfur** [comment] 2024-06-30 02:20
Duplicate of #2462.

**Closed by tearfur** 2024-06-30 02:20 UTC

**Comment by gingerbeardman** [comment] 2024-06-30 11:38
> Non-blocking IO is in the works. In the meantime you could script copying the data to its target and then relocate the data without moving in Transmission.

Scripting is a good idea to avoid the issue. I'll have to look into it. Any specific examples are appreciated.
