### ISSUE TITLE
Newly added torrents that are paused show up as Stalled

### ISSUE THREAD

**Issue by robd003** [transmission/transmission#4781] opened 2023-02-09 20:12 UTC
### What is the issue?

This new version seems to add torrents that aren't yet started as "Stalled". They aren't stalled, they're paused, and these torrents show up when you press "Paused" from the filter buttons at the top. Equally, when a torrent has finished seeding it's now "Stalled". Stalled is not the right word to use.

Copied this report from: https://forums.macrumors.com/threads/bittorrent-client-transmission-gains-apple-silicon-support-in-fourth-major-release.2380179/post-31952470

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0

**Comment by TopperBG** [comment] 2023-02-10 23:41
Same under Linux, added torrents won't start and stay paused until manual start them

**Comment by Xaositek** [comment] 2023-02-11 14:38
I believe this is being tracked here - https://github.com/transmission/transmission/issues/4740

**Comment by ckerr** [comment] 2023-02-11 15:39
Closing as a duplicate of #4740, thanks @Xaositek

**Closed by ckerr** 2023-02-11 15:39 UTC
Labels: bug, scope:mac

**Comment by TopperBG** [comment] 2023-02-12 13:01
> Closing as a duplicate of #4740, thanks @Xaositek

I'm talking about torrent files, not about magnet links. If you decide is the same problem ok.
