### ISSUE TITLE
Can multithreading be supported？

### ISSUE THREAD

**Issue by mjyhj** [transmission/transmission#1305] opened 2020-06-08 05:25 UTC
Some CPUs have low single frequency, which will cause webui to jam when downloading large files

**Comment by alaa13212** [comment] 2020-06-08 15:42
I think this is supported but no enabled. Enabling it require compiling your own version.

Explanation [here](https://github.com/transmission/transmission/wiki/Can-I-sequence-the-files-I-download)

**Comment by antivirtel** [comment] 2020-10-09 09:10
Same happens to me, allocating files should be a separate thread in the background, so the GUI still stays responsive

**Comment by ckerr** [comment] 2022-01-19 23:02
Closing as a dupe of https://github.com/transmission/transmission/issues/2462. I realize this ticket was filed before 2462, but there are so many overlapping tickets at this point that it makes sense to start with a new "big picture" ticket.

**Closed by ckerr** 2022-01-19 23:02 UTC
