### ISSUE TITLE
Warning tr-udp.cc Couldn't send to IPv6 address (Network is unreachable)

### ISSUE THREAD

**Issue by herbanonymous** [transmission/transmission#5883] opened 2023-08-08 19:35 UTC
### What is the issue?

```
Tue Aug  8 12:20:01 2023	Warning	tr-udp.cc:261	Couldn't send to [2001:7d0:87ca:f480:45f3:8e09:4d61:a6d8]:6881: 101 (Network is unreachable)
Tue Aug  8 12:20:00 2023	Warning	tr-udp.cc:261	Couldn't send to [2001:8003:f40b:1d00:789:fe98:b106:8185]:6881: 101 (Network is unreachable)
Tue Aug  8 12:20:00 2023	Warning	tr-udp.cc:261	Couldn't send to [2001:8f8:1335:2401:8174:1876:1b7b:dd5d]:53308: 101 (Network is unreachable)
Tue Aug  8 12:19:59 2023	Warning	tr-udp.cc:261	Couldn't send to [2001:b07:6467:e137:a85f:62d0:df4c:f1dc]:6881: 101 (Network is unreachable)
Tue Aug  8 12:19:59 2023	Warning	tr-udp.cc:261	Couldn't send to [2409:4070:6e11:6cef:7be4:de09:6488:924f]:43881: 101 (Network is unreachable)
Tue Aug  8 12:19:59 2023	Warning	tr-udp.cc:261	Couldn't send to [2408:8207:a827:9ec1::1008]:63219: 101 (Network is unreachable)
Tue Aug  8 12:19:59 2023	Warning	tr-udp.cc:261	Couldn't send to [2001:8f8:1c65:2971:bbae:c05:2934:df16]:11995: 101 (Network is unreachable)
Tue Aug  8 12:19:59 2023	Warning	tr-udp.cc:261	Couldn't send to [2603:6080:ba40:ca88:4e5a:1735:4038:4467]:51188: 101 (Network is unreachable)
Tue Aug  8 12:19:59 2023	Warning	tr-udp.cc:261	Couldn't send to [2605:a200:9201:8261:b15a:408a:31b2:293e]:6881: 101 (Network is unreachable)
Tue Aug  8 12:19:58 2023	Warning	tr-udp.cc:261	Couldn't send to [2001:4451:87d3:2100:10e5:ad17:4c9c:f429]:6882: 101 (Network is unreachable)
Tue Aug  8 12:19:58 2023	Warning	tr-udp.cc:261	Couldn't send to [2001:b07:add:89db:a4c3:5c8e:5a3b:62b9]:43100: 101 (Network is unreachable)
Tue Aug  8 12:19:58 2023	Warning	tr-udp.cc:261	Couldn't send to [2a00:23c8:551b:d601:73df:fb27:43ef:656a]:6881: 101 (Network is unreachable)
Tue Aug  8 12:19:58 2023	Warning	tr-udp.cc:261	Couldn't send to [2800:300:8421:8400:f18c:38fd:859d:b49f]:15267: 101 (Network is unreachable)
Tue Aug  8 12:19:57 2023	Warning	tr-udp.cc:261	Couldn't send to [2405:9800:b960:6ba1:a25a:23b:9563:81b5]:41689: 101 (Network is unreachable)
Tue Aug  8 12:19:57 2023	Warning	tr-udp.cc:261	Couldn't send to [2001:8f8:1335:2401:8174:1876:1b7b:dd5d]:53308: 101 (Network is unreachable)
Tue Aug  8 12:19:56 2023	Warning	tr-udp.cc:261	Couldn't send to [2a01:e34:ec23:32d0:c8b:bbb8:834c:d184]:6881: 101 (Network is unreachable)
Tue Aug  8 12:19:56 2023	Warning	tr-udp.cc:261	Couldn't send to [2001:8f8:1c65:2971:bbae:c05:2934:df16]:11995: 101 (Network is unreachable)
Tue Aug  8 12:19:55 2023	Warning	tr-udp.cc:261	Couldn't send to [2605:a200:9201:8261:b15a:408a:31b2:293e]:6881: 101 (Network is unreachable)
Tue Aug  8 12:19:55 2023	Warning	tr-udp.cc:261	Couldn't send to [2001:b07:add:89db:a4c3:5c8e:5a3b:62b9]:43100: 101 (Network is unreachable)
Tue Aug  8 12:19:54 2023	Warning	tr-udp.cc:261	Couldn't send to [2001:7d0:87ca:f480:45f3:8e09:4d61:a6d8]:6881: 101 (Network is unreachable)
Tue Aug  8 12:19:54 2023	Warning	tr-udp.cc:261	Couldn't send to [2800:300:8421:8400:f18c:38fd:859d:b49f]:15267: 101 (Network is unreachable)
Tue Aug  8 12:19:53 2023	Warning	tr-udp.cc:261	Couldn't send to [2408:8207:a827:9ec1::1008]:63219: 101 (Network is unreachable)
Tue Aug  8 12:19:52 2023	Warning	tr-udp.cc:261	Couldn't send to [2001:4451:87d3:2100:10e5:ad17:4c9c:f429]:6882: 101 (Network is unreachable)
Tue Aug  8 12:19:51 2023	Warning	tr-udp.cc:261	Couldn't send to [2001:7d0:87ca:f480:45f3:8e09:4d61:a6d8]:6881: 101 (Network is unreachable)
Tue Aug  8 12:19:51 2023	Warning	tr-udp.cc:261	Couldn't send to [2405:9800:b960:6ba1:a25a:23b:9563:81b5]:41689: 101 (Network is unreachable)
Tue Aug  8 12:19:50 2023	Warning	tr-udp.cc:261	Couldn't send to [2a01:e34:ec23:32d0:c8b:bbb8:834c:d184]:6881: 101 (Network is unreachable)
Tue Aug  8 12:19:49 2023	Warning	tr-udp.cc:261	Couldn't send to [2408:8207:a827:9ec1::1008]:63219: 101 (Network is unreachable)
Tue Aug  8 12:19:48 2023	Warning	tr-udp.cc:261	Couldn't send to [2001:4451:87d3:2100:10e5:ad17:4c9c:f429]:6882: 101 (Network is unreachable)
Tue Aug  8 12:19:47 2023	Warning	tr-udp.cc:261	Couldn't send to [2405:9800:b960:6ba1:a25a:23b:9563:81b5]:41689: 101 (Network is unreachable)
Tue Aug  8 12:19:46 2023	Warning	bt.xxx-tracker.com:2710	Couldn't look up 'bt.xxx-tracker.com:2710': Name or service not known (-2)
Tue Aug  8 12:19:46 2023	Warning	tr-udp.cc:261	Couldn't send to [2a01:e34:ec23:32d0:c8b:bbb8:834c:d184]:6881: 101 (Network is unreachable)
Tue Aug  8 12:19:46 2023	Information	session.cc:1406	Loaded 3 torrents
Tue Aug  8 12:19:46 2023	Information	rpc-server.cc:923	Serving RPC and Web requests from '/usr/share/transmission/public_html'
Tue Aug  8 12:19:46 2023	Information	rpc-server.cc:763	Added '::1' to host whitelist
Tue Aug  8 12:19:46 2023	Information	rpc-server.cc:763	Added '127.0.0.1' to host whitelist
Tue Aug  8 12:19:46 2023	Information	tr-udp.cc:202	Bound UDP IPv6 address [::]:51413
Tue Aug  8 12:19:46 2023	Information	tr-udp.cc:168	Bound UDP IPv4 address [0.0.0.0]:51413
Tue Aug  8 12:19:46 2023	Information	port-forwarding.cc:215	State changed from 'Not forwarded' to 'Starting'
Tue Aug  8 12:19:46 2023	Information	session.cc:404	Listening to incoming peer connections on [::]:51413
Tue Aug  8 12:19:46 2023	Information	session.cc:404	Listening to incoming peer connections on [0.0.0.0]:51413
Tue Aug  8 12:19:46 2023	Information	session.cc:646	Transmission version 4.0.3 (6b0e49bbb2) starting
```

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.3 (6b0e49bbb2)

**Comment by tearfur** [comment] 2023-08-09 01:08
Duplicate of #86.

**Closed by tearfur** 2023-08-09 01:08 UTC
