### ISSUE TITLE
Sort by Queue Order not working properly

### ISSUE THREAD

**Issue by b0ydcr0wder** [transmission/transmission#6270] opened 2023-11-19 14:39 UTC
### What is the issue?

Sorting by Queue Order is not working properly. After very launch, the transfers are always in random order.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.4

**Comment by killemov** [comment] 2023-11-19 20:58
Please search before you post.
Duplicate of #327, #6163.
Related to #5323, #5551, #5970.

**Closed** 2023-11-20 06:47 UTC
Labels: duplicate
