### ISSUE TITLE
Possibility to choose language other than system default?

### ISSUE THREAD

**Issue by gustavosarmento** [transmission/transmission#1295] opened 2020-06-04 18:15 UTC
Transmisssion 3.00 on macOS 10.15.5

Apparently there's no pt-br translation as of yet, so it fallbacks to pt-pt, which is awful for us in Brazil. I'd rather be able to choose it to be in English.

**Comment by ZorroGuevara** [comment] 2020-06-08 17:17
Possibly duplicate of  #1152

**Closed** 2020-07-28 00:02 UTC
