### ISSUE TITLE
How to stop Transmission creating complete and incomplete folders

### ISSUE THREAD

**Issue by k-matti** [transmission/transmission#4954] opened 2023-02-19 14:41 UTC
### What is the issue?

Transmission still creating two folders (complete and incomplete) in download folder. I don't need these folders. How to fix that?
My settings:
` "download-dir": "/downloads/",
    "incomplete-dir": "/downloads/",
    "incomplete-dir-enabled": false,
`

I am using transmission docker image from linuxserver

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.0

**Comment by ckerr** [comment] 2023-02-19 15:25
Hi @k-matti, thanks for reporting this!

I think this is a duplicate of https://github.com/transmission/transmission/issues/399, so I'm going to close this ticket as a dupe.

**Closed by ckerr** 2023-02-19 15:25 UTC
