### ISSUE TITLE
main window shows 99% progress when seeding

### ISSUE THREAD

**Issue by kuroya2mouse** [transmission/transmission#4868] opened 2023-02-13 18:37 UTC
### What is the issue?

Torrent is full downloaded, but show only 99% percents
![2](https://user-images.githubusercontent.com/108447847/218545319-20193011-9f16-490f-a8a6-739a9d375fea.png)
![Без имени](https://user-images.githubusercontent.com/108447847/218545326-edce03be-5b25-49f0-b580-fa6187115c4a.png)

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

git feb-13-2023

**Comment by ckerr** [comment] 2023-02-13 23:34
This looks like a duplicate of #4583, but totally understandable that you didn't find that issue since it had a kind-of misleading title.

Thanks for the report @kuroya2mouse!

**Closed by ckerr** 2023-02-13 23:34 UTC
Labels: bug, scope:qt, scope:core, needs confirmation
