### ISSUE TITLE
When I reboot Transmission it starts download faster

### ISSUE THREAD

**Issue by effolkronium** [transmission/transmission#5778] opened 2023-07-13 19:17 UTC
### What is the issue?

After a hour of downloading the speed drops to a 100kb\s, but when I manually reboot the app, it gets much more number of seeders and downloads faster with 1mb\s speed.

Why it can't search for new\other seeders while downloading ?

### Which application of Transmission?

MacOS M1

### Which version of Transmission?

4.0.3

**Comment by tearfur** [comment] 2023-07-14 01:42
We've been commiting a series of changes that addresses this issue in the main development branch, and there are more to come.

Hopefully this will improve in `4.1.0`.

**Comment by Pentaphon** [comment] 2023-07-14 14:32
> Hopefully this will improve in `4.1.0`.

I have a feeling 4.1.0 is still a long ways off. Will these changes be backported to a 4.0.4 release in the meantime?

**Comment by tearfur** [comment] 2023-07-14 14:37
> Will these changes be backported to a 4.0.4 release in the meantime?

Nope. Some of them aren't backwards-compatible.

Closing this as a duplicate of #5261.

**Closed by tearfur** 2023-07-14 14:37 UTC
