### ISSUE TITLE
SIGSEGV in tr_swarm::on_got_port

### ISSUE THREAD

**Issue by wiz78** [transmission/transmission#5988] opened 2023-09-09 09:45 UTC
### What is the issue?

since 4.0.4 I've been seeing some crashes like this:

```
Thread 2 "transmission-da" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff651e640 (LWP 1153608)]
0x00005555556aa246 in tr_swarm::on_got_port (this=this@entry=0x7ffff01ffd70, msgs=msgs@entry=0x7ffff0d45750, event=..., was_connectable=was_connectable@entry=false) at Transmission/libtransmissi
on/peer-mgr.cc:725
725             nh.key().port_ = event.port;
(gdb) p nh
Python Exception <class 'gdb.error'>: There is no member or method named _M_engaged.
Python Exception <class 'gdb.error'>: There is no member or method named _M_engaged.
$7 = {<std::_Node_handle_common<std::pair<tr_socket_address const, tr_peer_info>, std::allocator<std::__detail::_Hash_node<std::pair<tr_socket_address const, tr_peer_info>, false> > >> = {_M_ptr = 0x0,
    _M_alloc = {_M_empty = {<No data fields>},
      _M_alloc = {<__gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<tr_socket_address const, tr_peer_info>, false> >> = {<No data fields>}, <No data fields>}}}, _M_pkey = 0x0, _M_pmapped = 0x0}
```

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

commit 1d1ad6568dc96f88c37519caeed9e305ee001f08

**Comment by tearfur** [comment] 2023-09-09 14:39
Duplicate of #5940.

**Closed by tearfur** 2023-09-09 14:39 UTC
