### ISSUE TITLE
Transmission 4.0.2 Never Unchokes When Seeding 

### ISSUE THREAD

**Issue by roryyamm** [transmission/transmission#5447] opened 2023-04-24 14:10 UTC
### What is the issue?

I make torrents for others to use. Transmission 4.0.2 on Debian can download torrents perfectly fine, but when it comes time to actually seed said torrents, the peers always have the K or ? flag by them in the peer list. Peers never get unchoked, or otherwise never get data sent to them. 
Seeding is occasionally useful in a torrent program, so I am surprised that this issue hasn't been noticed or addressed before.

To replicate, create a torrent with Transmission to ensure there are no other peers, and attempt to seed it to another device somewhere else. For instance, I used the following torrent, generated from a video file on Wikipedia (probably not active as I have likely rolled back Transmission):

magnet:?xt=urn:btih:e7bf5ed4ca3239ea7a800df8876dad1d9f320c51&dn=CHU_2022-10-14_7.85MHz.ogg&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce

When using another torrent client on my phone to try and download it, the phone cannot even get the metadata associated with the magnet. Meanwhile, Transmission 4 only shows 'T?' as status flags, indicating the other side is apparently uninterested in getting the file. I know for a fact that's a bald-faced lie. 

![Screenshot From_2023-04-24 100432](https://user-images.githubusercontent.com/24758288/234021518-13b176e2-7c09-4c7c-a378-36cae499dc98.png)

This functionality works perfectly well in Transmission 3.00, but breaks in all versions of 4 on Debian up to the current 4.0.2.

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.2 (2a57b17031)

**Comment by Pentaphon** [comment] 2023-04-25 18:52
@ckerr this guy may be on to something and could prove useful in addressing performance issues since 3.00

If this gets fixed, the solution should find its way to a 4.0.4 release.

**Comment by ckerr** [comment] 2023-04-27 02:35
OK I've tested this by running Transmission as a seed on one machine and qBittorrent as a downloader on the same local network, and I do see similar behavior to what you're reporting, but...

... the problem isn't one of Transmission unchoking, at least in my testing. qBittorrent tries to fetch metadata from Transmission, but there is a off-by-one bug in `4.0.[0..3]` that prevents it from getting the final block of metadata. #5460 fixes that issue (and yes @Pentaphon I've already cherry-picked it in the `4.0.x` branch :smile_cat: and after that qBittorrent is able to get all the metadata and start downloading the torrent.

I think this bug is fixed now in `main` and in `4.0.x`. If the problem persists for you in the nightly builds please lmk.

**Closed by ckerr** 2023-04-27 02:35 UTC
