### ISSUE TITLE
macOS Sierra "Your system has run out of application memory" error

### ISSUE THREAD

**Issue by rnhurt** [transmission/transmission#197] opened 2017-02-26 01:31 UTC
When running Transmission 2.92 (14714) on macOS Sierra beta (10.12.4 Beta (16E163f)) I am getting a "Your system has run out of application memory" error from the OS.  The only way to resolve the issue was to reboot.  I've rebooted twice and performed a parameter ram flush.

At first I thought it might really be a memory issue, however now I think it might be related to the size of the torrent I'm downloading.  The torrent is 64GB and I only have 34GB of storage space available.

Whatever the cause, my system is stable until I open Transmission and start downloading.  After 60-90 seconds I get the warning dialog box from macOS and am forced to reboot.

**Comment by timmerk** [comment] 2017-03-03 16:59
How much RAM do you have on your Mac? I had this problem with all of my RAM heavy apps. Turns out my /var/vm folder was missing, and OS X couldn't create a swap file for virtual memory.

**Comment by rnhurt** [comment] 2017-03-04 01:13
@timmerk my MBP is maxed out with 16GB of RAM and the /var/vm directory is present.  Again, my gut feeling is that it was trying to allocate storage somewhere for the extra large files.  When I cleaned up my local storage and removed some of the larger seeds everything went back to working as it should.

**Comment by ckerr** [comment] 2022-02-10 16:37
I'm closing this issue due to its age and that the maintainers haven't been able to reproduce it.

If this is still happening in the [nightly builds](https://transmissionbt.com/download), please open a new bug with updated information. Thank you!

**Closed by ckerr** 2022-02-10 16:37 UTC
