### ISSUE TITLE
Limit Download checkbox no longer respected

### ISSUE THREAD

**Issue by jlholt** [transmission/transmission#5044] opened 2023-02-25 04:18 UTC
### What is the issue?

To limit the download rate of a torrent, in version 2.94, I could click the torrent's icon which would raise a dialog that showed two Transfer Bandwidth checkboxes.

I could check them to limit the download rate and it would respect the number in the correlated text widget.

That value is now ignored.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1

**Comment by jlholt** [comment] 2023-02-25 04:20
It's entirely possible that some other setting was lost in the upgrade. For example, there is a turtle icon at the bottom of the main dialog. This toolbar containing the turtle icon also includes a count of the transfers.

That turtle was selected before the upgrade from 2.94 to 4.0.1. After the upgrade it wasn't selected which seems to be the reason why the bandwidth limitation was being ignored.

**Comment by jlholt** [comment] 2023-02-25 04:22
I take that back. There's more funny business going on. If I click the torrent's left icon to raise the dialog showing the limiting checkboxes, then the respect for the limitation is gone. As soon as I close that dialog, the respect returns.

**Comment by jlholt** [comment] 2023-02-25 04:25
Are preferences stored in /Applications/Transmission.app? That folder was replaced when the upgrade from 2.94 to 4.0.1 failed, forcing me to download the app manually and drag it to /Applications, which causes it to replace the prior one.

**Comment by ckerr** [comment] 2023-02-25 04:33
Hi @jholt, thanks for reporting this!

I think this is a duplicate of https://github.com/transmission/transmission/issues/4701 so I'm closing this one as a duplicate.

> Are preferences stored in /Applications/Transmission.app? That folder was replaced when the upgrade from 2.94 to 4.0.1 failed, forcing me to download the app manually and drag it to /Applications, which causes it to replace the prior one.

@Coeur DYK the answer to this for the macOS client?

**Closed by ckerr** 2023-02-25 04:33 UTC
Labels: duplicate

**Comment by GaryElshaw** [comment] 2023-02-25 04:46
/Users/your_name/Library/Application Support/Transmission
