### ISSUE TITLE
Transmission downloads parts of the files that i have not selected

### ISSUE THREAD

**Issue by slrslr** [transmission/transmission#1105] opened 2020-01-13 21:52 UTC
I do not know if this is the issue of the Transmission 2.94, but on Windows 10 when i add this torrent: magnet:?xt=urn:btih:38b46a67491637e7a650aa909ba219c89f866803
in the dialog of torrent adding i deselect all payload folders and select only folder "2003 Leben". When download complete i find that it also downloaded two different folders and partialy a few of its files. When i delete these trunk incomplete files so it do not mess there, the torrent is incomplete on recheck. Can you prevent this to happen please? So the torrent client does not lookup for the files that are not selected for download and do not download these while keeping torrent resumed in seeding state?

**Comment by sio** [comment] 2020-01-22 12:05
That is an expected behavior. It happens because Bittorrent transfers happen in chunks and not in files - almost always chunk boundaries do not align with file boundaries and some part of unwanted files has to be fetched. Some clients hide away those partial files from users, some do not - but all of them need to download and store those little extras somehow.

**Comment by porg** [comment] 2021-03-02 22:46
From a technical standpoint correct, but from a usability perspective, having files which you did not select is undesirable, so hiding them away is better I'd say.

This request already came in one form or the other of this project's lifetime, here i.e. in 2007:
https://trac.transmissionbt.com/ticket/532

There even is a patch which achieves what you wanted.

**Comment by ckerr** [comment] 2022-02-22 18:43
Duplicate of #290

**Closed by ckerr** 2022-02-22 18:43 UTC
