### ISSUE TITLE
Downlimits ignored

### ISSUE THREAD

**Issue by ManDay** [transmission/transmission#7015] opened 2024-07-27 08:00 UTC
### What is the issue?

Added a torrent, set no torrent specific downlimit, set a global downlimit `transmission-remote -d 1024`. 10 minutes later the torrent is still downloading at 3000+. Same for torrent specific downlimit.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.5

**Comment by killemov** [comment] 2024-07-27 10:15
Duplicate of #7005 ?

**Comment by ManDay** [comment] 2024-07-27 10:50
Perhaps? I'm a bit confused by

> No matter which values other than 0 assigned to the above 2 limits, the actual download speed for one torrent seems to be around 8.19KB/s for each peer connected. Usually there will be 4 concurrent peers connected for downloading simultaneously. So the total download speed for one torrent would be around 32.77KB/s.

though. Is the reporter saying that their torrents download at 32.77 KB/s max when `-d` is set? Because this is evidently not the case for me, I just seem to get unlimited downspeed.

**Comment by killemov** [comment] 2024-07-28 12:18
Apparently there are several related issues with set speed limits that are not adhered to.

**Comment by tearfur** [comment] 2024-08-06 08:15
More probably a duplicate of #6361.

#7005 does not look like a problem of libtransmission, I will have an update soon once I do more testing.

**Closed** 2024-08-06 08:16 UTC
Labels: duplicate
