### ISSUE TITLE
The Transmission icon looks exactly like the Faststone Image Viewer icon

### ISSUE THREAD

**Issue by Ridbowt** [transmission/transmission#4915] opened 2023-02-16 11:55 UTC
The Transmission icon looks exactly like the Faststone Image Viewer icon. Transmission 4.0.0 (280ace12f8).
![2023-02-16_14-54-08](https://user-images.githubusercontent.com/37126465/219358344-6aa1a6ea-3f07-423f-9f27-6623eaa6f0f8.png)

**Comment by ckerr** [comment] 2023-02-16 15:43
Hey @Ridbowt I think this is a duplicate of https://github.com/transmission/transmission/issues/4572, so I'm going to close this as a duplicate.

That issue has been stuck for a little while I _think_ because the maintainers weren't sure how to reproduce the issue, so if you have any clues on how it might have happened, please do drop a line in that ticket. Thanks!

**Closed by ckerr** 2023-02-16 15:43 UTC
