### ISSUE TITLE
Release Apple Silicon (M1) version

### ISSUE THREAD

**Issue by fulldecent** [transmission/transmission#2607] opened 2022-02-11 15:49 UTC
I know people are working on this. But just wanted to track this as an issue. Anybody can subscribe here if you are just waiting for the M1 gold master release.

**Comment by ckerr** [comment] 2022-02-11 15:54
Duplicate of https://github.com/transmission/transmission/discussions/1925

**Closed by ckerr** 2022-02-11 15:54 UTC
Labels: discussion
