### ISSUE TITLE
`nightly` `transmission-gtk` added torrents are paused even when the preferences say they should start

### ISSUE THREAD

**Issue by belovachap** [transmission/transmission#4196] opened 2022-11-16 12:17 UTC
### What is the issue?

I noticed that when I add new torrents from my watched directory they are paused by default even though I have them set to start in preferences. I have to select the paused torrents and tell them to start as a work around. It used to work so not sure what's changed recently :\

![image](https://user-images.githubusercontent.com/396781/202177035-555c0e2a-7619-4f23-a1ff-e5a03f86faee.png)

![image](https://user-images.githubusercontent.com/396781/202177123-1549018e-d5b1-410e-98f6-39b7db854bb6.png)

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

812588100d

**Comment by ckerr** [comment] 2022-11-16 19:33
Closing as a duplicate of https://github.com/transmission/transmission/issues/3753

**Comment by ckerr** [comment] 2022-11-16 19:34
BTW @belovachap your bug reports recently have been very helpful. Thank you!

**Closed by ckerr** 2022-11-16 19:33 UTC
