### ISSUE TITLE
Never starts the download from magnet - stuck on retrieving metadata

### ISSUE THREAD

**Issue by CrimsonVex** [transmission/transmission#4765] opened 2023-02-09 04:29 UTC
### What is the issue?

Transmission 4.0.0 (280ace12f8)
Windows 10 Pro x64 22H2 19045.2364
Yes, this seems to be the same issue as in #1618 

Adding via a magnet link results in an infinite time spent retrieving metadata (stays at 0%).
This occurs for any magnet I try.
I've confirmed that the torrent has found peers via the tracker tab.

Port being used is open according to transmission. No CGNAT, using NAT passthrough. Manually port opened. Confirmed via online tools. Windows firewall is off. Defender off. Nil other third party AV.

Problem is solved if I use a .torrent file instead of a magnet. Nil issues using magnets with any alternative torrent application.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.0 (280ace12f8)

**Comment by SNBogdanov** [comment] 2023-02-14 06:46
This is also true for daemon on windows

**Comment by BenCanada** [comment] 2023-03-11 04:44
The same is happening on my Synology NAS.

**Comment by garoto** [comment] 2023-03-11 21:17
It took some ~6mins to bootstrap the DHT network on a fresh v4.0.1-release Transmission Windows environment, but this magnet `magnet:?xt=urn:btih:ffe1e36385ee3e4cfc779fa5b6141052609c8a36&dn=FreeBSD-13.1-RELEASE-amd64-bootonly.iso` eventually downloaded successfully for me.

**Comment by damcav35** [comment] 2023-06-02 07:25
I've add the same issue as #1618 since transmission 2.94, on linux OS.
For some of our applications, we are generating / deploying  our own torrents in a private network, so i'm sure there are seeders in the trackers. (verified it multiple times)
Never found anything in the logs at debug mode, nor in the network packets : the handshake works fine with others peers, but sometimes a client is never able to get the metadata. 
And at some point, maybe 30-40 mn later, it may suddenly unlock.
I was never able to reproduce it at will, and in the end we got rid of using magnet urls

**Comment by tearfur** [comment] 2023-07-14 17:59
Should be fixed by #5460.

**Closed by tearfur** 2023-07-14 17:59 UTC

**Comment by brccabral** [comment] 2025-02-24 19:15
I am having this issue in 4.0.6, trying to download Arch Linux iso `magnet:?xt=urn:btih:c5919866bb860b51dcc8e242add5fed5d8045b15&dn=archlinux-2025.02.01-x86_64.iso`

**Comment by meszaros-lajos-gyorgy** [comment] 2025-07-22 16:14
I have the same issue on Linux Mint 22.1 using Transmission 4.0.5 (64805552b4)

**Comment by tearfur** [comment] 2025-07-23 06:14
Can you provide more information? When you do, please open a new issue for it. It's impossible for us to troubleshoot with just "it doesn't work".

Ideally a full-on analysis like https://github.com/transmission/transmission/issues/5943#issuecomment-1848909539 will be very useful, but that's a tall ask. If that's not possible, providing some logs like https://github.com/transmission/transmission/issues/5943#issuecomment-1752144537 did could be helpful as well.
