### ISSUE TITLE
No tray icon option in preferences

### ISSUE THREAD

**Issue by dlblv** [transmission/transmission#5211] opened 2023-03-13 01:50 UTC
### What is the issue?

There's no option to enable tray icon in "Desktop" tab of preferences window (see attachment).
Icon does not appear.
Transmission exits on window closed, not minimized to tray as it was before.

![image](https://user-images.githubusercontent.com/20345406/224590076-bdb9ab5e-5f22-4aa7-aceb-af157f2598a7.png)

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.1 (e1c6e1be43)

**Comment by ckerr** [comment] 2023-03-13 04:32
Hey @dlblv, thanks for reporting this.

I think this is a duplicate of https://github.com/transmission/transmission/issues/4749 so I'm going to close this one as a dupe.

**Closed by ckerr** 2023-03-13 04:32 UTC
