### ISSUE TITLE
Writing on disk at main thread.

### ISSUE THREAD

**Issue by ASPIRINI1** [transmission/transmission#6027] opened 2023-09-21 19:20 UTC
### What is the issue?

App not responding for a long time when I try to start load huge file(20gb and more). My external drive seems like do some work, but app UI not clickable and not have any activity indicator. It's look like that app do some work on a main thread and block UI.

### Which application of Transmission?

macOS app

### Which version of Transmission?

All

**Comment by xavery** [comment] 2023-09-21 22:24
Duplicate of https://github.com/transmission/transmission/issues/2462.

**Closed** 2023-09-22 01:03 UTC
