### ISSUE TITLE
(GNOME Shell) While transmission-gtk is running, no application icon on the dash nor on the top panel, a generic icon is used instead

### ISSUE THREAD

**Issue by Amr-Ibra** [transmission/transmission#5812] opened 2023-07-21 11:25 UTC
### What is the issue?

- Running on Debian testing up-to-date

On GNOME Shell, while transmission-gtk is running, it does not show its icon on the dash nor on the top panel. It shows a generic icon instead. Furthermore, it is displaying its application-id rather than the application name, and the right-click actions do not show.

Note that the application-id on the dash and top panel is coming from [this line of code](https://github.com/transmission/transmission/blob/d7473f22ed1f1cc637a23d17f12f3c22d5c4b8a4/gtk/Application.cc#L705).

| Dash | Top Panel |
| ------------- | ------------- |
| ![transmission-gtk-dash-gnome-shell](https://github.com/transmission/transmission/assets/45657128/36c319c1-11ae-44c5-9219-06ffb4605893) | ![transmission-gtk-top-panel-gnome-shell](https://github.com/transmission/transmission/assets/45657128/f151d2b0-af15-47f8-810b-5b3a2bf83e11) |

I found a fix for this, or a workaround, by adding this line in [transmission-gtk.desktop.in](https://github.com/transmission/transmission/blob/main/gtk/transmission-gtk.desktop.in) (after `Actions=Pause;Minimize;`):

`StartupWMClass=com.transmissionbt.transmission_66308_7078421`

(That can be easily tested on an already installed transmission-gtk by copying the file `/usr/share/applications/transmission-gtk.desktop`, pasting and modifying it in `~/.local/share/applications/`.)

I think `StartupWMClass` enables gnome-shell to map the application to its desktop file and icon. After this fix, the application icon, name and right-click actions are displayed correctly.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.2 (2a57b17031)

**Comment by Pentaphon** [comment] 2023-07-23 07:50
@GaryElshaw may find this of interest

**Comment by mikedld** [comment] 2023-07-23 13:12
Duplicate of #5067.

**Closed** 2023-07-26 03:01 UTC
