### ISSUE TITLE
Transmission allocates full sized .part files to disk for a single stray piece

### ISSUE THREAD

**Issue by mraonea** [transmission/transmission#1953] opened 2021-10-14 13:27 UTC
Download a torrent containing two or more large files. Select only one file to be downloaded.

If a piece in the beginning or end of this file overlaps with a file you have selected not to be downloaded, Transmission still allocates the full size of the file not meant to be downloaded to disk, instead of just the actual piece that contains meaningful data.

This results in unnecessary 99% empty multi GB files on disk, wasting hard drive space.

There is an old Trac report about this and apparently even some old patches submitted to fix this:

https://trac.transmissionbt.com/ticket/514#comment:3

And here is a more recent discussion: https://github.com/transmission/transmission/discussions/1921

Other torrent clients handle this common case gracefully, only allocating the few bytes of space needed for the actual piece.

**Comment by leosnake2208** [comment] 2022-01-01 13:34
noted that once. in my experience Transmission will rather occupy full space on disk through a file system.
other clients stores an overlapsed blocks inside a separate files with an additional extensions and do not rely on the file system.

**Comment by killemov** [comment] 2022-01-13 13:29
And an even older method was to use padding files. The current sparse file allocation method works for all filesystems that allow it. Which is most, if not all.

**Comment by mraonea** [comment] 2022-01-15 03:06
> The current sparse file allocation method works for all filesystems that allow it. 

No it doesn't. This issue is specifically about that. And the referenced old trac issue on Mac OS.

**Comment by ckerr** [comment] 2022-01-17 22:37
I don't think a back-and-forth on this is productive. There may be different behaviors on different OSes, and even in different filesystems on the same OS.

Bottom line is that this _may_ be a valid case _for some users_. I suspect that it's not a very common case, but if someone out there feels strongly about it and wants to write a PR for it, I'd be happy to review it.

**Comment by ckerr** [comment] 2022-02-22 18:38
Duplicate of #290

**Closed by ckerr** 2022-02-22 18:38 UTC
Labels: scope:core, pr welcome
