### ISSUE TITLE
Can't automatically add new trackers to existing task

### ISSUE THREAD

**Issue by Tockman** [transmission/transmission#5305] opened 2023-03-26 17:57 UTC
### What is the issue?

![Снимок экрана 2023-03-26 в 20 39 20](https://user-images.githubusercontent.com/74548419/227793997-56d8820a-a89e-44c7-830c-27a0d9562505.png)
When you start a new torrent file containing a task identical to already existing on a list, but with a different trackers set, you get a message "The distribution [name] already exists. It cannot be added because it's a copy of existing one". Meanwhile, some another torrent clients act otherwise under the same circumstances: they offer to add trackers from the new t-file to the existing task. May Transmission have this option, so practical and convenient one?

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.2 (2a57b17031)

**Comment by ckerr** [comment] 2023-03-27 15:46
Duplicate of https://github.com/transmission/transmission/issues/65

**Closed by ckerr** 2023-03-27 15:46 UTC
