### ISSUE TITLE
It just keeps crashing.

### ISSUE THREAD

**Issue by Dharengo** [transmission/transmission#7133] opened 2024-09-22 12:09 UTC
### What is the issue?

I don't know what to say. The client just keeps randomly crashing for reasons I do not understand. I'm on Pop!_OS. I'm not sure what information you need exactly, but I'll do whatever I can to help. I don't know if there's a crash log anywhere, if there is, I'm not sure where it is.

This only started happening very recently.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.5 (a6fe2a64aa)

**Comment by jacobzimmermann** [comment] 2024-09-23 00:13
Same problem here:

`transmission-gt[152938]: segfault at 7f301b267747 ip 00007f380f0d2e5e sp 00007f3805ff9698 error 6 in libstdc++.so.6.0.32[d2e5e,7f380f0a4000+141000] likely on CPU 18 (core 24, socket 0)`

NB: running transmission 4.0.5 from flathub, fedora 40 and 41

**Comment by tmp64** [comment] 2024-09-23 05:06
transmission-daemon 4.0.5 began crashing on Alpine after I updated the system. Unfortunately, I don't have a core dump and there wasn't anything in Transmission logs. Restoring the system from a pre-update backup resolved the crash (but that doesn't say much as I also restored Transmission data).

The following packages were updated. Maybe that will be useful for someone else, considering Transmission depends on libcurl.

```
alpine-base-3.19.4-r0 x86_64 {alpine-base} (MIT) [upgradable from: alpine-base-3.19.3-r0]
alpine-release-3.19.4-r0 x86_64 {alpine-base} (MIT) [upgradable from: alpine-release-3.19.3-r0]
curl-8.9.1-r0 x86_64 {curl} (curl) [upgradable from: curl-8.9.0-r0]
libarchive-3.7.5-r0 x86_64 {libarchive} (BSD-2-Clause AND BSD-3-Clause AND Public-Domain) [upgradable from: libarchive-3.7.4-r0]
libcurl-8.9.1-r0 x86_64 {curl} (curl) [upgradable from: libcurl-8.9.0-r0]
```

**Comment by tearfur** [comment] 2024-09-23 08:55
There's too little information to judge, maybe some of you are seeing #7035?

**Comment by Dharengo** [comment] 2024-09-23 11:14
I've no idea but this issue only started last week for me. I did absolutely nothing. So it must be made due to an update either to the app, or to something the app is making use of.

**Comment by RobinTheRogue** [comment] 2024-09-23 17:30
I am also having issues. I am running Ubuntu Server 24.04.1 with kernel 6.8.0-45-generic. I recently did updates and rebooted the machine at which point the transmission-daemon service would no longer run. Here is the output I received:
Sep 23 17:04:58 kessel kernel: audit: type=1400 audit(1727111098.973:643): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=9661 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=110 ouid=0
Sep 23 17:04:59 kessel systemd[1]: transmission-daemon.service: start operation timed out. Terminating.
Sep 23 17:04:59 kessel kernel: audit: type=1400 audit(1727111099.291:644): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=9661 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=110 ouid=0
Sep 23 17:05:01 kessel CRON[10457]: pam_unix(cron:session): session opened for user root(uid=0) by root(uid=0)
Sep 23 17:05:01 kessel CRON[10458]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Sep 23 17:05:01 kessel CRON[10457]: pam_unix(cron:session): session closed for user root
Sep 23 17:05:14 kessel kernel: audit: type=1400 audit(1727111114.350:645): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=9661 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=110 ouid=0
Sep 23 17:05:14 kessel transmission-daemon[9661]: Closing transmission session... done.
Sep 23 17:05:14 kessel systemd[1]: transmission-daemon.service: Failed with result 'timeout'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit transmission-daemon.service has entered the 'failed' state with result 'timeout'.
Sep 23 17:05:14 kessel systemd[1]: Failed to start transmission-daemon.service - Transmission BitTorrent Daemon.
░░ Subject: A start job for unit transmission-daemon.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit transmission-daemon.service has finished with a failure.
░░ 
░░ The job identifier is 2081 and the job result is failed.
Sep 23 17:05:14 kessel systemd[1]: transmission-daemon.service: Consumed 22.311s CPU time, 233.1M memory peak, 0B memory swap peak.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit transmission-daemon.service completed and consumed the indicated resources.

**Comment by proton-ab** [comment] 2024-09-23 21:51
> transmission-daemon 4.0.5 began crashing on Alpine after I updated the system. Unfortunately, I don't have a core dump and there wasn't anything in Transmission logs. Restoring the system from a pre-update backup resolved the crash (but that doesn't say much as I also restored Transmission data).
> 
> The following packages were updated. Maybe that will be useful for someone else, considering Transmission depends on libcurl.
> 
> ```
> alpine-base-3.19.4-r0 x86_64 {alpine-base} (MIT) [upgradable from: alpine-base-3.19.3-r0]
> alpine-release-3.19.4-r0 x86_64 {alpine-base} (MIT) [upgradable from: alpine-release-3.19.3-r0]
> curl-8.9.1-r0 x86_64 {curl} (curl) [upgradable from: curl-8.9.0-r0]
> libarchive-3.7.5-r0 x86_64 {libarchive} (BSD-2-Clause AND BSD-3-Clause AND Public-Domain) [upgradable from: libarchive-3.7.4-r0]
> libcurl-8.9.1-r0 x86_64 {curl} (curl) [upgradable from: libcurl-8.9.0-r0]
> ```

This is related to https://github.com/transmission/transmission/issues/7035. Someone in alpine thought it is amazing idea to push 3.18 and 3.19 branches to 8.9.1 but without applicable patch that is present in 3.20 and main, so it is wrecking havoc month after it was fixed.

Ref:
- https://git.alpinelinux.org/aports/commit/?h=3.18-stable&id=b451d31977d56d6da36f8655246cedfc45ab1b7c
- https://git.alpinelinux.org/aports/commit/?h=3.19-stable&id=998ca79a0eb5e2c17be76a50e12209ac0cc7124e
- https://git.alpinelinux.org/aports/tree/main/curl?h=3.19-stable
- https://git.alpinelinux.org/aports/tree/main/curl?h=3.18-stable
- https://git.alpinelinux.org/aports/tree/main/curl?h=3.20-stable
- https://git.alpinelinux.org/aports/tree/main/curl?h=master

**Comment by Dharengo** [comment] 2024-09-23 23:29
So what do we do? Will these things be fixed in future updates?

**Comment by tearfur** [comment] 2024-09-24 09:16
@RobinTheRogue Maybe this is a hint:

> Sep 23 17:05:14 kessel kernel: audit: type=1400 audit(1727111114.350:645): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=9661 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=110 ouid=0

**Comment by Sergaly** [comment] 2024-09-24 18:47
> @RobinTheRogue This might be hinting at some configuration error with apparmor.
> 
> > Sep 23 17:05:14 kessel kernel: audit: type=1400 audit(1727111114.350:645): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=9661 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=110 ouid=0

I have the same problem. Apparmor configuration is default. At least this issue worth studying, since it occurs on basic configuration.

**Comment by jacobzimmermann** [comment] 2024-09-24 22:56
I don't think it's related to apparmor. The same problem happens on Fedora, which uses selinux, not apparmor.

**Comment by tearfur** [comment] 2024-09-25 01:55
@jacobzimmermann Your crash doesn't look the same as the other crashes reported here. Are you about to get a backtrace of the segfault?

**Comment by Sergaly** [comment] 2024-09-25 07:04
> @jacobzimmermann Your crash doesn't look the same as the other crashes reported here. Are you about to get a backtrace of the segfault?

My case looks similar:

[171564.292366] audit: type=1400 audit(1727121767.913:512): apparmor="ALLOWED" operation="rename_src" class="file" profile="transmission-daemon" name="/etc/transmission-daemon/bandwidth-groups.json.tmp.ybbgJA" pid=71619 comm="transmission-da" requested_mask="wd" denied_mask="wd" fsuid=0 ouid=0

**Comment by vincejv** [comment] 2024-09-25 12:08
@Dharengo
> So what do we do? Will these things be fixed in future updates?

upgrade to alpine 3.20, it has the sigpipe fix
https://git.alpinelinux.org/aports/tree/main/curl?h=3.20-stable

**Comment by proton-ab** [comment] 2024-09-25 15:33
> @RobinTheRogue This might be hinting at some configuration error with apparmor.
> 
> > Sep 23 17:05:14 kessel kernel: audit: type=1400 audit(1727111114.350:645): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=9661 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=110 ouid=0

Duplicate of https://github.com/transmission/transmission/issues/6991 and related to https://gitlab.com/apparmor/apparmor/-/wikis/Release_Notes_2.5#path-name-lookup-and-mediation-of. For one reason or another, we are trying to access socket by path with no leading slash. Ubuntu recently pushed update with new AppArmor profile for Transmission and it lacks `attach_disconnected` workaround so it's all broken.

**Comment by zondaryota** [comment] 2024-09-25 18:22
> > @RobinTheRogue This might be hinting at some configuration error with apparmor.
> > > Sep 23 17:05:14 kessel kernel: audit: type=1400 audit(1727111114.350:645): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=9661 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=110 ouid=0
> 
> Duplicate of #6991 and related to https://gitlab.com/apparmor/apparmor/-/wikis/Release_Notes_2.5#path-name-lookup-and-mediation-of. For one reason or another, we are trying to access socket by path with no leading slash. Ubuntu recently pushed update with new AppArmor profile for Transmission and it lacks `attach_disconnected` workaround so it's all broken.

Faced same issue, just added attach_disconnected to apparmor's transmission profile, the works fine, thanks you

**Comment by tearfur** [comment] 2024-09-26 01:30
> > For one reason or another, we are trying to access socket by path with no leading slash.
> 
> This seems to be side-effect of using either `ProtectSystem` or `PrivateTmp` and would be caused by systemd implementation, not us.

Or maybe the `vmm.notify_socket` credential (whatever that means) is set to `run/systemd/notify` on Ubuntu? That seems to explain the logs provided by @RobinTheRogue.

I don't have a Ubuntu machine on hand to investigate this. If someone can figure it out, then we will know which project we should report this to.

https://github.com/transmission/transmission/blob/38c164933e9f77c110b48fe745861c3b98e3d83e/daemon/daemon.cc#L833

Ref: https://www.freedesktop.org/software/systemd/man/latest/systemd.html#vmm.notify_socket

**Comment by proton-ab** [comment] 2024-09-26 08:12
> > > For one reason or another, we are trying to access socket by path with no leading slash.
> > 
> > 
> > This seems to be side-effect of using either `ProtectSystem` or `PrivateTmp` and would be caused by systemd implementation, not us.
> 
> Or maybe the `vmm.notify_socket` credential (whatever that means) is set to `run/systemd/notify` on Ubuntu? That seems to explain the logs provided by @RobinTheRogue. This credential seems to be used to set the `NOTIFY_SOCKET` environment variable, which in turn is used as the destination that receives notifications from systemd services.
> 
> I don't have a Ubuntu machine on hand to investigate this. If someone can figure it out, then we will know which project we should report this to.
> 
> https://github.com/transmission/transmission/blob/38c164933e9f77c110b48fe745861c3b98e3d83e/daemon/daemon.cc#L833
> 
> Ref: https://www.freedesktop.org/software/systemd/man/latest/systemd.html#vmm.notify_socket

It is not - this is an override added in v254 and as far as I can see Ubuntu does not pass this as system credential so default will be used as before v254. Ubuntu 24.04 is on systemd v255.

I have verified that disabling both `ProtectSystem` and `PrivateTmp` causes path with leading slash to be used (since no other options are present that would cause creation of namespace, such as `ProtectHome`). The best guess of other people I talked with is that this is behavioral change caused by namespace being created for process by systemd when either of these options are used (specifically I think that libsystemd might be passing fd from outer namespace into inner namespace of `transmission-daemon`). I am reluctant to report it upstream (again) because this seems to be well known issue and has been reported and acknowledged by AppArmor developers multiple times[1], explicitly specifying that `attach_disconnected` is currently only way to solve this. They have been supposedly working on better alternatives for a good 5 years now[2], with nothing visible showing up on the horizon. This is also not the first time this affected something in Ubuntu in this exact configuration[3], so the blame lies entirely on maintainer that merged this broken profile with no testing.

Immediate fix would involve using `attach_disconnected` to mediate path by having AppArmor insert leading slash, hence satisfying profile.

Affected users definitely should report it as bug to Ubuntu and let them deal with it though - as it stands, Transmission fails to install on clean Ubuntu 24.04.01 with service timing out to start inside dpkg, so it is certainly broken.

[1]: https://lists.ubuntu.com/archives/apparmor/2018-July/011718.html
[2]: https://gitlab.com/apparmor/apparmor/-/issues/125
[3]: https://lists.ubuntu.com/archives/apparmor/2021-November/012363.html

**Comment by mooky31** [comment] 2024-09-26 20:26
> > > @RobinTheRogue This might be hinting at some configuration error with apparmor.
> > > > Sep 23 17:05:14 kessel kernel: audit: type=1400 audit(1727111114.350:645): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=9661 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=110 ouid=0
> > 
> > 
> > Duplicate of #6991 and related to https://gitlab.com/apparmor/apparmor/-/wikis/Release_Notes_2.5#path-name-lookup-and-mediation-of. For one reason or another, we are trying to access socket by path with no leading slash. Ubuntu recently pushed update with new AppArmor profile for Transmission and it lacks `attach_disconnected` workaround so it's all broken.
> 
> Faced same issue, just added attach_disconnected to apparmor's transmission profile, the works fine, thanks you

Could you please explain how to do this ?
I tried to add `capability attach_disconnected;` at the end of the block `profile transmission-daemon /usr/bin/transmission-daemon flags=(complain) {` but :
```
root@vmi2173903:/etc/apparmor.d# apparmor_parser -r transmission
AppArmor parser error for transmission in profile transmission at line 41: Invalid capability attach_disconnected.
```

System info:
```
root@vmi2173903:/etc/apparmor.d# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
```

**Comment by proton-ab** [comment] 2024-09-27 00:43
>Could you please explain how to do this ?

It's a flag, so
```diff
- profile transmission-daemon /usr/bin/transmission-daemon flags=(complain) {
+ profile transmission-daemon /usr/bin/transmission-daemon flags=(complain,attach_disconnected) {
```

**Comment by dechamps** [comment] 2024-10-03 11:29
> This is related to #7035. Someone at Alpine thought it is amazing idea to push 3.18 and 3.19 branches to 8.9.1 but without applicable patch that is present in 3.20 and main, so it is wrecking havoc month after it was fixed.

Reported in https://gitlab.alpinelinux.org/alpine/aports/-/issues/16493

**Comment by ptrcnull** [comment] 2024-10-03 12:07
> > This is related to #7035. Someone at Alpine thought it is amazing idea to push 3.18 and 3.19 branches to 8.9.1 but without applicable patch that is present in 3.20 and main, so it is wrecking havoc month after it was fixed.
> 
> Reported in https://gitlab.alpinelinux.org/alpine/aports/-/issues/16493

and fixed in [`63ccc4913dad`](https://dup.pw/alpine/aports/63ccc4913dad) (3.18) and [`391cfe0a94e5`](https://dup.pw/alpine/aports/391cfe0a94e5) (3.19)

**Comment by reaperhammer** [comment] 2024-10-06 12:12
I'm a bit confused, is this in fact related to libcurl or apparmor, or are these 2 different issues or related ?
I'm running Ubuntu 24.04.1 and have libcurl 8.5.0, not the pre-release 8.9.1, not really sure why anyone would have that pre-release version?
https://launchpad.net/ubuntu/+source/curl

Also, I checked the diff for the apparmor fix, https://gitlab.com/apparmor/apparmor/-/merge_requests/1355/diffs
applied the fix to the file.. run this command `sudo apparmor_parser -r /etc/apparmor.d/transmission`
reboot my server... same issue, transmission crashes after a few moments, no torrents were started at the time

I'm also not really sure how to check what's causing the crash... all I found was some nonsense in syslog that wasn't really helpful... lots of apparmor="ALLOWED" for transmission services..

**Comment by cboltz** [comment] 2024-10-07 18:18
> I'm also not really sure how to check what's causing the crash... all I found was some nonsense in syslog that wasn't really helpful... lots of apparmor="ALLOWED" for transmission services..

Uploading a file with that "nonsense" would help to improve the AppArmor profile ;-)

That said: the profile is in complain mode (which means it logs things that would be denied, but doesn't actually deny things) - which makes it unlikely that AppArmor is causing the crashes.

**Comment by proton-ab** [comment] 2024-10-08 18:38
> That said: the profile is in complain mode (which means it logs things that would be denied, but doesn't actually deny things) - which makes it unlikely that AppArmor is causing the crashes.

I believe in this particular case, setting `complain` has no effect because of how it internally deals with namespaces - AA is not denying access to this path, but at the same time it is making it impossible for process to access it because it is failing to facilitate connection to path that is outside of namespace. Just the act of having profile matched against binary is enough to trigger this issue.

**Comment by sinner-** [comment] 2024-10-29 06:12
> @jacobzimmermann Your crash doesn't look the same as the other crashes reported here. Are you able to get a backtrace of the segfault?

I have the same issue on Fedora 40.

Constant crashing.

```
                Stack trace of thread 3603:
                #0  0x00005600152545f2 _Z15tr_sessionFetchP10tr_sessionON6tr_web12FetchOptionsE (transmission-gtk + 0x1225f2)
                #1  0x0000560015337310 _ZN12_GLOBAL__N_124favicon_web_done_idle_cbESt10unique_ptrINS_12favicon_dataESt14default_deleteIS1_EE.isra.0 (transmission-gtk + 0x205310)
                #2  0x00005600151dc62c _ZN4sigc8internal9slot_callIZN12_GLOBAL__N_119favicon_web_done_cbERKN6tr_web13FetchResponseEEUlvE_bJEE7call_itEPNS0_8slot_repE (transmission-gtk + 0xaa62c)
                #3  0x00007f318015ac76 glibmm_source_callback (libglibmm-2.68.so.1 + 0x59c76)
                #4  0x00007f317f4b669d g_idle_dispatch (libglib-2.0.so.0 + 0x6369d)
                #5  0x00007f317f4afe8c g_main_context_dispatch_unlocked.lto_priv.0 (libglib-2.0.so.0 + 0x5ce8c)
                #6  0x00007f317f511c98 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0xbec98)
                #7  0x00007f317f4b1383 g_main_context_iteration (libglib-2.0.so.0 + 0x5e383)
                #8  0x00007f317f1130fd g_application_run (libgio-2.0.so.0 + 0xe20fd)
                #9  0x0000560015191c5f main (transmission-gtk + 0x5fc5f)
                #10 0x00007f317ea39088 __libc_start_call_main (libc.so.6 + 0x2a088)
                #11 0x00007f317ea3914b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a14b)
                #12 0x0000560015193385 _start (transmission-gtk + 0x61385)
                
                Stack trace of thread 3605:
                #0  0x00007f317eb1c87d __poll (libc.so.6 + 0x10d87d)
                #1  0x00007f317f511c34 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0xbec34)
                #2  0x00007f317f4b1383 g_main_context_iteration (libglib-2.0.so.0 + 0x5e383)
                #3  0x00007f317f4b13e1 glib_worker_main (libglib-2.0.so.0 + 0x5e3e1)
                #4  0x00007f317f4e0813 g_thread_proxy (libglib-2.0.so.0 + 0x8d813)
                #5  0x00007f317eaa66d7 start_thread (libc.so.6 + 0x976d7)
                #6  0x00007f317eb2a60c __clone3 (libc.so.6 + 0x11b60c)
                
                Stack trace of thread 3612:
                #0  0x00007f317eaa2da9 __futex_abstimed_wait_common (libc.so.6 + 0x93da9)
                #1  0x00007f317eaa57f9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x967f9)
                #2  0x00007f31718a893d cnd_wait (iris_dri.so + 0xa893d)
                #3  0x00007f317188570b util_queue_thread_func (iris_dri.so + 0x8570b)
                #4  0x00007f31718a886c impl_thrd_routine (iris_dri.so + 0xa886c)
                #5  0x00007f317eaa66d7 start_thread (libc.so.6 + 0x976d7)
                #6  0x00007f317eb2a60c __clone3 (libc.so.6 + 0x11b60c)
                
                Stack trace of thread 3604:
                #0  0x00007f317eb283dd syscall (libc.so.6 + 0x1193dd)
                #1  0x00007f317f50eccd g_cond_wait (libglib-2.0.so.0 + 0xbbccd)
                #2  0x00007f317f47a61b g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x2761b)
                #3  0x00007f317f4e1a03 g_thread_pool_spawn_thread (libglib-2.0.so.0 + 0x8ea03)
                #4  0x00007f317f4e0813 g_thread_proxy (libglib-2.0.so.0 + 0x8d813)
                #5  0x00007f317eaa66d7 start_thread (libc.so.6 + 0x976d7)
                #6  0x00007f317eb2a60c __clone3 (libc.so.6 + 0x11b60c)
                
                Stack trace of thread 3606:
                #0  0x00007f317eb1c87d __poll (libc.so.6 + 0x10d87d)
                #1  0x00007f317f511c34 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0xbec34)
                #2  0x00007f317f4b5f37 g_main_loop_run (libglib-2.0.so.0 + 0x62f37)
                #3  0x00007f317f146682 gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x115682)
                #4  0x00007f317f4e0813 g_thread_proxy (libglib-2.0.so.0 + 0x8d813)
                #5  0x00007f317eaa66d7 start_thread (libc.so.6 + 0x976d7)
                #6  0x00007f317eb2a60c __clone3 (libc.so.6 + 0x11b60c)
                
                Stack trace of thread 3610:
                #0  0x00007f317eaa2da9 __futex_abstimed_wait_common (libc.so.6 + 0x93da9)
                #1  0x00007f317eaa57f9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x967f9)
                #2  0x00007f31718a893d cnd_wait (iris_dri.so + 0xa893d)
                #3  0x00007f317188570b util_queue_thread_func (iris_dri.so + 0x8570b)
                #4  0x00007f31718a886c impl_thrd_routine (iris_dri.so + 0xa886c)
                #5  0x00007f317eaa66d7 start_thread (libc.so.6 + 0x976d7)
                #6  0x00007f317eb2a60c __clone3 (libc.so.6 + 0x11b60c)
                
                Stack trace of thread 3609:
                #0  0x00007f317eaa2da9 __futex_abstimed_wait_common (libc.so.6 + 0x93da9)
                #1  0x00007f317eaa57f9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x967f9)
                #2  0x00007f31718a893d cnd_wait (iris_dri.so + 0xa893d)
                #3  0x00007f317188570b util_queue_thread_func (iris_dri.so + 0x8570b)
                #4  0x00007f31718a886c impl_thrd_routine (iris_dri.so + 0xa886c)
                #5  0x00007f317eaa66d7 start_thread (libc.so.6 + 0x976d7)
                #6  0x00007f317eb2a60c __clone3 (libc.so.6 + 0x11b60c)
                
                Stack trace of thread 3623:
                #0  0x00007f317eaa2da9 __futex_abstimed_wait_common (libc.so.6 + 0x93da9)
                #1  0x00007f317eaa57f9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x967f9)
                #2  0x00007f31718a893d cnd_wait (iris_dri.so + 0xa893d)
                #3  0x00007f317188570b util_queue_thread_func (iris_dri.so + 0x8570b)
                #4  0x00007f31718a886c impl_thrd_routine (iris_dri.so + 0xa886c)
                #5  0x00007f317eaa66d7 start_thread (libc.so.6 + 0x976d7)
                #6  0x00007f317eb2a60c __clone3 (libc.so.6 + 0x11b60c)
                
                Stack trace of thread 3624:
                #0  0x00007f317eaa2da9 __futex_abstimed_wait_common (libc.so.6 + 0x93da9)
                #1  0x00007f317eaa57f9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x967f9)
                #2  0x00007f31718a893d cnd_wait (iris_dri.so + 0xa893d)
                #3  0x00007f317188570b util_queue_thread_func (iris_dri.so + 0x8570b)
                #4  0x00007f31718a886c impl_thrd_routine (iris_dri.so + 0xa886c)
                #5  0x00007f317eaa66d7 start_thread (libc.so.6 + 0x976d7)
                #6  0x00007f317eb2a60c __clone3 (libc.so.6 + 0x11b60c)
                
                Stack trace of thread 3611:
                #0  0x00007f317eaa2da9 __futex_abstimed_wait_common (libc.so.6 + 0x93da9)
                #1  0x00007f317eaa57f9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x967f9)
                #2  0x00007f31718a893d cnd_wait (iris_dri.so + 0xa893d)
                #3  0x00007f317188570b util_queue_thread_func (iris_dri.so + 0x8570b)
                #4  0x00007f31718a886c impl_thrd_routine (iris_dri.so + 0xa886c)
                #5  0x00007f317eaa66d7 start_thread (libc.so.6 + 0x976d7)
                #6  0x00007f317eb2a60c __clone3 (libc.so.6 + 0x11b60c)
                
                Stack trace of thread 3608:
                #0  0x00007f317eb283dd syscall (libc.so.6 + 0x1193dd)
                #1  0x00007f317f50eccd g_cond_wait (libglib-2.0.so.0 + 0xbbccd)
                #2  0x00007f317f47a61b g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x2761b)
                #3  0x00007f317f47a67c g_async_queue_pop (libglib-2.0.so.0 + 0x2767c)
                #4  0x00007f317e0ca0d9 fc_thread_func (libpangoft2-1.0.so.0 + 0xb0d9)
                #5  0x00007f317f4e0813 g_thread_proxy (libglib-2.0.so.0 + 0x8d813)
                #6  0x00007f317eaa66d7 start_thread (libc.so.6 + 0x976d7)
                #7  0x00007f317eb2a60c __clone3 (libc.so.6 + 0x11b60c)
                
                Stack trace of thread 3619:
                #0  0x00007f317eb283dd syscall (libc.so.6 + 0x1193dd)
                #1  0x00007f317f50eeb0 g_cond_wait_until (libglib-2.0.so.0 + 0xbbeb0)
                #2  0x00007f317f47a5e3 g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x275e3)
                #3  0x00007f317f4e259a g_thread_pool_thread_proxy.lto_priv.0 (libglib-2.0.so.0 + 0x8f59a)
                #4  0x00007f317f4e0813 g_thread_proxy (libglib-2.0.so.0 + 0x8d813)
                #5  0x00007f317eaa66d7 start_thread (libc.so.6 + 0x976d7)
                #6  0x00007f317eb2a60c __clone3 (libc.so.6 + 0x11b60c)
                ELF object binary architecture: AMD x86-64
```

**Comment by tearfur** [comment] 2024-11-01 03:40
This issue is becoming a dump of all sorts of different crashes and it's getting impossible to discern. I'm going to close it.

If you've got a crash and a stack trace, please open a new issue.

**Closed** 2024-11-01 03:40 UTC

**Comment by Dharengo** [comment] 2024-11-01 04:27
It appears my titling was a bit unfortunate, but at the same time I can't think of one that better describes the issue.

Which has since resolved itself, as mentioned.
