### ISSUE TITLE
Is it expected to be back to zero peers after receiving metadata?

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#3859] opened 2022-10-02 05:28 UTC
1. Open a magnet link
2. See the number of peers increasing
3. Receive the metadata
4. See the number of peers back to zero

**Comment by ckerr** [comment] 2022-10-02 16:27
Depends on what you're referring to?

Transferring piece data is a different state than transferring metainfo,  e.g. a peer may be willing to send metainfo but be choking a client / not sending piece data. So if that's what you're describing, it's as intended.

I'm assuming the peer count comes back up again after awhile?

**Comment by Coeur** [comment] 2022-10-02 19:01
Yes, it comes back up after a while.

**Closed** 2022-10-02 19:02 UTC
Labels: question, needs clarification
