### ISSUE TITLE
In the web version there is always a scrollbar at the bottom

### ISSUE THREAD

**Issue by vartemkin** [transmission/transmission#7154] opened 2024-10-04 05:41 UTC
### What is the issue?

In the web version, there is always a scrollbar at the bottom. It is because the bar with filters protrudes beyond the window. It protrudes because of the indents. To prevent internal indents from creating external indents, you need to add one line to the CSS style.
![S8475456](https://github.com/user-attachments/assets/6935592b-666d-4718-bba0-e0ea23b9290a)
![S4356346](https://github.com/user-attachments/assets/4ee84784-1b3e-4400-9675-54b22aae0f59)

P.S.: I wanted to write about the bug on the phpbb forum, but I couldn't register. Registration doesn't work there.

### Which application of Transmission?

Web client

### Which version of Transmission?

docker image: lscr.io/linuxserver/transmission:latest

**Comment by killemov** [comment] 2024-10-04 11:00
> P.S.: I wanted to write about the bug on the phpbb forum, but I couldn't register. Registration doesn't work there.

This is the correct place for this anyway. What about disabling horizontal scrolling completely?

**Comment by vartemkin** [comment] 2024-10-04 12:57
> This is the correct place for this anyway. What about disabling horizontal scrolling completely?

No. The bottom scrollbar does not need to be disabled completely to maintain adaptivity in non-shaky screens. We need to fix the error due to which the real width of the page is always greater than 100% and we just need to fix this. I highlighted the line on the screenshot that needs to be added to the rule to fix it

**Comment by vartemkin** [comment] 2024-10-04 12:59
.mainwin-filterbar {
...
  box-sizing: border-box; // <-- add this
}

**Comment by Rukario** [comment] 2024-10-06 20:36
>.mainwin-filterbar {
>...
>box-sizing: border-box; // <-- add this
>}

This does not appear to resolve the problem and made adverse effect elsewhere. What browser are you on?

**Comment by vartemkin** [comment] 2024-10-09 06:28
I use the latest versions of Chrome and Firefox. The problem is reproduced in both. The solution you proposed does not work.

![43576457](https://github.com/user-attachments/assets/7197fd2d-8694-4ec1-86f9-69c0c36b00a0)

As a frontend developer by profession, I can say that the problem is in .mainwin-filterbar
You either need to remove the 5px indent

![4364356](https://github.com/user-attachments/assets/8127eac5-4f3c-49ff-bf4a-11f505c6cc4e)

Or write a border box (so that this indent does not expand the bar) (As I wrote in the first message)

**Comment by Rukario** [comment] 2024-10-09 14:56
You haven't yet to provide reproduction step because the problem isn't reproducible to me on Firefox, Chrome on computer, and even Safari on iPhone/iPad. Min-width is for similar problem reproduced by a growing number.

The problem you're currently observing isn't reproduced on 4.0.6 but I can see the problem lied elsewhere. 4.0.x shouldn't have the standalone CSS, it's inline in JavaScript file. You can try delete transmission-app.css and see if it's fixed for you too.

**Comment by Rukario** [comment] 2024-10-09 15:00
The problem you're currently observing isn't reproduced on 4.0.6 but I can see the problem lied elsewhere. 4.0.x shouldn't have the standalone CSS, it's inline in JavaScript file. You can try delete transmission-app.css and see if it's fixed for you too.

**Comment by Rukario** [comment] 2024-10-14 03:55
Resolved in #7159

For existing setup you can try delete `public_html/transmission-app.css` from working directory and update `public_html/index.html` to not load the missing file.

**Closed** 2024-11-12 17:07 UTC
