### ISSUE TITLE
Transmission hangs and locks up the keyboard on  M1 Macbook Pro when using "Move data file to..."

### ISSUE THREAD

**Issue by magiker** [transmission/transmission#6636] opened 2024-02-21 08:26 UTC
### What is the issue?

The keyboard locks up completely when moving datafile from one external drive to another. This is a very weird bug. I cannot enter text into any application, Chrome, iTerm 2, Franz etc unless i force quit Transmission.

Version: Transmission 4.0.5 (a6fe2a64aa)
Version: Mac OS Sonoma 14.3.1 (23D60)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.5 (a6fe2a64aa)

**Comment by killemov** [comment] 2024-02-21 10:18
How do you force quit Transmission when you can't use the keyboard?

But read before you post ... #108 #2462

**Comment by magiker** [comment] 2024-02-21 15:10
> How do you force quit Transmission when you can't use the keyboard?
> 
> But read before you post ... #108 #2462

I have of course checked previous issues and I have seen the issues with Transmission hanging while moving data. This has been going on for years but this bug is new for me.

The mouse still works so you can right click the application in the dock and select "force quit", it is also possible to set a timer in the shell to kill it or use activity monitor with the mouse as well.

**Comment by Yohmi** [comment] 2024-02-23 09:54
Not new for me, it's been years (before 3.x) for me when moving data the whole Mac faces issues, I can't browse Internet, I can't type etc. even without beach ball.

**Comment by magiker** [comment] 2024-02-23 12:09
For me the keyboard hanging is new, the beach ball and Transmission hanging is not new. I did move the files manually and then changed with "Move data file to..." in Transmission afterwards. This workaround works fine.

The weird thing is that it locks up Mac OS X in this way at all, as it should not allow any process to behave this way. This leads me to think that it might an issue with Mac OS itself. 

I might have to switch to another torrent client, I have tried several and I really enjoy Transmission, at least up until this point. Any tips? :o]

**Comment by killemov** [comment] 2024-02-24 06:41
So when moving data with Finder there is no keyboard lock-up and when moving data with Transmission there is. It appears that Transmission does this with a single big, unyielding IO operation when it should be doing it in many small ones, yielding in between. I don't know if Transmission can detect filesystem barriers, but that looks like the key to differentiate between strategies.

**Comment by GaryElshaw** [comment] 2024-02-24 06:44
I think Charles has this at the top of the list for Transmission 5.0.

**Comment by tearfur** [comment] 2024-03-23 06:12
Closing as duplicate of #2462

**Closed by tearfur** 2024-03-23 06:12 UTC
