### ISSUE TITLE
4.0.0-beta.1 WebUI should display and reflect "Groups" from app

### ISSUE THREAD

**Issue by TorsteinVin** [transmission/transmission#3965] opened 2022-10-14 11:30 UTC
### What is the issue?

I have set up groups in Transmission 4.00-beta.1 to have things more organized. These groups do not show up in the WebUI. I think it would be a welcome feature to have the WebUI reflect groups from the app, and hope the dev-team is considering this. 

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.0-beta.1

**Comment by mikedld** [comment] 2022-10-20 16:14
This looks like a duplicate of #3813 and more generally #79. Nod if you agree.

**Closed** 2022-12-01 16:59 UTC
Labels: duplicate

**Comment by TorsteinVin** [comment] 2022-12-02 11:23
Does this mean "Groups" has been added to the webui? Also, eta for beta2?

**Comment by GaryElshaw** [comment] 2022-12-02 12:09
Today: https://github.com/transmission/transmission/releases/tag/4.0.0-beta.2?notification_referrer_id=NT_kwDOBB1PIrM0OTc3NTg0NzU1OjY5MDI5NjY2
