### ISSUE TITLE
Add groups usability

### ISSUE THREAD

**Issue by ghost** [transmission/transmission#38] opened 2016-09-27 19:34 UTC
Today the only usage I have seen so far for groups is to filter the view of Transmission.
But why not to give those groups some usage ? I am thinking of having some properties linked to the groups like:
- having different destination folder for Torrents
- having different seed ration for those

And possibly having the support for groups with the API, for example when I add a file, I tag in the "seed" group so I know that I will retain this file forever.

**Comment by Taruga** [comment] 2016-11-12 04:11
Waiting for those features for so long. It was awesome if they come reality one day....

**Comment by Trisooma** [comment] 2017-07-09 12:11
Something that allows you to set destination folder for completed torrent was commited to trac a while back: https://trac.transmissionbt.com/ticket/5385.
FYI I am the original author of that patch

**Comment by mattia-b89** [comment] 2019-07-12 09:24
duplicate of #79  ?

**Comment by ckerr** [comment] 2022-01-18 06:40
Closing as duplicate of #79

**Closed by ckerr** 2022-01-18 06:40 UTC
Labels: enhancement, pr welcome
