### ISSUE TITLE
Freeze in ubuntu 19.04

### ISSUE THREAD

**Issue by ndtoan96** [transmission/transmission#901] opened 2019-05-07 12:30 UTC
Adding magnet link from browser while transmission was running makes it freeze in Ubuntu 19.04.

I've already reported this to Ubuntu dev but he seems to not know where the problem is. More information: https://bugs.launchpad.net/ubuntu/+source/transmission/+bug/1825651

**Comment by ckerr** [comment] 2022-01-25 21:15
I'm not able to reproduce this issue in the [nightly builds](https://transmissionbt.com/download/). If this is still happening for you in a nightly build, please update the issue with info on how the nightlies behave.

**Comment by Noobsai** [comment] 2022-01-26 22:29
Hi @ckerr 

I'm able to reproduce on build https://github.com/transmission/transmission/commit/4fe33496c781031217ce5045d1f169ed0b23ecf4. 
Arch x64, gnome-shell 41.3, X11


1) Open the transmission (do not minimize to tray), will be better to move it to the secondary monitor.
2) Make the window Inactive (unfocused)
3) Open a browser and click to any magnet
You will see the torrent option window
![Screenshot from 2022-01-27 02-21-33](https://user-images.githubusercontent.com/17625194/151249203-e0bca68b-3857-413d-b587-a91d79dc6667.png)

4) Click directly on any dropdown (Priority or Destination folder). 
     Do **not** click at window, title or notification. The first click must be on dropdown.
5) Transmission freezes with the output:

> (transmission-gtk:16991): Gtk-CRITICAL **: 02:07:35.287: _gtk_css_image_get_concrete_size: assertion 'default_width > 0' failed
> 
> (transmission-gtk:16991): Gtk-CRITICAL **: 02:07:35.287: _gtk_css_image_get_surface: assertion 'surface_height > 0' failed
> 
> (transmission-gtk:16991): Gtk-CRITICAL **: 02:07:35.302: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> 
> (transmission-gtk:16991): Gtk-CRITICAL **: 02:07:35.302: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> 
> (transmission-gtk:16991): Gtk-CRITICAL **: 02:07:35.302: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> 
> (transmission-gtk:16991): Gtk-CRITICAL **: 02:07:35.302: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> 
> (transmission-gtk:16991): Gtk-CRITICAL **: 02:07:35.414: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> 
6) And transmission cannot be closed, crashed on minimize (click on tray icon): 
[crash.log](https://github.com/transmission/transmission/files/7945725/crash.log)

- Freeze is not 100% reproducible, but I'm able to catch 8 of 10
- It works with torrent-files too if open it from the browser directly 
- it freezes if the main window hasn't been active before opened the torrent options window. I think problem is here.
- It does't freeze if open torrent from Nautilus (Nautilus makes the main window active for moment before opened the torrent options window)
- it freezes with chrome, firefox

I will be grateful if you tell me how to build and run with a debug symbols to get a readable stack trace.

Thanks!

**Comment by ckerr** [comment] 2022-02-23 18:04
Crash trace:

```txt
#0  0x00007f7e0f25a51b _ZN3Gtk6Window17get_transient_forEv (libgtkmm-3.0.so.1 + 0x2f751b)
#1  0x000055a74a61f56c n/a (transmission-gtk + 0xe656c)
#2  0x000055a74a5b6b32 n/a (transmission-gtk + 0x7db32)
#3  0x000055a74a5b125b n/a (transmission-gtk + 0x7825b)
#4  0x00007f7e0edf1413 n/a (libgiomm-2.4.so.1 + 0x12e413)
#5  0x00007f7e0f4e9ebf g_closure_invoke (libgobject-2.0.so.0 + 0x12ebf)
#6  0x00007f7e0f50637b n/a (libgobject-2.0.so.0 + 0x2f37b)
#7  0x00007f7e0f507ba7 g_signal_emit_valist (libgobject-2.0.so.0 + 0x30ba7)
#8  0x00007f7e0f507e04 g_signal_emit (libgobject-2.0.so.0 + 0x30e04)
#9  0x00007f7e0f608e4e n/a (libgio-2.0.so.0 + 0xd6e4e)
#10 0x00007f7e0f8eb6c9 n/a (libgtk-3.so.0 + 0x1ef6c9)
#11 0x00007f7e0f4e9ebf g_closure_invoke (libgobject-2.0.so.0 + 0x12ebf)
#12 0x00007f7e0f506188 n/a (libgobject-2.0.so.0 + 0x2f188)
```

**Comment by ckerr** [comment] 2022-02-24 16:18
>  I will be grateful if you tell me how to build and run with a debug symbols to get a readable stack trace.

https://github.com/transmission/transmission/#building has information on how to build Transmission that should work!

**Comment by ckerr** [comment] 2023-01-17 18:56
Closing due to lack of actionable info. If this is still broken in the Transmission 4 series, please open a new issue. Thanks!

**Closed by ckerr** 2023-01-17 18:56 UTC
Labels: bug, needs clarification, scope:gtk
