### ISSUE TITLE
ADD PROXY!!!

### ISSUE THREAD

**Issue by Mikrizi** [transmission/transmission#4554] opened 2023-01-08 01:22 UTC
### What is the issue?

Is there seriously no proxy support in the client? 

Why was this functionality removed? What kind of nonsense and absurdity? This is not some superfluous or narrow function, for example, my provider blocks the download of torrents, this can be easily bypassed using http proxies, which can be taken from the first site that comes across, which will perfectly solve the problem, or a person does not want to give out his real IP address.

The lack of proxy support right in the client makes the program unusable.

Hell, transmission is the only torrent that isn't tied to DBUS that can be used on any operating system, Hyperbola for example.

WHAT THE ***UCK** IS NOT PROXY?

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

**Comment by mikedld** [comment] 2023-01-08 02:07
Why would you think demanding tone and foul language will help prove your point?

Seems like a duplicate of #447. There's also https://github.com/transmission/transmission/issues/344#issuecomment-318743154.

**Closed by mikedld** 2023-01-08 02:07 UTC

**Comment by Mikrizi** [comment] 2023-01-08 02:25
> Why would you think demanding tone and foul language will help prove your point?
> 
> Seems like a duplicate of #447. There's also [#344 (comment)](https://github.com/transmission/transmission/issues/344#issuecomment-318743154).

infamy.
