### ISSUE TITLE
Transmission 4.0.6 Speed limit

### ISSUE THREAD

**Issue by Omeliax** [transmission/transmission#6885] opened 2024-06-02 15:24 UTC
### What is the issue?

The speed limit does not work correctly, when you start the application with the "turtle" pressed, the speed is not limited, when you press and press the "turtle" again, the restriction begins to work.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.6

**Comment by SNBogdanov** [comment] 2024-06-16 04:45
Same behaviour for daemon mode.
Also this is true when add new torrent. It started in unlimited mode

**Comment by tearfur** [comment] 2024-06-21 07:45
Closing as duplicate of #5488.

**Closed by tearfur** 2024-06-21 07:45 UTC
