### ISSUE TITLE
Transmission stops and never restart

### ISSUE THREAD

**Issue by cybospam** [transmission/transmission#5190] opened 2023-03-10 10:25 UTC
### What is the issue?

Transmission 4.01 downloads are stopping and never restart. Application must be forced quitting prior to being restarted
[Apple crash report-20230310.rtf.zip](https://github.com/transmission/transmission/files/10941067/Apple.crash.report-20230310.rtf.zip)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4,01

**Comment by cybospam** [comment] 2023-03-10 16:47
FYI, I think I found the cause of the freeze I am facing with Transmission. The app is freezing if there are too many torrents active. I have removed half of the torrents I had in line and the app seems to not be freezing anymore.

**Comment by ckerr** [comment] 2023-03-11 05:12
```
Date/Time:                2023-03-10 11:16:34.073 +0100
End time:                  2023-03-10 11:17:10.997 +0100
OS Version:              macOS 11.7 (Build 20G817)
Architecture:          x86_64h
Report Version:      32
Share With Devs:    Yes

Data Source:            Stackshots
Shared Cache:          1FF61C30-FB8C-36BE-B7E2-5D513370F4BB slid base address 0x7fff2010e000, slide 0x10e000

Command:                    Transmission
Path:                          /Applications/Transmission.app/Contents/MacOS/Transmission
Identifier:              org.m0k.transmission
Version:                    4.0.1 (14714.4.0.1)
Parent:                      launchd [1]
PID:                            4125
Time Since Fork:    595s

Event:                        hang
Duration:                  36.92s
Duration Sampled: 1.10s (process was unresponsive for 36 seconds before sampling)
Steps:                        11 (100ms sampling interval)

Hardware model:      iMac17,1
Active cpus:            8

Time Awake Since Boot: 6625s
Time Since Wake:    6419s

Fan speed:                1204 rpm

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------


Heaviest stack for the main thread of the target process:
    11    start + 1 (libdyld.dylib + 89917) [0x7fff20437f3d]
    11    NSApplicationMain + 816 (AppKit + 14348) [0x7fff22ce080c]
    11    -[NSApplication run] + 586 (AppKit + 194057) [0x7fff22d0c609]
    11    -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364 (AppKit + 250597) [0x7fff22d1a2e5]
    11    _DPSNextEvent + 864 (AppKit + 256786) [0x7fff22d1bb12]
    11    _BlockUntilNextEventMatchingListInModeWithFilter + 70 (HIToolbox + 199923) [0x7fff2875bcf3]
    11    ReceiveNextEventCommon + 284 (HIToolbox + 200230) [0x7fff2875be26]
    11    RunCurrentEventLoopInMode + 292 (HIToolbox + 201203) [0x7fff2875c1f3]
    11    CFRunLoopRunSpecific + 563 (CoreFoundation + 518652) [0x7fff205129fc]
    11    __CFRunLoopRun + 879 (CoreFoundation + 521262) [0x7fff2051342e]
    11    __CFRunLoopDoBlocks + 440 (CoreFoundation + 526195) [0x7fff20514773]
    11    __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12 (CoreFoundation + 526530) [0x7fff205148c2]
    11    ___NSMainRunLoopPerformBlockInModes_block_invoke + 25 (AppKit + 4904168) [0x7fff2318a4e8]
    11    __52-[NSApplication(NSAppleEventHandling) _handleAEQuit]_block_invoke + 46 (AppKit + 4573374) [0x7fff231398be]
    11    -[NSApplication _terminateFromSender:askIfShouldTerminate:saveWindows:] + 126 (AppKit + 4573622) [0x7fff231399b6]
    11    -[NSApplication terminate:] + 1377 (AppKit + 3043075) [0x7fff22fc3f03]
    11    -[NSNotificationCenter postNotificationName:object:userInfo:] + 59 (Foundation + 39976) [0x7fff2124dc28]
    11    _CFXNotificationPost + 736 (CoreFoundation + 292654) [0x7fff204db72e]
    11    _CFXRegistrationPost + 496 (CoreFoundation + 1121908) [0x7fff205a5e74]
    11    ___CFXRegistrationPost_block_invoke + 49 (CoreFoundation + 1122041) [0x7fff205a5ef9]
    11    __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12 (CoreFoundation + 484547) [0x7fff2050a4c3]
    11    ??? (Transmission + 40827) [0x10d011f7b]
    11    ??? (Transmission + 815507) [0x10d0cf193]
    11    std::__1::__assoc_sub_state::wait() + 46 (libc++.1.dylib + 50912) [0x7fff203866e0]
    11    std::__1::__assoc_sub_state::__sub_wait(std::__1::unique_lock<std::__1::mutex>&) + 45 (libc++.1.dylib + 50807) [0x7fff20386677]
    11    std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18 (libc++.1.dylib + 48498) [0x7fff20385d72]
    11    __psynch_cvwait + 10 (libsystem_kernel.dylib + 15566) [0x7fff203e9cce]
 *11    psynch_cvcontinue + 0 (pthread + 21269) [0xffffff80035ea315]
```

**Comment by ckerr** [comment] 2023-03-11 05:14
>     11    ??? (Transmission + 40827) [0x10d011f7b]
>    11    ??? (Transmission + 815507) [0x10d0cf193]

Calling retracer boss @mikedld :smile_cat:

**Comment by mikedld** [comment] 2023-03-11 05:39
```
    11    -[Controller applicationWillTerminate:] (Controller.mm:1075) (Transmission + 40827) [0x10d011f7b]
    11    tr_sessionClose (session.cc:1334) (Transmission + 815507) [0x10d0cf193]
```

**Comment by ckerr** [comment] 2023-03-17 17:47
Closing as duplicate of https://github.com/transmission/transmission/issues/5243

**Closed by ckerr** 2023-03-17 17:47 UTC
Labels: scope:mac, needs confirmation, needs testers
