### ISSUE TITLE
transmission-remote: consistently seperate output columns with 2+ spaces for easier piping in shell scripts

### ISSUE THREAD

**Issue by fritzrehde** [transmission/transmission#3817] opened 2022-09-13 21:51 UTC
I am trying to filter the output of commands like `transmission-remote --list` or `transmission-remote -t $ID --files` using Unix tools like `awk` and `sed`, but the delimiters between the table columns are suboptimal for this purpose. Sometimes it is 2 or more spaces, sometimes only 1. 
Would it be possible to add an option to specify a custom delimiter like "," or, at least, always output at least two spaces between columns. (Example for only one space between columns: `transmission-remote -t $ID --files`)

**Comment by LaserEyess** [comment] 2022-09-13 23:02
The output of `transmission-remote` is supposed to be human readable. If you want a machine readable version the easiest thing to do would be to dump the JSON from the RPC call. That would be way easier to work with than delimiting text, and you can use jq for scripts.

**Comment by ckerr** [comment] 2022-09-13 23:10
I'm going to close this as a duplicate of https://github.com/transmission/transmission/issues/2299 because I _think_ this is the same issue?

If this is in error, please feel free to open another issue. Thanks!

**Closed by ckerr** 2022-09-13 23:10 UTC

**Comment by LaserEyess** [comment] 2022-09-14 21:29
@fritzrehde #3819 should be what you want
