### ISSUE TITLE
[3.00] Over 14 million transmission gtk errors in syslog, crashes and mislocated labels

### ISSUE THREAD

**Issue by PeterKMcN** [transmission/transmission#4126] opened 2022-11-09 11:25 UTC
I am running Transmission 3.00 as distributed with Ubuntu 22.04 (removed incorrect reference to snap) under Ubuntu 22.04. All snaps are shown as up to date and all updates installed. this has been going on for a month or so and the 14 million errors a week is typical

I attach two screenshots showing mislocated labels and a small sample of the gtk errors recorded in syslog

Despite the wrong labels the prompt windows (eg remove torrent?) work correctly but the display windows (eg peers tab) do not display correctly.

As for the crashes I have no additional information to offer but assume they are as a result of the errors

![image](https://user-images.githubusercontent.com/79274767/200816608-e6593bb9-cf76-4e58-986b-7a8e8fefd844.png)
![image](https://user-images.githubusercontent.com/79274767/200816296-6aa8907c-48b6-49f9-b84b-051f6adc744e.png)

[Transmission errors.txt](https://github.com/transmission/transmission/files/9970475/Transmission.errors.txt)

**Comment by mikedld** [comment] 2022-11-09 11:42
Something is going terribly wrong there but I'm not sure we can help. We're not maintaining any Snap or AppImage or Flatpak packages ourselves and there're no links to those packages on the [official downloads page](https://transmissionbt.com/download). Moreover, I [cannot find](https://snapcraft.io/search?q=transmission) any GTK client packages in the Snap Store.

**Comment by PeterKMcN** [comment] 2022-11-09 12:14
Sorry, I think I assumed it was a snap package because Ubuntu seems to have gone that way for its own reasons.

However, having checked the software center it doesn't seem to be.

My apologies

**Comment by mikedld** [comment] 2022-11-09 12:23
Is Transmission the only non-Snap GTK+ 3 app behaving this way on your system? Since you're saying it started happening only a month ago, do you remember updating the system back then? I can't imagine how it could be related to Transmission at this point, hence looking for other factors that may have had an influence...

**Comment by PeterKMcN** [comment] 2022-11-09 12:43
Transmission is the only app I am aware with such problems. No others are showing up in the syslog

I regularly do the software updates with Ubuntu but don't remember anything in particular. Not a helpful response I know but best I can do

**Comment by BrendonIrwan** [comment] 2022-11-26 03:28
I have a similar issue for the same version built by Debian (testing).

Just playing around the UI (while downloading an item) can break it. Not that I found a static way to reproduce it.

In some occasions, I ran into segfaults.

You can review the attached log which I hope helps.

![image](https://user-images.githubusercontent.com/13151306/204070693-5ba90fdc-3282-4f73-be56-a8af0d48c743.png)
[log.txt](https://github.com/transmission/transmission/files/10095598/log.txt)

**Comment by dominix** [comment] 2022-12-03 20:44
same for me (ubuntu 22.04) no snap, random crash when editing properties, or setting ratio, or renaming torrent.

**Comment by Ka-zam** [comment] 2022-12-05 08:56
Trying to set properties of a torrent/opening and closing the properties window will crash it. Ubuntu 22.04.

**Comment by dominix** [comment] 2022-12-05 21:06
for me : any property of a torrent(file name, ration, pair or server) random crash (sometimes works), changing placement folder random crash, preferences of the app as well, even "about" show strange glitches.

**Comment by uralets** [comment] 2022-12-11 06:17
See some of the last comments here https://bugs.launchpad.net/ubuntu/+source/transmission/+bug/1969315

Seems that Transmission-GTK is somehow incompatible with the GTK (and poss. other) libs in Ubuntu.

And it's happening not only for Ubuntu/Debian built deb/snap/... but for example Arch binary as well.

Which seems to point that t-gtk does something that breaks Ubuntu's GTK.

No other app exhibits this behavior for me.

**Comment by ckerr** [comment] 2022-12-13 08:55
If there was a data corruption bug, or if there were enough easy fixes, it might be worth doing a 3.0x patch release, without that tipping point I'm hesitant to do it since so much effort is going into the 4 series.

**Comment by uralets** [comment] 2022-12-13 13:52
> If there was a data corruption bug, or if there were enough easy
> fixes, it might be worth doing a 3.0x patch release, without that
> tipping point I'm hesitant to do it since so much effort is going
> into the 4 series.
> 

Not sure if this could lead to actual data corruption, but since it
writes all sorts of random values to say any input field in the prop
dialog, it could fill say dl/ul, peers per torrent limits to a torrent?
Thing is, I'm not entirely sure, but I did find some of my torrents
suddenly set to 2 peers limit (I was wondering why it was so while the
swarm was large) - sure as hell I didn't set that...

**Comment by mikedld** [comment] 2022-12-16 16:07
I made some additional changes in #4379 but I'd say even those weren't strictly required. The original issue was fixed a while ago.

**Comment by ckerr** [comment] 2022-12-16 21:11
Based on the previous comment, I'm closing this as fixed.

If we ever do a point release for the 3 series, we should consider backporting this fix

**Closed by ckerr** 2022-12-16 21:11 UTC
Labels: scope:gtk, confirmed
