### ISSUE TITLE
Bump miniupnpc to 2.2.5

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#5609] opened 2023-06-12 10:55 UTC
Out today: https://github.com/miniupnp/miniupnp/commit/58837ef586278d18cbebee50be758835ed4be79a

### Which version of Transmission?

4.x

**Comment by ckerr** [comment] 2023-06-12 16:16
duplicate of https://github.com/transmission/transmission/issues/3181 :smile_cat:

**Comment by GaryElshaw** [comment] 2023-06-12 16:18
True! I'll close the other if you reopen this latest release?

**Comment by GaryElshaw** [comment] 2023-06-18 04:18
Tested and compiles from current git. Can we please update this?

**Closed** 2024-03-15 23:19 UTC
Labels: dependencies
