### ISSUE TITLE
Crashing every 3 minutes on FreeBSD

### ISSUE THREAD

**Issue by Nerdy314159265** [transmission/transmission#1359] opened 2020-07-12 18:09 UTC
It's running on FreeBSD 11.3-Release-p11 with Transmission version 3.00_2

After starting transmission-daemon in my jail, it runs for about 3 minutes before exiting on signal 6.
I've starting trying to log the error but it doesn't seem to be recording one to the log file before the crash

All I see before the crash is a failure to connect to a tracker and that it will retry scraping in some amount of time.

**Comment by beam** [comment] 2020-07-14 08:26
Same here, i have to downgrade to 2.94.
How many torrents in client have you got?

**Comment by Nerdy314159265** [comment] 2020-07-14 11:22
73 with less than 200GB between them.
Possibly related is that I've noticed performance completely tank when a single large torrent is added.

**Comment by zoon01** [comment] 2020-07-19 20:18
i saw this in my log files too:
Jul 16 00:03:33 transmission-daemon: Unable to create session lock file (78): Function not implemented (session-id.c:96)

**Comment by pywy18** [comment] 2020-07-25 11:59
Same for me with 12.1-RELEASE-p7 with transmission-daemon-3.00_2
Crash happends every one day or two.
Nothing obvious in logs.

**Comment by Nerdy314159265** [comment] 2020-07-25 15:12
I've also reverted to the previous release and that solved the issue entirely.
So there is likely some regression in either transmission or a library that it used in previous FreeBSD releases.
I specifically reset my pkg repo from latest to release_4 and reinstalled only transmission-cli (since I'm using it headless and don't need the extra stuff).

Also there was not a single error logged before the crashes; I believe I had the logs configured for debugging.

**Comment by ckerr** [comment] 2020-07-27 23:42
Would it be possible for you to make a debug build from source and run it inside a debugger so that you can provide a backtrace?

The README has instructions for building from source

**Comment by beam** [comment] 2020-07-28 09:30
Is it ok? https://gist.github.com/beam/162daada7db1a949e83818e47cdb6aa4

**Comment by mikedld** [comment] 2020-07-28 11:45
FreeBSD seems to default to Release build configuration, unless you have `WITH_DEBUG` or `CMAKE_BUILD_TYPE` defined somewhere: https://github.com/freebsd/freebsd-ports/blob/9f478a9fe796b18440e0420426a64deb8585b78d/Mk/Uses/cmake.mk#L65-L69

Release builds don't assert unless `TR_FORCE_ASSERTIONS` macro is defined (CMake itself is expected to define `NDEBUG` for release configurations which effectively disables `TR_ASSERT` macros), which I'm not seeing anywhere in FreeBSD ports.

That is to say that if you're building from source then please pass `-DCMAKE_BUILD_TYPE=RelWithDebInfo` option to cmake when configuring so that you get a release build that doesn't assert but still does have enough debug information to hopefully produce a nice backtrace.

What you're seeing right now is not a crash but an assertion (which matches SIGABRT=6 that OP mentions). Don't expect me to understand in full how FreeBSD ports work, but if you're building them from source and somehow getting a debug build while you didn't define `WITH_DEBUG` and didn't override `CMAKE_BUILD_TYPE` then it's an issue you need to report downstream; if you did in fact define `WITH_DEBUG` and are now getting an assertion then let's figure out what's causing it but it shouldn't stop you from using the software in the meantime (because now you hopefully understand what the workaround is).

**Comment by beam** [comment] 2020-07-28 11:54
I defined WITH_DEBUG for this port and i check cc compiler gets parametr -g

**Comment by mikedld** [comment] 2020-07-28 11:59
Did you do this even before reporting this issue? Apart from adding debug information, defining `WITH_DEBUG` enables assertions. Is that what you really want? Just trying to understand you motivation and whether your issues have started once you defined `WITH_DEBUG` or were present before that.

**Comment by beam** [comment] 2020-07-28 12:00
Issue starts before, i add WITH_DEBUG and recompile port a run transmission under gdb.
After crash a read .core file for backtrace.

**Comment by mikedld** [comment] 2020-07-28 12:16
Instead of `WITH_DEBUG`, please define `CMAKE_BUILD_TYPE=RelWithDebInfo`. The abort that you're seeing right now is a bug, but is not (I guess) the crash that you were seeing prior to defining `WITH_DEBUG`.

**Comment by mikedld** [comment] 2020-07-28 12:19
Looking at that cmake.mk, you may also need to define `STRIP=no` or something like that to prevent debug symbols from being stripped.

**Comment by beam** [comment] 2020-07-28 12:41
Is it possible that it stopped crashing at all now? I have RelWithDebInfo with keeped (i hope) debug symbols.

**Comment by Nerdy314159265** [comment] 2020-07-28 13:15
> FreeBSD seems to default to Release build configuration, unless you have `WITH_DEBUG` or `CMAKE_BUILD_TYPE` defined somewhere: https://github.com/freebsd/freebsd-ports/blob/9f478a9fe796b18440e0420426a64deb8585b78d/Mk/Uses/cmake.mk#L65-L69
> 
> Release builds don't assert unless `TR_FORCE_ASSERTIONS` macro is defined (CMake itself is expected to define `NDEBUG` for release configurations which effectively disables `TR_ASSERT` macros), which I'm not seeing anywhere in FreeBSD ports.

> What you're seeing right now is not a crash but an assertion (which matches SIGABRT=6 that OP mentions). Don't expect me to understand in full how FreeBSD ports work, but if you're building them from source and somehow getting a debug build while you didn't define `WITH_DEBUG` and didn't override `CMAKE_BUILD_TYPE` then it's an issue you need to report downstream; if you did in fact define `WITH_DEBUG` or override `CMAKE_BUILD_TYPE` and are now getting an assertion then let's figure out what's causing it but it shouldn't stop you from using the software in the meantime (because now you hopefully understand what the workaround is).

I want to make sure it's clear that I did not build transmission from source and got it from the pkg repository as normal. So if the issue is due to assertions being active then that's an issue with the version in the actual repository.

**Comment by beam** [comment] 2020-07-28 13:25
Yes, thats corrent. NDEBUG missing in compiled package in fbsd repository.
But i don't know how have to add NDEBUG FreeBSD ports system or Transmission in CMakeList.txt with

if (NOT CMAKE_BUILD_TYPE MATCHES Debug)
    add_definitions(-DNDEBUG)
endif()

**Comment by mikedld** [comment] 2020-07-28 13:49
From the same cmake.mk file, it looks like FreeBSD overrides `CMAKE_{C,CXX}_FLAGS_RELEASE` with its own `{C,CXX}FLAGS` which probably doesn't contain `-DNDEBUG`. This may be intentional (I know some people want to enable assertions in release builds, that's why `TR_FORCE_ASSERTIONS` was added) but is still worth raising a question with FreeBSD developers.

The issue here is then about a failed assertion which we need to look into. The code was refactored a bit for 3.00 and this assertion is a new one.

**Comment by beam** [comment] 2020-07-28 14:52
Ok, i opened ticket on FreeBSD bugzilla and linked here..

**Comment by beam** [comment] 2020-07-31 07:58
@Nerdy314159265 try to upgrade on version 3.00**_3**

**Comment by beam** [comment] 2020-08-04 10:55
@Nerdy314159265 @zoon01 @pywy18 is it ok now? Package is on /latest **transmission-daemon-3.00_3**

**Comment by elovelan** [comment] 2020-08-05 00:46
@beam, I can confirm that I also had this problem and it has been resolved by `3.00_3` (running in a jail)

**Comment by pywy18** [comment] 2020-08-11 08:54
@beam , upgraded to transmission-daemon-3.00_3 (latest)  this morning , I'll let you know if crash happends again.

**Comment by pywy18** [comment] 2020-08-14 08:02
Running smoothly since a few, days ago. Looks like release transmission-daemon-3.00_3 solved my issues with this random crash.
Cheers

**Comment by zoon01** [comment] 2020-09-12 17:14
> @Nerdy314159265 @zoon01 @pywy18 is it ok now? Package is on /latest **transmission-daemon-3.00_3**

working ok now but, still warnings in log file:


transmission-daemon[5782]: Unable to create session lock file (78): Function not implemented (session-id.c:96)

**Comment by pywy18** [comment] 2020-09-13 10:25
Yes working just fine for me. No crash since update with the /latest version. I've disabled logging so can't tell about the warnings :(

**Comment by Nerdy314159265** [comment] 2020-10-07 10:32
@beam I think that change fixed it, it so far seems to be working fine and has been up continuously for awhile now.

Full disclosure: I installed via portsnap and made a small modification to the source (I just implemented #922 since I wanted it and it hasn't made it to release yet). Nothing that should affect this specific issue.

**Closed** 2021-04-23 13:18 UTC
Labels: needs clarification
