### ISSUE TITLE
Maximum download and seed limits not working

### ISSUE THREAD

**Issue by robd003** [transmission/transmission#4780] opened 2023-02-09 20:12 UTC
### What is the issue?

If you limit the maximum downloads and seeds to, say 7 and 3 respectively, when one is downloaded it should start seeding. When you have three torrents already seeding, a fourth download will also start seeding, thereby ignoring the maximum seeds. This has been an issue with Transmission for years.

Copied this report from: https://forums.macrumors.com/threads/bittorrent-client-transmission-gains-apple-silicon-support-in-fourth-major-release.2380179/post-31952470

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0

**Comment by glotcha** [comment] 2023-02-22 09:10
FWIW, both global bandwidth limits and speed limit mode don't appear to work in 4.0 on the Mac. I use this feature so as not to hog the internet connection I share with other people in the house. High priority pretty please, thank you!

**Comment by ckerr** [comment] 2023-02-22 10:27
@glotcha #4701

**Comment by ckerr** [comment] 2023-02-28 15:51
@robd003 thanks for reporting this, but I think it's a duplicate of https://github.com/transmission/transmission/issues/379 --  the reason extra seeds get added is the already-seeding ones are stalled -- so I'm going to close this as a dupe.

**Closed by ckerr** 2023-02-28 15:51 UTC
Labels: bug, scope:mac
