### ISSUE TITLE
4.0.0-beta: issues with some non-ASCII (Unicode?) files in torrents

### ISSUE THREAD

**Issue by blind-oracle** [transmission/transmission#4025] opened 2022-10-25 07:24 UTC
### What is the issue?

After switching `transmission-daemon` from 3.0 to 4.0-beta all of my torrents were caught up OK but one, though it was 100% downloaded - Transmission stated that it had missing files. After I re-added it - it didn't see the files and started to download again from scratch.

FIles have cyrillic letters in them partially, that's how it looks in web UI:
![image](https://user-images.githubusercontent.com/592248/197708243-e597ada0-deca-40eb-9ccd-c20f546a3377.png)

That's how it looks on the filesystem:
```bash
root@srv:/torrents/Aliens [Чужие]# ls
'Alien I ['$'\327\363\346\356\351'' 1] Director'\''s cut (1979) 1920x818 BDRip -=RbM=- RusEngSubsChpt.mkv'
'Alien II - Aliens ['$'\327\363\346\356\351'' 2] Special Edition (1986) 1920x1038 BDRip -=RbM=- RusEngSubsChpt.mkv'
'Alien II - Aliens [Чужой 2] Special Edition (1986) 1920x1038 BDRip -=RbM=- RusEngSubsChpt.mkv'
'Alien III ['$'\327\363\346\356\351'' 3] Special Edition (1992) 1920x810 BDRip -=RbM=- RusEngSubsChpt.mkv.part'
'Alien III [Чужой 3] Special Edition (1992) 1920x810 BDRip -=RbM=- RusEngSubsChpt.mkv'
'Alien IV - Resurrection ['$'\327\363\346\356\351'' 4 - '$'\302\356\361\352\360\345\370\345\355\350\345''] Special Edition (1997) 1920x818 BDRip -=RbM=- RusEngSubsChpt.mkv.part'
'Alien IV - Resurrection [Чужой 4 - Воскрешение] Special Edition (1997) 1920x818 BDRip -=RbM=- RusEngSubsChpt.mkv'
'Alien I [Чужой 1] Director'\''s cut (1979) 1920x818 BDRip -=RbM=- RusEngSubsChpt.mkv'
```

So it tries to name the files using escaped Unicode code points instead of normal character representation. Strange thing is that I have other torrents with Cyrillic characters and they work fine, only this one fails, hard to say why.

It worked 100% fine in 3.0

Attaching torrent file in question (in .gz since github forbids .torrent)
[problematic_cyrillic.torrent.gz](https://github.com/transmission/transmission/files/9858000/problematic_cyrillic.torrent.gz)

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.0-beta.1+r98cf7d9b3c

**Comment by ri-gilfanov** [comment] 2022-11-18 14:05
@blind-oracle, your torrent also crashes the current nightly build of transmission-gtk 4.0.0-beta.1.dev:
```
(transmission-gtk:426267): Pango-WARNING **: 18:44:23.202: Invalid UTF-8 string passed to pango_layout_set_text()

(transmission-gtk:426267): Pango-WARNING **: 18:44:23.205: Invalid UTF-8 string passed to pango_layout_set_text()

(transmission-gtk:426267): Pango-WARNING **: 18:44:23.206: Invalid UTF-8 string passed to pango_layout_set_text()

(transmission-gtk:426267): Pango-WARNING **: 18:44:23.206: Invalid UTF-8 string passed to pango_layout_set_text()

(transmission-gtk:426267): Pango-WARNING **: 18:44:23.206: Invalid UTF-8 string passed to pango_layout_set_text()

(transmission-gtk:426267): Pango-WARNING **: 18:44:23.206: Invalid UTF-8 string passed to pango_layout_set_text()

(transmission-gtk:426267): Pango-WARNING **: 18:44:23.206: Invalid UTF-8 string passed to pango_layout_set_text()

(transmission-gtk:426267): Pango-WARNING **: 18:44:23.206: Invalid UTF-8 string passed to pango_layout_set_text()

(transmission-gtk:426267): Pango-WARNING **: 18:44:24.679: Invalid UTF-8 string passed to pango_layout_set_text()

(transmission-gtk:426267): Pango-WARNING **: 18:44:24.681: Invalid UTF-8 string passed to pango_layout_set_text()

(transmission-gtk:426267): Pango-WARNING **: 18:44:24.682: Invalid UTF-8 string passed to pango_layout_set_text()

(transmission-gtk:426267): Pango-WARNING **: 18:44:24.684: Invalid UTF-8 string passed to pango_layout_set_text()

(transmission-gtk:426267): Pango-WARNING **: 18:44:24.962: Invalid UTF-8 string passed to pango_layout_set_text()

(transmission-gtk:426267): Gtk-WARNING **: 18:44:24.974: Failed to set text 'Alien II - Aliens [\xd7\xf3\xe6\xee\xe9 2] Special Edition (1986) 1920x1038 BDRip -=RbM=- RusEngSubsChpt.mkv' from markup due to error parsing markup: Ошибка в строке 1 на символе 102: Недопустимый UTF-8 текст в имени — неправильная последовательность «Alien II - Aliens [\xd7\xf3\xe6\xee\xe9 2] Special Edition (1986) 1920x1038 BDRip -=RbM=- RusEngSubsChpt.mkv»

(transmission-gtk:426267): Pango-WARNING **: 18:44:24.977: Invalid UTF-8 string passed to pango_layout_set_text()

(transmission-gtk:426267): Pango-WARNING **: 18:44:24.979: Invalid UTF-8 string passed to pango_layout_set_text()

(transmission-gtk:426267): Pango-WARNING **: 18:44:24.989: Invalid UTF-8 string passed to pango_layout_set_text()

** (transmission-gtk:426267): ERROR **: 18:44:25.592: 
unhandled exception (type std::exception) in signal handler:
what: basic_string::_M_create

Ловушка трассировки/останова (стек памяти сброшен на диск)
```
The following messages appeared in the file `~/.xsession-errors`:
```
Gjs-Message: 18:44:20.139: JS LOG: [LookingGlass/info] Adding systray: transmission-gtk (1x1px)
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x620000c
```
I have several dozen torrents with Cyrillic filenames. However, this problem appeared only in two my torrents.

**Comment by ckerr** [comment] 2023-01-27 15:35
Duplicate of #3442.

**Closed by ckerr** 2023-01-27 15:35 UTC
