### ISSUE TITLE
Firefox opens every new magnet as a new 'transmission.exe' process

### ISSUE THREAD

**Issue by andradadad** [transmission/transmission#1536] opened 2020-11-26 11:04 UTC
Reproduction: click on any magnet with firefox, and transmission will open a new window of transmission.exe with the other still running.
Very dangerous for data, since it could download both at the same time or corrupt profile with list of downloads.

Windows 7 64bits
Firefox 84

**Comment by andradadad** [comment] 2020-12-19 03:21
Anyone?

**Comment by ckerr** [comment] 2022-02-25 20:21
This is a duplicate of https://github.com/transmission/transmission/issues/255

**Closed by ckerr** 2022-02-25 20:21 UTC
Labels: duplicate
