### ISSUE TITLE
All transfers deleted after update

### ISSUE THREAD

**Issue by l-g** [transmission/transmission#891] opened 2019-04-22 21:34 UTC
I had problems using the built in update from 2.9.3 to 2.9.4 so in an attempt to fix it I launched Transmission with sudo from the command line.

I got some welcome messages and the transfer list window's size was different but beyond that everything looked ok. I then updated - which worked fine - followed by relaunching it.

Now the window size and position was back to normal but instead the list of transfers was empty. Restarting didn't change that.

What happened? I had dozens of ongoing transfers I want back.

**Comment by Nikita11790** [comment] 2019-08-18 06:38
sudo is a different user account then your normal user account. dont use sudo and you should have them back

**Comment by l-g** [comment] 2019-08-18 19:19
I didn't use sudo after the relaunch.

**Comment by ckerr** [comment] 2022-01-24 06:10
This should've been triaged ages ago. If this is still an issue, please update the issue with full instructions on how to reproduce the issue -- I'm not sure that I understand how to test this correctly.

**Comment by Coeur** [comment] 2022-11-12 18:48
I'm afraid no action can be taken on this issue without reproduction or clarification.
Since it's too old, I'll close it. Feel free to open a new issue if it happens again with Transmission 4.

**Closed by Coeur** 2022-11-12 18:48 UTC
Labels: bug, needs clarification
