### ISSUE TITLE
Serious memory leak

### ISSUE THREAD

**Issue by nengxu** [transmission/transmission#4786] opened 2023-02-10 00:15 UTC
### What is the issue?

Since early V4.0 beta 1 dev releases, there are always serious memory leak on Windows. Unfortunately, this problem persist with the official V4.0 release. The transmission-qt.exe keeps increasing in RAM usage (more than 500M easily). I have to stay with an old release: transmission-4.0.0-beta.1.dev+r70f623f32b-x64, which does not have memory leak.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.0

**Comment by gramakri** [comment] 2023-02-10 07:23
I can see the same in Ubuntu 22.04 builds. I run transmission in a container. Giving it 1GB makes it run OK but previous versions used to run with 256MB.

**Comment by ckerr** [comment] 2023-02-10 18:22
@gramakri if you're seeing this in Ubuntu 22.04 could you try running it with [heaptrack](https://github.com/KDE/heaptrack) (or some other tool if you have a preferred method) to see where the allocations are coming from, e.g. by sharing the `heaptrack.APP.PID.gz` filef?

**Comment by ckerr** [comment] 2023-02-10 18:30
The problem with triaging an issue like this is there are a lot of ways that it can happen and all three of us may have different configurations and so we may each see different behavior when we test. For that reason I like to try to ask y'all to do as much of the detective work as possible, since you are already able to reproduce the problem locally :smile_cat: 

@gramakri if you're seeing this in Ubuntu 22.04 could you try running it with [heaptrack](https://github.com/KDE/heaptrack) (or some other tool if you have a preferred method) to see where the allocations are coming from, e.g. by sharing the `heaptrack.APP.PID.gz` filef?

@nengxu Just to confirm, the issue you're seeing is _not_ happening in r70f623f32b but _is_ happening in `4.0.0-beta.2`, is that correct? That's the span of about 150 commits. Do you have (or are you willing to build) any of the nightly releases between [r70f623f32b...4.0.0-beta.2] that you can test with to try to narrow down the range even further?

**Comment by nengxu** [comment] 2023-02-10 18:57
@ckerr I've been using many of the beta 1 daily releases after the r70f623f32b one. Every one I tried had the memory leak. I had to revert to the r70f623f32b one repeatedly. The memory leak still persists in the public release of 4.0.0,  I haven't tried any beta 2 or 3 release as I was disappointed by the consistent memory leak.

**Comment by ckerr** [comment] 2023-02-10 19:34
@nengxu I hear what you're saying, but understand what I'm looking for are more clues on how to track this down because I am not seeing this leak when I run transmission locally.

So e.g. I'm trying to figure out the commit range to look at. You say it's not present in r70f623f32b so that's one endpoint. What is the name of the first release where you saw the leak?

**Comment by nengxu** [comment] 2023-02-11 00:29
@ckerr I was following the nightly dev releases closely at that moment. So any beta1 release after the r70f623f32b one could be the culprit. Unfortunately, I don't know how to get those beta1 dev releases now. If you can send me a copy of such release, I would be able to reproduce the problem.

**Comment by nengxu** [comment] 2023-02-11 01:34
@ckerr I installed the nearest release I can get from github: transmission-4.0.0-beta.2+rbceb368f1b-x64.exe. It had the memory leak.

**Comment by ckerr** [comment] 2023-02-11 01:40
```sh
$ git log --oneline '70f623f32b..bceb368f1b' | wc --lines
157
```

157 commits. That's a lot but we can give this a try.

@nengxu if I start completely from scratch with a fresh install of Transmission and  no torrents, what specific steps do I need to follow to test whether or not a version has the leak? Please be as detailed as possible so that I don't bisect through 157 commits looking at the wrong thing :dizzy: 

(Also if you had reported this back in Nov / Dec when you noticed it, those old builds would still be in the CI cache for us to test with. :crying_cat_face:)

**Comment by nengxu** [comment] 2023-02-11 01:47
@ckerr That's my bad. I just downloaded the dev releases, did not realize that project also has github. But from my memory, the memory leak was the reason I had to revert to the old good release every time I triied a new dev release. So it may be safe to check the commits right after the old good one.

If you don't have any torrent, the memory leak may not show up. For now, I have 129 torrents (88 dlowloading). The memory leak is evident.

**Comment by ckerr** [comment] 2023-02-11 01:53
@nengxu what I'm saying is that several times a week I run the build of Transmission through a memory profiler to watch for leaks. If It was as easy as having a 100 torrents I would've seen it months ago; I have a testbed with something like 25,000 torrents and am not seeing it.

This is why I want the instructions to be as explicit as possible, so that I don't bisect through 157 commits looking at the wrong thing :smile_cat: for example if all the torrents are paused does it still happen? How much does it increase over time -- how long do I need to run each build in order to reproduce it? Do I need to download a torrent each time? Do I need to download 88 torrents each time?

You're asking me to look through a lot of versions so please give whatever info would be needed for someone who hasn't seen this bug to be able to reproduce it. :bow:

**Comment by nengxu** [comment] 2023-02-11 01:58
@ckerr My suggestion is to start at the commit right after 70f623f32b, don't use bisect. The memory leak is showing quickly after starting Transmission. You just need to maintain certain number of torrents, some downloading (can set the download speed very low to keep those torrents live), some seeding. I need to reinstall beta2 to see if it still leaks even when all torrents are paused.

**Comment by ckerr** [comment] 2023-02-11 02:13
@nengxu thanks for the info and for the quick responses!

I just had an idea -- would you be willing to test out builds? Here's what I'm thinking: if I made a not-for-merging draft PR that rolls back Transmission to, say, 10 commits after 70f623f, then CI will build that and you can install from the artifact made by the CI run.

Since it's (apparently?) easy for you to test, maybe this would be a productive and mostly-painless way we can figure out where the problem started.

Also, to ask the obvious just to make sure I'm not aiming us in the wrong direction -- 70f623f does _not_ have the leak, correct?

**Comment by nengxu** [comment] 2023-02-11 02:27
@ckerr I just reinstalled beta2, let it running for a while to reach 600+M. Pause all torrents. The RAM usage dropped immediately to round 100M. Then I restart all torrents. RAM usage climbing again.

Yes, I'd be happy to help you.  70f623f32b is not leaking.

**Comment by ckerr** [comment] 2023-02-11 02:30
OK. I am going to be offline for awhile; will get back to you sometime tomorrow with a URL for a build as described two comments up :+1: Thank you!

**Comment by abubaca4** [comment] 2023-02-15 13:49
Also have memory leak
4.0.0 source archive self builded
After install start to verify all my ~280 torrents and ram consumption grow by 500mb
After end of verify memory not freed
![изображение](https://user-images.githubusercontent.com/55701175/219040877-551bd8f6-9ff9-4005-ac1b-f3fec1f6819c.png)
I can't repeat it with checking one big torrent, maby problem caused with specific torrent from my list

And second one I start to download 3 torrents size 30-40Gb
Memory consumption start to unlimited grow and oom kill transmission
Out of memory: Killed process 16379 (transmission-da) total-vm:2329580kB, anon-rss:1610044kB, file-rss:1828kB, shmem-rss:0kB, UID:1000 pgtables:3308kB oom_score_adj:0
After restart download continue without issues

I don't know is it help or not

**Comment by AlexanderCurl** [comment] 2023-02-18 08:13
![image](https://user-images.githubusercontent.com/10440034/219849725-4e7a6599-a64f-41e8-b655-63a07b0df976.png)

**Comment by ckerr** [comment] 2023-02-18 22:08
> 4.0.0 source archive self builded

@abubaca4 ooh nice nice!  I love a tester who knows how to build from source :heart: Could you try making a debug build with the cmake `-DCMAKE_BUILD_TYPE=Debug` option and then reproduce the memory leak while running a session in [heaptrack](https://github.com/KDE/heaptrack)? After that you'll be able to feed the session data in to `heaptarck_gui` to get a flame graph of where the leak is coming from. If all goes well that _should_ lead us right to the problem

**Comment by AlexanderCurl** [comment] 2023-02-19 09:35
@ckerr I built transmission from source 2 day ago from git as well, if you need something, don't hesitate to let me know.
(Although it's on Ubuntu headless install, but compiled everything)

**Comment by abubaca4** [comment] 2023-02-19 11:29
> Could you try

I tried to reproduce case when oom kill transmission but unsuccessfully. Memory consumption grow only from 120mb to 170mb.
I tried to start same three torrents but seeding list has some difference. It running on arm single board so speed of debug version was soo slow and heaptrack file hear 52mb(I leave transmission on night).
https://vault.abubaca4.ml/#/send/oys0ek4hSUm8yxXmAYU-4Q/fzfT7ESU2NT9BgIfRcskOw

Now I started trying to reproduce second one when I has 700mb ram consumption after all library verify.

**Comment by ckerr** [comment] 2023-02-19 13:01
@AlexanderCurl same request, basically -- heaptrack so that we can see a flame graph of where memory is getting used. If all goes well, that should tell us exactly where any problem lies...

**Comment by ckerr** [comment] 2023-02-19 13:24
Ok not a leak per se but I see blocklists use a _lot_ of space -- in @abubaca4's link above, it's >700 MB, >80% of memory used by Transmission. I've opened a new ticket #4949 to track that.

**Comment by abubaca4** [comment] 2023-02-19 13:44
> I think that's consistent with the 700 MB you're talking about in that comment.

No, usualy Transmission take 120-170mb with blocklist enabled. But one time I get error from #3442 an starting to verify all my torrents. After than complete I got 704 mb consumption as on screenshot.
Link to blocklist https://github.com/Naunter/BT_BlockLists


> (`heaptrack_gui` > caller / callee tab > sort by leaked)

In that single board I haven't gui at all. My main pc is on windows. I can make virtual machine or run linux in live mode but I think will be faster if I just upload result file.

**Comment by ckerr** [comment] 2023-02-19 13:56
> No, usualy Transmission take 120-170mb with blocklist enabled. But one time I get error from https://github.com/transmission/transmission/issues/3442 an starting to verify all my torrents. After than complete I got 704 mb consumption as on screenshot.

I think I am misunderstanding what you're telling me? The heaptrack session you sent me is real clear on this; it shows that the blocklist is taking 717 MB, nothing to do with 3442:

![flame-graph](https://user-images.githubusercontent.com/70381/219952679-e2f1f179-9de4-429b-8cc9-39cf0c612462.png)

If there is a separate memory hole unrelated to blocklists, please do make a new heaptrack log so that I can see it. I'm happy to fix as many bugs as we can find :smile_cat:

**Comment by ckerr** [comment] 2023-02-19 14:03
@abubaca4 which blocklist from that repo are you using?

**Comment by abubaca4** [comment] 2023-02-19 14:18
> @abubaca4 which blocklist from that repo are you using?

https://github.com/Naunter/BT_BlockLists/releases/download/v.1/bt_blocklists.gz

Don't know about peak but right now(verifying all 284 torrents) and usual use htop show no more than 170mb consumption 
![изображение](https://user-images.githubusercontent.com/55701175/219953514-572e4382-0a42-422a-8878-32a65b32abf1.png)
![изображение](https://user-images.githubusercontent.com/55701175/219953527-6682f438-9d2d-4fb4-a762-79303842fbd8.png)
Maybe peak is 700mb while parsing but I don't see it by system tools
I can make shot heaptrack just about time when blocklist enabling

**Comment by ckerr** [comment] 2023-02-19 14:35
OK whoever is building from source, https://github.com/transmission/transmission/pull/4953 has a one-liner that should fix the blocklist memory issue. If you're using `4.0.0` from tarball, you may want to apply that line by hand. If you're building from git, I'll merge this into `main` as soon as it passes CI.

**Comment by GaryElshaw** [comment] 2023-02-19 14:42
Note to self when learning to code: Are there enough, or is there any such thing as too much cow-bell/braces.

**Comment by ckerr** [comment] 2023-02-19 14:45
> Note to self when learning to code: Are there enough, or is there any such thing as too much cow-bell/braces.

https://www.reddit.com/r/ProgrammerHumor/comments/7sk1rx/a_spy_manages_to_steal_the_last_50mb_of_the_lisp/

**Comment by ckerr** [comment] 2023-02-19 14:47
I'm leaving this ticket open in case anyone else has heaptrack traces they want to submit.

Shaving 756 MB off of Transmission's runtime is what call a pretty productive morning! I'm happy to keep the ball rolling if anyone else has heaptrack logs :smile_cat:

**Comment by abubaca4** [comment] 2023-02-19 18:23
Look like verify all not give nothing new
But I give [file](https://vault.abubaca4.ml/#/send/nLShkk6gT9alrNxARmTZIg/C0Jn0I_SuCFSo5TLuHu_xg) because I spent 7 hours to make it
Maybe problem was I use -DCMAKE_BUILD_TYPE=Release instead of -DCMAKE_BUILD_TYPE=RelWithDebInfo, but I can't reproduce it with debug build
Hope someone can do this
@ckerr I think do less size field for ipv4 rules still good idea but it has low priority

**Comment by ckerr** [comment] 2023-02-19 18:46
Yep that second snapshot is very similar to the first, 717MB in the blocklist.

**Comment by abubaca4** [comment] 2023-02-19 19:09
> Yep that second snapshot is very similar to the first, 717MB in the blocklist.

It's offtop but you really need libdeflate 1.10? Debian 11 contains only 1.7 so I can't use system package

**Comment by ckerr** [comment] 2023-02-19 21:26
@abubaca4 I don't remember why the minimum was raised to 1.10. I'd say try changing it to 1.7 in CMakeLists.txt and see how it goes 🤷 

If 1.7 works LMK; I'd like it to build out-of-the-box-box in Debian 11

**Comment by abubaca4** [comment] 2023-02-19 23:23
> I'd say try changing it to 1.7 in CMakeLists.txt and see how it goes 🤷

I don't now what's up but when I set 1.7 it still can't found
`Could NOT find DEFLATE (missing: DEFLATE_VERSION) (Required is at least version "1.7")`
libdeflate-dev/stable,now 1.7-1 and libdeflate0/stable,now 1.7-1 installed
So I installed backport version of deflate and returned version in CMake
`libdeflate0:arm64 (1.10-2~bpo11+1) libdeflate-dev:arm64 (1.10-2~bpo11+1)`
But CMake still can't found deflate
`Could NOT find DEFLATE (missing: DEFLATE_VERSION) (Required is at least version "1.10")`

What's wrong? With other dependencies I just install -dev package and all work

**Comment by ckerr** [comment] 2023-02-20 00:51
Try just esiting CMakeLists.txt in thr top.directory, find the deflate line that says 1.10, and change it to 1.7

Cc @GaryElshaw next time you get mad at me for not bumping a dependency I am going to think of this convo 😸

**Comment by GaryElshaw** [comment] 2023-02-20 04:37
And i'll blame Debian for not keeping up :-)

**Comment by abubaca4** [comment] 2023-02-20 12:22
> Try just esiting CMakeLists.txt in thr top.directory, find the deflate line that says 1.10, and change it to 1.7

I change version in this line https://github.com/transmission/transmission/blob/main/CMakeLists.txt#L34
1) I try to set 1.7 but cmake can't found deflate `Could NOT find DEFLATE (missing: DEFLATE_VERSION) (Required is at least version "1.7")`
2) I look how cmake searching deflate in https://github.com/transmission/transmission/blob/main/cmake/FindDEFLATE.cmake and found coment about it `# pkg-config support added in libdeflate v1.9`. I think it mean that cmake can't found version erliaer than 1.9
3) So I found version 1.10 in bullseye-backports and install it. But cmake still can't found it(no matter I set 1.7 1.9 or 1.10)

So I think something bad with searching deflate library
It not matter a lot but I has that trouble

**Comment by nengxu** [comment] 2023-02-20 15:55
Thanks for all the progress. Though I don't use any blocklist, and I'm on Windows. I can try the new version which has the blocklist fix. But how can I get it for Windows?

**Comment by AlexanderCurl** [comment] 2023-02-20 18:57
Commit: c5b1df0

![image](https://user-images.githubusercontent.com/10440034/220181726-2047ba66-feee-4735-9aae-646661163965.png)

This should contain the fix above, but doesn't seem to work yet.

**Comment by mikedld** [comment] 2023-02-20 20:05
@abubaca4, this should fix it: https://github.com/transmission/transmission/pull/4607#issuecomment-1385860737. Feel free to open a PR with both this and downgrade to 1.7 (if that works out; it builds fine for me, but I didn't test if it works).

**Comment by abubaca4** [comment] 2023-02-20 23:59
> It looks like transmission keeps a load of data cached, as the main process uses "only" 1.5GB of ram.

I think you should only look at RES and SHR memory consumption 
virt can be very big it's not mean that app really use it
![изображение](https://user-images.githubusercontent.com/55701175/220214663-212bdb8a-fd27-4134-99cd-e5fa4c0c729e.png)
First google [link](https://serverfault.com/questions/138427/what-does-virtual-memory-size-in-top-mean) about virt memory
I think it's just memory mapped files and system free this memory as fast as it required by other app

**Comment by ckerr** [comment] 2023-02-21 02:23
> Thanks for all the progress. Though I don't use any blocklist, and I'm on Windows. I can try the new version which has the blocklist fix. But how can I get it for Windows?

@nengxu nightly builds at https://transmissionbt.com/ ... also 4.0.1 is scheduled for Wednesday

> It looks like transmission keeps a load of data cached, as the main process uses "only" 1.5GB of ram.

:+1: on what @abubaca4 said about RES / SHR / VIRT said. One [useful description](https://serverfault.com/a/138625):

> Virtual memory isn't even necessarily memory. For example, if a process memory-maps a large file, the file is actually stored on disk, but it still takes up "address space" in the process.
>
> Address space (ie. virtual memory in the process list) doesn't cost anything; it's not real. What's real is the RSS (RES) column, which is resident memory. That's how much of your actual memory a process is occupying.

Anyway @AlexanderCurl if you think Transmission is using too much memory you could follow the suggestions above with heaptrack and we can find out where the memory is being  used :bow: This is the single most useful thing for helping track down any actual improper memory use.

**Comment by AlexanderCurl** [comment] 2023-02-21 07:19
Cool, I will do this week some time later.

**Comment by nengxu** [comment] 2023-02-21 07:35
@ckerr I installed transmission-4.0.0-dev+r6a185634b0. Now with 84 downloading, 135 torrents in total, RAM stayed around 142.34MB.

**Comment by ckerr** [comment] 2023-02-23 00:26
I'm closing this issue since [4.0.1 has been released](https://github.com/transmission/transmission/releases/tag/4.0.1). If y'all are still seeing memory problems please file new tickets with heaptrack logs. They're amazingly helpful.

**Closed by ckerr** 2023-02-23 00:26 UTC
Labels: bug, needs clarification, scope:qt, needs confirmation, needs testers
