### ISSUE TITLE
Seemingly random reordering of torrents

### ISSUE THREAD

**Issue by juman123** [transmission/transmission#5970] opened 2023-09-03 06:25 UTC
### What is the issue?

Transmission 4.0.x reorders torrents seemingly randomly, at least on re-starting the app, but maybe even other times too.

Since the Dawn of Time, torrents appeared in the order they had been added, which makes a lot of sense, since that way the torrents you're most interested in will be found at the very bottom of the list.

Please restore the old, sensible behaviour.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.4

**Comment by killemov** [comment] 2023-09-03 07:50
> Since the Dawn of Time, torrents appeared in the order they had been added, which makes a lot of sense, since that way the torrents you're most interested in will be found at the very bottom of the list.

Maybe for macOS it might have been in some correct order, but for the other clients it has always been any other order than date added. AFAIK the torrents are ordered in the way they are encountered on disk on startup. I even made a queue reordering function in [Shift](https://github.com/killemov/Shift) especially for this.

**Comment by juman123** [comment] 2023-09-03 07:54
> AFAIK the torrents are ordered in the way they are encountered on disk on startup.

So is that basically "random order" in practice?

But really, the ordering was the same (last added last) for ages, since I started using Transmission. AFAIK it's always been the same for any Torrent client.. but now it's different at least with Transmission.

What changed and why?

**Comment by GaryElshaw** [comment] 2023-09-03 07:59
Did you upgrade Transmission? Don't forget you can change the order by going to View --> Sort Transfers By.

**Comment by juman123** [comment] 2023-09-03 08:02
Wow, excellent tip :)

I never even knew that was an option, because I never felt like changing the default ordering.

Thanks!

**Comment by ckerr** [comment] 2023-09-03 23:30
Duplicate of https://github.com/transmission/transmission/issues/327

**Closed by ckerr** 2023-09-03 23:30 UTC
