### ISSUE TITLE
Speed limit not working since v4 update

### ISSUE THREAD

**Issue by KirenJames7** [transmission/transmission#4797] opened 2023-02-10 17:06 UTC
### What is the issue?

I've been using Transmission for a long time, recently updated to version 4, but speed limit doesn't seem to be working and overriding globsl bandwidth.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0 (280ace12f8)

**Comment by ckerr** [comment] 2023-02-10 20:25
Duplicate of https://github.com/transmission/transmission/issues/4701

**Closed by ckerr** 2023-02-10 20:25 UTC
