### ISSUE TITLE
Windows daemon does not obey speed limit

### ISSUE THREAD

**Issue by SNBogdanov** [transmission/transmission#4988] opened 2023-02-22 12:14 UTC
### What is the issue?

After installing transmission-4.0.0-dev+r9d1a141482-x64.msi transmission daemon does not obey speed limits. I set up 2 MB/s limit but daemon downloaded files at 3-5 MB/s (my provider limit is 5MB/s)

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

transmission-4.0.0-dev+r9d1a141482-x64.msi

**Comment by ckerr** [comment] 2023-02-22 12:43
Hi @SNBogdanov, thanks for reporting this.

I think this is a duplicate of https://github.com/transmission/transmission/issues/4701 so I'm going to close this as a dupe.

**Closed by ckerr** 2023-02-22 12:43 UTC
