### ISSUE TITLE
Listening port check does not work

### ISSUE THREAD

**Issue by escalade** [transmission/transmission#392] opened 2017-08-30 09:13 UTC
It works fine in 2.92, but when using latest master (0378ee8) it does not.

**Comment by MoBattah** [comment] 2017-11-12 03:25
Can you provide any more information? 

To get it right, this is in regards to checking port status in the gtk settings panel?

**Comment by escalade** [comment] 2017-11-12 22:17
Sorry, should have been more specific. I haven't tested the GTK version, this is regarding the port status in the web settings panel. It says closed, but it's correctly forwarded through UPnP.

**Comment by MoBattah** [comment] 2017-11-13 07:21
Is your IP v4 or v6?

**Comment by escalade** [comment] 2017-11-13 12:10
It's IPv4, I've also tested with ipv6.disable=1 as kernel option to exclude any IPv6 issue.

**Comment by bunder** [comment] 2020-04-25 16:08
Do you use proxy or several IP addresses?

**Comment by txVLN** [comment] 2021-12-19 04:07
Looks like there's several copies of this issue. Here's the one with the most activity: https://github.com/transmission/transmission/issues/407

**Comment by ckerr** [comment] 2022-02-25 03:48
Duplicate of #407

**Closed by ckerr** 2022-02-25 03:48 UTC
