### ISSUE TITLE
Magnetic links added but not started in Transmission 3 disappear in Transmission 4 beta 3

### ISSUE THREAD

**Issue by WowbaggersLiquidLunch** [transmission/transmission#4728] opened 2023-02-06 22:46 UTC
### What is the issue?

As title.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0-beta.3 (634b1e8fc1)

**Comment by ckerr** [comment] 2023-02-06 22:50
Duplicate of https://github.com/transmission/transmission/issues/4295

**Closed by ckerr** 2023-02-06 22:50 UTC
Labels: duplicate
