### ISSUE TITLE
Adding trackers via Transmission Web

### ISSUE THREAD

**Issue by lewri** [transmission/transmission#6756] opened 2024-03-29 17:08 UTC
### What is the issue?

As recommended, forwarding into an enhancement request based on discussion #6727 as it does not exist yet:

I have always been a user of transmission with web interface over the years on single board devices (even if I'm currently not using one). I do greatly enjoy it!

However, from what I can see I can't actually find a list of function or feature changes (if any) for **adding trackers via the web interface**. I believe the readme file for Web is still targeting older versions: https://github.com/transmission/transmission/blob/main/docs/Web-Interface.md

Currently I use a modified version of the web interface with https://github.com/54mv39/web as this is still compatible on 3.00-20,I have hesitated moving to version 4 as I don't believe this modification is compatible. An image just to show how the modified interface acts:
![image](https://github.com/transmission/transmission/assets/20030128/f2000585-da3e-4b0c-ac97-3d142dbf36f8)

### Which application of Transmission?

Web client

### Which version of Transmission?

[3.00 (bb6b5a062e)] / 3.00-20 (SynoCommunity Port for Synology NAS)

**Comment by killemov** [comment] 2024-03-30 09:31
As stated in #6727, you could have done this with a web-UI by using [Shift](https://github.com/killemov/Shift) instead of the stock web-UI and an external piece of software.

**Comment by lewri** [comment] 2024-03-30 13:27
> As stated in #6727, you could have done this with a web-UI by using [Shift](https://github.com/killemov/Shift) instead of the stock web-UI and an external piece of software.

Just to reaffirm from the discussion -- I'm merely asking about a feature request to the in-house system rather than 3rd party.

**Comment by killemov** [comment] 2024-04-03 08:40
Duplicate of #5234

**Comment by killemov** [comment] 2024-04-03 08:54
@ckerr [I  am painfully aware](https://forum.transmissionbt.com/viewtopic.php?p=68740#p68740). I give the TS the option to use this functionality NOW but he opts to wait for it to be implemented by the TM-devs instead. This gives us a sense of the urgency of this feature request. Also, he is a long time user of the web-UI, why now? More dead trackers since May 31, 2023?

**Comment by lewri** [comment] 2024-04-06 16:10
I agree with killemov here in that this issue does closely align with #5234 (they both ideally want to achieve the same thing). I'm happy to have this one merged into that issue instead if you like -- perhaps adding the terms add/remove may be helpful to reduce other duplicates like this one. But I'm not precious; no matter what I'm just glad for the project being here.

I'll also append the other issue to the discussion for visibility again as part of the main post 👍

**Comment by Pentaphon** [comment] 2024-04-11 20:26
@ckerr dupe of https://github.com/transmission/transmission/issues/5234

**Closed** 2024-04-18 07:59 UTC
Labels: scope:web, pr welcome, type:feat
