### ISSUE TITLE
MacOS 3.00+ (749bb591fb) crash accessing Message Log

### ISSUE THREAD

**Issue by GScottElshaw** [transmission/transmission#2760] opened 2022-03-12 00:59 UTC
[3.00+ (749bb591fb) crash.txt](https://github.com/transmission/transmission/files/8236694/3.00%2B.749bb591fb.crash.txt)

**Comment by ckerr** [comment] 2022-03-12 16:42
Thanks for the crash report! I think this is a duplicate of #2759 but it's helpful to have the crash report too :+1:

**Closed by ckerr** 2022-03-12 16:42 UTC

**Comment by GScottElshaw** [comment] 2022-03-12 16:46
Oh, you saw those are two separate builds, yes?
