### ISSUE TITLE
Set download path to .torrent file location

### ISSUE THREAD

**Issue by mike-kasianov** [transmission/transmission#1683] opened 2021-04-28 13:47 UTC
On macos there is an option to set download path to the place where .torrent file is located. It is super handy, but I didn't find this option on Linux.
I checked gtk and qt interfaces but didn't find this option.
Also I didn't find any config parameter I can set manually into settings.json to reach such behavior.
It would be great to have this feature on Linux.

Thanks.

**Comment by InfiniteProductions** [comment] 2022-01-22 09:45
On windows version at least, there is this option:

> "open-dialog-dir": "C:\\Users\\<username>"

which looks like to match what you're looking for.
There is no preferences item (yet) to set it, so it needs to be modified directly in the JSON pref file.

**Comment by ckerr** [comment] 2023-02-01 06:58
Duplicate of #720

**Closed by ckerr** 2023-02-01 06:58 UTC
Labels: enhancement, scope:gtk, scope:qt, feature disparity, pr welcome
