### ISSUE TITLE
[WebUI] scheduled times don't get saved/applied

### ISSUE THREAD

**Issue by arthemis95** [transmission/transmission#5194] opened 2023-03-10 23:07 UTC
### What is the issue?

Times set under the speed tab in the preferences don't get saved/applied. (see picture)

![image](https://user-images.githubusercontent.com/18481868/224442920-8ac3f17a-3210-4194-b66d-c1105dcd4d31.png)

For example, if I change the "from" time to 8:45, and then check the "Scheduled times" checkbox, or change the speed limits, it reverts to the default 9:00.

I can't definitively say if this is a pure UI bug, or if the feature is not working at the moment, but rudimentary testing seems to indicate it doesn't work at all. I've tried to test it by setting the alternative speed limits to zero, setting the time to something <15 min in the future, and waiting for the download speed to change once it passed the set time. Which it didn't. I haven't yet been able to test if the scheduled alternative limits work with the default time however.

### Which application of Transmission?

Web client

### Which version of Transmission?

e1c6e1be43 inside a docker container

**Comment by ckerr** [comment] 2023-03-11 01:40
Hi @arthemis95 thanks for reporting this!

I think this is a duplicate of https://github.com/transmission/transmission/issues/5009 so I'm going to close this ticket as a dupe.

5009 is fixed by 
https://github.com/transmission/transmission/pull/5033, which will be included in next week's 4.0.2 release.

Thanks again!

**Closed by ckerr** 2023-03-11 01:40 UTC
