### ISSUE TITLE
Magnet link info is not downloaded after adding

### ISSUE THREAD

**Issue by SNBogdanov** [transmission/transmission#4989] opened 2023-02-22 12:18 UTC
### What is the issue?

In release 4.0 new feature were added. Magnet link download can download info regadless of start torrent checkbox.
But it were bug about this feature. Torren updated info but then went to paused state (even if I checked start).
in transmission-4.0.0-dev+r9d1a141482-x64.msi torrent info did not updated for magnet link. But torrent added in state which I set up while adding.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

transmission-4.0.0-dev+r9d1a141482-x64.msi

**Comment by ckerr** [comment] 2023-02-22 12:41
Hwy @SNBogdanov, thanks for reporting this.

I think this is a duplicate of https://github.com/transmission/transmission/issues/4740 so I'm closing this one as a dupe.

This fix will be included in `4.0.1`.

**Closed by ckerr** 2023-02-22 12:41 UTC
