### ISSUE TITLE
Nightly crash in peer_stat_helpers

### ISSUE THREAD

**Issue by dantearmok** [transmission/transmission#6262] opened 2023-11-17 04:39 UTC
### What is the issue?

Mac mini (late 2012, 2.5-GHz 4-Core i5), 16GB RAM, plus an assortment of USB & FW HDs.
macOS Ventura 13.6.1 (w/OCLP 1.1.0), PeakHour 4.1.16, PIA 3.5.1, and Xcode 15.0.1.

Running Transmission-f8c544397a Build #9438 (Nov 16, 2023, 12:54:40 AM)

Ran for quite a few hours before punting....

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Transmission [46599]
Path:                  /Users/USER/*/Transmission.app/Contents/MacOS/Transmission
Identifier:            org.m0k.transmission
Version:               4.1.0-dev (14714.4.1.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-11-16 23:25:58.9403 -0500
OS Version:            macOS 13.6.1 (22G313)
Report Version:        12
Anonymous UUID:        9D83084F-22F2-20FB-B0D2-056E94905F2F

Time Awake Since Boot: 180000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00007ff845230290
Exception Codes:       0x0000000000000002, 0x00007ff845230290

Termination Reason:    Namespace SIGNAL, Code 10 Bus error: 10
Terminating Process:   exc handler [46599]

VM Region Info: 0x7ff845230290 is in 0x7ff84522cd00-0x7ff845230460;  bytes after start: 13712  bytes before end: 463
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      unused __TEXT            7ff84522ccf8-7ff84522cd00 [     8] r--/rw- SM=COW  ...ed lib __TEXT
--->  __DATA_CONST             7ff84522cd00-7ff845230460 [   14K] r--/rw- SM=COW  ...bc++abi.dylib
      __DATA_CONST             7ff845230460-7ff8452328c8 [    9K] r--/rw- SM=COW  ..._kernel.dylib

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	    0x7ff845230290 vtable for __cxxabiv1::__class_type_info + 16
1   Transmission                  	       0x1030858f4 (anonymous namespace)::peer_stat_helpers::get_peer_stats(tr_peerMsgs const*, long, unsigned long long) + 82 (peer-mgr.cc:1630) [inlined]
2   Transmission                  	       0x1030858f4 auto tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_5::operator()<tr_peerMsgs>(tr_peerMsgs const*) const + 82 (peer-mgr.cc:1742) [inlined]
3   Transmission                  	       0x1030858f4 tr_peer_stat* std::__1::transform<std::__1::__wrap_iter<tr_peerMsgs* const*>, tr_peer_stat*, tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_5>(std::__1::__wrap_iter<tr_peerMsgs* const*>, std::__1::__wrap_iter<tr_peerMsgs* const*>, tr_peer_stat*, tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_5) + 116 (transform.h:29) [inlined]
4   Transmission                  	       0x1030858f4 tr_peerMgrPeerStats(tr_torrent const*, unsigned long*) + 301 (peer-mgr.cc:1738)
5   Transmission                  	       0x102faea6f -[Torrent peers] + 59 (Torrent.mm:938)
6   Transmission                  	       0x103001036 -[InfoPeersViewController updateInfo] + 1260 (InfoPeersViewController.mm:162)
7   Transmission                  	       0x102fc5404 -[InfoWindowController updateInfoStats] + 48 (InfoWindowController.mm:469)
8   Transmission                  	       0x102f7cabf -[Controller updateUI] + 904 (Controller.mm:2324)
9   Foundation                    	    0x7ff8064fe716 __NSFireTimer + 67
10  CoreFoundation                	    0x7ff8056eeb42 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
11  CoreFoundation                	    0x7ff8056ee6bf __CFRunLoopDoTimer + 807
12  CoreFoundation                	    0x7ff8056ee2da __CFRunLoopDoTimers + 285
13  CoreFoundation                	    0x7ff8056d47b8 __CFRunLoopRun + 2210
14  CoreFoundation                	    0x7ff8056d38bc CFRunLoopRunSpecific + 560
15  HIToolbox                     	    0x7ff80f61ef3d RunCurrentEventLoopInMode + 292
16  HIToolbox                     	    0x7ff80f61ed4e ReceiveNextEventCommon + 657
17  HIToolbox                     	    0x7ff80f61eaa8 _BlockUntilNextEventMatchingListInModeWithFilter + 64
18  AppKit                        	    0x7ff8086cf25c _DPSNextEvent + 858
19  AppKit                        	    0x7ff8086ce106 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1214
20  AppKit                        	    0x7ff8086c0788 -[NSApplication run] + 586
21  AppKit                        	    0x7ff8086949a1 NSApplicationMain + 817
22  Transmission                  	       0x102f6be9f main + 73 (main.mm:17)
23  dyld                          	    0x7ff8052a041f start + 1903

Thread 1:
0   libsystem_malloc.dylib        	    0x7ff8054304a9 small_free_list_remove_ptr_no_clear + 257
1   libsystem_malloc.dylib        	    0x7ff80542dc79 free_small + 847
2   Transmission                  	       0x103091cf3 tr_swarm::remove_peer(tr_peerMsgs*) + 231 (peer-mgr.cc:386)
3   Transmission                  	       0x10308708f (anonymous namespace)::disconnect_helpers::close_bad_peers(tr_swarm*, long, small::vector<tr_peerMsgs*, 512ul, std::__1::allocator<tr_peerMsgs*>, std::__1::integral_constant<bool, true>, unsigned long, std::__1::ratio<3l, 2l>>&) + 1740 (peer-mgr.cc:2133) [inlined]
4   Transmission                  	       0x10308708f tr_peerMgr::reconnect_pulse() + 2109 (peer-mgr.cc:2203)
5   Transmission                  	       0x10308884e tr_peerMgr::bandwidth_pulse() + 162 (peer-mgr.cc:2261)
6   Transmission                  	       0x103120c03 event_persist_closure + 210 (event.c:1623) [inlined]
7   Transmission                  	       0x103120c03 event_process_active_single_queue + 1121 (event.c:1682)
8   Transmission                  	       0x10311daa3 event_process_active + 220 [inlined]
9   Transmission                  	       0x10311daa3 event_base_loop + 1134 (event.c:2006)
10  Transmission                  	       0x10306eba5 tr_session_thread_impl::sessionThreadFunc(event_base*) + 87 (session-thread.cc:239)
11  Transmission                  	       0x10306ef77 decltype(*static_cast<tr_session_thread_impl*>(fp0).*fp(static_cast<event_base*>(fp1))) std::__1::__invoke<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, void>(void (tr_session_thread_impl::*&&)(event_base*), tr_session_thread_impl*&&, event_base*&&) + 30 (type_traits:3859) [inlined]
12  Transmission                  	       0x10306ef77 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, 2ul, 3ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>&, std::__1::__tuple_indices<2ul, 3ul>) + 30 (thread:287) [inlined]
13  Transmission                  	       0x10306ef77 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>>(void*) + 63 (thread:298)
14  libsystem_pthread.dylib       	    0x7ff8055fa1d3 _pthread_start + 125
15  libsystem_pthread.dylib       	    0x7ff8055f5bd3 thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	    0x7ff8055bdfae __semwait_signal + 10
1   libsystem_c.dylib             	    0x7ff8054b0585 nanosleep + 196
2   libc++.1.dylib                	    0x7ff8055435b4 std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>> const&) + 73
3   Transmission                  	       0x1030b6aae void std::__1::this_thread::sleep_for<long long, std::__1::ratio<1l, 1000l>>(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l>> const&) + 17 (thread:386) [inlined]
4   Transmission                  	       0x1030b6aae tr_web::Impl::curlThreadFunc() + 448 (web.cc:713)
5   Transmission                  	       0x1030b6d25 decltype(*static_cast<tr_web::Impl*>(fp0).*fp()) std::__1::__invoke<void (tr_web::Impl::*)(), tr_web::Impl*, void>(void (tr_web::Impl::*&&)(), tr_web::Impl*&&) + 26 (type_traits:3859) [inlined]
6   Transmission                  	       0x1030b6d25 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*>&, std::__1::__tuple_indices<2ul>) + 26 (thread:287) [inlined]
7   Transmission                  	       0x1030b6d25 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*>>(void*) + 59 (thread:298)
8   libsystem_pthread.dylib       	    0x7ff8055fa1d3 _pthread_start + 125
9   libsystem_pthread.dylib       	    0x7ff8055f5bd3 thread_start + 15

Thread 3:
0   libsystem_kernel.dylib        	    0x7ff8055c01de kevent + 10
1   Transmission                  	       0x10301463c -[VDKQueue watcherThread:] + 203 (VDKQueue.mm:189)
2   Foundation                    	    0x7ff8064b85d3 __NSThread__start__ + 1009
3   libsystem_pthread.dylib       	    0x7ff8055fa1d3 _pthread_start + 125
4   libsystem_pthread.dylib       	    0x7ff8055f5bd3 thread_start + 15

Thread 4:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff8055bb5a2 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff8055c971d mach_msg2_internal + 78
2   libsystem_kernel.dylib        	    0x7ff8055c25d4 mach_msg_overwrite + 692
3   libsystem_kernel.dylib        	    0x7ff8055bb88a mach_msg + 19
4   CoreFoundation                	    0x7ff8056d59e0 __CFRunLoopServiceMachPort + 145
5   CoreFoundation                	    0x7ff8056d446b __CFRunLoopRun + 1365
6   CoreFoundation                	    0x7ff8056d38bc CFRunLoopRunSpecific + 560
7   AppKit                        	    0x7ff80882f3f5 _NSEventThread + 132
8   libsystem_pthread.dylib       	    0x7ff8055fa1d3 _pthread_start + 125
9   libsystem_pthread.dylib       	    0x7ff8055f5bd3 thread_start + 15

Thread 5:
0   libsystem_pthread.dylib       	    0x7ff8055f5bb0 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	    0x7ff8055f5bb0 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	    0x7ff8055f5bb0 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	    0x7ff8055f5bb0 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	    0x7ff8055f5bb0 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00000001031d5c90  rbx: 0x00006000035f02b8  rcx: 0x0000000000000010  rdx: 0xffffffffffffffd0
  rdi: 0x00007ff7bcf94c10  rsi: 0x00007fe1c7e3a800  rbp: 0x00007ff7bcf94d30  rsp: 0x00007ff7bcf94c08
   r8: 0x00000000000007d0   r9: 0x0000000000000000  r10: 0x0000000000000007  r11: 0xffffffea0bdc3be0
  r12: 0x00007fe1c7e3a800  r13: 0x0000018bdb874b8a  r14: 0x00007fe1c8d588e0  r15: 0x000000006556eb1a
  rip: 0x00007ff845230290  rfl: 0x0000000000010287  cr2: 0x00007ff845230290
  
Logical CPU:     3
Error Code:      0x00000015 (invalid protections for user instruction read)
Trap Number:     14

### Which application of Transmission?

macOS app

### Which version of Transmission?

Transmission-f8c544397a Build #9438 (Nov 16, 2023, 12:54:40 AM)

**Comment by ckerr** [comment] 2023-11-17 05:15
Hey @dantearmok, thanks for reporting this. This is a duplicate of #59853 and may be fixed by #5992.

**Closed by ckerr** 2023-11-17 05:15 UTC
