### ISSUE TITLE
[WEB] web UI does not use drag + drop

### ISSUE THREAD

**Issue by killemov** [transmission/transmission#4012] opened 2022-10-23 07:38 UTC
https://github.com/transmission/transmission/blob/f0a0b855c6a475acc7cf79e690752511b9ca9916/web/public_html/index.html#L215

Maybe use a drop handler on the body element instead? If I drop a torrent or a magnet on the page I want it added. I would not want a specific drop-area or even worse: a dialog to be opened before I can drop items. See [Shift](https://github.com/killemov/Shift) for inspiration.

**Comment by killemov** [comment] 2023-01-11 23:15
Just did a small test with 4.0.0-beta.3+r634b1e8fc1 with the iframe removed from index.html and it still works. So why is the iframe there?

**Comment by ckerr** [comment] 2023-01-12 00:18
> Just did a small test with 4.0.0-beta.3+r634b1e8fc1 with the iframe removed from index.html and it still works. So why is the iframe there?

Do you see the `pr welcome` and `good first issue` labels I added three months ago...? :smiley_cat:

**Comment by killemov** [comment] 2023-01-12 13:54
Yes, but should it not be a good second issue OR a first good issue? :sweat_smile:

But there is question in my previous post that needs an answer.  If you (@ckerr) are not the maintainer of the web UI, then please @dareiff or @FluxState, take a stab at it.

**Comment by ckerr** [comment] 2023-02-27 16:05
Good catch. @killemov this looks like a duplicate of 670?

**Comment by killemov** [comment] 2023-02-27 22:05
Somewhat duplicate, the other issue discusses the "how" UX-wise. This one gives a working example (No dialog by default, just add and upload.) and point out that there is an unused element in the HTML.

**Comment by ckerr** [comment] 2023-02-27 23:22
Closing as a duplicate of #670 but @dareiff ^ FYI about the unused element

**Closed** 2023-02-27 23:23 UTC
Labels: scope:web, pr welcome, good first issue, type:feat, type:ui
