### ISSUE TITLE
Stalled at 99% but there is no more .part suffix in any of the files

### ISSUE THREAD

**Issue by fulalas** [transmission/transmission#4986] opened 2023-02-22 05:24 UTC
### What is the issue?

This new version 4.0.0 introduced a few issues. On Slackware 15.0 x64, a given torrent is stalled at 99% but it's either 100% downloaded or the .part suffix has been removed before it reached 100% (because it's a video, I can't really tell).

Also, why the binaries size increased by like 4 to 5 times (regardless of the distro)?

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.0

**Comment by ckerr** [comment] 2023-02-22 10:24
Hi @fulalas,, thanks for reporting this.

I think this is a duplicate of #4891, so I'm going to close this one as a dupe.

This fix will be included in `4.0.1`. :smile_cat:

**Closed by ckerr** 2023-02-22 10:24 UTC
