### ISSUE TITLE
Magnet links pause after downloading metadata for no reason

### ISSUE THREAD

**Issue by robd003** [transmission/transmission#2266] opened 2021-12-04 05:27 UTC
For some reason after submitting a magnet link to transmission it will download the metadata and then pause without starting to download the files.

I find this really annoying when trying to sync files remotely as I have to wait for the metadata download to happen (can take a while with DHT magnet links) and then manually click resume on the torrent.

Example magnet link: magnet:?xt=urn:btih:3057ad5d5df45fe07dbcbca184ec4276d3068a2e&dn=ubuntu-20.04.3-live-server-amd64.iso

**Comment by sweetppro** [comment] 2021-12-04 07:52
I get crashing with build #7419:
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Transmission [41823]
Path:                  /Applications/Transmission.app/Contents/MacOS/Transmission
Identifier:            org.m0k.transmission
Version:               3.00+ (14714.3.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2021-12-04 08:50:11.1794 +0100
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Anonymous UUID:        FB981302-784B-58FE-8C47-7DCF9BEB9E70

Sleep/Wake UUID:       7E99D299-5488-4C02-AEA7-56FCEDE340E2

Time Awake Since Boot: 100000 seconds
Time Since Wake:       1039 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [41823]

VM Region Info: 0 is not in any region.  Bytes before following region: 4367974400
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      1045a0000-104708000    [ 1440K] r-x/r-x SM=COW  .../Transmission

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Transmission                  	       0x104669c60 tr_file_priorities::filePriority(unsigned int) const + 4
1   Transmission                  	       0x104635ee8 tr_torrentFile(tr_torrent const*, unsigned int) + 128
2   Transmission                  	       0x1045d6cc8 -[Torrent(Private) createFileList] + 232
3   Transmission                  	       0x1045d7db8 -[Torrent(Private) metadataRetrieved] + 72
4   libdispatch.dylib             	       0x1b2a60e60 _dispatch_call_block_and_release + 32
5   libdispatch.dylib             	       0x1b2a62bac _dispatch_client_callout + 20
6   libdispatch.dylib             	       0x1b2a710ac _dispatch_main_queue_callback_4CF + 944
7   CoreFoundation                	       0x1b2d2de60 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
8   CoreFoundation                	       0x1b2ceb820 __CFRunLoopRun + 2540
9   CoreFoundation                	       0x1b2cea694 CFRunLoopRunSpecific + 600
10  HIToolbox                     	       0x1bb860990 RunCurrentEventLoopInMode + 292
11  HIToolbox                     	       0x1bb860704 ReceiveNextEventCommon + 552
12  HIToolbox                     	       0x1bb8604c4 _BlockUntilNextEventMatchingListInModeWithFilter + 72
13  AppKit                        	       0x1b583faec _DPSNextEvent + 844
14  AppKit                        	       0x1b583e390 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1332
15  AppKit                        	       0x1b58303b0 -[NSApplication run] + 596
16  AppKit                        	       0x1b5801a84 NSApplicationMain + 1064
17  dyld                          	       0x104bb90f4 start + 520

Thread 1:
0   libsystem_kernel.dylib        	       0x1b2beb8cc kevent + 8
1   Transmission                  	       0x1046a1948 kq_dispatch + 492
2   Transmission                  	       0x104691fc8 event_base_loop + 592
3   Transmission                  	       0x10464a1ec libeventThreadFunc(void*) + 132
4   Transmission                  	       0x10463fc74 ThreadFunc(void*) + 32
5   libsystem_pthread.dylib       	       0x1b2c214ec _pthread_start + 148
6   libsystem_pthread.dylib       	       0x1b2c1c2d0 thread_start + 8

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1b2be5954 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b2be5d00 mach_msg + 76
2   CoreFoundation                	       0x1b2cece38 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1b2ceb2f0 __CFRunLoopRun + 1212
4   CoreFoundation                	       0x1b2cea694 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x1b59acc24 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x1b2c214ec _pthread_start + 148
7   libsystem_pthread.dylib       	       0x1b2c1c2d0 thread_start + 8

Thread 3:
0   libsystem_pthread.dylib       	       0x1b2c1c2bc start_wqthread + 0

Thread 4:
0   libsystem_kernel.dylib        	       0x1b2be8ebc __semwait_signal + 8
1   libsystem_c.dylib             	       0x1b2af3d88 nanosleep + 216
2   Transmission                  	       0x10461c7d8 tr_wait_msec(long) + 76
3   Transmission                  	       0x104663aa0 tr_webThreadFunc(void*) + 1812
4   Transmission                  	       0x10463fc74 ThreadFunc(void*) + 32
5   libsystem_pthread.dylib       	       0x1b2c214ec _pthread_start + 148
6   libsystem_pthread.dylib       	       0x1b2c1c2d0 thread_start + 8

Thread 5:
0   libsystem_pthread.dylib       	       0x1b2c1c2bc start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x1b2c1c2bc start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x1b2c1c2bc start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000000013f857f50   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x00006000006ae5c0
    x4: 0x0000000000005207   x5: 0x00000000ffffffff   x6: 0x0000000000000000   x7: 0x0000600003da01a0
    x8: 0x0000000000000000   x9: 0x0000000000000028  x10: 0x00000000aa1d03fd  x11: 0x0000000000000000
   x12: 0x00000000d125b130  x13: 0x000000005125b000  x14: 0x0000000051200000  x15: 0x000000020b8fd130
   x16: 0x00000001b2ab1c40  x17: 0x000000020c63bf28  x18: 0x000000010804b940  x19: 0x000000016b85e148
   x20: 0x00006000037a1860  x21: 0x0000000000000000  x22: 0x000000013f857a00  x23: 0x0000000000000000
   x24: 0x00000001fce49a00  x25: 0x0000600001381780  x26: 0x0000600001383600  x27: 0x000000000000000f
   x28: 0x000000010472e000   fp: 0x000000016b85e110   lr: 0x0000000104635ee8
    sp: 0x000000016b85e0a0   pc: 0x0000000104669c60 cpsr: 0x20000000
   far: 0x0000000000000000  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x1045a0000 -        0x104707fff org.m0k.transmission (3.00+) <5be02f9d-d13b-36e2-8275-f0e1f90a463d> /Applications/Transmission.app/Contents/MacOS/Transmission
       0x1b2a5f000 -        0x1b2aa5fff libdispatch.dylib (*) <3d7a56a3-23bf-3077-b5c6-9ce65ce7333e> /usr/lib/system/libdispatch.dylib
       0x1b2c68000 -        0x1b31abfff com.apple.CoreFoundation (6.9) <b2ff96d0-ae99-31ef-9014-fc9964b4f3e0> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1bb830000 -        0x1bbb5ffff com.apple.HIToolbox (2.1.1) <98ea191e-b6f8-3036-b267-eeadb5f03c7d> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x1b57fe000 -        0x1b66affff com.apple.AppKit (6.9) <518f4e68-c324-320f-9d7f-85c224eae972> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x104bb4000 -        0x104c13fff dyld (*) <86a8ba48-8bb4-3b30-9cda-051f73c74f44> /usr/lib/dyld
       0x1b2be4000 -        0x1b2c19fff libsystem_kernel.dylib (*) <c8524c02-b14f-30bd-a228-c44b4a448e68> /usr/lib/system/libsystem_kernel.dylib
       0x1b2c1a000 -        0x1b2c26fff libsystem_pthread.dylib (*) <4786e19a-9312-38e6-80ef-9c1394548118> /usr/lib/system/libsystem_pthread.dylib
       0x1b2ae5000 -        0x1b2b65fff libsystem_c.dylib (*) <002a39ae-6431-3b2e-85e7-c45fc2f95ad0> /usr/lib/system/libsystem_c.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=1.6G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.6G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                 2176K        4 
CG image                           128K        4 
ColorSync                          528K       26 
CoreAnimation                     2304K       23 
CoreGraphics                        16K        1 
CoreUI image data                 1184K       10 
Foundation                          96K        2 
Kernel Alloc Once                   32K        1 
MALLOC                           281.0M       51 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)         960.0M        8         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.1M        8 
Stack                             11.7M        8 
VM_ALLOCATE                        1.0G       13 
VM_ALLOCATE (reserved)             256K        1         reserved VM address space (unallocated)
__AUTH                            2454K      280 
__AUTH_CONST                      18.6M      459 
__DATA                            14.3M      445 
__DATA_CONST                      16.7M      465 
__DATA_DIRTY                      1675K      194 
__FONT_DATA                          4K        1 
__LINKEDIT                       572.0M        5 
__OBJC_CONST                      3232K      244 
__OBJC_RO                         81.8M        1 
__OBJC_RW                         3088K        1 
__TEXT                           445.9M      483 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
mapped file                      151.1M       25 
shared memory                      864K       14 
===========                     =======  ======= 
TOTAL                              3.9G     2794 
TOTAL, minus reserved VM space     2.6G     2794 



-----------
Full Report
-----------

{"app_name":"Transmission","timestamp":"2021-12-04 08:50:11.00 +0100","app_version":"3.00+","slice_uuid":"5be02f9d-d13b-36e2-8275-f0e1f90a463d","build_version":"14714.3.0","platform":1,"bundleID":"org.m0k.transmission","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.0.1 (21A559)","incident_id":"D5E62E70-EDA0-459C-B379-A17B553DCDC5","name":"Transmission"}
{
  "uptime" : 100000,
  "procLaunch" : "2021-12-04 08:45:41.2650 +0100",
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "procStartAbsTime" : 2398685650776,
  "coalitionID" : 5463,
  "osVersion" : {
    "train" : "macOS 12.0.1",
    "build" : "21A559",
    "releaseType" : "User"
  },
  "captureTime" : "2021-12-04 08:50:11.1794 +0100",
  "incident" : "D5E62E70-EDA0-459C-B379-A17B553DCDC5",
  "bug_type" : "309",
  "pid" : 41823,
  "procExitAbsTime" : 2405163270052,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Transmission",
  "procPath" : "\/Applications\/Transmission.app\/Contents\/MacOS\/Transmission",
  "bundleInfo" : {"CFBundleShortVersionString":"3.00+","CFBundleVersion":"14714.3.0","CFBundleIdentifier":"org.m0k.transmission"},
  "storeInfo" : {"deviceIdentifierForVendor":"6A5442B8-0C89-5DCE-875F-A8C8F4349E32","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.m0k.transmission",
  "crashReporterKey" : "FB981302-784B-58FE-8C47-7DCF9BEB9E70",
  "wakeTime" : 1039,
  "sleepWakeUUID" : "7E99D299-5488-4C02-AEA7-56FCEDE340E2",
  "sip" : "enabled",
  "vmRegionInfo" : "0 is not in any region.  Bytes before following region: 4367974400\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      1045a0000-104708000    [ 1440K] r-x\/r-x SM=COW  ...\/Transmission",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000000"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":41823},
  "vmregioninfo" : "0 is not in any region.  Bytes before following region: 4367974400\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      1045a0000-104708000    [ 1440K] r-x\/r-x SM=COW  ...\/Transmission",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":897909,"threadState":{"x":[{"value":5360680784},{"value":0},{"value":0},{"value":105553123272128},{"value":20999},{"value":4294967295},{"value":0},{"value":105553180885408},{"value":0},{"value":40},{"value":2854028285},{"value":0},{"value":3508908336},{"value":1361424384},{"value":1361051648},{"value":8783909168,"symbolLocation":0,"symbol":"OBJC_CLASS_$___NSPlaceholderArray"},{"value":7292525632,"symbolLocation":0,"symbol":"objc_retainAutoreleasedReturnValue"},{"value":8797798184},{"value":4429494592},{"value":6098903368},{"value":105553174599776},{"value":0},{"value":5360679424},{"value":0},{"value":8537807360,"objc-selector":"stringWithUTF8String:"},{"value":105553136719744},{"value":105553136727552},{"value":15},{"value":4369604608}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4368588520},"cpsr":{"value":536870912},"fp":{"value":6098903312},"sp":{"value":6098903200},"esr":{"value":2449473542,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":4368800864,"matchesCrashFrame":1},"far":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":826464,"symbol":"tr_file_priorities::filePriority(unsigned int) const","symbolLocation":4,"imageIndex":0},{"imageOffset":614120,"symbol":"tr_torrentFile(tr_torrent const*, unsigned int)","symbolLocation":128,"imageIndex":0},{"imageOffset":224456,"symbol":"-[Torrent(Private) createFileList]","symbolLocation":232,"imageIndex":0},{"imageOffset":228792,"symbol":"-[Torrent(Private) metadataRetrieved]","symbolLocation":72,"imageIndex":0},{"imageOffset":7776,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":1},{"imageOffset":15276,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":1},{"imageOffset":73900,"symbol":"_dispatch_main_queue_callback_4CF","symbolLocation":944,"imageIndex":1},{"imageOffset":810592,"symbol":"__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__","symbolLocation":16,"imageIndex":2},{"imageOffset":538656,"symbol":"__CFRunLoopRun","symbolLocation":2540,"imageIndex":2},{"imageOffset":534164,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":199056,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":3},{"imageOffset":198404,"symbol":"ReceiveNextEventCommon","symbolLocation":552,"imageIndex":3},{"imageOffset":197828,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":72,"imageIndex":3},{"imageOffset":269036,"symbol":"_DPSNextEvent","symbolLocation":844,"imageIndex":4},{"imageOffset":263056,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1332,"imageIndex":4},{"imageOffset":205744,"symbol":"-[NSApplication run]","symbolLocation":596,"imageIndex":4},{"imageOffset":14980,"symbol":"NSApplicationMain","symbolLocation":1064,"imageIndex":4},{"imageOffset":20724,"symbol":"start","symbolLocation":520,"imageIndex":5}]},{"id":897934,"frames":[{"imageOffset":30924,"symbol":"kevent","symbolLocation":8,"imageIndex":6},{"imageOffset":1055048,"symbol":"kq_dispatch","symbolLocation":492,"imageIndex":0},{"imageOffset":991176,"symbol":"event_base_loop","symbolLocation":592,"imageIndex":0},{"imageOffset":696812,"symbol":"libeventThreadFunc(void*)","symbolLocation":132,"imageIndex":0},{"imageOffset":654452,"symbol":"ThreadFunc(void*)","symbolLocation":32,"imageIndex":0},{"imageOffset":29932,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":8912,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":897941,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6484,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":6},{"imageOffset":7424,"symbol":"mach_msg","symbolLocation":76,"imageIndex":6},{"imageOffset":544312,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":2},{"imageOffset":537328,"symbol":"__CFRunLoopRun","symbolLocation":1212,"imageIndex":2},{"imageOffset":534164,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":1764388,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":4},{"imageOffset":29932,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":8912,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":899881,"frames":[{"imageOffset":8892,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":902058,"frames":[{"imageOffset":20156,"symbol":"__semwait_signal","symbolLocation":8,"imageIndex":6},{"imageOffset":60808,"symbol":"nanosleep","symbolLocation":216,"imageIndex":8},{"imageOffset":509912,"symbol":"tr_wait_msec(long)","symbolLocation":76,"imageIndex":0},{"imageOffset":801440,"symbol":"tr_webThreadFunc(void*)","symbolLocation":1812,"imageIndex":0},{"imageOffset":654452,"symbol":"ThreadFunc(void*)","symbolLocation":32,"imageIndex":0},{"imageOffset":29932,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":8912,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":902217,"frames":[{"imageOffset":8892,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":902218,"frames":[{"imageOffset":8892,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":902250,"frames":[{"imageOffset":8892,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4367974400,
    "CFBundleShortVersionString" : "3.00+",
    "CFBundleIdentifier" : "org.m0k.transmission",
    "size" : 1474560,
    "uuid" : "5be02f9d-d13b-36e2-8275-f0e1f90a463d",
    "path" : "\/Applications\/Transmission.app\/Contents\/MacOS\/Transmission",
    "name" : "Transmission",
    "CFBundleVersion" : "14714.3.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7292186624,
    "size" : 290816,
    "uuid" : "3d7a56a3-23bf-3077-b5c6-9ce65ce7333e",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7294320640,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5521408,
    "uuid" : "b2ff96d0-ae99-31ef-9014-fc9964b4f3e0",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1855.105"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7440891904,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3342336,
    "uuid" : "98ea191e-b6f8-3036-b267-eeadb5f03c7d",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7340023808,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15409152,
    "uuid" : "518f4e68-c324-320f-9d7f-85c224eae972",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4374347776,
    "size" : 393216,
    "uuid" : "86a8ba48-8bb4-3b30-9cda-051f73c74f44",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7293779968,
    "size" : 221184,
    "uuid" : "c8524c02-b14f-30bd-a228-c44b4a448e68",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7294001152,
    "size" : 53248,
    "uuid" : "4786e19a-9312-38e6-80ef-9c1394548118",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7292735488,
    "size" : 528384,
    "uuid" : "002a39ae-6431-3b2e-85e7-c45fc2f95ad0",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  }
],
  "sharedCache" : {
  "base" : 7290830848,
  "size" : 3072180224,
  "uuid" : "a6162d66-93e3-3251-93cc-b11f7c8c830e"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.6G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.6G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               384K        3 \nActivity Tracing                   256K        1 \nCG backing stores                 2176K        4 \nCG image                           128K        4 \nColorSync                          528K       26 \nCoreAnimation                     2304K       23 \nCoreGraphics                        16K        1 \nCoreUI image data                 1184K       10 \nFoundation                          96K        2 \nKernel Alloc Once                   32K        1 \nMALLOC                           281.0M       51 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)         960.0M        8         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.1M        8 \nStack                             11.7M        8 \nVM_ALLOCATE                        1.0G       13 \nVM_ALLOCATE (reserved)             256K        1         reserved VM address space (unallocated)\n__AUTH                            2454K      280 \n__AUTH_CONST                      18.6M      459 \n__DATA                            14.3M      445 \n__DATA_CONST                      16.7M      465 \n__DATA_DIRTY                      1675K      194 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       572.0M        5 \n__OBJC_CONST                      3232K      244 \n__OBJC_RO                         81.8M        1 \n__OBJC_RW                         3088K        1 \n__TEXT                           445.9M      483 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nmapped file                      151.1M       25 \nshared memory                      864K       14 \n===========                     =======  ======= \nTOTAL                              3.9G     2794 \nTOTAL, minus reserved VM space     2.6G     2794 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000076
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "6194416dea7ed64a7812a429"
      },
      "deploymentId" : 240000322
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000162
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61a69939b1c7c7620ce6e408"
      },
      "deploymentId" : 240000285
    }
  ],
  "experiments" : [

  ]
}
}
```

**Comment by toddlindner** [comment] 2022-01-02 17:33
looks to be a dupe of https://github.com/transmission/transmission/issues/2239

**Comment by ckerr** [comment] 2022-01-18 01:19
Agree w / @toddlindner. Closing as a dupe.

**Closed by ckerr** 2022-01-18 01:19 UTC
