### ISSUE TITLE
Can't donate from russia

### ISSUE THREAD

**Issue by intelegenter** [transmission/transmission#4690] opened 2023-01-29 23:57 UTC
### What is the issue?

Can't donate from russia :/

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Transmission 3.00 (bb6b5a062e)

**Comment by intelegenter** [comment] 2023-01-29 23:59
you should fix that!

**Comment by robd003** [comment] 2023-01-30 01:02
I'd donate via crypto if I could. (BTC / ETH / ADA)

**Comment by ckerr** [comment] 2023-01-30 01:50
Duplicate of https://github.com/transmission/transmission/discussions/4140

**Closed by ckerr** 2023-01-30 01:50 UTC
