### ISSUE TITLE
utp_on_error messages in Debug log

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3110] opened 2022-05-19 02:50 UTC
Hi Charles, still getting thousands of these in the Debug message log @ckerr.

![SCR-20220519-kkn](https://user-images.githubusercontent.com/69029666/169193821-6eb0d3b9-f701-4193-8135-39c62b770e79.png)

**Comment by ckerr** [comment] 2022-05-26 17:11
This is coming entirely from libutp; nothing that can be fixed in libtransmission per se other than updating our libutp snapshot.

Closing as a duplicate of https://github.com/transmission/transmission/issues/2996.

**Closed by ckerr** 2022-05-26 17:11 UTC
Labels: scope:core

**Comment by GaryElshaw** [comment] 2022-05-27 03:19
Afraid i've got as far as i could with that :-(
