### ISSUE TITLE
Request of a login page instead of the browser popup for web UI password

### ISSUE THREAD

**Issue by illando** [transmission/transmission#823] opened 2019-01-28 13:16 UTC
It seems iOS is not able to autofill the fields in the browser popup generated by the web UI, so you always have to manually enter user and password from mobile.
It can be solved using a login page instead of the basic browser popup.
Some app like Sonarr has an option to choose between these two type of authentication.

Thanks.

**Comment by chrisadas** [comment] 2020-01-05 17:24
I second this. Using browser pop-up is incompatible with password managers, not just on iOS but Android and desktop browsers as well.

**Comment by normanr** [comment] 2021-11-09 22:30
This is the same request as https://github.com/transmission/transmission/issues/716

**Comment by ckerr** [comment] 2022-02-24 20:47
Duplicate of #716

**Closed by ckerr** 2022-02-24 20:47 UTC
Labels: duplicate
