### ISSUE TITLE
Web interface is unreadable on iOS Safari and desktop Firefox

### ISSUE THREAD

**Issue by stevenengler** [transmission/transmission#3762] opened 2022-09-05 00:16 UTC
With transmission 1bba2a8c6, the interface for the pop-ups and other pages is unreadable on iOS (not sure about other mobile devices like Android). I've attached some screenshots. Also the new sidebar pop-up doesn't support scrolling, which makes it unusable on smaller screens or when in landscape mode.

**Edit:** The white text issue appears to be an issue on desktop Firefox as well. Changing the title to reflect this.

<img src="https://user-images.githubusercontent.com/3708797/188338998-71fc2d26-59dc-404b-aeae-03cde5352c49.JPG" width="50%">
<img src="https://user-images.githubusercontent.com/3708797/188338999-fb8a333f-7019-4266-9f56-bf216c975225.JPG" width="50%">
<img src="https://user-images.githubusercontent.com/3708797/188339000-3d5b8cf8-2bf2-4a23-921b-c2a3321bb22c.JPG" width="50%">

Firefox right panel:

<img src="https://user-images.githubusercontent.com/3708797/188341739-ef151e5e-35bb-454c-b5e5-36e37503b733.png" width="50%">

**Comment by ckerr** [comment] 2022-10-07 20:45
I think this is a duplicate of https://github.com/transmission/transmission/issues/3893

**Closed by ckerr** 2022-10-07 20:45 UTC
Labels: scope:web
