### ISSUE TITLE
too many open files in system - windows 7

### ISSUE THREAD

**Issue by andradadad** [transmission/transmission#967] opened 2019-08-05 07:40 UTC
After downloading the torrent, it shows sometimes 99% after a verify local content, and sometimes 100% when I click on resume button.
Trying to transfer the file shows me an error of source file in windows.

I can move around the file on the same disk though.
It's the second file that this happens. I'm having to redownload the torrent.

**Comment by ckerr** [comment] 2020-05-18 23:13
Appears to be a duplicate of #633

**Closed by ckerr** 2020-05-18 23:13 UTC
Labels: os:windows
