### ISSUE TITLE
Some columns in the Peers pane are too narrow

### ISSUE THREAD

**Issue by fghzxm** [transmission/transmission#4887] opened 2023-02-14 15:04 UTC
### What is the issue?

Some columns in the Peers pane of the web interface are too narrow to cleanly display their contents.  In particular:

* The Address column cannot cleanly display IPv6 addresses.
* The Status column will take a line break to display a long Status string, like the topmost one below.

Neither the width of the pane nor the columns can be adjusted.

![transmission-web-peers](https://user-images.githubusercontent.com/32954258/218767963-1ca25a78-e36e-4861-9ec4-0996cc4dfd76.png)

My takes are:
1. The Status column should be wide enough to display the longest possible Status string.
2. I don't think most people are interested in seeing the entire IPv6 address of every peer, so maybe the Address column should be treated the same as the Client column, where the ellipsis is used for long contents.
3. The Done column is apparently wider than needed.
4. Ultimately we should probably make the widths adjustible.
5. One interesting alternative is to forgo the table structure and instead display the peer list as a list view.  Each item in the list view can have non-trivial internal layouts, and we can make it look pretty without occupying too much horizontal space, e. g.
   ```
   +-----------------------------------------------+
   | T D U E X I                       192.0.2.123 |
   | Done: 42%       ^: 314 kB/s       v: 271 kB/s |
   |                            Transmission 4.0.0 |
   +-----------------------------------------------+
   ```

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.0

**Comment by ckerr** [comment] 2023-02-14 18:07
Hi @fghzxm, thanks for reporting this!

I think this is a duplicate of #4209, so I'm closing this one as a dupe.

**Closed by ckerr** 2023-02-14 18:07 UTC
