### ISSUE TITLE
Can't get rid of a transfer on launch

### ISSUE THREAD

**Issue by Max2P** [transmission/transmission#5311] opened 2023-03-28 13:24 UTC
### What is the issue?

Hello, 
Everytime I launch Transmission, I have a persistant transfer that I don't recognise.
When I delete it, each time I reopen the app, it appears again. Can you tell me how to get rid of it ?
Thanks!
<img width="757" alt="capture" src="https://user-images.githubusercontent.com/129186551/228251081-21e2cebe-1d60-462e-827e-c6aedd69b10d.png">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.2 (2a57b17031)

**Comment by ckerr** [comment] 2023-03-28 16:56
Duplicate of https://github.com/transmission/transmission/discussions/5267

**Closed by ckerr** 2023-03-28 16:56 UTC
