### ISSUE TITLE
feat: save queue order between sessions

### ISSUE THREAD

**Issue by KAMiKAZOW** [transmission/transmission#155] opened 2017-01-26 07:14 UTC
When I set up a queue order, then quit Transmission and restart it, the queue is jumbled around.
Tested with both the Qt and GTK clients.

**Comment by jemxpat** [comment] 2019-06-23 07:31
This is a massive problem for me, in terms of usability. Is there no way to retain queue order between restarts? How is the queue order determined? Perhaps I can re-write something in the torrent resume files? Some clue, please!

**Comment by jemxpat** [comment] 2019-06-23 07:39
What I *really* want is the ability to assign a label(s) to a torrent and then display via a label pulldown, sort queue by label, etc. Something completely orthogonal to the automated queue order, and entirely controlled by the user.

**Comment by carmanaught** [comment] 2019-07-06 01:33
> How is the queue order determined?

I'd had a bit of a look into this previously and just re-tested this and as far as I can tell, the queue is restored on resume by loading the files in `$XDG_CONFIG_HOME/transmission/resume`. The files in the `resume` directory are named according to the torrent hash (e.g. `aec2e48d6ece459f8358aad4889dc83046746b0b.resume` is the hash for Fedora-Workstation-Live-x86_64-30) and are loaded in dictionary order (I think that's the right term?), so the order depends upon the hash values.

I would think you'd need to maintain some sort of queue order list based on the torrent hash and compare against the torrents to resume to then order the queue. I assume some of how it loads the torrent order is based in [`resume.c`](https://github.com/transmission/transmission/tree/master/libtransmission/resume.c).

**Comment by ahimta** [comment] 2019-08-06 19:18
I'm using 2.94 now and it's surprising how this issue hasn't been resolved for years:sweat_smile:. These sorts of bugs are important in the sense that they are very obvious and tangible to users. And although software can never be perfect, having as externally perfect as possible product is a true multiplier:sweat_smile:.

I was planning on fixing this in the past because I was sorting the queue manually and I would rather spend 100x the time productively in fixing a bug than spending 1+ hour on annoying-distracting tasks:sweat_smile:.

However, these days I don't download many torrents and almost never need to sort the queue and would probably rather fix some bugs in other projects are taking away from my time (there's one VLC bug that I plan to work on).

Anyways, the most important thing at this stage is the macro level as to where this issue is in the future of the project. For example, is there an outstanding or planned work that will resolve this or make it easier to resolve.

Otherwise, if there's no related work and only the implementation of the fix is needed, then we need to determine the scope and start working toward a solution.

I haven't looked into this closely but from what @carmanaught mentioned it may be the case that the queue order is just not persisted and from the behavior (can change the queue and everything is reset on restart) and how long this issue has been open (2+ years) this is probably the case:sweat_smile:.

In addition, the 2+ years may indicate that there's some factor why this hasn't been resolved yet and I hope that it's just that the maintainers are busy with something else:sweat_smile:.

So people, let's get going and see this through:smiley:. I think may be able to work on this especially if the maintainers acknowledge this issue and at least provided an outline for the fix:smiley:.

**Comment by beren12** [comment] 2022-12-02 21:01
Hasn't os x had this forever? It still has the ability to have torrent groups, but keeping the queue order seems to be broken after 3.x changes. I never noticed 2.x forgetting the order I put my torrents.

**Comment by ckerr** [comment] 2023-02-09 15:32
Marking this as a regression because starting in 4.0.0 the macOS client uses the same backend settings as the other clients, so now it has this issue as well  :tada:

**Comment by beninato8** [comment] 2023-02-11 01:01
I've manually ordered dozens of torrents, so it's pretty annoying to have that messed up on updating to 4.0.0. I'll be switching back to 3.0 until a fix comes out, but hopefully a warning or mention of the issue could be added to the release notes for other macOS users.

**Comment by mag01** [comment] 2023-02-15 01:45
Yup, this is incredibly annoying. There was no such issue at macOS until (I think) some late 2021 - early 2022 nightlies where it started to occur. Since then I was hoping for a fix before the next release, but seeing the 4.0.0 out with this issue still present doesn't give my any hope.

**Comment by ckerr** [comment] 2023-02-15 04:34
@mag01 maybe reporting it sometime during the four month beta cycle would have helped? :smile_cat:

**Comment by frozenpandaman** [comment] 2023-04-17 12:18
Really really hope this will get fixed ASAP.

**Comment by GaryElshaw** [comment] 2023-04-17 17:33
@pkd81 If you have some skills, please contribute.

**Comment by pkd81** [comment] 2023-04-17 17:54
@GaryElshaw raising awareness of this issue is my contribution. Thanks!

**Comment by albabe** [comment] 2023-04-17 18:43
> Really glad I didn't waste 2 hours of my life on this release re-ordering all my torrents only to have it all wiped out after I rebooted a few days later, like what happened when 4.0.2 was released.

> Really really hope this will get fixed ASAP.

I hope so too.  I reordered my torrents 3 times thinking it was just a glitch.  Probably 4 or 5 hours.

To: [ckerr](https://github.com/ckerr)

This is my first ever complaint to Transmission.. so... sorryt for my ignorance.

**Comment by albabe** [comment] 2023-04-24 17:25
Is there a Nightly Build that fixes this?

**Comment by manofsticks** [comment] 2023-04-26 23:08
This issue seems to only have popped up for me starting with 4.0.3; did not experience it with 4.0.2

**Comment by albabe** [comment] 2023-04-26 23:12
> This issue seems to only have popped up for me starting with 4.0.3; did not experience it with 4.0.2

Odd... I've had it since 4.0.0.  I'm in Monterey 12.4 still.  It's odd that not many people are talking about it.  I guess I'm one of the few that uses that organization method.  I try my best to keep torrents up for a long time... sometimes year.  So, this kinda messes that up.

**Comment by albabe** [comment] 2023-04-27 19:25
This Fix-It Thread has been around since Jan 25, 2017?  It doesn't even show-up on the main page here.  Is that why no one seems to be working on it?

**Comment by GaryElshaw** [comment] 2023-04-28 00:41
Afraid you might need a little patience on this one being addressed; a few different things. The bug recorded in 2017 was resolved in the 3.0 release, but reappeared this year.

A lot of people have been have been discussing it, because there were a number of duplicate issue threads, and the project maintainers and other contributors have also noted it (me included). As you have also #4892.

Right now there are 52 open pr's, some may be necessary for subsequent work, some may be of higher or lower priority, and some might need merging before the code changes for this bug can be made. And everyone on the project is a volunteer.

**Comment by albabe** [comment] 2023-04-28 16:47
Thanx [GaryElshaw](https://github.com/GaryElshaw)
I went back to 3.00 and am in the process of putting everything in order there.  So, no rush.

I noticed something that might help (might not too).

When I updated to 4.00 it messed-up the Que Order, seemingly putting everything in a Random non-order.  I then reordered my torrents, and after every restart, it was random again.

Then when I finally figured-out that no matter how many times I reordered everything, that when I restarted it was always random... I tried to start-up 3.00... and it was all over the place too, so I assumed it messed-up the Library and that 3.00 was messed-up too.

Not true - It just messed it up on that first restart after trying 4.000... Now I notice that when I reorder 3.00 it will stay the way I reorder it.  So I assume it wasn't just the Library.

**Comment by albabe** [comment] 2023-05-03 14:33
Excuse my ignorance here, but Is there a way to know if any of the nightly Builds fix this problem?

**Comment by GaryElshaw** [comment] 2023-05-03 14:34
Not yet...

**Comment by albabe** [comment] 2023-05-03 17:14
@GaryElshaw
Thanx Gary.  I'm not sure if I was clear.  I  was curious is there was a place to go to find out when this Build comes-down?

**Comment by GaryElshaw** [comment] 2023-05-03 17:25
Best just to keep an eye on the commits: https://github.com/transmission/transmission/commits/main

**Comment by ckerr** [comment] 2023-05-04 20:29
@albabe a commit will refer directly to this issue by ticket number and the commit title will be something along the lines of "preserve queue order between sessions"

**Comment by albabe** [comment] 2023-05-17 16:04
Thanx for the help, folks.  But I am still at a loss here.  I searched "preserve queue order between sessions" and got nothing.

**Comment by albabe** [comment] 2023-07-27 22:58
So, how do I find out if this issue has been fixed yet?

**Comment by frozenpandaman** [comment] 2023-07-28 00:28
@albabe It's been fixed in v4.1.0, but the stable release of that version isn't out yet… eagerly waiting. Any estimate until release, @GaryElshaw or @ckerr?

**Comment by GaryElshaw** [comment] 2023-07-28 00:31
I _think_ Charles had mentioned the next week or two?

**Comment by albabe** [comment] 2023-07-28 21:26
Thanx so much, you guys.  I really appreciate it... as when I usually ask a question in here, I get sorta smacked around... : )

**Comment by albabe** [comment] 2023-08-19 17:31
Any word on this?

**Comment by Pentaphon** [comment] 2023-08-21 01:58
> It's been fixed in v4.1.0, but the stable release of that version isn't out yet… eagerly waiting. Any estimate until release,

@albabe 4.1.0 won't happen for months but 4.0.4 is coming out this week, it seems. Not sure if this has been backported for 4.0.4 or not.

**Comment by frozenpandaman** [comment] 2023-08-21 02:26
@Pentaphon Thanks for the news, really really hoping so! 🙏 Might you know if that's possible or hapening, @GaryElshaw?!

**Comment by albabe** [comment] 2023-08-22 00:01
Thanx [Pentaphon](https://github.com/Pentaphon)

Not sure what you mean by "backported for 4.0.4 or not."

I'm afraid to even try it.  It's such a pain to try it, and have it cast all my torrents to the wind, and then spend a couple hours trying to organize them again.  I guess it's better that just use 3.00 till whenever.  : )

**Comment by tearfur** [comment] 2023-08-22 01:21
> It's been fixed in v4.1.0

Has it? Which commit was it?

**Comment by Pentaphon** [comment] 2023-08-22 02:52
> Not sure what you mean by "backported for 4.0.4 or not."

@frozenpandaman said it was fixed in the 4.1.0 branch so what I mean is that I don't know if that fix has been applied to the 4.0.4 branch or not. I'm just going with what he said and trying to clarify it a bit more for you. I do think he should have pointed to the commit since now Tearfur is asking for it.

**Comment by albabe** [comment] 2023-09-12 15:20
So, is this fixed in 4.0.4?

**Comment by albabe** [comment] 2023-09-19 21:38
No one knows?

**Comment by tearfur** [comment] 2023-09-20 00:51
It isn't yet. You can know by that fact that this issue has not yet been closed, nor is it included in the [release notes](https://github.com/transmission/transmission/releases/tag/4.0.4) of 4.0.4.

**Comment by albabe** [comment] 2023-09-20 00:55
Hey thanx so much!  It seemed like the folks above thought it might be.  It's easy to get confused in here.

**Comment by albabe** [comment] 2023-10-21 22:14
So... this is just not gonna happen?  6 months now.

**Comment by ckerr** [comment] 2023-10-22 02:41
@albabe if you are in a hurry, Transmission is open-source and PRs are welcome

**Comment by albabe** [comment] 2023-10-23 17:10
I assume PR has something to do with Programming?   I would, gladly... but I'm no Programmer.  Not even remotely.
I've used Transmission for a very long time.  I'm just saddened that I can no longer use it.  And, honestly, I'm not really sure I would call waiting 6 months as me being impatient.

**Comment by nevack** [comment] 2023-10-23 17:30
***I do not represent the Transmission project, I'm just one of the contributors, and this is my opinion.***

@albabe, I understand your frustration and appreciate you speaking about it and bringing attention to the issue.
But all project contributors are volunteers, you are not in a position to demand anything.
All you can hope for is that somebody with 1. **skills**, 2. **will** and 3. **time** will look into this issue.
I think Charles can confirm that many issues were fixed just like that — someone stepped out and did it.
I hope you understand that and will not be turned off by this truth.

**Comment by Pentaphon** [comment] 2023-10-23 22:03
> So... this is just not gonna happen? 6 months now. I guess no one uses the "Sort By Cue" but me.

@albabe you have to understand that this is a volunteer project. Nobody is obligated or paid to take care of any issues. They do it when they feel like it and have the free time to do it. In many projects like this one, an issue may never be fixed. That's just the reality of open source projects. It's ok to come in here and inquire  about this issue when it seems overlooked for a long time or to ask if somebody is still interested in an issue when they haven't responded for a long time, but coming in to repeatedly ping people about an issue is simply bothersome and comes off as very entitled. I highly suggest you heed the advice that people are giving you and to leave the issue be after 1 inquiry and just wait to see what happens. Github will ping you when this issue is commented on so you can follow the progress on your own. 

Also, if an application is not doing what you want, you need to simply move on to another client that will. That's all you can do for your own needs.

**Comment by GaryElshaw** [comment] 2023-10-24 03:32
@albabe I'm building from the main branch and finding it to be stable, i'd recommend moving to the nightlies. https://build.transmissionbt.com/job/trunk-mac/

**Comment by Pentaphon** [comment] 2023-12-07 20:54
@ckerr can we have this and all the https://github.com/transmission/transmission/milestone/14 4.0.x milestones changed to 4.1.0 now that 4.0.5 is out?

**Comment by ckerr** [comment] 2023-12-08 16:02
@Pentaphon that's what we thought after 4.0.4 as well, so :man_shrugging: let's see what happens.

There's still the issue at https://github.com/transmission/transmission/pull/5263#issuecomment-1845642037. Fixing that would be worth a 4.0.6 release IMO.

**Comment by albabe** [comment] 2023-12-08 20:52
> @albabe I'm building from the main branch and finding it to be stable, i'd recommend moving to the nightlies. https://build.transmissionbt.com/job/trunk-mac/

[GaryElshaw](https://github.com/GaryElshaw)
Thanx so much for the reply.  I really appreciate it<

I have trouble follow this thread.  I don't program so I don't even remotely know the vernacular.  So forgive me if I seem even denser than I am.  So, are you saying the "Sort By Cue" issue has been addressed?  I keep my torrents seeding for a long time, sometimes years, so I have a load right now...  and I'd really hate to have to take a few hours to reorganize them if the "Que" option doesn't work  : )

**Comment by GaryElshaw** [comment] 2023-12-09 00:26
@albabe I understand. Entirely up to you, but I think i would still move to the 4.1 branch, even if it is painful at first.

**Comment by frozenpandaman** [comment] 2023-12-11 06:04
I hope it gets included in _whatever_ the next stable release is, whether that is 4.0.6 or 4.1.0. Frankly, **I believe this issue being fixed is worth a v4.0.6 release by itself.** As I think I mentioned way back when, many places do not allow the use of nightly/unstable/beta clients and thus many users are awaiting any sort of non-nightly release here, whether a minor version, patch, etc.

**Comment by Pentaphon** [comment] 2023-12-11 06:47
> **I believe this issue being fixed is worth a v4.0.6 release by itself.**

it's a feature so it's supposed to be in 4.1.0 if we are following semantic versioning.

**Comment by frozenpandaman** [comment] 2023-12-11 07:54
> it's a feature so it's supposed to be in 4.1.0 if we are following semantic versioning.

@Pentaphon It _was_ a feature that was already in the program. Re-ordering torrents has always been available. This is just fixing a _bug_ with the feature, which caused the order get scrambled upon dragging or relaunching. It's a patch, I think.

**Comment by albabe** [comment] 2023-12-11 16:48
@ [Pentaphon](https://github.com/Pentaphon) [rozenpandaman](https://github.com/frozenpandaman)
It's definitely NOT a "New Feature."  It was one of the reasons I've been using Transmission for decades.


It's always seemed odd to me that the Transmission folks rarely do updates.  I think sometimes it's been Years between Official Builds.
So no word if there will be a 4.1 soon?  But from what I'm gleaning here, the "Sort by Que" Feature is working in a recent Nightly Build?  And will likely be in 4.1 a "few years" from now?  : )

**Comment by racemus** [comment] 2024-02-18 06:05
I'm still using Transmission 3 because when I tried to move to 4th version, my queue order sorting was shuffled. It's still so with 4.0.5 and the yesterday nightly build. As far as I understand, it's connected with this bug.

**Comment by albabe** [comment] 2024-02-18 21:09
@ [racemus](https://github.com/racemus)
Heyz<  Same here.  It's been almost a year now.
It's an important feature to me, but I assumed since no one has tried to "fix" it since 4 was released, that I was the only one it mattered to.

**Comment by albabe** [comment] 2024-03-27 16:36
So... I guess this "Feature" has been dropped and will no longer be available on Transmission?  I guess not very many Users used this?

**Comment by Pentaphon** [comment] 2024-03-28 08:35
> So... I guess this "Feature" has been dropped and will no longer be available on Transmission? I guess not very many Users used this?

This is a volunteer project. When somebody has time to add this feature, it will be added or maybe it won't be added because there's nobody to add it. There is no use in asking for it over and over again. The issue is open, there is demand for it as you can see from the thumbs up you got, so it's just a matter of being patient. Your time would be better spent promoting the project elsewhere so people can find it and help work on it.

**Comment by albabe** [comment] 2024-03-28 23:57
Yes... I know.  I've read this response from you a few times.  I would think there's as little need for you to repeat it as you believe about my comment.  Irony might be a factor.   And there's no need in being condescending.  I've not be mean or condescending to anyone in here.

I didn't notice any "Thumbs."  

Unlike your opinion of my comment, I thought my comment might be helpful.  Sorry to offend you.  I was hoping my comment might remind someone.  Obviously this fix is a very low priority.

And:  I've been promoting Transmission for what seems like decades.

**Comment by Pentaphon** [comment] 2024-03-29 13:54
From the new PR that will fix this issue: 

>Important: This PR does not load the queue order stored in pre-4.0.0 macOS apps.

>The macOS app in Tr 3.00 and below has a feature to save the queue order between sessions, but it got removed in 4.0.0. This PR adds it back in libtransmission for all Tr clients to enjoy.

>Need help

>It would be nice if someone can write code in the macOS app that loads the queue order from pre-4.0.0 macOS apps. AFAICT, they are stored in Transfers.plist.

Just posting this here in case they don't see that message on the new PR

**Comment by albabe** [comment] 2024-05-17 23:07
Thanx [Pentaphon](https://github.com/Pentaphon)
Just checking-in.  Any word?

**Comment by Pentaphon** [comment] 2024-05-18 00:28
> Just checking-in. Any word?

Just follow that PR. Not merged yet.

**Comment by albabe** [comment] 2024-05-18 19:57
Thanx, but Sorry...  I'm at a loss here.  There's no hyperlinks in your post, so I see nowhere to go.  I don't know what a PR is.  And I don't know what is meant by "merged" is this situation.

I went to the link above your comment and I'm not sure what is going on in  the thread.

**Comment by Pentaphon** [comment] 2024-05-18 22:28
> I don't know what a PR is. And I don't know what is meant by "merged" is this situation.

It sounds like you need to educate yourself on how github works if you want to understand what we are doing here. Please have a look at this and all other Github documentation. 

https://docs.github.com/en/get-started/start-your-journey/hello-world

**Comment by albabe** [comment] 2024-05-19 21:15
Does it really sound that way?  Odd, since I'm not a programmer or anything of the sort.  I'm just a person who used to use Transmission, who was hoping the nice Volunteers would eventually fix the feature I use.

But thanx for the lofty condescension, rather than an actual answer.

**Comment by Pentaphon** [comment] 2024-05-19 21:39
> But thanx for the lofty condescension, rather than an actual answer.

I linked you to a resource that will help you understand what PR and "merged" means. I'm not going to use this issue or spend needless time to type out a whole crash course on Github when you can search that information for yourself. Please educate yourself on how Github works by using my link and gathering your own information. You don't need to be a programmer to be expected to learn the basics of a site you are using. Let's also not flood this issue with bickering. The issue looks like it is being resolved so lets just leave it at that.

**Comment by albabe** [comment] 2024-08-01 18:30
Does this mean "Sort By Cue" is fixed?

**Comment by Pentaphon** [comment] 2024-08-01 21:57
> Does this mean "Sort By Cue" is fixed?

@albabe the PR fixing this issue is not yet merged nor released. Please learn more about how github works before posting.

**Closed** 2024-10-13 16:36 UTC
Labels: scope:core, pr welcome, type:feat, bug:regression

**Comment by sarpuser** [comment] 2024-12-18 21:33
This seems to also be happening with the transmission-daemon 4.x running on Alpine. As far as I can tell, the PR is only for Mac clients.
