### ISSUE TITLE
4.0.x torrent-get sorts torrents by hash instead of by id

### ISSUE THREAD

**Issue by ThePowerTool** [transmission/transmission#5551] opened 2023-05-23 06:03 UTC
### What is the issue?

before the latest update to transmission* -4.0.3-1.fc36.x86_64 (Fedora 36)
`transmission-remote -tall -l`
would list torrent IDs in ascending order, starting with 1 and incrementing through the last torrent ID.

Transmission has never had an argument to specify sort.

Now the same command with "-tall" displays torrents in what appears to be a random order.

Note:
`transmission-remote -t[lower]#-[higher]# -l`
still displays torrent IDs in ascending order from the left-lower number to the right-higher number.

If the plan is to add a "sort" argument then this error becomes moot.  Otherwise it is logical to expect without a sort argument that torrent IDs would be displayed in ascending order following precedence (set by previous versions).

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

transmission* -4.0.3-1.fc36.x86_64 (Fedora 36)

**Comment by valcomm** [comment] 2023-06-03 08:17
I second for this issue.
Updated transmission (3.00 -> 4.0.3) and was unpleasantly surprised with this change.
Before when daemon started torrents were assigned ids that stayed for the session.  And adding a new torrent caused assignment of the consecutive not used in this session id.  And `transmission-remote` was displaying newly added torrents on the bottom.

Now torrents on daemon restart are getting some weird ids, with values larger than total number of torrents.
`transmission-remote` dumps torrents without any order forcing to doubt the reason for Id field at all.
Adding new torrent gets to it some random number in the middle (filling holes in Id sequence I guess).
And displaying the list of torrents now puts newly added torrents not to the bottom, but at some random place.
This consistent Id change brought too many bugs without any real advantage

**Comment by lvd2** [comment] 2023-06-07 19:36
> Now torrents on daemon restart are getting some weird ids, with values larger than total number of torrents.

Regarding this, it always was (and still is) the least yet unused number since the start of transmission-daemon. One of the reasons to have it is that you'll never remove wrong torrent by erroneously issuing `transmission-remote -t NUM -rad` twice: number is guaranteed to be not valid after the 1st invocation. All that is just my IMO.

**Comment by valcomm** [comment] 2023-06-07 19:44
> > Now torrents on daemon restart are getting some weird ids, with values larger than total number of torrents.
> 
> Regarding this, it always was (and still is) the least yet unused number since the start of transmission-daemon. 
This isn't true.  3.00 version used incremental assignments.
If in one daemon run you had torrents with Id 1,2,3, removed 1 and 2 and add a new torrent, it'd get expected and reasonable Id equal 4.

> One of the reasons to have it is that you'll never remove wrong torrent by erroneously issuing `transmission-remote -t NUM -rad` twice: number is guaranteed to be not valid after the 1st invocation. All that is just my IMO.

It's exactly opposite.  Now it's possible to remove a wrong torrent.

One daemon, two clients.
client 1: transmission-remote -t 2 -r
client 2: transmission-remote -a 'magnet...' -s
client 1: transmission-remote -t 2 -r

Before it wasn't a possible scenario at all, but with persistent Id changes many scheduled jobs and scripts needs to be revisited.

**Comment by lvd2** [comment] 2023-06-07 20:06
I've just made a quick check:
1. In a sequential stopping and starting of `transmission-daemon` *all* the torrents keep their numbers: `transmission-remote -l | sort -hk1` gives essentially the same order (but up/down numbers might change, obviously). Also the numbers right after start of the daemon are always from 1 to N without holes.
2. In a sequential addition and removing of some torrent, the first time it gets number N+1, the second time it is N+2 etc.

What am I missing here?

**Comment by valcomm** [comment] 2023-06-08 06:42
> What am I missing here?

You're right.  I haven't checked this part:

> it always was (and still is) the least yet unused number since the start of transmission-daemon.

and blindly believed that it was so.  Also I had the same impression (caused also by surprisingly big Id numbers with not so long set of torrents).
I apologize for supporting this confusion (missing Ids in the sequence are being assigned to the new torrents).

With added sorting workaround it is reduced to the question "why I have such a big Id numbers with so few torrents?"

**Comment by valcomm** [comment] 2023-06-08 16:21
> > With added sorting workaround it is reduced to the question "why I have such a big Id numbers with so few torrents?"
> 
> Does this happen also right after you restart `transmission-daemon` (or whatever executable is running at your place as actual torrenting daemon)?

Yes, it does.  The cause of needed workarounds related to Ids is that Id field became persistent.  Meaning that restarts don't change them as they did before.  Now Id field is confusing.

**Comment by lvd2** [comment] 2023-06-08 17:03
For me, restarts do change numbers as I described above. How can I make `transmission-daemon` not to change them?

**Comment by ckerr** [comment] 2023-06-11 16:56
IDs are and always have been transient -- they are literally an index into the table where all the torrents are stored. It's possible that they could be the same between sessions *if* you don't add or remove any torrents and *if* your OS walks the files in the .torrents directory in the same order each time, but this isn't any guarantee built into Transmission.

In 20-20 hindsight, maybe IDs should never have been exposed via RPC. They are a convenient shorthand but their transience makes them brittle compared to the persistence of an info-dict hash.

**Comment by ckerr** [comment] 2023-06-11 17:02
I've added up a PR https://github.com/transmission/transmission/pull/5604 to restore sort-by-ID but now that I wrote out that previous comment, I'm now second-guessing myself and wondering if sort-by-id was a misfeature in the first place since it is transient. Maybe 4.0.x's sort-by-hash *is* an improvement since it will give a guaranteed consistent order between sessions.

One advantage of sort-by-id mentioned in this thread is that it's easier to look at the end of `-tall` to see what torrents have been added. Are there other advantages?

**Comment by ThePowerTool** [comment] 2023-06-11 20:46
Note:  This post not intended for GUI point-n-clickers >:)

One example of torrent ID value:
. Add 5 torrents
. Access the 5 torrents just added via CL:
transmission-remote -tx-(x+4) -l # (and subsequent handy commands)

Remember, added torrents can be added without starting for a number of important use-cases.

Without torrent IDs the above use-case (including reference to expanded variations), and associated simplicity, would be lost.

Another example:
. with 5 related torrents (e.g.):
torrent 1 of 5
...
torrent 5 of 5

Where torrents are in a list, the related torrents may be accessed via:
transmission-remote -t1.23,99,105-106 -l (and associated handy commands)

In this case, torrent managment is facilitated by torrent ID.  This can be even more important when the 5 related torrents do not have similar names or are related because of user-grouping vs creator-grouping.

I have always greatly valued the provided torrent ID.

**Comment by ckerr** [comment] 2023-06-11 23:02
> `transmission-remote -tall -l -srt=[x]`

I'd happily review a PR for this if you or @lvd2 or anyone else wants to write this :1st_place_medal:

**Comment by lvd2** [comment] 2023-06-12 09:05
> I've added up a PR #5604 to restore sort-by-ID but after writing that previous comment now I'm second guessing myself.
> 
> Maybe sort-by-info-hash _is_ better than sort-by-id since it will give a consistent order between sessions.
> 
> One use of sort-by-id mentioned earlier is looking at the end of `-tall` to see what torrents were recently added. That's something that we could fix e.g. by adding an option to sort by `addedDate`.
> 
> Are there other use cases for sort-by-id?

For more than 10 years, since transmission 2.xx versions, I was into a misbelief that ID order (which is also happened to be ordered by addition data) was *the* feature, not coincidence. And I get used to that feature, as @valcomm obviously also did.

It turned out to be actually an order of torrent files into a transmission working directory (as listed by `ls -f`) and accidentally it was kept by the FSes for all those years :)

Now I do agree that *the* feature must be a default sorting by addedDate, while the ID itself is actually irrelevant.

A quick fix for `transmission-remote`: https://github.com/transmission/transmission/pull/5608
I guess @ckerr might implement that in a more elegant/fitting way.

**Comment by snarl817** [comment] 2023-07-14 18:30
I mean, I'm not going to lie. I'd LOVE to see the client implement user-specified sort orders. Yes, I can use the sort command, but not every piece of data is available in the list output. Sort by date added is perfect, and SHOULD be the default, but what about sort by Date started, or Latest Activity, Number of peers, number of connected trackers, etc?

I'm certainly not going to complain about date added, though. 99.9% of the time, THIS is the order I want. Not "sort by hash ID". :)

**Closed** 2023-10-25 17:42 UTC
