### ISSUE TITLE
Xcode project still references miniupnpc submodule despite being replaced by miniupnp in 4.0.6

### ISSUE THREAD

**Issue by i0ntempest** [transmission/transmission#6876] opened 2024-05-31 02:31 UTC
### What is the issue?

Title. miniupnp target was not updated, so it references nonexistent stuff in thirdparty/miniupnpc which is now empty, causing the build to fail.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.6

**Comment by tearfur** [comment] 2024-05-31 02:39
Duplicate of #6873. The problem is with the submodules being synced with the `main` branch instead of `4.0.x`, instead of the Xcode project being outdated.

**Closed by tearfur** 2024-05-31 02:39 UTC
