### ISSUE TITLE
In hybrid torrents .pad dir created

### ISSUE THREAD

**Issue by abubaca4** [transmission/transmission#4602] opened 2023-01-16 21:57 UTC
### What is the issue?

I checked how latest beta build work with hybrid torrent files and discovered that hybrid torrents works but garbage dir .pad created.
As I know .pad files has no information and it just pad all files to block size.(it need only for hybrid torrents)
All clients that support hybrid torrents(but not v2) like last uTorrent and qBittorrent with libtorrent 1.2 not create this dir.
When torrent contains a lot of small files this dir can take a lot of drive place.

I hope that this will be fixed until stable 4.0.0

I created this issue because support of bittorrent v2 placed in [5.0.0-beta.1](https://github.com/transmission/transmission/milestone/7). This fix will not be needed when support of v2 will be implemented.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.0-beta.3 (634b1e8fc1)

**Comment by ckerr** [comment] 2023-01-17 18:49
Duplicate of #3387, and you're right, is also related to #458

**Closed by ckerr** 2023-01-17 18:49 UTC
Labels: bug, duplicate, scope:core, pr welcome, bep-compliance
