### ISSUE TITLE
Web interface priority buttons don't do anything

### ISSUE THREAD

**Issue by stevenengler** [transmission/transmission#3763] opened 2022-09-05 01:15 UTC
When clicking one of the priority buttons for a file on the web interface (1bba2a8c6), it doesn't seem to have an effect and the button doesn't "stick". For example if I click the high-priority button for a file, both the normal-priority and high-priority buttons become depressed, and when refreshing the page it becomes reset back to the normal-priority.

Browser: Chromium 104.0

After clicking the high-priority button, both buttons are in the depressed state:

![1662340287_grim](https://user-images.githubusercontent.com/3708797/188342070-44fb1225-edca-486d-a963-15c9c8b2343a.png)

After waiting a minute and refreshing the page:

![1662340437_grim](https://user-images.githubusercontent.com/3708797/188342116-a71660b2-feab-463a-aa3d-bb3ed87dfe1b.png)

**Comment by dareiff** [comment] 2022-10-17 20:18
I'm seeing some similar issues, but I'm wondering if priority in general is ... semi-broken? (I'm on macOS, and I don't currently see the priority icons at all in the inspector.)

**Comment by killemov** [comment] 2022-10-23 08:00
> I'm seeing some similar issues, but I'm wondering if priority in general is ... semi-broken? (I'm on macOS, and I don't currently see the priority icons at all in the inspector.)

Nope. Priority works. Files with higher priority are consistently finished first with only a few exceptions. However a UI might have a broken component. If so, that should be addressed. Also sometimes requests to or responses from transmission-daemon get lost.

**Comment by ckerr** [comment] 2023-01-17 16:56
When you click a priority button in the web ui, the web ui sends a "change the priority" request to the transmission server. What's described in this issue is exactly what you'd see if the server is lagging & doesn't respond with "ok, priority changed" in a timely manner. Refreshing the page likely cancels the communication and so the request is lost and we have to start all over again.

So my guess is that this bug is not really about the Web UI, it's about making the transmission RPC server less laggy, e.g. through #2462.

Closing this as a duplicate of #2462.

**Comment by stevenengler** [comment] 2023-01-17 17:00
> When you click a priority button in the web ui, the web ui sends a "change the priority" request to the transmission server. What's described in this issue is exactly what you'd see if the server is lagging & doesn't respond with "ok, priority changed" in a timely manner. Refreshing the page likely cancels the communication and so the request is lost and we have to start all over again.
> 
> So my guess is that this bug is not really about the Web UI, it's about making the transmission RPC server less laggy, e.g. through #2462.
> 
> Closing this as a duplicate of #2462.

I just tested it on the latest beta by waiting 60 seconds after pressing the button before refreshing the page. I don't think the transmission server would be that laggy? Or are you saying that the transmission server would drop the request if it's too laggy?

**Comment by stevenengler** [comment] 2023-01-17 17:08
I just checked, and when I click a priority button, it always sends a `torrent-set` request with `priority-normal: [<idx>]`. Even when I click the up arrow or down arrow, it always sets the "priority-normal" instead of the "priority-high" or "priority-low". So I still think this is a bug in the web UI and should be re-opened.

**Comment by ckerr** [comment] 2023-01-17 18:27
Yuck. But that's very helpful information, thank you!

**Comment by dareiff** [comment] 2023-01-17 20:22
Been a little while since I've checked on the webui, but I'm going to see if it was something I've touched!

**Comment by ckerr** [comment] 2023-01-17 21:47
> Been a little while since I've checked on the webui, but I'm going to see if it was something I've touched!

@dareiff thanks for volunteering to look! I'm assigning the ticket to you, not in a "Derek must fix it no matter who broke it" sense, but in a "Derek has the baton right now" sense.

If you want to fix it, :100:, and if you investigate and have info but want to pass it along, also :100:

**Comment by dareiff** [comment] 2023-01-17 22:26
My experimenting:

- After initial data download, I can go from High to Normal (and webui buttons adjust themselves)
- After initial data download, I can go from Low to Normal (and webui buttons adjust themselves)
- After initial [...], I cannot go from Normal to High. 

---

Fix soon, having to do with types, and the default case (after "-1" not matching `-1` or `1`.)

**Closed** 2023-01-21 20:23 UTC
Labels: scope:web, confirmed, bug:regression

**Comment by dareiff** [comment] 2023-01-23 04:30
Sorry for my absence here! I was in a land without internet. I see it's merged, though! Thanks!!

**Comment by stevenengler** [comment] 2023-01-23 05:11
@dareiff Thanks for the fix!
