### ISSUE TITLE
[osx v2.92 (14714)] How can one Sort Transfers By -> Queue Order + Descending?

### ISSUE THREAD

**Issue by dmitry-salnikov** [transmission/transmission#390] opened 2017-08-28 18:49 UTC
Sorry if a dumb question. App menu item "Sort Transfers By -> Ascending" is disabled when sort mode is "Queue Order", as by default. Is it possible to enable "Descending"? 
Thanks for any feedback!

**Comment by KingLucius** [comment] 2017-09-08 15:27
Try this build:
https://build.transmissionbt.com/job/trunk-mac/lastSuccessfulBuild/artifact/release/Transmission-0378ee8298.dmg

I can sort by queue and use reverse sort order using 0378ee8298 build.

**Comment by dmitry-salnikov** [comment] 2017-09-27 18:05
Thanks @KingLucius , I've tried the build, but with no success, the issue remains. See screenshot attached (app version also visible on it) 
![screenshot 2017-09-27 21 01 29](https://user-images.githubusercontent.com/1784828/30929547-88bf9e1a-a3c7-11e7-89e0-82a71e1ab3ff.png)

**Comment by ckerr** [comment] 2022-02-10 18:14
I'm closing this issue due to its age and that I'm not able to reproduce it.

If this is still a problem in the [nightly builds](https://transmissionbt.com/download), please open a new bug report with updated information. Thank you!

**Closed by ckerr** 2022-02-10 18:14 UTC
