### ISSUE TITLE
Data lost when moving to existing location

### ISSUE THREAD

**Issue by torkve** [transmission/transmission#617] opened 2018-05-10 11:14 UTC
Transmission silently drops data if it is moved to folder with symlink.

### Used configuration:
 * transmission-daemon 2.92-2 on Debian sid
 * transmission-remote-gtk 1.3.1 on Ubuntu 18.04

### How to reproduce:
1. Download torrent into path /downloads/A
2. Create symlink /some_category/A -> /downloads/A
3. Ask transmission to move data into /some_category/

### Result:
Data is silently removed, symlink remains broken, transmission shows torrent as valid until "verify data" is called.

### Expected behavior:
Symlmink is removed (possibly with confirmation), data is moved to new location. Or just nothing happens and error occurs.

**Comment by ckerr** [comment] 2023-01-27 07:41
Duplicate of #3695.

**Closed by ckerr** 2023-01-27 07:41 UTC
