### ISSUE TITLE
[git] torrents opened in transmission-gtk don't appear/resume in qt nor daemon

### ISSUE THREAD

**Issue by dchmelik** [transmission/transmission#4073] opened 2022-11-02 07:11 UTC
### What is the issue?

I reported this in Summer (in plain/simple English, but seems to have been misread/ignored/deleted) for git transmission: torrents opened in transmission-gtk don't appear/resume in qt nor daemon (other than ones they all already loaded before the bug, in a much older version, perhaps v3, which I no longer use).  I stated I test each application for each same git version (not mixed versions, which I don't know how, nor presumably know any next complicated aspect I'm asked about, i.e., didn't omit).

Steps
1. In transmission-gtk (in version weeks/months before original bug report, maybe final stable v3) open many torrents: almost 3,000 to 3,200 (possibly testable with some/many fewer).
2. Exit, and 'upgrade' to git.
3. Exit, and start as gtk, and open some tens more torrents, and remember which because they may not appear later (meaning they'll be invisible in the list).
4. Exit, and restart as either qt or daemon, and then check for resume error (the tens new torrents may not appear unless you next exit, and start as gtk, they'll still appear in the gtk), and then exit & restart & check vice-versa (repeat steps two to four over & over, likely with same result).

### Which application of Transmission?

daemon, gtk, qt

### Which version of Transmission?

git after v3 to current

**Comment by ckerr** [comment] 2022-11-02 14:16
Duplicate of https://github.com/transmission/transmission/issues/3676

**Closed by ckerr** 2022-11-02 14:16 UTC
