### ISSUE TITLE
4.0 update corrupt data error

### ISSUE THREAD

**Issue by Audibletoxin** [transmission/transmission#4817] opened 2023-02-11 03:41 UTC
### What is the issue?

After upgrading to 4.0 none of my torrents would complete. They would download normally to 30-40% then throttle down to 0. After downgrading to version 3.0 all the files added on 4.0 had corrupt data errors. Upon removing the files and adding the torrents again in version 3.0 everything downloaded normally.  4.0 was unusable as none of the added files would complete. 

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0

**Comment by dogtopus** [comment] 2023-02-11 05:17
#4583

**Comment by ddbock** [comment] 2023-02-11 20:14
+1

**Comment by ckerr** [comment] 2023-02-11 20:54
Appears to be a duplicate of https://github.com/transmission/transmission/issues/4583 ?

**Closed by ckerr** 2023-02-11 20:54 UTC

**Comment by Audibletoxin** [comment] 2023-02-11 20:56
#4583 specifies his files complete. Mine do not. They generally fail around 30-40%

**Comment by dogtopus** [comment] 2023-02-12 00:32
It's now used to track the corruption issue in general, not just stuck at 99% which is caused by said issue.
