### ISSUE TITLE
Issues when download folder (not incomplete folder) is a remote system

### ISSUE THREAD

**Issue by Zorlin** [transmission/transmission#1655] opened 2021-04-01 05:55 UTC
Hi there!

I'm trying to create a massive farm of Transmission containers for https://riff.cc. We've created some automation based on a community container image, which can be found here - https://github.com/riffcc/sillyradio.

It works perfectly when everything is local to a machine, however, when we change the download directories to point at a MooseFS filesystem instead, on a brand new instance, and start adding torrents... Transmission seems to stop responding to any requests about 100 torrents in.

We're not putting the incomplete folder on MooseFS, just the downloads folder. My preference is strongly to be able to seed everything back to archive.org (which we're pulling torrents from) but I don't have enough storage local to the machine to do that.

My hope was that the incomplete folder would be used for all the initial downloading (which is the case) and as such Transmission wouldn't really be bothered by the "slow" MooseFS speeds, as it would just be moving stuff as it completes.

This is the docker image - https://github.com/dperson/transmission

**Comment by Zorlin** [comment] 2021-04-01 06:04
Interesting... I thought that the container was just running as root, but it looks like it's actually running (at least running Transmission, maybe) as a different user.

**Comment by Zorlin** [comment] 2021-04-01 06:17
After fixing all permissions and ensuring that was all copacetic... the issue remains :(

**Comment by ckerr** [comment] 2022-01-25 17:40
Reading this, I _think_ the root cause is https://github.com/transmission/transmission/issues/2462 but I'm not confident enough in that guess to close this issue yet.

@Zorlin if you use a faster filesystem as the download folder, things work fine, right? And when  you say "stops responding to any requests", you mean the entire app stops responding? And if you were to run Transmission in a debugger and look at the state of the app when it stops responding, it's blocked in a filesystem write?

**Comment by Zorlin** [comment] 2022-01-25 22:46
I'm no longer using Transmission (or sillyradio), so unfortunately can't really check. As far as I remember the entire app stopped, yes - never got as far as running it in a debugger.

The MooseFS FS it was pointed at was plenty fast but had additional latency as a networked file system...

**Closed** 2022-01-26 17:47 UTC
Labels: duplicate
