### ISSUE TITLE
Speed limit not working 4.0

### ISSUE THREAD

**Issue by sqig** [transmission/transmission#4814] opened 2023-02-11 02:07 UTC
### What is the issue?

Hello,
If I have the speed limit on or off the download speed still stays at maximum.
The tortoise logo goes blue but seems not to have any effect.
Thank you
<img width="1372" alt="Screenshot 2023-02-11 at 03 02 09" src="https://user-images.githubusercontent.com/19361341/218233449-db30fdb3-7de0-4c29-adf1-f60c7fe26a2b.png">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0

**Comment by ckerr** [comment] 2023-02-11 02:18
Duplicate of https://github.com/transmission/transmission/issues/4701

**Closed by ckerr** 2023-02-11 02:18 UTC
