### ISSUE TITLE
transmission-daemon.service: Failed with result 'timeout'. Ubuntu Noble Numbat (24.04).

### ISSUE THREAD

**Issue by Sergaly** [transmission/transmission#7138] opened 2024-09-24 11:04 UTC
### What is the issue?

sergaly@home-server:~$ journalctl -xeu transmission-daemon.service
░░ The unit transmission-daemon.service completed and consumed the indicated resources.
Sep 24 13:52:41 home-server systemd[1]: Starting transmission-daemon.service - Transmission BitTorrent Daemon...
░░ Subject: A start job for unit transmission-daemon.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit transmission-daemon.service has begun execution.
░░
░░ The job identifier is 24029.
Sep 24 13:52:41 home-server transmission-daemon[28654]: [2024-09-24 13:52:41.719] web.cc:174: Will verify tracker certs using envvar CURL_CA_BUNDLE: none
Sep 24 13:52:41 home-server transmission-daemon[28654]: [2024-09-24 13:52:41.719] web.cc:176: NB: this only works if you built against libcurl with openssl or gnutls, NOT nss
Sep 24 13:52:41 home-server transmission-daemon[28654]: [2024-09-24 13:52:41.719] web.cc:177: NB: Invalid certs will appear as 'Could not connect to tracker' like many other errors
Sep 24 13:52:41 home-server transmission-daemon[28654]: [2024-09-24 13:52:41.720] rpc-server.cc:836: setting password-enabled to 'false'
Sep 24 13:52:41 home-server transmission-daemon[28654]: [2024-09-24 13:52:41.720] rpc-server.cc:763: Added '127.0.0.1' to host whitelist
Sep 24 13:52:41 home-server transmission-daemon[28654]: [2024-09-24 13:52:41.720] rpc-server.cc:763: Added '::1' to host whitelist
Sep 24 13:52:41 home-server transmission-daemon[28654]: [2024-09-24 13:52:41.720] rpc-server.cc:822: setting our username to ''
Sep 24 13:52:41 home-server transmission-daemon[28654]: [2024-09-24 13:52:41.720] rpc-server.cc:830: setting our salted password to ''
Sep 24 13:52:41 home-server transmission-daemon[28654]: [2024-09-24 13:52:41.720] rpc-server.cc:923: Serving RPC and Web requests from '/usr/share/transmission/public_html'
Sep 24 13:54:41 home-server systemd[1]: transmission-daemon.service: start operation timed out. Terminating.
Sep 24 13:54:42 home-server transmission-daemon[28654]: Closing transmission session... done.
Sep 24 13:54:42 home-server systemd[1]: transmission-daemon.service: Failed with result 'timeout'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit transmission-daemon.service has entered the 'failed' state with result 'timeout'.
Sep 24 13:54:42 home-server systemd[1]: Failed to start transmission-daemon.service - Transmission BitTorrent Daemon.
░░ Subject: A start job for unit transmission-daemon.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit transmission-daemon.service has finished with a failure.
░░
░░ The job identifier is 24029 and the job result is failed.
Sep 24 13:54:42 home-server systemd[1]: transmission-daemon.service: Consumed 58.874s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit transmission-daemon.service completed and consumed the indicated resources.
__________________________________________________
Transmission Log file:
__________________________________________________

[2024-09-24 13:52:42.767] inf session.cc:646 Transmission version 4.0.5 (a6fe2a64aa) starting (session.cc:646)
[2024-09-24 13:52:42.767] dbg cache.cc:123 Maximum cache size set to 4.00 MiB (256 blocks) (cache.cc:123)
[2024-09-24 13:52:42.767] dbg net.cc:328 Bound socket 14 to port 51413 on 0.0.0.0 (net.cc:328)
[2024-09-24 13:52:42.767] inf session.cc:404 Listening to incoming peer connections on [0.0.0.0]:51413 (session.cc:404)
[2024-09-24 13:52:42.767] dbg net.cc:328 Bound socket 15 to port 51413 on :: (net.cc:328)
[2024-09-24 13:52:42.767] inf session.cc:404 Listening to incoming peer connections on [::]:51413 (session.cc:404)
[2024-09-24 13:52:42.767] inf tr-udp.cc:168 Bound UDP IPv4 address [0.0.0.0]:51413 (tr-udp.cc:168)
[2024-09-24 13:52:42.767] inf tr-udp.cc:202 Bound UDP IPv6 address [::]:51413 (tr-udp.cc:202)
[2024-09-24 13:52:42.767] dbg tr-lpd.cc:280 Initialising Local Peer Discovery (tr-lpd.cc:280)
[2024-09-24 13:52:42.767] dbg tr-lpd.cc:399 Local Peer Discovery initialised (tr-lpd.cc:399)
[2024-09-24 13:52:42.767] dbg tr-dht.cc:139 Starting DHT on port 51413 (tr-dht.cc:139)
[2024-09-24 13:52:42.767] dbg rpc-server.cc:836 setting password-enabled to 'true' (rpc-server.cc:836)
[2024-09-24 13:52:42.767] inf rpc-server.cc:763 Added '127.0.0.1' to host whitelist (rpc-server.cc:763)
[2024-09-24 13:52:42.767] inf rpc-server.cc:763 Added '192.168.0.*' to host whitelist (rpc-server.cc:763)
[2024-09-24 13:52:42.767] dbg rpc-server.cc:822 setting our username to 'sergaly' (rpc-server.cc:822)
[2024-09-24 13:52:42.767] dbg rpc-server.cc:830 setting our salted password to '{d324fb92f60083d43c5d39fb267f5a73f34a38561U1vK/4u' (rpc-server.cc:830)
[2024-09-24 13:52:42.767] inf rpc-server.cc:907 Serving RPC and Web requests on 0.0.0.0:9091/transmission/ (rpc-server.cc:907)
[2024-09-24 13:52:42.767] inf rpc-server.cc:713 Listening for RPC and Web requests on '0.0.0.0:9091' (rpc-server.cc:713)
[2024-09-24 13:52:42.767] inf rpc-server.cc:912 Whitelist enabled (rpc-server.cc:912)
[2024-09-24 13:52:42.767] inf rpc-server.cc:917 Password required (rpc-server.cc:917)
[2024-09-24 13:52:42.767] inf rpc-server.cc:923 Serving RPC and Web requests from '/usr/share/transmission/public_html' (rpc-server.cc:923)
[2024-09-24 13:52:42.767] dbg tr-lpd.cc:280 Initialising Local Peer Discovery (tr-lpd.cc:280)
[2024-09-24 13:52:42.767] dbg tr-lpd.cc:399 Local Peer Discovery initialised (tr-lpd.cc:399)
[2024-09-24 13:52:42.767] inf daemon.cc:715 Loading settings from '/var/lib/transmission-daemon/.config/transmission-daemon' (daemon.cc:715)
[2024-09-24 13:52:42.767] inf daemon.cc:751 Requiring authentication (daemon.cc:751)

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.5-1build5

**Comment by tearfur** [comment] 2024-09-25 01:48
Duplicate of #6991.

If you have any findings please report it there.

**Closed by tearfur** 2024-09-25 01:48 UTC
