### ISSUE TITLE
windows: when minimised to tray, magnet links spawn extra process

### ISSUE THREAD

**Issue by mappu** [transmission/transmission#572] opened 2018-04-04 02:02 UTC
Version:
Windows x86_64, `transmission-2.93-x64.msi` ("early preview" from https://transmissionbt.com/ )

Problem:
Clicking a magnet link causes process confusion & lost UI connection

Steps to reproduce:
- Install transmission, local-mode only
- Configure transmission to show the tray icon, and, to not show the Torrent Options dialog
- Close the main window, so only the tray is visible
- Click a magnet link from web browser

The main window does not appear. A second transmission-qt process is launched in the background.
When reopening the main window from the tray, the torrent does not appear, but it is clearly downloading within the second transmission-qt process. Closing all transmission-qt processes and relaunching transmission shows the torrent in a partially-completed state.

**Comment by sala91** [comment] 2020-06-14 11:59
Same with 3.0

**Comment by ckerr** [comment] 2022-02-25 16:24
Duplicate of https://github.com/transmission/transmission/issues/255

**Closed by ckerr** 2022-02-25 16:24 UTC
