### ISSUE TITLE
Slow performance when downloading to SD card

### ISSUE THREAD

**Issue by depler** [transmission/transmission#4282] opened 2022-11-30 07:35 UTC
### What is the issue?

There is very long delay when transmission creating big files (more than 1 Gb) on micro SD card. The buffer size is only 32 Mb, so it should not take too long to write this data, but creating file leads to hanging for a while. Is there any workaround for this? The OS is linux.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

latest

**Comment by ckerr** [comment] 2022-11-30 19:14
Probably better to download to a local disk and then move it to the SD card once completed.

Closing as a duplicate of https://github.com/transmission/transmission/issues/2462

**Closed by ckerr** 2022-11-30 19:14 UTC
Labels: duplicate
