### ISSUE TITLE
Latest nightly crashing on startup on Windows 10

### ISSUE THREAD

**Issue by karimsah** [transmission/transmission#3158] opened 2022-05-30 10:15 UTC
Hi there !
Nightly transmission-3.00+-rd1028510c1-x64 crashes upon startup on Windows 10. I have this in eventvwr : 

```
Faulting application name: transmission-qt.exe, version: 3.0.0.0, time stamp: 0x62914a26
Faulting module name: ntdll.dll, version: 10.0.19041.1682, time stamp: 0x7b5414ec
Exception code: 0xc0000374
Fault offset: 0x00000000000ff249
Faulting process ID: 0x750
Faulting application start time: 0x01d8740c8be32eed
Faulting application path: C:\Program Files\Transmission\transmission-qt.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report ID: fd49feb0-4e72-43c8-8e67-50a758cd861c
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by GaryElshaw** [comment] 2022-05-30 13:26
Appears to be cross-platform #3155

**Comment by ckerr** [comment] 2022-05-30 13:28
Thanks for the report! This is a duplicate of #3153

**Closed by ckerr** 2022-05-30 13:28 UTC

**Comment by karimsah** [comment] 2022-05-30 13:35
Thanks for the answer guys !
FYI I noticed it cause stable 3.0.0 on Windows stopped working spontaneously today :)
Doesn't crash tho, just not working, window staying open
