### ISSUE TITLE
Transmission Web Shortcuts 

### ISSUE THREAD

**Issue by ask1234560** [transmission/transmission#5310] opened 2023-03-28 05:39 UTC
### What is the issue?

Hi All,

Thank you for the project. 

Due to #5054, the `Ctrl + V` and `Ctrl + A`  is not working when adding magnet link ie pasting and selecting all text is not working. 

```
OS - Arch linux
Browser - Brave
```

![image](https://user-images.githubusercontent.com/25929911/228138388-6a267e5d-d7a6-4308-8c60-a6af4cd23551.png)

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.2

**Comment by jinmiaoluo** [comment] 2023-03-28 08:29
Confirmed, https://github.com/transmission/transmission/pull/5054 caused the shortcut key for pasting magnet links and selecting all to not work.

**Comment by ckerr** [comment] 2023-03-28 16:58
Closing as duplicate of https://github.com/transmission/transmission/issues/5298

**Closed by ckerr** 2023-03-28 16:58 UTC
