### ISSUE TITLE
transmission absolutely destroys my disk space by spamming the log file

### ISSUE THREAD

**Issue by tjeulink** [transmission/transmission#3673] opened 2022-08-18 21:35 UTC
whenever transmission encounters a problem, it just spams my syslog full. my current syslog for example is 106gigabytes, all of it is an error transmission encountered and reported, exactly 181622 times per second making it 26 minutes to write 100 gigabytes of data. The latest error causing this for example:

`Aug 18 21:54:29 pop-os transmission-gtk.desktop[62170]: [00007fa63071fb50] vdpau_chroma filter error: video mixer features failure: An invalid handle value was provided.
Aug 18 21:54:29 pop-os transmission-gtk.desktop[62170]: [00007fa63071fb50] vdpau_chroma filter error: video mixer attributes failure: An invalid handle value was provided.
`

**Comment by ckerr** [comment] 2022-08-19 06:55
Duplicate of #2756

This is fixed in the nightlies; 4.0.0-beta.1 coming Real Soon Now

**Closed by ckerr** 2022-08-19 06:55 UTC
