### ISSUE TITLE
(Very) old torrents load up on start up since update

### ISSUE THREAD

**Issue by M4TT-C** [transmission/transmission#5209] opened 2023-03-12 15:14 UTC
### What is the issue?

Since updating to 4.0.1, whenever I start the app it loads up a bunch of torrent links from 2012 that are no longer active. I have to highlight and remove from the list. If I close the app and restart, the same four torrents appear in the list again. 

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1 (e1c6e1be43)

**Comment by ckerr** [comment] 2023-03-12 15:24
Hi @M4TT-C, thanks for reporting this!

I think this is a duplicate of #5053, so I'm going to close this ticket as a dupe.

5053 is fixed by https://github.com/transmission/transmission/pull/5117, which will be included in 4.0.2 later this week.

Thanks again!

**Closed by ckerr** 2023-03-12 15:24 UTC
