### ISSUE TITLE
UDP trackers on nightly builds

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#2767] opened 2022-03-12 23:49 UTC
For the last few days (a week?) i've been seeing various connection issues with trackers either with queuing issues, subsequent failures, looping failures, or, ironically, no trouble connecting to http/s trackers, but none of the usual udp tracker connections will connect. With #2764 landing (thanks Charles), i looked in the message log and saw this. Is there anything i can do to help diagnose what is causing this?

![Screenshot 2022-03-13 at 11 40 45 AM](https://user-images.githubusercontent.com/69029666/158038948-c38a0cee-f0ff-4964-abd6-ad98e71ab4c8.png)

Edit: Okay. Digging in a little i can see how things have run a little awry between the setup at home and where i am for the moment. I opened a port on the router where i'm currently staying and didn't uncheck the 'Automatically map port' preference. My question then is how this preference should behave if an open port is being used? Is this a bug or intended behaviour?

**Comment by ckerr** [comment] 2022-06-17 18:37
Closing as a duplicate of #3239 3285

**Closed by ckerr** 2022-06-17 18:37 UTC
