### ISSUE TITLE
Others files are download even not marked to have it downloaded

### ISSUE THREAD

**Issue by Janaboy** [transmission/transmission#2616] opened 2022-02-13 09:07 UTC
Hi All,

I was trying to find this error as i have this for a long time now, but couldn't find the answer. (Maybe used the wrong keywords).
Currently i am running an Ubuntu Desktop 20.04 with Transmission 3.00.
I use the Tornado app on android to access Transmission and download files.
The error what i will describe i had with Windows and previous Transmission versions as well.
I often download without choosing all files to download in a torrent. but despite i select only 1 or 2 files to download, it always download additional files which are not even selected.
The funny if i delete the file which shouldn't be downloaded the Transmission "crys" that there are missing files.
Any idea how to fix this?

Thanks

Br,
Janaboy

**Comment by ckerr** [comment] 2022-02-14 03:48
Duplicate of https://github.com/transmission/transmission/issues/1105.

**Closed by ckerr** 2022-02-14 03:48 UTC

**Comment by ckerr** [comment] 2022-02-14 03:51
Also, looking at the (removed) screenshots, I think OP is asking for assistance in downloading infringing material. We can't give technical support for that. User blocked from Transmission org for 30 days.
