### ISSUE TITLE
No russian language on Windows 11

### ISSUE THREAD

**Issue by Coockie** [transmission/transmission#5414] opened 2023-04-18 11:33 UTC
### What is the issue?

There is no russian language on Windows 11 see screenshot.
![2023-04-18_16-26-57](https://user-images.githubusercontent.com/6870054/232763172-57f8074c-72b0-4e1c-b245-b228f6b1a790.png)
There is a russian language in flatpak version of transmission on GNU/Linux Mint 21.1 Cinnamon.
Also there is no russian language in .msi setup. See screenshot.
![2023-04-18_16-30-21](https://user-images.githubusercontent.com/6870054/232764012-241f3c0c-afb9-49ac-be03-978fe9558c2b.png)

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.3

**Comment by 00blt00** [comment] 2023-05-05 08:14
learn fuckin language you sons of a bitches, face new reality

**Comment by mikedld** [comment] 2023-05-05 15:46
The fact that MSI setup isn't in Russian hints towards you not having a language pack installed and/or Russian selected in the OS settings, all those phrases come from Windows Installer which we don't ourselves translate.

Russian not being selected in the OS settings is probably the reason Qt client isn't localized as well. Are all the other programs you use localized?

**Comment by Coockie** [comment] 2023-05-05 16:33
>Russian selected in the OS settings

I have default russian installation of Windows 11 Pro.

>Are all the other programs you use localized?

Yes. Also i do not have russian localization in snap transmission-qt on GNU/Linux Mint 21.1 see screenshot.
![Transmission-qt](https://user-images.githubusercontent.com/6870054/236515148-5d9c7b89-f0a7-4452-b22e-eec6d454e01d.png)

**Comment by mikedld** [comment] 2023-05-05 20:49
We don't support Snap and Flatpak packages here.

I have no idea then. Sounds like one more case for #1152.

**Comment by ckerr** [comment] 2023-05-06 04:33
Closing as a duplicate of 1152.

**Closed by ckerr** 2023-05-06 04:33 UTC
