### ISSUE TITLE
Ability to use macOS client as a transmission-daemon controller

### ISSUE THREAD

**Issue by Dexwell** [transmission/transmission#3912] opened 2022-10-08 13:10 UTC
I would love to use the beautiful new Mac app, but my transfers are handled by my NAS. 

I know we have options like Transmission Remote GUI, but can remote control functionality please be built into the official app? That way we can have the best of both worlds: a great native Mac app, and transfers running on an always-on device. 

I'm thinking the title bar in the new transfers window could become a dropdown or something, allowing you to switch between "This Device" transfers and transfers on daemons (or even other Macs/devices) on the network.

**Comment by nevack** [comment] 2022-10-08 18:13
Unfortunately, macOS app itself uses `libtransmission` directly, without RPC indirection.
Adding this feature would require a lot of work to migrate all usages to RPC, properly handle local daemon lifecycle etc.
@ckerr What are your thoughts about this?
I think we previously discussed something about migrating macOS client to RPC connection, like GTK app does.

**Comment by ckerr** [comment] 2022-10-10 15:29
> Adding this feature would require a lot of work to migrate all usages to RPC, properly handle local daemon lifecycle etc.
@ckerr What are your thoughts about this?

I think it would be great if this work happened. I'd absolutely be open to PRs that work on this.

We're currently without a primary macOS dev so there's no timeline for this, but if someone steps up and does the work that would be great.

**Comment by lucian1900** [comment] 2022-12-19 23:06
Would a macOS build of Transmission-Qt be more reasonable? The UX wouldn't be the same, but it would serve a similar purpose.

**Comment by canine-afficionado** [comment] 2023-02-27 04:00
I think a macOS build of Transmission-Qt is the way to go as transmission-remote-gui seems to have been abandoned and we need a client with daemon v4 feature parity.

I don't have any real experience using XCode and haven't developed in C++ for many years. I had a go at building it about a month ago using the instructions [here](https://trac.transmissionbt.com/wiki/BuildingTransmissionQtMac) but couldn't get it to work. Those instructions are 12 years old so probably out of date. We also need to be able to build the qt client without Transmission.app if that's possible.

As @ckerr commented previously there is no macOS dev helping so I'm not sure how to proceed. I was thinking of rolling my own WASM client in Blazor but it's a fair amount of work to just reinvent the wheel.

Anyone got any ideas to proceed from here?

**Comment by GaryElshaw** [comment] 2023-02-27 04:04
Qt on macOS is helped along by having Hombrew installed. You'll need qt@5 or qt@6 installed with Homebrew, and then the normal cmake instructions should work. https://github.com/transmission/transmission#building-transmission-from-git-first-time

**Comment by canine-afficionado** [comment] 2023-02-27 04:11
Thanks @GaryElshaw I do have qt installed via homebrew but was trying to build using Xcode based on those old instructions.

I'll give it a try.

**Comment by nevack** [comment] 2023-02-27 13:21
> Thanks @GaryElshaw I do have qt installed via homebrew but was trying to build using Xcode based on those old instructions.
> 
> 
> 
> I'll give it a try.

Qt version is can only be built with Cmake, Xcode project is solely for macOS "native" GUI

**Comment by canine-afficionado** [comment] 2023-02-27 21:56
Thanks to @GaryElshaw I got transmission-qt to build successfully on my mac (Monterey, Intel) yesterday. It was easy once I knew how. I can't get it to connect to the daemon at the moment but that's a seperate issue.

As per @ckerr question doesn't feel as polished as a native macOS app (like the transmission app itself) but it looks to be useable. Agree that maintaining multiple codebases is a pain in the neck - another option would be to get the web client up to feature parity with the native clients and just use that. If people really want an app it can then just be packaged into Electron or one of it's leaner better alternatives.

**Comment by GaryElshaw** [comment] 2023-02-28 02:37
> I can't get it to connect to the daemon at the moment but that's a seperate issue.

What's going on there @canine-afficionado?

> doesn't feel as polished as a native macOS app

Some polish i've been working on #4376

**Comment by canine-afficionado** [comment] 2023-02-28 03:49
> > I can't get it to connect to the daemon at the moment but that's a seperate issue.
> 
> What's going on there @canine-afficionado?
> 
well.... my seedbox provider only provides remote access over TLS which is fair enough. AFAIK this isn't supported in the qt client like it is in transmission-remote and transmission remote gui. So I've been trying to use stunnel to connect ie:
`client <--http--> stunnel <--https--> rpc` but can't get it working. I think it's something to do with the url redirection on the provider side so I've lodged a ticket with them. Hopefully I can get it working because I'm pretty sick of transmission remote gui which is a bit unreliable and not up to date feature-wise.

> > doesn't feel as polished as a native macOS app
> Some polish i've been working on #4376

very nice @GaryElshaw

**Comment by GaryElshaw** [comment] 2023-02-28 03:54
Best of luck with your provider. I have the best of worlds with my current provider, i know others aren't so lucky.

**Comment by canine-afficionado** [comment] 2023-02-28 04:41
Thanks @GaryElshaw I just got it working using a SSH tunnel and it's pretty good - fast.

Only thing is sometimes the menu bar items are frozen and I can't click them. Do you have this issue?

**Comment by GaryElshaw** [comment] 2023-02-28 04:46
> Only thing is sometimes the menu bar items are frozen and I can't click them. Do you have this issue?

I did have that issue, it usually happened when the client was immediately launched, and then a minute or two later would function correctly. From memory it was happening more frequently with one of the qt versions, but i can't remember which was giving me grief now, but i'm betting it was 6.

**Comment by GaryElshaw** [comment] 2023-02-28 05:23
> This is how I use Transmission now, with transmission-daemon + transmission-qt.

How do i do that? And should we document it?

**Comment by ckerr** [comment] 2023-03-13 04:56
Closing as duplicate of #717.

@GaryElshaw via the session dialog in tr-qt

**Closed by ckerr** 2023-03-13 04:56 UTC
Labels: scope:mac, feature disparity, type:feat

**Comment by vlad-infra-admin** [comment] 2024-03-20 18:39
Same thing here. Missing remote functionality. I don't upload anything directly from my main machine.
Usually using an external server where transmission is running. I am aware of transmission remote gui, transmissonic.
Interface of those apps is pretty messy and heavy. I love simple, functional, reliable interface of original app. 
So I have to use a separate windows VM for now.
Still confused by the closer. Is this functionality already available or not yet?

**Comment by nevack** [comment] 2024-03-20 20:56
> Is this functionality already available or not yet?

It's not. This issue is a duplicate of #717, and that is still open.
