### ISSUE TITLE
Feat: Web UI needs setting page to configure RPC settings

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#4996] opened 2023-02-22 14:57 UTC
### What is the issue?

This is something that should be added because:

1) The Qt and GTK clients have it to a large extent (client feature disparity) 
2) Other clients like qBittorrent allow you to change Web UI settings directly within the Web UI

There's several use-cases for changing the RPC settings within the WebUI. 

- changing the IP whitelist remotely to allow another IP or removing whitelist entries
- changing bruteforce settings to something more stringent remotely
- changing password when away from home
- disabling remote access completely after logoff
- any other relevant rpc settings in the settings.json that people might find important to change from the webui. 

It would also make setup easier for people who use the daemon only instead of the Qt/GTK/Mac clients. 

### Which application of Transmission?

Web client

### Which version of Transmission?

Transmission 4.0.0-dev 9d1a141

**Comment by ckerr** [comment] 2023-02-22 15:59
Hey @Pentaphon,

I think this is a duplicate of https://github.com/transmission/transmission/issues/4819 so I'm closing this one as a duplicate.

Also, "any other relevant rpc settings in the settings.json that people might find important to change from the webui" is too broad for a feature request.

**Closed by ckerr** 2023-02-22 15:59 UTC
