### ISSUE TITLE
Windows 2.94 64bit reports wrong amount of free space

### ISSUE THREAD

**Issue by ghost** [transmission/transmission#602] opened 2018-05-02 07:22 UTC
I have 784GB of free space on a drive according to Windows 10, but Transmission 2.94 64bit for Windows reports the same drive as having 842GB of free space. 

784GB of free space is also ~842,000,000,000 bytes so this is probably where the number is coming from.

**Comment by mikedld** [comment] 2018-05-02 07:35
Related to [TRAC-4747](https://trac.transmissionbt.com/ticket/4747) and [TRAC-5939](https://trac.transmissionbt.com/ticket/5939).

**Comment by ckerr** [comment] 2022-01-27 05:06
Duplicate of https://github.com/transmission/transmission/issues/198

**Closed by ckerr** 2022-01-27 05:06 UTC
