### ISSUE TITLE
Feature request: Stop seeding after a time limit, not just after idle

### ISSUE THREAD

**Issue by ibex-are-goats** [transmission/transmission#1728] opened 2021-06-14 05:36 UTC
An expected feature is killing each torrent a fixed time after completion, not just after idle.

**Comment by nankingrider** [comment] 2021-12-01 08:01
I need this too, as most PT sites now use H&R instead of ratio-limit. 

this will be a huge useful feature for pt-ers.

**Comment by ckerr** [comment] 2022-02-25 03:52
Duplicate of #111

**Closed by ckerr** 2022-02-25 03:52 UTC
Labels: enhancement
