### ISSUE TITLE
Weird UI bug showing upload traffic but no connected peer (c7466b3ff4)

### ISSUE THREAD

**Issue by robd003** [transmission/transmission#3643] opened 2022-08-14 22:38 UTC
Seeing an issue where the UI shows 0 of 1 peers being seeded however there is upload traffic. No peers show up in the Peers inspector.

<img width="202" alt="Screen Shot 2022-08-14 at 6 36 08 PM" src="https://user-images.githubusercontent.com/571328/184557367-eb35a642-3381-4e9a-a7fd-c2cac49ef42b.png">

This is on build c7466b3ff4

**Comment by Coeur** [comment] 2022-10-07 18:38
Kindly clarify which client: GTK or macOS?

**Comment by GaryElshaw** [comment] 2022-10-07 20:13
That's macOS.

**Comment by Coeur** [comment] 2022-10-07 20:56
From the string, it's either macOS or Web.

https://github.com/transmission/transmission/blob/aeaa6ca52fcd979a6aaa069b219625c6ba18aed7/web/src/torrent-row.js#L127-L132
https://github.com/transmission/transmission/blob/aeaa6ca52fcd979a6aaa069b219625c6ba18aed7/macosx/Torrent.mm#L1165-L1166

**Comment by ckerr** [comment] 2023-02-02 04:47
Is this still happening?

**Comment by robd003** [comment] 2023-02-02 06:30
Haven't seen this lately.

**Comment by ckerr** [comment] 2023-02-02 06:39
OK. Since neither of us can reproduce this II'm going to close this for now. Please do re-report it if it comes back :shrug:

**Closed by ckerr** 2023-02-02 06:39 UTC
Labels: needs clarification
