### ISSUE TITLE
Transmission web UI needs refresh to apply Display changes

### ISSUE THREAD

**Issue by WilliUreta** [transmission/transmission#4867] opened 2023-02-13 17:56 UTC
### What is the issue?

In the new web UI for transmission hosted via Docker, the Display buttons for "Reverse Sort" and "Compact rows" need a refresh to update the view of the web. 
Changing the "Sort by" works correctly
![image](https://user-images.githubusercontent.com/62305530/218535498-fc512d27-9c67-447c-9edc-abff230f89a8.png)

### Which application of Transmission?

Web client

### Which version of Transmission?

Transmission 4.0.0 280ace12f8

**Comment by ckerr** [comment] 2023-02-13 18:03
@WilliUreta thanks for reporting this!

This is a duplicate of #4830 which is fixed by #4839.

**Closed by ckerr** 2023-02-13 18:03 UTC
