### ISSUE TITLE
Download List Order Does Not Stick

### ISSUE THREAD

**Issue by Agnapot** [transmission/transmission#6163] opened 2023-10-25 06:42 UTC
### What is the issue?

When re-opening Transmission the order that I have dragged the incomplete downloads is not saved.  

Further, when re-ordering it for the first time, the download list changes again to a new order.

I have attached 3 images, the order they appear when first opened ("First Order"), the order they rearrange in after dragging the top torrent to the bottom ("Tried to Rearrange Order"), and the order I rearranged them in ("Preferred Order").

This Rearranged Order does save some information from the first rearrangement, for example note that the item labeled "Torrent 1" is directly underneath "Torrent 10", which is where it was moved, but then Torrent 10 was moved to a new place and seemed to take "Torrent 1" with it.  If I move a different torrent, it stays below the one above it that it was moved next to, but everything else arranges into the same order as before.

Wacky!

First Opened Order:
<img width="806" alt="First Opened Order" src="https://github.com/transmission/transmission/assets/140664603/eeb8a1a7-2820-4d48-b381-f16474a157aa">

Tried to Rearrange Order:
<img width="806" alt="Tried to Rearrange Order" src="https://github.com/transmission/transmission/assets/140664603/51fa4f48-bbdd-4b8d-ac16-9867dd6fe499">

Arranged Order:
<img width="806" alt="Arranged Order" src="https://github.com/transmission/transmission/assets/140664603/75d7ef65-baf4-4c93-8284-8b91608d3f5c">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.4 (24077e3511)

**Comment by killemov** [comment] 2023-10-25 07:46
Please search before you post.
Duplicate of #327.
Related to #5323, #5551, #5970.

**Comment by tearfur** [comment] 2023-10-25 08:26
Thank you for your detailed screenshots though, please keep up this practice if you are reporting any other issues in the future. It helps a lot.

**Closed by tearfur** 2023-10-25 08:26 UTC
Labels: duplicate
