### ISSUE TITLE
printf() fmt string translation errors cause Transmission to crash

### ISSUE THREAD

**Issue by frague59** [transmission/transmission#1353] opened 2020-07-09 18:25 UTC
Hi, 

transmission-gtk starts normally then segfault after a few seconds.

When starting from terminal:
```sh 
$ transmission-gtk 

(transmission-gtk:16862): Gtk-CRITICAL **: 20:13:50.586: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
*** invalid %N$ use detected ***
Abandon
```
My version:
```sh
$ transmission-gtk -v
transmission-gtk 3.00 (bb6b5a062e)
```

Thanks for this great app !

**Comment by ckerr** [comment] 2020-07-27 23:51
Hi @frague59, thanks for reporting this crash.

Would it be possible for you to get a backtrace from a dbgsym build using these steps: https://wiki.debian.org/HowToGetABacktrace ? That would make tracking this down *much* easier, since I'm not seeing this crash myself.

**Comment by wjt** [comment] 2020-10-14 09:37
Reproduced this in the [Flathub](https://flathub.org/apps/details/com.transmissionbt.Transmission) version, using the "English" torrent file from https://endlessos.com/download/. Backtrace:

https://gist.github.com/wjt/ce2bcd92a4c6a076fd902379e234c829

Offending call:

```
(gdb) l
263	                        ngettext("peer", "peers", st->peersConnected), (int)(100.0 * st->metadataPercentComplete));
264	                }
265	                else if (st->peersSendingToUs != 0 && st->webseedsSendingToUs != 0)
266	                {
267	                    /* Downloading from 2 of 3 peer (s) and 2 webseed (s) */
268	                    g_string_append_printf(gstr, _("Downloading from %1$'d of %2$'d %3$s and %4$'d %5$s"), st->peersSendingToUs,
269	                        st->peersConnected, ngettext("peer", "peers", st->peersConnected), st->webseedsSendingToUs,
270	                        ngettext("web seed", "web seeds", st->webseedsSendingToUs));
271	                }
272	                else if (st->webseedsSendingToUs != 0)
```

My locale is set to `fr_FR.utf8`. I don't know for sure what locale @frague59 uses but based on name & location I would assume it's the same! I'll expand the gettext calls:

```
(gdb) p (gchar*) _("Downloading from %1$'d of %2$'d %3$s and %4$'d %5$s")
$4 = (gchar *) 0x7ffff52fb142 "Téléchargement à partir %1$'d sur %2'd %3$s et %4$'d %5$s"

(gdb) p (char *) ngettext("peer", "peers", st->peersConnected)
$6 = 0x7ffff52fe26a "pairs"

(gdb) p (char *) ngettext("web seed", "web seeds", st->webseedsSendingToUs)
$7 = 0x7ffff52fe3bd "semences Web"
```

The translation [here](https://github.com/transmission/transmission/blob/3.00/po/fr.po#L1348) is malformed:

```
wjt@toolbox:~/src/transmission/transmission☭ LANG=C.utf-8 msgfmt -o /dev/null --check po/fr.po                                                                 
msgfmt: po/fr.po: warning: PO file header fuzzy
                  warning: older versions of msgfmt will give an error on this
po/fr.po:17: warning: header field 'Project-Id-Version' still has the initial default value
po/fr.po:1348: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the character ''' is not a valid conversion specifier.
msgfmt: found 1 fatal error
```

The issue is the `%2'd`, which should be `%2$'d`.

There are a number of other translations with fatal warnings detected by `msgfmt`:

```
wjt@toolbox:~/src/transmission/transmission☭ (for i in po/*.po; do if ! msgfmt -o /dev/null --check $i >/dev/null 2>/dev/null ; then echo $i; fi; done) | LANG=en_GB.utf8 xargs -I_ msgfmt -o /dev/null --check _ 2>&1 | grep -v warning:
po/af.po:673: format specifications in 'msgid' and 'msgstr' for argument 2 are not the same
msgfmt: found 1 fatal error
po/ar.po:797: number of format specifications in 'msgid_plural' and 'msgstr[3]' does not match
po/ar.po:808: number of format specifications in 'msgid_plural' and 'msgstr[3]' does not match
msgfmt: found 6 fatal errors
po/be.po:797: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
po/be.po:806: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
msgfmt: found 2 fatal errors
po/fo.po:789: number of format specifications in 'msgid_plural' and 'msgstr[1]' does not match
po/fo.po:796: number of format specifications in 'msgid_plural' and 'msgstr[1]' does not match
msgfmt: found 2 fatal errors
po/fr.po:1405: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the character ''' is not a valid conversion specifier.
msgfmt: found 1 fatal error
po/he.po:416: 'msgstr[0]' is not a valid C format string, unlike 'msgid_plural'. Reason: The string refers to argument number 3 but ignores argument number 2.
po/he.po:1100: 'msgstr[0]' is not a valid C format string, unlike 'msgid_plural'. Reason: The string refers to argument number 2 but ignores argument number 1.
msgfmt: found 2 fatal errors
po/hr.po:795: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
po/hr.po:803: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
msgfmt: found 2 fatal errors
po/hu.po:2207: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 3, the token after '<' is not the name of a format specifier macro. The valid macro names are listed in ISO C 99 section 7.8.1.
po/hu.po:2212: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 3, the token after '<' is not the name of a format specifier macro. The valid macro names are listed in ISO C 99 section 7.8.1.
msgfmt: found 2 fatal errors
po/is.po:789: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
po/is.po:796: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
msgfmt: found 2 fatal errors
po/nb.po:2112: format specifications in 'msgid' and 'msgstr' for argument 1 are not the same
msgfmt: found 1 fatal error
po/oc.po:2385: number of format specifications in 'msgid' and 'msgstr' does not match
msgfmt: found 1 fatal error
po/ru.po:799: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
po/ru.po:808: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
msgfmt: found 2 fatal errors
po/te.po:789: number of format specifications in 'msgid_plural' and 'msgstr[1]' does not match
msgfmt: found 1 fatal error
po/tr.po:2241: format specifications in 'msgid' and 'msgstr' for argument 1 are not the same
msgfmt: found 1 fatal error
```

**Comment by wjt** [comment] 2020-10-14 09:38
I would send a patch but I think the fix needs to be made in https://www.transifex.com/transmissionbt/transmissionbt/ then synced back into the Git repo.

**Comment by wjt** [comment] 2020-10-14 18:44
Consider enabling “Variable substitution specifiers (like "%s") are preserved in the translations.” in https://www.transifex.com/transmissionbt/settings/validations/

**Comment by mikedld** [comment] 2020-10-18 21:57
It seems to be enabled by default (set to "error"). The issue is that Transifex doesn't detect all the format "variables" (in this case, those using `'` XSI extension; but there're other cases as well), and so is unable to properly enforce the rule.

**Comment by wjt** [comment] 2020-10-19 07:55
I suggest running `msgfmt --check` when importing. (Now I remember finding the same limitation when some dodgy translations got imported into Endless OS!)

**Comment by mimi89999** [comment] 2020-10-22 16:07
Hello,
I also have this issue.
Same version (`transmission-gtk 3.00 (bb6b5a062e)`), same OS (Debian testing) and same locale (`fr_FR.utf8`).

**Comment by neitsab** [comment] 2020-12-05 02:39
Just been hit by this bug on Arch Linux with `fr_FR.utf8` locale as well. I was downloading the [latest Arch ISO](https://www.archlinux.org/download/) and two core dumps occurred in less than a minute (the application crashed once, then I reopened it to finish the download and it crashed again). System details and coredump if that still may help:

```
% uname -a
Linux hostname 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux
% localectl 
   System Locale: LANG=fr_FR.utf8
       VC Keymap: fr-latin9
      X11 Layout: fr
     X11 Variant: oss
% transmission-gtk -v    
transmission-gtk 3.00 (bb6b5a062e)

% journalctl -f
...
déc. 05 03:23:06 hostname transmission-gtk.desktop[44796]: *** invalid %N$ use detected ***
...
déc. 05 03:23:06 hostname systemd[1]: Started Process Core Dump (PID 45546/UID 0).
...
éc. 05 03:23:07 hostname systemd-coredump[45547]: [🡕] Process 44796 (transmission-gt) of user 1000 dumped core.
                                                   
                                                   Stack trace of thread 44796:
                                                   #0  0x00007f44393fc615 raise (libc.so.6 + 0x3d615)
                                                   #1  0x00007f44393e5862 abort (libc.so.6 + 0x26862)
                                                   #2  0x00007f443943e5e8 __libc_message (libc.so.6 + 0x7f5e8)
                                                   #3  0x00007f443943e61a __libc_fatal (libc.so.6 + 0x7f61a)
                                                   #4  0x00007f443942912c printf_positional (libc.so.6 + 0x6a12c)
                                                   #5  0x00007f443942ae2d __vfprintf_internal (libc.so.6 + 0x6be2d)
                                                   #6  0x00007f443943d4a5 __vasprintf_internal (libc.so.6 + 0x7e4a5)
                                                   #7  0x00007f4439c0b0c0 g_vasprintf (libglib-2.0.so.0 + 0xa20c0)
                                                   #8  0x00007f4439bde126 g_string_append_vprintf (libglib-2.0.so.0 + 0x75126)
                                                   #9  0x00007f4439bde3b5 g_string_append_printf (libglib-2.0.so.0 + 0x753b5)
                                                   #10 0x0000555ce64eca4e n/a (transmission-gtk + 0x3ba4e)
                                                   #11 0x0000555ce64ed171 n/a (transmission-gtk + 0x3c171)
                                                   #12 0x00007f443a0fca81 n/a (libgtk-3.so.0 + 0xd3a81)
                                                   #13 0x00007f443a101976 gtk_cell_renderer_get_preferred_width (libgtk-3.so.0 + 0xd8976)
                                                   #14 0x00007f443a102a2f n/a (libgtk-3.so.0 + 0xd9a2f)
                                                   #15 0x00007f443a102048 gtk_cell_renderer_get_aligned_area (libgtk-3.so.0 + 0xd9048)
                                                   #16 0x00007f443a0fb5b3 n/a (libgtk-3.so.0 + 0xd25b3)
                                                   #17 0x00007f443a104843 n/a (libgtk-3.so.0 + 0xdb843)
                                                   #18 0x00007f443a0fb9ed n/a (libgtk-3.so.0 + 0xd29ed)
                                                   #19 0x00007f443a358582 n/a (libgtk-3.so.0 + 0x32f582)
                                                   #20 0x00007f443a3403c5 n/a (libgtk-3.so.0 + 0x3173c5)
                                                   #21 0x00007f443a26521f n/a (libgtk-3.so.0 + 0x23c21f)
                                                   #22 0x00007f443a33a9f7 n/a (libgtk-3.so.0 + 0x3119f7)
                                                   #23 0x00007f443a36481a n/a (libgtk-3.so.0 + 0x33b81a)
                                                   #24 0x00007f443a1300e1 gtk_container_propagate_draw (libgtk-3.so.0 + 0x1070e1)
                                                   #25 0x00007f443a1301ee n/a (libgtk-3.so.0 + 0x1071ee)
                                                   #26 0x00007f443a296d80 n/a (libgtk-3.so.0 + 0x26dd80)
                                                   #27 0x00007f443a130a2d n/a (libgtk-3.so.0 + 0x107a2d)
                                                   #28 0x00007f443a13c73b n/a (libgtk-3.so.0 + 0x11373b)
                                                   #29 0x00007f443a28e801 n/a (libgtk-3.so.0 + 0x265801)
                                                   #30 0x00007f443a36481a n/a (libgtk-3.so.0 + 0x33b81a)
                                                   #31 0x00007f443a1300e1 gtk_container_propagate_draw (libgtk-3.so.0 + 0x1070e1)
                                                   #32 0x00007f443a1301ee n/a (libgtk-3.so.0 + 0x1071ee)
                                                   #33 0x00007f443a0de13d n/a (libgtk-3.so.0 + 0xb513d)
                                                   #34 0x00007f443a130a2d n/a (libgtk-3.so.0 + 0x107a2d)
                                                   #35 0x00007f443a13c73b n/a (libgtk-3.so.0 + 0x11373b)
                                                   #36 0x00007f443a0de601 n/a (libgtk-3.so.0 + 0xb5601)
                                                   #37 0x00007f443a36481a n/a (libgtk-3.so.0 + 0x33b81a)
                                                   #38 0x00007f443a1300e1 gtk_container_propagate_draw (libgtk-3.so.0 + 0x1070e1)
                                                   #39 0x00007f443a1301ee n/a (libgtk-3.so.0 + 0x1071ee)
                                                   #40 0x00007f443a3842fc n/a (libgtk-3.so.0 + 0x35b2fc)
                                                   #41 0x00007f443a36481a n/a (libgtk-3.so.0 + 0x33b81a)
                                                   #42 0x00007f443a37228b n/a (libgtk-3.so.0 + 0x34928b)
                                                   #43 0x00007f443a20d109 gtk_main_do_event (libgtk-3.so.0 + 0x1e4109)
                                                   #44 0x00007f4439f66413 n/a (libgdk-3.so.0 + 0x3c413)
                                                   #45 0x00007f4439f6f152 n/a (libgdk-3.so.0 + 0x45152)
                                                   #46 0x00007f4439f740fb n/a (libgdk-3.so.0 + 0x4a0fb)
                                                   #47 0x00007f4439f742f9 n/a (libgdk-3.so.0 + 0x4a2f9)
                                                   #48 0x00007f4439ccc98a g_signal_emit_valist (libgobject-2.0.so.0 + 0x2f98a)
                                                   #49 0x00007f4439cccb00 g_signal_emit (libgobject-2.0.so.0 + 0x2fb00)
                                                   #50 0x00007f4439f6a170 n/a (libgdk-3.so.0 + 0x40170)
                                                   #51 0x00007f4439f578ac n/a (libgdk-3.so.0 + 0x2d8ac)
                                                   #52 0x00007f4439bbc134 n/a (libglib-2.0.so.0 + 0x53134)
                                                   #53 0x00007f4439bbb8f4 g_main_context_dispatch (libglib-2.0.so.0 + 0x528f4)
                                                   #54 0x00007f4439c0f821 n/a (libglib-2.0.so.0 + 0xa6821)
                                                   #55 0x00007f4439bba121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                                                   #56 0x00007f4439dc3d1e g_application_run (libgio-2.0.so.0 + 0xccd1e)
                                                   #57 0x0000555ce64d5658 main (transmission-gtk + 0x24658)
                                                   #58 0x00007f44393e7152 __libc_start_main (libc.so.6 + 0x28152)
                                                   #59 0x0000555ce64d589e _start (transmission-gtk + 0x2489e)
                                                   
                                                   Stack trace of thread 44799:
                                                   #0  0x00007f44394b446f __poll (libc.so.6 + 0xf546f)
                                                   #1  0x00007f4439c0f7af n/a (libglib-2.0.so.0 + 0xa67af)
                                                   #2  0x00007f4439bba121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                                                   #3  0x00007f4439bba172 n/a (libglib-2.0.so.0 + 0x51172)
                                                   #4  0x00007f4439be8d31 n/a (libglib-2.0.so.0 + 0x7fd31)
                                                   #5  0x00007f44395913e9 start_thread (libpthread.so.0 + 0x93e9)
                                                   #6  0x00007f44394bf293 __clone (libc.so.6 + 0x100293)
                                                   
                                                   Stack trace of thread 44805:
                                                   #0  0x00007f44394b6b7b __select (libc.so.6 + 0xf7b7b)
                                                   #1  0x0000555ce651e121 n/a (transmission-gtk + 0x6d121)
                                                   #2  0x0000555ce64fc86a n/a (transmission-gtk + 0x4b86a)
                                                   #3  0x00007f44395913e9 start_thread (libpthread.so.0 + 0x93e9)
                                                   #4  0x00007f44394bf293 __clone (libc.so.6 + 0x100293)
                                                   
                                                   Stack trace of thread 44802:
                                                   #0  0x00007f44394b446f __poll (libc.so.6 + 0xf546f)
                                                   #1  0x00007f4439c0f7af n/a (libglib-2.0.so.0 + 0xa67af)
                                                   #2  0x00007f4439bba121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                                                   #3  0x00007f443a7f0c0e n/a (libdconfsettings.so + 0x5c0e)
                                                   #4  0x00007f4439be8d31 n/a (libglib-2.0.so.0 + 0x7fd31)
                                                   #5  0x00007f44395913e9 start_thread (libpthread.so.0 + 0x93e9)
                                                   #6  0x00007f44394bf293 __clone (libc.so.6 + 0x100293)
                                                   
                                                   Stack trace of thread 44803:
                                                   #0  0x00007f44394bf5de epoll_wait (libc.so.6 + 0x1005de)
                                                   #1  0x00007f4439b3f9e6 n/a (libevent-2.1.so.7 + 0x2f9e6)
                                                   #2  0x00007f4439b348c9 event_base_loop (libevent-2.1.so.7 + 0x248c9)
                                                   #3  0x0000555ce6514209 n/a (transmission-gtk + 0x63209)
                                                   #4  0x0000555ce64fc86a n/a (transmission-gtk + 0x4b86a)
                                                   #5  0x00007f44395913e9 start_thread (libpthread.so.0 + 0x93e9)
                                                   #6  0x00007f44394bf293 __clone (libc.so.6 + 0x100293)
                                                   
                                                   Stack trace of thread 44801:
                                                   #0  0x00007f44394b446f __poll (libc.so.6 + 0xf546f)
                                                   #1  0x00007f4439c0f7af n/a (libglib-2.0.so.0 + 0xa67af)
                                                   #2  0x00007f4439bbae43 g_main_loop_run (libglib-2.0.so.0 + 0x51e43)
                                                   #3  0x00007f4439df8fe8 n/a (libgio-2.0.so.0 + 0x101fe8)
                                                   #4  0x00007f4439be8d31 n/a (libglib-2.0.so.0 + 0x7fd31)
                                                   #5  0x00007f44395913e9 start_thread (libpthread.so.0 + 0x93e9)
                                                   #6  0x00007f44394bf293 __clone (libc.so.6 + 0x100293)
déc. 05 03:23:07 zenbook systemd[1]: systemd-coredump@3-45546-0.service: Succeeded.
```

Can we help with something? Thanks for your work maintaining Transmission!

**Comment by neitsab** [comment] 2020-12-05 02:54
(Note that it is the first time it happens while I've been using Transmission on this machine for over a week on and off; what may have triggered it this time is maybe the speed of the download: being behind fibre optic connection the ISO download speed  quickly picked up pace and peaked at 40 MB/s... I was downloading to `tmpfs` as well.)

**Comment by oopen** [comment] 2021-01-16 15:38
Same problem, if I add any torrent to transmission,
after a few seconds it close with :

`*** invalid %N$ use detected ***`

transmission-gtk 3.00 (bb6b5a062e)

Manjaro Linux
Release: 20.2.1
Kernel: 5.10.2-2-MANJARO

**Comment by ABelliqueux** [comment] 2021-03-22 17:49
I can reproduce in transmission-gtk 3.00 (bb6b5a0),  Manjaro 20.2.1 with kernel 5.10.18-1-MANJARO.

Running with `LANG=C transmission-gtk` seems to avoid the issue.

**Comment by mimi89999** [comment] 2021-03-28 13:01
> It seems to be enabled by default (set to "error"). The issue is that Transifex doesn't detect all the format "variables" (in this case, those using `'` XSI extension; but there're other cases as well), and so is unable to properly enforce the rule.

Maybe that could be added to CI, so any such issue would be quickly detected and the translation could be fixed or removed? I could correct the translations on Transifex, but I'm waiting for my request to be accepted.

**Comment by Rawleenc** [comment] 2021-05-10 12:47
Same issue here with gentoo's stable ebuild https://packages.gentoo.org/packages/net-p2p/transmission 3.00-r1
However, compiling without the `nls` use flag in order to disable translations fix the issue.
There is my test case : 
- Locale fr_FR.utf8
- Downloading the `manjaro-xfce-21.0.4-210506-linux510.iso.torrent` the currently latest Manjaro XFCE ISO
- Transmission crash after few seconds with this message : 
```
*** invalid %N$ use detected ***
Abandon (core dumped)
```

**Comment by m-i-k-e-e** [comment] 2021-07-11 16:32
Hi All, 
As a workaround, this one worked for me : 
`LC_ALL=en_GB transmission-gtk`

**Comment by legluondunet** [comment] 2021-12-19 20:05
I have this issue on Arcolinux and Transmission 3.00, transmission crashes some seconds after launch.
If I use this workaround: 
LANG=C transmission-gtk
It is stable.

**Comment by ckerr** [comment] 2022-02-18 18:55
There's an open issue https://github.com/transmission/transmission/issues/2551 for converting some of the benc and json serialization to use the [{fmt}](https://fmt.dev/latest/index.html) library for formatting.

It [also supports positional arguments](https://fmt.dev/latest/index.html#format-api) which IMO would be a clean + safe fix for this issue.

**Closed** 2022-03-21 14:15 UTC
Labels: scope:gtk, os:linux, pr welcome

**Comment by pierre04** [comment] 2023-10-02 09:42
Hello, the problem is still present here.
Debian 12 stable
Transmission 3.00 (bb6b5a062e)

Fixed with $ LANG=C  transmission-gtk

**Comment by nevack** [comment] 2023-10-02 10:07
> Transmission 3.00

I believe this was fixed in Transmission 4.+

**Comment by pierre04** [comment] 2023-10-02 10:09
Ok, so I should rather post a bug on Debian. Thank you.
