### ISSUE TITLE
1366x768 and smaller screens on Firefox result in poor formatting of top of WebUI settings sidebar

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#5337] opened 2023-04-02 02:23 UTC
### What is the issue?

On a 1366x768 Windows laptop, here's what the 4.0.2 WebUI looks like on each browser in fully maximized window mode: 

It looks fine on a 1600x900 laptop and 1080p desktop on both Firefox and Chromium browsers. 

Can anybody confirm? 

**Firefox:** 

![firefox](https://user-images.githubusercontent.com/49374058/225548537-697e6b8f-1dc6-4273-b626-2b6e3b08510d.png)

**Microsoft Edge (Chromium-based)** 

![edge](https://user-images.githubusercontent.com/49374058/225548615-8bed6ab3-cdff-47dc-9ff1-ddc03eea578d.png)

**Vivaldi (Chromium-based)** 

![vivaldi](https://user-images.githubusercontent.com/49374058/225548930-7c4856c7-c4a3-40e3-9e64-fa38fd836c79.png)

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.2

**Comment by sfan5** [comment] 2023-04-02 22:21
You mean parts are missing? #5299 then

**Comment by ckerr** [comment] 2023-04-13 00:23
Closing as a duplicate of #5299 based on previous comment

**Closed by ckerr** 2023-04-13 00:23 UTC
