### ISSUE TITLE
WIKI: Editing Configuration Files: 'queue-download-size' should be 'download-queue-size'

### ISSUE THREAD

**Issue by 01100001** [transmission/transmission#2257] opened 2021-12-01 15:57 UTC
Refer to: <https://github.com/transmission/transmission/wiki/Editing-Configuration-Files>

Under **GTK / Daemon / CLI** > **Options** > **Queuing**, this:

> *   **queue-stalled-enabled:** Boolean (default = true) When true, torrents that have not shared data for `queue-stalled-minutes` are treated as 'stalled' and are not counted against the `queue-download-size` and `seed-queue-size` limits.

Should be:

> *   **queue-stalled-enabled:** Boolean (default = true) When true, torrents that have not shared data for `queue-stalled-minutes` are treated as 'stalled' and are not counted against the `download-queue-size` and `seed-queue-size` limits.

...right?

**Comment by ckerr** [comment] 2022-02-25 03:54
Duplicate of #712.

Fixed by https://github.com/transmission/transmission/issues/1453

**Closed by ckerr** 2022-02-25 03:54 UTC
