### ISSUE TITLE
Units missing when displaying certain speeds

### ISSUE THREAD

**Issue by stonegray** [transmission/transmission#2643] opened 2022-02-18 13:45 UTC
At certain download speeds, the download speed display is unexpectedly truncated. 

I'm running the latest 3.00+ (17cb155451) on macOS 12.0.1. 

The display is at it's default `@2x` scaling, native `2880x1800` looks like `1440x900`. 

The observed truncation (only at specific speeds)
![](https://gist.github.com/stonegray/b48121f5a7692fef281de3e2e126fb43/raw/3e30285e57504be70c75ad552e62d19b4be1f28b/Screen%2520Shot%25202022-02-18%2520at%25208.31.10%2520AM.png)

Other higher and lower speeds display fine:

![](https://gist.github.com/stonegray/b48121f5a7692fef281de3e2e126fb43/raw/3e30285e57504be70c75ad552e62d19b4be1f28b/Screen%2520Shot%25202022-02-18%2520at%25208.31.24%2520AM.png)

![](https://gist.github.com/stonegray/b48121f5a7692fef281de3e2e126fb43/raw/ded6ba36d7f7d9b87e8c8086a4483fe2ee3989ba/Screen%2520Shot%25202022-02-18%2520at%25208.38.00%2520AM.png)

I've observed this at 33.94MB/s, and 34.98MB/s, and 40.36MB/s, with other values displaying fine.

**Comment by ckerr** [comment] 2022-02-18 19:44
Thanks for reporting this!

This appears to be a duplicate of https://github.com/transmission/transmission/issues/1687

**Closed by ckerr** 2022-02-18 19:44 UTC
