### ISSUE TITLE
FIX THE RESUME ALL TRANSFERS BUTTON

### ISSUE THREAD

**Issue by friedhopper** [transmission/transmission#6063] opened 2023-10-02 13:32 UTC
### What is the issue?

This issue has been present for the last three builds. How about a little attention?

### Which application of Transmission?

macOS app

**Comment by ckerr** [comment] 2023-10-02 15:21
duplicate of #4889.

user blocked for 1 week for being hostile/aggressive.

**Closed by ckerr** 2023-10-02 15:21 UTC
Labels: scope:mac, needs confirmation
