### ISSUE TITLE
Auto-add torrents from 'watch' folder not working on macOS

### ISSUE THREAD

**Issue by realcam** [transmission/transmission#5045] opened 2023-02-25 10:37 UTC
### What is the issue?

Like the title says. This applies to macOS 13.2.1 (22D68) (M1Pro).

Torrent files added to the watch folder specified under 'Settings/Transfers/Auto add' no longer get picked up by transmission. To be more specific torrent files present in the folder get picked up when starting up transmission, but while transmission is running any torrent files added to that folder are being ignored.

I thought this could also be a macOS upgrade (permission) problem, but this appears to be working just fine with pre v4.0 transmission clients. From v4.0 onwards it stopped working.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1 (e1c6e1be43)

**Comment by ckerr** [comment] 2023-02-25 12:29
Hey @realcam thanks for reporting this.

I think this is a duplicate of https://github.com/transmission/transmission/issues/4683 so I'm closing this one as a dupe.

**Closed by ckerr** 2023-02-25 12:29 UTC
