### ISSUE TITLE
Folders names in torrents are ignored when assigning groups by names

### ISSUE THREAD

**Issue by ThomasPzzz** [transmission/transmission#2724] opened 2022-03-02 13:34 UTC
Hi,

When assigning up groups to new transfers based on name, folders names in torrents are ignored, only the files names are taking in account. At least under MacOS.

Cheers.

**Comment by ckerr** [comment] 2022-03-03 01:02
Hi @ThomasPzzz, thanks for reporting this. I _think_ this is a duplicate of https://github.com/transmission/transmission/issues/2028 so I'm closing this issue.

**Closed by ckerr** 2022-03-03 01:02 UTC
