### ISSUE TITLE
"unable to get local issuer certificate" error

### ISSUE THREAD

**Issue by cwbsw** [transmission/transmission#567] opened 2018-03-30 10:37 UTC
Environment: 

Win 10 64bit 1709, msys2, curl 7.59.0 built against openssl 1.0.2o, Transmission latest git version

Error info, when announce:
```
[2018-03-30 18:14:02.205] web will verify tracker certs using envvar CURL_CA_BUNDLE: none (D:/msys64/home/ae/Transmission/libtransmission/web.c:383)
[2018-03-30 18:14:02.205] web NB: this only works if you built against libcurl with openssl or gnutls, NOT nss (D:/msys64/home/ae/Transmission/libtransmission/web.c:384)
[2018-03-30 18:14:02.205] web NB: invalid certs will show up as 'Could not connect to tracker' like many other errors (D:/msys64/home/ae/Transmission/libtransmission/web.c:385)
[2018-03-30 18:14:03.204] Alpha.zip Could not connect to tracker (D:/msys64/home/ae/Transmission/libtransmission/announcer.c:1038)
```
```
*   Trying 12.34.56.78...
* TCP_NODELAY set
* Connected to example.org (12.34.56.78) port 443 (#1)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* SSL certificate problem: unable to get local issuer certificate
* stopped the pause stream!
* Closing connection 1
```

This error only happens under transmission git version built against curl-openssl, transmission 2.93 is ok, transmission git version built against curl-winssl works well too.

curl was already configured with `--with-ca-bundle=/mingw64/ssl/certs/ca-bundle.crt`, curl command-line tool works well, `CURL_CA_BUNDLE=/mingw64/ssl/certs/ca-bundle.crt transmission-daemon -f` also works well.

**Comment by ckerr** [comment] 2022-01-23 16:51
This appears to be a duplicate of #446.

**Closed by ckerr** 2022-01-23 16:51 UTC
