### ISSUE TITLE
[macOS] "Keep incomplete files in…" setting doesn't work as expected

### ISSUE THREAD

**Issue by magicgoose** [transmission/transmission#163] opened 2017-01-29 16:48 UTC
Some files are kept in _incomplete_ directory even after they are completely done.

Also, some other files are moved to _completed_ directory even if they are not complete (this is even indicated by `.part` extension).

I think, it should work differently — simply store all `.part` files in the specified _incomplete_ directory and move them to target location as soon as they become finished. Current behavior is hardly useful and non-intuitive.

**Comment by sabotagebeats** [comment] 2020-12-08 07:04
having this same issue in windows 10

**Comment by ckerr** [comment] 2023-03-13 21:45
I think this ticket is the result of a misunderstanding: The torrent is moved from the incomplete directory to the complete directory when the torrent becomes complete, not when individual files become complete.

One use case I've seen is people who have scripts that watch the "complete" directory and perform actions when torrents are moved from the incomplete dir to the complete dir. If Transmission started moving individual files over instead of complete torrents, those scripts would likely break.

The "Also" part about `.part` files being kept is a duplicate of #290.

**Closed by ckerr** 2023-03-13 21:45 UTC
