### ISSUE TITLE
Feature request - login with form type

### ISSUE THREAD

**Issue by GulyFMG** [transmission/transmission#5056] opened 2023-02-25 23:10 UTC
### What is the issue?

Would it be possible to implement forms login?

### Which application of Transmission?

Web client

### Which version of Transmission?

Transmission 4.0.1

**Comment by ckerr** [comment] 2023-02-26 00:21
Hey @GulyFMG, thanks for reporting this.

I think this is a duplicate of https://github.com/transmission/transmission/issues/716 so I'm closing this ticket as a dupe.

**Closed by ckerr** 2023-02-26 00:21 UTC
