### ISSUE TITLE
Transfer list order changes on its own

### ISSUE THREAD

**Issue by shpongolian** [transmission/transmission#4913] opened 2023-02-16 10:45 UTC
### What is the issue?

Sometimes when opening transmission, the items in the transfer list will be in a different order. This new order doesn't appear to have any logic to it, i.e. it doesn't appear to be sorted alphabetically, or by status, date added, etc.

I don't know how to reproduce the issue because it seems to happen randomly. It isn't a temporary change, it is permanent and will persist across closing and opening the app (until it randomly reorders again).

This issue only started happening when I updated to v4.0.0, I never experienced it before that.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0

**Comment by ckerr** [comment] 2023-02-16 15:51
Hi @shpongolian, I think this is a duplicate of https://github.com/transmission/transmission/issues/155 so I'm going to close this ticket as a dupe.

Thank you for reporting it though! I'd rather have a bug that gets duplicate reports than one that goes unreported :smile_cat:

**Closed by ckerr** 2023-02-16 15:51 UTC
