### ISSUE TITLE
Web UI Upload speed to large for display area, wraps

### ISSUE THREAD

**Issue by teeks99** [transmission/transmission#6032] opened 2023-09-23 13:58 UTC
### What is the issue?

This is pretty minor, but my upload bandwidth (I just noticed, this is the same for download bandwidth) is wrapping across two lines when there are two digits after the decimal. 

![TransmissionDaemonUploadSpeed](https://github.com/transmission/transmission/assets/33045/0759608a-2329-4fde-a1f3-559246ecc08b)

Running the head of the 4.0.x branch, on ubuntu 20.04, browsing the Web UI from Firefox 117.0.

### Which application of Transmission?

Web client

### Which version of Transmission?

24077e35111cd6a6498fa61910bb54288a702bfc

**Comment by Daniel6372** [comment] 2023-09-24 01:31
duplicate of https://github.com/transmission/transmission/issues/5951

**Closed** 2023-09-24 05:11 UTC

**Comment by GaryElshaw** [comment] 2023-09-24 05:49
This should remain open if it's still an issue in the 4.0 branch.

**Comment by tearfur** [comment] 2023-09-24 13:55
I'd rather close the issue while I can still remember and I know there is a fix for it.

I don't want to to mentally track issues until they are included in a release or backported to a branch, especially since I don't know when that will happen.
