### ISSUE TITLE
Cannot resume file stopped due to disk full

### ISSUE THREAD

**Issue by doub** [transmission/transmission#1001] opened 2019-09-11 23:59 UTC
I'd like to be able to queue a lot of torrents, way beyond available disk space, and transfer them somewhere else when they complete. I have the download queue enabled. However if the disk fills up before I can downloaded files, all remaining torrents get into an error state (error 3, errorString starts with "No space left on device"). This is annoying in itself, but I'm being told (on IRC) that this is normal.

When I clear out some disk space, I try to resume the downloads by right-clicking on them from the web interface, and clicking "Resume", but that only works for a few of the torrents. For most of them nothing happens.

Also I was asked to try to stop and resume the download, but the "Pause" option of the web interface context menu is grayed out for all those stuck torrents.

I'm using transmission-daemon 2.94 on Arch Linux on a headless system. I just tried running a local build of the branch develop (at 5a5fe7d7f) with the same results. I use the web interface to add some torrents, or RPC requests from custom scripts for most of them. I have a custom torrent-done script that moves the files elsewhere and remove the torrent from transmission via RPC. I'm happy to try anything you might suggest to get more info.

**Comment by killemov** [comment] 2022-04-07 12:58
This is also related to https://github.com/transmission/transmission/issues/1835 .

**Comment by ckerr** [comment] 2023-01-27 15:28
Duplicate of #1835.

**Closed by ckerr** 2023-01-27 15:28 UTC
