### ISSUE TITLE
Transmission struggles when I pause (multiple) torrents

### ISSUE THREAD

**Issue by forthrin** [transmission/transmission#533] opened 2018-03-01 17:01 UTC
Using Transmission 2.92 (14714) on macOS, consider the following steps:

1. Have half a dozen or so torrents running
1. Press pause on a torrent
1. Possibly, press pause on another torrent a second later

Two problems frequently occur:

1. Transfer speeds drop to zero almost instantly, then after ten seconds they return to their original value. I don't know if this just a speed calculation bug, or if the connections actually fall out.
1. Some times I get the spinning beach ball, which may stay for a long time (not sure how long), but I think Transmission usually recovers sooner or later; it's not permanent! Is this because Transmission just has to do a lot of work whenever pausing a torrent, or is this a bug?

**Comment by ldexterldesign** [comment] 2018-03-02 19:53
Hey,

Do you still suffer this problem after upgrading to the latest release (i.e. 2.9.3)?:

If yes, feel free to update this issue

If no, close this issue

Regards

**Comment by forthrin** [comment] 2018-03-06 13:43
Speed drop to zero when pausing torrents happens with 2.93. No spinning beach ball (yet).

**Comment by ldexterldesign** [comment] 2018-03-06 13:45
Good to hear

Feel free to close the issue

Regards

**Comment by forthrin** [comment] 2018-03-06 14:06
No. The problem still present in 2.93.

1. Speed dropping to zero still happens. If the connections drop, it's a major issue. If it's only the speed calculation code that gets confused because some torrents are paused, it's a minor issue, but should still be fixed, because the user gets the impression that connections *are* dropped.

2. Spinning beach ball happened now too, but only for a few seconds, which is a minor problem. I'll let you know if it happens for a longer time.

**Comment by ldexterldesign** [comment] 2018-03-06 15:31
I'm not downloading much right now so I can't reproduce this issue

I doubt this issue would bother me much, even if I could reproduce it, but that's not to say it's not a potential bug worth fixing

Hopefully someone else can help..?

Regards

**Comment by forthrin** [comment] 2018-03-12 14:58
Paused two torrents (10+ GB) right after each other. Transmission hung for 30 seconds.

**Comment by forthrin** [comment] 2019-03-28 13:51
As for issue #1, Activity Monitor in macOS shows lots of data packages going in and out even if all Transmission transfer speed values say zero. So the problem is not connection loss, but an error in calculating the transfer speed values.

As for issue #2, there is still occasional beach balling with version 2.94. (The latest version.)

Has anyone reproduced this? Will it be fixed? It's been like a year since it was first reported.

**Closed** 2019-05-04 11:21 UTC
