### ISSUE TITLE
Downloads are not happening?

### ISSUE THREAD

**Issue by depesz** [transmission/transmission#1716] opened 2021-05-30 15:27 UTC
I have `transmission-daemon 2.94 (d8e60ee44f)` - newest available in debian stable.

Added ubuntu server torrent (https://releases.ubuntu.com/21.04/ubuntu-21.04-live-server-amd64.iso.torrent) which should be widely available, but I see no traffic happening.

Tested also with some other torrents via magnet links, and it "transmission-remote -l" never shows name of the thing in the torrent.

I do have DHT enabled. Logs show:

```
[2021-05-30 17:03:22.534] Transmission 2.94 (d8e60ee44f) started (session.c:740)
[2021-05-30 17:03:22.537] Cache Maximum cache size set to 4.00 MiB (256 blocks) (cache.c:261)
[2021-05-30 17:03:22.537] RPC Server Adding address to whitelist: 127.0.0.* (rpc-server.c:971)
[2021-05-30 17:03:22.538] RPC Server Adding address to whitelist: 172.28.173.* (rpc-server.c:971)
[2021-05-30 17:03:22.538] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)
[2021-05-30 17:03:22.538] RPC Server Started listening on 0.0.0.0:9091 (rpc-server.c:853)
[2021-05-30 17:03:22.538] RPC Server Whitelist enabled (rpc-server.c:1217)
[2021-05-30 17:03:22.539] Bound socket 15 to port 51413 on 0.0.0.0 (net.c:388)
[2021-05-30 17:03:22.539] Bound socket 16 to port 51413 on :: (net.c:388)
[2021-05-30 17:03:22.539] DHT Initializing DHT (tr-dht.c:278)
[2021-05-30 17:03:22.539] DHT Reusing old id (tr-dht.c:307)
[2021-05-30 17:03:22.539] DHT DHT initialized (tr-dht.c:332)
[2021-05-30 17:03:22.539] DHT Bootstrapping from 86 IPv4 nodes (tr-dht.c:156)
[2021-05-30 17:03:22.539] Using settings from "/var/lib/transmission-daemon/.config/transmission-daemon/" (daemon.c:528)
[2021-05-30 17:03:22.540] Saved "/etc/transmission-daemon/settings.json" (variant.c:1274)
[2021-05-30 17:03:22.540] ubuntu-21.04-live-server-amd64.iso Read resume file "/var/lib/transmission-daemon/.config/transmission-daemon//resume/ubuntu-21.04-live-server-amd64.iso.cab507494d02ebb1.resume" (resume.c:725)                                                       
[2021-05-30 17:03:22.540] ubuntu-21.04-live-server-amd64.iso Loaded 200 IPv4 peers from resume file (resume.c:94)
[2021-05-30 17:03:22.540] ubuntu-21.04-live-server-amd64.iso Resume file found 1 files marked for download (resume.c:157)
[2021-05-30 17:03:22.540] Loaded 1 torrents (session.c:2034)
[2021-05-30 17:03:22.540] Port Forwarding (NAT-PMP) initnatpmp succeeded (0) (natpmp.c:70)
[2021-05-30 17:03:22.540] Port Forwarding (NAT-PMP) sendpublicaddressrequest succeeded (2) (natpmp.c:70)
[2021-05-30 17:03:30.535] Port Forwarding (UPnP) UPNP_GetValidIGD failed (errno 0 - Success) (upnp.c:239)
[2021-05-30 17:03:30.536] Port Forwarding (UPnP) If your router supports UPnP, please make sure UPnP is enabled! (upnp.c:242)
[2021-05-30 17:03:30.536] Port Forwarding State changed from "Not forwarded" to "Starting" (port-forwarding.c:92)
[2021-05-30 17:03:30.536] ubuntu-21.04-live-server-amd64.iso IPv4 DHT not ready (broken, 0 nodes) (tr-dht.c:592)
[2021-05-30 17:03:30.536] ubuntu-21.04-live-server-amd64.iso Announcing to tracker (announcer.c:1554)
[2021-05-30 17:03:30.536] ubuntu-21.04-live-server-amd64.iso Announcing to tracker (announcer.c:1554)
[2021-05-30 17:03:30.537] ubuntu-21.04-live-server-amd64.iso Could not connect to tracker (announcer.c:996)
[2021-05-30 17:03:30.537] ubuntu-21.04-live-server-amd64.iso Retrying announce in 20 seconds. (announcer.c:1005)
[2021-05-30 17:03:30.537] ubuntu-21.04-live-server-amd64.iso Got 50 peers from tracker (torrent.c:565)
[2021-05-30 17:03:30.537] ubuntu-21.04-live-server-amd64.iso Announce response contained scrape info; rescheduling next scrape to 1800 seconds from now. (announcer.c:1152)                                                                                                      
[2021-05-30 17:03:38.535] ubuntu-21.04-live-server-amd64.iso IPv4 DHT not ready (broken, 4 nodes) (tr-dht.c:592)
[2021-05-30 17:03:42.534] ubuntu-21.04-live-server-amd64.iso Scrape error: Could not connect to tracker (announcer.c:1279)
[2021-05-30 17:03:42.535] ubuntu-21.04-live-server-amd64.iso Retrying scrape in 337 seconds. (announcer.c:1288)
[2021-05-30 17:03:47.535] ubuntu-21.04-live-server-amd64.iso IPv4 DHT not ready (broken, 7 nodes) (tr-dht.c:592)
[2021-05-30 17:03:51.535] ubuntu-21.04-live-server-amd64.iso Announcing to tracker (announcer.c:1554)
[2021-05-30 17:03:51.536] ubuntu-21.04-live-server-amd64.iso Could not connect to tracker (announcer.c:996)
[2021-05-30 17:03:51.536] ubuntu-21.04-live-server-amd64.iso Retrying announce in 906 seconds. (announcer.c:1005)
[2021-05-30 17:03:55.534] ubuntu-21.04-live-server-amd64.iso Starting IPv4 DHT announce (poor, 13 nodes) (tr-dht.c:577)
[2021-05-30 17:04:11.534] ubuntu-21.04-live-server-amd64.iso Learned 1 IPv4 peers from DHT (tr-dht.c:537)
[2021-05-30 17:04:11.535] ubuntu-21.04-live-server-amd64.iso Learned 1 IPv4 peers from DHT (tr-dht.c:537)
[2021-05-30 17:04:11.535] ubuntu-21.04-live-server-amd64.iso Learned 1 IPv4 peers from DHT (tr-dht.c:537)
[2021-05-30 17:04:12.535] ubuntu-21.04-live-server-amd64.iso Learned 3 IPv4 peers from DHT (tr-dht.c:537)
[2021-05-30 17:04:12.535] ubuntu-21.04-live-server-amd64.iso Learned 1 IPv4 peers from DHT (tr-dht.c:537)
[2021-05-30 17:04:12.536] ubuntu-21.04-live-server-amd64.iso Learned 9 IPv4 peers from DHT (tr-dht.c:537)
[2021-05-30 17:04:30.536] ubuntu-21.04-live-server-amd64.iso Learned 100 IPv4 peers from DHT (tr-dht.c:537)
[2021-05-30 17:04:30.537] ubuntu-21.04-live-server-amd64.iso Learned 100 IPv4 peers from DHT (tr-dht.c:537)
[2021-05-30 17:04:31.537] ubuntu-21.04-live-server-amd64.iso Learned 97 IPv4 peers from DHT (tr-dht.c:537)
[2021-05-30 17:04:31.537] ubuntu-21.04-live-server-amd64.iso Learned 3 IPv4 peers from DHT (tr-dht.c:537)
[2021-05-30 17:04:46.535] ubuntu-21.04-live-server-amd64.iso Learned 41 IPv4 peers from DHT (tr-dht.c:537)
[2021-05-30 17:04:46.536] ubuntu-21.04-live-server-amd64.iso Learned 100 IPv4 peers from DHT (tr-dht.c:537)
[2021-05-30 17:05:03.538] ubuntu-21.04-live-server-amd64.iso Learned 41 IPv4 peers from DHT (tr-dht.c:537)
[2021-05-30 17:05:27.539] ubuntu-21.04-live-server-amd64.iso Learned 41 IPv4 peers from DHT (tr-dht.c:537)
[2021-05-30 17:05:30.537] Port Forwarding (NAT-PMP) readnatpmpresponseorretry failed. Natpmp returned -7 (the gateway does not support nat-pmp); errno is 11 (Resource temporarily unavailable) (natpmp.c:75)                                                                    
[2021-05-30 17:05:30.537] Port Forwarding State changed from "Starting" to "???" (port-forwarding.c:92)
[2021-05-30 17:05:53.534] DHT Finished bootstrapping (tr-dht.c:260)
[2021-05-30 17:06:03.532] ubuntu-21.04-live-server-amd64.iso Learned 100 IPv4 peers from DHT (tr-dht.c:537)
[2021-05-30 17:07:54.535] ubuntu-21.04-live-server-amd64.iso IPv4 DHT announce done (tr-dht.c:545)
[2021-05-30 17:09:20.534] ubuntu-21.04-live-server-amd64.iso Scrape error: Could not connect to tracker (announcer.c:1279)
[2021-05-30 17:09:20.534] ubuntu-21.04-live-server-amd64.iso Retrying scrape in 1832 seconds. (announcer.c:1288)
[2021-05-30 17:09:21.535] Saved "/mnt/big/transmission-daemon/.config/transmission-daemon/resume/ubuntu-21.04-live-server-amd64.iso.cab507494d02ebb1.resume" (variant.c:1274)                                                                                                    
```

So it looks like it's getting something out of DHT, but no traffic actually happens ?!

One weird thing I noticed in strace output was:

```
17:23:09.958610 fcntl(19, F_GETFL)      = 0x2 (flags O_RDWR) <0.000079>
17:23:09.958763 fcntl(19, F_SETFL, O_RDWR|O_NONBLOCK) = 0 <0.000016>
17:23:09.958834 connect(19, {sa_family=AF_INET6, sin6_port=htons(443), inet_pton(AF_INET6, "2001:67c:1560:8008::14", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = -1 EADDRNOTAVAIL (Cannot assign requested address) <0.000046>
17:23:09.958999 close(19)               = 0 <0.000034>
17:23:09.959120 socket(AF_INET, SOCK_STREAM, IPPROTO_TCP) = 19 <0.000029>
17:23:09.959208 setsockopt(19, SOL_TCP, TCP_NODELAY, [1], 4) = 0 <0.000018>
17:23:09.959290 setsockopt(19, SOL_SOCKET, SO_SNDBUF, [1024], 4) = 0 <0.000017>
17:23:09.959364 setsockopt(19, SOL_SOCKET, SO_RCVBUF, [3072], 4) = 0 <0.000017>
17:23:09.959439 fcntl(19, F_GETFL)      = 0x2 (flags O_RDWR) <0.000015>
17:23:09.959506 fcntl(19, F_SETFL, O_RDWR|O_NONBLOCK) = 0 <0.000015>
17:23:09.959571 connect(19, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("91.189.95.21")}, 16) = -1 EINPROGRESS (Operation now in progress) <0.000067>
17:23:09.959711 poll([{fd=19, events=POLLOUT|POLLWRNORM}], 1, 0) = 0 (Timeout) <0.000018>
```

I tried to connect to this host (91.189.95.21:443) with telnet, and it worked 100% fine.

Any idea on what to look for/at?

**Comment by jeroenhabets** [comment] 2021-05-30 21:09
Ah, so I am not the only one... (though I'm running 3.0)

```
[2021-05-30 22:29:07.038] Transmission 3.00 (bb6b5a062e) started (session.c:769)
[2021-05-30 22:29:07.038] Cache Maximum cache size set to 256.0 MiB (16384 blocks) (cache.c:260)
[2021-05-30 22:29:07.038] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:956)
[2021-05-30 22:29:07.038] RPC Server Adding address to whitelist: 192.168.*.* (rpc-server.c:956)
[2021-05-30 22:29:07.038] RPC Server Serving RPC and Web requests on 192.168.1.101:9091/transmission/ (rpc-server.c:1243)
[2021-05-30 22:29:07.038] RPC Server Started listening on 192.168.1.101:9091 (rpc-server.c:834)
[2021-05-30 22:29:07.038] RPC Server Whitelist enabled (rpc-server.c:1249)
[2021-05-30 22:29:07.038] RPC Server Password required (rpc-server.c:1254)
[2021-05-30 22:29:07.038] Bound socket 17 to port 443 on 10.105.0.2 (net.c:462)
[2021-05-30 22:29:07.038] Bound socket 18 to port 443 on :: (net.c:462)
[2021-05-30 22:29:07.038] Port Forwarding Stopped (port-forwarding.c:196)
[2021-05-30 22:29:07.038] Using settings from "/var/lib/transmission-daemon/.config/transmission-daemon" (daemon.c:646)
[2021-05-30 22:29:07.038] Saved "/etc/transmission-daemon/settings.json" (variant.c:1221)
[2021-05-30 22:29:07.038] Saved pidfile "/run/transmission-daemon/transmission.pid" (daemon.c:662)
[2021-05-30 22:29:07.038] transmission-daemon requiring authentication (daemon.c:674)
```

**Comment by 0lm** [comment] 2021-08-13 11:42
Look here: https://github.com/transmission/transmission/issues/1254
I am still waiting for a fix, or looking for a good fork that fixed it, since I am not the best in compiling myself.

**Comment by DanAykroyd256** [comment] 2022-01-22 23:00
Have you found anything @0lm? I see you post has quite some time… I wonder if Transmission is still properly maintained.

I'm having the same exacty issue by the way.

**Comment by ckerr** [comment] 2022-12-01 18:41
Closing as duplicate of 1254

**Closed by ckerr** 2022-12-01 18:41 UTC
Labels: scope:daemon
