### ISSUE TITLE
large file support not enabled by default; errno EINVAL when seeking to large offset in file

### ISSUE THREAD

**Issue by dmig** [transmission/transmission#406] opened 2017-09-19 04:07 UTC
Trying to continue stopped download, I head this error: 'Invalid argument (filename)' and download stops.
Searching led me to this discussion: https://forum.transmissionbt.com/viewtopic.php?f=8&t=9913
But in my case neither filename nor path contain any non-latin characters.

Download session log:
```
Tue Sep 19 10:56:52 2017                        Transmission 2.92 (14714) started
Tue Sep 19 10:56:52 2017        debug   Cache   Maximum cache size set to 4.00 MiB (256 blocks)
Tue Sep 19 10:56:52 2017                RPC Server      Adding address to whitelist: 127.0.0.1
Tue Sep 19 10:56:52 2017        debug           Bound socket 16 to port 51413 on 0.0.0.0
Tue Sep 19 10:56:52 2017        debug           Bound socket 17 to port 51413 on ::
Tue Sep 19 10:56:52 2017        debug   DHT     Initializing DHT
Tue Sep 19 10:56:52 2017                DHT     Reusing old id
Tue Sep 19 10:56:52 2017        debug   DHT     DHT initialized
Tue Sep 19 10:56:52 2017        debug   LPD     Initialising Local Peer Discovery
Tue Sep 19 10:56:52 2017        debug   LPD     Local Peer Discovery initialised
Tue Sep 19 10:56:52 2017                DHT     Bootstrapping from 40 IPv4 nodes
Tue Sep 19 10:56:52 2017        debug   foo.mkv     Read resume file "/home/dmig/.config/transmission/resume/foo.mkv.a9856ff6e36a7e4e.resume"
Tue Sep 19 10:56:52 2017        debug   foo.mkv     Loaded 77 IPv4 peers from resume file
Tue Sep 19 10:56:52 2017        debug   foo.mkv     Resume file found 1 files marked for download
Tue Sep 19 10:56:52 2017                        Loaded 1 torrents
Tue Sep 19 10:56:52 2017                Port Forwarding (NAT-PMP)       initnatpmp succeeded (0)
Tue Sep 19 10:56:52 2017                Port Forwarding (UPnP)  Found Internet Gateway Device "http://192.168.0.1:5500/ctl/IPConn"
Tue Sep 19 10:56:52 2017                Port Forwarding (UPnP)  Local Address is "192.168.0.189"
Tue Sep 19 10:56:52 2017                Port Forwarding (UPnP)  Port forwarding through "http://192.168.0.1:5500/ctl/IPConn", service "urn:schemas-upnp-org:service:WANIPConnection:1". (local address: 192.168.0.189:51413)
Tue Sep 19 10:56:52 2017                Port Forwarding (UPnP)  Port forwarding successful!
Tue Sep 19 10:57:14 2017                        Inhibiting desktop hibernation
Tue Sep 19 10:57:14 2017        debug   foo.mkv     Announcing to tracker
Tue Sep 19 10:57:16 2017        debug           SO_SNDBUF size is 16384
Tue Sep 19 10:57:16 2017        debug           SO_RCVBUF size is 87380
Tue Sep 19 10:57:26 2017                foo.mkv     Starting IPv4 DHT announce (poor, 13 nodes)
Tue Sep 19 10:57:28 2017        debug   foo.mkv     Learned 1 IPv4 peers from DHT
Tue Sep 19 10:57:28 2017        debug   foo.mkv     [LAZY] checking just-completed piece 1370
Tue Sep 19 10:57:28 2017        error   foo.mkv     Piece 1370, which was just downloaded, failed its checksum test
Tue Sep 19 10:57:28 2017        debug   foo.mkv     Learned 1 IPv4 peers from DHT
Tue Sep 19 10:57:39 2017        error   foo.mkv     write failed for "foo.mkv": Invalid argument
Tue Sep 19 10:57:39 2017        error   foo.mkv     Invalid argument (/media/dmig/32G/foo.mkv)
Tue Sep 19 10:57:39 2017                foo.mkv     Pausing
Tue Sep 19 10:57:39 2017        error   foo.mkv     write failed for "foo.mkv": Invalid argument
Tue Sep 19 10:57:39 2017                        Saved "/home/dmig/.config/transmission/resume/foo.mkv.a9856ff6e36a7e4e.resume"
Tue Sep 19 10:57:40 2017        debug   foo.mkv     Announcing to tracker
Tue Sep 19 10:57:44 2017        debug   foo.mkv     Learned 50 IPv4 peers from DHT
Tue Sep 19 10:57:44 2017        debug   foo.mkv     Learned 59 IPv4 peers from DHT
Tue Sep 19 10:57:45 2017        debug   foo.mkv     Learned 53 IPv4 peers from DHT
```

**Comment by barbequesauce** [comment] 2018-04-03 19:43
Receiving this as well.

**Comment by barbequesauce** [comment] 2018-04-03 19:47
Note I see this with a number of torrents - one example is below.

```
[2018-04-03 15:27:47.776] Minions.2015.720p.BRRiP.XViD.AC3-budyzer Queued for verification (/opt/transmission-2.93/libtransmission/verify.c:269)
[2018-04-03 15:27:47.776] Minions.2015.720p.BRRiP.XViD.AC3-budyzer Verifying torrent (/opt/transmission-2.93/libtransmission/verify.c:224)
[2018-04-03 15:28:13.097] Minions.2015.720p.BRRiP.XViD.AC3-budyzer write failed for "Minions.2015.720p.BRRiP.XViD.AC3-budyzer/Minions.2015.720p.BRRiP.XViD.AC3-budyzer.avi": Invalid argument (/opt/transmission-2.93/libtransmission/inout.c:138)
[2018-04-03 15:28:13.097] Minions.2015.720p.BRRiP.XViD.AC3-budyzer Invalid argument (/mnt/sdb/completed/Watcher/Minions.2015.720p.BRRiP.XViD.AC3-budyzer/Minions.2015.720p.BRRiP.XViD.AC3- (/opt/transmission-2.93/libtransmission/torrent.c:537)
[2018-04-03 15:28:13.097] Minions.2015.720p.BRRiP.XViD.AC3-budyzer Pausing (/opt/transmission-2.93/libtransmission/torrent.c:1856)
[2018-04-03 15:28:13.097] Minions.2015.720p.BRRiP.XViD.AC3-budyzer write failed for "Minions.2015.720p.BRRiP.XViD.AC3-budyzer/Minions.2015.720p.BRRiP.XViD.AC3-budyzer.avi": Invalid argument (/opt/transmission-2.93/libtransmission/inout.c:138)
[2018-04-03 15:28:13.097] Saved "/mnt/sdb/transmission/resume/Minions.2015.720p.BRRiP.XViD.AC3-budyzer.5292f656b82023c8.resume" (/opt/transmission-2.93/libtransmission/variant.c:1266)
```

**Comment by barbequesauce** [comment] 2018-04-04 17:10
Wondering if it's related to [this commit](https://github.com/transmission/transmission/commit/580c5e416629280c8a8fa2cbeb5e1411336bcb37#diff-d9a5da82e3670184c9a5aec172839176)? Suggesting that based on the error I the log coming from inout.c line 138?

**Comment by barbequesauce** [comment] 2018-04-04 22:53
strace output here

```
root@public:~cat /home/pi/strace.transmission-daemon.log | grep -i EINVAL
[pid 13925] pwrite(27, "\0\0\6K\26)\0\n\0\0\326V\26)\0\n\0\0\336`\26)\0\n\0\0\370j\26)\0\n"..., 178, 18446744072234762240) = -1 EINVAL (Invalid argument)
[pid 13925] pwrite(27, "+\20_\246T\246\32\232T\254:S\n\272\252O\241\251\256\231l\2\225\337\246[M\363\2475\337\245"..., 1605632, 18446744072233156608) = -1 EINVAL (Invalid argument)
root@public:~# 

```

**Comment by cfpp2p** [comment] 2018-04-06 17:10
@barbequesauce 
In **_2.93_** inout.c line 138 is the  `tr_logAddTorErr` line.
```

      if (ioMode == TR_IO_READ)
        {
          if (!tr_sys_file_read_at (fd, buf, buflen, fileOffset, NULL, &error))
            {
              err = error->code;
              tr_logAddTorErr (tor, "read failed for \"%s\": %s", file->name, error->message);
              tr_error_free (error);
            }
        }

```
> strace output here

Try compiling with pwrite and prread disabled ( i.e. https://github.com/cfpp2p/transmission/commit/051e1d1b1a41b1dbdb0397345a53ade0d1997c12).

**Comment by barbequesauce** [comment] 2018-04-09 16:39
Sorry for the delay in responding. New strace output:

```
pi@public:~ $ sudo cat strace.transmission-daemon.log | grep -i EINVAL
[pid 22919] lseek(29, 2820177920, SEEK_SET) = -1 EINVAL (Invalid argument)
[pid 22919] lseek(29, 2818572288, SEEK_SET) = -1 EINVAL (Invalid argument)
pi@public:~ $ 
```

**Comment by barbequesauce** [comment] 2018-04-09 17:14
Wondering if this is helpful? Specifically the nonzero return three lines prior to the EINVAL error....

```
[pid 22919] stat64("/mnt/sda/transmission/working/[torrentname]/[torrentfile].part", {st_mode=S_IFREG|0777, st_size=2820178098, ...}) = 0
[pid 22919] open("/mnt/sda/transmission/working/[torrentname]/[torrentfile].part", O_RDWR|O_CREAT|O_LARGEFILE|O_CLOEXEC, 0666) = 29
[pid 22919] fadvise64_64(29, 0, 0, POSIX_FADV_SEQUENTIAL) = 0
[pid 22919] fallocate(29, 0, 0, 2820178098) = 0
[pid 22919] lseek(29, 2820177920, SEEK_SET) = -1 EINVAL (Invalid argument)
```

**Comment by barbequesauce** [comment] 2018-04-17 17:08
An example of a failing torrent can be found [here](http://linuxtracker.org/download.php?id=4ac572f0932ac778383cf2cd1092196d4ac863dc&f=eos-amd64-en-3.3.16.torrent&key=6c2d037a)

**Comment by barbequesauce** [comment] 2018-04-17 17:28
Per @mikedld in IRC - removed CPPFLAGS="$CPPFLAGS -DNDEBUG" from configure.ac and recompiled.

New log entries on adding torrent pointing to a file >8GB:

```
[2018-04-17 13:25:01.306] Preallocated file "/mnt/sda/transmission/working/eos-eos3.3-amd64-amd64.180407-114249.en.iso.part" (sparse, size: 15571843072) (/opt/transmission-2.93/libtransmission/fdlimit.c:220)
[2018-04-17 13:25:01.306] eos-eos3.3-amd64-amd64.180407-114249.en.iso write failed for "eos-eos3.3-amd64-amd64.180407-114249.en.iso": Invalid argument (/opt/transmission-2.93/libtransmission/inout.c:138)
[2018-04-17 13:25:07.628] eos-eos3.3-amd64-amd64.180407-114249.en.iso write failed for "eos-eos3.3-amd64-amd64.180407-114249.en.iso": Invalid argument (/opt/transmission-2.93/libtransmission/inout.c:138)
```

**Comment by barbequesauce** [comment] 2018-04-17 19:28
Working now. per @mikedld in IRC - cleaned build directory, then...

```
cd build
env CFLAGS="-D_FILE_OFFSET_BITS=64 -D_LARGE_FILES=1" 
cmake ..
make
sudo make install
```

and it seems to be back to normal.

**Comment by mikedld** [comment] 2018-05-02 07:27
Still no idea what's happening here. CMake adds `-D_FILE_OFFSET_BITS=64` on its own just fine, and judging by the system headers adding `-D_LARGE_FILES=1` shouldn't make any difference.

**Comment by mikedld** [comment] 2018-05-02 07:47
@dmig what's your system? Is it Raspbian as well?

**Comment by dmig** [comment] 2018-05-02 07:49
@mikedld Ubuntu 17.04 x64 at that time

**Comment by mikedld** [comment] 2018-05-02 11:04
@dmig Thanks, might be easier to reproduce there.

**Comment by dmig** [comment] 2018-05-02 11:08
Hope I could find that torrent again...

**Comment by axisfold** [comment] 2019-12-16 09:02
> 
> 
> Working now. per @mikedld in IRC - cleaned build directory, then...
> 
> ```
> cd build
> env CFLAGS="-D_FILE_OFFSET_BITS=64 -D_LARGE_FILES=1" cmake ..
> make
> sudo make install
> ```
> 
> and it seems to be back to normal.

I want to chime in that I tried to compile the 2.94 release zip found on the Releases page on raspbian, and I encountered the same errors. I had to use these cmake flags to get it to work.

**Comment by 1100101** [comment] 2021-09-13 22:09
I just found out after lots of trial and error that I still need to specify the two flags mentioned above with the current version of Transmission on `master` branch.

I'm compiling Transmission on a Raspberry Pi 4 running Raspbian 10 (buster) with gcc 8.3.0
Any reason why this isn't discovered automatically when running CMake?

**Comment by 1100101** [comment] 2023-01-17 20:40
I haven’t had any issues with Transmission and large files for a (long) while now.
I regularly build it from the `master` branch (on a Raspi 4 using gcc/Clang)

**Comment by ckerr** [comment] 2023-01-17 22:06
Closing as fixed based on the previous comment. Thanks for responding @1100101!

**Closed by ckerr** 2023-01-17 22:06 UTC
Labels: help wanted, needs clarification, pr welcome
