### ISSUE TITLE
4.0.0 chokes all torrents added

### ISSUE THREAD

**Issue by zencapop** [transmission/transmission#4943] opened 2023-02-19 02:39 UTC
### What is the issue?

Hello. Hope you are well. I am running Ventura 13.2.1 on my M1 Apple Macbook Pro. I recently updated to Transmission 4.0.0 and the torrents stopped working and downloading. They would download for a bit but then lose all connections. I tried several workarounds only to downgrade to 3.0.0, which is working fine. 

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0

**Comment by ckerr** [comment] 2023-02-19 02:49
Duplicate of https://github.com/transmission/transmission/issues/4849

**Closed by ckerr** 2023-02-19 02:49 UTC
