### ISSUE TITLE
Port Closed: Upstream issue ? (`bad request`)

### ISSUE THREAD

**Issue by d-a-v** [transmission/transmission#1657] opened 2021-04-01 21:20 UTC
There's an issue when IPv6 is used with `portcheck.transmissionbt.com`.

By instrumenting the source code I got a `400 Bad Request`. So I tried with port 22 and `curl`.

My `ssh` port (22) is wide opened to internet on both IPv4 and IPv6.

When forcing IPv4 (`-4`) it works :
```
$ curl -4 -v http://portcheck.transmissionbt.com/22; echo
*   Trying 87.98.162.88:80...
* TCP_NODELAY set
* Connected to portcheck.transmissionbt.com (87.98.162.88) port 80 (#0)
> GET /22 HTTP/1.1
> Host: portcheck.transmissionbt.com
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.10.3 (Ubuntu)
< Date: Thu, 01 Apr 2021 21:01:30 GMT
< Content-Type: text/html; charset=ISO-8859-1
< Transfer-Encoding: chunked
< Connection: keep-alive
< 
* Connection #0 to host portcheck.transmissionbt.com left intact
1
```

When I'm not forcing, I get `400 Bad Request`
```
$ curl -v http://portcheck.transmissionbt.com/22; echo
*   Trying 2001:41d0:c:5ac:5::1:80...
* TCP_NODELAY set
* Connected to portcheck.transmissionbt.com (2001:41d0:c:5ac:5::1) port 80 (#0)
> GET /22 HTTP/1.1
> Host: portcheck.transmissionbt.com
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Server: nginx/1.10.3 (Ubuntu)
< Date: Thu, 01 Apr 2021 21:02:37 GMT
< Content-Type: text/html; charset=ISO-8859-1
< Transfer-Encoding: chunked
< Connection: keep-alive
< 
* Connection #0 to host portcheck.transmissionbt.com left intact
```

My port 22 is opened to IPv6. From elsewhere to the machine which did the test above:
```
$ telnet 2001:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:8d6a 22
Trying 2001:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:8d6a...
Connected to 2001:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:8d6a.
Escape character is '^]'.
SSH-xxx-OpenSSH_xxxx Ubuntu-xubuntuxxx
```

I have not yet figured out where to force IPv4 requests for this check only in libtransmission.
And if I replace the website by its IPv4 address, then I am politely told to stop tinkering:

```
$ curl -v http://87.98.162.88/22; echo
*   Trying 87.98.162.88:80...
* Connected to 87.98.162.88 (87.98.162.88) port 80 (#0)
> GET /22 HTTP/1.1
> Host: 87.98.162.88
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Moved Temporarily
< Server: nginx/1.10.3 (Ubuntu)
< Date: Thu, 01 Apr 2021 21:10:11 GMT
< Content-Type: text/html
< Content-Length: 170
< Connection: keep-alive
< Location: http://transmissionbt.com/
< 
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
* Connection #0 to host 87.98.162.88 left intact

```

I don't think anymore it is an issue on my side but I can't be sure.
Is anyone IPv6-enabled able to see that the port is opened ?
Do the maintainers know the persons who are running `transmissionbt.com` ?

**Comment by m3nu** [comment] 2021-06-14 10:59
I noticed that Transmission shows the port as "closed" in the settings, after enabling IPv6. That's probably the reason.

**Comment by ckerr** [comment] 2022-01-26 07:17
I think this is a dupe of https://github.com/transmission/transmission/issues/381 ?

**Closed by ckerr** 2022-01-26 07:17 UTC
