### ISSUE TITLE
Deleting errornous torrents via RPC causes transmission-daemon to become unresponsive

### ISSUE THREAD

**Issue by krichter722** [transmission/transmission#268] opened 2017-05-07 15:32 UTC
Deleting errornous torrents like http://mirror.aarnet.edu.au/pub/sage/spkg/upstream/singular/meta/singular-3.1.5.tar.bz2.torrent via RPC causes transmission-daemon to become unresponsive. I can't provide more information due to the absense of a log configuration directive, a configuration file which isn't overwritten after restart of the service and absense of documentation in configuration files.

experienced with 2.92-2ubuntu1 on Ubuntu 17.04

**Comment by ckerr** [comment] 2022-01-19 23:04
Closing as a dupe of https://github.com/transmission/transmission/issues/2462. I realize this ticket was filed before 2462, but there are so many overlapping tickets at this point that it makes sense to start with a new "big picture" ticket.

**Closed by ckerr** 2022-01-19 23:04 UTC
