### ISSUE TITLE
Display window ... options ignored

### ISSUE THREAD

**Issue by lucian303** [transmission/transmission#1693] opened 2021-05-14 00:31 UTC
In 3.00, despite not having the "display window when" options turned on, I still get a window when adding anything.

**Comment by lucian303** [comment] 2021-11-10 16:35
Yes. From what I understand, with all the "display window when..." options unchecked, when clicking a magnet link, it should add and start downloading right away. Yet I get two windows that pop up every single time. Maybe I'm just not understanding the intent of those options and they hide other windows? If so, is it possible to get rid of these prompts. The download location, etc. is already set in the options. I can download a .torrent directly to a directory and have it pick up without verbosity. I'm hoping the same thing can apply to magnet links but so far, it seems impossible. 

<img width="429" alt="Captura de Pantalla 2021-11-10 a la(s) 5 32 30 p  m" src="https://user-images.githubusercontent.com/288151/141153587-cfb5e8dc-2a8b-4868-8348-6491da7e0679.png">
<img width="804" alt="Captura de Pantalla 2021-11-10 a la(s) 5 32 24 p  m" src="https://user-images.githubusercontent.com/288151/141153571-ce1af99f-aecc-471c-9416-6d456cbc8178.png">

**Comment by wngzro** [comment] 2021-12-03 22:14
To add to this, `defaults read org.m0k.transmission MagnetOpenAsk` returns 0 when "Display a window when opening a magnet link" is unchecked, so it seems like the value is being set properly but the behavior is still incorrect.

**Comment by wngzro** [comment] 2021-12-03 22:35
I think I see the confusion/bug here.

https://github.com/transmission/transmission/blob/b8c01a581edeb90a3867594a06b3fe5290777630/macosx/PrefsController.mm#L980-L993

Assuming that when "Default location" is set to "Same as torrent file", Transmission has to ask for magnet links because it doesn't know where to save the torrent. Things work normally when the location is set to an actual folder.

What's confusing here is the lockout for "Same as torrent file" and MagnetOpenAsk doesn't seem to persist after closing Transmission.

Expected behavior:
<img width="654" alt="Screen Shot 2021-12-03 at 4 30 51 PM" src="https://user-images.githubusercontent.com/61703516/144681689-240b86e7-1697-4fae-9145-191a5680f145.png">

Actual behavior:
<img width="654" alt="Screen Shot 2021-12-03 at 4 30 29 PM" src="https://user-images.githubusercontent.com/61703516/144681723-c925b5d5-978f-4fdb-89c7-f0774ae46042.png">

**Comment by ckerr** [comment] 2022-02-25 20:15
@wngzro thanks for tracking this down! Would you be willing to make a PR for this?

**Closed** 2022-05-14 02:27 UTC
Labels: bug, scope:mac, pr welcome, good first issue
