### ISSUE TITLE
uncaught exception reason: 'assertion failed: bit_count_:109, n:1434, std::size(flags_):495

### ISSUE THREAD

**Issue by chaseholden** [transmission/transmission#2803] opened 2022-03-24 04:15 UTC
Attaching 2 crash reports - occurred after Transmission running smoothly for 5-10 minutes. (apx 6000 magnets)

Build 53dc3a41b4
[Crash-Reports-Trans-20220523-CH.zip](https://github.com/transmission/transmission/files/8338370/Crash-Reports-Trans-20220523-CH.zip)

**Comment by chaseholden** [comment] 2022-03-24 04:21
Crashes continue in build 6db3fbfe64
[6db3fbfe64 - Crash Reports - Transmission - CH.zip](https://github.com/transmission/transmission/files/8338394/6db3fbfe64.-.Crash.Reports.-.Transmission.-.CH.zip)

**Comment by ckerr** [comment] 2022-03-24 04:44
This is a duplicate of https://github.com/transmission/transmission/issues/2727

**Closed by ckerr** 2022-03-24 04:44 UTC

**Comment by chaseholden** [comment] 2022-03-25 08:40
Build 783fa500e7 with ostensibly with log trace 

- several new macOS Crash Reports attached...

[783fa500e7_Crash_Reports_CH.zip](https://github.com/transmission/transmission/files/8348791/783fa500e7_Crash_Reports_CH.zip)

**Comment by chaseholden** [comment] 2022-03-25 08:55
Build b94c6796c8 with new macOS Crash Reports attached...

[Uploading b94c6796c8 Crash_Reports_CH.zip…]()

**Comment by chaseholden** [comment] 2022-03-25 09:14
[b94c6796c8_Crash_CH.txt.zip](https://github.com/transmission/transmission/files/8349076/b94c6796c8_Crash_CH.txt.zip)

**Comment by chaseholden** [comment] 2022-03-26 12:10
Build 1051160b99 Crash Reports 
[1051160b99-Crash-Reports-CH.zip](https://github.com/transmission/transmission/files/8355334/1051160b99-Crash-Reports-CH.zip)

**Comment by chaseholden** [comment] 2022-03-26 12:22
is there a way to send private msgs for trace logs?
