### ISSUE TITLE
remote authentication

### ISSUE THREAD

**Issue by raako71** [transmission/transmission#560] opened 2018-03-24 09:02 UTC
Is remote authentication just done with a plain text password? Is the connection secured with encryption? Can't seem to find an answer to this

**Comment by LaserEyess** [comment] 2018-03-24 13:12
Any acces to RPC is, by default, unencrypted. That includes all clients, such as the QT client and transmission-remote. If you want to encrypt it you can reverse proxy transmission behind something like nginx, but otherwise transmission has no way of encrypting http traffic by itself.

**Comment by ckerr** [comment] 2022-02-21 17:18
Closing duplicate of https://github.com/transmission/transmission/issues/1294

**Closed by ckerr** 2022-02-21 17:18 UTC
