### ISSUE TITLE
Can't add WebSocket trackers

### ISSUE THREAD

**Issue by qianbinbin** [transmission/transmission#5509] opened 2023-05-10 07:07 UTC
### What is the issue?

Hi there,

I was adding trackers to Transmission, but some of them result in `invalid argument`:

```sh
$ transmission-remote --auth "" --torrent "" --tracker-add 'ws://hub.bugout.link:80/announce'
Error: invalid argument
$ transmission-remote --auth "" --torrent "" --tracker-add 'wss://tracker.openwebtorrent.com:443/announce'
Error: invalid argument
```

Thank you.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

3.00 (bb6b5a062e)

**Comment by qianbinbin** [comment] 2023-05-13 12:08
I tried 4.1.0-dev (f2aa3e197b) and it works fine with IPv6 trackers, but not WebSocket.

**Comment by tearfur** [comment] 2023-07-14 15:35
We don't have WebTorrent support at the moment.

Closing as a duplicate of #47.

**Closed by tearfur** 2023-07-14 15:35 UTC
