### ISSUE TITLE
Auto add doesn't work

### ISSUE THREAD

**Issue by Dundo960** [transmission/transmission#5186] opened 2023-03-09 08:54 UTC
### What is the issue?

In previous versions Transmission would automatically add new torrents from folder chosen. Now it only works if I deselect this function and select it again manualy.
<img width="401" alt="slika" src="https://user-images.githubusercontent.com/104674454/223970351-98c6e0c1-e956-4814-90d7-1cb4f91ca2ab.png">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1

**Comment by ckerr** [comment] 2023-03-09 16:33
Hi @Dundo960 thanks for reporting this!

I think this is a duplicate of https://github.com/transmission/transmission/issues/4683 so I'm going to close this as a dupe.

4683 is fixed by 8a374a3310540f23500dbccf84a48609b7fea3c9 which will  be included in 4.0.2 next week.

Thanks again!

**Closed by ckerr** 2023-03-09 16:33 UTC
