### ISSUE TITLE
Downloads tangibly slower

### ISSUE THREAD

**Issue by dyavfc** [transmission/transmission#4784] opened 2023-02-09 23:51 UTC
Downloaded the 4.0 update on my mac. went to download my usual torrents but was not getting my standard speeds. I redownloaded 3.0 and the exact same torrents downloaded immediately!

**Comment by mzrimsek** [comment] 2023-02-10 01:27
Sincerely glad it's not just me I thought something on my network was failing.

Hopefully this resolved soon, but I'll be switching to 3.0 for now.

**Comment by ddbrierton** [comment] 2023-02-10 03:13
Yes, me too. This is on macOS 13.2 Apple Silicon and Transmission 4.0.0 vs 3.00.

I appreciate that a bug report like this is next to useless as long as it doesn’t contain more data. Please let us know what you need to know. As far as I can tell 4.0.0 is rejected a lot of downloaded data for failing validation, that appears to be part of the problem. But also 4.0.0 appears to be connecting to fewer available peers.

**Comment by leafygh** [comment] 2023-02-10 04:12
Same for me. Version 4 is creeping along, at a fraction of the speed of earlier versions.

**Comment by kingo55** [comment] 2023-02-10 11:22
Seeing the same here on 4.0.0, and seeing extraordinarily high amounts of discarded data. Anyone else seeing this for some of their torrents?:

<img width="432" src="https://user-images.githubusercontent.com/2361388/218078087-af777581-905e-44f2-9db4-cdf20652d345.png">

**Comment by ddbrierton** [comment] 2023-02-10 11:28
>  seeing extraordinarily high amounts of discarded data. Anyone else seeing this for some of their torrents?:

Yes.

**Comment by ddbrierton** [comment] 2023-02-10 11:34
Possibly related issue: #4583

**Comment by ckerr** [comment] 2023-02-10 20:21
Closing as duplicate of https://github.com/transmission/transmission/issues/4583.

**Closed by ckerr** 2023-02-10 20:21 UTC

**Comment by sweetppro** [comment] 2023-02-16 09:16
try the latest nightly, this should be fixed
