### ISSUE TITLE
Forcing to open window when opening magnet link?

### ISSUE THREAD

**Issue by swoondrones** [transmission/transmission#6176] opened 2023-10-28 01:49 UTC
### What is the issue?

Has something changed to not have the open to not have a window open when selecting a magnet link? I can't seem to unselect the option. I hope you haven't forced this and taken away the option.

How do I deselect it? It is so infuriating! See attachment.

Thanks!

<img width="752" alt="Screenshot 2023-10-28 at 12 42 05" src="https://github.com/transmission/transmission/assets/76269339/f4645d27-e9e9-4c79-b68e-5ae809396149">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.4

**Comment by nevack** [comment] 2023-10-28 02:31
@swoondrones It is explained in the tooltip.
<img width="419" alt="image" src="https://github.com/transmission/transmission/assets/8330119/1b3a62c4-0b3f-4d23-a90a-0c59d26d03de">

**Comment by nevack** [comment] 2023-10-28 02:38
Closing as duplicate of https://github.com/transmission/transmission/issues/5034

**Closed by nevack** 2023-10-28 02:38 UTC
