### ISSUE TITLE
When closing client it does not close every time instead it's still active in background

### ISSUE THREAD

**Issue by AK220011** [transmission/transmission#5494] opened 2023-05-04 21:40 UTC
### What is the issue?

When closing client it sometimes ends process, sometimes it takes 30 seconds for it to close itself and sometimes I have to "end task" otherwise it doesn't close. Using windows 11 up to date.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Transmission 4.0.3 (6b0e49bbb2)

**Comment by mikedld** [comment] 2023-05-04 22:58
Looks like a duplicate of #287.

**Closed** 2023-08-30 16:13 UTC
Labels: duplicate
