### ISSUE TITLE
Writing out cache from memory to disk blocks active downloading

### ISSUE THREAD

**Issue by cmargroff** [transmission/transmission#3146] opened 2022-05-27 14:56 UTC
I have a pretty slow external so I increased the cache size to 8GB which is half the system.

What I have been able to glean is that when Transmission is writing out whatever it has from cache, it causes active downloading on all torrrents to wait (network activity drops to 0). This is true even if the cache limit hasn't been reached and it is writing out a piece of one torrent and another could be downloading.

![image](https://user-images.githubusercontent.com/8389353/170723811-abd88a12-d14a-45a3-ac54-b01225fd606e.png)
![image](https://user-images.githubusercontent.com/8389353/170723957-97351a4e-c3a1-4b43-be95-489661046bc8.png)

Is this an I/O wait even with it being an external? The ethernet adapter is on a PCI bus and the external drive is connected to a USB 3.0 controller that has nothing else plugged into it.

Edit:
I ran a disk benchmark to stress the disk while something was downloading, it didn't effect the download speed at all.
![image](https://user-images.githubusercontent.com/8389353/170730562-30375f8b-cd22-4d5f-8ac0-ac57858ad8fc.png)
Could this be a thread blocking issue?

**Comment by ckerr** [comment] 2022-05-27 17:25
Hi @cmargroff, this is a duplicate of https://github.com/transmission/transmission/issues/2462

**Closed by ckerr** 2022-05-27 17:25 UTC

**Comment by cmargroff** [comment] 2022-05-27 20:33
@ckerr thanks
