### ISSUE TITLE
add ability to update default trackers from an online list

### ISSUE THREAD

**Issue by SESProMax** [transmission/transmission#5309] opened 2023-03-28 01:51 UTC
### What is the issue?

tracker enhance: Hope transmission can add the function that can update tracker via url subscription. Like bitcomet.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.2

**Comment by mikedld** [comment] 2023-03-28 01:55
I have no idea what this is about. Could you extend the description so that it's longer than 2 words and is clearer as to what you're asking for?

**Comment by SESProMax** [comment] 2023-03-28 02:49
sorry，I have added some words 😊
________________________________
发件人: Mike Gelfand ***@***.***>
发送时间: 2023年3月28日 9:56
收件人: transmission/transmission ***@***.***>
抄送: SUDOCODE ***@***.***>; Author ***@***.***>
主题: Re: [transmission/transmission] Hope for the tracker subscription (Issue #5309)


I have no idea what this is about. Could you extend the description so that it's longer than 2 words and is clearer as to what you're asking for?

**Comment by SESProMax** [comment] 2023-03-29 01:42
https://trackerslist.com/#/zh
https://github.com/XIU2/TrackersListCollection
Watch those pages. they will be helpful.
________________________________
发件人: Charles Kerr ***@***.***>
发送时间: Wednesday, March 29, 2023 1:04:38 AM
收件人: transmission/transmission ***@***.***>
抄送: SUDOCODE ***@***.***>; Mention ***@***.***>
主题: Re: [transmission/transmission] Hope for the tracker subscription (Issue #5309)


@SESProMax<https://github.com/SESProMax> I still don't understand what this means. What URL subscription?

―

**Comment by killemov** [comment] 2023-03-29 11:22
Ah, this might be something to put in `session["default-trackers"]`.

**Comment by ckerr** [comment] 2023-04-13 00:30
This isn't a feature that I'm going to prioritize; but if someone else wants to do the work and if the PR is short & simple enough, I'd be happy to review it.

**Comment by enihcam** [comment] 2023-06-22 06:42
> This isn't a feature that I'm going to prioritize; but if someone else wants to do the work and if the PR is short & simple enough, I'd be happy to review it.

or maybe just add an option like `default-trackers-filepath` and it redirs to a text file that can be updated easily and separately by users, and not necessarily to keep sync-ed in runtime.

**Comment by drws** [comment] 2023-07-17 20:24
This is a duplicate of #3881.

**Closed** 2023-07-17 22:36 UTC
Labels: pr welcome, type:feat
