### ISSUE TITLE
PR: Add WebRTC (Data Channel Only) Transport from libtorrent (Help Wanted)

### ISSUE THREAD

**Issue by frank-dspeed** [transmission/transmission#2886] opened 2022-04-06 05:29 UTC
This issue closes the following cluttered once: #47 #1717 

## Related Issues in libtorrent
- [ ] https://github.com/arvidn/libtorrent/pull/4123

## Search Terms
libtorrent, webrtc, webtorrent, magnet, link, dht, transmission, bittorrent,

**Comment by ckerr** [comment] 2022-04-06 06:16
I'm tempted to close this as a duplicate of #47, but since I'm not sure that I understand the goal of this issue -- @frank-dspeed could you clarify why this issue was filed? E.g. why should this become the issue to track this request when over a hundred people have emoji-voted in issue #47?

**Comment by frank-dspeed** [comment] 2022-04-06 07:10
@ckerr there is to much information in that issue this condenses it down so it is more easy to pick it up it takes to much time to read the old issue. we need to make it easy to pick that up.

**Closed** 2022-04-06 14:19 UTC
Labels: duplicate
