### ISSUE TITLE
macOS, v.3.00+, Crash report

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3101] opened 2022-05-16 11:16 UTC
[Crash report v.3.00+ (aa502f9312).zip](https://github.com/transmission/transmission/files/8699543/Crash.report.v.3.00%2B.aa502f9312.zip)

**Comment by ckerr** [comment] 2022-05-16 17:19
Thanks for the report!

This appears to be a dupe of #3088, so I'm closing this one. Followup discussion should go in 3088. Thanks!

**Closed by ckerr** 2022-05-16 17:19 UTC
