### ISSUE TITLE
Maximum peers per torrent setting doesn't work

### ISSUE THREAD

**Issue by andrasfuchs** [transmission/transmission#370] opened 2017-08-12 14:05 UTC
I use Transmission 2.92 on Windows 10.

If I set the Peer Limits on the Settings / Network tab, I got the following reactions:
* If I lower the Maximum peers overall setting, the number of connections drops instantly. If I increase it back up to 1024, it reconnects to peers. This works fine, this is the behavior I would expect.
* If I lower the Maximum peers per torrent thought, let's say to 3, nothing changes, all my torrents will have the same number of peers connected. They display things like "Downloading from 24 of 50 connected peers" or "Seeing to 14 of 21 connected peers". 

Pausing and restarting the torrent doesn't change the situation.

**Comment by pyrovski** [comment] 2018-09-17 06:09
Duplicate of #314?

**Comment by andrasfuchs** [comment] 2018-09-17 06:37
Yes, I think it is the same bug.

**Comment by ckerr** [comment] 2022-02-11 05:35
Closing as duplicate based on previous commnents

**Closed by ckerr** 2022-02-11 05:35 UTC
