### ISSUE TITLE
Feature Request: Re-read .resume file when starting a torrent

### ISSUE THREAD

**Issue by Markus-N** [transmission/transmission#4314] opened 2022-12-04 09:27 UTC
### What is the issue?

**Background info:** In my opinion, some creators of torrents suffer from subfolder-itis :-) meaning: they add unnecessary folders for almost every file in the torrent. Some torrents even have a single file in a subfolder. Previously, I've changed the folder/file structure after the torrent was finished, but I'd prefer having "my" names already while downloading. **I'm aware that this is kind of special.**

However ... I've found a way to hack the subfolder-itis :-) and it works like this:
* Pause the torrent (ideally before any content is downloaded)
* Stop transmission
* Edit the corresponding .resume file with a hex editor (details below)
* If there is already some downloaded content, reflect the changes in the filesystem
* Start transmission
* Start the torrent

**I'd like to remove the need of stopping and starting transmission.**  
I've tested editing the .resume file without restarting transmission (just pause/start the torrent), and my changes were ignored. I think re-reading the .resume file when starting a torrent would help.

Details about editing the .resume file:  
As long as I don't change the length of the paths/filenames, I don't break the file. So I just replace some **/** with a **_** and after restarting transmission, I can change the file names to the final (mostly shorter) names I would like to have.

It would be very great if this could make it into the upcoming version 4.0. :-)

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

3.00 (bb6b5a062e)

**Comment by mikedld** [comment] 2022-12-04 14:09
Resume files are considered internal to Transmission, so it has all the rights to think that they didn't change unless it has written to them itself. What you're asking for is certainly possible to implement, but I think a better solution would be to instead let you do the changes you want without resorting to a hex editor, which is both user-unfriendly and error-prone.

**Comment by Markus-N** [comment] 2022-12-04 14:37
I would be very happy to have such a tool within transmission. I just thought that this is way easier to implement. And because I'm unsure how many people want/need to change the directory structure, "easy to implement" could be a decision criterion :-)

I'm currently thinking about how this tool could be implemented in transmission as simple as possible. When I'm done, would you prefer if I add it to this feature request or should I open a new one?

**Comment by fredo-47** [comment] 2022-12-04 18:17
A workaround that does not require restart of Transmission:
1) Open the resume-file in your preferable (hex-)editor, and change it to your liking in the editor
2) In Transmission, remove the torrent, which will delete torrent- and resume-file from hard disk
3) Then back in your hex-editor, save the resume-file to its original place on hard disk
4) Re-add the torrent to Transmission. The existing resume-file (your modified version) will be detected and used

PS: Some editors may not be able to save the file in step 3, if it has already been deleted from hard disk.
In that case, you'd have to save it as a copy elsewhere before step 2, and then copy it over again before step 4.

**Comment by Markus-N** [comment] 2022-12-04 18:30
Oh, cool ... I'll test this next time when I add a torrent with too many subfolders.

**Comment by ckerr** [comment] 2022-12-16 21:18
I'm going to close this request since there's a workable alternative and agree with @mikedld

**Closed by ckerr** 2022-12-16 21:18 UTC

**Comment by rpatterson** [comment] 2024-10-27 18:54
> A workaround that does not require restart of Transmission:

Great tip, thanks!

Unfortunately, @ckerr, this doesn't work for changing the `done-date`, called `doneDate` in the RPC API, because Transmission seems to set it to the `added-date` after the torrent is re-added. I only tested this with a seeding torrent, so I'm not sure if this only happens for seeding items, but it makes some sense if that's the case. I confirmed this with a few different seeding torrents using `$ transmission-remote` to eliminate variables.

I can understand the rationale for making the dates that Transmission updates read-only and excluding them from [the `torrent-set` RPC API endpoint](https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#32-torrent-mutator-torrent-set), but I would argue there are valid use cases for changing those dates. In my case it's reconstructing a set of seeding torrents after Transmission re-wrote all my `/config/resume/*.resume` files when that file-system ran out of space.
