### ISSUE TITLE
Unable to create session lock file: Invalid argument (session-id.c:96)

### ISSUE THREAD

**Issue by lilws** [transmission/transmission#1391] opened 2020-08-09 03:08 UTC
I tried to upgrade transmission from 2.94 to 3.00 from synology packages.
After the upgrade, transmission log file stated that 
`Unable to create session lock file (22): Invalid argument (session-id.c:96)`
How can I trace to this error? since everything still working, only the error repeat every hour.

**Comment by lilws** [comment] 2020-08-11 08:51
A little bit of inspecting, I found that everytime I use a web interface or any programs like transgui to connect to transmission, this error will appears. So what really happen here?

**Comment by zoon01** [comment] 2020-09-12 18:03
same on freebsd

**Comment by negan07** [comment] 2021-03-10 11:37
The problem seems to belong to func code: `libtransmission/file-posix.c/tr_sys_file_lock()`
The lock can't be setup while opening webUI: file's created, but no lock can be setup generating the error.
This is not so critical but the webUI can go under runrace condition without it.

This happen I suppose running the daemon on old kernel machines not equipped with `F_OFD_SETLK`  and `F_OFD_SETLKW` flag support (present from 3.16 onward), with or without `fcntl()`

The preprocessor skip the related passing to the old non posix `flock()` based one

```
bool tr_sys_file_lock(tr_sys_file_t handle, int operation, tr_error** error)
{

...

#if defined(F_OFD_SETLK)

...

#elif defined(HAVE_FLOCK)

...

#else

...
    errno = ENOSYS;
    ret = false;
```

As it can be seen if no `F_OFD_SETLK` is defined, the preprocessor skip the code and check for `HAVE_FLOCK` flag presence.
If `HAVE_FLOCK` not defined, the code skip finally to error setup (maybe also `lockf()` could be tried as last failsafe)

A possible solution would be adding a `flock()` preliminary check at `configure` stage setting up `HAVE_FLOCK` if success, making the 2nd code block available at least.

```
--- a/configure.ac
+++ b/configure.ac
@@ -646,6 +646,21 @@ AM_CONDITIONAL(WIN32, test "x$have_msw"
 
 dnl ----------------------------------------------------------------------------
 dnl
+dnl  flock() presence
+AC_MSG_CHECKING(for flock declaration)
+have_flock=no
+AC_COMPILE_IFELSE([AC_LANG_PROGRAM([[
+#include <sys/file.h>
+]], [[void* p = flock]])],
+  [have_flock=yes])
+AC_MSG_RESULT($have_flock)
+
+if test "$have_flock" = yes ; then
+	AC_DEFINE(HAVE_FLOCK, 1, Define if you have the 'flock' function.)
+fi
+
+dnl ----------------------------------------------------------------------------
+dnl
 dnl  Generate the output
 
 AC_CONFIG_FILES([Makefile
```

**Comment by ckerr** [comment] 2022-02-22 18:55
Fixed by https://github.com/transmission/transmission/pull/2629.

#2555 was a duplicate of this, though I didn't recognize it at the time.

**Closed by ckerr** 2022-02-22 18:55 UTC
