### ISSUE TITLE
Special Characters in Magnet Links Break the magnet

### ISSUE THREAD

**Issue by Endlesszombiez** [transmission/transmission#608] opened 2018-05-04 12:15 UTC
I don't know if its a localized issue or a broad one; But for me if a magnet link has a special character particularly : or  | then it will get stuck and never connect to peers even with 4k seeders, after a minute or so it will turn red and give the "Unable to save resume file" error or something along those lines. Editing the name of the file in the magnet link fixes this. Tried multiple different links and they all do the same.

I'm on Winx64 2.94

**Comment by vctls** [comment] 2018-05-31 18:14
Same here on Windows 10.
The problem seems to be that transmission is trying to create a file with the exact name included in the magnet, which fails when there are forbidden characters like columns or slashes.

**Comment by Endlesszombiez** [comment] 2018-05-31 18:20
Ahh so it is a broader issue than i assumed. You can manually edit/fix each link but that's very tedious. Could probably code Transmission to scan the file name for the characters to delete them.

**Comment by vctls** [comment] 2018-05-31 18:29
But only on windows, maybe?
Well, it wouldn't be much of a loss for Linux users to have a few characters removed from the .torrent or .resume files.
I don't know which is causing the problem, by the way.
Are there any logs?

**Comment by vctls** [comment] 2018-05-31 18:31
I think this is a duplicate of #61

**Comment by mikedld** [comment] 2020-05-05 13:30
This was probably fixed as part of #122 (see bb4741002f832a8f1046196830917462d7063862) where resume files naming was changed. Feel free to test current nightly and report back.

**Comment by Endlesszombiez** [comment] 2020-05-05 14:56
> 
> 
> This was probably fixed as part of #122 (see [bb47410](https://github.com/transmission/transmission/commit/bb4741002f832a8f1046196830917462d7063862)) where resume files naming was changed. Feel free to test current nightly and report back.

Thank you for commenting! I got en email and decided to upgrade to the nightly to test it.
Looks like this issue is Fixed in 3.00+ (20119f006c)!
Thank you!

**Comment by mikedld** [comment] 2020-05-06 13:54
Closing then, thanks for testing!

**Closed by mikedld** 2020-05-06 13:54 UTC
