### ISSUE TITLE
Incomplete folder inconsistent behaviour with files and folders

### ISSUE THREAD

**Issue by ntorrente** [transmission/transmission#374] opened 2017-08-16 22:25 UTC
Settings:
![settings](https://user-images.githubusercontent.com/7033291/29386856-eec79b5c-82b3-11e7-9e74-c604bd8a58dd.jpg)

Behaviour:
![downloads](https://user-images.githubusercontent.com/7033291/29386896-1bd5e838-82b4-11e7-8277-2ee82afe9542.JPG)

Folders:
- They are moved to the wanted location [OK]
- When using the "open folder" feature on the torrent, it goes to the correct folder. [OK]
- When using the delete torrent and files feature it does not delete the folder neither the files.

Single files:
- They stay on temp folder when torrent finish.
- When using the "open folder" feature on the torrent, it opens the "Documents" directory and not the actual folder.
- When using the delete torrent and files feature it removes it from the temp folder. [OK?]

Contextual information:
- Transmission 2.92+ (38d3d5377b) nightly build (ago 11, 2017 7:51:07 a.m.) (also seen on stable 2.92)
- OS: Windows 10

**Comment by slrslr** [comment] 2020-08-13 13:26
i think that i am having same problem described under paragraph "Single files", contrary to OP i am using newer version: Transmission 3.00+

**Comment by mikedld** [comment] 2020-08-28 08:12
Please don't combine multiple issues in one report. See #325.

**Comment by sabotagebeats** [comment] 2020-12-08 07:06
I have this same problems on windows 10

**Comment by ckerr** [comment] 2023-03-13 23:18
Closing as a duplicate of #325.

If the other issues in this ticket persist, please open individual tickets for each issue. As @mikedld said above, the project tries to keep one topic per issue to make it possible to productively search & triage the issue tracker.

**Closed by ckerr** 2023-03-13 23:18 UTC
Labels: scope:qt, os:windows
