### ISSUE TITLE
Watched folder no longer works

### ISSUE THREAD

**Issue by nickdpi** [transmission/transmission#4820] opened 2023-02-11 07:23 UTC
### What is the issue?

Upon upgrading to 4.0.0, watched folders no longer work.

- Expected: drag torrent into folder, torrent is added to Transmission & deleted.
- Actual: drag torrent into folder, nothing happens.

Torrents _are_ correctly parsed in folder when you go into Preferences and reselect the folder.

My folder has an exclamation point in it, so perhaps that may be the issue.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0

**Comment by ckerr** [comment] 2023-02-11 14:01
Does it work for you if you use a folder that does not have an exclamation mark?

**Comment by coryoksiuta** [comment] 2023-02-12 18:27
I have the same issue. It'll check the directory on app load, but won't catch anything added after the app is loaded. On Monterey.

**Comment by ckerr** [comment] 2023-02-12 20:04
Does it work for you if you use a folder that does not have an exclamation mark?

**Comment by coryoksiuta** [comment] 2023-02-13 00:27
None of my folders have exclamation marks. Its just a Torrents folder under Downloads.

**Comment by ckerr** [comment] 2023-02-13 05:33
@sweetppro do you have time to take a look into this?

**Comment by nickdpi** [comment] 2023-02-13 08:05
Same issue without exclamation mark. macOS 13.2, for the record.

**Comment by coryoksiuta** [comment] 2023-02-15 06:33
Did some testing. 
On restart of app, it will check the directory and get the new torrents. 
On toggling of the checkbox for watching the directory it will get the new torrents. 
My current watch directory is Downloads/Torrents
Tried switching it to just Downloads, no go.
Created a Test directory under Downloads and set it the new directory and then moved a .torrent file into it, THAT got picked up.

I was also an upgrade from an earlier version. So likely that's part of the issue.

**Comment by anthonyeleven** [comment] 2023-02-15 22:21
M1 Ultra, Ventura 13.2

Upgraded from 3.latest to 4.0.0 (280ace12f8)

Transmission previously mostly (but not always) picked up a torrent file saved in ~/Downloads by Firefox, with 4.0.0 it no longer does for me either.  When I `mkdir ~/Downloads/torrents` and point Transmission's watch directory there, it works as expected, as does saving the `.torrent` into `/tmp` and `mv`ing it into `~/Downloads` after reverting Transmission's watch directory there as before.  So much like Cory's experience.

**Comment by jaegan438** [comment] 2023-02-19 14:42
Same issue.  10.15.7 Catalina on an intel machine. torrents are only picked up when launching app, or toggling setting in preferences since upgrading to version 4

**Comment by anthonyeleven** [comment] 2023-02-19 14:47
Update on my comment above - after a short time it stopped working.  I’ve reverting to using `open` from a shell.

**Comment by ckerr** [comment] 2023-02-25 13:00
This appears to be a duplicate of https://github.com/transmission/transmission/issues/4683 so I'm closing this ticket as a dupe.

**Closed by ckerr** 2023-02-25 13:00 UTC
Labels: bug, needs clarification, scope:mac, needs confirmation, needs testers
