### ISSUE TITLE
Error: No data found!

### ISSUE THREAD

**Issue by kov-serg** [transmission/transmission#345] opened 2017-07-25 11:25 UTC
Very funny bug.

Let assume transmission default download directory is ~/Downloads
You have a.torrent it containg data about a.txt
You place downloaded before file a.txt into ~/Downloads
Then open a.torrent in transmission. Transmission asks you for "Destination folder" you wait several seconds. Transmission finds out that file is already there and you have 100% downloaded.
Then you select different directory to download for example ~/Desktop where no a.txt and it still belive you have 100% of a.txt
Then press "Open"
And you'll have "Error: No data found! Ensure your drives are connected or use ..."

**Comment by gkaklas** [comment] 2017-09-02 14:42
This is not a bug. When you set the location of a torrent you are asked if you want to move the data or if the data is already there. If you select a new location with the option that says that the data is there and they aren't, you get this error. You just need to select the option to move the data in the new folder when setting the new location.

**Comment by Alkaris** [comment] 2018-08-27 03:12
@gkaklas Don't be so dismissive. This is indeed a bug and I can confirm.

```
Error: No data found! Ensure your drives are connected or use "Set Location". To re-download, remove the torrent and re-add it.
```

I'm facing an exact same issue here. I've got a torrent that's downloaded to one of my external hard drives that's connected via USB, the file is 100% there, but returns an error saying the data isn't found when it clearly is and the drive is connected an active. This seems to be stagnant issue for Windows build of Transmission in particular. You also can't even 'Set Location' or get Transmission to 'Verify Local Data' either, you can select where the files go of course, but it doesn't update for the torrent itself, leaving it to hang on the error.

**Comment by gkaklas** [comment] 2018-08-27 13:13
Oops I'm sorry, I didn't want to sound dismissive :smiley: 

> Then you select different directory to download for example ~/Desktop where no a.txt and it still belive you have 100% of a.txt
> Then press "Open"
> And you'll have "Error: No data found! Ensure your drives are connected or use ..."

@kov-serg's issue describes that when they set the download location to a directory that doesn't have the file, they get the error `Error: No data found!`, which I think is expected.

>  it still belive you have 100% of a.txt

However, now that I read again the description, the real bug maybe isn't the `No data found!` error itself, but the fact that after setting the new folder, transmission doesn't detect that the file isn't there until after you try to open it. :thinking: 

@Alkaris I too get this error if I connect my drive *after* opening transmission, in which case I have to quit and start it again or else I get stuck with the error. Again, this is expected, since if transmission starts and doesn't find the file it says that it couldn't find the file.

But that is a different issue: maybe we shouldn't have to restart transmission for it to find the data, for example probably the "verify local data" option should be enough. :thinking:

**Comment by Alkaris** [comment] 2018-08-27 18:43
@gkaklas I've tried quitting Transmission and restarting it but for some reason it still gives the same error even after closing it completely. I don't seem to get this issue when I do this on Linux, cuz if there's an error like that it detects automatically what drives are detected even if you mountain the drives after opening Transmission. Same external drive I use in Windows which is formatted ExFAT which gives the best support across OS's between Windows, Mac and Linux and does files bigger than the 4GB limit you would normally get with FAT32 partitions. I'll need to try more testing by completely removing the torrent data and re-adding it like it initially suggests in the error message.

**Comment by newnah** [comment] 2018-12-06 14:13
I have found what is causing this issue. It's not a bug, rather just bad design. When specifying a directory transmission looks for the file inside that directory. Essentially you need to traverse one level higher than what you would expect. For example, If I wanted to specify the data location to be:
/home/github/folder
I would need to select /home/github as my file location, not /home/github/folder, as transmission appends /folder to the directory specified. If I had selected /home/github/folder as my file location, it would be looking for /home/github/folder/folder resulting in the error 'no data found'.

**Comment by cjohnweb** [comment] 2019-05-04 07:21
This is happening to me as well for some torrents on upload. I upload a torrent via magnet url, set to the same location as I always use and some torrents give me this error while others do not. Here is one such torrent: ( magnet:?xt=urn:btih:E20EFBEE11972B4585387ED513DE8FD29AEED0B3&dn=Game+of+Thrones+Season+1-7+1+2+3+4+5+6+7+Complete+1080p&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.istole.it%3A6969&tr=udp%3A%2F%2Fopen.demonii.com%3A1337 )

I have 100GB free and this tends to be randomly appearing for other torrents too.

**Comment by AxeleratedDragon** [comment] 2019-10-28 14:25
If you face this problem in Ubuntu it might be because you disabled auto-mount of drives with 'dconf editor'. I think the best solution is to activate your drive(simply open the drive) where your torrent download is in before you start transmission. if you already made a mistake make sure to activate the drive before choosing set location -> local data is already there->apply(to show transmission where the torrent download is located since transmission do not seem to remember) , wait for verification then it should be alright.

**Comment by thebitstick** [comment] 2020-06-14 00:44
Still not fixed. Just encountered this bug on 2.94, Debian Buster.

**Comment by Mhowser** [comment] 2020-11-18 05:56
@thebitstick did you read this? https://github.com/transmission/transmission/issues/345#issuecomment-444883740

**Comment by AmbitiousDan** [comment] 2020-12-16 05:37
I'm having the same problem. Didn't even know at first. But one day torrent-remote crashed. When I restarted it (Ubuntu 20.04 LTS) I did systemctl status transmission-daemon to ensure it was running. It was but I got a whole TON of files saying that the data could not be found. It says to remove it and re-add it. Thing is, most of these files were added via Magnet links. And I can't find anywhere that transmission is making an actual .torrent file, So do I have to go through the entire list of files (a little over 250) and re-find EACH AND EVERY MAGNET LINK? If torrent-remote knows about the files, shouldn't it be able to generate a .torrent for the files?  How does one go about deleting and re-adding torrents? Who KEEPS .torrent files once they are added to the torrent program, unless of course the torrent program itself does.

**Comment by AmbitiousDan** [comment] 2020-12-16 05:38
Oh, and I tried the idea of moving data, but the torrent doesn't even SHOW UP in Transmission's remote GUI, which is how I control the transmission daemon running on a headless machine.

**Comment by marko-avlijas** [comment] 2022-01-23 14:18
> I have found what is causing this issue. It's not a bug, rather just bad design. When specifying a directory transmission looks for the file inside that directory. Essentially you need to traverse one level higher than what you would expect. For example, If I wanted to specify the data location to be: /home/github/folder I would need to select /home/github as my file location, not /home/github/folder, as transmission appends /folder to the directory specified. If I had selected /home/github/folder as my file location, it would be looking for /home/github/folder/folder resulting in the error 'no data found'.

This is true. Also it's necessary to click start now to start seeding and clear the error message.

I propose 2 changes to Set Location functionality:

1. In "Set Torrent Location" dialog add message like "Please select parent folder in which this file/folder resides".
2. After location has been set, automatically clear the error message in list of torrents.

I believe UX will be a lot less confusing with these 2 changes.

**Comment by Mhowser** [comment] 2022-01-23 23:34
Exactly, this confused the heck out of me as a first time user.

**Comment by ckerr** [comment] 2022-01-27 04:35
Closing, this is a dupe of #83

**Closed by ckerr** 2022-01-27 04:35 UTC
Labels: bug, pr welcome

**Comment by zand-yasin** [comment] 2023-09-29 11:11
This fixed the error for me, and the download resumed.

1. Right-click on the file the error appears.
2. Click on Set Location.
3. Set the torrent location to where you previously selected to save your files. (Keep in mind, set one directory behind the actual content).
4. Select Move from the current folder.
5. apply.

Note: if it didn't fix, you may have selected the wrong path in the 3rd instruction again.

**Comment by ScarletMcLearn** [comment] 2024-04-09 09:23
I tried everything mentioned here.
They do not work.
