### ISSUE TITLE
Perhaps it's time for a new release?

### ISSUE THREAD

**Issue by BuonHobo** [transmission/transmission#3754] opened 2022-09-04 10:05 UTC
Transmission's latest release is 3.00 and it is from 2020. Transmission's development has been going on since then and it's difficult to track how up to date a package is (since they are all 3.00).

The flathub version, for example, has the exact version that came out in 2020 ([based on this commit](https://github.com/transmission/transmission/commit/bb6b5a062ee594dfd4b7a12a6b6e860c43849bfd)).

Some other packages might be based on more recent commits, but they all are 3.00. I think a new release would make it easier to know if we're using a recent version or not. It would also probably stimulate maintainers to update their package from the old 3.00 to the new 3.xx version.

What do you think?

**Comment by orowith2os** [comment] 2022-09-04 10:07
One more question I'll toss in here: Is there anything that a new release should watch out for? I can help update the flathub manifest if it makes some changes that would affect it.

**Comment by mangosplat** [comment] 2022-09-04 10:49
Duplicate of #2287 

Lead dev already commented on this topic in that thread.

**Comment by nevack** [comment] 2022-09-04 11:47
Yup, Duplicate of https://github.com/transmission/transmission/discussions/2287

**Closed by nevack** 2022-09-04 11:47 UTC
