### ISSUE TITLE
LetsEncrypt / DST Root CA X3 expiration: some trackers fail to connect on Mac.

### ISSUE THREAD

**Issue by theirongiant82** [transmission/transmission#1876] opened 2021-10-02 00:58 UTC
Some trackers were using LetsEncrypt to generate SSL certificates.  On Tuesday September 30, one of these roots expired.  The trackers in question have already rotated their certificates long ago and they are now issued from a different root certificate - for example, ISRG Root X1.  A test at SSL Labs (Qualys) confirms this.  

Although other apps like Deluge seem to be able to connect to these trackers––even the older 1.3 release––Transmission 3.00 is not honoring the expiration and still failing to connect to the trackers.

One support article for apps that facilitate NNTP downloads explains that the app requires an update from the developer to resolve the issue:

https://support.newshosting.com/kb/article/534-tls-certificate-verification-failed/

In the MacOS keychain, the "System Roots" already show the above cert has expired, and Transmission should not keep using it, but it does.

**Comment by Tockman** [comment] 2021-10-02 08:10
Oh yes, it's a very annoying problem! Third day I can not connect to SSL protected trackers. Please help.

**Comment by andreygursky** [comment] 2021-10-03 17:47
As an immediate workaround you could disable SSL certificate verification by setting the environment variable ```TR_CURL_SSL_NO_VERIFY=1```.

Since the Let's Encrypt certificate is valid, the encountered bug should be in an SSL library implementation. I'm curious, whether Transmission for MacOS is bundled with an outdated SSL library or it is built against some MacOS native SSL library and your MacOS is outdated.

What is the exact version of your MacOS?

(I'm not a Mac user, just trying to figure out some details.)

**Comment by Tockman** [comment] 2021-10-03 17:52
> TR_CURL_SSL_NO_VERIFY=1
In what specific file may I change this variable?

> What is the exact version of your MacOS?
macOS 12 Monterey Beta 8.

**Comment by theirongiant82** [comment] 2021-10-03 18:16
This computer has macOS 10.14.6 Mojave.  Not the newest, but still reasonably well supported.  It also has the ISRG Root CA in the System Roots list.  This authority is the root for the cert used by one of the trackers that Transmission is unable to contact (but Deluge is).

**Comment by theirongiant82** [comment] 2021-10-03 18:17
> As an immediate workaround you could disable SSL certificate verification by setting the environment variable `TR_CURL_SSL_NO_VERIFY=1`.
> 
> Since the Let's Encrypt certificate is valid, the encountered bug should be in an SSL library implementation. I'm curious, whether Transmission for MacOS is bundled with an outdated SSL library or it is built against some MacOS native SSL library and your MacOS is outdated.
> 
> What is the exact version of your MacOS?
> 
> (I'm not a Mac user, just trying to figure out some details.)

Already tried this, no effect.

**Comment by andreygursky** [comment] 2021-10-03 18:19
@Tockman
> In what specific file may I change this variable?

Could you try, what search on Internet suggest?

**Comment by andreygursky** [comment] 2021-10-03 18:20
@theirongiant82 
> Already tried this, no effect.

How did you set it? Do you use Transmission 3.0?

**Comment by Tockman** [comment] 2021-10-03 18:22
You know, I'm busy with that for third day. All environment variables they offer to change, are on Linux systems. No one specific notice what to do with macOS ;)

**Comment by esabol** [comment] 2021-10-03 18:36
> All environment variables they offer to change, are on Linux systems. No any specific notice what to do with macOS ;)

Try this:

1. Open the Terminal app on your Mac.
2. Execute the following command:
```
env TR_CURL_SSL_NO_VERIFY=1 open /Applications/Transmission.app
```

**Comment by andreygursky** [comment] 2021-10-03 18:38
Looking into https://github.com/transmission/transmission/tree/976fec6e94ad74bb7b1aaad4167fcf153eeb6181/third-party/openssl reveals Transmission is likely to use it's own copy of the OpenSSL library. The last commit:
"Update curl and openssl to those in 10.10 SDK (macOS)" https://github.com/transmission/transmission/commit/3538eb93c3d3b6cf8c5bf8315635a5db5ffa3a6c.
So accordingly to https://letsencrypt.org/docs/certificate-compatibility/
> These platforms would have worked up to September 2021 but will no longer validate Let’s Encrypt certificates.
> macOS < 10.12.1

version 10.10 that Transmission 3.00 uses is unfortunately broken. And hopefully there could be an urgent Transmission 3.01 release with at least OpenSSL (and maybe curl) updated.

**Comment by theirongiant82** [comment] 2021-10-03 18:41
I’d say this is the underlying issue.  “Nurse!  We need 20 gcc’s of compilazene, STAT!

**Comment by Tockman** [comment] 2021-10-03 18:42
> env TR_CURL_SSL_NO_VERIFY=1 open /Applications/Transmission.app
Did that. As of now - no change, Transmission still won't connect to SSL announcer.

**Comment by theirongiant82** [comment] 2021-10-03 18:42
@Tockman : confirmed, I had tried that also.  No effect.

**Comment by esabol** [comment] 2021-10-03 18:48
Weird. It works for me on 10.13.6. Are you using Transmission 3.0.0? Maybe Mojave changed something with how environment variables are set when opening an application.

Maybe try this method:
https://stackoverflow.com/a/58164730/5153779

**Comment by Tockman** [comment] 2021-10-03 18:51
@esabol 
You mean Monterey, not Mohave. Yes, Transmission 3.0.0.

**Comment by esabol** [comment] 2021-10-03 19:17
> Maybe try this method: https://stackoverflow.com/a/58164730/5153779

This method also worked for me. I created a text file named `setenv.TR_CURL_SSL_NO_VERIFY.plist` in `$HOME/Library/LaunchAgents/` with the following contents:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  <plist version="1.0">
  <dict>
  <key>Label</key>
  <string>setenv.TR_CURL_SSL_NO_VERIFY</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/launchctl</string>
    <string>setenv</string>
    <string>TR_CURL_SSL_NO_VERIFY</string>
    <string>1</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
```
Then, in the Terminal, I executed the following command:
```
launchctl load ~/Library/LaunchAgents/setenv.TR_CURL_SSL_NO_VERIFY.plist
```
Then I quit and re-launched Transmission. After doing that, I was able to connect to an https tracker that was giving me problems before.

**Comment by Tockman** [comment] 2021-10-03 19:30
@esabol 
Alas, even that doesn't work for me :(

**Comment by esabol** [comment] 2021-10-03 19:53
Do you get an error of some sort?

**Comment by Tockman** [comment] 2021-10-03 19:55
With a .plist - no. It created and loaded well. Just an announcer error: Could not connect the tracker.

**Comment by esabol** [comment] 2021-10-03 20:10
I've heard that reverting back to Transmission 2.9.4 works on some older Mac OS versions, such as Mojave. (SSL verification was turned off in 2.9.4.) I don't know about macOS Monterey.

**Comment by Tockman** [comment] 2021-10-03 20:18
Oh no, I remember that Transmission screwed all my torrent library while upgraded to 3.00 (it lost locations of majority of files), and I restored 1000 files' whereabouts by hand. It took about 5 hours. The second downgrade-upgrade cycle I won't do ;)

**Comment by theirongiant82** [comment] 2021-10-04 06:25
> > Maybe try this method: https://stackoverflow.com/a/58164730/5153779
> 
> This method also worked for me...
>
> [...]
> 
> Then I quit and re-launched Transmission. After doing that, I was able to connect to an https tracker that was giving me problems before.

Confirmed.  This workaround fixed the issue immediately on my Mac.

**Comment by ahujet** [comment] 2021-10-04 11:16
There is same issue on Windows build too.

**Comment by theirongiant82** [comment] 2021-10-08 15:44
It’s telling Transmission not to verify SSL connections, the equivalent of `curl -k`.  

The connections are still secure, but having expired certificates does technically reduce your security posture.

**Comment by al3xtjames** [comment] 2021-10-10 21:02
Building Transmission with Homebrew-provided cURL seems to fix this (for me, at least).

**Comment by Tockman** [comment] 2021-10-11 06:58
@al3xtjames
You built a version for Mac? Won't you be so kind as to share it?

**Comment by 2V3EvG4LMJFdRe** [comment] 2021-10-14 04:37
@al3xtjames 
Another request for the macOS version, if at all possible...

**Comment by al3xtjames** [comment] 2021-10-16 07:11
Here is Release CMake build of 7b423b7e0d618ab3c83a170ea0fd306425df959f on macOS 11.6. This uses Homebrew-provided versions of OpenSSL and cURL (`export PKG_CONFIG_PATH="/usr/local/opt/openssl@3/lib/pkgconfig:/usr/local/opt/curl/lib/pkgconfig"` prior to building). I've bundled the libraries with [macpack](https://github.com/chearon/macpack). This was done on macOS 10.14.6, so it should work on 10.14+ (bundling Homebrew libraries from 11.x limits compatibility to 11.x).

[Transmission.app.zip](https://github.com/transmission/transmission/files/7357088/Transmission.app.zip)

**Comment by al3xtjames** [comment] 2021-10-16 07:53
This should be fixed (had to update rpath and bundle the missing framework):

[Transmission.app.zip](https://github.com/transmission/transmission/files/7357182/Transmission.app.zip)

**Comment by al3xtjames** [comment] 2021-10-17 03:21
It seems like Transmission (or the native cURL) is using `/etc/ssl/cert.pem`. Updating this cert bundle resolved the issue with official releases of Transmission.

**Comment by theirongiant82** [comment] 2021-10-17 03:54
@al3xtjames : it should not be necessary for users to edit this file, which risks them destroying the entire system root collection.  

As I mentioned in my opening notes, other clients like Deluge have no issue.  They know to ignore the expired roots.   Transmission’s SSL libraries are so old they may not know how to deal with newer roots.

**Comment by al3xtjames** [comment] 2021-10-17 04:45
Of course, this is merely a workaround, not a proper fix. AFAIK Deluge ships its own copy of OpenSSL, which may explain why it isn't affected. By default, Transmission on macOS uses the system cURL. On macOS 10.14, this uses the system LibreSSL (v2.6.5). OpenSSL versions prior to 1.1.0 [are known to have a quirk resulting in rejection of certificates cross-signed with the expired DST Root CA X3](https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/). I suspect that LibreSSL 2.6.5 suffers from the same issue.

**Comment by Tockman** [comment] 2021-10-17 07:20
@al3xtjames 

> Removing DST Root CA X3 from the cert bundle resolves this issue
In fact, it was the first I did since the problem has appeared. But you can not delete it from Certification Centers on Mac...

**Comment by al3xtjames** [comment] 2021-10-17 07:25
Did you manually edit /etc/ssl/cert.pem? I'm not sure if it is synchronized with System Roots in Keychain.

**Comment by Tockman** [comment] 2021-10-17 07:39
No, I manually delete it in KeyChain. It doesn't appear anymore.

**Comment by Tockman** [comment] 2021-10-17 08:38
Nope, this one doesn't want to connect to SSL tracker, again.

**Comment by amandamana** [comment] 2021-10-18 22:49
> What did you modify exactly? @amandamana
I deleted the whole certificate block similar to [step 7 here](https://docs.hedge.video/remove-dst-root-ca-x3-certificate).

**Comment by Tockman** [comment] 2021-10-19 15:38
@theirongiant82 

It's reasonable enough. But why on Beta 10 it launched successfully and on RC two days later it won't?

**Comment by Tockman** [comment] 2021-10-19 15:58
@tabanger 
To be more exact, something weird is going on with some of SSL trackers. My Transmission is able to connect to some of them and unable to another ones. So it's not persistent or configuration depended problem.

**Comment by HamburgerPlsdotexe** [comment] 2021-11-21 23:30
Is there any update regarding this? I use transmission 3. on Windows and I still can't connect to some trackers due to the outdated CA

**Comment by Tockman** [comment] 2021-12-01 18:37
@tabanger 

> 1. Download cacert.pem from https://curl.se/docs/caextract.html
> 2. Backup the existing cert store: sudo cp -p /etc/ssl/cert.pem /etc/ssl/cert.pem.bak
> 3. Install the new store: sudo mv ~/Downloads/cacert.pem /etc/ssl/cert.pem

I've found that there's one more location for cert.pem: /System/Library/Templates/Data/private/etc/ssl/cert.pem, where it remains unchangeable and where from it overwrites our "new" storage. Have I to replace it with the new storage also (having in mind that it's read-only location)?

**Comment by tabanger** [comment] 2021-12-01 21:20
> I've found that there's one more location for cert.pem: /System/Library/Templates/Data/private/etc/ssl/cert.pem, where it remains unchangeable and where from it overwrites our "new" storage. Have I to replace it with the new storage also (having in mind that it's read-only location)?

That directory path only exists in the read-only system volume of Catalina and later.  Since the correct certs are already included in the certificate bundle in Catalina and later, there is no need to modify that cert.pem file where it appears.

**Comment by Tockman** [comment] 2021-12-03 18:23
Anyway, it still doesn't work on Monterey even after cert.pem change..

**Comment by GScottElshaw** [comment] 2021-12-03 21:28
It doesn't work for me on Big Sur.

**Comment by ckerr** [comment] 2022-01-19 00:18
The discussion in https://github.com/transmission/transmission/issues/2429 is, I think, the same as this issue, so I'm closing one of them as a dupe.

**Comment by esabol** [comment] 2022-01-19 03:02
> The discussion in #2429 is, I think, the same as this issue, so I'm closing one of them as a dupe.

This issue came first though, and it has more useful discussion, imho. Usually, one closes the later issue as the dupe, not the original.

**Comment by ckerr** [comment] 2022-01-19 18:19
Yeah that's a fair point.

**Comment by Tockman** [comment] 2022-01-29 02:14
I hasten to inform that today, after installing Beta 1 of macOS Monterey 12.3 I've found our old nasty problem solved. Now it seems it was OS related, more or less:
![Снимок экрана 2022-01-29 в 05 10 40](https://user-images.githubusercontent.com/74548419/151643325-bf6f4adf-bc5a-4e86-9801-b6576e752ae7.png)

**Comment by GScottElshaw** [comment] 2022-01-29 02:22
No such joy here with the Big Sur update from the day before.

**Comment by al3xtjames** [comment] 2022-02-05 06:32
The issues being reported on 11.x/12.x seem unrelated. I had no problems connecting to a tracker using an affected Let's Encrypt certificate in a fresh 11.6.1 VM with the official Transmission 3.00 release. I could easily reproduce this issue in a 10.14.6 VM.

**Comment by GScottElshaw** [comment] 2022-02-05 06:43
Sweet! I'm on 11.6.3, installed ISRG Root X1 and ISRG Root X2 the other day and no dice.

**Comment by al3xtjames** [comment] 2022-02-05 06:45
https://github.com/transmission/transmission/issues/1876#issuecomment-946781217 should've made this clear - modifying the root CA store via Keychain Access will not change anything. The system libcurl uses /etc/ssl/cert.pem, which is not updated as far as I can tell.

**Comment by GScottElshaw** [comment] 2022-02-05 07:12
> The system libcurl uses /etc/ssl/cert.pem, which is not updated as far as I can tell.

It's not, been there and done that too. Much of what seems to be a muddle is Apple changing to a different process and provider. I think this might be key for the developers to have a look at for Transmission on OSX. https://www.apple.com/certificateauthority/

**Comment by tabanger** [comment] 2022-02-05 09:54
OK, I'm going to try to put this issue to bed once and for all.  The specific problem addressed in this issue is that the DST Root CA X3 expired, which causes HTTPS connections to trackers using LetsEncrypt SSL certificates to fail if the system openssl/libressl root certificate store has not been updated.

I ran tests on brand-new, freshly installed systems to determine which are affected by this specific issue.  The results are below:

### High Sierra 10.13.6
Connections to LetsEncrypt certificate sites failed out-of-the-box:
```
$ ls -la /etc/ssl/cert.pem
-rw-r--r--  1 root  wheel  227344 Dec  4  2017 /etc/ssl/cert.pem

$ curl https://www.letsencrypt.org -v
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html
```
After replacing cert.pem with the latest version provided by curl.se (using the instructions [above](https://github.com/transmission/transmission/issues/1876#issuecomment-946781217)), trying to connect again was successful:
```
$ curl https://www.letsencrypt.org -v
*  SSL certificate verify ok.
Redirecting to https://letsencrypt.org/
```

### Mojave 10.14.6
Connections to LetsEncrypt certificate sites failed out-of-the-box:
```
$ ls -la /etc/ssl/cert.pem
-rw-r--r--  1 root  wheel  196928 Mar 21  2019 /etc/ssl/cert.pem

$ curl https://www.letsencrypt.org -v
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
* SSL certificate problem: certificate has expired
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html
```
After replacing cert.pem with the latest version provided by curl.se (using the instructions [above](https://github.com/transmission/transmission/issues/1876#issuecomment-946781217)), trying to connect again was successful:
```
$ curl https://www.letsencrypt.org -v
*  SSL certificate verify ok.
Redirecting to https://letsencrypt.org/
```

### Catalina 10.15.7
Connections out-of-the-box were successful:
```
% ls -la /etc/ssl/cert.pem
-rw-r--r--  1 root  wheel  346545 Jun 11  2020 /etc/ssl/cert.pem

% curl https://www.letsencrypt.org -v
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
*  SSL certificate verify ok.
Redirecting to https://letsencrypt.org/
```

### Big Sur 11.6
Connections out-of-the-box were successful:
```
% ls -la /etc/ssl/cert.pem
-rw-r--r--  1 root  wheel  346545 Dec 31  2019 /etc/ssl/cert.pem

% curl https://www.letsencrypt.org -v
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
*  SSL certificate verify ok.
Redirecting to https://letsencrypt.org/
```

### Monterey 12.1
Connections out-of-the-box were successful:
```
% ls -la /etc/ssl/cert.pem
-rw-r--r--  1 root  wheel  333483 Dec  7 13:39 /etc/ssl/cert.pem

% curl https://www.letsencrypt.org -v
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  SSL certificate verify ok.
Redirecting to https://letsencrypt.org/
```

### Conclusions
As you can see from the testing above, this specific issue (LetsEncrypt certificate validation failures due to the expiration of DST Root CA X3) only affects Mojave and earlier.  You can correct the issue by using the 3 step process outlined earlier.

**If you are on Catalina or later, this issue does not apply to your system.**  Your issue is something else.  Open a new issue or create a new post in the discussion forum.

Actions for Transmission devs:  none that I can see.  As systems age and no longer receive updates, root certificates on the system will age and expire.  It's up to the user to maintain those certificate stores.  In this case, it's an easy procedure.  You shouldn't be downgrading Transmission's encrypted connection handling by ignoring chain of trust errors.

**Comment by GScottElshaw** [comment] 2022-02-05 10:25
Okay. I am genuinely in awe of your self-assurance, would you mind documenting a step by step method for users? Unless i'm grossly misunderstanding, the conversation moved beyond the expiry of CA X3 long ago, i'm not even sure if that expiry was a determining factor in being unable to connect with https trackers, but a rationale for why.

I'm sorry, but there are many MacOS users who are unable to connect with https trackers using Transmission regardless of their version of MacOS. You're telling me that out of the box Big Sur can connect with https trackers when I can't? That's fine. So tell me again that my daily use, where i am an advanced user of the OS since 1983 is emblematic of a failure of what, imagination?

Please continue.

ls -la /etc/ssl/cert.pem
-rw-r--r--  1 root  wheel
-rw-r--r--@ 1 garyelshaw  staff  344407  2 Feb 02:28 /etc/ssl/cert.pem
zsh: command not found: -rw-r--r--

**Comment by tabanger** [comment] 2022-02-05 10:33
You're in the wrong ticket.  The "conversation moved beyond the expiry of CA X3" because you and Tockman issue-creeped it by bringing up unrelated connection issues.  TLS connections can fail for dozens of reasons.  This ticket is about the DST Root CA X3 expiration only.  Don't hijack it.  You've got your own ticket, #2429, which I will respond to there.

**Comment by GScottElshaw** [comment] 2022-02-05 10:34
Oh wow.

**Comment by Tockman** [comment] 2022-02-05 10:37
> You've got your own ticket, #2429, which I will respond to there.

#1876, you mean, because #2429 is closed.

**Comment by tabanger** [comment] 2022-02-05 10:37
No.  #2429.  It should be reopened, because it is not a dupe of this one, #1876.  Your issues are not related to #1876.

**Comment by Tockman** [comment] 2022-02-05 10:44
@tabanger 
I like your confidence - mostly because my problem seems to be solved. But if it wasn't i'd be ready to fight not less than respected **GScottElshaw** does.

**Comment by Tockman** [comment] 2022-02-06 00:07
> I hasten to inform that today, after installing Beta 1 of macOS Monterey 12.3 I've found our old nasty problem solved. Now it seems it was OS related, more or less:
> ![Снимок экрана 2022-01-29 в 05 10 40](https://user-images.githubusercontent.com/74548419/151643388-8f2c5f31-b0fb-402a-bc8f-a5969d23b222.png)

I have to apologize a lot. In fact, "after installing Beta 1 of macOS Monterey 12.3" I've got not the problem solved, but TR_CURL_SSSL_NO_VERIFY script working. As soon as I turned it off - everything returned to "could not connect to tracker" state. So the problem still stays on :(

**Comment by tabanger** [comment] 2022-02-06 00:42
@Tockman, as we already determined, your issue is unrelated to the topic of this Ticket (expired LetsEncrypt root).  But I’d be happy to try to help you in a different ticket.  #2429 would probably be appropriate.  Can you list the trackers and curl results in there, like we did with the other tests in there?

**Comment by briantully** [comment] 2022-04-05 17:22
> > Maybe try this method: https://stackoverflow.com/a/58164730/5153779
> 
> This method also worked for me. I created a text file named `setenv.TR_CURL_SSL_NO_VERIFY.plist` in `$HOME/Library/LaunchAgents/` with the following contents:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
>   <plist version="1.0">
>   <dict>
>   <key>Label</key>
>   <string>setenv.TR_CURL_SSL_NO_VERIFY</string>
>   <key>ProgramArguments</key>
>   <array>
>     <string>/bin/launchctl</string>
>     <string>setenv</string>
>     <string>TR_CURL_SSL_NO_VERIFY</string>
>     <string>1</string>
>   </array>
>   <key>RunAtLoad</key>
>   <true/>
> </dict>
> </plist>
> ```
> 
> Then, in the Terminal, I executed the following command:
> 
> ```
> launchctl load ~/Library/LaunchAgents/setenv.TR_CURL_SSL_NO_VERIFY.plist
> ```
> 
> Then I quit and re-launched Transmission. After doing that, I was able to connect to an https tracker that was giving me problems before.

@esabol you are a lifesaver! Thank you so much for this fix. I owe you many beers! 🍻 🍻 🍻

**Comment by briantully** [comment] 2022-04-13 21:41
Interesting. The LaunchAgent plist file workaround works for the most part, but I'm noticing that Transmission seems to forget the `TR_CURL_SSL_NO_VERIFY=1` env setting every now and then. It's as if every few hours or so it reloads its default `TR_CURL_SSL_NO_VERIFY=0` setting and the trackers once again can't be reached. Restarting Transmission seems to temporarily fix things, but after a few hours/days it reverts back.

Any other ideas?

Ideally the SSL cert verification would be a checkbox within Transmission's settings so that it can be set and retained within Transmission itself, no?

**Comment by esabol** [comment] 2022-04-13 22:06
> Any other ideas?

Have you tried the steps listed in **[this comment](https://github.com/transmission/transmission/issues/1876#issuecomment-1030591670)**?

> Ideally the SSL cert verification would be a checkbox within Transmission's settings so that it can be set and retained within Transmission itself, no?

I agree that it would be a nice option to have more accessible.

**Comment by briantully** [comment] 2022-04-14 04:36
> 

Thanks. Yes I looked at that comment last week, and even though I am using Mojave 10.14.6, I am not having an issue using curl to connect to letsencrypt.org when using the commands listed above.

I have the same cert.pem from Mar 21 2019:

```
ls -la /etc/ssl/cert.pem
-rw-r--r--  1 root  wheel   192K Mar 21  2019 /etc/ssl/cert.pem
```
And when running curl, it tells me that the cert is verified and expires on July 7, 2022 (almost 3 months from now):

```
curl https://www.letsencrypt.org -v

*   Trying 34.194.149.67:443...
* Connected to www.letsencrypt.org (34.194.149.67) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=lencr.org
*  start date: Apr  8 03:00:43 2022 GMT
*  expire date: Jul  7 03:00:42 2022 GMT
*  subjectAltName: host "www.letsencrypt.org" matched cert's "www.letsencrypt.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
```

**Comment by esabol** [comment] 2022-04-14 04:55
> I have the same cert.pem from Mar 21 2019:

Well, regardless, I recommend that you try to update it using **[these instructions](https://github.com/transmission/transmission/issues/1876#issuecomment-946781217)**.

**Comment by briantully** [comment] 2022-04-14 04:58
> > I have the same cert.pem from Mar 21 2019:
> 
> Well, that's still kind of old. Regardless, I recommend that you try to update it using **[these instructions](https://github.com/transmission/transmission/issues/1876#issuecomment-946781217)**.

Yup, I just did that a few minutes ago. Now it's time to wait and see. Thanks for all your help, Ed! 🍻 😄

**Comment by tabanger** [comment] 2022-04-14 05:19
> Thanks. Yes I looked at that comment last week, and even though I am using Mojave 10.14.6, I am not having an issue using curl to connect to letsencrypt.org when using the commands listed above.

So, the issue is that in your testing, you're not actually using your system curl.  You have a third-party, updated version of curl installed on your system.  I know that because your verbose output shows curl making TLS 1.3 and HTTP/2 connections, which are not supported by the Mojave default version of curl.  So, in your testing, you're not getting an accurate picture of your system curl's behavior.  Your third-party curl is probably not using the system default cert.pem (although It did not show the "CAfile" location it was using in your output; you can probably show it by increasing the verbosity (use `-vvv`)).  But, you can test the system curl (instead of your third-party curl) by invoking it specifically by typing `/usr/bin/curl` instead of just `curl`.

In any case, Transmission does not use curl, it uses libcurl.  And the system libcurl is still using the system default cert.pem, which you had not updated, so you were still subject to the issues outlined earlier in this ticket.  Now that you've updated the cert.pem, you should see your HTTPS connections start working.

**Comment by briantully** [comment] 2022-04-14 05:44
> > Thanks. Yes I looked at that comment last week, and even though I am using Mojave 10.14.6, I am not having an issue using curl to connect to letsencrypt.org when using the commands listed above.
> 
> So, the issue is that in your testing, you're not actually using your system curl. You have a third-party, updated version of curl installed on your system. I know that because your verbose output shows curl making TLS 1.3 and HTTP/2 connections, which are not supported by the Mojave default version of curl. So, in your testing, you're not getting an accurate picture of your system curl's behavior. Your third-party curl is probably not using the system default cert.pem (although It did not show the "CAfile" location it was using in your output; you can probably show it by increasing the verbosity (use `-vvv`)). But, you can test the system curl (instead of your third-party curl) by invoking it specifically by typing `/usr/bin/curl` instead of just `curl`.
> 
> In any case, Transmission does not use curl, it uses libcurl. And the system libcurl is still using the system default cert.pem, which you had not updated, so you were still subject to the issues outlined earlier in this ticket. Now that you've updated the cert.pem, you should see your HTTPS connections start working.

Thank you for your expert sleuthing and your detailed and clear explanation, @tabanger ! You are 100% correct in that I am using an updated curl via Homebrew (and I actually meant to mention that in my previous comment). Thanks again for figuring this all out and guiding the path forward! 🍻 😃

**Comment by tearfur** [comment] 2024-03-26 08:43
So am I correct to assume this is related to Mojave's curl library version, and not Transmision? I'm closing this for now, please correct me if I'm wrong.

**Closed by tearfur** 2024-03-26 08:43 UTC
Labels: duplicate, help wanted, pr welcome

**Comment by nevack** [comment] 2024-03-26 11:14
> So am I correct to assume this is related to Mojave's curl library version, and not Transmision? I'm closing this for now, please correct me if I'm wrong.

I think so, and the fix is system wide for any software relying on system's `libcurl`.
