### ISSUE TITLE
macOS crash when pausing active torrent

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4330] opened 2022-12-06 14:24 UTC
### What is the issue?

Pausing a seeding torrent will crash the client.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0-beta.2.dev (40c7f5bceb)

**Comment by ckerr** [comment] 2022-12-06 20:12
Closing as a duplicate of https://github.com/transmission/transmission/issues/4329

**Closed by ckerr** 2022-12-06 20:12 UTC
