### ISSUE TITLE
Crash on "Move Data File To..."

### ISSUE THREAD

**Issue by fedorpashin** [transmission/transmission#1225] opened 2020-05-12 05:39 UTC
After moving a torrent data to another directory and choosing it with "Move Data File To..." button, the client crashes.

**Comment by ckerr** [comment] 2020-05-15 17:23
I'm not able to reproduce this crash. Can you provide a crash report / backtrace / platform & version info?

**Comment by timkaarsemaker** [comment] 2020-05-18 12:05
On my client (MacOS) it seems to crash (beachballing) but the app just freezes until it completes the moving of the data file(s). After this is finished it resumes to work just as normal.

**Comment by Yohmi** [comment] 2020-05-25 09:46
I suppose this is related to this : https://github.com/transmission/transmission/issues/108
The behaviour timkaarsemaker is referring to, beachball, and if the file is big, it can take up to several minutes, so you feel the app is frozen (as it says "not responding" in activity monitor).

**Comment by ckerr** [comment] 2022-01-19 16:53
OK. Closing this as a dupe of the other please-make-transmission-disk-io-nonblocking issues. Thanks for the clarification.

**Closed by ckerr** 2022-01-19 16:53 UTC
Labels: needs clarification
