### ISSUE TITLE
Wave behaviour

### ISSUE THREAD

**Issue by ElDavoo** [transmission/transmission#1540] opened 2020-11-27 12:28 UTC
On multiple transmission versions and on multiple situations (download only, dl/up, seed only) i've observed a "wave" behaviour, where the speed goes up and down instead of being constant. Does anyone have a clue about it?
Right now i'm downloading some torrents from a biglybt instance that shows me this graph
![image](https://user-images.githubusercontent.com/7345120/100449479-497b5c80-30b4-11eb-912d-278f468a96ef.png)

**Comment by Adam-Kadmon** [comment] 2021-09-12 13:43
I'm getting the same behaviour, plus the torrents are downloading painfully slow. It also seems to be slowing down my whole connection when active. I've tried all the relevant settings (speed and connection limits)

**Comment by ElDavoo** [comment] 2021-09-12 15:03
I guess it has something to do with writing the blocks to disk? Downloading is not impacted for me so I just let it run, I was just curious about why this happens

**Comment by ckerr** [comment] 2022-01-19 23:04
Closing as a dupe of https://github.com/transmission/transmission/issues/2462. I realize this ticket was filed before 2462, but there are so many overlapping tickets at this point that it makes sense to start with a new "big picture" ticket.

**Closed by ckerr** 2022-01-19 23:04 UTC
