### ISSUE TITLE
All trackers fail

### ISSUE THREAD

**Issue by fxcoudert** [transmission/transmission#2546] opened 2022-01-31 10:54 UTC
Recently, using Transmission nightly on macOS 12.2 with magnet links, I systematically see all trackers failing:

<img width="613" alt="Capture d’écran 2022-01-31 à 11 53 14" src="https://user-images.githubusercontent.com/1980544/151781237-542bcbde-0f19-4b7b-8642-4079d4924e1f.png">

Sometimes it seems Transmission still manages to get information about peers from DHT (do I understand it right?), but sometimes it doesn't and even for relatively "popular" torrents, it will simply never find peers.

How can I debug these "connection failed" messages and know what the problem is? I'm willing to debug the issue but I don't really know where to start.

**Comment by GScottElshaw** [comment] 2022-01-31 11:00
I haven't seen that here on 11.6.3; what happens when you manually update the trackers?

**Comment by fxcoudert** [comment] 2022-01-31 11:04
Not sure what you mean by "manually update the trackers". I clicked "Transfer > Update from tracker" (backtranslated from French, I hope it matches the native English menu) and it gives more:

> 2022-01-31 11:03:06 +0000 announcer.cc:912 [Info] XXXXXXXXXX: Tracker '9.rarbg.to:2710' announce error: Connection failed (Retrying in 1830 seconds)

**Comment by GScottElshaw** [comment] 2022-01-31 11:07
I've found that particular tracker to be problematic, but 2730 to be fine. Yes, Transfer -> Update Tracker is correct. Nothing new installed?

**Comment by fxcoudert** [comment] 2022-01-31 11:16
Here this one fails as well.

<img width="610" alt="Capture d’écran 2022-01-31 à 12 11 01" src="https://user-images.githubusercontent.com/1980544/151783746-0beca121-9df1-41fa-988d-99fbb1d1e06b.png">

I don't think it's a local network issue:

```
$ nc -vz -u 9.rarbg.to 2710
Connection to 9.rarbg.to port 2710 [udp/sso-service] succeeded!
$ nc -vz -u 9.rarbg.to 2730
Connection to 9.rarbg.to port 2730 [udp/nec-raidplus] succeeded!
```

**Comment by Coding4Coffee** [comment] 2022-01-31 14:53
I'm on the latest nightly (b7235ed425)  on 12.2 and have no tracker issues with magnet links.

**Comment by fxcoudert** [comment] 2022-01-31 14:59
I think the main question I have is:

> How can I debug these "connection failed" messages and know what the problem is?

I've seen this issue with several builds, from several different networks, and I can reach the trackers outside of Transmission. I'd like to debug the issue further, but don't know how.

**Comment by Coding4Coffee** [comment] 2022-01-31 15:37
You could try using [Wireshark](https://www.wireshark.org) to inspect the connections going out.

**Comment by ckerr** [comment] 2022-01-31 15:58
> How can I debug these "connection failed" messages and know what the problem is? I'm willing to debug the issue but I don't really know where to start.

If you run Transmission with the `TR_CURL_VERBOSE` environment variable set to 1, http/https tracker requests and responses will be logged to the console. This can be really valuable when trying to figure out who Transmission is trying to talk to and what their response is.

**Comment by fxcoudert** [comment] 2022-01-31 17:06
I get tons of these messages:

```
2022-01-31 18:00:44.853 Transmission[75349:1271729] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-01-31 18:00:44.853 Transmission[75349:1271729] nil host used in call to allowsAnyHTTPSCertificateForHost:
```

Then I'm getting a specific error for one tracker:

```
* Hostname p4p.arenabg.com was found in DNS cache
*   Trying 185.230.4.150:1337...
* connect to 185.230.4.150 port 1337 failed: Connection refused
* Failed to connect to p4p.arenabg.com port 1337: Connection refused
* Closing connection 1
* Hostname p4p.arenabg.com was found in DNS cache
*   Trying 185.230.4.150:1337...
* connect to 185.230.4.150 port 1337 failed: Connection refused
* Failed to connect to p4p.arenabg.com port 1337: Connection refused
* Closing connection 2
* Hostname p4p.arenabg.com was found in DNS cache
*   Trying 185.230.4.150:1337...
* connect to 185.230.4.150 port 1337 failed: Connection refused
* Failed to connect to p4p.arenabg.com port 1337: Connection refused
* Closing connection 3
2022-01-31 18:01:15.872 Transmission[75349:1272249] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-01-31 18:01:15.872 Transmission[75349:1272249] nil host used in call to allowsAnyHTTPSCertificateForHost:
* Hostname in DNS cache was stale, zapped
*   Trying 185.230.4.150:1337...
* connect to 185.230.4.150 port 1337 failed: Connection refused
* Failed to connect to p4p.arenabg.com port 1337: Connection refused
* Closing connection 4
```

But it's always that one, the others are not giving any console error. Also, from the command-line, it seems to work:

```
⌁ [fx:~/Sites/fxcoudert.github.io] [base] master* 1 ± nc -vz -u 185.230.4.150 1337
Connection to 185.230.4.150 port 1337 [udp/menandmice-dns] succeeded!
```

**Comment by ckerr** [comment] 2022-01-31 17:53
> * connect to 185.230.4.150 port 1337 failed: Connection refused

This sounds like just what it said, that the tracker is down?

**Comment by GScottElshaw** [comment] 2022-01-31 23:03
> I get tons of these messages:
> 
> ```
> 2022-01-31 18:00:44.853 Transmission[75349:1271729] nil host used in call to allowsSpecificHTTPSCertificateForHost
> 2022-01-31 18:00:44.853 Transmission[75349:1271729] nil host used in call to allowsAnyHTTPSCertificateForHost:
> ```

I'm wondering if this might be related? https://github.com/transmission/transmission/issues/1876

**Comment by fxcoudert** [comment] 2022-02-01 10:31
@ckerr netcat seems to be able to connect, though

**Comment by Tockman** [comment] 2022-02-04 23:50
@GScottElshaw 
> I'm wondering if this might be related? #1876
I suppose, "could not connect to tracker" and "connection failed" are different types of error.

**Comment by GScottElshaw** [comment] 2022-02-05 00:02
> I suppose, "could not connect to tracker" and "connection failed" are different types of error.

True that.

**Comment by tabanger** [comment] 2022-02-05 10:13
> @ckerr netcat seems to be able to connect, though

You're using UDP on netcat.  The error message you posted for p4p.arenabg.com appears to indicate an attempted HTTP/HTTPS connection.

**Comment by pbsds** [comment] 2022-03-03 19:41
I experienced this in a fresh install of FreeBSD, tried to update my certs, but didn't work. Disabling encryption did.

**Comment by ckerr** [comment] 2022-06-14 15:25
Closing as a duplicate of #3285

**Closed by ckerr** 2022-06-14 15:25 UTC
