### ISSUE TITLE
[FEAT] Transmission Interface Binder (or something similar)

### ISSUE THREAD

**Issue by pa-0** [transmission/transmission#7337] opened 2024-12-27 00:49 UTC
### What is the issue?

For the better part of a decade, I used [this tool](https://github.com/pa-0/Transmission-Interface-Binder) because it worked reliably and was incredibly easily to set up.  If my vpn disconnected for whatever reason, all active connections in Transmission would automatically cease.  

If I had the know-how, I would update the utility to work with the latest version of Transmission. Unfortunately I do not.  At any rate, I think having something akin to this as a feature of Transmission would be incredibly useful to many users. 

### Which application of Transmission?

macOS app

### Which version of Transmission?

latest

**Comment by tearfur** [comment] 2024-12-27 04:12
Duplicate of #338

**Closed by tearfur** 2024-12-27 04:12 UTC
Labels: duplicate
