### ISSUE TITLE
Max peers per torrent option ignored

### ISSUE THREAD

**Issue by slicer69** [transmission/transmission#314] opened 2017-06-22 15:27 UTC
Transmission version: 2.92 (daemon)
Platform: FreeBSD 11.0

Issue: When setting the "max peers per torrent" variable in the Transmission daemon's web interface, the value is ignored. The "max peers overall" variable is respected.

For example, if I set the "max peers overall" value to 10 and the "max peers per torrent" value to 5, then the first torrent I start will download from 10 peers and the second torrent will have 0 peers. The first torrent should be limited to just five peers, leaving another 5 for additional torrents to use.

Workaround: None so far.

**Comment by Astara** [comment] 2017-07-12 10:04
The max peers per torrent value is a limit on number of connections -- not the list of peers.    I.e. when you see numbers for seeds and peers it will say something like xx/yy.  The 1st number is actual connections, the 2nd number is number of peers (or seeds).  

When I have 20 peers/torrent setup, I'll notice about half of those (~10)  used for download traffic (seeds) and the other half for upload traffic (peers).  I've never seen a case where the limits were ignored.  

A possible condition -- example if you have 100KB of download b/w, and you set max peers to '5', and each of those 5 use 20KB download each,  transmission won't try to open another 5 connections to another torrent, because all its bandwidth is being used.

In addition to limiting # of clients, you may need to limit total bandwidth for each of your torrents in order to get things spread out -- though it will likely be less efficient doing it that way.

**Comment by bagobones** [comment] 2021-01-06 23:29
Confirmed still doesn't work in 3.00.

**Comment by Astara** [comment] 2021-01-07 02:51
On 2021/01/06 15:29, bagobones wrote:
>
> Confirmed still doesn't work in 3.00.
>
---
I think it is working but that how it works may be confusing
to some.

It sets the max clients at the number specified, which I *think* may
still be limited by the global-max clients (so if that is low, you may
not get the max/torrent you want -- not sure about this but saying
to make sure the global setting is 'high' enough to accommodate your
single-torrent limits. 

Then I see # peers on up OR down (whichever is saturated at the time)
at ONE-HALF the number I put in.  With the other half being reserved
for the other direction.  So when I am receiving a torrent, I might see
up to 13-15 active senders when I allow 30 peers/torrent.  I rarely see
more than a few active on most of my torrents because most are old
stuff/infrequently asked for.

So, if you are seeing within 10% of 50% of your max-peer/torrent setting,
I'd say it is working as expected.

How are you determining that it isn't working?

**Comment by bagobones** [comment] 2021-01-07 04:16
https://cdimage.debian.org/debian-cd/current/amd64/bt-dvd/

First ISO has 542 seeds

"download-queue-size": 6,
"peer-limit-global": 200,
"peer-limit-per-torrent": 30

Restarted to be SURE that those where the values used and confirmed in the web UI.

Got up to 82/542 peers before it was complete.

Scrolled through the peer list no upload, all peers where me downloading from them.

That is close the 3x the limit set.

**Comment by Astara** [comment] 2021-01-07 05:35
On 2021/01/06 20:16, bagobones wrote:
>
> https://cdimage.debian.org/debian-cd/current/amd64/bt-dvd/
>
> First ISO has 542 seeds
>
> "download-queue-size": 6,
> "peer-limit-global": 200,
> "peer-limit-per-torrent": 30
>
> Restarted to be SURE that those where the values used and confirmed in 
> the web UI.
>
> Got up to 82/542 peers before it was complete.
>
----
    I just tried the above, jumped to 82 on first update (had 90 
allowed). 768global
download-queue-size isn't related, I don't think.  (number of different
torrents that can download simultaneously).

Cut that to 30, and next update it dropped to the 1st 30 peers/548.

    So it is working for me.  Now to figure out what is different.
Maybe I have lower limits for some things that cause more
frequent updating?

    I just use the daemon, headless on linux + xmission-client on windows.

Did you self compile yours?  I have a few local patches, but
nothing that should affect traffic.
Here is my config (mostly).



{
    "alt-speed-down": 1024,
    "alt-speed-enabled": true,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 128,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": true,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 1024,
    "dht-enabled": true,
    "download-dir": "/Media",
    "download-queue-enabled": false,
    "download-queue-size": 2,
    "encryption": 0,
    "idle-seeding-limit": 43200,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/home/tran/",
    "incomplete-dir-enabled": true,
    "lazy-bitfield-enabled": false,
    "lpd-enabled": true,
    "message-level": 2,
    "open-file-limit": 16384,
    "peer-congestion-algorithm": "lp",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 768,
    "peer-limit-per-torrent": 96,
    "peer-port": 0000,
    "peer-port-random-high": 00000,
    "peer-port-random-low": 00000,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "pidfile": "/run/tran-d.pid",
    "port-forwarding-enabled": false,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 1501,
    "ratio-limit": 7.1999,
    "ratio-limit-enabled": false,
    "rename-partial-files": true,
    "rpc-authentication-required": false,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "mysys",
    "rpc-host-whitelist-enabled": true,
    "rpc-password": "",
    "rpc-port": 0000,
    "rpc-url": "/tran/",
    "rpc-username": "",
    "rpc-whitelist": "127.0.0.1,192.168.127.*",
    "rpc-whitelist-enabled": true,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 40,
    "speed-limit-down": 3076,
    "speed-limit-down-enabled": true,
    "speed-limit-up": 768,
    "speed-limit-up-enabled": true,
    "start-added-torrents": false,
    "trash-original-torrent-files": false,
    "umask": 0,
    "upload-slots-per-torrent": 24,
    "utp-enabled": true,
    "watch-dir-enabled": false
}

**Comment by ckerr** [comment] 2022-02-15 16:30
I'm closing this issue based on the previous comment. If this is still a problem, please open a new issue with updated information. Thank you!

**Closed by ckerr** 2022-02-15 16:30 UTC
Labels: needs clarification
