### ISSUE TITLE
Torrents stop as soon as they would start

### ISSUE THREAD

**Issue by thany** [transmission/transmission#4875] opened 2023-02-13 20:45 UTC
### What is the issue?

When a torrent is added, it goes into "downloading" state where it's catching up with the trackers. Then, as soon as it would recieve the first byte (or so it seems), it is kicked into "paused" state. There is no error shown.

The "Start when added" checkbox is ticked in the web UI.

Since my torrents are initially in "downloading" state, it seems to be almost the reverse of #4873. Not quite the reverse, which is why I decided to create a separate issue, as the root cause might be a different one.

Edit: after a cursory test, it seems the checkbox mentioned doesn't do anything. Unticking it makes it behave exactly the same.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.0 280ace12f8

**Comment by sweetppro** [comment] 2023-02-13 20:51
Have you tried the latest nightly?

**Comment by thany** [comment] 2023-02-13 20:54
No I haven't. I've got it installed as a docker in unraid, and I don't quite know how to update it to a version that isn't provided there. I should probably figure this out.

In the mean time: are you saying it is definitely solved in the latest nightly, or you just want me to try to see if it might be solved by accident?

**Comment by sweetppro** [comment] 2023-02-13 21:03
A pull request was just merged which may fix your problem #4856

**Comment by ckerr** [comment] 2023-02-13 21:08
@thany thanks for reporting this!

I think this is a duplicate of #4740 so I'm going to close this one as a dupe.

**Closed by ckerr** 2023-02-13 21:08 UTC
