### ISSUE TITLE
nightly macOS builds are unsigned, causing repeated permission prompts

### ISSUE THREAD

**Issue by chaseholden** [transmission/transmission#3680] opened 2022-08-20 00:46 UTC
Transmission 3.00+ (aac1ab784d) on Mac Studio M1 Ultra macOS 12.5.1 Monterey

Considering that Monterey is all about Privacy, your testing procedure should always include testing torrents running on removable media drives. 

Were you to test this, you'd know that for every single version for at least the 2 weeks that I've been testing each of these betas, there is a constant and never ending stream of Privacy Permission Prompts asking to access files on Removable drives. 

Over 50 prompts within the first minute alone, despite the fact that I am only using 5 removable drives. I believe this means that every single individual active torrent requires its own separate permission prompt to access the removable drives, and macOS Privacy Settings are completely ignored. 

Prompt: “Transmission” would like to access files on a removable volume."

This happens even when Transmission already has Full Disk Access in macOS Monterey 12.5.1 Privacy

Here's a screen capture video so you can see the madness: https://www.dropbox.com/s/jcbqq1klalp2lp3/Constant-Prompts-Privacy-Permission-Removable-Volume.mp4

<img width="703" alt="Prompts ∞" src="https://user-images.githubusercontent.com/19694741/185722625-a282eb0b-0d4e-4a15-8b34-69e4ec3e0fbd.png">

**Comment by chaseholden** [comment] 2022-08-20 23:12
Redundant Prompts eliminated successfully after I updated to build 785119f2c2

However, it still seems both unexpected and tad frustrating user must approve access to the same 5-6 "access removable volume" prompts: 

1. because I explicitly gave Transmission "Full Disk Access" in macOS Security & Privacy Settings; and
2. because I already gave permission each and every time I relaunch Transmission to the same drives.

So far, Apps requiring removable volume access simply prompt the user upon first launch for permission to Add the Privacy Rule in macOS Settings, and then remember that from that point on, never asking for permission again. 

For example: "Carbon Copy Cloner.app" which I use exclusively uses removable drives and even runs automatically on a schedule in the background and would not work at all if it required manual approval for permission on every operation. 

It would be great if Transmission would similarly ask user for permission to create the ongoing rule allowing it Full Disk Access permission to suppress future removable volume access prompts. :) 

Incidentally, an unrelated bug was solved with these past couple updates which generated Crash Report windows even after manually quitting Transmission normally.

**Comment by chaseholden** [comment] 2022-08-23 00:47
Please REOPEN as this bug is back. Constant, infinite access removable prompts again.

And please see previous comment if you haven't already.

**Comment by chaseholden** [comment] 2022-08-23 01:23
Closing again. Apparently, even though Transmission is already added to macOS Privacy Full Disk Access panel, each new update must be manually re-added to that panel all over again including every beta.

**Comment by chaseholden** [comment] 2022-10-18 02:42
This is a problem again in #8383 build c8e652c820 
There are 50, yes 50 access prompts! Please fix this again.

**Comment by GaryElshaw** [comment] 2022-10-18 07:23
In my experience this is almost always to do with the security and privacy module itself. It's not necessarily a bug, but a feature. If you navigate to disk access in the panel, make sure Transmission has 'full disk access'.

**Comment by chaseholden** [comment] 2022-10-18 19:01
> It's not necessarily a bug, but a feature. If you navigate to disk access in the panel, make sure Transmission has 'full disk access'.

@GaryElshaw Fifty (50) repeating prompts asking the exact same question fifty times in a row and the App is unusable until you approve every single one… and YOU Gary are calling that a "FEATURE!?" Preposterous. 
And I had already had Transmission added to Privacy with full disk access.

**Comment by mikedld** [comment] 2022-10-18 19:44
Just a thought, could this be related to nightly builds being unsigned? Did you try 4.0.0-beta.1 (released and thus signed binaries) to see if it would still behave this way? Transmission isn't doing anything specifically to ask or not ask for those permissions, that's the OS that filters disk access and does this transparently to the app so I'm not yet sure what we can do here.

Also, please keep your emotions in check ;) We're all trying to help each other here.

**Comment by nevack** [comment] 2022-10-18 20:56
Yup, this system prompts are happening to me only when I use not properly signed builds, like built by me without any DEVELOPMENT_TEAM set AND have some torrents  pointing to External Drive/Share.
No issues with public builds.

I think we can try to move any FS reads later, after UI is initialised, do not block it, just grey-out unaccessible paths, but is it worth it?

**Comment by chaseholden** [comment] 2022-10-18 21:08
> Just a thought, could this be related to nightly builds being unsigned? Did you try 4.0.0-beta.1 (released and thus signed binaries) to see if it would still behave this way? Transmission isn't doing anything specifically to ask or not ask for those permissions…

@mikedld & @nevack : The "About" window displays 4.0.0-beta.1.dev (c8e652c820) so I don't know if that indicates it's signed or not? 
So in that case, is there any way to know before or after downloading a build whether the build is signed or not? … and if so, how?

**Comment by mikedld** [comment] 2022-10-18 21:16
With recent versioning changes, `.dev` at the end of version points to a development (and thus unsigned) build. Basically, any build currently produced by TeamCity, Jenkins, or GitHub Actions, will be unsigned. Signed builds are those that we prepare semi-manually, and those are published on https://transmissionbt.com/ and as assets for GitHub releases (https://github.com/transmission/transmission/releases).

**Comment by chaseholden** [comment] 2022-10-19 02:49
> With recent versioning changes, `dev` at the end of version points to a development (and thus unsigned) build. Basically, any build currently produced by TeamCity, Jenkins, or GitHub Actions, will be unsigned. Signed builds are those that we prepare semi-manually, and those are published on https://transmissionbt.com/ and as assets for GitHub releases (https://github.com/transmission/transmission/releases).

Thank you @mikedld … that was really helpful. I'll keep an eye out for the signed non-dev versions from now on.

**Comment by chaseholden** [comment] 2022-12-23 00:22
Disappointingly, there have only been 2 actual signed beta versions of 4.0 so far, which means that we are stuck using the impossible Nightly Builds if we want any recent bug fixes at all, but I say "impossible" because of this ongoing problem of nearly infinite Permission Prompts. 

I don't understand how you Devs are all able to open Nightlies without all the prompts unless you are signing your own builds locally? 

I really want to help but I can't if signed versions aren't uploaded frequently, at least monthly, and I think I speak for many others and am unlikely a lone voice here.

**Comment by ckerr** [comment] 2022-12-24 00:31
Is #2171 the same issue?

**Comment by chaseholden** [comment] 2022-12-24 00:40
> Is #2171 the same issue?

Yes, @ckerr I believe it might be the same issue although mine is not related to repeated prompts for network access, only for removable volume access already granted.

**Comment by ckerr** [comment] 2023-01-27 04:19
Closing as duplicate of 2171 as per previous comment

**Closed by ckerr** 2023-01-27 04:19 UTC
Labels: needs clarification, scope:mac, pr welcome
