### ISSUE TITLE
Transmission rpc port temporarily freezes (with slow underlying FS)

### ISSUE THREAD

**Issue by zwimer** [transmission/transmission#6420] opened 2023-12-21 23:48 UTC
### What is the issue?

Occasionally, transmission-daemon's user-accessible-frontend (such as it's WebUI) will seemingly freeze. This is normally when the app is under some sort of heavy load. For example, moving 2000 torrents from `/downloads/A` to `/downloads/B` might cause this. It is not every time, just sometimes.

It is possible this might be because my FS hangs for a bit sometimes (like if SSHFS hangs for a bit). If WebUI (or rather the rpc port in general) is expected to freeze for a bit during this, feel free to close this issue!

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.5

**Comment by tearfur** [comment] 2023-12-22 01:14
Duplicate of #2462.

**Closed by tearfur** 2023-12-22 01:14 UTC
