### ISSUE TITLE
Ordering issue with Tr4.0.0 and later

### ISSUE THREAD

**Issue by Xake** [transmission/transmission#5323] opened 2023-03-29 12:37 UTC
### What is the issue?

Transmission-daemon 4.0.0 changed the order it lists torrents over RPC.
This is very visible with transmission-remote that takes torrents as they come in the list from the daemon, and lists it straight.

Version 3 send the torrent list in order of ID, and always seems to do this.
That means that old torrents are high up, and new torrents are in the end of the output from transmission-remote.

Since version 4 of the daemon this is not true anymore:
<pre>
$ transmission-remote -l | head
    ID   Done       Have  ETA           Up    Down  Ratio  Status       Name
   142   100%   457.7 GB  Unknown      0.0     0.0   1.28  Idle         <REMOVED>
   153   100%    4.12 GB  Unknown      0.0     0.0   2.15  Idle         <REMOVED>
   188   100%    9.74 GB  Unknown      0.0     0.0   1.24  Idle         <REMOVED>
   171   100%   938.9 MB  Unknown      0.0     0.0   0.33  Idle         <REMOVED>
     1   100%    4.21 GB  Unknown      0.0     0.0    5.3  Idle         <REMOVED>
   169   100%    1.54 GB  Unknown      0.0     0.0   0.74  Idle         <REMOVED>
     2   100%    5.71 GB  Unknown      0.0     0.0    6.6  Idle         <REMOVED>
    25   100%    5.54 GB  Unknown      0.0     0.0    9.4  Idle         <REMOVED>
   139   100%   448.9 GB  Unknown      0.0     0.0   2.34  Idle         <REMOVED>
</pre>

This is unrelated to which version of of transmission-remote I am using, and I have confirmed with --debug that only changing between versions om the daemon does change the order that it gets over RPC.
Also newly added torrents ends up in what at a quick glance looks like a random placement in the list.

I have not fully 100% confirmed this, but when I have tried to dig into this it seems like transmission-daemon-4.0.0 and newer lists the torrents in the order the files in the "resume" directory is alphabetically listed.  I have no good way to confirm as I have no good way to parse the torrent name out from the resume-files, but using "cat" on them and looking at what is outputed the last five torrents listed (also out of order wrt IDs) are an exact match to the last 5 files in the resume directory.

Could you please change transmission-daemon back to over RPC send the list of torrents in order of ID?

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

Verified with transmission-daemon and remote 3.0, 4.0.0 and 4.0.2 with both different and same versions of remote interacting with the daemon

**Comment by snarl817** [comment] 2023-04-12 14:15
Tangentially related: When the daemon starts up, it reorders the torrents in alphabetical order by hash ID. It would be REALLY nice if the daemon would instead order the torrents based on date added, oldest to newest.

And what's up with transmission-remote NOT giving any ability to sort torrents? As someone who almost EXCLUSIVELY uses the command line, a filter/sort interface to the client would be REALLY nice.

**Comment by killemov** [comment] 2023-06-30 07:06
> Tangentially related: When the daemon starts up, it reorders the torrents in alphabetical order by hash ID. It would be REALLY nice if the daemon would instead order the torrents based on date added, oldest to newest.

I always figured it was either random or by node order on disk, but this also makes sense. Logically the id's cant change within a session, but I have an option in [Shift](https://github.com/killemov/Shift) to at least reorder the queue by date added.

**Comment by tearfur** [comment] 2023-07-14 17:19
Closing as a duplicate of #5551.

**Closed by tearfur** 2023-07-14 17:19 UTC
Labels: scope:daemon
