### ISSUE TITLE
Feature Request: Add option to always minimize to notification icon only (Windows)

### ISSUE THREAD

**Issue by ghost** [transmission/transmission#604] opened 2018-05-03 11:49 UTC
Right now, Transmission for Windows only minimizes to both the taskbar and notification icon. There is an option in the notification icon to close the main window and taskbar icon but you have to click it each time the main window is reopened. Can we have a setting to always minimize Transmission to the notification icon only?

**Comment by ckerr** [comment] 2022-02-10 16:27
Closing this issue as a duplicate of #36

**Closed by ckerr** 2022-02-10 16:27 UTC
Labels: enhancement, scope:qt, pr welcome
