### ISSUE TITLE
port-test only tests IPv4

### ISSUE THREAD

**Issue by slokhorst** [transmission/transmission#381] opened 2017-08-24 09:19 UTC
The port-test function (which sends a request to https://portcheck.transmissionbt.com/), is IPv4-only. On dual-stack or IPv6-only hosts, this gives confusing results.

It would be great if port-test and portcheck.transmissionbt.com would be made IPv6-capable, so it could test both protocols and report both results (e.g. "IPv4: open, IPv6: open").

I'm not sure how portcheck.transmissionbt.com is implemented, but it is likely trivial to make it IPv6 capable. (maybe just add an AAAA record at portcheck6.transmissionbt.com or something)

From the client side this would be easy too (send an extra request to portcheck6.transmissionbt.com and report both results). I would be willing to do this myself.

**Comment by JohnClay** [comment] 2017-08-27 20:45
I *think* the service is v6 capable, but the DNS record got left out during a migration.

I've added a v6 record - can you test and report back?

**Comment by slokhorst** [comment] 2017-08-27 23:19
Thanks for the response. I can now connect to the server, but get a `400 Bad Request` response when using IPv6.

IPv4:
```
$ curl -v -4 https://portcheck.transmissionbt.com/80

> GET /80 HTTP/1.1
> Host: portcheck.transmissionbt.com
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.10.3 (Ubuntu)
< Date: Sun, 27 Aug 2017 23:17:13 GMT
< Content-Type: text/html; charset=ISO-8859-1
< Transfer-Encoding: chunked
< Connection: keep-alive
```

IPv6:
```
$ curl -v -6 https://portcheck.transmissionbt.com/80

> GET /80 HTTP/1.1
> Host: portcheck.transmissionbt.com
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Server: nginx/1.10.3 (Ubuntu)
< Date: Sun, 27 Aug 2017 23:15:18 GMT
< Content-Type: text/html; charset=ISO-8859-1
< Transfer-Encoding: chunked
< Connection: keep-alive
```

**Comment by mlpo** [comment] 2017-10-24 12:40
Exactly same problem here.

IPv4:
```
$ curl -v -4 http://portcheck.transmissionbt.com/80
*   Trying 87.98.162.88...
* TCP_NODELAY set
* Connected to portcheck.transmissionbt.com (87.98.162.88) port 80 (#0)
> GET /80 HTTP/1.1
> Host: portcheck.transmissionbt.com
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.10.3 (Ubuntu)
< Date: Tue, 24 Oct 2017 12:38:59 GMT
< Content-Type: text/html; charset=ISO-8859-1
< Transfer-Encoding: chunked
< Connection: keep-alive
<
* Curl_http_done: called premature == 0
* Connection #0 to host portcheck.transmissionbt.com left intact
1
```

IPv6:
```
$ curl -v -6 http://portcheck.transmissionbt.com/80
*   Trying 2001:41d0:c:5ac:5::1...
* TCP_NODELAY set
* Connected to portcheck.transmissionbt.com (2001:41d0:c:5ac:5::1) port 80 (#0)
> GET /80 HTTP/1.1
> Host: portcheck.transmissionbt.com
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Server: nginx/1.10.3 (Ubuntu)
< Date: Tue, 24 Oct 2017 12:38:54 GMT
< Content-Type: text/html; charset=ISO-8859-1
< Transfer-Encoding: chunked
< Connection: keep-alive
<
* Curl_http_done: called premature == 0
* Connection #0 to host portcheck.transmissionbt.com left intact
```

**Comment by slokhorst** [comment] 2018-02-27 11:53
@JohnClay Is there anything we can do to help here? Is the portcheck.transmissionbt.com code public?

**Comment by slokhorst** [comment] 2020-05-22 19:33
Bump..

`curl -v 6 http://portcheck.transmissionbt.com/80` is still responding with `HTTP/1.1 400 Bad Request`.

**Comment by wereii** [comment] 2021-09-15 20:24
Bump?

**Comment by txVLN** [comment] 2021-12-19 04:07
Looks like there's several copies of this issue. Here's the one with the most activity: https://github.com/transmission/transmission/issues/407

**Comment by user00265** [comment] 2022-02-25 02:48
With the world going IPv6 alongside IPv4 for years now, and the first report being back in 2017... what needs to be done to solve this? If help is needed with code, where is it? This is awfully sad that a lot of people and companies treat IPv6 as a second class citizen because "IPv4 is the majority" -- please don't be one of those. We're willing to help!

**Comment by user00265** [comment] 2022-02-25 03:05
@ckerr I am assuming the issue is with portcheck web service and not with transmission itself. Where would the code for that reside? I saw some mention of portcheck on the old websites repo, but I am assuming that is not current... please correct me if I am wrong?

**Comment by Oleg-Chashko** [comment] 2022-06-12 16:25
Maybe someone has information whether this bug (Port check site is down) will be fixed in version 4.00.

**Comment by user00265** [comment] 2022-07-30 02:13
Well, as a temporary measure I have created my own imitating the true/false replies from the real one and overrode portcheck.transmissionbt.com to point to my own web server where the portcheck I have resides.

**Comment by axet** [comment] 2022-08-07 07:19
ipv6 and ipv4 checks should be done separately. ipv6 can be booth public global ip or nat.

transmission should check ipv4 mapping separately from ipv6 mappings.

if ipv6 behind nat, then upnp should be used to map ipv6 ports.

**Comment by rwkjones** [comment] 2022-11-24 10:15
I had to write my own rpz zone file for bind to not return an IPv6 address for this, very annoying. Here's a snippet of the config for anyone who wants to do similar:

```
named.conf:
options {
   response-policy {
      zone "rpz-transmission";
   };

zone "rpz-transmission" { type master; file "/etc/bind/rpz-transmission.db; };

```
/etc/bind/rpz-transmission.db:

```
$TTL 2w
@ IN SOA localhost. root.localhost. (
       2   ; 1667842442
       2w  ; refresh 
       2w  ; retry 
       2w  ; expiry 
       2w) ; minimum 
    IN NS localhost.
      
vm4.transmissionbt.com A 87.98.162.88
;vm4.transmissionbt.com AAAA ::1
portcheck.transmissionbt.com A 87.98.162.88
;portcheck.transmissionbt.com AAAA ::1

```

**Comment by axet** [comment] 2022-11-24 16:43
For openwrt routers it can be done using:

**/etc/config/dhcp**
```
config domain
        option name 'portcheck.transmissionbt.com'
        option ip '::1'
```

**Comment by ckerr** [comment] 2023-01-17 16:34
This is the same issue as https://github.com/transmission/transmission/issues/3102. Usually the newer issue should be closed as a duplicate, but since 3102 has more details and discussion I'm going to close this one instead.

**Closed by ckerr** 2023-01-17 16:34 UTC
Labels: enhancement, pr welcome
