### ISSUE TITLE
downloads stuck at 99% when torrent piece size isn't cleanly divisible by 2^14

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3111] opened 2022-05-19 03:06 UTC
A variation on a theme? - #820 #3107 

The behaviour seems consistent across downloads that exceed 1.2GB, and especially if there is a large swarm w/ multiple peers. The download reaches around 98 - 99%, and every connected peer's uploading suddenly drops to 0.0.

Assuming there's a corruption issue, i verify local data and Transmission doesn't indicate anything is wrong with the file(s), and reconnecting, resumes, and with the same 0.0 connection speed or around  1 -2k/s.

At this point i usually quit the nightly and open 3.0 release and re-verify. Sure enough, 3.0 will either correctly verify and resume, or sometimes, depending on how bad the corruption is, i'll start the download again fresh in 3.0.

**Comment by ckerr** [comment] 2022-05-20 04:45
I think I'm not reading this correctly. Is this separate from 3107? If so, how?

**Comment by GaryElshaw** [comment] 2022-05-20 04:50
> I think I'm not reading this correctly. Is this separate from 3107? If so, how?

There is no reversion in the percentage completed. 2gb is far less than 20gb. Resuming the torrent does not complete the download (peers signal 0.0 and disappear.

**Comment by fxcoudert** [comment] 2022-05-21 18:43
I'm seeing that too: many downloads exceed 99%, but then don't progress further. They still show active connexions, it sees peers, it's even saying it's downloading from those peers, but it's downloading at exactly 0,0 K (displayed):

<img width="208" alt="Capture d’écran 2022-05-21 à 20 39 28" src="https://user-images.githubusercontent.com/1980544/169665047-e72b4e70-fa05-45ba-87c6-f9e7f1a8e3b2.png">
 
In the logs, I see tons of:

```
[2001:8f8:1623:f46:e07e:2fff:9d66:2970]:54415: event_read_cb err: res:-1, what:33, errno:54 (Connection reset by peer)
xxxxxxxx.mkv: [2001:8f8:1623:f46:e07e:2fff:9d66:2970]:54415 [µTorrent 3.5.5]: libevent got an error! what=33, errno=54 (Connection reset by peer)
xxxxxxxx.mkv: setting [2001:8f8:1623:f46:e07e:2fff:9d66:2970]:53454 doPurge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error
xxxxxxxx.mkv: [2001:8f8:1623:f46:e07e:2fff:9d66:2970]:54415 [µTorrent 3.5.5]: libevent got an error! what=49, errno=0 (Undefined error: 0)
xxxxxxxx.mkv: setting [2001:8f8:1623:f46:e07e:2fff:9d66:2970]:53454 doPurge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error
xxxxxxxx.mkv: [2001:8f8:1623:f46:e07e:2fff:9d66:2970]:54415 [µTorrent 3.5.5]: libevent got an error! what=49, errno=0 (Undefined error: 0)
xxxxxxxx.mkv: setting [2001:8f8:1623:f46:e07e:2fff:9d66:2970]:53454 doPurge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error
yyyyyyyy: [2607:fa49:c33d:8c00:2064:2b40:2e9:9f2a]:51413 [Transmission 3.00]: libevent got an error! what=16, errno=35 (Resource temporarily unavailable)
yyyyyyyy: setting [2607:fa49:c33d:8c00:2064:2b40:2e9:9f2a]:51413 doPurge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error
[49.228.83.57]:41331: utp_on_error -- errcode is 54
[81.182.159.69]:36400: utp_on_error -- errcode is 54
```

**Comment by fxcoudert** [comment] 2022-05-31 14:37
@ckerr could you let us know what you need to debug this further?

**Comment by ckerr** [comment] 2022-06-04 15:18
> @ckerr could you let us know what you need to debug this further?

If you can link to a public domain torrent where this is happening so that I can test and reproduce the problem, that would help. I'm not seeing this issue in my own use.

**Comment by fxcoudert** [comment] 2022-06-04 16:40
> If you can link to a public domain torrent where this is happening

I don't have one right now, I've tried a couple of Linux distros, and I'm not seeing it. On the torrents I've used, it happens in 8 out of 10 roughly.

**Comment by robd003** [comment] 2022-06-06 02:29
I've had the issue repeatedly with ~180gb torrents that were created with transmission, seeded and then downloaded with transmission.

I'm using them to synchronize database backups so unfortunately I can't share the torrents. Seems to have occurred for builds after May 27th. I'm trying to find the date when this was still working.

**Comment by ckerr** [comment] 2022-06-06 14:59
@robd003 if you can narrow it down to a range of commits (or, obviously even better, a specific commit) that would be fantastic. I understand this is frustrating some people but haven't been able to reproduce the issue. Hoping to hear back from you on this :smile_cat:

**Comment by ckerr** [comment] 2022-06-13 02:19
I'm curious to know if the recent changes that landed to the block write cache in #3108 affect this issue. Can someone in-ticket try a nightly and report back whether or not this is still an issue?

**Comment by fxcoudert** [comment] 2022-06-13 07:05
A quick check at bf1d668f9afeec27e6dea2119f44e039faa08cbc seems to say the problem is still there (at least when resuming existing and blocked transfers).

**Comment by ckerr** [comment] 2022-06-17 18:36
This issue seems important and I'd like to move it forward, but I still haven't been able to reproduce it and don't have any leads. If there's a PD torrent I can test with, or if someone knows a range of commits that introduced this, I'd be happy for the help.

**Comment by fxcoudert** [comment] 2022-06-17 19:12
@ckerr is there a way we can increase log level, provide more data? I don't have a public domain torrent that reproduces this, but I am willing to provide detailed logs / run debug builds / etc.

**Comment by ckerr** [comment] 2022-06-18 02:37
Yeah, I agree it's frustrating.

If by some slim chance the issue is that the .torrent file you've got has some PII key that you don't want to share here, my email is firstname @ firstandlastname.com. I can do triage on public domain torrents and won't share PII.

**Comment by fxcoudert** [comment] 2022-06-18 08:41
Here is a magnet link that demonstrates the issue:

```
echo 'bWFnbmV0Oj94dD11cm46YnRpaDozODg5NzE2MUNDMUFDQUY5MzBCNUU5NjFCQjc3MzUyNThEMjA3MTU2JmRuPUJldHRlciUyMENhbGwlMjBTYXVsJTIwUzA2RTAxJTIwMTA4MHAlMjBXRUIlMjBIMjY0LUdMSEYmdHI9dWRwJTNBJTJGJTJGMTg1LjE5My4xMjUuMTM5JTNBNjk2OSUyRmFubm91bmNlJnRyPXVkcCUzQSUyRiUyRnRyYWNrZXIub3BlbnRyYWNrci5vcmclM0ExMzM3JnRyPXVkcCUzQSUyRiUyRnRyYWNrZXIub3BlbmJpdHRvcnJlbnQuY29tJTNBNjk2OSUyRmFubm91bmNlJnRyPXVkcCUzQSUyRiUyRm1vdmllcy56c3cuY2ElM0E2OTY5JTJGYW5ub3VuY2UmdHI9dWRwJTNBJTJGJTJGb3Blbi5zdGVhbHRoLnNpJTNBODAlMkZhbm5vdW5jZSZ0cj11ZHAlM0ElMkYlMkZ0cmFja2VyLjB4LnRmJTNBNjk2OSUyRmFubm91bmNlJnRyPXVkcCUzQSUyRiUyRm9wZW50cmFja2VyLmkycC5yb2NrcyUzQTY5NjklMkZhbm5vdW5jZSZ0cj11ZHAlM0ElMkYlMkY0Ny5pcC01MS02OC0xOTkuZXUlM0E2OTY5JTJGYW5ub3VuY2U' | base64 --decode
```

It downloaded fine for a while, then got stuck: it has active peers, but their net download is at 0 and all I see in the logs are error messages. The same magnet link, on the same machine, on the same network, downloads fine with other software. Also note that even during the time window when Transmission was downloading, it was showing a lot of error messages like those below.

----

So I get a better understanding where to go debugging, which of the hundreds of debug messages per minutes I get are “normal”, and which indicate an issue?

- In `peer-msgs.cc:2320`, `libevent got an error! what=17, errno=0 (Undefined error: 0)`
(values of `what` are not always the same)
- In `peer-mgr.cc:930`, `setting [x]:63985 doPurge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error`
- `peer-io.cc:309`, `event_read_cb err: res:0, what:17, errno:0 (Undefined error: 0)`
- `peer-io.cc:525`, `utp_on_error -- errcode is 60`
-

**Comment by ckerr** [comment] 2022-06-18 22:12
**Yuck** this is a pretty nasty one.

Some of the optimizations in the new code are based on assumptions  that fail when piece size isn't a power of two that's >= 2^14, so this is going to require some new plumbing.

Torrents that deviate from that are actually not allowed in BitTorrent 2.0 but still exist in 1.0. I need to make sure to add that to the test cases.

**Closed** 2022-06-20 04:08 UTC
Labels: bug, confirmed

**Comment by sweetppro** [comment] 2022-06-20 06:41
#3324 fixes this for me on macOS, Nice!

**Comment by GaryElshaw** [comment] 2022-07-04 15:45
Unfortunately i'm seeing this again :-( 3.00+ (849a36a30d)

Download can be anywhere between 30 - 80% complete, and the total file(s) size is between 1 - 2gb. Multiple peers drop, those that remain are 0.0kps and the file(s) are corrupted.

**Comment by GaryElshaw** [comment] 2022-08-09 02:29
I'm also seeing the low peers and slow upload speeds with 3.00+ (41c0f8885e)

**Comment by andyoneal** [comment] 2022-09-12 22:18
seeing the same problems and same log spam as @krendll on latest (https://github.com/transmission/transmission/commit/3c8d8488eaa8ec5216fce1247764a082d1846814)

Been checking back in and building my own every so often and had the same issues for months. Will work on something reliable that reproduces it. On an M1 Mac mini, if that narrows anything down.
