### ISSUE TITLE
transmission not working in windows 11

### ISSUE THREAD

**Issue by celestinoxp** [transmission/transmission#6178] opened 2023-10-29 22:36 UTC
### What is the issue?

when try open transmission the window is blank while 1 second and close automatically, crashes!

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

transmission-4.1.0-dev+rd059669c0e-x64.msi

**Comment by ckerr** [comment] 2023-10-30 01:52
@celestinoxp thanks for the report!

I'm pretty sure this is a duplicate of https://github.com/transmission/transmission/issues/6172 so I'm going to close this ticket.

If you still see issues after the fix for 6172 is merged, please open a new ticket :bowing_man:

**Closed by ckerr** 2023-10-30 01:52 UTC
