### ISSUE TITLE
Incorrect Display of Upload and Download Speeds

### ISSUE THREAD

**Issue by MineGene** [transmission/transmission#7280] opened 2024-12-05 07:28 UTC
### What is the issue?

**Summary:**
The Transmission torrent client displays upload and download speeds as approximately double their actual values.

**Steps to Reproduce:**

1. Open Transmission torrent client.
2. Start downloading or uploading a torrent.
3. Compare the speeds reported in Transmission with another network monitoring tool (e.g., iftop, Activity Monitor, or Task Manager). All are showing the same inaccuracy.

**Expected Result:**
The upload and download speeds in Transmission should accurately reflect the actual network throughput.

**Actual Result:**
Transmission reports upload and download speeds approximately twice the actual speed.

Environment:

Transmission Version: 4.0.6 (38c164933e)
Operating System: macOS 15.2 Beta (24C5089c)
Network Configuration: Wi-Fi

**Additional Notes:**
The behavior persists across multiple torrents.
No changes to network settings were made recently.
Restarting Transmission and the computer did not resolve the issue.
Network traffic monitoring tools confirm the inaccuracy.

Attachments:
<img width="163" alt="Screenshot 2024-12-05 at 5 23 20 pm" src="https://github.com/user-attachments/assets/5b46ea2e-1fe4-405d-be03-338291e792a8">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.6 (38c164933e)

**Comment by tearfur** [comment] 2024-12-05 08:18
Does your torrents have webseeds?

**Comment by MineGene** [comment] 2024-12-05 08:43
> Do your torrents have webseeds?

Yes

**Comment by tearfur** [comment] 2024-12-05 11:15
Duplicate of #7221

**Closed by tearfur** 2024-12-05 11:15 UTC
