### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by robd003** [transmission/transmission#4336] opened 2022-12-08 21:09 UTC
### What is the issue?

```
Process:               Transmission [19475]
Path:                  /Applications/Transmission.app/Contents/MacOS/Transmission
Identifier:            org.m0k.transmission
Version:               4.0.0-beta.2.dev (14714.4.0.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-12-08 16:07:30.6527 -0500
OS Version:            macOS 12.6.1 (21G217)
Report Version:        12

Time Awake Since Boot: 330000 seconds

System Integrity Protection: enabled

Crashed Thread:        1

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000040
Exception Codes:       0x0000000000000001, 0x0000000000000040
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [19475]

VM Region Info: 0x40 is not in any region.  Bytes before following region: 68719476672
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  ...(unallocated)

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x19ec26270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x19ec6083c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x19ebaf284 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   libc++.1.dylib                	       0x19ebafe5c std::__1::__assoc_sub_state::__sub_wait(std::__1::unique_lock<std::__1::mutex>&) + 56
4   libc++.1.dylib                	       0x19ebaff00 std::__1::__assoc_sub_state::wait() + 56
5   Transmission                  	       0x102caf580 tr_sessionClose(tr_session*, unsigned long) + 520
6   Transmission                  	       0x102c0ac98 -[Controller applicationWillTerminate:] + 1032
7   CoreFoundation                	       0x19ed21468 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
8   CoreFoundation                	       0x19edc5bb8 ___CFXRegistrationPost_block_invoke + 52
9   CoreFoundation                	       0x19edc5b24 _CFXRegistrationPost + 456
10  CoreFoundation                	       0x19ecf00f8 _CFXNotificationPost + 732
11  Foundation                    	       0x19fbb5c28 -[NSNotificationCenter postNotificationName:object:userInfo:] + 96
12  AppKit                        	       0x1a1b17edc -[NSApplication terminate:] + 1352
13  AppKit                        	       0x1a1a965c8 -[NSApplication(NSResponder) sendAction:to:from:] + 460
14  AppKit                        	       0x1a1b8c2ec -[NSMenuItem _corePerformAction] + 444
15  AppKit                        	       0x1a1b8bfe0 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 100
16  AppKit                        	       0x1a1ec70cc -[NSMenu _performActionForItem:atIndex:fromEvent:] + 228
17  AppKit                        	       0x1a1b8b304 -[NSMenu performKeyEquivalent:] + 452
18  AppKit                        	       0x1a20021fc routeKeyEquivalent + 568
19  AppKit                        	       0x1a1a00e6c -[NSApplication(NSEvent) sendEvent:] + 1172
20  AppKit                        	       0x1a1cbb0f4 -[NSApplication _handleEvent:] + 76
21  AppKit                        	       0x1a1883008 -[NSApplication run] + 636
22  AppKit                        	       0x1a18546fc NSApplicationMain + 1132
23  dyld                          	       0x1032d108c start + 520

Thread 1 Crashed:
0   Transmission                  	       0x102ce45b8 tr_peerIo::setCallbacks(ReadState (*)(tr_peerIo*, void*, unsigned long*), void (*)(tr_peerIo*, unsigned long, bool, void*), void (*)(tr_peerIo*, short, void*), void*) + 0
1   Transmission                  	       0x102cdd84c tr_handshakeDone(tr_handshake*, bool) + 204
2   Transmission                  	       0x102cee764 Handshakes::abortAll() + 56
3   Transmission                  	       0x102ce974c tr_swarm::stop() + 56
4   Transmission                  	       0x102cbc26c stopTorrent(tr_torrent*) + 176
5   Transmission                  	       0x102cbc428 tr_torrentFreeInSessionThread(tr_torrent*) + 144
6   Transmission                  	       0x102caeef8 tr_session::closeImplPart1(std::__1::promise<void>*, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 312
7   Transmission                  	       0x102cdab7c tr_session_thread_impl::onWorkAvailable() + 116
8   Transmission                  	       0x102d6dbb8 event_process_active_single_queue + 1092
9   Transmission                  	       0x102d6a560 event_base_loop + 1068
10  Transmission                  	       0x102cda8f8 tr_session_thread_impl::sessionThreadFunc(event_base*) + 96
11  Transmission                  	       0x102cdad40 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> >(void*) + 68
12  libsystem_pthread.dylib       	       0x19ec6026c _pthread_start + 148
13  libsystem_pthread.dylib       	       0x19ec5b08c thread_start + 8
```

### Which application of Transmission?

macOS app

### Which version of Transmission?

e06e304cc8

**Comment by ckerr** [comment] 2022-12-09 06:34
Thanks for the report! I think this is a duplicate of https://github.com/transmission/transmission/issues/4317

**Closed by ckerr** 2022-12-09 06:34 UTC
