### ISSUE TITLE
Transmission-Qt 2.94 (d8e60ee44f) x64 crashed

### ISSUE THREAD

**Issue by AngelFalse** [transmission/transmission#875] opened 2019-04-08 02:44 UTC
![image](https://user-images.githubusercontent.com/28922095/55694787-4b2c7400-59e8-11e9-8fea-b89c9cd2eaf2.png)

Transmission-Qt crashed when connected to a remote machine in the same LAN with transmission-daemon running.
transmission-qt在连接控制着局域网内的一台远程机器时崩溃

Local (Qt Management Interface) Environment:
本地机器配置：
Windows 10 Enterprise 10.0.14393 2016 LTSB
transmission-qt 2.94 (d8e60ee44f) x64
Chinese Simplified
![image](https://user-images.githubusercontent.com/28922095/55694891-d6a60500-59e8-11e9-81c8-c9d80e3adbb7.png)

Remote (Transmission-daemon, on a ARM device) Version:
远程transmission版本：
transmission-daemon 2.84 (14307) downloaded from a entware mirror. (the mirror has been shutdown, and 2.84 hasn't been found on other sites.)
从一个entware镜像下载的transmission-daemon 2.84 (14307)，镜像站已经没了，而且2.84版本的transmission-daemon并没有在其它地方发现。
Platform information:
平台信息
https://paste.ubuntu.com/p/VPs7b8kTqB/

There is only so much to provide, because I consider this problem happens on the "management interface" side other than on the remote transmission-daemon side.
我只提供这些信息，因为我认为这个问题应该出在2.94版本的Qt版transmission上。
And I don't know what else to provide.
而且我不知道该给哪些其它信息。

**Comment by AngelFalse** [comment] 2019-05-28 23:30
Another crash happened with transmission-daemon 2.94. I was able to gather a full dump with procxp.
![image](https://user-images.githubusercontent.com/28922095/58518832-5bd8b980-81e3-11e9-90f2-b19317f85d94.png)
If anyone want's to analyze this dump, plz leave a message.

**Comment by ckerr** [comment] 2022-02-25 20:36
This should've been triaged sooner, but unfortunately it wasn't.

@AngelFalse you may want to try a [nightly build](https://transmissionbt.com/download) to see if the problem is still there. There has been a _lot_ of work on improving Transmission over the last few months.

**Comment by ckerr** [comment] 2023-01-30 18:18
Closing due to lack of actionable information + lack of a response.

If this is still happening in 4.0.0-beta.1 or newer, please open a new issue. Thank you!

**Closed by ckerr** 2023-01-30 18:18 UTC
Labels: bug, needs clarification, scope:qt, os:windows
