### ISSUE TITLE
[Feature Request] support for global upload slot limit

### ISSUE THREAD

**Issue by username-not-taken** [transmission/transmission#1343] opened 2020-06-28 18:24 UTC
would be nice if a option to limit the upload slots that are available for all torrents could be implemented.

currently it is only possible to set the global peer limit and that seems to favor seeding torrents so downloads become hard if you are seeding hundreds of torrents and set the global peer limit to something that your connections upload bandwidth and hdds can handle.
i know that there is the upload queue but that does not work very well with private trackers because it pauses the torrents and even on public trackers it would be bad because the peer cant connect to you and wait for their turn when the torrent is not being announced anywhere and that is the reason why im making this request

**Comment by Pentaphon** [comment] 2022-01-24 06:47
@ckerr since you're doing a massive cleanup of issues, here's a duplicate of this issue. I suggest keeping this one even though the other one is older since the user on the other one deleted his account and this one has more reactions to show support. Also, I think this would be a great feature to add to Transmission's GUI since most people aren't aware that Transmission has 14 upload slots by default since most people don't go to the .json file and just use the GUI. Making it easier for users to lower the number of upload slots would speed up the upload to each peer since a seeder's upload speed is divided up among a smaller number of leechers.

https://github.com/transmission/transmission/issues/683

**Closed** 2022-01-24 15:54 UTC
Labels: enhancement
