### ISSUE TITLE
[Feature request] Add sequential downloads

### ISSUE THREAD

**Issue by UsmanTariq2** [transmission/transmission#6944] opened 2024-06-24 16:28 UTC
### What is the issue?

Please add sequential downloading to transmission

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

transmission-4.0.6-x64.

**Comment by tearfur** [comment] 2024-06-25 01:48
Duplicate of #5169.

**Closed by tearfur** 2024-06-25 01:48 UTC
