### ISSUE TITLE
transmission ignore blank info make wrong hash

### ISSUE THREAD

**Issue by ted423** [transmission/transmission#1136] opened 2020-02-28 07:37 UTC
The seed I found is not suitable for public, so I just made one according to the principle.

[1.zip](https://github.com/transmission/transmission/files/4265770/1.zip)
![批注 2020-02-28 153556](https://user-images.githubusercontent.com/7042766/75520299-2e55c080-5a40-11ea-890f-3461fc5aec47.png)
![批注 2020-02-28 153506](https://user-images.githubusercontent.com/7042766/75520302-301f8400-5a40-11ea-9873-1041e747c12b.png)

**Comment by ckerr** [comment] 2022-01-19 16:59
I don't understand this bug report. Could you give a little more detail about what bug you're seeing?

**Comment by ckerr** [comment] 2022-02-25 03:53
Duplicate of https://github.com/transmission/transmission/issues/1453

**Closed by ckerr** 2022-02-25 03:53 UTC
