### ISSUE TITLE
Docker not persisting changes to settings.json

### ISSUE THREAD

**Issue by MikeVlad6** [transmission/transmission#1776] opened 2021-09-04 15:20 UTC
After hours of debugging i still can't figure out how to change values inside `settings.json` and for them to be persistent.

I have two objectives:
1. To assign a script to be ran whenever a torrent is completed
2. To disable `incomplete-dir-enabled` so that the torrents will download directly in the final folder and transmission won't freeze at each completed torrent move (as described in issue 108 here).

I'm running a transmission instance inside a Docker container. This docker container is part of a docker-compose. These are the configs:

`docker-compose`
``` transmission:
    container_name: PLEXSTACK_Transmission
    build:
      context: ./
      dockerfile: Dockerfile_MAINSTACK_transmission
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - ${TRANSMISSION_FILES_LOCATION}/downloads:/downloads
      - ${TRANSMISSION_FILES_LOCATION}/watch:/watch
      - ${PLEX_TV_LIBRARY_FOLDER}:/tv
      - ${PLEX_MOVIES_LIBRARY_FOLDER}:/movies
      - /mnt/Media/books/downloads:/books
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
```
`dockerfile:`
```
FROM ghcr.io/linuxserver/transmission

LABEL Author="some"

# Copy files
COPY torr_service/finished_torrent_routine.py ./
COPY torr_service/torr_finished_routine.sh ./
# Set run rights -i know they're too broad but fk it
RUN chmod 777 finished_torrent_routine.py
RUN chmod 777 torr_finished_routine.sh

# Add routine to change transmission settings.
COPY torr_service/change_transmission_settings.sh ./config/custom-cont-init.d/
RUN chmod +x ./config/custom-cont-init.d/change_transmission_settings.sh
RUN chmod 777 ./config/custom-cont-init.d/change_transmission_settings.sh
```

This is the `change_transmission_settings.sh`:
```
#!/bin/bash

jq '."script-torrent-done-enabled" = true' /config/settings.json
jq '."script-torrent-done-filename" = "/torr_finished_routine.sh"' /config/settings.json
# test 1231
jq '."incomplete-dir-enabled" = false' /config/settings.json
```
It simply changes the values of a json.

Docker builds fine, it runs the `change_transmission_settings.sh` script but transmission reverts these changes to the default. Each. And. Every. Time. 
logs:
```
[custom-init] files found in /config/custom-cont-init.d executing

[custom-init] change_transmission_settings.sh: executing...

{

  "alt-speed-down": 50,

  "alt-speed-enabled": false,

  "alt-speed-time-begin": 540,

  "alt-speed-time-day": 127,

  "alt-speed-time-enabled": false,

  "alt-speed-time-end": 1020,

  "alt-speed-up": 50,

  "bind-address-ipv4": "0.0.0.0",

  "bind-address-ipv6": "::",

  "blocklist-enabled": false,

  "blocklist-url": "http://www.example.com/blocklist",

  "cache-size-mb": 4,

  "dht-enabled": true,

  "download-dir": "/downloads/complete",

  "download-queue-enabled": true,

  "download-queue-size": 5,

  "encryption": 1,

  "idle-seeding-limit": 30,

  "idle-seeding-limit-enabled": false,

  "incomplete-dir": "/downloads/incomplete",

  "incomplete-dir-enabled": true,

  "lpd-enabled": false,

  "message-level": 2,

  "peer-congestion-algorithm": "",

  "peer-id-ttl-hours": 6,

  "peer-limit-global": 200,

  "peer-limit-per-torrent": 50,

  "peer-port": 51413,

  "peer-port-random-high": 65535,

  "peer-port-random-low": 49152,

  "peer-port-random-on-start": false,

  "peer-socket-tos": "default",

  "pex-enabled": true,

  "port-forwarding-enabled": true,

  "preallocation": 1,

  "prefetch-enabled": 1,

  "queue-stalled-enabled": true,

  "queue-stalled-minutes": 30,

  "ratio-limit": 2,

  "ratio-limit-enabled": false,

  "rename-partial-files": true,

  "rpc-authentication-required": true,

  "rpc-bind-address": "0.0.0.0",

  "rpc-enabled": true,

  "rpc-password": "vreinuvrei6",

  "rpc-port": 9091,

  "rpc-url": "/transmission/",

  "rpc-username": "mike",

  "rpc-host-whitelist": "",

  "rpc-host-whitelist-enabled": false,

  "rpc-whitelist": "",

  "rpc-whitelist-enabled": false,

  "scrape-paused-torrents-enabled": true,

  "script-torrent-done-enabled": true,

  "script-torrent-done-filename": "",

  "seed-queue-enabled": false,

  "seed-queue-size": 10,

  "speed-limit-down": 100,

  "speed-limit-down-enabled": false,

  "speed-limit-up": 100,

  "speed-limit-up-enabled": false,

  "start-added-torrents": true,

  "trash-original-torrent-files": false,

  "umask": 2,

  "upload-slots-per-torrent": 14,

  "utp-enabled": false,

  "watch-dir": "/watch",

  "watch-dir-enabled": true

}

{

  "alt-speed-down": 50,

  "alt-speed-enabled": false,

  "alt-speed-time-begin": 540,

  "alt-speed-time-day": 127,

  "alt-speed-time-enabled": false,

  "alt-speed-time-end": 1020,

  "alt-speed-up": 50,

  "bind-address-ipv4": "0.0.0.0",

  "bind-address-ipv6": "::",

  "blocklist-enabled": false,

  "blocklist-url": "http://www.example.com/blocklist",

  "cache-size-mb": 4,

  "dht-enabled": true,

  "download-dir": "/downloads/complete",

  "download-queue-enabled": true,

  "download-queue-size": 5,

  "encryption": 1,

  "idle-seeding-limit": 30,

  "idle-seeding-limit-enabled": false,

  "incomplete-dir": "/downloads/incomplete",

  "incomplete-dir-enabled": true,

  "lpd-enabled": false,

  "message-level": 2,

  "peer-congestion-algorithm": "",

  "peer-id-ttl-hours": 6,

  "peer-limit-global": 200,

  "peer-limit-per-torrent": 50,

  "peer-port": 51413,

  "peer-port-random-high": 65535,

  "peer-port-random-low": 49152,

  "peer-port-random-on-start": false,

  "peer-socket-tos": "default",

  "pex-enabled": true,

  "port-forwarding-enabled": true,

  "preallocation": 1,

  "prefetch-enabled": 1,

  "queue-stalled-enabled": true,

  "queue-stalled-minutes": 30,

  "ratio-limit": 2,

  "ratio-limit-enabled": false,

  "rename-partial-files": true,

  "rpc-authentication-required": true,

  "rpc-bind-address": "0.0.0.0",

  "rpc-enabled": true,

  "rpc-password": "vreinuvrei6",

  "rpc-port": 9091,

  "rpc-url": "/transmission/",

  "rpc-username": "mike",

  "rpc-host-whitelist": "",

  "rpc-host-whitelist-enabled": false,

  "rpc-whitelist": "",

  "rpc-whitelist-enabled": false,

  "scrape-paused-torrents-enabled": true,

  "script-torrent-done-enabled": false,

  "script-torrent-done-filename": "/torr_finished_routine.sh",

  "seed-queue-enabled": false,

  "seed-queue-size": 10,

  "speed-limit-down": 100,

  "speed-limit-down-enabled": false,

  "speed-limit-up": 100,

  "speed-limit-up-enabled": false,

  "start-added-torrents": true,

  "trash-original-torrent-files": false,

  "umask": 2,

  "upload-slots-per-torrent": 14,

  "utp-enabled": false,

  "watch-dir": "/watch",

  "watch-dir-enabled": true

}

{

  "alt-speed-down": 50,

  "alt-speed-enabled": false,

  "alt-speed-time-begin": 540,

  "alt-speed-time-day": 127,

  "alt-speed-time-enabled": false,

  "alt-speed-time-end": 1020,

  "alt-speed-up": 50,

  "bind-address-ipv4": "0.0.0.0",

  "bind-address-ipv6": "::",

  "blocklist-enabled": false,

  "blocklist-url": "http://www.example.com/blocklist",

  "cache-size-mb": 4,

  "dht-enabled": true,

  "download-dir": "/downloads/complete",

  "download-queue-enabled": true,

  "download-queue-size": 5,

  "encryption": 1,

  "idle-seeding-limit": 30,

  "idle-seeding-limit-enabled": false,

  "incomplete-dir": "/downloads/incomplete",

  "incomplete-dir-enabled": false,

  "lpd-enabled": false,

  "message-level": 2,

  "peer-congestion-algorithm": "",

  "peer-id-ttl-hours": 6,

  "peer-limit-global": 200,

  "peer-limit-per-torrent": 50,

  "peer-port": 51413,

  "peer-port-random-high": 65535,

  "peer-port-random-low": 49152,

  "peer-port-random-on-start": false,

  "peer-socket-tos": "default",

  "pex-enabled": true,

  "port-forwarding-enabled": true,

  "preallocation": 1,

  "prefetch-enabled": 1,

  "queue-stalled-enabled": true,

  "queue-stalled-minutes": 30,

  "ratio-limit": 2,

  "ratio-limit-enabled": false,

  "rename-partial-files": true,

  "rpc-authentication-required": true,

  "rpc-bind-address": "0.0.0.0",

  "rpc-enabled": true,

  "rpc-password": "vreinuvrei6",

  "rpc-port": 9091,

  "rpc-url": "/transmission/",

  "rpc-username": "mike",

  "rpc-host-whitelist": "",

  "rpc-host-whitelist-enabled": false,

  "rpc-whitelist": "",

  "rpc-whitelist-enabled": false,

  "scrape-paused-torrents-enabled": true,

  "script-torrent-done-enabled": false,

  "script-torrent-done-filename": "",

  "seed-queue-enabled": false,

  "seed-queue-size": 10,

  "speed-limit-down": 100,

  "speed-limit-down-enabled": false,

  "speed-limit-up": 100,

  "speed-limit-up-enabled": false,

  "start-added-torrents": true,

  "trash-original-torrent-files": false,

  "umask": 2,

  "upload-slots-per-torrent": 14,

  "utp-enabled": false,

  "watch-dir": "/watch",

  "watch-dir-enabled": true

}

[custom-init] change_transmission_settings.sh: exited 0

[cont-init.d] 99-custom-files: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

[2021-09-04 18:01:52.028] Transmission 3.00 (bb6b5a062e) started (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/session.c:769)

[2021-09-04 18:01:52.028] RPC Server Serving RPC and Web requests on 0.0.0.0:9091/transmission/ (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:1243)

[2021-09-04 18:01:52.028] RPC Server Password required (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:1254)

[2021-09-04 18:01:52.028] DHT Generating new id (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-dht.c:389)

[2021-09-04 18:01:52.028] Using settings from "/config" (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:646)

[2021-09-04 18:01:52.028] Saved "/config/settings.json" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/variant.c:1221)
```
In the example i gave, i was changing `/config/settings.json` . I got it working by changing  `/default/settings/json` instead but i might have changed something else on the way because i can't replicate it anymore. 

Is there any other way of changing these 3 settings?
- script-torrent-done-enabled
- script-torrent-done-filename
- incomplete-dir-enabled
?

Any help would be much appreciated.
Thank you!

**Comment by Trim21** [comment] 2021-10-16 21:00
just mount a json file from host to default settings.json locationin the container

**Comment by ckerr** [comment] 2021-10-17 15:21
Sending it a SIGHUP will tell transmission-daemon to reload settings:

https://github.com/transmission/transmission/blob/1fb5a798132e9ba4bcd016153ffd1e933aea3b24/daemon/daemon-posix.cc#L49

**Comment by ckerr** [comment] 2022-01-26 06:52
Closing as a duplicate of https://github.com/transmission/transmission/issues/882. The two tickets are phrased differently, but have the same core issue

**Closed by ckerr** 2022-01-26 06:52 UTC
