### ISSUE TITLE
'Execute script' isn't working on windows

### ISSUE THREAD

**Issue by hulekgre** [transmission/transmission#405] opened 2017-09-17 23:20 UTC
I just want to execute a .bat with a command line, just like it works in basically any other bitorrent client available.

**Comment by dakotalightning** [comment] 2017-12-08 00:38
bump

I'm having the same issue. Does anyone have any ideas on how to get this to work?

**Comment by mikedld** [comment] 2017-12-08 03:06
Sorry I didn't notice this before. The issue has been fixed in recent nightly builds (30c7c05cbbca935a815d72ae4d425afabc922e4f). If you can, please try it out ([x64](https://build.transmissionbt.com/job/trunk-win32/lastSuccessfulBuild/arch=x64,label=pepito-win10/), [x86](https://build.transmissionbt.com/job/trunk-win32/lastSuccessfulBuild/arch=x86,label=pepito-win10/)) and report back.

**Comment by dakotalightning** [comment] 2017-12-09 21:45
Is there a log I can check to see if the script has failed?

**Comment by mikedld** [comment] 2017-12-13 13:49
You could start the daemon with `-e`/`--logfile` option to get the log file.

**Comment by opicron** [comment] 2017-12-21 19:32
Tried the latest build. Script is not executed after download here.

**Comment by mikedld** [comment] 2018-01-26 05:42
Any more details guys?
@dakotalightning is it working for you?
@opicron what does your script look like? how do you know that it's not executed?

**Comment by slokhorst** [comment] 2018-01-27 10:02
Just tested the Windows x64 94be7dbd9bd3a149c2c954cdaaa4192f7d24a953 nightly (Qt client) and it worked just fine.

**Comment by fabionar** [comment] 2018-03-04 20:13
@mikedld Not working on Transmission 2.93+ (96926a8337)

**Comment by slokhorst** [comment] 2018-03-04 20:28
@fabionar are you using the Qt client?

**Comment by fabionar** [comment] 2018-03-04 21:36
@slokhorst https://build.transmissionbt.com/job/trunk-win32/lastBuild/arch=x64,label=pepito-win10/artifact/build-x64/dist/msi/transmission-2.93+-r96926a8337-x64.msi
I'm not sure if I understand what you're saying. But I haven't installed anything but this link.

**Comment by slokhorst** [comment] 2018-03-04 21:48
@fabionar in the installation wizard, you have to choose which components you want to install. The default is the Qt client only so you probably have that.

What does your script look like? Does it work for a simple `.bat` file like this?
```bat
echo test at %time% >> %userprofile%\desktop\log.txt
```

**Comment by mikedld** [comment] 2018-10-04 04:53
Closing this for the lack of response assuming it's fixed in master. If it's still not working please provide more information e.g. what @slokhorst asks.

**Closed by mikedld** 2018-10-04 04:53 UTC
Labels: bug, comp:core, os:windows

**Comment by opicron** [comment] 2019-02-01 08:43
I cant test in the latest nighly build because ssl servers are not connecting in that build. It doesnt work on the default download 64bit.

**Comment by thiagoalz** [comment] 2019-03-10 18:02
Not working for me.
Tested with 2.94 x64.

Log says Calling script "C:\PathToScript\SimpleScript.bat"

but te script(That should only write hello to a file) is not executed.

**Comment by mikedld** [comment] 2019-03-10 18:39
@thiagoalz please test the latest nightly at the links above (https://github.com/transmission/transmission/issues/405#issuecomment-350159767). The milestone is explicitly set to 3.00, 2.94 doesn't contain the fix.

**Comment by thiagoalz** [comment] 2019-03-10 20:11
Oh.. sorry about that. I thought it was on 2.94 because of the dates (commit is 2017 X release is 2018 ).
But ok, going to try nightly and return here.

**Comment by thiagoalz** [comment] 2019-03-10 21:25
Same thing :/ 
Used Build #185 (03/03/2019 14:20:09).
Log says [2019-03-10 18:20:01.482] MytorrentName Calling script "PathTo.Bat"
But bat did not run

**Comment by mikedld** [comment] 2019-03-10 21:54
What is the exact contents of your batch script? What is the expected behavior? How do you know that it "did not run"?

**Comment by thiagoalz** [comment] 2019-03-10 23:07
It just writes "hello" to a file.
Running it directly it works perfectly.
Running after a torrent finishes nothing happens

**Comment by mikedld** [comment] 2019-03-10 23:35
Please provide the exact contents of the script...

**Comment by thiagoalz** [comment] 2019-03-12 01:09
I've tried some different options (any of them worked)
The one im using now is like this:
@echo off
echo MyTest - "%TR_TORRENT_DIR%\%TR_TORRENT_NAME%" > D:\Downloads\zlegendas\output2.txt

**Comment by thiagoalz** [comment] 2019-03-12 01:15
Running it directly, the file is like this (as expected):
MyTest - "\" 

"Running" on torrent finish, file is empty.

**Comment by samkatakouzinos** [comment] 2019-03-12 06:24
Have installed and run as deamon from x64 file from https://github.com/transmission/transmission/issues/405#issuecomment-350159767.

installation file: transmission-2.94+-ra440981571-x64.msi

settings.json entries:
    "script-torrent-done-enabled": true,
    "script-torrent-done-filename": "C:\\ProgramData\\NZBGet\\scripts\\nzbToMedia\\TorrentToMedia.py",

log entries (log-debug):
```logtalk
[2019-03-12 15:42:02.505] Saved "C:\Windows\ServiceProfiles\LocalService\AppData\Local\transmission-daemon\Resume\b51ef3d700a8ec82e77a770ceaaee4f8f2fa64c3.resume" (C:\Transmission\Jenkins\workspace\trunk-win32\arch\x64\label\pepito-win10\libtransmission\variant.c:1199)
[2019-03-12 15:42:02.505] INXS - The Years 1979-1997 (320) Calling script "C:\ProgramData\NZBGet\scripts\nzbToMedia\TorrentToMedia.py" (C:\Transmission\Jenkins\workspace\trunk-win32\arch\x64\label\pepito-win10\libtransmission\torrent.c:2263)
[2019-03-12 15:42:02.505] INXS - The Years 1979-1997 (320) Error executing script "C:\ProgramData\NZBGet\scripts\nzbToMedia\TorrentToMedia.py" (193): Call to CreateProcess() failed: %1 is not a valid Win32 application. (C:\Transmission\Jenkins\workspace\trunk-win32\arch\x64\label\pepito-win10\libtransmission\torrent.c:2269)
[2019-03-12 15:44:03.503] Saved "C:\Windows\ServiceProfiles\LocalService\AppData\Local\transmission-daemon\stats.json" (C:\Transmission\Jenkins\workspace\trunk-win32\arch\x64\label\pepito-win10\libtransmission\variant.c:1199)
```

**Comment by samkatakouzinos** [comment] 2019-03-12 06:37
Seems that 

> CreateProcess requires you to provide an executable file. If you wish to be able to open any file with its associated application then you need ShellExecute rather than CreateProcess. 
[reference](https://stackoverflow.com/questions/12637203/why-does-createprocess-give-error-193-1-is-not-a-valid-win32-app)

Q: Would you be willing to implement a ShellExecute test version? This may allow scripts interpreters to run the script (Python, Powershell, CMD, other).

**Comment by mikedld** [comment] 2019-03-12 07:40
@samkatakouzinos, Running Python scripts directly is currently not supported; only .exe, .bat, or .cmd could be used (or at least were tested). Using `ShellExecute` is not possible as it doesn't allow for customization of environment of the command being started and that's how we pass all the good stuff to the scripts. Supporting running other types of scripts (directly) is something we want, but not as part of this issue here anyway.

**Comment by samkatakouzinos** [comment] 2019-03-12 08:35
I see, https://github.com/transmission/transmission/blob/c11f2870fd18ff781ca06ce84b6d43541f3293dd/libtransmission/subprocess-win32.c#L323 .
Do you see a problem if I call a batch file (*.bat) that calls python to execute a script?

**Comment by thiagoalz** [comment] 2019-03-12 09:40
Do you see a problem if I call a batch file (*.bat) that calls python to execute a script?

That was exactly what I was trying to do. Once it didn't work, I moved to a simpler script to check execution end noticed that even just a echo is not running.

**Comment by mikedld** [comment] 2019-03-12 22:58
I've just verified and script execution is still working as expected in latest builds. Expectations may vary though, so here's what you may want to bear in mind:
* To reiterate, only .exe, .bat, and .cmd are currently officially supported/tested.
* When installing the daemon, it's set up to run under Local Service account. This is a limited account that doesn't have access to all the files on your disk, and these limitations apply to any processes it launches including the scripts you specify in settings.json. In particular, Local Service will most probably NOT have access to the files in your home folder. Solutions include (but aren't limited to) putting the script into a folder that server is specifically granted access to, or reconfiguring the service to run under your user account; the latter may not stick between updates, I didn't test but I have a feeling.
* This is mostly a continuation of the above: whether you're using the daemon or the Qt client, the script you're running may not have access to the directory you're trying to create files in (including via output redirection) due to access permissions.
* When writing a script,
  * start with a very basic version, e.g. echo a few words to a file in a folder writable by Everyone;
  * don't assume you know what current working directory is at the beginning of the script: either use absolute paths or do an explicit `cd ...` (using absolute path, again) beforehand; even if you're used to working directory being "inherited" by child processes, it's not the case here (and you shouldn't know Transmission's current working directory anyway); using environment variables in paths is okay (but see below) if the final resolved path is absolute;
  * don't assume that the environment you're manually testing the script in the same as the one Transmission is setting up to run your script; add a `set > C:\Path\To\Script.log` line to your test script to see what variables are actually present, and what their values are (you may be surprised by e.g. PATH; adding `where toolname > C:\Path\To\Script.log` sometimes helps);
  * not directly related, but if you feel like you're writing a lot of stuff into the log file but getting little actual output, quickly scan through your script code to check if you're using `>` (truncate) and `>>` (append) output redirections properly.
* When editing settings.json manually to specify script path,
  * make sure you're double-quoting the value and doubling the backslashes (i.e. writing `"C:\\Path\\To\\Script.cmd"` and not `"C:\Path\To\Script.cmd"`);
  * using forward slashes (i.e. writing `"C:/Path/To/Script.cmd"`) is acceptable if you're tired;
  * official builds aren't using Cygwin or anything, so paths like `"/cygdrive/c/path/to/script.cmd"` (or whatever) will not be recognized;
  * `script-torrent-done-filename` value needs to contain a single path, not a command with arguments.

The above may be incomplete but should hopefully save you a few hours/days. Looking forward to putting this somewhere in docs (help welcome).

P.S. I recognize that troubleshooting may be harder than we'd all like when something goes wrong (same on *NIX really). PRs and ideas to somehow improve that are welcome.

P.P.S. Happy scripting.

**Comment by thiagoalz** [comment] 2019-03-13 01:29
Ya man.... You nailed it!
First, your tips are gold. I already spent 2 days discovering them one by one!
Second.... I`had tried everything I could with permissions and nothing...Once I changed the user running the service... Bingo!

Another tip for those trying this now... after I changed the user running the service I had to reconfigure settings.json!

All perfect now!
Thanks alot for the help!

**Comment by samkatakouzinos** [comment] 2019-03-14 09:21
@thiagoalz that's a great result and promising news for me.  
May you share your script here for me to study?  
  
I'm taking baby steps to see where I'm failing.  
Echoing and appending  (>>) work.
I'm having trouble with calling python with a script.  
Also with using parameters such as "set >> %~dpn0.output.log" which I expected to create a log file where the batch file resides but instead created a file named ~dpn0.output.log under c drive.  

Appreciate any advice from all.

My efforts below;

<details><summary>batch file contents</summary>

```batchfile
rem CD /d "%~dp0"
rem python3.exe .\nzbToMedia\nzbToLidarr.py 
echo " " >> c:\nzbToLidarr.output2.txt
echo " " >> c:\nzbToLidarr.output2.txt
echo "=========" >> c:\nzbToLidarr.output2.txt
echo "~dp0 = " %~dp0 >> c:\nzbToLidarr.output2.txt
%~dp0 >> c:\nzbToLidarr.output2.txt
echo "where python3.exe = " where python3.exe >> c:\nzbToLidarr.output2.txt
where python3.exe >> c:\nzbToLidarr.output2.txt
rem echo %~dp0 >> c:\nzbToLidarr.output2.txt
echo MyTest - "%TR_TORRENT_DIR%\%TR_TORRENT_NAME%" >> c:\nzbToLidarr.output2.txt
set >> c:\nzbToLidarr.output2.txt
echo MyTest - "%TR_TORRENT_DIR%\%TR_TORRENT_NAME%" >> %~dpn0.output.log
set >> %~dpn0.output.log
python3.exe .\nzbToMedia\nzbToLidarr.py 
```
</details>

<details><summary>c:\nzbToLidarr.output2.txt content</summary>

```
" " 
" " 
"=========" 
"~dp0 = " ~dp0 
"where python3.exe = " where python3.exe 
C:\ProgramData\Python\3\python3.exe
MyTest - "C:\WINDOWS\ServiceProfiles\LocalService\Downloads\transmissionbt\music\David Gray - Gold in a Brass Age (2019) [320]" 
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\b19680703\AppData\Roaming
asl.log=Destination=file
ChocolateyInstall=C:\ProgramData\chocolatey
ChocolateyLastPathUpdate=Sun Mar 10 17:12:16 2019
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=SKG-DV-003
ComSpec=C:\WINDOWS\system32\cmd.exe
D3DGEARPATH=c:\program files (x86)\iracing
DriverData=C:\Windows\System32\Drivers\DriverData
INTEL_DEV_REDIST=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\
LIBTHAI_DICTDIR=C:\Program Files\GIMP 2\share\libthai
LOCALAPPDATA=C:\Users\b19680703\AppData\Local
MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\compiler\lib\mic
NDI_RUNTIME_DIR_V2=C:\Program Files\NewTek\NewTek NDI Redist\v3
NDI_RUNTIME_DIR_V3=C:\Program Files\NewTek\NewTek NDI Redist\v3
NUMBER_OF_PROCESSORS=8
OneDrive=C:\Users\b19680703\OneDrive
OneDriveConsumer=C:\Users\b19680703\OneDrive
OS=Windows_NT
Path=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\programdata\Python\2\;C:\programdata\Python\2\Scripts;C:\ProgramData\Python\3\;C:\ProgramData\Python\3\Scripts\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;c:\program files (x86)\iracing;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\ProgramData\Boxstarter;C:\Program Files\Calibre2\;C:\Program Files\PuTTY\;C:\Program Files\MariaDB 10.2\bin;C:\Program Files\Microsoft VS Code\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Streamlink\bin;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Python27;C:\Users\b19680703\AppData\Local\Microsoft\WindowsApps;C:\Users\b19680703\AppData\Local\atom\bin;C:\Program Files\Oracle\VirtualBox;C:\Users\b19680703\AppData\Roaming\npm;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3a09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Users\b19680703\Documents\WindowsPowerShell\Modules
PUBLIC=C:\Users\Public
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\b19680703\AppData\Local\Temp
TMP=C:\Users\b19680703\AppData\Local\Temp
TR_APP_VERSION=2.94+
TR_TIME_LOCALTIME=Thu Mar 14 19:48:05 2019
TR_TORRENT_DIR=C:\WINDOWS\ServiceProfiles\LocalService\Downloads\transmissionbt\music
TR_TORRENT_HASH=bda94086dd335f6025484a4d942f713c71d71443
TR_TORRENT_ID=10
TR_TORRENT_NAME=David Gray - Gold in a Brass Age (2019) [320]
USERDOMAIN=SKG-DV-003
USERNAME=b19680703
USERPROFILE=C:\Users\b19680703
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
windir=C:\WINDOWS
```
</details>

**Comment by thiagoalz** [comment] 2019-03-15 01:38
Sure
This is the script Im using now:
```
@echo off
::Transmission vars
::* TR_APP_VERSION
::* TR_TIME_LOCALTIME
::* TR_TORRENT_DIR
::* TR_TORRENT_HASH
::* TR_TORRENT_ID
::* TR_TORRENT_NAME


IF [%TR_TORRENT_NAME%]==[] (
	echo Baixando Legendas em: "D:\Downloads\series"
	python D:\Downloads\zlegendas\OpenSubtitlesDownload.py "D:\Downloads\series"
	echo Baixando Legendas em: "D:\Downloads\torrents"
	python D:\Downloads\zlegendas\OpenSubtitlesDownload.py "D:\Downloads\torrents"
) ELSE (
	echo Baixando Legendas em: "%TR_TORRENT_DIR%\%TR_TORRENT_NAME%" > D:\Downloads\zlegendas\outputTransmission.txt
	python D:\Downloads\zlegendas\OpenSubtitlesDownload.py "%TR_TORRENT_DIR%\%TR_TORRENT_NAME%" >> D:\Downloads\zlegendas\outputTransmission.txt
)

TIMEOUT 10
```

**Comment by samkatakouzinos** [comment] 2019-03-18 16:46
> Sure
> This is the script Im using now:

Thank you, very useful.

**Comment by sergeevabc** [comment] 2020-02-20 16:22
transmission-cli 2.77 (for Windows 7) throws error as follows
```error executing script "stop_cli.cmd": No such file or directory```
The command was ```transmission-cli.exe -f stop_cli.cmd -w . magnet:?xt=urn:btih:...```
