### ISSUE TITLE
Observing for torrents in a folder does not work in Beta 4

### ISSUE THREAD

**Issue by nvanfleet** [transmission/transmission#4100] opened 2022-11-05 21:33 UTC
### What is the issue?

I tried several times to re-configure observing a specific folder for a new torrent file. So far I have had no luck in getting it working. If I select a folder that contains torrents it will add them, but if I add a torrent after that point it won't detect them at all.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0 beta 41422c357e

**Comment by belovachap** [comment] 2022-11-06 14:05
Hrm, we had a similar problem but in the transmission-gtk app that has been fixed recently: https://github.com/transmission/transmission/issues/4076

**Comment by ckerr** [comment] 2023-01-17 23:56
@nvanfleet based on the previous comment, looks like this might be fixed. Are you still seeing this problem in 4.0.0-beta.3 or newer?

**Comment by ckerr** [comment] 2023-03-11 07:39
Duplicate of https://github.com/transmission/transmission/issues/4683

**Closed by ckerr** 2023-03-11 07:39 UTC
Labels: bug, needs clarification
