### ISSUE TITLE
Transmission mono core

### ISSUE THREAD

**Issue by elpedriyo** [transmission/transmission#1121] opened 2020-02-01 23:51 UTC
Hello guys,

Just having some few problems with transmission, at the moment I was trying to make a build with a NAS, and transmission to be downloading in the NAS.
So I started downloading in NAS, and saw some behavieurs that I really do not like from it. So at the first beginning I thought on downloading first on an individual disk, and once the download was completed, tranmission should move it to a NAS folder, this ended up terribly bad, each time a download finished, transmission started to move from local to NAS through NFS the file, but at the same time, it was freezed for the rest of the downloads, so I guess that tranmission only works as mono thread process.
So the second thing I tried, was skipping the local disk, and directly downloading in NAS, as I was trying that solution, I observed that each 10 sec more or less, transmission thin client was getting freezed, and when loading back again, all downloadings were not downloading. All of them started quickly enough, but that was not the problem, something was hapenning, and as I observed before, the mono thread issue was the problem. I started checking traffic in and out, and saw that when it was downloading only traffic in was shown and little out, and when transmission was getting freezed, a lot of traffic out was being registered, so I guess, that at that moment, the same thing was ocurring, transmission was copying cached files from the downloads into NAS, and stopping the downloads of the files, while the copy was being made.

Has anyone experienced this problem before, or if it can be fixed?

Kind regards

**Comment by skewty** [comment] 2020-02-15 05:18
Sounds like Python GIL is the issue here (but I have not read the code).

Perhaps file writing should be written using the `multiprocessing` module.
https://docs.python.org/3.5/library/multiprocessing.html

**Comment by ckerr** [comment] 2020-04-30 22:19
> So I started downloading in NAS, and saw some behavieurs that I really do not like from it. So at the first beginning I thought on downloading first on an individual disk, and once the download was completed, tranmission should move it to a NAS folder, this ended up terribly bad, each time a download finished, transmission started to move from local to NAS through NFS the file, but at the same time, it was freezed for the rest of the downloads, so I guess that tranmission only works as mono thread process.

This is a duplicate of #108

**Closed by ckerr** 2020-04-30 22:19 UTC
