### ISSUE TITLE
nothing happens after verify torrent

### ISSUE THREAD

**Issue by RainerZufall187** [transmission/transmission#6064] opened 2023-10-02 14:51 UTC
### What is the issue?

im seeding a torrent, modified one file then wanted to test verify local data then it says verifying local data and continues seeding. and the file still got my modification

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Transmission 4.0.4 (24077e3511)

**Comment by Coeur** [comment] 2023-10-02 19:31
While it's an undesired outcome, it's possible that the present implementation of data verification is limited to what is assumed to be "downloaded data": once a file has been verified, it will be marked as such and won't be further verified. So subsequent corruption on disk is a vector of data corruption that may not be properly supported: but if you have a disk that corrupts data, fixing that data won't save it from being corrupted again an hour later... your disk may be mostly good for the chimney during next atomic winter.

Anyway, while I haven't verified if above is the actual implementation or just a bug, a "force re-verification" may be a nice feature.

**Comment by killemov** [comment] 2023-10-03 08:47
So you have all the content of a torrent. You modify the content. You verify the torrent content. The modification goes unnoticed. Strange.

**Comment by tearfur** [comment] 2023-10-03 12:41
@RainerZufall187 I can't reproduce it. If you have a public domain torrent where this happens, please share it here and tell us which file to modify.

**Comment by killemov** [comment] 2023-10-04 07:12
@RainerZufall187 Could it be that the UI (status) wasn't updated during checking and downloading?

**Closed as completed** 2023-12-15 19:36 UTC
Labels: needs clarification, needs testers
