### ISSUE TITLE
Documentation: How to share my own files

### ISSUE THREAD

**Issue by HiranChaudhuri** [transmission/transmission#2117] opened 2021-11-08 06:51 UTC
It seems the use case of sharing your own files is not documented in transmission.
For a Peer-to-Peer file sharing network this usecase should not be neglected.

Could someone please add a few lines, even if it is a copy of the solution I found in https://github.com/transmission/transmission/discussions/2109 ?

**Comment by Pentaphon** [comment] 2021-11-09 03:52
Torrent clients are meant for mass file sharing with lots people you don't necessarily know. It takes a bit of tweaking to make a torrent client share your file to a specific person privately. The directions given in this forum post will let you do that. 

https://forum.transmissionbt.com/viewtopic.php?t=14644

Otherwise, it's easier to do what you want with an open source browser-based service like https://file.pizza/

Or you can use an open source software like https://syncthing.net/

**Comment by HiranChaudhuri** [comment] 2021-11-09 06:40
Torrent clients are meant for mass sharing? That is what I want. 
Sharing with just one individual is what you made up yourself.

File-Pizza is definitely not what I want. I do not intend to keep my browser open until a 2 GB file has left my network.
Syncthing might work, but again: I want to use Bittorrent to share files that I created.

Imagine that I created some big files. Now I want to share those with whomever might be interested. So sharing with lots of people whom I do not know is absolutely ok for me. I know I am trying to use P2P file sharing in a rare legal usecase. But it is more puzzling that such a usecase is not even documented.

And somehow I do not want to believe that Transmission is a Bittorrent client meant to only share other people's files. In that case I will definitely have to seek for other Bittorrent clients. Yet my request is to improve the documentation. So you could state this view in the docs and others do not have to spend time searching.

**Comment by Pentaphon** [comment] 2021-11-09 07:09
My mistake. I thought it was obvious from the thousands of tutorials online that show you how to use a torrent client, which all work the same way. It doesn't matter what client you use. You will be confused until you understand how to use a torrent client. Try this guide. 

https://www.morehawes.co.uk/bittorrent-transmission

**Comment by ckerr** [comment] 2021-11-09 15:05
Duplicate of https://github.com/transmission/transmission/discussions/2109

**Closed by ckerr** 2021-11-09 15:05 UTC

**Comment by HiranChaudhuri** [comment] 2021-11-09 20:15
I checked the guide you pointed me to. It describes exactly what I tried to do on the web interface but it did not work.
At least now I know there must be a bug in the web interface.

Check the fine documentation on the web interface - it is rather poor: https://github.com/transmission/transmission/wiki/Web-Interface
Have you ever tried to create a torrent on it? I get the feeling you rather close this issue than improve or test the documentation.

**Comment by Pentaphon** [comment] 2021-11-10 01:57
> It describes exactly what I tried to do on the web interface

The web UI doesn't do that. No web UI does that. You need the CLI or GUI to do that.

**Comment by HiranChaudhuri** [comment] 2021-11-10 06:11
I totally agree.

Now would that not be worth a little statement in the documentation? For you it is obvious. Not so for novice users.

**Comment by Pentaphon** [comment] 2021-11-10 09:20
> 
> 
> I totally agree.
> 
> Now would that not be worth a little statement in the documentation? For you it is obvious. Not so for novice users.

It's obvious to everybody except you. A web UI is just a control layer to direct and send files to software over a network. You need the software itself to create torrent files.

**Comment by ckerr** [comment] 2022-02-14 20:35
@Pentaphon this is unnecessarily hostile. Everyone starts off as a beginner.

**Comment by GScottElshaw** [comment] 2022-02-15 00:20
Obviously not overnight, but incrementally, I want to have a thorough look at stuff like the various wiki documents, tutorials, and any other piece of information that can help everyone from beginners to advanced users. I am an advanced *Apple* (1983 - ) and *Web* user, but I am still coming across behaviours or concepts and language using BT that appear to be almost a new vernacular.

**Comment by HiranChaudhuri** [comment] 2022-02-17 10:52
> > @Pentaphon this is unnecessarily hostile. Everyone starts off as a beginner.
> 
> Sorry but this is out of the scope of an issue tracker. I pointed him to the relevant post in the forum, and I pointed him to 3rd party tutorials. Moreover, there's not a single client that includes this kind of tutorial in their documentation because that process is kind of a workaround than normal usage of a torrent client and his use case is better served by other projects like syncthing which I also linked him to. I don't know how much more helpful I can be and now he's demanding somebody write something on the documentation he can already find elsewhere. It's a bit much.

Yes, you pointed me to syncthing. And looking at https://syncthing.net/ I see
_Syncthing is a continuous file synchronization program. It synchronizes files between two or more computers in real time, safely protected from prying eyes._

This is not my usecase. I wanted to publish a file - make it available for the public just like so many other files are already available. I was able to solve this using transmission but it was a path to get there.
Now if you believe all this is rightfully searched elsewhere, just put  up a wiki page with excerpts from this thread so other users can more easily find their way. Cut and paste is not really much, at least on my side.

However proceed as you like. I second the opinion that your reaction was not really polite. My problem is solved. Live and let live...
