### ISSUE TITLE
Transmission 3.00 stuck downloading torrent with high CPU usage

### ISSUE THREAD

**Issue by VadimMuhtarov** [transmission/transmission#3162] opened 2022-05-31 07:19 UTC
Today I tried to download torrent and after 99.77% it stuck with connected pears and 0 download speed. Upload worked and CPU usage was up to 100%. Tried to stop/resume, no changes, only Transmission restart helped. Sample of it in the attachment
[Sample of Transmission.txt](https://github.com/transmission/transmission/files/8802927/Sample.of.Transmission.txt)

macOS 10.15.7, Transmission 3.00 (f4489c982e), SSD

**Comment by VadimMuhtarov** [comment] 2022-05-31 15:37
There are no messages from that time, only new

**Comment by ckerr** [comment] 2022-05-31 15:41
f4489c9 is over 1000 commits old (4.0.0-beta.1 coming sometime in June / July).

@VadimMuhtarov any chance you could try a nightly build from https://transmissionbt.com/ and see how that goes?

**Comment by VadimMuhtarov** [comment] 2022-05-31 15:49
I'll try, hope it will be released soon also

**Comment by ckerr** [comment] 2022-06-04 15:16
Closing as a duplicate of #3111

**Closed by ckerr** 2022-06-04 15:16 UTC
Labels: bug, needs clarification
