### ISSUE TITLE
No bandwidth limits work

### ISSUE THREAD

**Issue by jbarlov** [transmission/transmission#6533] opened 2024-01-17 02:33 UTC
### What is the issue?

The Global Bandwidth limit or the separate item download speed limit do not activate when the box is ticked.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.5

**Comment by tearfur** [comment] 2024-01-17 03:53
Duplicate of #6361.

**Closed by tearfur** 2024-01-17 03:53 UTC
