### ISSUE TITLE
Transmission ignores empty (zero-byte) files

### ISSUE THREAD

**Issue by point-source** [transmission/transmission#1077] opened 2019-12-13 23:14 UTC
When a zero-byte file exists in a torrent, transmission shows the file as being part of the torrent but does not create the file on disk. 

Although it is quite possible to argue that there (in most cases) is no point to a zero-byte file, it seems to me that the purpose of a torrent client is to reproduce the file/data state as accurately as possible in accordance with the torrent file.

**Comment by ckerr** [comment] 2022-01-25 21:55
Duplicate of https://github.com/transmission/transmission/issues/417

**Closed** 2022-02-11 06:51 UTC
Labels: duplicate
