### ISSUE TITLE
Speed Limit Mode does not work 

### ISSUE THREAD

**Issue by ishanoval** [transmission/transmission#4926] opened 2023-02-17 14:23 UTC
Hey there, 

Thanks for the fantastic app, first of all. 
I updated the app a few days ago and the speed limit mode stopped working properly. 
It downloads at a regular speed even if the limiter is enabled. 

<img width="689" alt="Screen Shot 2023-02-17 at 7 19 36 PM" src="https://user-images.githubusercontent.com/4179047/219680656-0a217f21-1c08-4559-9aed-91cefa5f31cc.png">

**Comment by ckerr** [comment] 2023-02-17 18:25
Hi @ishanoval, I think this is a duplicate of https://github.com/transmission/transmission/issues/4701 so I'm going to close this as a dupe, but thanks for reporting this!

I'd rather have a bug get duplicate reports than to go unreported smile_cat

**Closed by ckerr** 2023-02-17 18:25 UTC
