### ISSUE TITLE
Info panel  - can be illegible, words overwrite themselves, etc.  (also, can't be resized)

### ISSUE THREAD

**Issue by winbatch** [transmission/transmission#5304] opened 2023-03-26 15:35 UTC
When there is an ip6 address things look funky.  Also the headers don't seem to always line up with the detail.  Is 'Done' and 'Status' supposed to be one column or two?  Is the data of 'TDE', etc. supposed to be a flags column?
![image](https://user-images.githubusercontent.com/2419795/227786473-590beb60-841a-4638-8f40-138afce63eb1.png)

**Comment by ckerr** [comment] 2023-03-27 02:21
Duplicate of https://github.com/transmission/transmission/pull/5249, I think

**Comment by ckerr** [comment] 2023-03-27 02:23
Wrong link; https://github.com/transmission/transmission/issues/4209 is the one I was looking for.

**Closed by ckerr** 2023-03-27 02:23 UTC
