### ISSUE TITLE
Build fails when configured with `-DENABLE_WEB=ON`

### ISSUE THREAD

**Issue by belovachap** [transmission/transmission#4088] opened 2022-11-03 17:19 UTC
### What is the issue?

I was looking into https://github.com/transmission/transmission/issues/4087 and found out that you can pass `-DENABLE_WEB=ON` and the build will actually try to use `yarn` to generate the `transmission-app.js`. I wonder if this is related to https://github.com/transmission/transmission/pull/4061 in some way.

Any way, here's what I'm running into at the moment if someone else can replicate it:

```
chapman@chapman-Alienware-Aurora-Ryzen-Edition:~/code/transmission/build$ make
[  2%] Built target event
[  4%] Built target natpmp
[  6%] Built target miniupnpc
[  8%] Built target dht
[ 10%] Built target psl
[ 12%] Built target utp
[ 13%] Built target b64
[ 14%] Built target gtestall
[ 33%] Built target transmission
[ 33%] Built target subprocess-test
[ 45%] Built target libtransmission-test
[ 66%] Built target transmission-gtk-po
[ 67%] Built target transmission-daemon
[ 75%] Built target transmission-gtk
[ 76%] Automatic MOC for target transmission-qt
[ 76%] Built target transmission-qt_autogen
[ 99%] Built target transmission-qt
[ 99%] Built target transmission-create
[ 99%] Built target transmission-edit
[ 99%] Built target transmission-remote
[100%] Built target transmission-show
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.36s.
yarn run v1.22.19
$ /home/chapman/code/transmission/build/web/node_modules/.bin/webpack --config /home/chapman/code/transmission/web/webpack.config.js --context /home/chapman/code/transmission/web
[webpack-cli] Failed to load '/home/chapman/code/transmission/web/webpack.config.js' config
[webpack-cli] Error: Cannot find module 'mini-css-extract-plugin'
Require stack:
- /home/chapman/code/transmission/web/webpack.config.js
- /home/chapman/code/transmission/build/web/node_modules/webpack-cli/lib/webpack-cli.js
- /home/chapman/code/transmission/build/web/node_modules/webpack-cli/lib/bootstrap.js
- /home/chapman/code/transmission/build/web/node_modules/webpack-cli/bin/cli.js
- /home/chapman/code/transmission/build/web/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/chapman/code/transmission/web/webpack.config.js:3:30)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/chapman/code/transmission/web/webpack.config.js',
    '/home/chapman/code/transmission/build/web/node_modules/webpack-cli/lib/webpack-cli.js',
    '/home/chapman/code/transmission/build/web/node_modules/webpack-cli/lib/bootstrap.js',
    '/home/chapman/code/transmission/build/web/node_modules/webpack-cli/bin/cli.js',
    '/home/chapman/code/transmission/build/web/node_modules/webpack/bin/webpack.js'
  ]
}
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make[2]: *** [web/CMakeFiles/trweb.dir/build.make:93: web/CMakeFiles/trweb] Error 2
make[1]: *** [CMakeFiles/Makefile2:1637: web/CMakeFiles/trweb.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

### Which application of Transmission?

Web client

### Which version of Transmission?

8857e8c1a492467ff23bb533851a8b870b10f540

**Comment by templarundead** [comment] 2022-11-03 17:37
Add this line: COMMAND ${CMAKE_COMMAND} -E create_symlink "${CMAKE_CURRENT_BINARY_DIR}/node_modules" "${CMAKE_CURRENT_SOURCE_DIR}/node_modules" to Cmakelists.txt file in web folder

**Comment by t-8ch** [comment] 2022-12-30 00:35
Seems to be a duplicate of #4019

**Comment by ckerr** [comment] 2022-12-31 17:01
Agreed; closing a s duplicate of #4019

**Closed by ckerr** 2022-12-31 17:01 UTC
Labels: type:build
