### ISSUE TITLE
Literal "Hide taskbar" remains unchanged each time you click on it

### ISSUE THREAD

**Issue by simonbcn** [transmission/transmission#6136] opened 2023-10-20 10:00 UTC
### What is the issue?

When I click on the menu option `View` > `Hide taskbar` it works correctly, but it does not change the literal from `Hide` to `Show` ever. At least not in the Spanish menu.

![Captura de pantalla 2023-10-20 a las 11 56 17](https://github.com/transmission/transmission/assets/428231/9ec922d6-2748-40a2-b387-0c0a71fabab9)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.4

**Comment by Coeur** [comment] 2023-11-04 04:40
Duplicate of #4419.
It was fixed in Transmission 4.1.0

**Closed by Coeur** 2023-11-04 04:40 UTC
Labels: bug, scope:mac, needs confirmation
