### ISSUE TITLE
After completing "Set Location", you need to "Start" the torrent.

### ISSUE THREAD

**Issue by slrslr** [transmission/transmission#1344] opened 2020-06-29 07:50 UTC
Transmission 3.00+ (somenumber: what is it? is it privacy risk to disclose?)
Windows 10 64bit

Happened numerous times that i set to change location of the torrent payload. But the location stay the same with torrent saying "Error: No data found! Ensure your drives are connected or use "Set Location". To re-download, remove the torrent and re-add it."

Stopping, starting, verifying local data not help. Have to delete/add torrent.

**Comment by slrslr** [comment] 2021-10-30 07:55
OP is no longer using Windows, so unsubscribing. Now running qBittorrent alpha and have no significant issues with it, can recommend.

**Comment by contrapunctus-1** [comment] 2021-11-29 18:00
Facing the same issue with Transmission 3.00 (bb6b5a062e) on Debian Testing.

**Comment by NautilusChan** [comment] 2022-01-18 02:09
Is there a better solution?
Same issue withe Transmission 3.00 on OpenWRT.

**Comment by contrapunctus-1** [comment] 2022-01-18 12:27
I found the "issue" later (thought I wrote about it here...apparently not). After completing "Set Location", you need to "Start" the torrent. Technically it's user error, but I see an opportunity to improve UX - when the "Set Location" has completed, I'd suggest -

**Comment by ckerr** [comment] 2022-01-27 04:36
I think this is a duplicate of #83

**Closed by ckerr** 2022-01-27 04:36 UTC
Labels: enhancement
