### ISSUE TITLE
"IPv4 DHT announce failed" flooding syslog

### ISSUE THREAD

**Issue by sergserg2** [transmission/transmission#1059] opened 2019-11-21 10:17 UTC
This is old issue, like here: https://github.com/transmission/transmission/issues/564

> "dht_search
> 
> This schedules a search for information about the info-hash specified in
> id; it returns 1 if this is a new search, and 0 if it merely reset the
> timeouts for a search in progress."

If above 0 is not error, then can be info message instead error:

```c
--- libtransmission/tr-dht.c.orig       2019-11-21 11:02:23.189834110 +0100
+++ libtransmission/tr-dht.c    2019-11-21 04:49:45.998280846 +0100
@@ -732,6 +732,11 @@

             ret = 1;
         }
+       else if (rc == 0)
+       {
+            tr_logAddTorInfo(tor, "%s DHT announce failed (%s, %d nodes): %s", af == AF_INET6 ? "IPv6" : "IPv4",
+                tr_dhtPrintableStatus(status), numnodes, tr_strerror(errno));
+       }
         else
         {
             tr_logAddTorErr(tor, "%s DHT announce failed (%s, %d nodes): %s", af == AF_INET6 ? "IPv6" : "IPv4",
```

**Comment by G4Zz0L1** [comment] 2020-05-28 18:19
Yep, it's going on also with the new 3.00

**Comment by rezad1393** [comment] 2020-06-03 22:20
I get the same error for just one torrent (and it is downloading too)
transmission-daemon[redacted]: _redacted_ IPv4 DHT announce failed (firewalled, 988 nodes): Resource temporarily unavailable (tr-dht.c:737)

**Comment by donileo** [comment] 2020-06-19 20:31
Bump. Same error.

**Comment by G4Zz0L1** [comment] 2020-07-07 15:12
Any news on that? It's really annoying to search things on syslog when you've several background service reporting something, due to the amount of transmission errors from this.

**Comment by sergserg2** [comment] 2020-07-08 10:55
Use patch in my first post above then set loglevel to info. All flood will gone.

**Comment by BachoSeven** [comment] 2020-07-18 18:23
I experience this too on 3.00

**Comment by G4Zz0L1** [comment] 2020-10-27 14:50
@sergserg2 I'm on Arch, it'll be nice to have a new version on the package manager, but I don't see any known roadmap for a new release, or I don't know where to look for it.

**Comment by somercet** [comment] 2021-01-18 14:24
Also bumping for this patch. This DHT spam always seems to be tied to specific torrents (or specific DHT peers on certain torrents, more exactly).

**Comment by shadowlmd** [comment] 2021-05-25 05:55
Any chances this issue will ever be fixed?

**Comment by ckerr** [comment] 2022-02-25 05:17
This is one piece of https://github.com/transmission/transmission/issues/1992

**Comment by ckerr** [comment] 2022-03-05 16:15
Oh wait, this logging-when-`dht_search()`-returns-0 issue is a duplicate of https://github.com/transmission/transmission/issues/564 which was fixed by https://github.com/transmission/transmission/pull/1619

**Closed by ckerr** 2022-03-05 16:15 UTC
Labels: bug, scope:core, pr welcome
