### ISSUE TITLE
When will the next stable release?

### ISSUE THREAD

**Issue by vuslatx** [transmission/transmission#3082] opened 2022-05-14 11:26 UTC
No stable version has been released since May 2020. 

When will the next stable release?

**Comment by GaryElshaw** [comment] 2022-05-14 13:18
No solid date, but the suggestion is that there will be a beta in the coming months.

**Comment by ckerr** [comment] 2022-05-14 14:08
Duplicate of https://github.com/transmission/transmission/discussions/2287

**Closed by ckerr** 2022-05-14 14:08 UTC
