### ISSUE TITLE
option to delete some files from downloaded torrent

### ISSUE THREAD

**Issue by mgorny** [transmission/transmission#1003] opened 2019-09-14 16:32 UTC
When downloading torrents with multiple files, Transmission lets me choose which files to download which is a nice. However, I'd really use an easy option to delete data from some of the previously downloaded files.

Say, my torrent has large files `1`, `2`, `3` which I use in order. I first tell Transmission to fetch `1`, then I tell it to fetch `2` and I would like to also tell it to delete `1` to free up some space.

This is currently possible externally via removing the file, then having Transmission re-verify data, then re-fetch incidentally mismatched beginning of the next file but that's obviously suboptimal.

**Comment by kevvood** [comment] 2019-09-14 18:18
Related to issue [#595](https://github.com/transmission/transmission/issues/595)

**Comment by mikedld** [comment] 2022-11-05 09:43
Looks like a duplicate of #852 to me.

**Closed** 2023-01-27 07:30 UTC
Labels: duplicate

**Comment by dechamps** [comment] 2024-09-15 16:14
[transmission_delete_unwanted](https://github.com/dechamps/transmission_delete_unwanted) is a tool that solves the OP's problem, but it sure would be nice to have the feature directly in Transmission - that would be more user-friendly and would not require the torrent to be reverified. This would require two changes:

1. Change the UI so that already downloaded files can be "unchecked" (currently the checkbox is grayed out)
2. Add a "trim unwanted files" torrent command (similar to the "verify" command) that basically implements the same logic as [transmission_delete_unwanted](https://github.com/dechamps/transmission_delete_unwanted) (minus the verification), and expose it in the UI.
   - One could also do it as soon as the file is unchecked, but that would arguably be dangerous/surprising from a user perspective.

Alternatively, it may also make sense to add a file-specific "delete" command, which would simultaneously mark the file as unwanted and delete/trim it at the same time.

> Looks like a duplicate of #852 to me.

I don't think so - #852 seems to have been clarified to something different. Can we re-open this issue please, since it's not a duplicate?

**Comment by bravely-beep** [comment] 2025-04-14 00:45
I agree this issue should be reopened; it's not a duplicate of #852, and it's a feature I'd find very useful (and which no other torrent client seems to easily support either).
