### ISSUE TITLE
macOS app fails to quit

### ISSUE THREAD

**Issue by m4l3vich** [transmission/transmission#6338] opened 2023-12-05 07:01 UTC
### What is the issue?

Sometimes, when trying to exit Transmission it acts weird: it hangs with a spinning ball, trying to force quit the app makes the window disappear, but the icon in Dock remains with "Application Not Responding" text for some more time.
Trying to open the app again results in the app icon "jumping" in Dock infinitely, and then it begins to say that it is not responding again.
Checking through htop revealed that the Transmission process is still "active", but does not use any system resources, and does not respond to any kill signals, even SIGKILL.
The only thing that helps is rebooting.

Also this time after Transmission "hanged" like this, I didn't reboot my device, but I tried to delete the file Transmission was downloading at the moment (shouldn't have done that), and it took my Finder and now I can't even access the folder with this file, any program doing this goes cursed and hangs too.

I've seen that a similar issue was reported about app hanging for a few seconds, but in my case it may be minutes (I've waited for a few minutes and force quit) and the app is going cursed after that.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.4

**Comment by yakovmanshin** [comment] 2023-12-16 22:52
Potentially related:

I normally download files to a folder on a (spinning) hard drive, and when I attempt to quit the app, it *sometimes* hangs, while the drive indicates high IO activity. The same behavior is *sometimes* observed when I pause all transfers.

In *some* of those cases, the “beach ball” disappears after a few seconds, the app reacts as expected (pauses transfers or quits), and the IO light stops its rapid blinking. In others, this continues for multiple minutes. A couple times this behavior froze and then crashed the entire system (i.e. the macOS watchdog rebooted the OS after not having received a response from the UI components).

I have witnessed this behavior in v4.0.4 *and* other 4.0.x versions. I don’t remember seeing this in v3.x.x (it might have happened, but I don’t remember). Next time something like this happens, I’ll make sure to preserve the logs.

**Comment by Coeur** [comment] 2023-12-31 14:45
>Trying to open the app again results in the app icon "jumping" in Dock infinitely, and then it begins to say that it is not responding again.

In that case, it may be a duplicate of #6359 and #6408.
Can you tell which version of macOS, and if you're on Intel or Apple Silicon? For others, it was Sonoma 14.2+ on Intel.
Can you also share a crash report when you force kill it?

**Comment by Coeur** [comment] 2024-01-12 22:39
Closing because no answers. For following an issue with similar symptoms AND a crash report, there is now #6522.

**Closed by Coeur** 2024-01-12 22:39 UTC
Labels: scope:mac
