### ISSUE TITLE
Transmission web interface scale

### ISSUE THREAD

**Issue by Petrprogs** [transmission/transmission#5564] opened 2023-05-28 20:45 UTC
### What is the issue?

The menu in the transmission web interface comes out cropped on my 14" WXGA 1366x768 laptop display. You have to zoom out the web interface page to 70% to see the menu completely

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.2

**Comment by killemov** [comment] 2023-05-29 07:41
Duplicate of #5299. But with screen limitation.

You could try and see if [Shift](https://github.com/killemov/Shift) fits better.

**Closed** 2023-07-14 15:22 UTC
