### ISSUE TITLE
Qt client crashes at random when using a remote server

### ISSUE THREAD

**Issue by Avamander** [transmission/transmission#2823] opened 2022-03-25 22:40 UTC
I can't pinpoint why exactly it crashes, but it seems that quickly navigating trough the UI seems to cause crashes more often.

Stacktrace:
```
#0  QWidget::focusPolicy (this=0xf09af3114b61412) at kernel/qwidget.cpp:7606
#1  0x00007fdeb17a977a in QLabelPrivate::needTextControl (this=0x561f012726e0) at widgets/qlabel_p.h:99
#2  QLabel::setText (this=this@entry=0x561f01241e70, text=...) at widgets/qlabel.cpp:344
#3  0x0000561f003c29bd in operator() (r=..., __closure=0x7ffdc446a580) at FreeSpaceLabel.cc:87
#4  operator() (r=..., this=0x7ffdc446a580) at RpcQueue.h:98
#5  std::__invoke_impl<QFuture<RpcResponse>, RpcQueue::normalizeFunc<FreeSpaceLabel::onTimer()::<lambda(const RpcResponse&)>, 0>::<lambda(const RpcResponseFuture&)>&, const QFuture<RpcResponse>&>
    (__f=...) at /usr/include/c++/10/bits/invoke.h:60
#6  std::__invoke_r<QFuture<RpcResponse>, RpcQueue::normalizeFunc<FreeSpaceLabel::onTimer()::<lambda(const RpcResponse&)>, 0>::<lambda(const RpcResponseFuture&)>&, const QFuture<RpcResponse>&> (
    __fn=...) at /usr/include/c++/10/bits/invoke.h:115
#7  std::_Function_handler<QFuture<RpcResponse>(const QFuture<RpcResponse>&), RpcQueue::normalizeFunc<FreeSpaceLabel::onTimer()::<lambda(const RpcResponse&)>, 0>::<lambda(const RpcResponseFuture&)> >::_M_invoke(const std::_Any_data &, const QFuture<RpcResponse> &) (__functor=..., __args#0=...) at /usr/include/c++/10/bits/std_function.h:292
#8  0x0000561f003e67ff in std::function<QFuture<RpcResponse> (QFuture<RpcResponse> const&)>::operator()(QFuture<RpcResponse> const&) const (__args#0=..., this=0x7ffdc446a580)
    at /usr/include/c++/10/bits/std_function.h:622
#9  RpcQueue::runNext (this=0x561f01811850, response=...) at RpcQueue.cc:76
#10 0x0000561f003e9f91 in RpcQueue::stepFinished (this=0x561f01811850) at RpcQueue.cc:48
#11 0x00007fdeb096da88 in doActivate<false> (sender=0x561f018118a0, signal_index=4, argv=0x7ffdc446a720) at kernel/qobject.cpp:3898
#12 0x00007fdeb0966d67 in QMetaObject::activate (sender=<optimized out>, m=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3946
#13 0x00007fdeb0753ec5 in QFutureWatcherBase::event (this=<optimized out>, event=0x561f01205b90) at thread/qfuturewatcher.cpp:334
#14 0x00007fdeb16696b3 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x561f018118a0, e=0x561f01205b90) at kernel/qapplication.cpp:3632
#15 0x00007fdeb093616a in QCoreApplication::notifyInternal2 (receiver=0x561f018118a0, event=0x561f01205b90) at kernel/qcoreapplication.cpp:1063
#16 0x00007fdeb0939257 in QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, data=0x561f006ee910) at kernel/qcoreapplication.cpp:1817
#17 0x00007fdeb098fef7 in postEventSourceDispatch (s=0x561f00838640) at kernel/qeventdispatcher_glib.cpp:277
#18 0x00007fdeaf62dc9b in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007fdeaf682248 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007fdeaf62b353 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007fdeb098f548 in QEventDispatcherGlib::processEvents (this=0x561f0083f540, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#22 0x00007fdeb0934a9b in QEventLoop::exec (this=this@entry=0x7ffdc446ab00, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#23 0x00007fdeb093d024 in QCoreApplication::exec () at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#24 0x00007fdeb0f55d10 in QGuiApplication::exec () at kernel/qguiapplication.cpp:1867
#25 0x00007fdeb1669629 in QApplication::exec () at kernel/qapplication.cpp:2824
#26 0x0000561f00399058 in main (argc=<optimized out>, argv=<optimized out>) at Application.cc:649
```

Version: `transmission-qt 3.00 (bb6b5a062e)` (Ubuntu)

**Comment by ckerr** [comment] 2022-03-26 01:49
Hi @Avamander, thanks for reporting this.

Happily this is fixed in the [nightly builds](https://transmissionbt.com/download) by #1604.

I'm closing this issue as a duplicate of #1510.

**Closed by ckerr** 2022-03-26 01:49 UTC
