### ISSUE TITLE
Everything changed and is broken since latest update.

### ISSUE THREAD

**Issue by NolanSyKinsley** [transmission/transmission#5415] opened 2023-04-18 12:22 UTC
### What is the issue?

IDK if this is an issue with my distro(Manjaro) or Transmission itself, but my latest system update Transmission really, really changed and is all broken. Transmission used to follow my system theme, which is a dark theme, now it is blinding white. The folder selector when I started a torrent used to be a drop down menu of previous folders, now I have to manually navigate to the folder every. Single. Time.

And when I say broken, I really do mean broken. The first time I start transmission up it seems fine, but if I close it and start it again, all I get is a title bar, the rest of the app refuses to render. I move my mouse and tooltips appear like the app is actually there, but all I see is my desktop. I tried starting it in a terminal to see what errors happen, but nothing, the app seems to think everything is A-OK and prints no errors despite not displaying anything.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.2 (2a57b17031)

**Comment by ckerr** [comment] 2023-04-20 19:21
Duplicate of https://github.com/transmission/transmission/discussions/5140

**Closed by ckerr** 2023-04-20 19:21 UTC
