### ISSUE TITLE
Transmission continues to show removed magnetized transfer on each launch

### ISSUE THREAD

**Issue by mythrowawayemail18** [transmission/transmission#5050] opened 2023-02-25 16:55 UTC
### What is the issue?

1. I updated from a 3.x version of Transmission to 4.0.1 (e1c6e1be43)
2. Upon launch of Transmission, there was a magnetized transfer in the list that wasn't there previously
3. I used command + delete to remove it
4. Quit the app and relaunch the app

The magnetized transfer has returned.

I tried remove from list and trash data file - issue still persists.

I have this stuck file that I cannot get rid of and the issue only started once updating to e1c6e1be43

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1 (e1c6e1be43)

**Comment by smartarts1** [comment] 2023-02-25 22:12
same here - when I first installed the update I had about 200 old torrents appeared - I had to delete them all and most are now gone (including stuff that was half downloaded!!)
but now every time I launch I get the same 7 red files - they were successfully downloaded a long time ago

**Comment by ckerr** [comment] 2023-02-26 01:08
Hey @mythrowawayemail18 this appears to be a duplicate of #5053 so I'm going to close this one as a dupe.

Technically this one was reported first but I saw that one first and already responded there so ...  please subscribe to that one and take a look at the questions I asked there :heart:

**Closed by ckerr** 2023-02-26 01:08 UTC
