### ISSUE TITLE
Transmission randomly rearranges torrents when closed/reopened

### ISSUE THREAD

**Issue by 11plustwo** [transmission/transmission#6974] opened 2024-07-04 19:59 UTC
### What is the issue?

Torrents don't maintain order when Transmission is closed and reopened. The new order seems random. It's not alphabetical. If there is an order, I can't figure it out. Regardless I would prefer if the torrents opened in the same order.

I'm on Transmission version 4.0.6 and MacOS Ventura 13.6.7

Here's a video:
https://www.youtube.com/watch?v=ZQ98Q6GDb8E

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.6

**Comment by tearfur** [comment] 2024-07-05 01:15
Duplicate of #155.

**Closed by tearfur** 2024-07-05 01:15 UTC
