### ISSUE TITLE
web interface's peer list is garbled (due to too long (?) ipv6 addresses?)

### ISSUE THREAD

**Issue by sanderjo** [transmission/transmission#7205] opened 2024-10-27 20:28 UTC
### What is the issue?

The peers list in the web interfaces is garbled. See pic.

The Status column is too small, and status info is overwritten onto the Address info

Transmission 4.0.5 on Ubuntu 24.04
EDIT: also in git version Transmission 4.1.0-dev

![image](https://github.com/user-attachments/assets/fc292547-8daf-4beb-8c6a-7521bc3894aa)

### Which application of Transmission?

Web client

### Which version of Transmission?

 Transmission 4.0.5
Transmission 4.1.0-dev

**Comment by tearfur** [comment] 2024-10-30 09:23
Duplicate of #4209

**Closed by tearfur** 2024-10-30 09:23 UTC
