### ISSUE TITLE
[2.92 x64 daemon W8.1] Daemon crashes repeatedly trying to start torrent

### ISSUE THREAD

**Issue by Tharn** [transmission/transmission#147] opened 2017-01-16 16:42 UTC
Hi,

I don't know why it does this. The torrent should be fine. I can't post it here unfortunately, but I can give you some Error Logs. The torrent shows up with a proper .torrent and .resume file, as well as a download folder. Every time, it starts to download with full speed, gets to 1 or 2% and then crashes the daemon.

Got a couple of these if you need more than one pair. They all point at the same exception offset though.

```
Faulting application name: transmission-daemon.exe, version: 2.92.0.0, time stamp: 0x56e41ee1
Faulting module name: transmission-daemon.exe, version: 2.92.0.0, time stamp: 0x56e41ee1
Exception code: 0xc0000005
Fault offset: 0x000000000000ee56
Faulting process id: 0x8bc
Faulting application start time: 0x01d270163b4eeae7
Faulting application path: C:\Program Files\Transmission\transmission-daemon.exe
Faulting module path: C:\Program Files\Transmission\transmission-daemon.exe
Report Id: add7cab5-dc09-11e6-8274-00248c414a93
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Version=1
EventType=APPCRASH
EventTime=131290580821095717
ReportType=2
Consent=1
ReportIdentifier=add7cab6-dc09-11e6-8274-00248c414a93
IntegratorReportIdentifier=add7cab5-dc09-11e6-8274-00248c414a93
NsAppName=transmission-daemon.exe
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=transmission-daemon.exe
Sig[1].Name=Application Version
Sig[1].Value=2.92.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=56e41ee1
Sig[3].Name=Fault Module Name
Sig[3].Value=transmission-daemon.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=2.92.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=56e41ee1
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=000000000000ee56
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.3.9600.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1031
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=89ba
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=89bad5bab94522467381c3941ada61ba
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=9ed4
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=9ed4605c2c671af286447737f9a76d48
UI[2]=C:\Program Files\Transmission\transmission-daemon.exe
UI[3]=Transmission Daemon has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution (recommended)
UI[6]=Check for a solution later (recommended)
UI[7]=Close
UI[8]=Transmission Daemon stopped working and was closed
UI[9]=A problem caused the application to stop working correctly. Windows will notify you if a solution is available.
UI[10]=&Close
LoadedModule[0]=C:\Program Files\Transmission\transmission-daemon.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Program Files\Transmission\zlib.dll
LoadedModule[5]=C:\Program Files\Transmission\LIBEAY32.dll
LoadedModule[6]=C:\Program Files\Transmission\libcurl.dll
LoadedModule[7]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[8]=C:\Windows\system32\WS2_32.dll
LoadedModule[9]=C:\Windows\system32\SHELL32.dll
LoadedModule[10]=C:\Windows\system32\ole32.dll
LoadedModule[11]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[12]=C:\Windows\SYSTEM32\VCRUNTIME140.dll
LoadedModule[13]=C:\Windows\SYSTEM32\api-ms-win-crt-runtime-l1-1-0.dll
LoadedModule[14]=C:\Windows\SYSTEM32\api-ms-win-crt-stdio-l1-1-0.dll
LoadedModule[15]=C:\Windows\SYSTEM32\api-ms-win-crt-convert-l1-1-0.dll
LoadedModule[16]=C:\Windows\SYSTEM32\api-ms-win-crt-string-l1-1-0.dll
LoadedModule[17]=C:\Windows\SYSTEM32\api-ms-win-crt-utility-l1-1-0.dll
LoadedModule[18]=C:\Windows\SYSTEM32\api-ms-win-crt-time-l1-1-0.dll
LoadedModule[19]=C:\Windows\SYSTEM32\api-ms-win-crt-locale-l1-1-0.dll
LoadedModule[20]=C:\Windows\SYSTEM32\api-ms-win-crt-heap-l1-1-0.dll
LoadedModule[21]=C:\Windows\SYSTEM32\api-ms-win-crt-math-l1-1-0.dll
LoadedModule[22]=C:\Windows\SYSTEM32\api-ms-win-crt-environment-l1-1-0.dll
LoadedModule[23]=C:\Windows\SYSTEM32\api-ms-win-crt-filesystem-l1-1-0.dll
LoadedModule[24]=C:\Windows\system32\GDI32.dll
LoadedModule[25]=C:\Windows\system32\USER32.dll
LoadedModule[26]=C:\Windows\SYSTEM32\api-ms-win-crt-conio-l1-1-0.dll
LoadedModule[27]=C:\Program Files\Transmission\SSLEAY32.dll
LoadedModule[28]=C:\Windows\system32\NSI.dll
LoadedModule[29]=C:\Windows\SYSTEM32\WINNSI.DLL
LoadedModule[30]=C:\Windows\system32\RPCRT4.dll
LoadedModule[31]=C:\Windows\system32\msvcrt.dll
LoadedModule[32]=C:\Windows\SYSTEM32\combase.dll
LoadedModule[33]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[34]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[35]=C:\Windows\SYSTEM32\ucrtbase.DLL
LoadedModule[36]=C:\Windows\system32\SspiCli.dll
LoadedModule[37]=C:\Windows\SYSTEM32\CRYPTBASE.DLL
LoadedModule[38]=C:\Windows\SYSTEM32\bcryptPrimitives.dll
LoadedModule[39]=C:\Windows\SYSTEM32\shcore.dll
LoadedModule[40]=C:\Windows\SYSTEM32\profapi.dll
LoadedModule[41]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[42]=C:\Windows\system32\mswsock.dll
LoadedModule[43]=C:\Windows\SYSTEM32\CRYPTSP.dll
LoadedModule[44]=C:\Windows\system32\rsaenh.dll
LoadedModule[45]=C:\Windows\SYSTEM32\bcrypt.dll
LoadedModule[46]=C:\Windows\SYSTEM32\DNSAPI.dll
LoadedModule[47]=C:\Windows\SYSTEM32\dhcpcsvc6.DLL
LoadedModule[48]=C:\Windows\SYSTEM32\dhcpcsvc.DLL
LoadedModule[49]=C:\Windows\System32\rasadhlp.dll
LoadedModule[50]=C:\Windows\System32\fwpuclnt.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=Transmission Daemon
AppPath=C:\Program Files\Transmission\transmission-daemon.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=E2F9AAE21032559B136A0F818E6D3532
```

**Comment by mikedld** [comment] 2017-01-16 17:40
Not sure if this will help me, but try generating a minidump with [procdump](https://live.sysinternals.com/procdump64.exe) sysinternals utility ([read more](https://technet.microsoft.com/en-us/sysinternals/dd996900.aspx) about it). You'll need to run it as something like:

    procdump64 -w -e 1 transmission-daemon

Note that I've intentionally omitted arguments such as `-ma` or `-mp` to skip dumping of process memory which would otherwise not only increase the dump file size but also cause it to potentially include information related to specific torrents you're running (and I don't need that).

Also please tell which exact version you are using. If not sure, run

    transmission-daemon --version

**Comment by Tharn** [comment] 2017-01-16 17:51
Version is 2.92 (14714) 64-bit. I run only the daemon and access it with Transmission Remote GUI.
Here you go. Sorry about the shitty host, Github won't let me upload .zips.

http://www.filedropper.com/transmission-daemonexe170116184647

**Comment by Tharn** [comment] 2017-01-16 20:52
Hmm.. again, it could be a special character issue. Looking at the file list, there's a file in it with these characters: Ó Î Ï À Í ø

**Comment by mikedld** [comment] 2017-01-16 23:46
Thanks for the dump. It looks like this crash has already been fixed (in 91f8ceb20dd39010d173de5b763fd8a736be39aa, and I've extended it a bit just now with 67bda2dcb83f127b8403d3379e2ec6927d2a7631), a while after 2.92 (14714) release. It won't crash, but won't download much either; should write offending file name to the log though (which is not saved on disk by default, sorry). If you follow answers on [ServerFault](http://serverfault.com/questions/143367/how-to-start-a-service-with-certain-start-parameters-on-windows) (or elsewhere), you should be able to pass the daemon arguments to enable it, e.g. `--log-debug --logfile c:\temp\daemon.log`.

Test build you could try: [transmission-2.92+-r67bda2dcb8-x64.msi](http://mikedld.com/f/transmission/transmission-2.92%2B-r67bda2dcb8-x64.msi)

**Comment by Tharn** [comment] 2017-01-17 19:49
I appreciate your help. Can't use the test build on my main machine unfortunately, as a lot of trackers use restrictive whitelists. But I'll see about testing it soon.

**Comment by mikedld** [comment] 2017-01-17 21:37
Closing now. Please reopen if the crash is reproduced with the build provided.

**Closed by mikedld** 2017-01-17 21:37 UTC

**Comment by neocrivi** [comment] 2017-11-01 22:38
Same problem with latest version in gihub...
I try "transmission-2.92+-r67bda2dcb8-x64.msi" and working perfect! 
Thanks for all your work!  
Thanks for make the perfect client for torrent!
