### ISSUE TITLE
Add support for the distribution of the torrent  WebTorrent JS client.

### ISSUE THREAD

**Issue by korenevskiy** [transmission/transmission#1717] opened 2021-05-31 22:55 UTC
Please support for the distribution of the torrent  WebTorrent JS client.
I create a distribution and insert it into the https://instant.io/.
I can't create a torrent and insert a JS WebTorrent Player into my site and other users site.
Since Transmission does not distribute videos in JS to the site.
I want to write a module for CMS Joomla, so that users of CMS Joomla can host a video player on their site. But Transmission does not distribute the file there.
Please add support for file distribution to support JS clients. Transmission requires more than just support for a new protocol. Transmission requires support for distributing videos to sites and may support the distribution of data from other images, for example, on the sites of various companies, it will be possible to place a link to ISO images, without the support of third-party clients.

**Comment by korenevskiy** [comment] 2021-06-01 08:28
thanks to this feature, transmission will not have competition for distributing branded software in companies.

**Comment by ckerr** [comment] 2022-02-22 18:53
I am still not understanding this request. Transmission can open peer connections with both TCP and UDP, so If "JS Torrent" is a TCP-based BitTorrent client, Transmission should already be able to communicate with it.

**Comment by korenevskiy** [comment] 2022-03-01 00:00
> I am still not understanding this request. Transmission can open peer connections with both TCP and UDP, so If "JS Torrent" is a TCP-based BitTorrent client, Transmission should already be able to communicate with it.



The JS client is not compatible with the BitTorrent client. If I knew exactly the reason for the incompatibility, I would specify the code and functions in the library. But I know for sure, the mentors of the JS torrent library report that the incompatibility is due to a JS restriction or browser restrictions. Browsers have a security system, they block packages from third-party resources, but I don't understand this. We can recall an example of browsers blocking JS downloads from a third-party domain. 
[Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/ru/docs/Web/HTTP/CORS)
Please understand that the browser code is very limited, since 90% of browser extensions and libraries send personal data to the JS programmer. As a result, I personally know that WebTorrent on JS will not be able to download the distribution file from your client. You can't understand my request?, Have you checked Web Torrent personally at work? Try to check the compatibility of your client and JS! I recently ran into a problem. I created a website with the address https://www.mysite.ru, and then connected the font to it at https://mysite.ru . Even though there is a redirection from www to non-www on the server. The browser has blocked the font on the site anyway.

**Comment by noahtkeller** [comment] 2022-03-24 16:05
I believe this request is to support "web peers", or peers using WebRTC protocol.

https://webtorrent.io/

WebTorrent library can be used in the browser to talk to tracker, connect to peers, and download data right in the browser. This enables web developers to add video players on their websites that are powered by torrents.

https://ferrolho.github.io/magnet-player/

Due to the limitations of the browser, the web torrent clients talk to trackers  over websockets, and peers over WebRTC.

https://github.com/webtorrent/instant.io/issues/52

```
The peers returned from the websocket tracker are fundamentally different than those for normal bittorrent. Normal bittorrent returns "ip:port" addresses. The websocket tracker returns webrtc offer/answers. It's a bit more complicated :)
...
Right now it's just the code, but it's quite simple. It's very similar to the current tracker spec, but with a few changes to accommodate webrtc
```

https://wiki.vuze.com/w/WebTorrent#Implementation

I don't know much about this type of development, so I can't offer many more details, but the basic requirements of this would be for Transmission to support Websockets (to talk to trackers for webrtc peers) and WebRTC (to talk to the peers themselves)

**Comment by korenevskiy** [comment] 2022-03-29 10:58
The possibility of making the WebTorrent and Bittorrent networks compatible is discussed [here](https://github.com/arvidn/libtorrent/pull/4123) https://github.com/arvidn/libtorrent/pull/4123. As soon as this problem is solved. You will be able to use this library

**Comment by bmwalters** [comment] 2022-04-03 22:18
Duplicate of #47?

**Comment by korenevskiy** [comment] 2022-04-05 10:30
> Duplicate of #47?

Yes

**Closed** 2022-04-06 06:12 UTC
Labels: duplicate
