### ISSUE TITLE
Transmission 4.0.6 is now banned due to bugs in this version. Please either downgrade to 4.0.5 ,please fix next release .

### ISSUE THREAD

**Issue by mmmmm-sbi** [transmission/transmission#7083] opened 2024-08-27 20:43 UTC
Transmission 4.0.6 is now banned due to bugs in this version. Please either downgrade to 4.0.5 or change to a different client.

please fix next release .

**Comment by killemov** [comment] 2024-08-27 21:01
Duplicate of #7082, but clear description.

**Comment by ryliejamesthomas** [comment] 2024-08-28 08:40
It's because of #7078.

**Comment by tearfur** [comment] 2024-08-28 11:29
Duplicate of #7078

**Closed by tearfur** 2024-08-28 11:29 UTC
