### ISSUE TITLE
Transmission not responding  on Mac (总是卡住无响应, 强制关闭或者重启就打不开了)

### ISSUE THREAD

**Issue by wendingp** [transmission/transmission#904] opened 2019-05-09 14:39 UTC
MacOS 10.14.4 (18E226)

Transmission 2.94 is frequently not responding. After force-quitting and/or restarting my Mac, it freezes and can't even open the window again.

It happens a lot. Any ideas?

**Comment by mikedld** [comment] 2019-05-09 14:59
Take a look at #106 and #420 since this could be a duplicate of one of those. Also, there's no point in writing in Chinese, everyone should use English here anyway.

**Comment by wendingp** [comment] 2019-05-09 15:27
After force-restarting Mac, this time it opens fast. Also, I checked that there is not crash log. 

Open Transmission in Terminal and also got the line `[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0` shows up, but then seems to run normally.

What is the meaning of `sample Transmission`?

**Comment by mikedld** [comment] 2019-05-09 15:34
`sample` is the command, `Transmission` is the name of the process to sample. Read more in [`man 1 sample`](http://www.manpagez.com/man/1/sample/).

**Comment by wendingp** [comment] 2019-05-09 15:43
Thanks. It froze again when I stopped a torrent downloading. Attached is the sample log generated by `sample Transmission`.
[Transmission_2019-05-09_233907_iRo9.sample.txt](https://github.com/transmission/transmission/files/3162906/Transmission_2019-05-09_233907_iRo9.sample.txt)

**Comment by wendingp** [comment] 2019-05-12 15:12
Also, I got this error when moving data file: 

`objc[97082]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff948c53c8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10d34ef50). One of the two will be used. Which one is undefined.`

**Comment by ckerr** [comment] 2022-02-24 16:29
This does seem to be a duplicate of #420

**Closed by ckerr** 2022-02-24 16:29 UTC
Labels: bug, scope:mac
