### ISSUE TITLE
Lost connexion when i change torrent localisation

### ISSUE THREAD

**Issue by DidierMasse** [transmission/transmission#1462] opened 2020-09-30 15:26 UTC
Hello ! 

i'm on raspbian os ( debian buster ) and i'm using Transmission 2.94

I've some issues with transmission. When i want change torrent localisation i loose connexion with server...

Some idéa for fix it ? 

Thanks

**Comment by xavery** [comment] 2020-10-13 23:34
This is a known issue. Network traffic - including the RPC - is not processed when moving large amounts of data around.

**Comment by ckerr** [comment] 2022-01-25 22:24
Duplicate of https://github.com/transmission/transmission/issues/2462

**Closed by ckerr** 2022-01-25 22:24 UTC
