### ISSUE TITLE
New download open new app

### ISSUE THREAD

**Issue by celestinoxp** [transmission/transmission#4961] opened 2023-02-20 10:24 UTC
### What is the issue?

When clicking to download a torrent via magnet link in google chrome it opens a new transmission with the download instead of adding to the transmission app that was already open. That is, if you do 2 downloads, you open 2 transmissions, if you do 3, you open 3...
The downloads in question are from the site: www.btdig.com

### Which application of Transmission?

Qt app on Windows 11 (x64)
Language: Portuguese

### Which version of Transmission?

Transmission 4.0.0-dev (c5b1df0daa)

**Comment by ckerr** [comment] 2023-02-20 15:23
Hi @celestinoxp thanks for reporting this.

I think this is a duplicate of #255, so I'm going to close this one as a dupe.

**Closed by ckerr** 2023-02-20 15:23 UTC
