### ISSUE TITLE
How can it start a torrent download without checking the hash of an identically named file? 

### ISSUE THREAD

**Issue by oxalfe** [transmission/transmission#649] opened 2018-06-24 22:48 UTC
Suppose you have two different torrents:

# ExampleTorrent
NameConflict 523.47 MB

# ExampleTorrent
NameConflict 987.54 MB

Both torrents will be downloaded to the same folder, and one of them will overwrite the other

How can it start a torrent download without checking the hash of an identically named file?

**Comment by ckerr** [comment] 2022-02-25 16:22
Duplicate of https://github.com/transmission/transmission/issues/251

**Closed by ckerr** 2022-02-25 16:22 UTC
