### ISSUE TITLE
Transmission stuck on send metadata

### ISSUE THREAD

**Issue by Juniorsnet** [transmission/transmission#5811] opened 2023-07-21 04:16 UTC
### What is the issue?

I created a torrent and start seeded in Transmission 4.0.3 on PC1
Then I shared the torrent via magnet link to PC2 (another PC on LAN) with Transmission 4.0.3 and get stuck on 66% of metadata.
Same thing ocurr with qbittorrent on PC2 or deluge on PC2

When start seed on PC1 with qbittorrent every body can download on PC2 via magnet link.
![image](https://github.com/transmission/transmission/assets/9701508/a444e82f-956f-45b1-911f-a10b8a98d2f0)

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.3

**Comment by valcomm** [comment] 2023-07-21 04:56
There's definitely some issue with metadata exchange in v4.0.3.
I have a number of magnet of torrents that have no live tracker (ex-rarbg links).  They're stuck on metadata fetch.  If I insert the same magnets to QBitttorrent, metadata is fetched fine.
I think this is a critical issue to have a higher priority for a fix/new version.
Is it a new issue or been reported before?

**Comment by tearfur** [comment] 2023-07-21 09:19
Should be fixed at #5460. Duplicate of #4765.

**Closed by tearfur** 2023-07-21 09:19 UTC
