### ISSUE TITLE
4.0 consistently corrupts data on MacOS

### ISSUE THREAD

**Issue by KristijanZic** [transmission/transmission#4801] opened 2023-02-10 19:28 UTC
### What is the issue?

The 4.0 shows 548 of 506,7 MB (100%) but still says it is downloading and the file is still a .part file. Verifying data didn't help.

Moved back to the 3.0.0 version and it says 471,6 of 506,7 MB (93,07%) and it says that data is corrupted. After verifying with 3.0.0 the download continues.

This issue happens consistently with any torrent. The only solution is to roll back to 3.0.0

I'm on the Macbook 14 Pro M1, MacOS Ventura 13.2, downloading on the external Samsung T5 2TB drive.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0

**Comment by ddbrierton** [comment] 2023-02-10 19:40
Same. There is an open ticket about this issue for one of the beta releases: #4583. I think it is also the underlying cause of #4784.

**Comment by KristijanZic** [comment] 2023-02-10 20:04
> Same. There is an open ticket about this issue for one of the beta releases: #4583. I think it is also the underlying cause of #4784.

Yeah, I've seen those before. This was happening to me in beta too. It's mind-blowing to me that they released it like this.

**Comment by ckerr** [comment] 2023-02-10 20:21
Closing as duplicate of #4583.

**Closed by ckerr** 2023-02-10 20:21 UTC
