### ISSUE TITLE
Closing and opening causes torrents to reorganize

### ISSUE THREAD

**Issue by Angrybob911** [transmission/transmission#5231] opened 2023-03-15 20:35 UTC
### What is the issue?

What happens is that the torrents I have listed inside of Transmission used to stay in the same order I put them in. However, with this new update, when I close and later reopen Transmission, all of the torrents are unorganized and all over the place. Is there a way to remedy this? Thanks!

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1 (e1c6e1be43)

**Comment by ckerr** [comment] 2023-03-15 20:41
Hi @Angrybob911, thanks for reporting this!

I think this is a duplicate of #155 so I'm closing this issue as a duplicate.

**Closed by ckerr** 2023-03-15 20:41 UTC

**Comment by GaryElshaw** [comment] 2023-04-17 05:13
@ckerr I just noticed that both this and #155 have been closed, do we have an open version of this issue?

**Comment by ckerr** [comment] 2023-04-17 05:35
@GaryElshaw I think you might be looking at the wrong page? 155 isn't closed

**Comment by GaryElshaw** [comment] 2023-04-17 06:32
Ugh. So it is, thanks.
