### ISSUE TITLE
Large torrent files revert to paused at 99.9% after being completed.

### ISSUE THREAD

**Issue by ShipOfUnraid** [transmission/transmission#3107] opened 2022-05-17 17:28 UTC
Perhaps similar to issue #820. With many large torrent files (20gb+), I will notice a few days after the download completes that the torrent has paused seeding and is reporting only 99.99% complete. This is after it previously reached 100%, and seeded for some time. Resuming the torrent finishes the download and begins seeding again. Unlike #820, there is not always an error, the torrent just is "paused".

I am running version 2.94 in docker on Unraid (haugene-transmission-openvpn docker to be specific).

**Comment by ValZapod** [comment] 2022-05-21 21:20
> seeding and is reporting only 99.99% complete. This is after it previously reached 100%,

Is that really possible? Is it allowed to rescan like that?

**Comment by Tharn** [comment] 2022-05-31 20:08
Some other thing happening? Opening the torrent in a program that parses/changes file metadata for media, for example?

**Comment by ShipOfUnraid** [comment] 2022-06-04 19:53
Radarr is hard linking the completed files somewhere else, but my understanding was that that would not impact the downloaded file

**Comment by killemov** [comment] 2022-10-23 08:16
Possible scenario that I can think of:

1. Torrent was completed successfully.
2. Transmission somehow (temporarily) lost access to a file when serving up a requested piece.
3. Transmission stops seeding that torrent and marks the requested piece as non-existent.
4. Verification when access has been restored shows the torrent complete again. (For large files with slow file read, like over NFS, re-downloading that piece is usually faster.)

(Please use piece instead of chunk.)

**Comment by ckerr** [comment] 2023-01-27 04:15
This is a duplicate of https://github.com/transmission/transmission/issues/4621.

Bug report etiquette is to close the newer ones as duplicates of the older ones, but @hauuau had such a great writeup in 4621 for how to repro the issue consistently that I'm leaving that one open and closing this one as the dupe.

**Closed by ckerr** 2023-01-27 04:15 UTC
