### ISSUE TITLE
[bug][daemon] Transmission does not listen on IPv6 UDP socket

### ISSUE THREAD

**Issue by ly4096x** [transmission/transmission#1593] opened 2021-01-20 10:07 UTC
## Reproducing

- Enable ipv6 support for docker with private ipv6 address NAT setup (e,g, `"fixed-cidr-v6": "fd00:172:17:0::/80"`)
- `docker run -it alpine`
- `apk add transmission-daemon net-tools`
- `transmission-daemon -f -I :: -M --log-debug`
- After daemon starts up, run `netstat -tunpl` in a `docker exec` shell, shows ipv4 tcp and udp, ipv6 tcp are correctly listening, but not ipv6 udp.

## Some thoughts

It looks like Transmission checks whether the host ipv6 address is a global unicast address before binding. (see [libtransmission/net.c#L606](https://github.com/transmission/transmission/blob/9d313a8816f6341a9da1a84975c30c95dec5340e/libtransmission/net.c#L606). This doesn't make any sense. Even if I'm using a private ipv6 address I may still run Transmission as usual. In fact I'm manually mapping the public ipv6 address to the container but the daemon doesn't know that.

**Comment by ValZapod** [comment] 2021-03-12 18:25
> * "fd00:172:17:0::/80"

What is this? It does not look like Unique or Global for that matter. To be global it should be given by the router in SLAAC, just like normal white ivp6 prefix is delegated.

**Comment by ly4096x** [comment] 2021-03-12 19:39
> 
> 
> > * "fd00:172:17:0::/80"
> 
> What is this? It does not look like Unique or Global for that matter. To be global it should be given by the router in SLAAC, just like normal white ivp6 prefix is delegated.

Indeed it's not a global address. It's an address assigned for the container which has a port (the transmission listening port) mapped to another global address. Transmission should be able to work with this.

**Comment by ValZapod** [comment] 2021-03-12 19:52
But why cannot you use deprecated site-local or present for any ipv6 interface link-local address? And anyway to use it you will have to set after ip %wlan0 or %eth0 interface or %2.

**Comment by ly4096x** [comment] 2021-03-15 00:32
> 
> 
> But why cannot you use deprecated site-local or present for any ipv6 interface link-local address? And anyway to use it you will have to set after ip %wlan0 or %eth0 interface or %2.
> 
> Also, I get /64 prefix for ULA. Do you?
> 
> Also if your router gets you ULA it MUST work inside docker or virtual machine. You are getting /64 prefix that will be further delegated inside your machine. With PD (prefix delegation) **you** are setting the last 64 bits.

Of course this will work, but first PD requires special setup for containers and second it's harder to setup firewall rules with PD. IPv6-NAT provides a simple way to just expose one port with nothing else.

For now I'm using `net=host` for the container as a workaround, which completely breaks the network isolation but works with no problem.

**Comment by ckerr** [comment] 2022-01-18 22:56
This looks like a duplicate of https://github.com/transmission/transmission/issues/1659 so I'm closing this issue.

If this is in error, please file a new issue. Thank you!

**Closed by ckerr** 2022-01-18 22:56 UTC
