### ISSUE TITLE
[REQUEST] Update UI to GTK standard (Gnome 40+)

### ISSUE THREAD

**Issue by ghost** [transmission/transmission#3038] opened 2022-05-01 07:49 UTC
Hi,
I found the GTK UI very old-fashioned
Is it possible to update the UI that respect the new GTK standard on gnome 40+ ?

For example make the menu (files, settings, help...) hided and accessible with three dots menu
Like it is on other Gnome App as Nautilus (see below)

Screenshot of the three dots
![Capture d’écran du 2022-05-01 09-43-15](https://user-images.githubusercontent.com/99916888/166137136-b1aef855-5330-4bc7-8e59-9bed20c77143.png)

Screenshot of the submenu
![Capture d’écran du 2022-05-01 09-48-11](https://user-images.githubusercontent.com/99916888/166137141-793cde2d-7670-4531-a871-f3fa6e245617.png)

And maybe update other buttons (open, start, pause...) to respect GTK themes or something near Macos UI style ?

Thanks.

**Comment by sunjay140** [comment] 2022-05-22 03:37
It would be nice to have libadwaita support.

**Comment by ckerr** [comment] 2022-08-28 17:45
This is a duplicate of https://github.com/transmission/transmission/discussions/3719.

If anyone wants to contribute code for this that would be :fire:

**Closed by ckerr** 2022-08-28 17:45 UTC
Labels: enhancement, scope:gtk, pr welcome, type:ui
