### ISSUE TITLE
4.0.0-release daemon crashes on assertion

### ISSUE THREAD

**Issue by blind-oracle** [transmission/transmission#4743] opened 2023-02-08 14:36 UTC
### What is the issue?

4.0.0 daemon release built on Ubuntu 22.04 amd64

Crashes periodically with the following:
```
assertion failed: secret_ != key_bigend_t{} (/usr/src/transmission-4.0.0/libtransmission/peer-mse.h:66)
```

I guess this has to do something with encryption of BT traffic, but there's no way to disable it I think to work this around...

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.0

**Comment by mikedld** [comment] 2023-02-08 15:43
This is a duplicate of #4078. Unless you want to debug, building with one of release configurations (by setting `CMAKE_BUILD_TYPE` to one of `Release`, `RelWithDebInfo`, `MinSizeRel`) will disable assertions.

**Closed by mikedld** 2023-02-08 15:43 UTC

**Comment by blind-oracle** [comment] 2023-02-08 15:58
@mikedld Thanks, will rebuild with `Release`! I did a search on some keywords before reporting, but haven't found #4078 for some reason, sorry.
