### ISSUE TITLE
Transmission-gtk not accessible anymore after minimized to tray area

### ISSUE THREAD

**Issue by fredo-47** [transmission/transmission#4387] opened 2022-12-17 10:38 UTC
### What is the issue?

When I "close" the transmission-gtk via the close icon in the top right corner of its window, it disappears into the tray area.
So far as expected. Normally you can then right click on that icon in the tray area and perform various tasks, e.g. re-open its window, activate the speed limit, or actually quit the app.
![t-gtk_tray](https://user-images.githubusercontent.com/30537162/208237322-5beaa9f4-17bd-4fcc-a274-40f0ab77ec4d.png)

However, none of these works for me anymore (it used to work until a few weeks ago with previous builds).
In other words, after minimizing it into the tray area, I cannot re-open the window or quit the app anymore.

When I send a TERM signal to the process or press CTRL+C in the terminal window I opened it from, nothing happens. 
Only when I send a KILL signal, it quits.

PS: If I noticed correctly, any torrenting (uploading/downloading) does still continue. Only you as user cannot interact with the GTK app anymore in that state.

Linux Mint 21 Cinnamon
### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

Transmission 4.0.0-beta.2.dev (5d5893036d)

**Comment by dantob** [comment] 2022-12-20 13:26
Trying to restore the window causes transmission to consume 100% of one cpu core until it is manually sent a KILL signal 4.0.0-beta.2.dev (76db72bc4b)

**Comment by fredo-47** [comment] 2023-02-08 18:38
FYI, this is still happening with version 4.0.0 (280ace12f8)

**Comment by bitchecker** [comment] 2023-02-25 21:58
I have the same bug on release 4.0.0 (280ace12f8) on Fedora 37 system.

**Comment by ckerr** [comment] 2023-02-25 22:07
I thought this was fixed in 4.0.1.

@mikedld is this a duplicate of https://github.com/transmission/transmission/issues/4934 ?

**Comment by mikedld** [comment] 2023-02-25 22:21
It does look like a duplicate, yes, althought was reported earlier. Sorry I didn't see it before the release but 4.0.1 should indeed have a fix.

**Closed by mikedld** 2023-02-25 22:21 UTC
Labels: bug, needs clarification, scope:gtk
