### ISSUE TITLE
Quick Look Preview Broken on macOS Sequoia

### ISSUE THREAD

**Issue by mslmn** [transmission/transmission#7163] opened 2024-10-10 22:04 UTC
### What is the issue?

The Quick Look extension for torrent files no longer works when you update to the latest macOS.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.5

**Comment by nevack** [comment] 2024-10-10 22:58
https://github.com/transmission/transmission/issues/3029

**Comment by tearfur** [comment] 2024-10-11 04:03
Duplicate of #3029

**Closed by tearfur** 2024-10-11 04:03 UTC
