### ISSUE TITLE
Transmission WebGui 卡顿，如何关闭gzip功能，等了5分钟rpc还没跑完

### ISSUE THREAD

**Issue by 1265578519** [transmission/transmission#1055] opened 2019-11-11 16:07 UTC
Transmission WebGui 卡顿，如何关闭gzip功能，等了5分钟rpc还没跑完
![1](https://user-images.githubusercontent.com/6442439/68601952-601e3800-04e0-11ea-8887-b8815af5d22c.png)

**Comment by 1265578519** [comment] 2019-11-11 16:09
![image](https://user-images.githubusercontent.com/6442439/68602100-abd0e180-04e0-11ea-9f93-fd7ef8cb621b.png)
这，，有什么方案吗，top看进程占用10%左右cpu，我怀疑卡在gzip处理了

**Comment by 1265578519** [comment] 2019-11-11 16:20
![image](https://user-images.githubusercontent.com/6442439/68602947-467df000-04e2-11ea-818c-49937ecdff2e.png)
20分钟了。。

**Comment by aliyuchang33** [comment] 2019-11-19 13:51
你是不是在高速下载，我也有这个问题，我发现只要io写入大于30m/s它就开始卡

**Comment by aliyuchang33** [comment] 2019-11-19 23:38
It seems like webui will lag if the io is above 30MBps. This is an approximate value for my virtual machine. I'm not sure is that different on other machines. io can be measured by using `iotop`. I don't think transmission webui should be affected by io. Any idea here?

**Comment by 1265578519** [comment] 2019-11-20 10:16
高速下载也有这个问题，，我这个贴的问题是通过监视目录功能导入了近万的torrent文件，然后就报废掉了

**Comment by aliyuchang33** [comment] 2019-11-20 11:41
换deluge吧，我已经换了

**Comment by ckerr** [comment] 2022-01-25 22:45
Closing as a duplicate of https://github.com/transmission/transmission/issues/2462

**Comment by ckerr** [comment] 2022-01-25 22:46
Original title pre-Google Translate:

> Transmission WebGui 卡顿，如何关闭gzip功能，等了5分钟rpc还没跑完

**Closed by ckerr** 2022-01-25 22:45 UTC
