### ISSUE TITLE
4.0.0-beta.3 stops downloading

### ISSUE THREAD

**Issue by aoireiwa** [transmission/transmission#4700] opened 2023-02-01 08:26 UTC
### What is the issue?

When add a new torrent and after the metadata downloading, the process will be paused. I have to start it again.  

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.0-beta.3

**Comment by ckerr** [comment] 2023-02-01 18:14
Hi @aoireiwa, thanks for reporting this.

I think this is a duplicate of https://github.com/transmission/transmission/issues/3258 so I'm going to close this as a duplicate of that ticket.

**Closed by ckerr** 2023-02-01 18:14 UTC
