### ISSUE TITLE
All torrents at "Magnetized transfer - torrent metadata needed" status and won't change; no "Varify data" option

### ISSUE THREAD

**Issue by ChazChoppa** [transmission/transmission#5017] opened 2023-02-23 22:21 UTC
- All torrents at "Magnetized transfer - torrent metadata needed" status and won't change
- No "Varify data" option

**Comment by ckerr** [comment] 2023-02-24 00:52
@ChazChoppa could you take a look in Transmission's `torrents/` folder and see if there are two files with the same infohash but a different suffix, e.g. `${infohash}.magnet` and `${infohash}.torrent`?

- on macOS you would look in `~/Library/Application Support/Tranmsission/torrents`
- on Windows you would look in `%USERPROFILE%\AppData\Local\Transmission\torrents` (I think)
- on Linux you could look in `~/.config/transmission/torrents`

**Comment by FrostyGelato** [comment] 2023-02-24 05:45
I have the same problem, and there seems to be two files with same infohash for torrents with "Magnetized transfer - torrent metadata needed" status. Some of my torrents are still showing as complete and those only have one file with infohash.

**Comment by ckerr** [comment] 2023-02-24 05:55
I think this is a duplicate of https://github.com/transmission/transmission/issues/5007, so I'm going to close this ticket as a dupe. Please check out 5007 to see the discussion there.

**Closed by ckerr** 2023-02-24 05:55 UTC
Labels: bug, needs clarification

**Comment by marsnone** [comment] 2023-12-28 01:12
> @ChazChoppa could you take a look in Transmission's `torrents/` folder and see if there are two files with the same infohash but a different suffix, e.g. `${infohash}.magnet` and `${infohash}.torrent`?
> 
> * on macOS you would look in `~/Library/Application Support/Tranmsission/torrents`
> * on Windows you would look in `%USERPROFILE%\AppData\Local\Transmission\torrents` (I think)
> * on Linux you could look in `~/.config/transmission/torrents`

Seems like it doesn't exist for me...

```

>  ls: /Users/martinoneill/Library/Application: No such file or directory
> ls: Support/Tranmsission/: No such file or directory

```
