### ISSUE TITLE
Crash when connecting from web UI

### ISSUE THREAD

**Issue by teeks99** [transmission/transmission#6031] opened 2023-09-23 13:54 UTC
### What is the issue?

Running with the latest main (as of yesterday morning), on ubuntu 20.04 the daemon runs well with several dozen torrents active. The moment that I connect to the web UI, the `transmisison-daemon` process crashes.

I was able to pull this callstack out

```
libc.so.6!__GI_raise(int sig) (/build/glibc-SzIz7B/glibc-2.31/sysdeps/unix/sysv/linux/raise.c:50)
libc.so.6!__GI_abort() (/build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:79)
libstdc++.so.6![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libstdc++.so.6!std::terminate() (Unknown Source:0)
libstdc++.so.6!__cxa_throw (Unknown Source:0)
libstdc++.so.6![Unknown/Just-In-Time compiled code] (Unknown Source:0)
__gnu_cxx::new_allocator<tr_variant>::allocate() (/usr/include/c++/9/ext/new_allocator.h:102)
std::allocator_traits<std::allocator<tr_variant> >::allocate() (/usr/include/c++/9/bits/alloc_traits.h:443)
std::_Vector_base<tr_variant, std::allocator<tr_variant> >::_M_allocate(std::_Vector_base<tr_variant, std::allocator<tr_variant> > * const this, std::size_t __n) (/usr/include/c++/9/bits/stl_vector.h:343)
std::vector<tr_variant, std::allocator<tr_variant> >::_M_realloc_insert<>(__gnu_cxx::__normal_iterator<tr_variant*, std::vector<tr_variant, std::allocator<tr_variant> > >)(std::vector<tr_variant, std::allocator<tr_variant> > * const this, std::vector<tr_variant, std::allocator<tr_variant> >::iterator __position) (/usr/include/c++/9/bits/vector.tcc:440)
std::vector<tr_variant, std::allocator<tr_variant> >::emplace_back<>()(std::vector<tr_variant, std::allocator<tr_variant> > * const this) (/usr/include/c++/9/bits/stl_iterator.h:803)
tr_variantListAdd(tr_variant * const var) (/home/tomkent/src/transmission/libtransmission/variant.cc:425)
tr_variantListAddList(tr_variant * const var, size_t n_reserve) (/home/tomkent/src/transmission/libtransmission/variant.cc:480)
(anonymous namespace)::torrentGet(tr_session * session, tr_variant * args_in, tr_variant * args_out) (/usr/include/c++/9/bits/stl_vector.h:915)
tr_rpc_request_exec_json(tr_session * session, const tr_variant * request, tr_rpc_response_func callback, void * callback_user_data) (/home/tomkent/src/transmission/libtransmission/rpcimpl.cc:2543)
(anonymous namespace)::handle_rpc_from_json(tr_rpc_server * server, evhttp_request * req) (/usr/include/c++/9/optional:912)
(anonymous namespace)::handle_rpc(tr_rpc_server * server, evhttp_request * req) (/home/tomkent/src/transmission/libtransmission/rpc-server.cc:375)
(anonymous namespace)::handle_request(evhttp_request * req, void * arg) (/home/tomkent/src/transmission/libtransmission/rpc-server.cc:578)
evhttp_handle_request(struct evhttp_request * req, void * arg) (/home/tomkent/src/transmission/third-party/libevent/http.c:3501)
evhttp_read_body(struct evhttp_connection * evcon, struct evhttp_request * req) (/home/tomkent/src/transmission/third-party/libevent/http.c:1119)
evhttp_get_body(struct evhttp_request * req, struct evhttp_connection * evcon) (/home/tomkent/src/transmission/third-party/libevent/http.c:2269)
evhttp_get_body(struct evhttp_connection * evcon, struct evhttp_request * req) (/home/tomkent/src/transmission/third-party/libevent/http.c:2215)
bufferevent_run_readcb_(struct bufferevent * bufev, int options) (/home/tomkent/src/transmission/third-party/libevent/bufferevent.c:251)
bufferevent_trigger_nolock_(int options, short iotype, struct bufferevent * bufev) (/home/tomkent/src/transmission/third-party/libevent/bufferevent-internal.h:411)
bufferevent_readcb(int fd, short event, void * arg) (/home/tomkent/src/transmission/third-party/libevent/bufferevent_sock.c:214)
event_persist_closure(struct event * ev, struct event_base * base) (/home/tomkent/src/transmission/third-party/libevent/event.c:1623)
event_process_active_single_queue(struct event_base * base, int max_to_process, const struct timeval * endtime) (/home/tomkent/src/transmission/third-party/libevent/event.c:1682)
event_process_active(struct event_base * base) (/home/tomkent/src/transmission/third-party/libevent/event.c:1783)
event_base_loop(struct event_base * base, int flags) (/home/tomkent/src/transmission/third-party/libevent/event.c:2006)
tr_session_thread_impl::sessionThreadFunc(tr_session_thread_impl * const this, event_base * evbase) (/home/tomkent/src/transmission/libtransmission/session-thread.cc:239)
libstdc++.so.6![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libpthread.so.0!start_thread(void * arg) (/build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477)
libc.so.6!clone() (/build/glibc-SzIz7B/glibc-2.31/sysdeps/unix/sysv/linux/x86_64/clone.S:95)
```

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

586cff9506487eabf72baa3c1588e623a8b1ac63

**Comment by warmach1ne** [comment] 2023-09-24 02:52
Revert to stable build for now. The dev build has this issue.

**Comment by tearfur** [comment] 2023-09-24 05:12
Duplicate of #6003.

**Closed by tearfur** 2023-09-24 05:12 UTC
