### ISSUE TITLE
when updating blocklist, check peer connections for blocked IP to disconnect

### ISSUE THREAD

**Issue by qianbinbin** [transmission/transmission#2959] opened 2022-04-21 16:35 UTC
How to reproduce:

1. start a torrent and seed
2. add an IP of a peer to blocklist in `~/.config/transmission-daemon/blocklists/`
3. reload Transmission and ensure the `.bin` file updated
4. the torrent is still uploading to the IP

Simply restarting the torrent or transmission-daemon should do the trick, but I think it should stop seeding right after reloading the blocklist.

Version: Transmission 3.00 (bb6b5a062e)

Thank you for your brilliant work!

**Comment by ckerr** [comment] 2023-01-27 20:29
duplicate of #732

**Closed by ckerr** 2023-01-27 20:29 UTC
Labels: enhancement, pr welcome
