### ISSUE TITLE
Sometimes files are not deleted when you delete torrent and data.

### ISSUE THREAD

**Issue by lvella** [transmission/transmission#5361] opened 2023-04-07 23:33 UTC
### What is the issue?

This is tricky because it doesn't always happen, but often when I use a remote GUI connected to `transmission-daemon` (last time it happened I was using [transgui](https://github.com/transmission-remote-gui/transgui)) and I click to remove a torrent plus data, the torrent is removed but not the data, so I am left with the old files taking up space on my disc.

I don't know why it happens, but I have seen it happening on previous versions, too.

I think the removal of the torrent should not succeed if the data could not be removed. Maybe an error should be returned through the API, maybe the torrent should be stopped with an error condition, but the error should not be silently ignored.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

3.00+ (42198afc5f)

**Comment by ckerr** [comment] 2023-04-08 01:42
> 3.00+ (https://github.com/transmission/transmission/commit/42198afc5feb1c017f6a9c54bef5c854980d201d)

...a nightly build from a year ago? Why? :confused: 

Is this still happening in 4.0.2?

Does transmission return any error information back to the daemon?

Do any errors get logged in the daemon's log?

**Comment by killemov** [comment] 2023-04-08 06:38
This was and probably still is normal behavior when the filesystem is full. (On Linux.) AFAIK Transmission does some weird things when trashing a torrent. For example when a file is symbolically linked it first get resolved/copied before trashing.

**Comment by lvella** [comment] 2023-04-09 22:54
But my files are not symbolically linked. Some are have multiple hardlinks, but not the ones who where not removed.

**Comment by killemov** [comment] 2023-04-09 23:28
But was the filesystem full? (You know, the important part of my post?)

**Comment by ckerr** [comment] 2023-04-10 03:11
And all four of the questions from my comment? :smile_cat:

**Comment by lvella** [comment] 2023-04-10 18:51
> But was the filesystem full? (You know, the important part of my post?)

Yes, probably. The filesystem is often full, and it is when I tend to delete torrents with the data.

> ...a nightly build from a year ago? Why? confused

Not a nightly build, it is my own build of the commit that merged my PR, that I am using. Why? Because the version that comes with my outdated distro is even older.

> Is this still happening in 4.0.2?

I am working on figuring this out.
 
> Does transmission return any error information back to the daemon?

Isn't transmission the daemon? The client simply removes the torrent with no errors displayed.

> Do any errors get logged in the daemon's log?

Not sure. If it did, it got rotated, because I am being spammed with the following, over and over again:
```
[msg] All nameservers have failed
[msg] Nameserver 8.8.8.8:53 is back up
[msg] Nameserver 8.8.8.8:53 has failed: request timed out.
```

**Comment by ckerr** [comment] 2023-04-11 00:26
> Isn't transmission the daemon? The client simply removes the torrent with no errors displayed.

I should've written _from_ the daemon. I'm wondering if RPC returns any error messages.

> I am working on figuring out [whether this is still happening in 4.0.2]

OK, please update this ticket when you have more information. Since that commit is from a year ago and of an unreleased version I'm not really sure about doing triage work on this until if/when there's something reproducible in 4.0.x :bow:

**Comment by killemov** [comment] 2023-04-11 10:20
> > Isn't transmission the daemon? The client simply removes the torrent with no errors displayed.
> 
> I should've written _from_ the daemon. I'm wondering if RPC returns any error messages.

Nope. TM Just removes the torrent, the content is not removed.

> > I am working on figuring out [whether this is still happening in 4.0.2]
> 
> OK, please update this ticket when you have more information. Since that commit is from a year ago and of an unreleased version I'm not really sure about doing triage work on this until if/when there's something reproducible in 4.0.x bow

Just tested with 4.0.2 (2a57b17031) and it's still business as usual. (NOT removing content.) You, as developers, could also ask yourselves if the deletion process has been overhauled. Apparently it has not.

**Comment by lvella** [comment] 2023-04-11 15:48
To be fair, I intended working on this issue myself. I just wanted to open the issue first.

**Comment by ckerr** [comment] 2023-04-11 22:34
Duplicate of https://github.com/transmission/transmission/issues/1835?

**Comment by nengxu** [comment] 2023-04-19 00:15
I encountered same problem with various versions of transmission, for example 4.0.3. It is not related to lack of disk space. It may relate to some downloaded ontents may not be valid.

**Comment by killemov** [comment] 2023-04-19 11:27
It is proven to be related to full drives. It MAY also be related to other causes. "Downloaded contents may not be valid" is also related to full drives as pieces are reported to have been written do disk when, in fact, they have not.

**Comment by nengxu** [comment] 2023-04-19 16:16
> It is proven to be related to full drives. It MAY also be related to other causes. "Downloaded contents may not be valid" is also related to full drives as pieces are reported to have been written do disk when, in fact, they have not.

In my case, the disk has lots of space.

**Comment by lvella** [comment] 2023-04-20 14:26
> It is proven to be related to full drives. It MAY also be related to other causes. "Downloaded contents may not be valid" is also related to full drives as pieces are reported to have been written do disk when, in fact, they have not.

Indeed, I remember now!

Since I started using a 3.00+ development version, I started having invalid chunks here and there. Most goes by unnoticed, until something happens and the torrent is stopped with the invalid chunk error. What comes next is my guesswork:
- some peer requests an invalid chunk, which is sent, but since it doesn't validate on the peer side, I guess there is a feedback message saying the chink is invalid, which causes transmission to verify it and stop the torrent with an error.
- if a file has invalid chunks when being deleted, it is somehow detected by transmission, and the deletion silently fails.

It may even be that the source of the corruption has been fixed since then, but if you still have corrupted files, they may fail to be deleted.

**Comment by killemov** [comment] 2023-04-23 20:38
Nope. Drive full means no content will be deleted.

**Comment by nengxu** [comment] 2023-04-23 21:32
> Nope. Drive full means no content will be deleted.

I already mentioned that at least in my cases the disk is not full.

**Comment by lvella** [comment] 2023-04-24 17:33
> Duplicate of #1835?

I would say this contained in #1835, because #1835 is also about other places the code assumes there is free space on the disk.

**Comment by nengxu** [comment] 2023-04-24 17:55
> > Duplicate of #1835?
> 
> I would say this is contained in #1835, because #1835 is also about other places the code assumes there is free space on the disk. I have experienced the issue described there of completed torrents raising an error when I try to add a new torrent and the disk is full, but that is nowhere as annoying as files not being removed.

I already mentioned several times that in my cases the disk was not full. But it may relate to invalid data in downloaded torrents.

**Comment by lvella** [comment] 2023-04-24 18:40
> I already mentioned several times that in my cases the disk was not full. But it may relate to invalid data in downloaded torrents.

Well, my issue indeed seems to be related with full disks, so your issue probably belongs in a different ticket.

Even the corrupted torrents issue I mentioned I had a long time ago seems to have been fixed with #2367, which is also related to full disks.

**Comment by lvella** [comment] 2023-04-24 18:56
@ckerr , looking at the code, it seem libtransmission's `tr_torrent_files::remove()` is concerned by platforms specific stuff, like points 1 and 3 in the comments quoted here:

```
 * 1. Try to preserve the directory hierarchy in the recycle bin.
 * 2. If there are nontorrent files, don't delete them...
 * 3. ...unless the other files are "junk", such as .DS_Store
```

I think such concerns should be implemented inside `#ifdef` for the relevant platforms (I guess windows and macos?). What do you think?

Anyway, the code for doing it doesn't check for error conditions in creating a temporary directory nor for moving the files there (or copying them there, if on different filesystem (what I am not sure if it can happen or not)). A proper fix would have to check for error conditions and maybe fallback to simpler implementation in case the file operations fails. I am not sure all this helps with preserving the directory hierarchy on the recycle bin.

**Comment by ckerr** [comment] 2023-04-24 23:09
> I think such concerns should be implemented inside #ifdef for the relevant platforms (I guess windows and macos?). What do you think?

GTK / Qt use the recycle bin too, so I'm not sure how this is platform-specific?

Seems like you mean transmission-daemon vs the other clients; but if so, there's also a longstanding enhancement request to use the trashcan / recycle bin there too https://github.com/transmission/transmission/issues/1722

> Anyway, the code for doing it doesn't check for error conditions in creating a temporary directory nor for moving the files there (or copying them there, if on different filesystem (what I am not sure if it can happen or not)). A proper fix would have to check for error conditions and maybe fallback to a simpler implementation in case the file operations fails.

I guess the question is, what is the Right Thing to do if the recycle bin fails? Surely we don't want to just unconditionally remove since that would make it impossible to undelete...

One thing that would be useful is better error reporting so that when removal fails, at least users have some more visibility into what went wrong. It looks to me like `tr_torrent_files::remove()` should take a tr_error but currently doesn't.

**Comment by Tharn** [comment] 2023-05-15 10:07
Honestly, I have encountered this issue with various torrent clients over the years, and it was always a rare thing that happened. So rare in fact that I'd simply account for it by the filesystem for one reason or another not having released the file or folder at the time the torrent client tried to have it deleted. Transmission is not an outlier in this. In fact on my dedicated server I don't see this happen at all. Moreso on a desktop.

The only thing I can think of here would be that the client should give notice that the filesystem has not released a file or folder, instead of silently failing and just deleting the torrent and the listing.

I can't say that I've seen Transmission or the daemon deliberately not deleting something when doing it through TRGUI.

**Comment by lvella** [comment] 2023-05-15 10:40
> I can't say that I've seen Transmission or the daemon deliberately not deleting something when doing it through TRGUI.

I use transmission-daemon, and it does happen a few times a year. Looking at the code, it is obvious how this can happen. It has nothing to do with the OS.

PR not done yet, though.

**Comment by lvella** [comment] 2023-05-18 20:20
Looking at Gtk client, if moving to trash fails, it raises an error but also permanently delete the file. I guess this is not really the desired behavior, right?

**Comment by lvella** [comment] 2023-10-01 14:34
What is the deal with "needs-clarification" label?

**Comment by tearfur** [comment] 2023-10-08 03:16
@lvella I've encountered something similar before when my Transmission downloads exhausted hard disk space, I wasn't able to delete any files using Transmission after that.

You are very welcomed to submit a PR since you know where the problem is :)

**Comment by lvella** [comment] 2023-10-08 10:22
@tearfur The PR #6055 has been opened a for few days now. But I don't know how it affects macOS, as deletion is no longer fire-and-forget. Had to make some changes in GTK, but I don't have a mac.

**Closed** 2024-08-13 04:26 UTC
Labels: bug, needs clarification, scope:core, pr welcome
