### ISSUE TITLE
Transmission locks up when HTTP download is too fast?

### ISSUE THREAD

**Issue by ieee8023** [transmission/transmission#485] opened 2018-01-24 17:44 UTC
Hello,

I am experiencing a strange problem. When I download torrents that have HTTP seeds that are really fast it makes Transmission hang unless I throttle the speed to something really low.

This torrent has the problem
http://academictorrents.com/details/c4f39a0a8e46e8d2174b8a8a81b9887150f44d50

I run Academic Torrents and I started noticing this issue when we added very fast HTTP peers (30MB/s>). Is the problem with transmission or something else?

**Comment by ckerr** [comment] 2022-01-18 22:34
Duplicate of https://github.com/transmission/transmission/issues/1829

**Closed by ckerr** 2022-01-18 22:34 UTC
