### ISSUE TITLE
Opening 'Message Log' in qt client tray doesn't work

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4653] opened 2023-01-24 12:54 UTC
### What is the issue?

Selecting 'Message Log' from the tray dropdown doesn't display amy information.

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.0-beta.3.dev (b055b98d0f)

**Comment by ckerr** [comment] 2023-01-24 15:44
Duplicate of https://github.com/transmission/transmission/issues/3773

**Closed by ckerr** 2023-01-24 15:44 UTC
Labels: duplicate
