### ISSUE TITLE
Crash while scrolling torrent list in gtk client

### ISSUE THREAD

**Issue by catadropa** [transmission/transmission#4307] opened 2022-12-03 17:24 UTC
### What is the issue?

```
(gdb) bt full
#0  0x00007f16e3853d3a in  () at /lib/x86_64-linux-gnu/libpixman-1.so.0
#1  0x00007f16e3829dbc in  () at /lib/x86_64-linux-gnu/libpixman-1.so.0
#2  0x00007f16e37f87dd in pixman_image_composite32 () at /lib/x86_64-linux-gnu/libpixman-1.so.0
#3  0x00007f16e42fe24d in  () at /lib/x86_64-linux-gnu/libcairo.so.2
#4  0x00007f16e43363b9 in  () at /lib/x86_64-linux-gnu/libcairo.so.2
#5  0x00007f16e4336b90 in  () at /lib/x86_64-linux-gnu/libcairo.so.2
#6  0x00007f16e42f1891 in  () at /lib/x86_64-linux-gnu/libcairo.so.2
#7  0x00007f16e4343718 in  () at /lib/x86_64-linux-gnu/libcairo.so.2
#8  0x00007f16e42fa6e3 in  () at /lib/x86_64-linux-gnu/libcairo.so.2
#9  0x00007f16e42f35de in  () at /lib/x86_64-linux-gnu/libcairo.so.2
#10 0x00007f16e435170e in cairo_fill () at /lib/x86_64-linux-gnu/libcairo.so.2
#11 0x00007f16e585de91 in Cairo::Context::fill() () at /lib/x86_64-linux-gnu/libcairomm-1.0.so.1
#12 0x0000561daef7f977 in TorrentCellRenderer::Impl::adjust_progress_bar_hue(Cairo::RefPtr<Cairo::Surface> const&, Cairo::RefPtr<Cairo::Context> const&, Gdk::RGBA const&, Gdk::Rectangle const&, double, double)
    (bg_surface=<optimized out>, context=..., color=..., area=..., bg_x=-41, bg_y=6)
    at /usr/include/cairomm-1.0/cairomm/refptr.h:202
        mask_surface = {pCppObject_ = 0x561db01b9f40, pCppRefcount_ = 0x561db01b9830}
#13 0x0000561daef7ff6c in TorrentCellRenderer::Impl::render_progress_bar(Cairo::RefPtr<Cairo::Context> const&, Gtk::Widget&, Gdk::Rectangle const&, Gtk::CellRendererState, Gdk::RGBA const&)
    (this=<optimized out>, snapshot=<optimized out>, widget=<optimized out>, area=..., flags=<optimized out>, color=...) at /home/me/workspace/transmission/gtk/TorrentCellRenderer.cc:675
        temp_area = {gobject_ = {x = 0, y = 0, width = 742, height = 12}}
        temp_surface = {pCppObject_ = 0x561db01d52e0, pCppRefcount_ = 0x561db01d8330}
        temp_context = {pCppObject_ = 0x561db0b09a60, pCppRefcount_ = 0x561db01e9600}
        context = {pCppObject_ = 0x561db01d5ce0, pCppRefcount_ = 0x561db01d1b00}
        surface = {pCppObject_ = 0x561db0aa30d0, pCppRefcount_ = 0x561db02155a0}
        dx = 0
        dy = 0
#14 0x0000561daef8471e in TorrentCellRenderer::Impl::render_full(Cairo::RefPtr<Cairo::Context> const&, Gtk::Widget&, Gdk::Rectangle const&, Gtk::CellRendererState)
    (this=0x561db08324a0, snapshot=..., widget=..., background_area=<optimized out>, flags=0)
    at /home/me/workspace/transmission/gtk/TorrentCellRenderer.cc:926
        xpad = 3
        ypad = 3
        min_size = {width = 202, height = 16}
        size = {width = 202, height = 16}
        tor = <optimized out>
        st = <optimized out>
        total_size = <optimized out>
        active = <optimized out>
        percent_done = 100
        sensitive = true
        icon = {pCppObject_ = 0x561db08ce888}
        name = {static npos = 18446744073709551615, string_ = "Random torrent name here"}
        progress_color = @0x561daf1c4fb8: {gobject_ = 0x561db03c2c80}
        gstr_prog = {static npos = 18446744073709551615, string_ = "xxx GB, uploaded xxx GB (Ratio: xx.y)"}
        gstr_stat = "Seeding to 0 of 0 connected peers"
        icon_area = {gobject_ = {x = 3, y = -24, width = 32, height = 32}}
        name_area = {gobject_ = {x = 41, y = -42, width = 742, height = 17}}
        prog_area = {gobject_ = {x = 41, y = -25, width = 742, height = 16}}
        stat_area = {gobject_ = {x = 41, y = 9, width = 742, height = 16}}
        prct_area = {gobject_ = {x = 41, y = -6, width = 742, height = 12}}
        fill_area = {gobject_ = {x = 3, y = -42, width = 780, height = 69}}
#15 0x00007f16e63c32bb in Gtk::CellRenderer_Class::render_vfunc_callback(_GtkCellRenderer*, _cairo*, _GtkWidget*, _cairo_rectangle_int const*, _cairo_rectangle_int const*, GtkCellRendererState) () at /lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#16 0x00007f16e59f85a1 in gtk_cell_renderer_render () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007f16e59ec693 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007f16e59ee9e0 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007f16e59ebbde in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007f16e5c374c2 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007f16e5c22335 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007f16e5b4983d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x00007f16e5c1e5d4 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007f16e6484a8e in Gtk::Widget::on_draw(Cairo::RefPtr<Cairo::Context> const&) ()
    at /lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#25 0x00007f16e647e779 in Gtk::Widget_Class::draw_callback(_GtkWidget*, _cairo*) ()
    at /lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#26 0x00007f16e5c41b64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007f16e5a22825 in gtk_container_propagate_draw () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007f16e5a2292d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#29 0x00007f16e5b79872 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#30 0x00007f16e5a1a2e1 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007f16e5a2e852 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#32 0x00007f16e5b71b65 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#33 0x00007f16e6484a8e in Gtk::Widget::on_draw(Cairo::RefPtr<Cairo::Context> const&) ()
    at /lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#34 0x00007f16e647e779 in Gtk::Widget_Class::draw_callback(_GtkWidget*, _cairo*) ()
    at /lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#35 0x00007f16e5c41b64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
--Type <RET> for more, q to quit, c to continue without paging--c
#36 0x00007f16e5a22825 in gtk_container_propagate_draw () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#37 0x00007f16e5a2292d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#38 0x00007f16e59c4571 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#39 0x00007f16e5a1a2e1 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#40 0x00007f16e5a2e852 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#41 0x00007f16e59c4e15 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#42 0x00007f16e6484a8e in Gtk::Widget::on_draw(Cairo::RefPtr<Cairo::Context> const&) () at /lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#43 0x00007f16e647e779 in Gtk::Widget_Class::draw_callback(_GtkWidget*, _cairo*) () at /lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#44 0x00007f16e5c41b64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#45 0x00007f16e5a22825 in gtk_container_propagate_draw () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#46 0x00007f16e5a2292d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#47 0x00007f16e5c6260e in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#48 0x00007f16e6484a8e in Gtk::Widget::on_draw(Cairo::RefPtr<Cairo::Context> const&) () at /lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#49 0x00007f16e647e779 in Gtk::Widget_Class::draw_callback(_GtkWidget*, _cairo*) () at /lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#50 0x00007f16e5c41b64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#51 0x00007f16e5c4ddb1 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#52 0x00007f16e5af454b in gtk_main_do_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#53 0x00007f16e4609743 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#54 0x00007f16e461c151 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#55 0x00007f16e4621221 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#56 0x00007f16e4621418 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#57 0x00007f16e53e3640 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#58 0x00007f16e53e37a3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#59 0x00007f16e4616c6f in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#60 0x00007f16e46032ad in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#61 0x00007f16e52cd2a8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#62 0x00007f16e52ccc24 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#63 0x00007f16e53216f8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#64 0x00007f16e52ca3c3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#65 0x00007f16e557bc85 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#66 0x0000561daeec69f7 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /home/me/workspace/transmission/gtk/main.cc:127
```

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

nightly build built an hour ago: 0e193a0cb35cce8efd6bbc0fb20d073bc52f0f38

**Comment by ckerr** [comment] 2022-12-03 18:29
CC @mikedld

**Comment by mikedld** [comment] 2022-12-03 20:09
Closing as duplicate of #4075.

**Closed by mikedld** 2022-12-03 20:09 UTC
Labels: bug, scope:gtk, type:ui
