### ISSUE TITLE
Trackers not showing up

### ISSUE THREAD

**Issue by dnalance** [transmission/transmission#4597] opened 2023-01-16 06:19 UTC
### What is the issue?

Hello there!

The beta is almost flawless, but there's one big bug I've found. When using Transmission-4.0.0-beta.3 remotely (to connect to my seedbox), the list of trackers shows nothing. However, when I check the WEBUI, or change from remote to local, it shows the list of trackers just fine. 

I've attached an image of what the tracker list looks like after I've added a torrent remotely, as well as what it looks like when from the WEBUI. 

![Screenshot 2023-01-16 011135](https://user-images.githubusercontent.com/122771633/212610372-93df9c5c-2f61-47a5-b1fe-5d1526613cd8.JPG)
![Screenshot 2023-01-16 011657](https://user-images.githubusercontent.com/122771633/212610773-86afbffc-443f-4eac-9aa6-74d08c05c769.JPG)

I apologize if this has been brought up before, I did a quick scan and keyword search but I wasn't able to find anything.

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

Transmission-4.0.0-beta.3

**Comment by ckerr** [comment] 2023-01-17 00:15
Huh, that's weird. I haven't seen that before.

@dnalance just to confirm, that first of the two screenshots is the qt client connecting to a remote session, right?

**Comment by ckerr** [comment] 2023-03-18 03:08
Closing since I wasn't able to reproduce the bug and since my Jan 16 questions did not get a response.

If anyone is still seeing this issue please open a new ticket with updated information :bow:

**Closed by ckerr** 2023-03-18 03:08 UTC
Labels: bug, needs clarification, scope:qt, needs confirmation
