### ISSUE TITLE
Change tracker on selected torrents doesn't work anymore

### ISSUE THREAD

**Issue by exal66** [transmission/transmission#5293] opened 2023-03-24 14:42 UTC
### What is the issue?

Hi,
I am using Transmission Remote GUI 5.0.2 as Transmission client on Windows 10 on another computer than the one having Transmission Deamon (on Windows 11).
With Transmission 4.0 I can no more change tracker(s) on selected torrents without having this error:
error setting announce list
After that, the first selected torrent has the tracker I have entered on top and the previous tracker just after.
Modifying multiple torrents tracker works very well on Transmission v3, so I think it is a little bug in v4.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.2

**Comment by ckerr** [comment] 2023-03-25 00:57
What is the RPC command that works in Transmission 3 but not Transmission 4?

**Comment by ckerr** [comment] 2023-04-13 04:10
What is the RPC command that works in Transmission 3 but not Transmission 4?

**Comment by batitou81** [comment] 2023-05-12 13:03
Hi, 
I am facing the same bug, while removing a tracker, after upgrading to v4:

transmission-remote -n xxx:xxx -t2 -tr http://xxx
Error: error setting announce list

Works fine on V3

**Comment by nightdawnex** [comment] 2023-08-10 20:18
seems that they deprecated the old args used for these rpc call but actually removed it totally. https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#5-protocol-versions

**Comment by chantzish** [comment] 2023-09-01 06:46
I got the same error message in transmission-remote version 4.0.4. After a lot of tries which seemed to give inconsistent results I discovered the right way to reproduce the error as well as some useful insights:
1. Install transmission-daemon and transmission-remote  version 4.0.4
2. Add a magnet link which includes some trackers (preferably with really few seeders for slow progress)
3. Optional: Add a tracker **before** the metadata finishes downloading.
4. Only **after** the metadata download completed try to remove any of the previously defined trackers using:
```
transmission-remote --auth transmission:transmission -l (to get the torrent id X)
transmission-remote --auth transmission:transmission -t X -it (to get the tracker id Y)
transmission-remote --auth transmission:transmission -t X -tr Y (to delete the tracker)
```
5. You will get the error `Error: error setting announce list`

The reason for this error is apparently when you add a magnet link with a tracker (or add a tracker before the metadata download is complete) transmission assigns these trackers a tracker ID. Lets say there are 2 trackers and they where assigned the next 2 available IDs 34 and 35. When the metadata download is completed transmission gets the torrent file and updates a lot of things in its memory about this torrent. As part of this update, transmission reassigns the trackers new IDs so the trackers will get the **next** available IDs which are 36 and 37 (in a very simple scenario when we didn't add any new torrents or magnet links) .
**The bug is as follows**: Even though the IDs were updated internally, the command `transmission-remote --auth transmission:transmission -t X -it` still returns the **old** (now invalid) IDs 34 and 35. This obviously causes you to try and delete a tracker by its obsolete ID which will not work as this ID is invalid now.
From understanding this we get this **interesting workaround**:
You can make an educated guess about the new ID of the tracker you want to delete and try deleting using that ID. For example, even though the IDs are displayed as 34 and 35, if you didn't add any new torrent, you can understand that the next 2 available IDs are 36 and 37 so the tracker number 35 is actually number 37 now (even though it still says 35) and you can delete it by `transmission-remote --auth transmission:transmission -t X -tr 37` which will succeed! (I verified this multiple times).
**The easy workaround** though is simply pause and resume the torrent which refreshes the IDs to be the correct ones :)

**Comment by chantzish** [comment] 2023-09-01 12:19
I created a PR fixing this issue https://github.com/transmission/transmission/pull/5957

**Closed** 2023-09-04 01:40 UTC
Labels: bug, scope:core, needs confirmation
