### ISSUE TITLE
Bug in the progress bar when downloading a file

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#2243] opened 2021-11-28 14:25 UTC
- Transmission v.3.00+998d4c514b
- macOS v.12.0.1 (21A559)

<img width="664" alt="Screen Shot 2021-11-28 at 15 07 05" src="https://user-images.githubusercontent.com/62497891/143771965-359505ef-5144-4a89-875b-4ed395ae61ae.png">

**Comment by Oleg-Chashko** [comment] 2021-11-28 16:25
<img width="658" alt="Screen Shot 2021-11-28 at 17 20 32" src="https://user-images.githubusercontent.com/62497891/143776824-36156dce-0962-4589-ae8c-08e756dffc27.png">

**Comment by ckerr** [comment] 2021-11-29 01:07
I think this has the same root cause as https://github.com/transmission/transmission/issues/2245

**Comment by ckerr** [comment] 2021-11-29 14:53
Closing as a duplicate of #2245, even though the symptoms are different.

**Closed by ckerr** 2021-11-29 14:53 UTC
Labels: bug, scope:core
