### ISSUE TITLE
DHT is not working on 4.0.0 beta-1 and previous recent nightlies

### ISSUE THREAD

**Issue by FunFrog-BY** [transmission/transmission#3936] opened 2022-10-10 21:48 UTC
Hello.
For maybe a month or so DHT stopped working for me after i updated my daemon from one nightly build to another. I receive no DHT peers (judging by peers flags and active torrents amount).
DHT worked with some nightly build i've installed several months ago.

What i tried to do:
- Installing 3.00 -> DHT working again
- Deleting dht.dat -> It's not being created again on latest versions.
- Deleting dht.dat with 3.00 -> it's being created again.

I've tried to get some logs but i can't get anything with recent versions. On the contrary, version 3.00 gives me a lot in Dbgview.

My info:
- Windows 10 x64
- 200/100 Mbit connection with all ports forwarded.
- 22862 torrents
- 32 Gb of RAM, fast ssd and CPU.

I've looked for similar issues here with no luck and waited a few weeks for one to appear. Maybe it's cause of my huge amount of torrents...

**Comment by TheFalcon81** [comment] 2022-11-11 02:29
Is DHT.dat still required or is that a legacy file no longer needed?
It's not created when I run new installs of 3.0 and 4.0 Nightly Build on my Mac.

**Comment by ckerr** [comment] 2022-11-15 18:25
This issue is  possibly fixed by #4122.

> Is DHT.dat still required or is that a legacy file no longer needed?
> It's not created when I run new installs of 3.0 and 4.0 Nightly Build on my Mac.

It's used to save a good state between Transmission sessions,  but if the swarm information is poor then the information won't be saved between sessions. If it's missing after a clean install, that indicates that DHT is not finding enough peers.

Also, this happening for you in 3 indicates that this isn't a new regression in 4 :man_shrugging:

**Comment by FunFrog-BY** [comment] 2022-11-15 19:47
Wow, it's finally working! Thanks!
Tested on latest nightly build.

**Closed** 2022-11-15 20:23 UTC
Labels: needs clarification

**Comment by TheFalcon81** [comment] 2022-11-18 03:51
> This issue is possibly fixed by #4122.
> 
> > Is DHT.dat still required or is that a legacy file no longer needed?
> > It's not created when I run new installs of 3.0 and 4.0 Nightly Build on my Mac.
> 
> It's used to save a good state between Transmission sessions, but if the swarm information is poor then the information won't be saved between sessions. If it's missing after a clean install, that indicates that DHT is not finding enough peers.
> 
> Also, this happening for you in 3 indicates that this isn't a new regression in 4 🤷‍♂️

Thanks for the reply. Just an update. Looks like 3.0 created the dht.dat file a few days ago.
