### ISSUE TITLE
Resuming Torrent + Verifying seems broken

### ISSUE THREAD

**Issue by nvanfleet** [transmission/transmission#3858] opened 2022-10-01 06:17 UTC
nightly Mac: 4977c1a021

- I opened a torrent file for a file I already had the data for.
- Paused it immediately
- Told it to move data to and pointed it to the directory where the file was
- Told it to resume
Results:
- The torrent just resumed at 0% downloaded, didn't acknowledge that the data was there or anything, the download didn't even start
Then:
- I told it to verify data and then it "saw" all of the data checking through everything until the bar was full and then suddenly I was seeding it again.

I also noticed that on a multi-gig file I verified data after downloading 590kb and it actually took several minutes to verify. Maybe this is expected behavior for how that works, but it seemed rather odd. I had the 590 kb but I had actually never connected to any peer so it seems like maybe the 590 is just the torrent file itself anyway? I guess it was actually 84kb though.

**Comment by ckerr** [comment] 2022-10-02 16:37
Slightly different steps, but I think this is a duplicate of https://github.com/transmission/transmission/issues/754. tldr Transmission doesn't force-verify after the 'move' step, which is a feature when Transmission is actually moving files from folder A to B, but is kind of an antifeature when you're telling Transmission where to find the files

**Closed by ckerr** 2022-10-02 16:37 UTC
