### ISSUE TITLE
crash when "File name too long"

### ISSUE THREAD

**Issue by Dachtire** [transmission/transmission#3816] opened 2022-09-13 13:37 UTC
transmission-daemon may crash when "File name too long" error occured.
<details><summary>log</summary>
<p>

```
transmission-daemon: ERR open-files.cc:183 Couldn't open '' : File name too long (36) (transmission/source/libtransmission/open-files.cc:183)
transmission-daemon: ERR Couldn't get ''  : File name too long (36) (transmission/source/libtransmission/inout.cc:145)
systemd[1]: transmission-daemon.service: Main process exited, code=killed, status=11/SEGV
systemd[1]: transmission-daemon.service: Failed with result 'signal'.
systemd[1]: transmission-daemon.service: Consumed 13min 44.064s CPU time.
```

</p>
</details>

**Comment by Coeur** [comment] 2022-09-25 13:14
Do you happen to have a .torrent reproducing the issue? Which OS and filesystem are you using?

**Comment by Dachtire** [comment] 2022-09-26 03:15
> Do you happen to have a .torrent reproducing the issue? Which OS and filesystem are you using?

It's a torrent created on windows which is private tracker and unable to show here. I'm using linux and btrfs.

**Comment by Coeur** [comment] 2022-09-27 08:29
Well, do you have Windows (or a different bittorrent client, like qBittorrent) on which you can open the torrent and find out about the culprit filename?

**Comment by Dachtire** [comment] 2022-09-28 03:10
> Well, do you have Windows (or a different bittorrent client, like qBittorrent) on which you can open the torrent and find out about the culprit filename?

I think transmisson not handle properly and crash itself when any filename longer than the filesystem limit, what is the filename does not matter.

**Comment by ckerr** [comment] 2023-03-10 20:11
I either need a sample .torrent file (preferred; feel free to create a fake one) to reproduce this, or a backtrace showing where the crash is.

From the original log, it's not even actually clear if the crash is happening in the same part of the code where the "File name too long" error message is coming from.

**Comment by Coeur** [comment] 2023-03-11 16:22
I took a FreeBSD torrent, I renamed the file to a 300 characters long name, and I'm able to open it on macOS without a crash.
But I do get "File name too long".
[FreeBSD-300 characters long filename.torrent.zip](https://github.com/transmission/transmission/files/10948920/FreeBSD-300.characters.long.filename.torrent.zip)

I haven't tried to open it with transmission-daemon. Can someone try it and share the crash log if there is one?

**Comment by ckerr** [comment] 2023-03-11 16:49
I'll try it in daemon

**Comment by GaryElshaw** [comment] 2023-03-11 21:30
btrfs 

Max. filename length | 255 ASCII characters (fewer for multibyte character encodings such as Unicode)
-- | --


Max. filename length	255 [ASCII](https://en.wikipedia.org/wiki/ASCII) characters (fewer for multibyte [character encodings](https://en.wikipedia.org/wiki/Character_encoding) such as [Unicode](https://en.wikipedia.org/wiki/Unicode))

**Comment by ckerr** [comment] 2023-03-11 23:39
FWIW this is probably not a btrfs-specific issue. btrfs and ext3/4 all top out at 255 iirc

**Comment by ckerr** [comment] 2023-03-12 02:15
Yep I'm not seeing a crash in transmission-daemon either, with the sample torrent uploaded by @Coeur 

Closing this as a duplicate of #2311 since the crash, whatever caused it, appears to be unrelated to the filename.

@Dachtire if you're able to reproduce the crash, please do open a new issue with more info about the crash itself.

**Closed by ckerr** 2023-03-12 02:15 UTC
Labels: needs clarification, scope:core, bug:regression
