### ISSUE TITLE
Open Folder not working

### ISSUE THREAD

**Issue by celestinoxp** [transmission/transmission#4960] opened 2023-02-20 10:20 UTC
### What is the issue?

Right-click -> open folder
not working 

### Which application of Transmission?

Qt app on Windows 11 (x64)
Language: Portuguese

### Which version of Transmission?

Transmission 4.0.0-dev (c5b1df0daa)

**Comment by ckerr** [comment] 2023-02-20 15:34
Duplicate of https://github.com/transmission/transmission/issues/1978

**Closed by ckerr** 2023-02-20 15:34 UTC
Labels: scope:qt, os:windows
