### ISSUE TITLE
3.00 magnet link loop download metadata 

### ISSUE THREAD

**Issue by sparkett** [transmission/transmission#3186] opened 2022-06-03 08:21 UTC
I have a problem with torrent magnetic links created with the qBittorrent client. Transmission tries to download the metadata but goes up to 88% and comes back, in a continuous loop. I'm not the only one using Transmission who has this problem.

ES. [magnet:?xt=urn:btih:7cf4afd801b8822bb919477a4b7a890b1fba3122&xt=urn:btmh:1220c151e96283a84c6e2328a9243dc61ce096f3e29c5612d3ee19895afdf11ffa2b&dn=Come%20Vinsi%20La%20Guerra.1926&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.0x.tf:6969/announce&tr=https://trackme.theom.nz:443/announce&tr=udp://discord.heihachi.pw:6969/announce&tr=udp://fe.dealclub.de:6969/announce&tr=udp://code2chicken.nl:6969/announce&tr=udp://mail.realliferpg.de:6969/announce&tr=udp://6ahddutb1ucc3cp.ru:6969/announce&tr=udp://tracker.blacksparrowmedia.net:6969/announce&tr=http://tracker.files.fm:6969/announce](url)

**Comment by ckerr** [comment] 2022-06-04 14:53
Hey @sparkett, I'm not able to reproduce the problem with that magnet link. When I add that link, the metainfo shows up fine. So either the swarm has changed, or maybe we're running different versions of Transmission.

What version of Transmission + platform are you running on?

**Comment by sparkett** [comment] 2022-06-05 06:23
Using Transmission 3.00 (f4489c982e) on macOS 10.13.6 (High Sierra)

**Comment by ckerr** [comment] 2022-06-05 14:55
Does the problem still happen with a nightly build from https://transmissionbt.com/ ?

**Comment by Coeur** [comment] 2022-10-08 22:55
I'm not reproducing either with 4.0.0-beta.1, so I'll close this issue.
Although, different issue, that torrent has a `.pad` folder which we should probably ignore:
![Capture d’écran 2022-10-09 à 06 53 56](https://user-images.githubusercontent.com/839992/194730499-05aa03d8-c161-420f-b5e6-a4f70613793f.png)

**Closed by Coeur** 2022-10-08 22:55 UTC
Labels: needs clarification
