### ISSUE TITLE
Message Log does not open in transmission-qt

### ISSUE THREAD

**Issue by fredo-47** [transmission/transmission#4386] opened 2022-12-17 10:19 UTC
### What is the issue?

In transmission-qt the message log is only accessible from its tray icon via right-click context menu.
(This is in contrast to transmission-gtk, where the message log is accessible from the normal menu bar)

![t-qt_message-log](https://user-images.githubusercontent.com/30537162/208236812-3c4bb036-a43e-481f-be1b-25ed370192b3.png)

However, when I click on that entry, nothing happens, i.e. the message log does not open.

Linux Mint 21 Cinnamon

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

Transmission 4.0.0-beta.2.dev (5d5893036d)

**Comment by ckerr** [comment] 2022-12-24 00:51
Duplicate of #3773

**Closed by ckerr** 2022-12-24 00:51 UTC
Labels: scope:qt, feature disparity
