### ISSUE TITLE
Transmission crashes with assertion failed

### ISSUE THREAD

**Issue by mecowell** [transmission/transmission#4870] opened 2023-02-13 19:55 UTC
### What is the issue?

On Ubuntu 22.10, transmission closes after a few minutes. I was able to see this error:

assertion failed: s->leftUntilDone <= s->sizeWhenDone (./libtransmission/torrent.cc:1643)
Aborted

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.0 (280ace12f8)

**Comment by ckerr** [comment] 2023-02-13 20:15
@mecowell thanks for reporting this! This confirms what was guessed in https://github.com/transmission/transmission/issues/4695 that reported an assertion failure but not which specific assertion.

I'm going to close this as a duplicate of 4695 but I apprecate the report!

**Closed by ckerr** 2023-02-13 20:15 UTC
