### ISSUE TITLE
Bug - Files deselected for download also gets preallocated

### ISSUE THREAD

**Issue by o-l-a-v** [transmission/transmission#1091] opened 2020-01-04 10:33 UTC
Running Transmission 2.94 on Ubuntu 18.04 (PeppermintOS 10) from official PPA.

Transmission preallocates space even for files deselected for download in a torrent. In my case it fills up gigabytes of data, and makes my disk go full.

Please make it so that files in a torrent not marked for download does not get preallocated, at least not 100% of the file size.

Also, I see no options for preallocation behavior inside Transmission. My preferred behavior is not to preallocate, but grow the file size as data gets downloaded.

**Comment by rmbleeker** [comment] 2020-05-25 11:40
> Also, I see no options for preallocation behavior inside Transmission. My preferred behavior is not to preallocate, but grow the file size as data gets downloaded.

In the settings.json file there is an option `preallocation` which has three options: 

- 0 = no preallocation
- 1 = fast (probably makes a sparse file), the default
- 2 = full

You can also find it in the [documentation](https://github.com/transmission/transmission/wiki/Editing-Configuration-Files#files-and-locations)

**Comment by o-l-a-v** [comment] 2020-05-25 11:54
> > Also, I see no options for preallocation behavior inside Transmission. My preferred behavior is not to preallocate, but grow the file size as data gets downloaded.
> 
> In the settings.json file there is an option `preallocation` which has three options:
> 
> * 0 = no preallocation
> * 1 = fast (probably makes a sparse file), the default
> * 2 = full
> 
> You can also find it in the [documentation](https://github.com/transmission/transmission/wiki/Editing-Configuration-Files#files-and-locations)

Thanks. That setting should be exposed in the GUI IMO. If fast is default, well, Transmission preallocates the whole thing (full), so, a bug? I haven't touched those settings.

**Comment by rmbleeker** [comment] 2020-05-25 12:32
Could be a bug, it could also be that the package maintainer for whatever distro you're using chose a different setting in the provided `settings.json`. You can check this by manually downloading the package, unpack it and examine the `settings.json` inside.

**Comment by ckerr** [comment] 2022-02-22 18:38
Duplicate of #290

**Closed** 2022-02-22 21:03 UTC
Labels: duplicate
