### ISSUE TITLE
xdotool: XGetWindowProperty[_NET_WM_DESKTOP] failed

### ISSUE THREAD

**Issue by sebastian-65** [transmission/transmission#5158] opened 2023-03-05 19:46 UTC
### What is the issue?

**Expected behaviour (worked on transmission-gtk 3.00)**

window=$(xdotool search --desktop 0 --name "Transmission" | tail -n 1) # get transmission window ID
xdotool windowunmap $window # hiding the application
xdotool windowactivate $window # unhide the application

**Current behaviour**

After transmission-gtk upgrade from 3.00 to 4.0.1-2:

xdotool windowunmap $window # hiding works
xdotool windowactivate $window # unhide returns an error:

`XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)`

----

Did something change that might have caused this issue?

Updated Arch linux, XFCE.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.1-2

**Comment by ckerr** [comment] 2023-03-05 20:42
Hey @sebastian-65 thanks for reporting this.

I think this is a duplicate of https://github.com/transmission/transmission/issues/5067 so I'm closing this one as a dupe. If this is wrong please reopen this or file a new ticket. Thanks!

**Closed by ckerr** 2023-03-05 20:42 UTC

**Comment by mikedld** [comment] 2023-03-07 22:06
Not necessarily related to the linked issue. The `xdotool search --desktop 0 --name "Transmission"` command gives different output when GTK client is built against GTK 3 vs. GTK 4 (but both contain at least one ID that's correct and can be used with other xdotool commands), and retrieving the last element from that list feels sketchy. The ordering also seems to depend on which window was last activated, plus you're searching by window title which may include unrelated windows too.

So... Maybe find a better way to get the window ID you need.

**Comment by mikedld** [comment] 2023-03-07 22:11
I'd even say that the linked issue is definitey unrelated since it's dealing with Wayland which is not something xdotool supports, being a X11 tool. Still, I don't believe this here is a valid Transmission issue, so I support it being closed.
