### ISSUE TITLE
Upload ratio gets calculated wrong in certain case

### ISSUE THREAD

**Issue by rene-s** [transmission/transmission#2119] opened 2021-11-08 14:06 UTC
Hi there, thanks for developing and providing Transmission. 

The upload ratio seems to get calculated wrong in a certain edge case. This is what I have done:

1. Downloaded Tails torrent files for ISO and IMG.
2. Started both and have it run for a few seconds in order to fetch  their sig files.
3. Stopped both torrents, deleted the `.part` files and copied trusted and verified ISO and IMG files that I had downloaded earlier in their place. The checksums match.
4. Had Transmission check the local files.
5. Started both torrents again (the goal was to start seeding).

As you can see in the attached screenshot, the ratio *seems* to get calculated based on the sig files alone, which sizes are just a few KBs.
![transmission_2021-11-08_14-56](https://user-images.githubusercontent.com/1558400/140755864-685077f3-381b-49c6-8e71-058f59b0eb80.png)

(The first ratio is wrong because 378 MB is not 64.8 times of 1.19 GB, the second is wrong because 51.98 MB is not 21.7 times of 1.18 GB)

**Comment by ckerr** [comment] 2021-11-24 21:00
Duplicate of https://github.com/transmission/transmission/issues/276

**Closed by ckerr** 2021-11-24 21:00 UTC
