### ISSUE TITLE
Incomplete torrent (feature request)

### ISSUE THREAD

**Issue by SNBogdanov** [transmission/transmission#5359] opened 2023-04-07 13:17 UTC
### What is the issue?

In my installation I xonfigured incomplete directory. This works correctly for fully downloaded torrents.
But if I checked only few files when they are completed all torrent moves to download directory. 
I want incomplete files remain in incomplete directory.
Even more. After partial download transmission creates new incomplete files not in Incomplete directory, but in download directory.
The only way to move them back is sotp transmission, move files, start transmission and recheck torrent.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.2

**Comment by ckerr** [comment] 2023-04-08 01:45
Duplicate of https://github.com/transmission/transmission/issues/1014

**Closed by ckerr** 2023-04-08 01:45 UTC

**Comment by SNBogdanov** [comment] 2023-04-08 03:02
My bug deal with incomplete file creation, not moving them to final destination.
