### ISSUE TITLE
Filter 

### ISSUE THREAD

**Issue by CyberSkull** [transmission/transmission#6536] opened 2024-01-17 10:43 UTC
### What is the issue?

The filter bar contents keep vanishing on Transmission 4.0.5 (a6fe2a64aa) on macOS 14.2.1. I suspect it happens when the light/dark transition occurs.

<img width="980" alt="Screenshot 2024-01-17 at 2 34 00 AM" src="https://github.com/transmission/transmission/assets/201815/0abbd16b-7797-466e-9e42-51c2fcbf4bc8">

This is the top of the window when I noticed it.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.5 (a6fe2a64aa)

**Comment by Coeur** [comment] 2024-01-17 11:26
Duplicate of #3400.
Although for me it was without switching light/dark. How do you switch theme? Based on time of the day?

**Closed** 2024-03-23 07:49 UTC
Labels: duplicate, os:mac
