### ISSUE TITLE
Could the names of the downloaded torrents named by its real names?

### ISSUE THREAD

**Issue by cool98eng** [transmission/transmission#3081] opened 2022-05-14 09:50 UTC
Could the names of the downloaded torrents named by its real names but not the 40 -digital verifying name?

**Comment by ckerr** [comment] 2022-05-14 14:10
Duplicate of https://github.com/transmission/transmission/issues/2988

**Closed by ckerr** 2022-05-14 14:10 UTC

**Comment by dchmelik** [comment] 2022-08-23 08:01
Sometimes people switch torrent clients which is part _why_ the claim users don't use torrent files is absolute nonsense.
